src/objects/App_Properties__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Generic Name value pair, can be utilized for any application.</description>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of the property</description>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <description>Value of the property</description>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>App Properties</label>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Supervisory_Status__c</fullName>
        <description>Populated based on same field on corresponding User record by Federation Identifier.</description>
        <label>Supervisory Status</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>GSA</fullName>
        <active>true</active>
        <description>This contact record is used to track information for GSA employees.</description>
        <label>GSA</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/EmailTracker__c.object
<CustomObject>
    <description>Object to store the email reminders for the Contact Manager VOE OHRM Surveys i.e. Hiring manager, Supervisor, etc</description>
    <fields>
        <fullName>Purpose__c</fullName>
        <label>Purpose</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Initial Send</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Reminder</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the email, Pending or Responded.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Queued</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Responded</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ToContact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Contact Recipient</description>
        <label>To Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Email Trackers</relationshipLabel>
        <relationshipName>Email_Trackers</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Options are 1-1 with Survey Master Record Names</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>VOE - Hiring Manager Survey</fullName>
                </value>
                <value>
                    <fullName>VOE - New Supervisor Survey</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Email Tracker</label>
    <nameField>
        <displayFormat>ET-{00000000}</displayFormat>
        <label>Email Tracking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Trackers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ContactTriggerHelperTest.cls
/**
 * Test coverage for Acumen Solutions's development on the ContactTriggers.trigger and ContactHelper.cls
 * @author Justin Lyon
 * @created 09.24.2015
 */
@isTest
private class ContactTriggerHelperTest {
	static final String QUEUED = 'Queued';
	static final String INITIAL_SEND = 'Initial Send';
	static final String NEW_SUPERVISOR_SURVEY = 'VOE - New Supervisor Survey';
    
	@TestSetup static void setup() {
		Id accountRtId = [SELECT Id FROM RecordType WHERE SObjectType = 'Account' AND Name = 'GSA Organization'].Id;
		Id userProfileId = [SELECT Id FROM Profile WHERE Name = 'GSA Standard Salesforce User'].Id;

		Account testAccount = TestUtil.buildAccount('testAccount', accountRtId);
		insert testAccount;
        
        //GSAAccountId
        App_Properties__c appPropertyAccountSetting = new App_Properties__c();
        appPropertyAccountSetting.Name = 'GSA Account Id';
		appPropertyAccountSetting.Type__c = 'GSAAccountId';
        appPropertyAccountSetting.Value__c = testAccount.id;
		insert appPropertyAccountSetting;
        
		List<User> testUsers = new List<User>();
		for(Integer i = 1; i < 4; i++) {
			testUsers.add(TestUtil.buildUser(i, userProfileId, 'testContact' + i + '@fake.com'));
		}

        
        App_Properties__c appPropertyContactSetting = new App_Properties__c();
        appPropertyContactSetting.Name = 'Contact Record Type for GSA';
		appPropertyContactSetting.Type__c = 'GSAContactRecordTypeId';
        appPropertyContactSetting.Value__c = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('GSA').getRecordTypeId();
		insert appPropertyContactSetting;        

        App_Properties__c appPropertyProfileSetting = new App_Properties__c();
        appPropertyProfileSetting.Name = 'GSA Standard Platform User';
		appPropertyProfileSetting.Type__c = 'ContactSyncProfile';
        appPropertyProfileSetting.Value__c = 'GSA Standard Platform User';
		insert appPropertyProfileSetting;        
        
		// By-pass User Trigger
		//////PublicUserGroupHandler.disableGroupMemberRecalculation = true;
		//PublicUserGroupHandler.disableGroupMemberRecalculation = true;
		insert testUsers;

		//System.assert(PublicUserGroupHandler.disableGroupMemberRecalculation);
		System.assert(!testUsers.isEmpty());
	}

	static TestMethod void testCatchNewSupervisors_afterUpdate() {
		Id contactRtId = [SELECT Id FROM RecordType WHERE SObjectType = 'Contact' AND Name = 'GSA'].Id;

		Account testAccount = [SELECT Id FROM Account LIMIT 1];
		List<User> testUsers = [SELECT FirstName, LastName, Email, FederationIdentifier FROM User WHERE Email LIKE '%@fake.com'];

		List<Contact> testContacts = new List<Contact>();
		for(User u : testUsers) {
			Contact tempContact = TestUtil.buildContactByUser(u, contactRtId, testAccount.Id);
			tempContact.Supervisory_Status__c = 1;
			testContacts.add(tempContact);
		}
		insert testContacts;

		for(Contact c : testContacts) {
			c.Supervisory_Status__c = 2;
		}

		Test.startTest();

			update testContacts;

		Test.stopTest();

		List<EmailTracker__c> afterUpdateEmailTrackers = [SELECT Type__c, Status__c, Purpose__c, ToContact__c FROM EmailTracker__c];
		System.assertEquals(3, afterUpdateEmailTrackers.size());
		for(EmailTracker__c emt : afterUpdateEmailTrackers) {
			System.assertEquals(QUEUED, emt.Status__c);
			System.assertEquals(INITIAL_SEND, emt.Purpose__c);
			System.assertEquals(NEW_SUPERVISOR_SURVEY, emt.Type__c);
		}
	}

	static TestMethod void testCatchNewSupervisors_afterInsert() {
		Id contactRtId = [SELECT Id FROM RecordType WHERE SObjectType = 'Contact' AND Name = 'GSA'].Id;

		Account testAccount = [SELECT Id FROM Account LIMIT 1];
		List<User> testUsers = [SELECT FirstName, LastName, Email, FederationIdentifier FROM User WHERE Email LIKE '%@fake.com'];

		List<Contact> testContacts = new List<Contact>();
		for(User u : testUsers) {
			Contact tempContact = TestUtil.buildContactByUser(u, contactRtId, testAccount.Id);
			tempContact.Supervisory_Status__c = 2;
			testContacts.add(tempContact);
		}

		Test.startTest();

			insert testContacts;

		Test.stopTest();

		List<EmailTracker__c> afterInsertEmailTrackers = [SELECT Type__c, Status__c, Purpose__c, ToContact__c FROM EmailTracker__c];
		System.assertEquals(3, afterInsertEmailTrackers.size());
		for(EmailTracker__c emt : afterInsertEmailTrackers) {
			System.assertEquals(QUEUED, emt.Status__c);
			System.assertEquals(INITIAL_SEND, emt.Purpose__c);
			System.assertEquals(NEW_SUPERVISOR_SURVEY, emt.Type__c);
		}
	}
}