src/objects/Application__c.object
<CustomObject>
    <description>This object will hold all Application records.</description>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Application_Function__c.object
<CustomObject>
    <description>This object is for the Project Central - Application Registry application and supports the &quot;Application&quot; object.  This object tracks the various functions available in an application.</description>
    <label>Application Function</label>
    <nameField>
        <label>Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Functions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Application_Version__c.object
<CustomObject>
    <description>This object is for the Project Central - Application Registry application and supports the &quot;Application&quot; object. This object tracks the different versions of an application.</description>
    <fields>
        <fullName>Application_Name__c</fullName>
        <formula>Application__r.Name__c</formula>
        <label>Application Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application ID</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Versions</relationshipLabel>
        <relationshipName>Application_Versions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Point_of_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business POC</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Versions1</relationshipLabel>
        <relationshipName>Versions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Development</fullName>
                </value>
                <value>
                    <fullName>Ready For Deployment</fullName>
                </value>
                <value>
                    <fullName>Operational</fullName>
                </value>
                <value>
                    <fullName>Sunset Planned</fullName>
                </value>
                <value>
                    <fullName>Sunsetted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Version</label>
    <nameField>
        <displayFormat>AV-{0000000}</displayFormat>
        <label>Application Version ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Included_Function__c.object
<CustomObject>
    <description>This object is for the Project Central - Application Registry application and supports the &quot;Application&quot; object. This object tracks the functions each application has.</description>
    <fields>
        <fullName>Application_Function__c</fullName>
        <description>To view all Application Functions, Click on the Application Functions tab above</description>
        <inlineHelpText>To view all Application Functions, Right Click on the Application Functions tab above and Open in a New Tab</inlineHelpText>
        <label>Application Function</label>
        <referenceTo>Application_Function__c</referenceTo>
        <relationshipLabel>Included Functions</relationshipLabel>
        <relationshipName>Application_Version_Functions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Application_Name__c</fullName>
        <formula>HYPERLINK(Application_Version__r.Application__r.Id,Application_Version__r.Application__r.Name__c,&quot;_self&quot;)</formula>
        <label>Application Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Application_Version__c</fullName>
        <label>Application Version</label>
        <referenceTo>Application_Version__c</referenceTo>
        <relationshipName>Application_Version_Functions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Included Function</label>
    <nameField>
        <displayFormat>AVF-{0000000}</displayFormat>
        <label>Included Function ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Included Functions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Point_of_Contact__c.object
<CustomObject>
    <label>Point of Contact</label>
    <nameField>
        <displayFormat>POC{0000000}</displayFormat>
        <label>Point of Contact Identifier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Point of Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AppRegistrySearchController.cls
/**
 * The AppRegistrySearchController searches for applications with specified characteristics.
 * 
 * Revision History
 *
 * 09/20/2011   DRH - Created.
 * 09/21/2011   DRH - Implemented the advancedSearch() method.
 * 09/27/2011   DRH - Fixed bugs in Included_Function__c queries.
 * 09/29/2011   DRH - Replaceded SOQL Where Like Statements With SOSL statements.
 * 10/03/2011   DRH - Consolidated standard text and advanced search search.
 * 10/05/2011   DRH - Refined the invalidSearchParameters() method.
 * 11/15/2011   DBP - Added filtering by Point of Contact.
 */
public with sharing class AppRegistrySearchController {

	public List<SelectOption> appTypeOptions {get;set;}
	public List<SelectOption> functionTypeOptions {get;set;}
	public List<SelectOption> stateOptions {get;set;}

	public List<Application_Version__c> appVersionList {get;set;}
	public Application_Version__c appVersionPOC{get;set;}

	public String keyWordInput {get;set;}
	public String appType {get;set;}
	public String functionType {get;set;}
	public String state {get;set;}

	private Set<Id> appSet = new Set<Id>();
	private Set<Id> appVersionSet = new Set<Id>();

	private Boolean textSearchRequired = false;

	public AppRegistrySearchController() {
		setAppTypeOptions();
		setFunctionTypeOptions();
		setStateOptions();
		appVersionPOC = new Application_Version__c();
	}

	public void search() {
		System.debug('\n\n>> AppRegistrySearchController.search()');
		
		if (invalidSearchParameters()) {
			ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.ERROR, 'Your search term must have 2 or more characters.');
			ApexPages.addMessage(msg);
			return;
		}

		if (textSearchRequired) {
			searchForKeyWords();

			// retrieve list of Application_Version__c matches
			appVersionList = [SELECT av.Application__c, av.Application_Name__c, av.Application__r.Type__c, av.Application__r.Description_Abbrev__c,
									 av.Id, av.Version__c, av.State__c, av.Point_of_Contact__r.Name,
							 (SELECT avf.application_function__c From Application_Version_Functions__r avf)
								FROM Application_Version__c av
							   WHERE av.Application__c In :appSet
								  OR av.Id In :appVersionSet];
		}
		else {
			// retrieve list of Application_Version__c matches
			appVersionList = [SELECT av.Application__c, av.Application_Name__c, av.Application__r.Type__c, av.Application__r.Description_Abbrev__c,
									 av.Id, av.Version__c, av.State__c, av.Point_of_Contact__r.Name,
							 (SELECT avf.application_function__c From Application_Version_Functions__r avf)
								FROM Application_Version__c av where av.isDeleted = false];
		}

		if (appType != null) {
			Integer items = appVersionList.size();

			for (Integer i=items; i>0; i--) {
				Integer index = i-1;

				Application_Version__c appVersion = appVersionList.get(index);

				if (appVersion.Application__r.Type__c != appType) {
					appVersionList.remove(index);
				}
			}
System.debug('\n\n>> AppRegistrySearchController.search() - appType: ' + appType);
		}

		if (functionType != null) {
			Integer items = appVersionList.size();

			for (Integer i=items; i>0; i--) {
				Integer index = i-1;

				Application_Version__c appVersion = appVersionList.get(index);

				List<Included_Function__c> incFunctionList = appVersion.Application_Version_Functions__r;

				Boolean noMatches = true;

				if (incFunctionList.size() > 0) {
					
					for (Included_Function__c incFunction : incFunctionList) {
						if (incFunction.Application_Function__c == functionType) {
							noMatches = false;
							break;
						}
					}
				}
				if (noMatches) {
					appVersionList.remove(index);				   
				}
			}
System.debug('\n\n>> AppRegistrySearchController.search() - functionType: ' + functionType);
		}

		if (state != null) {
			Integer items = appVersionList.size();

			for (Integer i=items; i>0; i--) {
				Integer index = i-1;

				Application_Version__c appVersion = appVersionList.get(index);

				if (appVersion.State__c != state) {
					appVersionList.remove(index);
				}
			}
System.debug('\n\n>> AppRegistrySearchController.search() - state: ' + state);
		}
		
		if (appVersionPOC.Point_of_Contact__c != null)
		{
			integer i = 0;
			while (i < appVersionList.size())
			{
				if (appVersionList.get(i).Point_Of_Contact__c != appVersionPOC.Point_Of_Contact__c)
				{
					appVersionList.remove(i);
				}else
				{
					i++;
				}
			}
		}

		//return null;
	}

	private Boolean invalidSearchParameters() {
		Boolean invalid = true;

		textSearchRequired = false;

		if (appType != null || functionType != null || state != null || appVersionPOC.Point_Of_Contact__c != null) {
			invalid = false;
		}
		if (keywordInput != null && keywordInput.trim().length() > 0) {
			String prefix = keywordInput;

			while (prefix.length() > 1 && prefix.endsWith('*')) {
				Integer index = prefix.length() - 1;
				prefix = prefix.substring(0, index);
			}
			if (prefix.length() > 1) {
				textSearchRequired = true;

				invalid = false;
			}
			else {
				invalid = true;
			}
		}
		return invalid;
	}

	private void searchForKeyWords() {

		// clear the previous results
		appSet.clear();
		appVersionSet.clear();

System.debug('\n\n>> AppRegistrySearchController.searchForKeyWords() - keyWordInput: ' + keyWordInput);

		List<List<SObject>> searchList = [FIND :keyWordInput IN ALL FIELDS RETURNING Application__c (id), Application_Version__c (id), Application_Function__c (id)];
System.debug('\n\n>> AppRegistrySearchController.search() - searchList.size() - ' + searchList.size());

		List<Application__c> appList = searchList.get(0);

		for (Application__c app : appList){
System.debug('\n\n>> AppRegistrySearchController.advancedSearchForKeyWords() - appSet: ' + app.id);
			appSet.add(app.id);
		}

		List<Application_Version__c> appVersionList = searchList.get(1);

		for (Application_Version__c appVersion : appVersionList) {
System.debug('\n\n>> AppRegistrySearchController.advancedSearchForKeyWords(1) - appVerionSet: ' + appVersion.id);
			appVersionSet.add(appVersion.id);
		}

		Set<Id> appFunctionSet = new Set<Id>();

		List<Application_Function__c> appFunctionList = searchList.get(2);

		for (Application_Function__c appFUnction : appFunctionList) {
			appFunctionSet.add(appFunction.id);
		}

		List<Included_Function__c> incFunctionList = [Select i.Application_Version__c
														From Included_Function__c i
													   Where i.Application_Function__c In :appFunctionSet];

		for (Included_Function__c includedFunction : incFunctionList) {
System.debug('\n\n>> AppRegistrySearchController.advancedSearchForKeyWords(2) - appVerionSet: ' + includedFunction.Application_Version__c);
			appVersionSet.add(includedFunction.Application_Version__c);
		}
	}

	private void setAppTypeOptions() {
		appType = '';
		appTypeOptions = new List<SelectOption>();

		appTypeOptions.add(new SelectOption('', 'Select...'));

		Schema.DescribeFieldResult fieldDescribe = Application__c.Type__c.getDescribe();
		List<Schema.PicklistEntry> picklistValues = fieldDescribe.getPicklistValues();

		for (Schema.PicklistEntry picklistValue : picklistValues) {
			appTypeOptions.add(new SelectOption(picklistValue.getValue(), picklistValue.getLabel()));
		}
	}

	private void setFunctionTypeOptions() {
		functionType = '';
		functionTypeOptions = new List<SelectOption>();

		List<Application_Function__c> functionTypeList = [Select af.Id, af.Name
															From Application_Function__c af
															Where af.isDeleted = false
														   Order By af.Name];
							 //SD 0927 Added isDeleted = false clause to include where clause
		functionTypeOptions.add(new SelectOption('', 'Select...'));

		for (Application_Function__c functionType : functionTypeList) {
			SelectOption option = new SelectOption(functionType.Id, functionType.Name);
			functionTypeOptions.add(option);
		}
	}

	private void setStateOptions() {
		state = 'Operational';
		stateOptions = new List<SelectOption>();

		stateOptions.add(new SelectOption('', 'Select...'));

		Schema.DescribeFieldResult fieldDescribe = Application_Version__c.State__c.getDescribe();
		List<Schema.PicklistEntry> picklistValues = fieldDescribe.getPicklistValues();

		for (Schema.PicklistEntry picklistValue : picklistValues) {
			stateOptions.add(new SelectOption(picklistValue.getValue(), picklistValue.getLabel()));
		}
	}
}