src/objects/Approval_Step__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Approver assigned to this Approval Step.</description>
        <inlineHelpText>The Approver assigned to this Approval Step.</inlineHelpText>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Approval_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Correspondence_Document__c</fullName>
        <description>The Controlled Document on which this Approval Step is listed.</description>
        <inlineHelpText>The Controlled Document on which this Approval Step is listed.</inlineHelpText>
        <label>Controlled Document</label>
        <referenceTo>Controlled_Document__c</referenceTo>
        <relationshipLabel>Approval Steps</relationshipLabel>
        <relationshipName>Approval_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <description>The date this Approval Step is due.</description>
        <inlineHelpText>The date this Approval Step is due.</inlineHelpText>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Office__c</fullName>
        <description>The Service/Staff Office of the Approver.</description>
        <inlineHelpText>The Service/Staff Office of the Approver.</inlineHelpText>
        <label>Approver&apos;s Service/Staff Office</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>A - Office of the Administrator</fullName>
                </value>
                <value>
                    <fullName>AK - Office of Civil Rights</fullName>
                </value>
                <value>
                    <fullName>B - Office of the Chief Financial Officer</fullName>
                </value>
                <value>
                    <fullName>C - Office of Human Resource Management</fullName>
                </value>
                <value>
                    <fullName>D - Office of Mission Assurance</fullName>
                </value>
                <value>
                    <fullName>E - Office of Small Business Utilization</fullName>
                </value>
                <value>
                    <fullName>G - Civilian Board of Contract Appeals</fullName>
                </value>
                <value>
                    <fullName>H - Office of Administrative Services</fullName>
                </value>
                <value>
                    <fullName>I - Office of the GSA IT</fullName>
                </value>
                <value>
                    <fullName>J - Office of the Inspector General</fullName>
                </value>
                <value>
                    <fullName>L - Office of the General Counsel</fullName>
                </value>
                <value>
                    <fullName>M - Office of Governmentwide Policy</fullName>
                </value>
                <value>
                    <fullName>O - Office of Customer Experience</fullName>
                </value>
                <value>
                    <fullName>P - Public Buildings Service</fullName>
                </value>
                <value>
                    <fullName>Q - Federal Acquisition Service</fullName>
                </value>
                <value>
                    <fullName>S - Office of Congressional and Intergovernmental Affairs</fullName>
                </value>
                <value>
                    <fullName>T - Technology Transformation Service</fullName>
                </value>
                <value>
                    <fullName>Y - Federal Permitting Improvement Steering Council</fullName>
                </value>
                <value>
                    <fullName>Z - Office of Strategic Communication</fullName>
                </value>
                <value>
                    <fullName>Region 1A</fullName>
                </value>
                <value>
                    <fullName>Region 1P</fullName>
                </value>
                <value>
                    <fullName>Region 1Q</fullName>
                </value>
                <value>
                    <fullName>Region 2A</fullName>
                </value>
                <value>
                    <fullName>Region 2P</fullName>
                </value>
                <value>
                    <fullName>Region 2Q</fullName>
                </value>
                <value>
                    <fullName>Region 3A</fullName>
                </value>
                <value>
                    <fullName>Region 3P</fullName>
                </value>
                <value>
                    <fullName>Region 3Q</fullName>
                </value>
                <value>
                    <fullName>Region 4A</fullName>
                </value>
                <value>
                    <fullName>Region 4P</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Role_of_Approver__c</fullName>
        <description>The role the Approver is playing for this Approval Step.</description>
        <inlineHelpText>The role the Approver is playing for this Approval Step.</inlineHelpText>
        <label>Role of Approver</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approver</fullName>
                </value>
                <value>
                    <fullName>Audit Analyst</fullName>
                </value>
                <value>
                    <fullName>Close-Out</fullName>
                </value>
                <value>
                    <fullName>Drafter</fullName>
                </value>
                <value>
                    <fullName>Editor</fullName>
                </value>
                <value>
                    <fullName>Exec Sec Reviewer</fullName>
                </value>
                <value>
                    <fullName>External Review</fullName>
                </value>
                <value>
                    <fullName>FYI</fullName>
                </value>
                <value>
                    <fullName>Office POC</fullName>
                </value>
                <value>
                    <fullName>Signatory</fullName>
                </value>
                <value>
                    <fullName>Subject Matter Expert</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <description>The order in which this Approval Step will appear on the Controlled Document record.</description>
        <inlineHelpText>The order in which this Approval Step will appear on the Controlled Document record.</inlineHelpText>
        <label>Sequence</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Approval Step</label>
    <nameField>
        <displayFormat>CC-Step{0000000}</displayFormat>
        <label>Approval Step ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Collaboration_Trigger_Control__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Disable_Collaboration_Triggers__c</fullName>
        <defaultValue>true</defaultValue>
        <description>When selected, this field prevents the ChatterFileCollaboratorTH class from executing any logic via triggers.</description>
        <label>Disable Collaboration Triggers</label>
        <type>Checkbox</type>
    </fields>
    <label>Collaboration Trigger Control</label>
</CustomObject>

src/objects/Controlled_Document__c.object
<CustomObject>
    <fields>
        <fullName>Due_Date__c</fullName>
        <description>The due date for the final signer.</description>
        <inlineHelpText>The due date for the final signer.</inlineHelpText>
        <label>Requested Due Date - Signer</label>
        <type>Date</type>
    </fields>
    <label>Controlled Document</label>
    <nameField>
        <displayFormat>CC{000000}</displayFormat>
        <label>Document ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Controlled Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ControlledDocumentTestUtility.cls
/*-------------------------------------------------------------------------------------------------*
  ControlledDocumentTestUtility
  -Static methods for use in test classes related to the Controlled Document functionality.
 *-------------------------------------------------------------------------------------------------*
  Author           | Date        | Version | Description
 *-------------------------------------------------------------------------------------------------*
  Stefan Maurer      10/31/2014    1.0       Created
 *-------------------------------------------------------------------------------------------------*/
 public class ControlledDocumentTestUtility {
	public static void createRequiredChatterGroups(){
		List<CollaborationGroup> newGroups = new List<CollaborationGroup>();
		if([SELECT id FROM CollaborationGroup WHERE Name = 'Chatter Support and Training'].size() == 0){
			newGroups.add(new CollaborationGroup(Name = 'Chatter Support and Training', CollaborationType='Public', OwnerId = UserInfo.getUserId()));
		}
		if([SELECT id FROM CollaborationGroup WHERE Name = 'GSA Central'].size() == 0){
			newGroups.add(new CollaborationGroup(Name = 'GSA Central', CollaborationType='Public', OwnerId = UserInfo.getUserId()));
		}

		insert newGroups;
	}

	public static Controlled_Document__c createTestControlDoc(){
		return new Controlled_Document__c();
	}

	public static Approval_Step__c createApprovalStep(Id ControlDocId, String sequenceNum, Id approverUserid){
		Approval_Step__c testStep = new Approval_Step__c(Correspondence_Document__c = ControlDocId,
		                                                 Sequence__c = sequenceNum,
		                                                 Assigned_Approver__c = approverUserId);
		return setApprovalStepRequiredFields(testStep);
	}

	public static Approval_Step__c setApprovalStepRequiredFields(Approval_Step__c approvalStep){
		approvalStep.Office__c = 'A - Office of the Administrator';
		approvalStep.Due_Date__c = System.today().addDays(7);
		approvalStep.Role_of_Approver__c = 'Approver';
		return approvalStep;
	}

	public static Approval_Step__c setApprovalStepRequiredFields(Approval_Step__c approvalStep, String sequenceNum, Id approverUserId){
		approvalStep.Sequence__c = sequenceNum;
		approvalStep.Assigned_Approver__c = approverUserId;
		approvalStep.Office__c = 'A - Office of the Administrator';
		approvalStep.Due_Date__c = System.today().addDays(7);
		approvalStep.Role_of_Approver__c = 'Approver';
		return approvalStep;
	}

	public static void initiateApprovalStep(Id approvalStepId){
		Approval.ProcessSubmitRequest submitRequest = new Approval.ProcessSubmitRequest();
		submitRequest.setObjectId(approvalStepId);
		submitRequest.setSubmitterId(UserInfo.getUserId());
		Approval.process(submitRequest);
	}

	public static void recallApprovalStep(Id approvalStep){
		Approval.ProcessWorkItemRequest recallRequest = new Approval.ProcessWorkItemRequest();
		recallRequest.setWorkItemId(getProcessWorkItem(approvalStep).get(0).Id);
		recallRequest.setAction('Removed');
		Approval.process(recallRequest);
	}

	public static void approveApprovalStep(Id approvalStep){
		Approval.ProcessWorkItemRequest recallRequest = new Approval.ProcessWorkItemRequest();
		recallRequest.setWorkItemId(getProcessWorkItem(approvalStep).get(0).Id);
		recallRequest.setAction('Approve');
		Approval.process(recallRequest);
	}

	public static FeedItem createFeedItem(Id controlDocumentId){
		return new FeedItem(ParentId = controlDocumentId,
		                    Type = 'ContentPost',
		                    ContentFileName = 'Test',
		                    ContentData = Blob.valueOf('1'));
	}

	public static void insertCollaborationTriggerControl(Boolean status){
		if(Collaboration_Trigger_Control__c.getall().values().size() == 0){
			insert new Collaboration_Trigger_Control__c(Name = 'TestControl',
				                                        Disable_Collaboration_Triggers__c = status);
		}
		else{
			Collaboration_Trigger_Control__c control = Collaboration_Trigger_Control__c.getall().values().get(0);
			control.Disable_Collaboration_Triggers__c = status;
			update control;
		}
	}

	public static Approval_Step__c getApprovalStep(Id approvalStepId){
		return [SELECT Correspondence_Document__c, Sequence__c, Assigned_Approver__c, 
		               Office__c, Due_Date__c, Role_of_Approver__c, LastModifiedById
		        FROM   Approval_Step__c
		        WHERE  id =: approvalStepId];
	}

	public static Controlled_Document__c getControlledDocument(Id controlledDocumentId){
		return [SELECT LastModifiedById
		        FROM   Controlled_Document__c
		        WHERE  Id =: controlledDocumentId];
	}

	public static List<ProcessInstanceWorkItem> getProcessWorkItem(Id approvalStepId){
		return [SELECT ProcessInstance.TargetObjectId
		        FROM ProcessInstanceWorkItem 
		        WHERE ProcessInstance.Status = 'Pending' AND 
		              ProcessInstance.TargetObjectId =: approvalStepId];
	}

	public static List<User> getStandardUsers(Integer lim){
		return [SELECT id 
		        FROM   User 
		        WHERE  ProfileId =: getProfileByName('GSA Standard Platform User').Id AND 
		               isActive = true AND
		               UserType = 'Standard'
		        LIMIT: lim];
	}

	public static List<User> getStandardUsersWithDelegatedApprovers(Integer lim){
		return [SELECT Id
				FROM User
				WHERE ProfileId =: getProfileByName('GSA Standard Platform User').Id AND 
		               isActive = true AND
		               UserType = 'Standard'
		               AND DelegatedApproverId != null
		        LIMIT: lim];
	}

	public static User getDelegateOfUser(Id userId){
		return [SELECT Id
				FROM User
				WHERE Id = :userId
				LIMIT 1];
	}

	public static ContentVersion getContentVersion(Id contentVersionId){
		return [SELECT ContentDocumentId 
		        FROM   ContentVersion 
		        WHERE  id =: contentVersionId];
	}

	public static List<ContentDocumentLink> getLinkForUserDocument(Id userId, Id contentDocId){
		return [SELECT Id, ShareType
		        FROM   ContentDocumentLink
		        WHERE  LinkedEntityId =: userId AND 
		               ContentDocumentId =: contentDocId];
	}

	public static FeedItem getFeedItem(Id feedItemId){
		return [SELECT Id, RelatedRecordId
		        FROM   FeedItem
		        WHERE  Id =: feedItemId];
	}

	public static Profile getProfileByName(String profileName){
		return [SELECT id
		        FROM   Profile
		        WHERE  Name =: profileName];
	}

}