src/objects/Approval_Step__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>The status of the Approval Step. This value is set by the system and cannot be manually input by users.</description>
        <inlineHelpText>The status of the Approval Step. This value is set by the system and cannot be manually input by users.</inlineHelpText>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Initiated</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Approved w Comments</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Initiated/Closed</fullName>
                </value>
                <value>
                    <fullName>Initiated/Reopened</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Assigned_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Approver assigned to this Approval Step.</description>
        <inlineHelpText>The Approver assigned to this Approval Step.</inlineHelpText>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Approval_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Completed_Date__c</fullName>
        <description>The date the Approval Step was completed (i.e., a decision was made).</description>
        <inlineHelpText>The date the Approval Step was completed (i.e., a decision was made).</inlineHelpText>
        <label>Completed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Correspondence_Document__c</fullName>
        <description>The Controlled Document on which this Approval Step is listed.</description>
        <inlineHelpText>The Controlled Document on which this Approval Step is listed.</inlineHelpText>
        <label>Controlled Document</label>
        <referenceTo>Controlled_Document__c</referenceTo>
        <relationshipLabel>Approval Steps</relationshipLabel>
        <relationshipName>Approval_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Days_Open__c</fullName>
        <description>The number of business days that elapse after this Approval Step was initiated and before it was completed.</description>
        <inlineHelpText>The number of business days that elapse after this Approval Step was initiated and before it was completed.</inlineHelpText>
        <label>Days Open</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Delegate__c</fullName>
        <label>Delegate</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Delegate</fullName>
                </value>
                <value>
                    <fullName>ExecSec</fullName>
                </value>
                <value>
                    <fullName>Approver</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>External_Review_Party__c</fullName>
        <description>When the &quot;Role of Approver&quot; is marked as &quot;External Review&quot;, this field indicates the external party that is conducting the review.</description>
        <inlineHelpText>When the &quot;Role of Approver&quot; is marked as &quot;External Review&quot;, this field indicates the external party that is conducting the review.</inlineHelpText>
        <label>External Review Party</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marked_for_Deletion__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checking this field marks this Approval Step as no longer being needed. Approval Steps that have been initiated will be recalled. At a later time, this field can be unchecked to reinstate an Approval Step.</description>
        <inlineHelpText>Checking this field marks this Approval Step as no longer being needed. Approval Steps that have been initiated will be recalled. At a later time, this field can be unchecked to reinstate an Approval Step.</inlineHelpText>
        <label>Deactivate Step</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Office__c</fullName>
        <description>The Service/Staff Office of the Approver.</description>
        <inlineHelpText>The Service/Staff Office of the Approver.</inlineHelpText>
        <label>Approver&apos;s Service/Staff Office</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>A - Office of the Administrator</fullName>
                </value>
                <value>
                    <fullName>AK - Office of Civil Rights</fullName>
                </value>
                <value>
                    <fullName>B - Office of the Chief Financial Officer</fullName>
                </value>
                <value>
                    <fullName>C - Office of Human Resource Management</fullName>
                </value>
                <value>
                    <fullName>D - Office of Mission Assurance</fullName>
                </value>
                <value>
                    <fullName>E - Office of Small Business Utilization</fullName>
                </value>
                <value>
                    <fullName>G - Civilian Board of Contract Appeals</fullName>
                </value>
                <value>
                    <fullName>H - Office of Administrative Services</fullName>
                </value>
                <value>
                    <fullName>I - Office of the GSA IT</fullName>
                </value>
                <value>
                    <fullName>J - Office of the Inspector General</fullName>
                </value>
                <value>
                    <fullName>L - Office of the General Counsel</fullName>
                </value>
                <value>
                    <fullName>M - Office of Governmentwide Policy</fullName>
                </value>
                <value>
                    <fullName>O - Office of Customer Experience</fullName>
                </value>
                <value>
                    <fullName>P - Public Buildings Service</fullName>
                </value>
                <value>
                    <fullName>Q - Federal Acquisition Service</fullName>
                </value>
                <value>
                    <fullName>S - Office of Congressional and Intergovernmental Affairs</fullName>
                </value>
                <value>
                    <fullName>T - Technology Transformation Service</fullName>
                </value>
                <value>
                    <fullName>Y - Federal Permitting Improvement Steering Council</fullName>
                </value>
                <value>
                    <fullName>Z - Office of Strategic Communication</fullName>
                </value>
                <value>
                    <fullName>Region 1A</fullName>
                </value>
                <value>
                    <fullName>Region 1P</fullName>
                </value>
                <value>
                    <fullName>Region 1Q</fullName>
                </value>
                <value>
                    <fullName>Region 2A</fullName>
                </value>
                <value>
                    <fullName>Region 2P</fullName>
                </value>
                <value>
                    <fullName>Region 2Q</fullName>
                </value>
                <value>
                    <fullName>Region 3A</fullName>
                </value>
                <value>
                    <fullName>Region 3P</fullName>
                </value>
                <value>
                    <fullName>Region 3Q</fullName>
                </value>
                <value>
                    <fullName>Region 4A</fullName>
                </value>
                <value>
                    <fullName>Region 4P</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Role_of_Approver__c</fullName>
        <description>The role the Approver is playing for this Approval Step.</description>
        <inlineHelpText>The role the Approver is playing for this Approval Step.</inlineHelpText>
        <label>Role of Approver</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approver</fullName>
                </value>
                <value>
                    <fullName>Audit Analyst</fullName>
                </value>
                <value>
                    <fullName>Close-Out</fullName>
                </value>
                <value>
                    <fullName>Drafter</fullName>
                </value>
                <value>
                    <fullName>Editor</fullName>
                </value>
                <value>
                    <fullName>Exec Sec Reviewer</fullName>
                </value>
                <value>
                    <fullName>External Review</fullName>
                </value>
                <value>
                    <fullName>FYI</fullName>
                </value>
                <value>
                    <fullName>Office POC</fullName>
                </value>
                <value>
                    <fullName>Signatory</fullName>
                </value>
                <value>
                    <fullName>Subject Matter Expert</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Approval Step</label>
    <nameField>
        <displayFormat>CC-Step{0000000}</displayFormat>
        <label>Approval Step ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Approval_Step_Recall_Request__c.object
<CustomObject>
    <description>Shows the requests made to recall Approval Steps that the user doesn&apos;t have access to directly.</description>
    <fields>
        <fullName>Approval_Step__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approval Step</label>
        <referenceTo>Approval_Step__c</referenceTo>
        <relationshipLabel>Approval Step Recall Requests</relationshipLabel>
        <relationshipName>Approval_Step_Recall_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recalled_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Recalled By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Approval_Step_Recall_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recalled_Date__c</fullName>
        <label>Recalled Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Work_Item_Id__c</fullName>
        <label>Work Item Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Approval Step Recall Request</label>
    <nameField>
        <displayFormat>ASRR-{0000000}</displayFormat>
        <label>Approval Step Recall Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Step Recall Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Controlled_Document__c.object
<CustomObject>
    <fields>
        <fullName>Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the ExecSec user assigned to the record.</inlineHelpText>
        <label>ExecSec Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Controlled_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Days_Open__c</fullName>
        <inlineHelpText>A calculation of the number of days a record has been open. This field is the difference between the ExecSec Start Date and either the current date, or the ExecSec End Date if that field is populated.</inlineHelpText>
        <label>ExecSec Business Days Open</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Controlled Document</label>
    <nameField>
        <displayFormat>CC{000000}</displayFormat>
        <label>Document ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Controlled Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ApprovalStepSelectManager.cls
/*-------------------------------------------------------------------------------------------------*
  ApprovalStepSelectManager
  -Responsible for managing the approval step objects in response to user input on the
   relatedApprovalStepList page.
 *-------------------------------------------------------------------------------------------------*
  Author           | Date        | Version | Description
 *-------------------------------------------------------------------------------------------------*
  Stefan Maurer      09/30/2014    1.0       Created
  Christian Coleman  10/1/2015     2.0       Added recall approval step functionality
  Raja Kumar P       02/22/2016    3.0       Enforce the due date validation case# 22035
  Raja Kumar P       06/07/2016    4.0       case# 25836 - bulkify the code while initiating multiple approval steps at a time.
 *-------------------------------------------------------------------------------------------------*/
 public without sharing class ApprovalStepSelectManager {
    public List<ApprovalStepSelect> approvalStepSelects {get; private set;}
    public Boolean noRowsSelected {get; private set;}
    public static boolean isRecallTest = false;
    private List<ApprovalStepSelect> backupApprovalStepSelects;
    private Id documentId;
    private Controlled_Document__c cdoc;

    public ApprovalStepSelectManager(Id documentId) {
        this.documentId = documentId;
        initializeSteps();
        addNewStep();
        determineNoRowsSelected();
        cdoc = [SELECT Id, OwnerId, Assignee__c FROM Controlled_Document__c WHERE Id = :documentId];
    }

    public Boolean save(){
        if(!addValidationErrors(extractUnlockedApprovalSteps())){
            try{
                update extractUnlockedApprovalSteps();
                initializeSteps();
                determineNoRowsSelected();
            } catch(Exception e){
                ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, ExceptionUtility.parseErrorMessage(e.getMessage())));
                return false;
            }
        }
        else{
            return false;
        }
        return true;
    }

    public void initiateSelected(){
        Map<Id,Id> approvalProcessMap = new Map<Id,Id>();
        Set<Id> approvalStepIds = new Set<Id>();
        // case# 22035 - BEGIN- added try and catch blocks to show the trigger errors, all other code is existing.
        try {
        // case# 22035 - END
        for(ApprovalStepSelect step : approvalStepSelects){
            approvalStepIds.add(step.approvalStep.id);
        }

        for(ProcessInstanceWorkItem approvalProcessItem : getProcessWorkItems(approvalStepIds)){
            approvalProcessMap.put(approvalProcessItem.ProcessInstance.TargetObjectId, approvalProcessItem.Id);
        }
        // case# 25836 - BEGIN
        List<Approval.ProcessSubmitRequest> requests = new List<Approval.ProcessSubmitRequest>();
        // case# 25836 - END
        for(ApprovalStepSelect step : approvalStepSelects){
            if(step.selected && !step.approvalStep.Marked_For_Deletion__c && approvalProcessMap.get(step.approvalStep.id) == null){
                Approval.ProcessSubmitRequest submitRequest = new Approval.ProcessSubmitRequest();
                submitRequest.setObjectId(step.approvalStep.id);
                submitRequest.setSubmitterId(UserInfo.getUserId());
                // case# 25836 - BEGIN
                requests.add(submitRequest);
                // case# 25836 - END
                //Approval.process(submitRequest); - COMMENTED for CASE# 25836
            }
        }
        // case# 25836 - BEGIN
        Approval.process(requests);
        // case# 25836 - END
        }
        // case# 22035 - BEGIN
        catch(Exception e) {
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, exceptionUtility.parseErrorMessage(e.getMessage())));
        }
        // case# 22035 - END
        
        initializeSteps();
        addNewStep();
        determineNoRowsSelected();
    }

    public void recallSelected(){
        Map<Id, Id> approvalProcessMap = new Map<Id, Id>();
        Set<Id> approvalStepIds = new Set<Id>();
        for(ApprovalStepSelect step : approvalStepSelects){
            approvalStepIds.add(step.approvalStep.id);
        }

        for(ProcessInstanceWorkItem approvalProcessItem : getProcessWorkItems(approvalStepIds)){
            approvalProcessMap.put(approvalProcessItem.ProcessInstance.TargetObjectId, approvalProcessItem.Id);
        }

        // list of approval steps that need to be processed
        List<Approval_Step_Recall_Request__c> approvalStepsToProcess = new List<Approval_Step_Recall_Request__c>();

        // check the current user to see if he/she is an ExecSec Admin
        boolean isExecSecAdmin = false;
        Id userId = UserInfo.getUserId();
        List<PermissionSet> pset = [SELECT Id, Name FROM PermissionSet WHERE Name = 'Controlled_Document_Tracker_OAS_Admin_User_CRED'];
        if(pset != null && !pset.isEmpty()){ 
            List<PermissionSetAssignment> psetAssignment = [SELECT Id FROM PermissionSetAssignment WHERE AssigneeId = :userId AND PermissionSetId = :pset[0].Id];
            if(psetAssignment != null && !psetAssignment.isEmpty()){
                isExecSecAdmin = true;
            }
        }

        // checks for existing recall requests to ensure an approval step isn't recalled in the batch in this scenario:
        // 1. someone initiates a recall request to be picked up by batch
        // 2. an admin recalls the approval step before the batch picks it up
        // 3. the admin changes something and initiates it again
        // 4. the batch runs and recalls the approval step out of order
        List<Id> idsToQueryForExistingRequests = new List<Id>();

        for(ApprovalStepSelect step : approvalStepSelects){
            if(step.selected && !step.approvalStep.Marked_For_Deletion__c && approvalProcessMap.get(step.approvalStep.Id) != null){
                // BATCH SOLUTION //////////////////////////////////////////////////////////////////////////////////////////////
                try {
                    System.debug('TRYING TO DO NORMALLY');
                    Approval.ProcessWorkItemRequest recallRequest = new Approval.ProcessWorkItemRequest();
                    recallRequest.setWorkItemId(approvalProcessMap.get(step.approvalStep.Id));
                    recallRequest.setAction('Removed');
                    Approval.process(recallRequest);
                    ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.CONFIRM, 'Your recall request has been processed.');
                    ApexPages.addMessage(myMsg);
                    // creating a record for historical purposes - batch won't pick this up
                    Approval_Step_Recall_Request__c approvalStepToRecall = new Approval_Step_Recall_Request__c();
                    approvalStepToRecall.Approval_Step__c = step.approvalStep.Id;
                    approvalStepToRecall.Work_Item_Id__c = approvalProcessMap.get(step.approvalStep.Id);
                    approvalStepToRecall.Status__c = 'Recalled';
                    approvalStepToRecall.Recalled_By__c = userId;
                    Datetime d = Datetime.now();
                    approvalStepToRecall.Recalled_Date__c = d;
                    approvalStepsToProcess.add(approvalStepToRecall);
                    // search for existing unprocessed recall requests to make sure it isn't reprocessed
                    idsToQueryForExistingRequests.add(step.approvalStep.Id);
                } catch (Exception e){
                    System.debug('INSIDE RECALL CATCH');
                    if(userId == cdoc.OwnerId 
                        || userId == cdoc.Assignee__c 
                        || userId == step.approvalStep.Assigned_Approver__c
                        || userId == step.approvalStep.CreatedById
                        || isExecSecAdmin)
                    {
                        System.debug('NOW HAFTA DO IT VIA BATCH');
                        Approval_Step_Recall_Request__c approvalStepToRecall = new Approval_Step_Recall_Request__c();
                        approvalStepToRecall.Approval_Step__c = step.approvalStep.Id;
                        approvalStepToRecall.Work_Item_Id__c = approvalProcessMap.get(step.approvalStep.Id);
                        approvalStepToRecall.Status__c = 'Pending';
                        approvalStepToRecall.Recalled_By__c = userId;
                        approvalStepsToProcess.add(approvalStepToRecall);
                        ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.INFO, 'Your recall request has been submitted. Please allow some time for the system to process it.');
                        ApexPages.addMessage(myMsg);
                    } else {
                        System.debug('UNAUTHORIZED RECALL');
                        ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, 'Please ask the Controlled Document owner, Approval Step creator, Assigned Approver, Exec Sec Assignee, or an administrator to recall the step manually.');
                        ApexPages.addMessage(myMsg);
                    }
                }
                ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////
            }
        }

        // deleting existing approval step recall requests if an admin beat them to the punch
        if(idsToQueryForExistingRequests != null && !idsToQueryForExistingRequests.isEmpty()){
            List<Approval_Step_Recall_Request__c> approvalStepRecallRequestList = [SELECT Id FROM Approval_Step_Recall_Request__c WHERE Work_Item_Id__c IN :idsToQueryForExistingRequests AND Status__c = 'Pending'];
            if(approvalStepRecallRequestList != null && !approvalStepRecallRequestList.isEmpty()){
                System.debug('Special case - VERY RARE');
                delete approvalStepRecallRequestList;
            }   
        }

        // insert approval step recall requests
        if(!approvalStepsToProcess.isEmpty()){
            insert approvalStepsToProcess;
        }

        initializeSteps();
        addNewStep();
        determineNoRowsSelected();
    }

    public void clearNewRow(){
        removeNewStep();
        addNewStep();
    }

    private List<Approval_Step__c> extractUnlockedApprovalSteps(){
        List<Approval_Step__c> steps = new List<Approval_Step__c>();
        for(ApprovalStepSelect step : approvalStepSelects){
            if(step.ApprovalStep.id != null && !step.getisLocked()){
                steps.add(step.ApprovalStep);
            }
        }
        return steps;
    }

    public void backup(){
        backupApprovalStepSelects = cloneApprovalStepSelectList(approvalStepSelects);
    }

    public void restore(){
        approvalStepSelects = cloneApprovalStepSelectList(backupApprovalStepSelects);
    }

    private static List<ApprovalStepSelect> cloneApprovalStepSelectList(List<ApprovalStepSelect> steps){
        List<ApprovalStepSelect> stepClones = new List<ApprovalStepSelect>();
        for(ApprovalStepSelect step : steps){
            stepClones.add(new ApprovalStepSelect(step));
        }
        return stepClones;
    }

    public void populateExternalReviewParty(){
        for(ApprovalStepSelect step : approvalStepSelects){
            if(step.approvalStep.Role_Of_Approver__c == ControlledDocumentConstants.EXTERNAL_REVIEW_ROLE_NAME){
                if(step.approvalStep.External_Review_Party__c == null){
                    step.approvalStep.External_Review_Party__c = ControlledDocumentConstants.EXTERNAL_REVIEW_AUTOFILL_VALUE;
                }
            }
            else{
                step.approvalStep.External_Review_Party__c = null;
            }
        }
    }

    private void initializeSteps(){
        approvalStepSelects = new List<ApprovalStepSelect>();
        for(Approval_Step__c step : getRelatedApprovalSteps()){
            approvalStepSelects.add(new ApprovalStepSelect(step));
        }
    }

    public void addNewStep(){
        approvalStepSelects.add(new ApprovalStepSelect(new Approval_Step__c(Correspondence_Document__c = documentId)));
    }

    public void removeNewStep(){
        approvalStepSelects.remove(approvalStepSelects.size()-1);
    }

    public void insertNewStep(){
        if(!addValidationErrors(new List<Approval_Step__c>{getNewApprovalStep()})){
            try{
                insert getNewApprovalStep();
                initializeSteps();
                addNewStep();
                determineNoRowsSelected();
            } catch(Exception e){
                ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, exceptionUtility.parseErrorMessage(e.getMessage())));
            }
        }
    }

    private Boolean addValidationErrors(List<Approval_Step__c> steps){
        Set<String> errorMessageKeys = new Set<String>();
        for(Approval_Step__c step : steps){
            for(String s : ControlledDocumentConstants.REQUIRED_FIELD_API_TO_LABEL_MAP.keySet()){
                if(step.get(s) == null){
                    errorMessageKeys.add(s);
                }
            }
        }

        for(String s : errorMessageKeys){
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, 'Missing Required Field: ' + ControlledDocumentConstants.REQUIRED_FIELD_API_TO_LABEL_MAP.get(s)));
        }

        if(errorMessageKeys.isEmpty()){
            return false;
        }
        return true;

    }

    private Approval_Step__c getNewApprovalStep(){
        return approvalStepSelects.get(approvalStepSelects.size()-1).approvalStep;
    }

    public void determineNoRowsSelected(){
        noRowsSelected = true;
        for(ApprovalStepSelect stepSelect : approvalStepSelects){
            if(stepSelect.selected){
                noRowsSelected = false;
                break;
            }
        }
    }

    private List<Approval_Step__c> getRelatedApprovalSteps(){
        return [SELECT Name, Approval_Status__c, Assigned_Approver__c, CreatedById, Completed_Date__c, Marked_for_Deletion__c, Office__c, Delegate__c,
                       Days_Open__c, Role_Of_Approver__c, Sequence__c, Start_Date__c, Due_Date__c, External_Review_Party__c, Assigned_Approver__r.Name
                FROM Approval_Step__c
                WHERE Correspondence_Document__c =: documentId
                ORDER BY Sequence__c ASC NULLS LAST];
    }

    private static List<ProcessInstanceWorkItem> getProcessWorkItems(Set<Id> approvalStepIds){
        return [SELECT Id, ProcessInstance.TargetObjectId
                FROM ProcessInstanceWorkItem 
                WHERE ProcessInstance.Status = 'Pending' AND 
                      ProcessInstance.TargetObjectId IN: approvalStepIds];
    }
}