src/objects/Approval_Step__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>The status of the Approval Step. This value is set by the system and cannot be manually input by users.</description>
        <inlineHelpText>The status of the Approval Step. This value is set by the system and cannot be manually input by users.</inlineHelpText>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Initiated</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Approved w Comments</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Initiated/Closed</fullName>
                </value>
                <value>
                    <fullName>Initiated/Reopened</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Assigned_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Approver assigned to this Approval Step.</description>
        <inlineHelpText>The Approver assigned to this Approval Step.</inlineHelpText>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Approval_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Correspondence_Document__c</fullName>
        <description>The Controlled Document on which this Approval Step is listed.</description>
        <inlineHelpText>The Controlled Document on which this Approval Step is listed.</inlineHelpText>
        <label>Controlled Document</label>
        <referenceTo>Controlled_Document__c</referenceTo>
        <relationshipLabel>Approval Steps</relationshipLabel>
        <relationshipName>Approval_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Marked_for_Deletion__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checking this field marks this Approval Step as no longer being needed. Approval Steps that have been initiated will be recalled. At a later time, this field can be unchecked to reinstate an Approval Step.</description>
        <inlineHelpText>Checking this field marks this Approval Step as no longer being needed. Approval Steps that have been initiated will be recalled. At a later time, this field can be unchecked to reinstate an Approval Step.</inlineHelpText>
        <label>Deactivate Step</label>
        <type>Checkbox</type>
    </fields>
    <label>Approval Step</label>
    <nameField>
        <displayFormat>CC-Step{0000000}</displayFormat>
        <label>Approval Step ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Controlled_Document__c.object
<CustomObject>
    <label>Controlled Document</label>
    <nameField>
        <displayFormat>CC{000000}</displayFormat>
        <label>Document ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Controlled Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Controlled_Document_Feed__c.object
<CustomObject>
    <description>This Object is being used by the Controlled Document Tracker application.</description>
    <fields>
        <fullName>Approval_Step_Delegate_Origin__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approval Step Delegate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Controlled_Document__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Controlled Document</label>
        <referenceTo>Controlled_Document__c</referenceTo>
        <relationshipName>Controlled_Document_Feed</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.UserType</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Controlled_Document_Feed</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Grant Update Access Request</label>
    <nameField>
        <displayFormat>GUA-{0000000}</displayFormat>
        <label>Grant Update Access Requests</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grant Update Access Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Supplementary_Access_User__c.object
<CustomObject>
    <description>A record for consolidating various controlled document sharing permissions from a verity of custom and apex sources,</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Approval_Step__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approval Step (If Applicable)</label>
        <referenceTo>Approval_Step__c</referenceTo>
        <relationshipLabel>Supplementary Access History</relationshipLabel>
        <relationshipName>Supplementary_Access_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Controlled_Document__c</fullName>
        <label>Controlled Document</label>
        <referenceTo>Controlled_Document__c</referenceTo>
        <relationshipLabel>Supplementary Access History</relationshipLabel>
        <relationshipName>CD_Add_on_Sharing_Users</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Inactivated_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inactivated By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CD_Add_on_Sharing_Users1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Inactivation_Date__c</fullName>
        <label>Inactivation Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Origin__c</fullName>
        <label>Origin</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Originating_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Originating User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CD_Add_on_Sharing_Users2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CD_Add_on_Sharing_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Supplementary Access User</label>
    <nameField>
        <displayFormat>SAU-{0000000000}</displayFormat>
        <label>Supplementary Access User Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplementary Access History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SupplementaryAccessUserGranterApprvlStep.cls
public class SupplementaryAccessUserGranterApprvlStep{

	public static void updateSupplementsForApprovalSteps(Map<Id, Approval_Step__c> oldApprovalStepMap, List<Approval_Step__c> newApprovalStepList){

		List<Approval_Step__c> qualifyingStepsForAdditionList = getQualifyingStepsForAddition(oldApprovalStepMap, newApprovalStepList);
		List<Supplementary_Access_User__c> supplementsToAddList = addSupplementsForDelegatesForApprovalSteps(qualifyingStepsForAdditionList);
		if(supplementsToAddList.size() > 0){
			insert supplementsToAddList;
		}
		
		List<Controlled_Document_Feed__c> batchItemsToAddList = giveAccessToChatterFiles(supplementsToAddList);
		if(batchItemsToAddList.size() > 0){
			insert batchItemsToAddList;
		}

		List<Approval_Step__c> qualifyingStepsForDeletionList = getQualifyingStepsForDeletion(oldApprovalStepMap, newApprovalStepList);
		List<Supplementary_Access_User__c> supplementsToDeactivateList = removeSupplementsForDelegatesForApprovalSteps(qualifyingStepsForDeletionList);
		if(supplementsToDeactivateList.size() > 0){
			update supplementsToDeactivateList;
			ControlledDocumentAccessDeterminer.syncAccessToChatterFiles(supplementsToDeactivateList);
		}
		
	}

	public static List<Approval_Step__c> getQualifyingStepsForAddition(Map<Id, Approval_Step__c> oldApprovalSteps, List<Approval_Step__c> newApprovalSteps){

		List<Approval_Step__c> qualifyingSteps = new List<Approval_Step__c>();
		for(Approval_Step__c newStep : newApprovalSteps){
			Approval_Step__c oldStep = oldApprovalSteps.get(newStep.Id);
			if(newStep.Approval_Status__c != oldStep.Approval_Status__c && newStep.Approval_Status__c == 'Initiated'){
				qualifyingSteps.add(newStep);
			} else if(newStep.Marked_for_Deletion__c != oldStep.Marked_for_Deletion__c 
				&& newStep.Marked_for_Deletion__c == false
				&& newStep.Approval_Status__c == 'Initiated'){
				qualifyingSteps.add(newStep);
			}
		}

		return qualifyingSteps;

	}

	public static List<Approval_Step__c> getQualifyingStepsForDeletion(Map<Id, Approval_Step__c> oldApprovalSteps, List<Approval_Step__c> newApprovalSteps){

		List<Approval_Step__c> qualifyingSteps = new List<Approval_Step__c>();
		for(Approval_Step__c newStep : newApprovalSteps){
			Approval_Step__c oldStep = oldApprovalSteps.get(newStep.Id);
			if(newStep.Marked_for_Deletion__c != oldStep.Marked_for_Deletion__c && newStep.Marked_for_Deletion__c == true){
				qualifyingSteps.add(newStep);
			}
		}

		return qualifyingSteps;

	}

	public static List<Supplementary_Access_User__c> addSupplementsForDelegatesForApprovalSteps(List<Approval_Step__c> qualifyingSteps){

		Map<Id, Approval_Step__c> newStepsWithMoreFields = getMoreFieldsForApprovalSteps(qualifyingSteps);

		List<Supplementary_Access_User__c> existingSupplements = getExistingSupplements(newStepsWithMoreFields.values()); 

		List<Supplementary_Access_User__c> newSupplementaryDelegateUserList = new List<Supplementary_Access_User__c>();

		for(Approval_Step__c step : newStepsWithMoreFields.values()){

			// if there is no delegate then we don't need to create a record
			if(step.Assigned_Approver__r.DelegatedApproverId == null) continue;

			// this prevents the case of a step being initiated, recalled, and reinitiated .. we don't want duplicate delegate records created
			boolean exists = false;
			for(Supplementary_Access_User__c supplement : existingSupplements){
				if(supplement.Approval_Step__c == step.Id) exists = true;
			}
			if(exists) continue;

			Supplementary_Access_User__c supplementaryDelegateUser = new Supplementary_Access_User__c();
			supplementaryDelegateUser.Active__c = true;
			supplementaryDelegateUser.Approval_Step__c = step.Id;
			supplementaryDelegateUser.Controlled_Document__c = step.Correspondence_Document__c;
			supplementaryDelegateUser.Origin__c = 'Delegate';
			supplementaryDelegateUser.Originating_User__c = step.Assigned_Approver__c;
			supplementaryDelegateUser.User__c = step.Assigned_Approver__r.DelegatedApproverId;
			newSupplementaryDelegateUserList.add(supplementaryDelegateUser);

		}

		return newSupplementaryDelegateUserList;

	}

	// this prevents the case of a step being initiated, recalled, and reinitiated .. we don't want duplicate delegate records created
	private static List<Supplementary_Access_User__c> getExistingSupplements(List<Approval_Step__c> stepList){

		Set<Id> stepIds = new Set<Id>();
		for(Approval_Step__c step : stepList){

			stepIds.add(step.Id);

		}

		List<Supplementary_Access_User__c> supplementList = [SELECT Id, Approval_Step__c, User__c 
															FROM Supplementary_Access_User__c 
															WHERE Approval_Step__c IN :stepIds 
															AND Active__c = true];

		return supplementList;

	}

	private static List<Controlled_Document_Feed__c> giveAccessToChatterFiles(List<Supplementary_Access_User__c> newSupplementaryDelegateUserList){

		List<Controlled_Document_Feed__c> batchItemsToAdd = new List<Controlled_Document_Feed__c>();
		for(Supplementary_Access_User__c supplement : newSupplementaryDelegateUserList){

			Controlled_Document_Feed__c batchItem = new Controlled_Document_Feed__c();
			batchItem.Controlled_Document__c = supplement.Controlled_Document__c;
			batchItem.Status__c = 'Pending';
			batchItem.User__c = supplement.User__c;
			batchItem.Approval_Step_Delegate_Origin__c = true;
			batchItemsToAdd.add(batchItem);

		}

		return batchItemsToAdd;

	}

	public static List<Supplementary_Access_User__c> removeSupplementsForDelegatesForApprovalSteps(List<Approval_Step__c> qualifyingSteps){

		Map<Id, Approval_Step__c> stepsWithMoreFields = getMoreFieldsForApprovalSteps(qualifyingSteps);

		Map<Id, Id> approverToDelegatedUserMap = new Map<Id, Id>();
		Set<Id> controlledDocumentIdSet = new Set<Id>();

		for(Id stepId : stepsWithMoreFields.keySet()){

			Approval_Step__c step = stepsWithMoreFields.get(stepId);
			approverToDelegatedUserMap.put(step.Assigned_Approver__c, step.Assigned_Approver__r.DelegatedApproverId);
			controlledDocumentIdSet.add(step.Correspondence_Document__c);

		}

		List<Supplementary_Access_User__c> supplementsToCheck = [
															SELECT Id, Active__c, Controlled_Document__c, Origin__c, Originating_User__c, User__c, Inactivated_By__c, Inactivation_Date__c, Approval_Step__c
															FROM Supplementary_Access_User__c
															WHERE Originating_User__c IN :approverToDelegatedUserMap.keySet()
															AND User__c IN :approverToDelegatedUserMap.values()
															AND Controlled_Document__c IN :controlledDocumentIdSet
															AND Origin__c = 'Delegate'
															AND Active__c = true
															AND Approval_Step__c IN :stepsWithMoreFields.keySet()
														];

		List<Supplementary_Access_User__c> supplementsToDeactivate = new List<Supplementary_Access_User__c>();

		for(Supplementary_Access_User__c supplement : supplementsToCheck){

			Id supplementOriginatingUser = supplement.Originating_User__c;
			Id supplementUser = supplement.User__c; 
			Id supplementControlledDocumentId = supplement.Controlled_Document__c;
			Id supplementApprovalStep = supplement.Approval_Step__c;

			for(Id stepId : stepsWithMoreFields.keySet()) {

				Approval_Step__c step = stepsWithMoreFields.get(stepId);

				Id approvalStepApprover = step.Assigned_Approver__c;
				Id approvalStepApproverDelegate = step.Assigned_Approver__r.DelegatedApproverId;
				Id approvalStepControlledDocumentId = step.Correspondence_Document__c;

				if(supplementOriginatingUser == approvalStepApprover 
					&& supplementUser == approvalStepApproverDelegate
					&& supplementControlledDocumentId == approvalStepControlledDocumentId
					&& supplementApprovalStep == stepId) {

					supplement.Active__c = false;
					supplement.Inactivated_By__c = UserInfo.getUserId();
					supplement.Inactivation_Date__c = System.now();
					supplementsToDeactivate.add(supplement);

				}

			}

		}

		return supplementsToDeactivate;

	}

	private static Map<Id, Approval_Step__c> getMoreFieldsForApprovalSteps(List<Approval_Step__c> stepList){
		
		Set<Id> stepIds = new Set<Id>();
		for(Approval_Step__c step : stepList){
			stepIds.add(step.Id);
		}

		return new Map<Id, Approval_Step__c>([
										SELECT Id, Assigned_Approver__c, Assigned_Approver__r.DelegatedApproverId, Correspondence_Document__c 
										FROM Approval_Step__c
										WHERE Id IN :stepIds
									]);

	}

}