src/objects/Approval_Step__c.object
<CustomObject>
    <fields>
        <fullName>Correspondence_Type__c</fullName>
        <description>The Document Type of the Controlled Document on which this Approval Step is listed.</description>
        <formula>TEXT(Correspondence_Document__r.Correspondence_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The Document Type of the Controlled Document on which this Approval Step is listed.</inlineHelpText>
        <label>Document Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <description>The date this Approval Step is due.</description>
        <inlineHelpText>The date this Approval Step is due.</inlineHelpText>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <description>The order in which this Approval Step will appear on the Controlled Document record.</description>
        <inlineHelpText>The order in which this Approval Step will appear on the Controlled Document record.</inlineHelpText>
        <label>Sequence</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>The date this Approval Step was initiated.</description>
        <inlineHelpText>The date this Approval Step was initiated.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Approval Step</label>
    <nameField>
        <displayFormat>CC-Step{0000000}</displayFormat>
        <label>Approval Step ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Controlled_Document__c.object
<CustomObject>
    <fields>
        <fullName>Correspondence_Type__c</fullName>
        <inlineHelpText>The type of document represented by the primary file(s) being approved through this record.</inlineHelpText>
        <label>Document Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Acquisition Plan</fullName>
                </value>
                <value>
                    <fullName>AFR</fullName>
                </value>
                <value>
                    <fullName>Annual Report</fullName>
                </value>
                <value>
                    <fullName>Appeal</fullName>
                </value>
                <value>
                    <fullName>ASF: Cost &amp; Capital Plan</fullName>
                </value>
                <value>
                    <fullName>Budget</fullName>
                </value>
                <value>
                    <fullName>Claim</fullName>
                </value>
                <value>
                    <fullName>Complaint</fullName>
                </value>
                <value>
                    <fullName>Dashboard</fullName>
                </value>
                <value>
                    <fullName>Delegation</fullName>
                </value>
                <value>
                    <fullName>Directive</fullName>
                </value>
                <value>
                    <fullName>E-Gov Reporting</fullName>
                </value>
                <value>
                    <fullName>FISMA</fullName>
                </value>
                <value>
                    <fullName>Forms</fullName>
                </value>
                <value>
                    <fullName>GAO Draft Response</fullName>
                </value>
                <value>
                    <fullName>GAO Final Response</fullName>
                </value>
                <value>
                    <fullName>Hazardous Waste Report</fullName>
                </value>
                <value>
                    <fullName>Home-To-Work</fullName>
                </value>
                <value>
                    <fullName>IG Audit</fullName>
                </value>
                <value>
                    <fullName>IG Draft Response</fullName>
                </value>
                <value>
                    <fullName>IG Final Response</fullName>
                </value>
                <value>
                    <fullName>Instructional Letter</fullName>
                </value>
                <value>
                    <fullName>Interagency Agreement</fullName>
                </value>
                <value>
                    <fullName>Inventory</fullName>
                </value>
                <value>
                    <fullName>Lease Prospectus</fullName>
                </value>
                <value>
                    <fullName>Letter</fullName>
                </value>
                <value>
                    <fullName>Memorandum</fullName>
                </value>
                <value>
                    <fullName>MOU</fullName>
                </value>
                <value>
                    <fullName>Occupational Safety &amp; Health</fullName>
                </value>
                <value>
                    <fullName>OMB Scorecard</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date_Closed__c</fullName>
        <inlineHelpText>The date the record is closed. This field cannot be completed until the Stage is set to Closed. When the Stage is set to Closed, this field is automatically populated with the current date. However, this date can be edited.</inlineHelpText>
        <label>Date Closed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <description>The due date for the final signer.</description>
        <inlineHelpText>The due date for the final signer.</inlineHelpText>
        <label>Requested Due Date - Signer</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Due_Date_for_Signature__c</fullName>
        <inlineHelpText>The Due Date for Signature field is used to indicate the date by which the final signature for this document should be obtained.</inlineHelpText>
        <label>Due Date for Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ExecSec_Due_Date__c</fullName>
        <inlineHelpText>The date by when ExecSec should complete their work on the record. This is generally the day it is sent for signature.</inlineHelpText>
        <label>ExecSec Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ExecSec_End_Date__c</fullName>
        <inlineHelpText>The date ExecSec completed their work on this record.</inlineHelpText>
        <label>ExecSec End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ExecSec_Start_Date__c</fullName>
        <inlineHelpText>This shows the date that ExecSec begins working on a Controlled Document record, but can be changed by ExecSec users.</inlineHelpText>
        <label>ExecSec Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Originating_Office__c</fullName>
        <inlineHelpText>The division originating or overseeing the Controlled Document. Once a value is selected, users from that Originating Service/Staff Office will be able to access and edit this Controlled Document unless further restrictions are implemented.</inlineHelpText>
        <label>Originating Service/Staff Office</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AK - Office of Civil Rights</fullName>
                </value>
                <value>
                    <fullName>A - Office of the Administrator</fullName>
                </value>
                <value>
                    <fullName>B - Office of the Chief Financial Officer</fullName>
                </value>
                <value>
                    <fullName>C - Office of Human Resource Management</fullName>
                </value>
                <value>
                    <fullName>D - Office of Mission Assurance</fullName>
                </value>
                <value>
                    <fullName>E - Office of Small Business Utilization</fullName>
                </value>
                <value>
                    <fullName>G - Civilian Board of Contract Appeals</fullName>
                </value>
                <value>
                    <fullName>H - Office of Administrative Services</fullName>
                </value>
                <value>
                    <fullName>I - Office of the GSA IT</fullName>
                </value>
                <value>
                    <fullName>J - Office of the Inspector General</fullName>
                </value>
                <value>
                    <fullName>L - Office of the General Counsel</fullName>
                </value>
                <value>
                    <fullName>M - Office of Governmentwide Policy</fullName>
                </value>
                <value>
                    <fullName>O - Office of Customer Experience</fullName>
                </value>
                <value>
                    <fullName>P - Public Buildings Service</fullName>
                </value>
                <value>
                    <fullName>PTT - Presidential Transition Team</fullName>
                </value>
                <value>
                    <fullName>Q - Federal Acquisition Service</fullName>
                </value>
                <value>
                    <fullName>S - Office of Congressional and Intergovernmental Affairs</fullName>
                </value>
                <value>
                    <fullName>T - Technology Transformation Service</fullName>
                </value>
                <value>
                    <fullName>Y - Federal Permitting Improvement Steering Council</fullName>
                </value>
                <value>
                    <fullName>Z - Office of Strategic Communication</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <inlineHelpText>An indication of where in the life-cycle of a Controlled Document this record resides. This field is manually updated by users with edit access to the Controlled Document record.</inlineHelpText>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Awaiting Closure</fullName>
                </value>
                <value>
                    <fullName>Awaiting Signature</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Concurrence</fullName>
                </value>
                <value>
                    <fullName>Directives Clearance</fullName>
                </value>
                <value>
                    <fullName>Directives Coordination</fullName>
                </value>
                <value>
                    <fullName>Drafting</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>External Review</fullName>
                </value>
                <value>
                    <fullName>Hold</fullName>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>Revise</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Controlled Document</label>
    <nameField>
        <displayFormat>CC{000000}</displayFormat>
        <label>Document ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Controlled Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestShareDocumentToApproversHelper.cls
/*-------------------------------------------------------------------------------------------------*
  TestShareDocumentToApproversHelperClass
  Test Class for ShareDocumentToApproversHelper.cls
 *-------------------------------------------------------------------------------------------------*
  Author           | Date        | Version | Description
 *-------------------------------------------------------------------------------------------------*
  Sathish Durairaj      10/22/2014    1.0       Created
  Raja Kumar P          05/15/2016    2.0       Updated for case# 21548 - remove the collaborator access to the approver for deactivated step
 *-------------------------------------------------------------------------------------------------*/

@isTest
private class TestShareDocumentToApproversHelper {
    
    private static Id testControlDocId;
   

    private static void loadTestData() {
        
        //Get Owner ID from existing users
        
        List<User> u = [Select u.UserType, u.Name, u.UserRoleId, u.ProfileID 
                    From User u 
                    where u.UserType = 'Standard' and isActive = true
                    and u.profileID in (select id from profile where name = 'GSA System Administrator')
                    limit 1 ];
        
        //Get User ID from existing users for Apex Managed Sharing access
        
        List<User> u1 = [Select u.UserType, u.Name, u.UserRoleId, u.ProfileID 
                    From User u 
                    where u.UserType = 'Standard' and isActive = true
                    limit 1 ];
        
        // Insert Controlled Document
        Controlled_Document__c testControlledDoc = new Controlled_Document__c();
        testControlledDoc.ExecSec_Start_Date__c = system.Today();
        testControlledDoc.ExecSec_Due_Date__c = system.Today() + 5;
        testControlledDoc.Date_Closed__c = system.Today() + 5;
        testControlledDoc.ExecSec_End_Date__c = system.Today() + 5;
        testControlledDoc.Due_Date_for_Signature__c = system.Today() +5;
        testControlledDoc.Title__c = 'Test Controlled Doc' + system.Today();
        testControlledDoc.Correspondence_Type__c = 'Annual Report';
        testControlledDoc.Originating_Office__c = 'A - Office of the Administrator';
        testControlledDoc.OwnerId = u[0].id;
        testControlledDoc.Stage__c = 'Closed';

        try
        {
            insert testControlledDoc;
            testControlDocId = testControlledDoc.id;
        }
        catch (DMLException dmle)
        {
            System.debug('\n\n>> TestShareDocumentToApproversHelper() - Unable to insert test Controlled Document.\nDMLException encountered - ' + dmle);
            System.assert(false);
        }
        
        // Insert 2nd Controlled Document
        Controlled_Document__c testControlledDoc1 = new Controlled_Document__c();
        testControlledDoc1.ExecSec_Start_Date__c = system.Today() - 7;
        testControlledDoc1.ExecSec_Due_Date__c = system.Today() - 5;
        testControlledDoc1.ExecSec_End_Date__c = null;
        testControlledDoc1.Date_Closed__c = null;
        testControlledDoc1.Due_Date_for_Signature__c = system.Today() +5;
        testControlledDoc1.Title__c = 'Test Controlled Doc 1' + system.Today();
        testControlledDoc1.Correspondence_Type__c = 'Annual Report';
        testControlledDoc1.Originating_Office__c = 'A - Office of the Administrator';
        testControlledDoc1.OwnerId = u[0].id;
        testControlledDoc1.Stage__c = 'Initiated';
        testControlledDoc1.Due_Date__c = system.Today() - 5;

        try
        {
            insert testControlledDoc1;
        }
        catch (DMLException dmle)
        {
            System.debug('\n\n>> TestShareDocumentToApproversHelper() - Unable to insert test Controlled Document.\nDMLException encountered - ' + dmle);
            System.assert(false);
        }
        
        // Insert 3rd Controlled Document
        Controlled_Document__c testControlledDoc2 = new Controlled_Document__c();
        testControlledDoc2.ExecSec_Start_Date__c = system.Today() - 7;
        testControlledDoc2.ExecSec_Due_Date__c = system.Today() - 5;
        testControlledDoc2.ExecSec_End_Date__c = system.Today();
        testControlledDoc2.Date_Closed__c = system.Today();
        testControlledDoc2.Due_Date_for_Signature__c = system.Today() +5;
        testControlledDoc2.Title__c = 'Test Controlled Doc 1' + system.Today();
        testControlledDoc2.Correspondence_Type__c = 'Annual Report';
        testControlledDoc2.Originating_Office__c = 'A - Office of the Administrator';
        testControlledDoc2.OwnerId = u[0].id;
        testControlledDoc2.Stage__c = 'Closed';
        testControlledDoc2.Due_Date__c = system.Today() - 5;

        try
        {
            insert testControlledDoc2;
        }
        catch (DMLException dmle)
        {
            System.debug('\n\n>> TestShareDocumentToApproversHelper() - Unable to insert test Controlled Document.\nDMLException encountered - ' + dmle);
            System.assert(false);
        }
        
      
        
        // Insert Approval Step
        
        List<Approval_Step__c> listApprovalStep = new List<Approval_Step__c>();
        
        Approval_Step__c testAppStep = new Approval_Step__c();
        testAppStep.Sequence__c = '1';
        testAppStep.Start_Date__c = system.Today();
        testAppStep.Due_Date__c = system.Today() + 5;
        testAppStep.Approval_Status__c = 'Not Initiated';
        testAppStep.Approval_Step_Type__c = 'Individual Approver';
        testAppStep.Assigned_Approver__c = u1[0].id;
        testAppStep.Correspondence_Document__c = testControlDocId;
        listApprovalStep.add(testAppStep);
        
        Approval_Step__c testAppStep1 = new Approval_Step__c();
        testAppStep1.Sequence__c = '2';
        testAppStep1.Start_Date__c = system.Today()+5;
        testAppStep1.Due_Date__c = system.Today() + 10;
        testAppStep1.Completed_Date__c = system.Today() + 10;
        testAppStep1.Approval_Status__c = 'Initiated';
        testAppStep1.Approval_Step_Type__c = 'Individual Approver';
        testAppStep1.Assigned_Approver__c = u1[0].id;
        testAppStep1.Correspondence_Document__c = testControlDocId;
        listApprovalStep.add(testAppStep1);
        System.debug('List of App Steps>>>>>>>>' + listApprovalStep);

        try
        {
           if (listApprovalStep.size() >0) {
            insert listApprovalStep;
           }
        }
        catch (DMLException dmle)
        {
            System.debug('\n\n>> TestShareDocumentToApproversHelper() - Unable to insert test Approval Step.\nDMLException encountered - ' + dmle);
            //System.assert(false);
        }

       
    }

    static testMethod void testInsertAppStep(){
        
   
        Test.startTest();

        loadTestData();

        Test.stopTest();
        
        List<Approval_Step__c> lstApps = [select a.id from Approval_Step__c a where Correspondence_Document__c = :testControlDocId];
        
        system.assertEquals(true, lstApps.size() >0);
    }
    
    static testMethod void testDeleteAppStep(){

        loadTestData();
        
        List<Approval_Step__c> listAppStepToDelete = [select a.id from Approval_Step__c a where Correspondence_Document__c = :testControlDocId];

        Test.startTest();
        
        delete listAppStepToDelete;

        Test.stopTest();
        
         List<Approval_Step__c> lstApps = [select a.id from Approval_Step__c a where Correspondence_Document__c = :testControlDocId];
        
        system.assertEquals(true, lstApps.size() == 0);
    }
    
    static testMethod void testUpdateAppStep(){
 
        loadTestData();
        
        List<User> u2 = [Select u.UserType, u.Name, u.UserRoleId, u.ProfileID 
                        From User u 
                        where u.UserType = 'Standard' and isActive = true
                        limit 2 ];
        
        Approval_Step__c testAppStep0 = new Approval_Step__c();
        testAppStep0.Sequence__c = '1';
        testAppStep0.Start_Date__c = system.Today();
        testAppStep0.Due_Date__c = system.Today() + 5;
        testAppStep0.Completed_Date__c = null;
        testAppStep0.Approval_Status__c = 'Initiated';
        testAppStep0.Approval_Step_Type__c = 'Individual Approver';
        testAppStep0.Assigned_Approver__c = u2[0].id;
        testAppStep0.Correspondence_Document__c = testControlDocId;
        insert testAppStep0;
        
        Test.startTest();
         
        testAppStep0.Assigned_Approver__c = u2[1].id;
        update testAppStep0;
          

        Test.stopTest();
        
        List<Approval_Step__c> lstApps = [select a.id from Approval_Step__c a where Correspondence_Document__c = :testControlDocId];
        
        system.assertEquals(true, lstApps.size() >0);
    }
    
    static testMethod void testUpdateDeactivationAppStep(){
 
        loadTestData();
        
        List<User> u2 = [Select u.UserType, u.Name, u.UserRoleId, u.ProfileID 
                        From User u 
                        where u.UserType = 'Standard' and isActive = true
                        limit 2 ];
        
        Approval_Step__c testAppStep0 = new Approval_Step__c();
        testAppStep0.Sequence__c = '1';
        testAppStep0.Start_Date__c = system.Today();
        testAppStep0.Due_Date__c = system.Today() + 5;
        testAppStep0.Completed_Date__c = null;
        testAppStep0.Approval_Status__c = 'Initiated';
        testAppStep0.Approval_Step_Type__c = 'Individual Approver';
        testAppStep0.Assigned_Approver__c = u2[0].id;
        testAppStep0.Correspondence_Document__c = testControlDocId;
        insert testAppStep0;
        
        Test.startTest();
         
        testAppStep0.Marked_for_Deletion__c = true;
        update testAppStep0;
          

        Test.stopTest();
        
        List<Approval_Step__c> lstApps = [select a.id from Approval_Step__c a where Marked_for_Deletion__c = true];
        
        system.assertEquals(1, lstApps.size());
    }
}