src/objects/Approval_Step__c.object
<CustomObject>
    <fields>
        <fullName>Correspondence_Type__c</fullName>
        <description>The Document Type of the Controlled Document on which this Approval Step is listed.</description>
        <formula>TEXT(Correspondence_Document__r.Correspondence_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The Document Type of the Controlled Document on which this Approval Step is listed.</inlineHelpText>
        <label>Document Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <description>The date this Approval Step is due.</description>
        <inlineHelpText>The date this Approval Step is due.</inlineHelpText>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <label>Approval Step</label>
    <nameField>
        <displayFormat>CC-Step{0000000}</displayFormat>
        <label>Approval Step ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Approval_Step_Recall_Request__c.object
<CustomObject>
    <description>Shows the requests made to recall Approval Steps that the user doesn&apos;t have access to directly.</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Approval Step Recall Request</label>
    <nameField>
        <displayFormat>ASRR-{0000000}</displayFormat>
        <label>Approval Step Recall Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Step Recall Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Controlled_Document__c.object
<CustomObject>
    <fields>
        <fullName>Correspondence_Type__c</fullName>
        <inlineHelpText>The type of document represented by the primary file(s) being approved through this record.</inlineHelpText>
        <label>Document Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Acquisition Plan</fullName>
                </value>
                <value>
                    <fullName>AFR</fullName>
                </value>
                <value>
                    <fullName>Annual Report</fullName>
                </value>
                <value>
                    <fullName>Appeal</fullName>
                </value>
                <value>
                    <fullName>ASF: Cost &amp; Capital Plan</fullName>
                </value>
                <value>
                    <fullName>Budget</fullName>
                </value>
                <value>
                    <fullName>Claim</fullName>
                </value>
                <value>
                    <fullName>Complaint</fullName>
                </value>
                <value>
                    <fullName>Dashboard</fullName>
                </value>
                <value>
                    <fullName>Delegation</fullName>
                </value>
                <value>
                    <fullName>Directive</fullName>
                </value>
                <value>
                    <fullName>E-Gov Reporting</fullName>
                </value>
                <value>
                    <fullName>FISMA</fullName>
                </value>
                <value>
                    <fullName>Forms</fullName>
                </value>
                <value>
                    <fullName>GAO Draft Response</fullName>
                </value>
                <value>
                    <fullName>GAO Final Response</fullName>
                </value>
                <value>
                    <fullName>Hazardous Waste Report</fullName>
                </value>
                <value>
                    <fullName>Home-To-Work</fullName>
                </value>
                <value>
                    <fullName>IG Audit</fullName>
                </value>
                <value>
                    <fullName>IG Draft Response</fullName>
                </value>
                <value>
                    <fullName>IG Final Response</fullName>
                </value>
                <value>
                    <fullName>Instructional Letter</fullName>
                </value>
                <value>
                    <fullName>Interagency Agreement</fullName>
                </value>
                <value>
                    <fullName>Inventory</fullName>
                </value>
                <value>
                    <fullName>Lease Prospectus</fullName>
                </value>
                <value>
                    <fullName>Letter</fullName>
                </value>
                <value>
                    <fullName>Memorandum</fullName>
                </value>
                <value>
                    <fullName>MOU</fullName>
                </value>
                <value>
                    <fullName>Occupational Safety &amp; Health</fullName>
                </value>
                <value>
                    <fullName>OMB Scorecard</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date_Closed__c</fullName>
        <inlineHelpText>The date the record is closed. This field cannot be completed until the Stage is set to Closed. When the Stage is set to Closed, this field is automatically populated with the current date. However, this date can be edited.</inlineHelpText>
        <label>Date Closed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <description>The due date for the final signer.</description>
        <inlineHelpText>The due date for the final signer.</inlineHelpText>
        <label>Requested Due Date - Signer</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Due_Date_for_Signature__c</fullName>
        <inlineHelpText>The Due Date for Signature field is used to indicate the date by which the final signature for this document should be obtained.</inlineHelpText>
        <label>Due Date for Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ExecSec_Due_Date__c</fullName>
        <inlineHelpText>The date by when ExecSec should complete their work on the record. This is generally the day it is sent for signature.</inlineHelpText>
        <label>ExecSec Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ExecSec_End_Date__c</fullName>
        <inlineHelpText>The date ExecSec completed their work on this record.</inlineHelpText>
        <label>ExecSec End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ExecSec_Start_Date__c</fullName>
        <inlineHelpText>This shows the date that ExecSec begins working on a Controlled Document record, but can be changed by ExecSec users.</inlineHelpText>
        <label>ExecSec Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Originating_Office__c</fullName>
        <inlineHelpText>The division originating or overseeing the Controlled Document. Once a value is selected, users from that Originating Service/Staff Office will be able to access and edit this Controlled Document unless further restrictions are implemented.</inlineHelpText>
        <label>Originating Service/Staff Office</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AK - Office of Civil Rights</fullName>
                </value>
                <value>
                    <fullName>A - Office of the Administrator</fullName>
                </value>
                <value>
                    <fullName>B - Office of the Chief Financial Officer</fullName>
                </value>
                <value>
                    <fullName>C - Office of Human Resource Management</fullName>
                </value>
                <value>
                    <fullName>D - Office of Mission Assurance</fullName>
                </value>
                <value>
                    <fullName>E - Office of Small Business Utilization</fullName>
                </value>
                <value>
                    <fullName>G - Civilian Board of Contract Appeals</fullName>
                </value>
                <value>
                    <fullName>H - Office of Administrative Services</fullName>
                </value>
                <value>
                    <fullName>I - Office of the GSA IT</fullName>
                </value>
                <value>
                    <fullName>J - Office of the Inspector General</fullName>
                </value>
                <value>
                    <fullName>L - Office of the General Counsel</fullName>
                </value>
                <value>
                    <fullName>M - Office of Governmentwide Policy</fullName>
                </value>
                <value>
                    <fullName>O - Office of Customer Experience</fullName>
                </value>
                <value>
                    <fullName>P - Public Buildings Service</fullName>
                </value>
                <value>
                    <fullName>PTT - Presidential Transition Team</fullName>
                </value>
                <value>
                    <fullName>Q - Federal Acquisition Service</fullName>
                </value>
                <value>
                    <fullName>S - Office of Congressional and Intergovernmental Affairs</fullName>
                </value>
                <value>
                    <fullName>T - Technology Transformation Service</fullName>
                </value>
                <value>
                    <fullName>Y - Federal Permitting Improvement Steering Council</fullName>
                </value>
                <value>
                    <fullName>Z - Office of Strategic Communication</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <inlineHelpText>An indication of where in the life-cycle of a Controlled Document this record resides. This field is manually updated by users with edit access to the Controlled Document record.</inlineHelpText>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Awaiting Closure</fullName>
                </value>
                <value>
                    <fullName>Awaiting Signature</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Concurrence</fullName>
                </value>
                <value>
                    <fullName>Directives Clearance</fullName>
                </value>
                <value>
                    <fullName>Directives Coordination</fullName>
                </value>
                <value>
                    <fullName>Drafting</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>External Review</fullName>
                </value>
                <value>
                    <fullName>Hold</fullName>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>Revise</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Controlled Document</label>
    <nameField>
        <displayFormat>CC{000000}</displayFormat>
        <label>Document ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Controlled Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Controlled_Document_Feed__c.object
<CustomObject>
    <description>This Object is being used by the Controlled Document Tracker application.</description>
    <fields>
        <fullName>Controlled_Document__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Controlled Document</label>
        <referenceTo>Controlled_Document__c</referenceTo>
        <relationshipName>Controlled_Document_Feed</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Grant Update Access Request</label>
    <nameField>
        <displayFormat>GUA-{0000000}</displayFormat>
        <label>Grant Update Access Requests</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grant Update Access Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Supplementary_Access_User__c.object
<CustomObject>
    <description>A record for consolidating various controlled document sharing permissions from a verity of custom and apex sources,</description>
    <fields>
        <fullName>Controlled_Document__c</fullName>
        <label>Controlled Document</label>
        <referenceTo>Controlled_Document__c</referenceTo>
        <relationshipLabel>Supplementary Access History</relationshipLabel>
        <relationshipName>CD_Add_on_Sharing_Users</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Supplementary Access User</label>
    <nameField>
        <displayFormat>SAU-{0000000000}</displayFormat>
        <label>Supplementary Access User Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplementary Access History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestGrantAccesToChatterFileBatch.cls
@isTest
private class TestGrantAccesToChatterFileBatch {

	static testMethod void myUnitTest() {
		
		NotificationItemCreationHandler.isTest = true;

		List<User> exsitingStandardUsers = ControlledDocumentTestUtility.getStandardUsers(2);
		User testUser1 = exsitingStandardUsers.get(0);
		User testUser2 = exsitingStandardUsers.get(1);
		Controlled_Document__c testcd;
		FeedItem post;
		Controlled_Document_Feed__c cdf;
		Controlled_Document_Admin__c cda = new Controlled_Document_Admin__c();
		cda.Name = 'ADMINUSER';
		cda.UserName__c = UserInfo.getUserName();
		insert cda;
		System.runAs(testUser1) {
			// Insert Controlled Document
			testcd = new Controlled_Document__c();
			testcd.ExecSec_Start_Date__c = system.Today() - 7;
			testcd.ExecSec_Due_Date__c = system.Today() - 5;
			testcd.ExecSec_End_Date__c = null;
			testcd.Date_Closed__c = null;
			testcd.Due_Date_for_Signature__c = system.Today() +5;
			testcd.Title__c = 'Test Controlled Doc 1' + system.Today();
			testcd.Correspondence_Type__c = 'Annual Report';
			testcd.Originating_Office__c = 'A - Office of the Administrator';
			testcd.OwnerId = testUser1.id;
			testcd.Stage__c = 'Initiated';
			testcd.Due_Date__c = system.Today() - 5;
			insert testcd; 	
			
			post = ControlledDocumentTestUtility.createFeedItem(testcd.id);
			insert post;
			
			cdf = new Controlled_Document_Feed__c();
			cdf.Controlled_Document__c = testcd.Id;
			cdf.Status__c = 'Pending';
			cdf.User__c = testUser2.Id;
			insert cdf;
			
		}
		
		Test.startTest();		
		GrantAccessToChatterFileBatch b0 = new GrantAccessToChatterFileBatch();
		ID batchprocessid = Database.executeBatch(b0,1);
		system.assert(batchprocessid != null);
		Test.stopTest();	

	}

	// this is a test to specifically cause an exception in the batch helper for >90% code coverage in the helper
	
	static testMethod void testGrantAccessToChatterFileBatchHelper(){

		NotificationItemCreationHandler.isTest = true;

		Test.startTest();
        
		try{
			GrantAccessToChatterFileBatchHelper helper = new GrantAccessToChatterFileBatchHelper();
            List<Controlled_Document_Feed__c> staging = new List<Controlled_Document_Feed__c>();
            Controlled_Document_Feed__c stage = new Controlled_Document_Feed__c();
            stage.Notified__c = false;
            staging.add(stage);
			helper.grantAccessToUser(staging);
		
		} catch (NullPointerException e){
			// expected			
		}
		Test.stopTest();
		// fake assert but this method isn't testing anything specifically but trying to achieve 90% code coverage in a very short class
		// where the only lines missed are exception catching
		System.assertEquals(1,1);

	}

	// accounts for 4% test coverage -_-
	static testMethod void testApprovalStepRecallBatchAddition(){

		NotificationItemCreationHandler.isTest = true;

		List<User> exsitingStandardUsers = ControlledDocumentTestUtility.getStandardUsers(2);
		User testUser1 = exsitingStandardUsers.get(0);
		User testUser2 = exsitingStandardUsers.get(1);

		// Insert Controlled Document
		Controlled_Document__c testcd1 = new Controlled_Document__c();
		testcd1.ExecSec_Start_Date__c = system.Today() - 7;
		testcd1.ExecSec_Due_Date__c = system.Today() - 5;
		testcd1.ExecSec_End_Date__c = null;
		testcd1.Date_Closed__c = null;
		testcd1.Due_Date_for_Signature__c = system.Today() +5;
		testcd1.Title__c = 'Test Controlled Doc 1' + system.Today();
		testcd1.Correspondence_Type__c = 'Annual Report';
		testcd1.Originating_Office__c = 'A - Office of the Administrator';
		testcd1.OwnerId = testUser1.id;
		testcd1.Stage__c = 'Initiated';
		testcd1.Due_Date__c = system.Today() - 5;
		insert testcd1; 	

		Approval_Step__c aStep = new Approval_Step__c();
		astep.Correspondence_Document__c = testCd1.Id;
		insert aStep;

		Approval_Step_Recall_Request__c stepToRecall = new Approval_Step_Recall_Request__c();
		stepToRecall.Approval_Step__c = aStep.Id;
		stepToRecall.Work_Item_Id__c = '1234567890';
		stepToRecall.Status__c = 'Pending';
		insert stepToRecall;

		Controlled_Document__c testcd2;
		FeedItem post;
		Controlled_Document_Admin__c cda = new Controlled_Document_Admin__c();
		cda.Name = 'ADMINUSER';
		cda.UserName__c = UserInfo.getUserName();
		insert cda;
		System.runAs(testUser1) {

			// Insert Controlled Document
			testcd2 = new Controlled_Document__c();
			testcd2.ExecSec_Start_Date__c = system.Today() - 7;
			testcd2.ExecSec_Due_Date__c = system.Today() - 5;
			testcd2.ExecSec_End_Date__c = null;
			testcd2.Date_Closed__c = null;
			testcd2.Due_Date_for_Signature__c = system.Today() +5;
			testcd2.Title__c = 'Test Controlled Doc 1' + system.Today();
			testcd2.Correspondence_Type__c = 'Annual Report';
			testcd2.Originating_Office__c = 'A - Office of the Administrator';
			testcd2.OwnerId = testUser1.id;
			testcd2.Stage__c = 'Initiated';
			testcd2.Due_Date__c = system.Today() - 5;
			
			insert testcd2; 	
			post = ControlledDocumentTestUtility.createFeedItem(testcd2.id);
			insert post;
			
		}
		
		Test.startTest();		
		GrantAccessToChatterFileBatch b0 = new GrantAccessToChatterFileBatch();
		ID batchprocessid = Database.executeBatch(b0,1);
		system.assert(batchprocessid != null);
		Test.stopTest();

	}

	static testMethod void testApprovalStepRecallBatchAdditionWithGUARequests(){

		NotificationItemCreationHandler.isTest = true;

		List<User> exsitingStandardUsers = ControlledDocumentTestUtility.getStandardUsers(2);
		User testUser1 = exsitingStandardUsers.get(0);
		User testUser2 = exsitingStandardUsers.get(1);

		// Insert Controlled Document
		Controlled_Document__c testcd1 = new Controlled_Document__c();
		testcd1.ExecSec_Start_Date__c = system.Today() - 7;
		testcd1.ExecSec_Due_Date__c = system.Today() - 5;
		testcd1.ExecSec_End_Date__c = null;
		testcd1.Date_Closed__c = null;
		testcd1.Due_Date_for_Signature__c = system.Today() +5;
		testcd1.Title__c = 'Test Controlled Doc 1' + system.Today();
		testcd1.Correspondence_Type__c = 'Annual Report';
		testcd1.Originating_Office__c = 'A - Office of the Administrator';
		testcd1.OwnerId = testUser1.id;
		testcd1.Stage__c = 'Initiated';
		testcd1.Due_Date__c = system.Today() - 5;
		insert testcd1; 	

		Approval_Step__c aStep = new Approval_Step__c();
		astep.Correspondence_Document__c = testCd1.Id;
		insert aStep;

		Approval_Step_Recall_Request__c stepToRecall = new Approval_Step_Recall_Request__c();
		stepToRecall.Approval_Step__c = aStep.Id;
		stepToRecall.Work_Item_Id__c = '1234567890';
		stepToRecall.Status__c = 'Pending';
		insert stepToRecall;

		Controlled_Document__c testcd2;
		FeedItem post;
		Controlled_Document_Feed__c cdf;
		Controlled_Document_Admin__c cda = new Controlled_Document_Admin__c();
		cda.Name = 'ADMINUSER';
		cda.UserName__c = UserInfo.getUserName();
		insert cda;
		System.runAs(testUser1) {
			// Insert Controlled Document
			testcd2 = new Controlled_Document__c();
			testcd2.ExecSec_Start_Date__c = system.Today() - 7;
			testcd2.ExecSec_Due_Date__c = system.Today() - 5;
			testcd2.ExecSec_End_Date__c = null;
			testcd2.Date_Closed__c = null;
			testcd2.Due_Date_for_Signature__c = system.Today() +5;
			testcd2.Title__c = 'Test Controlled Doc 1' + system.Today();
			testcd2.Correspondence_Type__c = 'Annual Report';
			testcd2.Originating_Office__c = 'A - Office of the Administrator';
			testcd2.OwnerId = testUser1.id;
			testcd2.Stage__c = 'Initiated';
			testcd2.Due_Date__c = system.Today() - 5;
			
			insert testcd2; 	
			post = ControlledDocumentTestUtility.createFeedItem(testcd2.id);
			insert post;
			
			cdf = new Controlled_Document_Feed__c();
			cdf.Controlled_Document__c = testcd2.Id;
			cdf.Status__c = 'Pending';
			cdf.User__c = testUser2.Id;
			insert cdf;
			
		}
		
		Test.startTest();		
		GrantAccessToChatterFileBatch b0 = new GrantAccessToChatterFileBatch();
		ID batchprocessid = Database.executeBatch(b0,1);
		system.assert(batchprocessid != null);
		Test.stopTest();	

	}

	static testMethod void testExecSecOverrides(){

		NotificationItemCreationHandler.isTest = true;

		List<User> existingStandardUsers = ControlledDocumentTestUtility.getStandardUsers(2);
		User testUser1 = existingStandardUsers.get(0);
		User testUser2 = existingStandardUsers.get(1);

		Controlled_Document__c controlDoc = ControlledDocumentTestUtility.createTestControlDoc();
		insert controlDoc;

		Approval_Step__c step = new Approval_Step__c();
		step.Correspondence_Document__c = controlDoc.Id;
		step.Assigned_Approver__c = testUser1.Id;
		insert step;

		ControlledDocumentTestUtility.initiateApprovalStep(step.Id);

		List<ProcessInstanceWorkItem> processInstanceWorkItemList = getProcessWorkItems(step.Id);

		ExecSec_Approval_Step_Override_Request__c request = new ExecSec_Approval_Step_Override_Request__c();
		request.Status__c = 'Pending';
		request.Approval_Step__c = step.Id;
		request.Overridden_By__c = testUser1.Id;
		request.Work_Item_Id__c = processInstanceWorkItemList.get(0).Id;
		insert request;

		Test.startTest();		
		GrantAccessToChatterFileBatch b0 = new GrantAccessToChatterFileBatch();
		ID batchprocessid = Database.executeBatch(b0,1);
		system.assert(batchprocessid != null);
		Test.stopTest();

	}

	static testMethod void testSupplementaryAccessSync(){

		NotificationItemCreationHandler.isTest = true;

		Supplementary_Access_User__c supplement = new Supplementary_Access_User__c();
		supplement.Active__c = true;

		Test.startTest();		
		GrantAccessToChatterFileBatch b0 = new GrantAccessToChatterFileBatch();
		ID batchprocessid = Database.executeBatch(b0,1);
		system.assert(batchprocessid != null);
		Test.stopTest();

	}

	private static List<ProcessInstanceWorkItem> getProcessWorkItems(Id approvalStepId){

		return [SELECT Id, ProcessInstance.TargetObjectId, ProcessInstanceId
				FROM ProcessInstanceWorkItem 
				WHERE ProcessInstance.Status = 'Pending' AND 
					  ProcessInstance.TargetObjectId =: approvalStepId];
					  
	}

}