src/objects/Approval_Step__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>The status of the Approval Step. This value is set by the system and cannot be manually input by users.</description>
        <inlineHelpText>The status of the Approval Step. This value is set by the system and cannot be manually input by users.</inlineHelpText>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Initiated</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Approved w Comments</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Initiated/Closed</fullName>
                </value>
                <value>
                    <fullName>Initiated/Reopened</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Assigned_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Approver assigned to this Approval Step.</description>
        <inlineHelpText>The Approver assigned to this Approval Step.</inlineHelpText>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Approval_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Correspondence_Document__c</fullName>
        <description>The Controlled Document on which this Approval Step is listed.</description>
        <inlineHelpText>The Controlled Document on which this Approval Step is listed.</inlineHelpText>
        <label>Controlled Document</label>
        <referenceTo>Controlled_Document__c</referenceTo>
        <relationshipLabel>Approval Steps</relationshipLabel>
        <relationshipName>Approval_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <description>The date this Approval Step is due.</description>
        <inlineHelpText>The date this Approval Step is due.</inlineHelpText>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Office__c</fullName>
        <description>The Service/Staff Office of the Approver.</description>
        <inlineHelpText>The Service/Staff Office of the Approver.</inlineHelpText>
        <label>Approver&apos;s Service/Staff Office</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>A - Office of the Administrator</fullName>
                </value>
                <value>
                    <fullName>AK - Office of Civil Rights</fullName>
                </value>
                <value>
                    <fullName>B - Office of the Chief Financial Officer</fullName>
                </value>
                <value>
                    <fullName>C - Office of Human Resource Management</fullName>
                </value>
                <value>
                    <fullName>D - Office of Mission Assurance</fullName>
                </value>
                <value>
                    <fullName>E - Office of Small Business Utilization</fullName>
                </value>
                <value>
                    <fullName>G - Civilian Board of Contract Appeals</fullName>
                </value>
                <value>
                    <fullName>H - Office of Administrative Services</fullName>
                </value>
                <value>
                    <fullName>I - Office of the GSA IT</fullName>
                </value>
                <value>
                    <fullName>J - Office of the Inspector General</fullName>
                </value>
                <value>
                    <fullName>L - Office of the General Counsel</fullName>
                </value>
                <value>
                    <fullName>M - Office of Governmentwide Policy</fullName>
                </value>
                <value>
                    <fullName>O - Office of Customer Experience</fullName>
                </value>
                <value>
                    <fullName>P - Public Buildings Service</fullName>
                </value>
                <value>
                    <fullName>Q - Federal Acquisition Service</fullName>
                </value>
                <value>
                    <fullName>S - Office of Congressional and Intergovernmental Affairs</fullName>
                </value>
                <value>
                    <fullName>T - Technology Transformation Service</fullName>
                </value>
                <value>
                    <fullName>Y - Federal Permitting Improvement Steering Council</fullName>
                </value>
                <value>
                    <fullName>Z - Office of Strategic Communication</fullName>
                </value>
                <value>
                    <fullName>Region 1A</fullName>
                </value>
                <value>
                    <fullName>Region 1P</fullName>
                </value>
                <value>
                    <fullName>Region 1Q</fullName>
                </value>
                <value>
                    <fullName>Region 2A</fullName>
                </value>
                <value>
                    <fullName>Region 2P</fullName>
                </value>
                <value>
                    <fullName>Region 2Q</fullName>
                </value>
                <value>
                    <fullName>Region 3A</fullName>
                </value>
                <value>
                    <fullName>Region 3P</fullName>
                </value>
                <value>
                    <fullName>Region 3Q</fullName>
                </value>
                <value>
                    <fullName>Region 4A</fullName>
                </value>
                <value>
                    <fullName>Region 4P</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Role_of_Approver__c</fullName>
        <description>The role the Approver is playing for this Approval Step.</description>
        <inlineHelpText>The role the Approver is playing for this Approval Step.</inlineHelpText>
        <label>Role of Approver</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approver</fullName>
                </value>
                <value>
                    <fullName>Audit Analyst</fullName>
                </value>
                <value>
                    <fullName>Close-Out</fullName>
                </value>
                <value>
                    <fullName>Drafter</fullName>
                </value>
                <value>
                    <fullName>Editor</fullName>
                </value>
                <value>
                    <fullName>Exec Sec Reviewer</fullName>
                </value>
                <value>
                    <fullName>External Review</fullName>
                </value>
                <value>
                    <fullName>FYI</fullName>
                </value>
                <value>
                    <fullName>Office POC</fullName>
                </value>
                <value>
                    <fullName>Signatory</fullName>
                </value>
                <value>
                    <fullName>Subject Matter Expert</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <description>The order in which this Approval Step will appear on the Controlled Document record.</description>
        <inlineHelpText>The order in which this Approval Step will appear on the Controlled Document record.</inlineHelpText>
        <label>Sequence</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>The date this Approval Step was initiated.</description>
        <inlineHelpText>The date this Approval Step was initiated.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Approval Step</label>
    <nameField>
        <displayFormat>CC-Step{0000000}</displayFormat>
        <label>Approval Step ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Controlled_Document__c.object
<CustomObject>
    <fields>
        <fullName>Due_Date__c</fullName>
        <description>The due date for the final signer.</description>
        <inlineHelpText>The due date for the final signer.</inlineHelpText>
        <label>Requested Due Date - Signer</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Originating_Office__c</fullName>
        <inlineHelpText>The division originating or overseeing the Controlled Document. Once a value is selected, users from that Originating Service/Staff Office will be able to access and edit this Controlled Document unless further restrictions are implemented.</inlineHelpText>
        <label>Originating Service/Staff Office</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AK - Office of Civil Rights</fullName>
                </value>
                <value>
                    <fullName>A - Office of the Administrator</fullName>
                </value>
                <value>
                    <fullName>B - Office of the Chief Financial Officer</fullName>
                </value>
                <value>
                    <fullName>C - Office of Human Resource Management</fullName>
                </value>
                <value>
                    <fullName>D - Office of Mission Assurance</fullName>
                </value>
                <value>
                    <fullName>E - Office of Small Business Utilization</fullName>
                </value>
                <value>
                    <fullName>G - Civilian Board of Contract Appeals</fullName>
                </value>
                <value>
                    <fullName>H - Office of Administrative Services</fullName>
                </value>
                <value>
                    <fullName>I - Office of the GSA IT</fullName>
                </value>
                <value>
                    <fullName>J - Office of the Inspector General</fullName>
                </value>
                <value>
                    <fullName>L - Office of the General Counsel</fullName>
                </value>
                <value>
                    <fullName>M - Office of Governmentwide Policy</fullName>
                </value>
                <value>
                    <fullName>O - Office of Customer Experience</fullName>
                </value>
                <value>
                    <fullName>P - Public Buildings Service</fullName>
                </value>
                <value>
                    <fullName>PTT - Presidential Transition Team</fullName>
                </value>
                <value>
                    <fullName>Q - Federal Acquisition Service</fullName>
                </value>
                <value>
                    <fullName>S - Office of Congressional and Intergovernmental Affairs</fullName>
                </value>
                <value>
                    <fullName>T - Technology Transformation Service</fullName>
                </value>
                <value>
                    <fullName>Y - Federal Permitting Improvement Steering Council</fullName>
                </value>
                <value>
                    <fullName>Z - Office of Strategic Communication</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Controlled Document</label>
    <nameField>
        <displayFormat>CC{000000}</displayFormat>
        <label>Document ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Controlled Documents</pluralLabel>
    <recordTypes>
        <fullName>Controlled_Document</fullName>
        <active>true</active>
        <description>Record Type for Controlled Documents</description>
        <label>Controlled Document</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestApprovalStepSelectManager.cls
/*-------------------------------------------------------------------------------------------------*
  TestApprovalStepSelectManager
  Test class for the ApprovalStepSelectManager class.
 *-------------------------------------------------------------------------------------------------*
  Author           | Date        | Version | Description
 *-------------------------------------------------------------------------------------------------*
  Stefan Maurer      11/02/2014    1.0       Created
  Raja Kumar P       03/11/2016    1.1       Updated for case# 22417, 22035
 *-------------------------------------------------------------------------------------------------*/
@isTest
private class TestApprovalStepSelectManager {
    
    @isTest static void testContructorWithoutApprovalSteps() {
        Controlled_Document__c controlDoc = ControlledDocumentTestUtility.createTestControlDoc();
        insert controlDoc;
        
        Test.startTest();
        ApprovalStepSelectManager manager = new ApprovalStepSelectManager(controlDoc.Id);
        Test.stopTest();

        System.assertEquals(1, manager.approvalStepSelects.size(), 'Should only contian new step');
    }
    
    @isTest static void testApprovalStepValidation() {
        Controlled_Document__c controlDoc = ControlledDocumentTestUtility.createTestControlDoc();
        insert controlDoc;
        Approval_Step__c approvalStep = new Approval_Step__c();
        approvalStep.Correspondence_Document__c = controlDoc.Id;
        approvalStep.Sequence__c = '1';
        approvalStep.Start_Date__c = System.today();
        approvalStep.Due_Date__c = System.today()+1;
        approvalStep.Role_of_Approver__c = 'Approver';
        approvalStep.Assigned_Approver__c = UserInfo.getUserId();
        approvalStep.Approval_Status__c = 'Not Initiated';
        insert approvalStep;
        approvalStep.Due_Date__c = System.today()-1;
        approvalStep.Approval_Status__c = 'Initiated';
        try {
            update approvalStep;
        }
        catch(DMLException e) {
            System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION', e.getDmlStatusCode(0));   
        }
    }
    
    @isTest static void testApprovalStepBulkInitiation() {
        Controlled_Document__c controlDoc = ControlledDocumentTestUtility.createTestControlDoc();
        insert controlDoc;
        List<Approval_Step__c> stepList = new List<Approval_Step__c>();
        // case# 25836 - added condition to exclude the users with inactive delegatedapprovers
        List<User> users = [SELECT Id FROM User WHERE UserType='Standard' AND IsActive=true AND DelegatedApproverId = null LIMIT 200];
        //List<PermissionSet> psets = new List<PermissionSet>([SELECT Id, Name FROM PermissionSet WHERE Name Like 'Controlled_Document%']);
        //TestApprovalStepSelectManager.assignPsets(psets[0].Id, users);
        for(Integer i =0; i<200; i++) {
            Approval_Step__c approvalStep = new Approval_Step__c();
            approvalStep.Correspondence_Document__c = controlDoc.Id;
            approvalStep.Sequence__c = '1';
            approvalStep.Start_Date__c = System.today();
            approvalStep.Due_Date__c = System.today()+1;
            approvalStep.Role_of_Approver__c = 'Approver';
            approvalStep.Assigned_Approver__c = users[i].Id;
            approvalStep.Approval_Status__c = 'Not Initiated';
            stepList.add(approvalStep);
        }
        insert stepList;
        for(Integer i =0; i<200; i++) {
            stepList[i].Approval_Status__c = 'Initiated';
        }
        Test.startTest();
        update stepList;
        Test.stopTest();        
        System.assertEquals(200, [SELECT Id FROM Approval_Step__c WHERE Approval_Status__c='Initiated'].size());   
        
    }
    
    @isTest static void testContructorWithApprovalSteps() {
        Controlled_Document__c controlDoc = ControlledDocumentTestUtility.createTestControlDoc();
        insert controlDoc;
        insert ControlledDocumentTestUtility.createApprovalStep(controlDoc.id, '1', UserInfo.getUserId());
        
        Test.startTest();
        ApprovalStepSelectManager manager = new ApprovalStepSelectManager(controlDoc.Id);
        Test.stopTest();

        System.assertEquals(2, manager.approvalStepSelects.size(), 'Should contian new step and existing approval step.');
    }

    @isTest static void testFailedSave() {
        Controlled_Document__c controlDoc = ControlledDocumentTestUtility.createTestControlDoc();
        insert controlDoc;
        Approval_Step__c step = ControlledDocumentTestUtility.createApprovalStep(controlDoc.id, '1', UserInfo.getUserId());
        insert step;
        ApprovalStepSelectManager manager = new ApprovalStepSelectManager(controlDoc.Id);
        manager.approvalStepSelects.get(0).ApprovalStep.Office__c = null;

        Boolean testResult;
        Test.startTest();
        testResult = manager.save();
        Test.stopTest();

        Approval_Step__c resultStep = ControlledDocumentTestUtility.getApprovalStep(step.id);
        System.assertEquals(false, testResult, 'Saving process should have failed.');
        System.assertEquals(step.Office__c, resultStep.Office__c, 'Office should have remained unchanged since the save failed.');
    }

    @isTest static void testSuccessfulSave() {
        Controlled_Document__c controlDoc = ControlledDocumentTestUtility.createTestControlDoc();
        insert controlDoc;
        Approval_Step__c step = ControlledDocumentTestUtility.createApprovalStep(controlDoc.id, '1', UserInfo.getUserId());
        insert step;
        ApprovalStepSelectManager manager = new ApprovalStepSelectManager(controlDoc.Id);
        manager.approvalStepSelects.get(0).ApprovalStep.Office__c = 'testOffice';

        Boolean testResult;
        Test.startTest();
        testResult = manager.save();
        Test.stopTest();

        Approval_Step__c resultStep = ControlledDocumentTestUtility.getApprovalStep(step.id);
        System.assertEquals(true, testResult, 'Saving process should have failed.');
        System.assertEquals('testOffice', resultStep.Office__c, 'Office should have been set and saved successfully.');
    }

    @isTest static void testInitiation(){
        Controlled_Document__c controlDoc = ControlledDocumentTestUtility.createTestControlDoc();
        insert controlDoc;
        Approval_Step__c step1 = ControlledDocumentTestUtility.createApprovalStep(controlDoc.id, '1', UserInfo.getUserId());
        Approval_Step__c step2 = ControlledDocumentTestUtility.createApprovalStep(controlDoc.id, '2', UserInfo.getUserId());
        insert new List<Approval_Step__c>{step1, step2};
        ApprovalStepSelectManager manager = new ApprovalStepSelectManager(controlDoc.Id);
        manager.approvalStepSelects.get(0).selected = true;
        manager.approvalStepSelects.get(1).selected = true;
        ControlledDocumentTestUtility.initiateApprovalStep(step2.id);

        Test.startTest();
        manager.initiateSelected();
        Test.stopTest();

        System.assertEquals(1, ControlledDocumentTestUtility.getProcessWorkItem(step1.Id).size(), 'A in progress approval should exist for this approval step.');
        System.assertEquals(1, ControlledDocumentTestUtility.getProcessWorkItem(step2.Id).size(), 'Initiation should not have created a duplicate approval process.');
        System.assertEquals(false, manager.approvalStepSelects.get(0).selected, 'Selected value should have been reset to false.');
        System.assertEquals(false, manager.approvalStepSelects.get(1).selected, 'Selected value should have been reset to false.');
    }

    // this recall test is done 'naturally' in that it doesn't require custom code
    // a single user creates an approval step, initiates it, and then recalls it
    // this is standard Salesforce functionality via their approval API
    @isTest static void testNaturalRecall(){
        Controlled_Document__c controlDoc = ControlledDocumentTestUtility.createTestControlDoc();
        insert controlDoc;
        Approval_Step__c step = ControlledDocumentTestUtility.createApprovalStep(controlDoc.id, '1', UserInfo.getUserId());
        insert step;
        ApprovalStepSelectManager manager = new ApprovalStepSelectManager(controlDoc.Id);
        manager.approvalStepSelects.get(0).selected = true;
        ControlledDocumentTestUtility.initiateApprovalStep(step.id);

        Test.startTest();
        manager.recallSelected();
        Test.stopTest();

        System.assertEquals(0, ControlledDocumentTestUtility.getProcessWorkItem(step.Id).size(), 'The approval process should no longer exist.');
        System.assertEquals(false, manager.approvalStepSelects.get(0).selected, 'Selected value should have been reset to false.');
    }

    // using SeeAllDate because of an issue where creating users failed at line 19 in UserToChatterMessage.cls which is not our code
    @isTest(SeeAllData=true) static void testAssignedApproverRecall(){
        // this flag avoids the callout in the ApprovalStepSelectManager; we test the callout in a separate method
        ApprovalStepSelectManager.isRecallTest = true;

        Controlled_Document__c controlledDocument;
        Approval_Step__c approvalStep;
        ApprovalStepSelectManager manager;

        Profile stdUserProfile = [SELECT Id FROM Profile WHERE Name = 'Standard User'];
        Profile adminUserProfile = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];

        // create non admin user
        User stdUser1 = new User();
        stdUser1.FirstName = 'John';
        stdUser1.LastName = 'DoeTEST';
        stdUser1.ProfileId = stdUserProfile.Id;
        stdUser1.Affiliation__c = 'Contractor';
        stdUser1.Email = stdUser1.FirstName + '@test.com';
        stdUser1.Username = stdUser1.FirstName + '@gsa.gov.thisisatest';
        stdUser1.CommunityNickname = stdUser1.FirstName + stdUser1.LastName + 'gsagovtest';
        stdUser1.TimeZoneSidKey = 'America/New_York';
        stdUser1.LocaleSidKey = 'en_US';
        stdUser1.EmailEncodingKey = 'ISO-8859-1';
        stdUser1.LanguageLocaleKey='en_US';
        stdUser1.Alias = 'jdoetest';
        insert stdUser1;

        // create admin user
        User adminUser = new User();
        adminUser.FirstName = 'Admin';
        adminUser.LastName = 'AdminTEST';
        adminUser.ProfileId = adminUserProfile.Id;
        adminUser.Affiliation__c = 'Contractor';
        adminUser.Email = adminUser.FirstName + '@test.com';
        adminUser.Username = adminUser.FirstName + '@gsa.gov.thisisatest';
        adminUser.CommunityNickname = adminUser.FirstName + adminUser.LastName + 'gsagovtest';
        adminUser.TimeZoneSidKey = 'America/New_York';
        adminUser.LocaleSidKey = 'en_US';
        adminUser.EmailEncodingKey = 'ISO-8859-1';
        adminUser.LanguageLocaleKey='en_US';
        adminUser.Alias = 'admintes';
        insert adminUser;
        List<PermissionSet> psetList = new List<PermissionSet>([SELECT Id FROM PermissionSet WHERE Name Like 'Controlled_Document%']);
		PermissionSetAssignment passign = new PermissionSetAssignment();
        passign.AssigneeId = stdUser1.Id;
        passign.PermissionSetId = psetList[0].Id;
        insert passign;
        // create controlled document with non admin user
        System.runAs(stdUser1){
            controlledDocument = new Controlled_Document__c();
            controlledDocument.Originating_Office__c = 'AK - Office of Civil Rights';
            insert controlledDocument;
        }

        // create approval step as admin user and assign it to non admin user
        System.runAs(adminUser){
            approvalStep = new Approval_Step__c();
            approvalStep.Correspondence_Document__c = controlledDocument.Id;
            approvalStep.Sequence__c = '1';
            approvalStep.Due_Date__c = System.today();
            approvalStep.Role_of_Approver__c = 'Approver';
            approvalStep.Assigned_Approver__c = stdUser1.Id;
            approvalStep.Approval_Status__c = 'Not Initiated';
            insert approvalStep;

            // initiate it as admin user
            manager = new ApprovalStepSelectManager(controlledDocument.Id);
            manager.approvalStepSelects.get(0).selected = true;
            Approval.ProcessSubmitRequest submitRequest = new Approval.ProcessSubmitRequest();
            submitRequest.setObjectId(approvalStep.Id);
            submitRequest.setSubmitterId(adminUser.Id);
            Approval.process(submitRequest);
        }

        System.runAs(stdUser1){
            
            manager.recallSelected();
        }

        System.assertEquals(1, ControlledDocumentTestUtility.getProcessWorkItem(approvalStep.Id).size());
    }


    @isTest(SeeAllData=true) static void testImproperUserRecall(){ 
        // this flag avoids the callout in the ApprovalStepSelectManager; we test the callout in a separate method
        ApprovalStepSelectManager.isRecallTest = true;

        Controlled_Document__c controlledDocument;
        Approval_Step__c approvalStep;
        ApprovalStepSelectManager manager;

        Profile stdUserProfile = [SELECT Id FROM Profile WHERE Name = 'Standard User'];
        Profile adminUserProfile = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];

        // create non admin user
        User stdUser1 = new User();
        stdUser1.FirstName = 'John';
        stdUser1.LastName = 'DoeTEST';
        stdUser1.ProfileId = stdUserProfile.Id;
        stdUser1.Affiliation__c = 'Contractor';
        stdUser1.Email = stdUser1.FirstName + '@test.com';
        stdUser1.Username = stdUser1.FirstName + '@gsa.gov.thisisatest';
        stdUser1.CommunityNickname = stdUser1.FirstName + stdUser1.LastName + 'gsagovtest';
        stdUser1.TimeZoneSidKey = 'America/New_York';
        stdUser1.LocaleSidKey = 'en_US';
        stdUser1.EmailEncodingKey = 'ISO-8859-1';
        stdUser1.LanguageLocaleKey='en_US';
        stdUser1.Alias = 'jdoetest';
        insert stdUser1;

        // create admin user
        User adminUser = new User();
        adminUser.FirstName = 'Admin';
        adminUser.LastName = 'AdminTEST';
        adminUser.ProfileId = adminUserProfile.Id;
        adminUser.Affiliation__c = 'Contractor';
        adminUser.Email = adminUser.FirstName + '@test.com';
        adminUser.Username = adminUser.FirstName + '@gsa.gov.thisisatest';
        adminUser.CommunityNickname = adminUser.FirstName + adminUser.LastName + 'gsagovtest';
        adminUser.TimeZoneSidKey = 'America/New_York';
        adminUser.LocaleSidKey = 'en_US';
        adminUser.EmailEncodingKey = 'ISO-8859-1';
        adminUser.LanguageLocaleKey='en_US';
        adminUser.Alias = 'admintes';
        insert adminUser;
		List<PermissionSet> psetList = new List<PermissionSet>([SELECT Id FROM PermissionSet WHERE Name Like 'Controlled_Document%']);
		PermissionSetAssignment passign = new PermissionSetAssignment();
        passign.AssigneeId = adminUser.Id;
        passign.PermissionSetId = psetList[0].Id;
        insert passign;
        
        // create controlled document with admin user
        System.runAs(adminUser){
            controlledDocument = new Controlled_Document__c();
            controlledDocument.Originating_Office__c = 'AK - Office of Civil Rights';
            insert controlledDocument;

            // create approval step as admin user and assign it to himself
            approvalStep = new Approval_Step__c();
            approvalStep.Correspondence_Document__c = controlledDocument.Id;
            approvalStep.Sequence__c = '1';
            approvalStep.Due_Date__c = System.today();
            approvalStep.Role_of_Approver__c = 'Approver';
            approvalStep.Assigned_Approver__c = adminUser.Id;
            approvalStep.Approval_Status__c = 'Not Initiated';
            insert approvalStep;

            // initiate it as admin user
            manager = new ApprovalStepSelectManager(controlledDocument.Id);
            manager.approvalStepSelects.get(0).selected = true;
            Approval.ProcessSubmitRequest submitRequest = new Approval.ProcessSubmitRequest();
            submitRequest.setObjectId(approvalStep.Id);
            submitRequest.setSubmitterId(adminUser.Id);
            Approval.process(submitRequest);
        }

        System.runAs(stdUser1){
            // the user is not approved to do such a thing so it will fail
            manager.recallSelected();
        }

        System.assertEquals(1, ControlledDocumentTestUtility.getProcessWorkItem(approvalStep.Id).size());
    }

    @isTest static void testClearNewRow(){
        Controlled_Document__c controlDoc = ControlledDocumentTestUtility.createTestControlDoc();
        insert controlDoc;
        ApprovalStepSelectManager manager = new ApprovalStepSelectManager(controlDoc.Id);
        manager.approvalStepSelects.get(0).ApprovalStep.Office__c = 'testOffice';

        Test.startTest();
        manager.clearNewRow();
        Test.stopTest();

        System.assertEquals(null, manager.approvalStepSelects.get(0).ApprovalStep.Office__c, 'Value should have reverted to null.');
    }

    @isTest static void testBackupRestore(){
        Controlled_Document__c controlDoc = ControlledDocumentTestUtility.createTestControlDoc();
        insert controlDoc;
        Approval_Step__c step = ControlledDocumentTestUtility.createApprovalStep(controlDoc.id, '1', UserInfo.getUserId());
        insert step;
        ApprovalStepSelectManager manager = new ApprovalStepSelectManager(controlDoc.Id);
        manager.approvalStepSelects.get(0).ApprovalStep.Office__c = 'testOffice1';

        Test.startTest();
        manager.backup();
        manager.approvalStepSelects.get(0).ApprovalStep.Office__c = 'testOffice2';
        manager.restore();
        Test.stopTest();

        System.assertEquals('testOffice1', manager.approvalStepSelects.get(0).ApprovalStep.Office__c, 'Office should have been reverted.');
    }

    @isTest static void testPopulateExternalReviewParty(){
        Controlled_Document__c controlDoc = ControlledDocumentTestUtility.createTestControlDoc();
        insert controlDoc;
        Approval_Step__c step1 = ControlledDocumentTestUtility.createApprovalStep(controlDoc.id, '1', UserInfo.getUserId());
        Approval_Step__c step2 = ControlledDocumentTestUtility.createApprovalStep(controlDoc.id, '2', UserInfo.getUserId());
        Approval_Step__c step3 = ControlledDocumentTestUtility.createApprovalStep(controlDoc.id, '3', UserInfo.getUserId());
        insert new List<Approval_Step__c>{step1, step2, step3};
        ApprovalStepSelectManager manager = new ApprovalStepSelectManager(controlDoc.Id);
        manager.approvalStepSelects.get(0).ApprovalStep.Role_Of_Approver__c = ControlledDocumentConstants.EXTERNAL_REVIEW_ROLE_NAME;
        manager.approvalStepSelects.get(1).ApprovalStep.Role_Of_Approver__c = ControlledDocumentConstants.EXTERNAL_REVIEW_ROLE_NAME;
        manager.approvalStepSelects.get(1).ApprovalStep.External_Review_Party__c = 'testExternalReviewParty';
        manager.approvalStepSelects.get(2).ApprovalStep.External_Review_Party__c = 'testExternalReviewParty';

        Test.startTest();
        manager.populateExternalReviewParty();
        Test.stopTest();

        System.assertEquals(ControlledDocumentConstants.EXTERNAL_REVIEW_AUTOFILL_VALUE, manager.approvalStepSelects.get(0).ApprovalStep.External_Review_Party__c, 'Review party should have been autofilled.');
        System.assertEquals('testExternalReviewParty', manager.approvalStepSelects.get(1).ApprovalStep.External_Review_Party__c, 'Review party should not have been autofilled.');
        System.assertEquals(null, manager.approvalStepSelects.get(2).ApprovalStep.External_Review_Party__c, 'Review party should have been cleared');
    }

    @isTest static void testAddRemoveNewStep(){
        Controlled_Document__c controlDoc = ControlledDocumentTestUtility.createTestControlDoc();
        insert controlDoc;
        ApprovalStepSelectManager manager = new ApprovalStepSelectManager(controlDoc.Id);

        Test.startTest();
        manager.removeNewStep();
        manager.addNewStep();
        Test.stopTest();

        System.assertEquals(1, manager.approvalStepSelects.size(), 'New step should have been removed and re-added, leaving 1 step in the list.');
    }

    @isTest static void testInsertNewStep(){
        Controlled_Document__c controlDoc = ControlledDocumentTestUtility.createTestControlDoc();
        insert controlDoc;
        ApprovalStepSelectManager manager = new ApprovalStepSelectManager(controlDoc.Id);
        ControlledDocumentTestUtility.setApprovalStepRequiredFields(manager.approvalStepSelects.get(0).ApprovalStep, '1', UserInfo.getUserId());
        manager.approvalStepSelects.get(0).ApprovalStep.Office__c = 'testOffice';

        Test.startTest();
        manager.insertNewStep();
        Test.stopTest();

        System.assertEquals(2, manager.approvalStepSelects.size(), 'List should include both a new row and the inserted row.');
        System.assertEquals('testOffice', manager.approvalStepSelects.get(0).ApprovalStep.Office__c, 'The first approval step should be the one that was inserted.');
    }
    /*
    static void assignPsets(Id psetId, List<User> users) {
        List<PermissionSetAssignment> passignList = new List<PermissionSetAssignment>();
        Map<Id, Id> passignMap = new Map<Id, Id>();
        Set<Id> userIds = new Set<Id>();
        for(User u : users) {
            userIds.add(u.Id);
        }
        for(PermissionSetAssignment pa : [SELECT Id, AssigneeId FROM PermissionSetAssignment WHERE AssigneeId IN :userIds AND 
                                          PermissionSet.Name Like 'Controlled_Document%']) {
                                              if(!passignMap.containsKey(pa.AssigneeId))
                                              passignMap.put(pa.assigneeId, pa.Id);
                                          }
        for(User u : users) {
            if(!passignMap.containskey(u.Id))
            passignList.add(new PermissionSetAssignment(AssigneeId=u.Id, PermissionSetId=psetId));
        }
        insert passignList;
    }
    */
    @isTest static void testApprovalStepUserValidation() {
        //Controlled_Document__c controlDoc = ControlledDocumentTestUtility.createTestControlDoc();
        //insert controlDoc;
        Set<Id> userIds = new Set<Id>();
        for(PermissionSetAssignment pa : [SELECT Id, AssigneeId FROM PermissionSetAssignment WHERE AssigneeId IN :userIds AND 
                                          PermissionSet.Name Like 'Controlled_Document%']) {
                                              userIds.add(pa.AssigneeId);
                                          }
        List<User> users = new List<User>([SELECT Id FROM User WHERE Id NOT IN :userIds AND IsActive=true AND UserType='Standard' LIMIT 5]);
        System.runAs(users[0]) {
            Controlled_Document__c controlledDocument = new Controlled_Document__c();
            controlledDocument.Originating_Office__c = 'AK - Office of Civil Rights';
            insert controlledDocument;
            Approval_Step__c approvalStep = new Approval_Step__c();
            approvalStep.Correspondence_Document__c = controlledDocument.Id;
            approvalStep.Sequence__c = '1';
            approvalStep.Start_Date__c = System.today();
            approvalStep.Due_Date__c = System.today()+1;
            approvalStep.Role_of_Approver__c = 'Approver';
            approvalStep.Assigned_Approver__c = users[0].Id;
            approvalStep.Approval_Status__c = 'Not Initiated';
            //insert approvalStep;
            //approvalStep.Due_Date__c = System.today()-1;
            //approvalStep.Approval_Status__c = 'Initiated';
            //approvalStep.Assigned_Approver__c = users[0].Id;        
            try {
                insert approvalStep;
            }
            catch(DMLException e) {
                System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION', e.getDmlStatusCode(0));   
            }
        }    
    }
}