src/objects/Approval_Step__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>The status of the Approval Step. This value is set by the system and cannot be manually input by users.</description>
        <inlineHelpText>The status of the Approval Step. This value is set by the system and cannot be manually input by users.</inlineHelpText>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Initiated</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Approved w Comments</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Initiated/Closed</fullName>
                </value>
                <value>
                    <fullName>Initiated/Reopened</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Assigned_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Approver assigned to this Approval Step.</description>
        <inlineHelpText>The Approver assigned to this Approval Step.</inlineHelpText>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Approval_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Correspondence_Document__c</fullName>
        <description>The Controlled Document on which this Approval Step is listed.</description>
        <inlineHelpText>The Controlled Document on which this Approval Step is listed.</inlineHelpText>
        <label>Controlled Document</label>
        <referenceTo>Controlled_Document__c</referenceTo>
        <relationshipLabel>Approval Steps</relationshipLabel>
        <relationshipName>Approval_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Approval Step</label>
    <nameField>
        <displayFormat>CC-Step{0000000}</displayFormat>
        <label>Approval Step ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Controlled_Document__c.object
<CustomObject>
    <label>Controlled Document</label>
    <nameField>
        <displayFormat>CC{000000}</displayFormat>
        <label>Document ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Controlled Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Controlled_Document_Feed__c.object
<CustomObject>
    <description>This Object is being used by the Controlled Document Tracker application.</description>
    <fields>
        <fullName>Approval_Step_Delegate_Origin__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approval Step Delegate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Controlled_Document__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Controlled Document</label>
        <referenceTo>Controlled_Document__c</referenceTo>
        <relationshipName>Controlled_Document_Feed</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quick_Share_Origin__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Quick Share?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.UserType</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Controlled_Document_Feed</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Grant Update Access Request</label>
    <nameField>
        <displayFormat>GUA-{0000000}</displayFormat>
        <label>Grant Update Access Requests</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grant Update Access Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Supplementary_Access_User__c.object
<CustomObject>
    <description>A record for consolidating various controlled document sharing permissions from a verity of custom and apex sources,</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Approval_Step__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approval Step (If Applicable)</label>
        <referenceTo>Approval_Step__c</referenceTo>
        <relationshipLabel>Supplementary Access History</relationshipLabel>
        <relationshipName>Supplementary_Access_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Controlled_Document__c</fullName>
        <label>Controlled Document</label>
        <referenceTo>Controlled_Document__c</referenceTo>
        <relationshipLabel>Supplementary Access History</relationshipLabel>
        <relationshipName>CD_Add_on_Sharing_Users</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Inactivated_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inactivated By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CD_Add_on_Sharing_Users1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Inactivation_Date__c</fullName>
        <label>Inactivation Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Origin__c</fullName>
        <label>Origin</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Originating_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Originating User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CD_Add_on_Sharing_Users2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CD_Add_on_Sharing_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Supplementary Access User</label>
    <nameField>
        <displayFormat>SAU-{0000000000}</displayFormat>
        <label>Supplementary Access User Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplementary Access History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SupplementaryAccessUserGranterUser.cls
public class SupplementaryAccessUserGranterUser{

	public static void updateSupplementsForDelegates(List<User> oldUserList, List<User> newUserList){

		Map<Id, Id> userIdToNewDelegateIdMap = new Map<Id, Id>();
		for(User oldUser : oldUserList){
			for(User newUser : newUserList) {
				if(oldUser.Id != newUser.Id) continue;
				if(oldUser.DelegatedApproverId != newUser.DelegatedApproverId && newUser.DelegatedApproverId != null){

					userIdToNewDelegateIdMap.put(newUser.Id, newUser.DelegatedApproverId);

				}
			}
		}

		addNewDelegatedSupplements(userIdToNewDelegateIdMap);

	}

	private static void addNewDelegatedSupplements(Map<Id, Id> userToNewDelegateMap){

		List<Approval_Step__c> relevantApprovalSteps = [
												SELECT Id, Assigned_Approver__c, Approval_Status__c, Correspondence_Document__c 
												FROM Approval_Step__c 
												WHERE Approval_Status__c = 'Initiated' 
												AND Assigned_Approver__c IN :userToNewDelegateMap.keySet()];

		List<Supplementary_Access_User__c> relevantQuickShares = [
														SELECT Id, Active__c, Controlled_Document__c, Inactivated_By__c, Inactivation_Date__c, Origin__c, Originating_User__c, User__c
														FROM Supplementary_Access_User__c
														WHERE Active__c = true
														AND User__c IN :userToNewDelegateMap.keySet()
														AND Origin__c = 'Quick Share'
													];

		List<Supplementary_Access_User__c> supplementsToCreate = new List<Supplementary_Access_User__c>();
		List<Controlled_Document_Feed__c> batchItemsToAdd = new List<Controlled_Document_Feed__c>();

		for(Approval_Step__c step : relevantApprovalSteps){

			//if(userToNewDelegateMap.get(originatingUser) == null) continue; // we check for empty delegates in updateSupplementsForDelegates()

			Id originatingUser = step.Assigned_Approver__c;

			Supplementary_Access_User__c newSupplement = new Supplementary_Access_User__c();
			newSupplement.Active__c = true;
			newSupplement.Approval_Step__c = step.Id;
			newSupplement.Controlled_Document__c = step.Correspondence_Document__c;
			newSupplement.Origin__c = 'Delegate';
			newSupplement.Originating_User__c = originatingUser;
			newSupplement.User__c = userToNewDelegateMap.get(originatingUser);
			supplementsToCreate.add(newSupplement);

			// GRANTS ACCESS TO CHATTER FILES
			Controlled_Document_Feed__c batchItem = new Controlled_Document_Feed__c();
			batchItem.Controlled_Document__c = newSupplement.Controlled_Document__c;
			batchItem.Status__c = 'Pending';
			batchItem.User__c = newSupplement.User__c;
			batchItem.Approval_Step_Delegate_Origin__c = true;
			batchItemsToAdd.add(batchItem);

		}

		for(Supplementary_Access_User__c quickShare : relevantQuickShares){

			Id originatingUser = quickShare.User__c;

			Supplementary_Access_User__c newSupplement = new Supplementary_Access_User__c();
			newSupplement.Active__c = true;
			newSupplement.Controlled_Document__c = quickShare.Controlled_Document__c;
			newSupplement.Origin__c = 'Delegate';
			newSupplement.Originating_User__c = originatingUser;
			newSupplement.User__c = userToNewDelegateMap.get(originatingUser);
			supplementsToCreate.add(newSupplement);

			// GRANTS ACCESS TO CHATTER FILES
			Controlled_Document_Feed__c batchItem = new Controlled_Document_Feed__c();
			batchItem.Controlled_Document__c = newSupplement.Controlled_Document__c;
			batchItem.Status__c = 'Pending';
			batchItem.User__c = newSupplement.User__c;
			batchItem.Quick_Share_Origin__c = true;
			batchItemsToAdd.add(batchItem);
		}

		insert supplementsToCreate;
		insert batchItemsToAdd;

	}

}