src/objects/Attendee__c.object
<CustomObject>
    <description>Tracks the Attendees for Conferences and Events tracked through the Event Approval application. This object will have a separate approval process from the Event or conference</description>
    <fields>
        <fullName>Event_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event Identifier</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 3)</booleanFilter>
            <errorMessage>Please select a GSA Sponsored Conference or Non GSA Sponsored Conference only.</errorMessage>
            <filterItems>
                <field>Event_Approval__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>GSA Sponsored Conference, Non GSA Sponsored Conference</value>
            </filterItems>
            <filterItems>
                <field>Event_Approval__c.EA_End_Date__c</field>
                <operation>greaterOrEqual</operation>
                <valueField>$Source.CreatedDate</valueField>
            </filterItems>
            <filterItems>
                <field>Event_Approval__c.Event_Type_Hidden__c</field>
                <operation>notEqual</operation>
                <value>Over</value>
            </filterItems>
            <infoMessage>Please select a GSA Sponsored Conference or Non GSA Sponsored Conference. Attendee requests for Internal Management Meetings and Award Ceremonies are not required.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Event_Approval__c</referenceTo>
        <relationshipLabel>Attendees</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HSSO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Who is my HSSO approver? 
See GSA HSSO Approver Listing at https://insite.gsa.gov/portal/content/669402</inlineHelpText>
        <label>HSSO</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Attendees2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supervisor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Attendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Estimated_Expenses_t__c</fullName>
        <label>Total Estimated Expenses_t</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>Attendee # {00000000}</displayFormat>
        <label>Attendee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Attendee_Expense__c.object
<CustomObject>
    <description>This is an add on to the Event Approval application. This would be to track the expenses of any individual attendees that wish attend either a GSA sponsored conference or a Non GSA sponsored conference.</description>
    <fields>
        <fullName>Attendee__c</fullName>
        <label>Attendee</label>
        <referenceTo>Attendee__c</referenceTo>
        <relationshipLabel>Attendee Expenses</relationshipLabel>
        <relationshipName>Attendee_Expenses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Attendee Expense</label>
    <nameField>
        <displayFormat>Attendee Exp #-{0000000000}</displayFormat>
        <label>Attendee Expenses Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendee Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Event_Approval__c.object
<CustomObject>
    <description>The Conference Planning application provides an automated request, audit , approval, and
organization processes for Agency Conferences, Awards Ceremonies (with food), and Internal Management Meetings via the Salesforce cloud platform. This application is the required entry point for Event Coordinators, Finance, Contracting, Public Affairs, Procurement, and Leadership to coordinate requests submitted to the Office of Administrative Services; who will review and approve these requests, before an event can move forward.</description>
    <fields>
        <fullName>HSSO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Who is my HSSO approver? 
See GSA HSSO Approver Listing at https://insite.gsa.gov/portal/content/669402</inlineHelpText>
        <label>HSSO</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Event_Approvals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supervisor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Event_Approvals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Estimated_Attendee_Expenses__c</fullName>
        <label>Total Estimated Attendee Expenses</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Event Approval</label>
    <nameField>
        <label>Event Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Approvals</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/AttendeeRollUpHelper.cls
/* ----------------------------------------------------------------------------------
   Calculate the roll up summary field on Event Approval record when users 
   insert/update/delete Attendee record 
-------------------------------------------------------------------------------------
    Author        | Date     | Version | Descripton
-------------------------------------------------------------------------------------
    Rajakumar       12/13/12   1.0       Initial Draft
    Rajakumar       05/06/14   2.0       updated for apex sharing for HSSO and Supervisor
    Rajakumar       08/19/14   3.0       Undo the changes made in 2.0
-------------------------------------------------------------------------------------    
*/
public class AttendeeRollUpHelper {
  
  // method will be invoked for roll up summary
  public static void onAfterUpsertorDelete(List<Attendee__c> triggerNeworOld) {
      //Limit the size of list by using Sets which do not contain duplicate elements
      Set<Id> EventApprovalIds = new Set<Id>();
 
      for(Attendee__c a : triggerNeworOld){
          EventApprovalIds.add(a.Event_Number__c);
      }
      
      //Map will contain one Event Approval Id to one sum value
      Map<Id, Double> EventApprovalMap = new Map<Id, Double>();
 
      //Produce a sum of Attendee_Expense__c and add them to the map
      //use group by to have a single Opportunity Id with a single sum value
      for(AggregateResult q : [select Event_Number__c,sum(Total_Estimated_Expenses_t__c) totalExpSum
          from Attendee__c where Event_Number__c IN :EventApprovalIds group by Event_Number__c]){
          EventApprovalMap.put((Id)q.get('Event_Number__c'),(Double)q.get('totalExpSum'));
      }
 
      List<Event_Approval__c> EventApprovalsToUpdate = new List<Event_Approval__c>();
 
      //Run the for loop on Event Approval using the non-duplicate set of Event Approval Ids
      //Get the sum value from the map and create a list of Event Approvals to update
      for(Event_Approval__c a : [Select Id, Total_Estimated_Attendee_Expenses__c from Event_Approval__c where Id IN :EventApprovalIds]){
          Double EstimatedExpSum = EventApprovalMap.get(a.Id);
          a.Total_Estimated_Attendee_Expenses__c = EstimatedExpSum;
          EventApprovalsToUpdate.add(a);
      }
 
      update EventApprovalsToUpdate;
  }
  /* -- Ver 3.0 Comment the code changes made in 2.0 -- BEGIN --
  // -- Ver 2.0 -- Added for the apex Record Sharing -- BEGIN -- //
  // process the records when insert operation is performed.
    public static void recordInsertSharing(List<Attendee__c> triggerNew) {
        List<RecordSharingUtil.RecordSharingDefiniation> newAttShares = new List<recordSharingUtil.RecordSharingDefiniation>();
        String supervisor, hsso, recId;
        // list of new records
        for(Attendee__c attendee: triggerNew) {
            // HSSO field is not null
            if(attendee.HSSO__c != null) {
                hsso = attendee.HSSO__c;
                recId = attendee.Id;
                newAttShares.add(new recordSharingUtil.RecordSharingDefiniation(recId, hsso, 'Edit', 'HSSO__c'));
            }
            // Supervisor field is not null
            if(attendee.Supervisor__c != null) {
                supervisor = attendee.Supervisor__c;
                recId = attendee.Id;
                newAttShares.add(new recordSharingUtil.RecordSharingDefiniation(recId, supervisor, 'Edit', 'Supervisor__c'));
            }    
        }
        //insert the apex sharing by using utility
        if(!newAttShares.isEmpty())
            RecordSharingUtil.share(newAttShares);
    }
    
    // process the records when update operation is performed
    public static void recordUpdateSharing(List<Attendee__c> triggerNew, Map<Id, Attendee__c> triggerOldMap) {
        List<RecordSharingUtil.RecordSharingDefiniation> newAttShares = new List<recordSharingUtil.RecordSharingDefiniation>();
        List<RecordSharingUtil.RecordSharingDefiniation> oldAttShares = new List<recordSharingUtil.RecordSharingDefiniation>();
    
        String supervisor, hsso, recId, prevSupervisor, prevHsso;
        // list of updated records
        for(Attendee__c attendee: triggerNew) {
            // HSSO field update
            if(attendee.HSSO__c != null && triggerOldMap.get(attendee.Id).HSSO__c != attendee.HSSO__c) {
                hsso = attendee.HSSO__c;
                recId = attendee.Id;
                newAttShares.add(new recordSharingUtil.RecordSharingDefiniation(recId, hsso, 'Edit', 'HSSO__c'));
            }
            if(triggerOldMap.get(attendee.Id).HSSO__c != attendee.HSSO__c && 
                triggerOldMap.get(attendee.Id).HSSO__c != null) {
                prevHsso = triggerOldMap.get(attendee.Id).HSSO__c;
                recId = attendee.Id;
                oldAttShares.add(new recordSharingUtil.RecordSharingDefiniation(recId, prevHsso, 'Edit', 'HSSO__c'));
            }
            //Supervisor field update
            if(attendee.Supervisor__c != null && triggerOldMap.get(attendee.Id).Supervisor__c != attendee.Supervisor__c) {
                supervisor = attendee.Supervisor__c;
                recId = attendee.Id;
                newAttShares.add(new recordSharingUtil.RecordSharingDefiniation(recId, supervisor, 'Edit', 'Supervisor__c'));
            }
            if(triggerOldMap.get(attendee.Id).Supervisor__c != attendee.Supervisor__c && 
                triggerOldMap.get(attendee.Id).Supervisor__c != null) {
                prevSupervisor = triggerOldMap.get(attendee.Id).Supervisor__c;
                recId = attendee.Id;
                oldAttShares.add(new recordSharingUtil.RecordSharingDefiniation(recId, prevSupervisor, 'Edit', 'Supervisor__c'));
            }
        }
        // insert the apex sharing entries by using utility
        if(!newAttShares.isEmpty())
            RecordSharingUtil.share(newAttShares);
        // delete the apex sharing entries by using utility
        if(!oldAttShares.isEmpty())
            RecordSharingUtil.unshare(oldAttShares);   
    }
    // -- Ver 2.0 -- Added for the apex Record Sharing -- END -- //
       -- Ver 3.0 Comment the code changes made in 2.0 -- END -- */
}