src/objects/Attendee__c.object
<CustomObject>
    <description>Tracks the Attendees for Conferences and Events tracked through the Event Approval application. This object will have a separate approval process from the Event or conference</description>
    <fields>
        <fullName>Attendee_Type_of_Funding_None__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Type of funding</description>
        <inlineHelpText>All funding provided by GSA or another US government agency. Do not select if there is a waived registration fee.</inlineHelpText>
        <label>None</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Attending_End_Date__c</fullName>
        <label>Attending End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Attending_Start_Date__c</fullName>
        <label>Attending Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event Identifier</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 3)</booleanFilter>
            <errorMessage>Please select a GSA Sponsored Conference or Non GSA Sponsored Conference only.</errorMessage>
            <filterItems>
                <field>Event_Approval__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>GSA Sponsored Conference, Non GSA Sponsored Conference</value>
            </filterItems>
            <filterItems>
                <field>Event_Approval__c.EA_End_Date__c</field>
                <operation>greaterOrEqual</operation>
                <valueField>$Source.CreatedDate</valueField>
            </filterItems>
            <filterItems>
                <field>Event_Approval__c.Event_Type_Hidden__c</field>
                <operation>notEqual</operation>
                <value>Over</value>
            </filterItems>
            <infoMessage>Please select a GSA Sponsored Conference or Non GSA Sponsored Conference. Attendee requests for Internal Management Meetings and Award Ceremonies are not required.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Event_Approval__c</referenceTo>
        <relationshipLabel>Attendees</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>Attendee # {00000000}</displayFormat>
        <label>Attendee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Attendee_Expense__c.object
<CustomObject>
    <description>This is an add on to the Event Approval application. This would be to track the expenses of any individual attendees that wish attend either a GSA sponsored conference or a Non GSA sponsored conference.</description>
    <fields>
        <fullName>Attendee__c</fullName>
        <label>Attendee</label>
        <referenceTo>Attendee__c</referenceTo>
        <relationshipLabel>Attendee Expenses</relationshipLabel>
        <relationshipName>Attendee_Expenses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Estimated_Amount__c</fullName>
        <label>Estimated Amount</label>
        <precision>10</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Expense_Detail__c</fullName>
        <label>Expense Detail</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Expense_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Air</fullName>
                </value>
                <value>
                    <fullName>Rail</fullName>
                </value>
                <value>
                    <fullName>POV</fullName>
                </value>
                <value>
                    <fullName>Shuttle or Taxi</fullName>
                </value>
                <value>
                    <fullName>Rental Car</fullName>
                </value>
                <value>
                    <fullName>Breakfast</fullName>
                </value>
                <value>
                    <fullName>Lunch</fullName>
                </value>
                <value>
                    <fullName>Dinner</fullName>
                </value>
                <value>
                    <fullName>Incidental</fullName>
                </value>
                <value>
                    <fullName>Per Diem</fullName>
                </value>
                <value>
                    <fullName>Booth Rental</fullName>
                </value>
                <value>
                    <fullName>Displays</fullName>
                </value>
                <value>
                    <fullName>Registration Fee</fullName>
                </value>
                <value>
                    <fullName>Taxes</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>gratuities</fullName>
                </value>
                <value>
                    <fullName>Room</fullName>
                </value>
                <value>
                    <fullName>Toll</fullName>
                </value>
                <value>
                    <fullName>Public Transit</fullName>
                </value>
                <value>
                    <fullName>Parking</fullName>
                </value>
                <value>
                    <fullName>Exhibit Cost</fullName>
                </value>
                <value>
                    <fullName>Audio Visual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Attendee Expense</label>
    <nameField>
        <displayFormat>Attendee Exp #-{0000000000}</displayFormat>
        <label>Attendee Expenses Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendee Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Event_Approval__c.object
<CustomObject>
    <description>The Conference Planning application provides an automated request, audit , approval, and
organization processes for Agency Conferences, Awards Ceremonies (with food), and Internal Management Meetings via the Salesforce cloud platform. This application is the required entry point for Event Coordinators, Finance, Contracting, Public Affairs, Procurement, and Leadership to coordinate requests submitted to the Office of Administrative Services; who will review and approve these requests, before an event can move forward.</description>
    <fields>
        <fullName>Conference_Site__c</fullName>
        <inlineHelpText>Enter the name of the site where the conference is being held. Include the country if international travel is required.</inlineHelpText>
        <label>Conference Venue</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EA_End_Date__c</fullName>
        <description>Used across all page layouts and record types for the Event Approval Application</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EA_Event_Name__c</fullName>
        <description>For Event Approval Application this tracks Conference  name on the Conference Approval Page layout, The Ceremony Name on the Ceremony Layout, and the meeting name on the meeting layout.</description>
        <inlineHelpText>The Event Identifier is the Short Name of the event for example &quot;FOSE&quot;  
The Event Name is the Long name of the event for example &quot;Federal Office Systems Expo&quot;</inlineHelpText>
        <label>Event</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>EA_Purpose_or_Objective__c</fullName>
        <description>Used in the OAS application for the EA object.  This field is required and will Span All three page layouts.</description>
        <label>Purpose or Objective</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EA_Stage__c</fullName>
        <description>Used in the OAS application on the Event Approval object.  This is not a required field and will be used for time based workflow and for moving through approval process.</description>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Waiting for Actuals</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EA_Start_Date__c</fullName>
        <description>used for across all layouts and record types for the Event Approval Application</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Event Approval</label>
    <nameField>
        <label>Event Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Approvals</pluralLabel>
    <recordTypes>
        <fullName>Non_GSA_Sponsored_Conference</fullName>
        <active>true</active>
        <description>For Conferences that are not sponsored by GSA</description>
        <label>Non GSA Sponsored Conference</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TestAttendeeExpenseRollUp.cls
/* ----------------------------------------------------------------------------------
   Test class for AttendeeExpenseRollup Trigger and Helper class 
-------------------------------------------------------------------------------------
    Author          | Date     | Version | Descripton
-------------------------------------------------------------------------------------
    Raja Nangunoori  12/13/12    1.0       Initial Draft
    Rajakumar        02/06/15    2.0       Test coverage for case#17704
-------------------------------------------------------------------------------------    
*/
@isTest
private class TestAttendeeExpenseRollUp {
    //private static Id AttendeeIds;
    static testMethod void testRollUp() {
        //User u = [SELECT Id, Name FROM User WHERE isactive = :true LIMIT 1];
        Id recTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Non_GSA_Sponsored_Conference' 
                        AND SObjectType = 'Event_Approval__c'].Id;
        Event_Approval__c EventApproval = new Event_Approval__c();
        EventApproval.Name = 'TestEAInsert01ABC1';
        EventApproval.EA_Event_Name__c = 'TestEAInsert01ABC1';
        EventApproval.Conference_Site__c ='Test Conf';
        EventApproval.EA_Purpose_or_Objective__c = 'Test Method';
        EventApproval.EA_Start_Date__c = Date.today();
        EventApproval.EA_End_Date__c = Date.today()+1;
        EventApproval.RecordTypeId = recTypeId;
        EventApproval.EA_Stage__c = 'Approved';
        insert EventApproval;
        
        Attendee__c Attendee = new Attendee__c();
        Attendee.Event_Number__c = EventApproval.Id;
        Attendee.Attending_Start_Date__c = Date.today();
        Attendee.Attending_End_Date__c = Date.today()+1;
        Attendee.Attendee_Type_of_Funding_None__c = true;
        //Attendee.Supervisors_Name__c = u.Id;      
        insert Attendee;
        
        Attendee_Expense__c AttExpense = new Attendee_Expense__c();
        AttExpense.Attendee__c = Attendee.Id;
        AttExpense.Estimated_Amount__c = 10.00;
        AttExpense.Expense_Detail__c = 'Meals';
        insert AttExpense;
        AttExpense.Expense_Detail__c = 'Other';
        upsert AttExpense;
        delete AttExpense;
        
        system.assertEquals(true, true);
        
    }

}