src/objects/BPA__c.object
<CustomObject>
    <description>VMO - BPA</description>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Vendor (Account) Name</description>
        <inlineHelpText>Search the Vendor Name</inlineHelpText>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Vendor does not exist or does not match the filter criteria</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Vendor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>BPAs</relationshipLabel>
        <relationshipName>BPA</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BPA</label>
    <nameField>
        <label>BPA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BPAs</pluralLabel>
    <recordTypes>
        <fullName>BPA</fullName>
        <active>true</active>
        <description>Used for Blanket Purchase Agreement (BPA)</description>
        <label>BPA</label>
    </recordTypes>
    <recordTypes>
        <fullName>Inactive</fullName>
        <active>true</active>
        <description>Used for Contracts and BPAs that the VM office does not need to view.</description>
        <label>Inactive</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/BPA_Call__c.object
<CustomObject>
    <description>VMO - BPA Call</description>
    <fields>
        <fullName>BPA_Name__c</fullName>
        <label>BPA Name</label>
        <referenceTo>BPA__c</referenceTo>
        <relationshipLabel>BPA Calls</relationshipLabel>
        <relationshipName>BPA_Calls</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Stratification_Score__c</fullName>
        <formula>IF ( Value_of_Task_Order_50M__c , 20, 0) + 
IF ( Limited_Sources__c , 5, 0 ) + 
IF ( ISBLANK(Key_Priorities__c) , 0, 25) +
IF ( ISBLANK( Mission_Critical__c ) , 0, 25) +
IF ( Innovative__c , 25, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Stratification Score</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Stratification_Value__c</fullName>
        <formula>IF ( Stratification_Score__c &lt; 26, &quot;Standard&quot;, IF ( Stratification_Score__c &gt;= 26 &amp;&amp; Stratification_Score__c &lt; 51 , &quot;Sustaining&quot;, IF (Stratification_Score__c &gt;= 51 &amp;&amp; Stratification_Score__c &lt; 76, &quot;Critical&quot;, &quot;Strategic&quot;)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The system calculated Stratification Value.</inlineHelpText>
        <label>Stratification Rating</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <description>Vendor (Account) Name</description>
        <formula>BPA_Name__r.Vendor__r.Name</formula>
        <inlineHelpText>Vendor Name</inlineHelpText>
        <label>Vendor</label>
        <type>Text</type>
    </fields>
    <label>BPA Call</label>
    <nameField>
        <label>BPA Call</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BPA Calls</pluralLabel>
    <recordTypes>
        <fullName>Inactive</fullName>
        <active>true</active>
        <description>Used for Task Orders and BPA Calls that the VM office does not need to view.</description>
        <label>Inactive</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contract__c.object
<CustomObject>
    <description>VMO - Contract</description>
    <fields>
        <fullName>Stratification_Score__c</fullName>
        <formula>IF ( Base_and_All_Options__c &gt; 50000000, 20, 0) +
IF ( ISBLANK(Key_Priorities__c), 0, 25) + 
IF ( ISBLANK(Mission_Critical__c), 0, 25) + 
IF ( Innovative__c = True, 25, 0) + 
IF ( Limited_Sources__c = True, 5, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Stratification Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Stratification_Value__c</fullName>
        <formula>IF ( AND(Stratification_Score__c &gt; 25, Stratification_Score__c &lt;= 50), &apos;Sustaining&apos;,
IF ( AND(Stratification_Score__c &gt; 50, Stratification_Score__c &lt;= 75), &apos;Critical&apos;,
IF ( AND(Stratification_Score__c &gt; 75, Stratification_Score__c &lt;= 100), &apos;Strategic&apos;,
 &apos;Standard&apos;)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Stratification Rating</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Vendor (Account) Name</description>
        <inlineHelpText>Search the Vendor Name</inlineHelpText>
        <label>Vendor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <recordTypes>
        <fullName>Inactive</fullName>
        <active>true</active>
        <description>Used for Contracts that the VM office does not need to view.</description>
        <label>Inactive</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Task_Order__c.object
<CustomObject>
    <description>VMO - Task Order object</description>
    <fields>
        <fullName>Stratification_Score__c</fullName>
        <formula>IF ( Base_and_All_Options__c &gt; 50000000, 20, 0) +
IF ( ISBLANK(Key_Priorities__c), 0, 25) + 
IF ( ISBLANK(Mission_Critical__c), 0, 25) + 
IF ( Innovative__c = True, 25, 0) + 
IF ( Limited_Sources__c = True, 5, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Stratification Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Stratification_Value__c</fullName>
        <formula>IF ( AND(Stratification_Score__c &gt; 25, Stratification_Score__c &lt;= 50), &apos;Sustaining&apos;,
IF ( AND(Stratification_Score__c &gt; 50, Stratification_Score__c &lt;= 75), &apos;Critical&apos;,
IF ( AND(Stratification_Score__c &gt; 75, Stratification_Score__c &lt;= 100), &apos;Strategic&apos;,
 &apos;Standard&apos;)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Stratification Rating</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Vendor (Account) Name</description>
        <inlineHelpText>Search the Vendor Name</inlineHelpText>
        <label>Vendor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Task Orders</relationshipLabel>
        <relationshipName>Task_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Task Order</label>
    <nameField>
        <label>Task Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Orders</pluralLabel>
    <recordTypes>
        <fullName>Inactive</fullName>
        <active>true</active>
        <description>Used for Task Orders that the VM office does not need to view.</description>
        <label>Inactive</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/VMO_AccountTriggerHelper.cls
public with sharing class VMO_AccountTriggerHelper {
    
    
    public static boolean run = true;
    public static boolean runOnce(){
        if(run){
         run=false;
         return true;
        }else{
            return run;
        }
    }
    public static void beforeUpdate(list<Account> triggerNew, map<ID, Account> triggerOldMap, 
                                        map <ID, Account> triggerNewMap) {
                                            
        map<string, decimal> mapStratScore = VMO_AccountTriggerHelper.stratScoreContTaskOrder(triggerNew);
        for (Account acct : triggerNew) {
            if (!String.isBlank(acct.Stratification_Value_Override__c)) {
                if(acct.Stratification_Value__c != acct.Stratification_Value_Override__c){
                    acct.Stratification_Value__c = acct.Stratification_Value_Override__c;
                }
            }else if (mapStratScore != null && mapStratScore.size() > 0) {
                decimal stratScore = mapStratScore.get(acct.id);
                
                if (stratScore > 25 && stratScore <= 50) {
                    acct.Stratification_Value__c = 'Sustaining';
                }else if (stratScore > 50 && stratScore <= 75) {
                    acct.Stratification_Value__c = 'Critical';
                }else if (stratScore > 75 && stratScore <= 100) {
                    acct.Stratification_Value__c = 'Strategic';
                }else {
                    acct.Stratification_Value__c = 'Standard';
                }
                System.debug('** StratValue: ' + stratScore);
            }else{
                acct.Stratification_Value__c='';
            }
        }
    }
    
    public static void beforeInsert(list<Account> triggerNew, map<ID, Account> triggerOldMap, 
                                        map <ID, Account> triggerNewMap) {
        for (Account acct : triggerNew) {
            if (!String.isBlank(acct.Stratification_Value_Override__c)) {
                if(acct.Stratification_Value__c != acct.Stratification_Value_Override__c){
                    acct.Stratification_Value__c = acct.Stratification_Value_Override__c;
                }
            }
        }                               
    }
    
    public static map<string, decimal> stratScoreContTaskOrder(list<Account> triggerNew){
        string contRecID = Schema.SObjectType.Contract__c.getRecordTypeInfosByName().get('Inactive').getRecordTypeId();
        
        map<string, decimal> mapStratScore = new map<string, decimal>();        
        for (Contract__c contTOList : [Select id, Vendor__c, Stratification_Score__c 
                                            from Contract__c where RecordTypeId !=:contRecID and Stratification_Score__c != null
                                            and Vendor__c in : triggerNew order By Stratification_Score__c desc limit 1]){
            if (mapStratScore.containsKey(contTOList.Vendor__c)){
                decimal stratScore = mapStratScore.get(contTOList.Vendor__c);
                if (contTOList.Stratification_Score__c > stratScore){
                    mapStratScore.put(contTOList.Vendor__c, contTOList.Stratification_Score__c);
                    system.debug('mapStratScoreContif22if::=='+mapStratScore);
                }   
            }else{ 
                mapStratScore.put(contTOList.Vendor__c, contTOList.Stratification_Score__c);
                system.debug('mapStratScoreCont11else::=='+mapStratScore);
             }                                           
        }
        system.debug('mapStratScore::Cont=='+mapStratScore);
        
        string toRecId = Schema.SObjectType.Task_Order__c.getRecordTypeInfosByName().get('Inactive').getRecordTypeId();
        for(Task_Order__c toBPAList : [Select id, Vendor__c, Stratification_Score__c 
                                                from Task_Order__c where RecordTypeId !=: toRecId and Stratification_Score__c != null
                                                 and Vendor__c in : triggerNew order By Stratification_Score__c desc limit 1]){
            if (mapStratScore.containsKey(toBPAList.Vendor__c)){
                decimal stratScore = mapStratScore.get(toBPAList.Vendor__c);
                if (toBPAList.Stratification_Score__c > stratScore){
                    mapStratScore.put(toBPAList.Vendor__c, toBPAList.Stratification_Score__c);
                    system.debug('mapStratScoreBPAif22if::=='+mapStratScore);
                }   
            }else{ 
                mapStratScore.put(toBPAList.Vendor__c, toBPAList.Stratification_Score__c);
                system.debug('mapStratScoreBPA11else::=='+mapStratScore);
             }                                          
        }
        system.debug('mapStratScore::BPA=='+mapStratScore);  
                                                      
        string bpaRecID = Schema.SObjectType.BPA_Call__c.getRecordTypeInfosByName().get('Inactive').getRecordTypeId();
        string bpaCallRecId = Schema.SObjectType.BPA__c.getRecordTypeInfosByName().get('Inactive').getRecordTypeId();
        
        for (BPA__c bpaList : [Select Id, Vendor__c,
                                (Select id, Stratification_Score__c 
                                    from BPA_Calls__r where RecordTypeId !=: toRecId  and Stratification_Score__c != null
                                    order By Stratification_Score__c desc limit 1)
                                From BPA__c Where RecordTypeId !=:contRecID and Vendor__c in : triggerNew]){
            if (mapStratScore.containsKey(bpaList.Vendor__c)){
                decimal stratScore = mapStratScore.get(bpaList.Vendor__c);
                if (bpaList.BPA_Calls__r != null && bpaList.BPA_Calls__r.size() > 0){  
                    system.debug('bpaCallScoreif22if::=='+mapStratScore);
                        if (bpaList.BPA_Calls__r[0].Stratification_Score__c > stratScore){
                        mapStratScore.put(bpaList.Vendor__c, bpaList.BPA_Calls__r[0].Stratification_Score__c);
                        system.debug('mapStratScoreif22ifif::=='+mapStratScore);
                    }
                }
            }else {
                if (bpaList.BPA_Calls__r != null && bpaList.BPA_Calls__r.size() > 0){  
                    mapStratScore.put(bpaList.Vendor__c, bpaList.BPA_Calls__r[0].Stratification_Score__c);
                    system.debug('bpaCallScoreelse22if::=='+mapStratScore);
                }
            }
        }
        system.debug('mapStratScore::BPA=='+mapStratScore);
        return mapStratScore;
    }
}