src/objects/BPA__c.object
<CustomObject>
    <description>VMO - BPA</description>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Vendor (Account) Name</description>
        <inlineHelpText>Search the Vendor Name</inlineHelpText>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Vendor does not exist or does not match the filter criteria</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Vendor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>BPAs</relationshipLabel>
        <relationshipName>BPA</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BPA</label>
    <nameField>
        <label>BPA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BPAs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/BPA_Call__c.object
<CustomObject>
    <description>VMO - BPA Call</description>
    <fields>
        <fullName>BPA_Name__c</fullName>
        <label>BPA Name</label>
        <referenceTo>BPA__c</referenceTo>
        <relationshipLabel>BPA Calls</relationshipLabel>
        <relationshipName>BPA_Calls</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Stratification_Value__c</fullName>
        <formula>IF ( Stratification_Score__c &lt; 26, &quot;Standard&quot;, IF ( Stratification_Score__c &gt;= 26 &amp;&amp; Stratification_Score__c &lt; 51 , &quot;Sustaining&quot;, IF (Stratification_Score__c &gt;= 51 &amp;&amp; Stratification_Score__c &lt; 76, &quot;Critical&quot;, &quot;Strategic&quot;)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The system calculated Stratification Value.</inlineHelpText>
        <label>Stratification Rating</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <description>Vendor (Account) Name</description>
        <formula>BPA_Name__r.Vendor__r.Name</formula>
        <inlineHelpText>Vendor Name</inlineHelpText>
        <label>Vendor</label>
        <type>Text</type>
    </fields>
    <label>BPA Call</label>
    <nameField>
        <label>BPA Call</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BPA Calls</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/VMO_BPACallTriggerHelper.cls
public with sharing class VMO_BPACallTriggerHelper {
    
    public static void afterUpdate(List<BPA_Call__c> triggerNew, Map<ID, BPA_Call__c> triggerOldMap, 
                                        Map <ID, BPA_Call__c> triggerNewMap) {
        
        set<string> setBPAId = new set<string>();
        system.debug('toBPAList==='+triggerNew);
        for(BPA_Call__c toBPAList : triggerNew){
            setBPAId.add(toBPAList.BPA_Name__c);
        }
        
        set<string> setAcctId = new set<string>();
        if(setBPAId != null && setBPAId.size() > 0){
            list<BPA__c> lstBPA = new list<BPA__c>();
            for(BPA__c bpaList :[Select Id,Vendor__c
                                 from BPA__c where Id IN: setBPAId]){
                setAcctId.add(bpaList.Vendor__c);
            }
        } 
        
        map<string, decimal> mapAcctBPACalls = new map<string, decimal>();
        for(BPA__c objBPA : [Select Vendor__c, (Select id from BPA_Calls__r) from BPA__c where Vendor__c IN : setAcctId]){
            system.debug(objBPA.BPA_Calls__r.size()+'****'+objBPA.BPA_Calls__r);
            if(mapAcctBPACalls.containsKey(objBPA.Vendor__c)){
                decimal totCalls = mapAcctBPACalls.get(objBPA.Vendor__c);
                if(objBPA.BPA_Calls__r != null && objBPA.BPA_Calls__r.size() > 0){
                    totCalls += objBPA.BPA_Calls__r.size();
                }
                mapAcctBPACalls.put(objBPA.Vendor__c, totCalls);
            }else{
                if(objBPA.BPA_Calls__r != null && objBPA.BPA_Calls__r.size() > 0){
                    mapAcctBPACalls.put(objBPA.Vendor__c,objBPA.BPA_Calls__r.size());
                }else{
                    mapAcctBPACalls.put(objBPA.Vendor__c,0);
                }
            }
        }
          
        system.debug(mapAcctBPACalls+'setAcctId==='+setAcctId);                             
        if(setAcctId != null && setAcctId.size() > 0){
            list<Account> acctList = [Select Id,Stratification_Value__c,Stratification_Value_Override__c 
                                        from Account where id IN : setAcctId];
            map<string, decimal> mapStratScore = VMO_AccountTriggerHelper.stratScoreContTaskOrder(acctList);
            list<Account> lstAcct = new list<Account>();
            for (Account acct : acctList) {
                Account acctObj = new Account();
                acctObj.Id = acct.Id;
                decimal totBPACalls = mapAcctBPACalls.get(acct.Id);
                system.debug('totBPACalls=='+totBPACalls);
                if(totBPACalls != null ){
                    acctObj.Total_No_of_BPACalls__c = totBPACalls;
                }
                if (!String.isBlank(acct.Stratification_Value_Override__c)) {
                    if(acct.Stratification_Value__c != acct.Stratification_Value_Override__c){
                        acctObj.Stratification_Value__c = acct.Stratification_Value_Override__c;
                    }
                }else if (mapStratScore != null && mapStratScore.size() > 0) {
                    decimal stratScore = mapStratScore.get(acct.id);
                    
                    if (stratScore > 25 && stratScore <= 50) {
                        acctObj.Stratification_Value__c = 'Sustaining';
                    }else if (stratScore > 50 && stratScore <= 75) {
                        acctObj.Stratification_Value__c = 'Critical';
                    }else if (stratScore > 75 && stratScore <= 100) {
                        acctObj.Stratification_Value__c = 'Strategic';
                    }else {
                        acctObj.Stratification_Value__c = 'Standard';
                    }
                    System.debug('** StratValue: ' + stratScore);
                }else{
                    acctObj.Stratification_Value__c = '';
                }
                lstAcct.add(acctObj);
            }
            system.debug('lstAcct==='+lstAcct);
            if (lstAcct != null && lstAcct.size() > 0) {
                update lstAcct;
            }
        }
    }
}