src/objects/CDT_Deletion_Log__c.object
<CustomObject>
    <description>This object will store the file details which was deleted from CDT object.</description>
    <fields>
        <fullName>Contolled_Document__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Controlled Document</label>
        <referenceTo>Controlled_Document__c</referenceTo>
        <relationshipLabel>CDT Deletion Logs</relationshipLabel>
        <relationshipName>CDT_Deletion_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DeletionDate__c</fullName>
        <description>Date the file is deleted.</description>
        <label>Deletion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>File_Name__c</fullName>
        <description>Name of the file which was deleted from CDT object</description>
        <label>File Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <description>Reason for file deletion</description>
        <label>Reason</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>User_Name__c</fullName>
        <description>User who deleted the file</description>
        <label>User Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CDT Deletion Log</label>
    <nameField>
        <label>CDT Deletion Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CDT Deletion Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Controlled_Document__c.object
<CustomObject>
    <fields>
        <fullName>Reason_File_Deletion__c</fullName>
        <description>Reason to be Entered for the file deletion. This reason will be logged in the CDTDeletionLog Object</description>
        <label>Reason For File Deletion</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Controlled Document</label>
    <nameField>
        <displayFormat>CC{000000}</displayFormat>
        <label>Document ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Controlled Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CDTPreventAttachmentDeleteHelper.cls
/*-------------------------------------------------------------------------------------------------*
Helper Class for  CDTPreventAttachmentDeleteHelper
*--------------------------------------------------------------------------------------------------*
Author           | Date        | Version | Description
*--------------------------------------------------------------------------------------------------*
Ramesh Dugar       03/28/2017    1.0       Trigger Created for Case#29763
*--------------------------------------------------------------------------------------------------*/
public class CDTPreventAttachmentDeleteHelper {
    public static void preventDeletemethod(List<ContentDocument> contentDocs){
        //test 
        List<Controlled_Document__c> conDoc = [SELECT Id,Reason_File_Deletion__c FROM Controlled_Document__c];
    	 Map<Id,String> cdIdMap = new Map<Id, String>();
         Set<Id> cdId = new Set<Id>();
           
        for(Controlled_Document__c cd : conDoc){
             cdIdMap.put(cd.Id,cd.Reason_File_Deletion__c);
             cdId.add(cd.Id);
         }
        List<ContentDocumentLink> clink = [Select Id,ContentDocumentId,LinkedEntityId from ContentDocumentLink Where LinkedEntityId IN:cdID];
        set<Id> AttId = new Set<Id>();
        Map<ID,ID> CDMap = new Map<ID,ID>();
        for(ContentDocumentLink cd : clink){
            AttId.add(cd.ContentDocumentId);
           // contentDocumentReasonMap.put(cd.contentDocumentID,cdIdMap.get(cd.LinkedEntityId));
           CDMap.put(cd.contentDocumentID,cd.LinkedEntityId);
        }
        system.debug('**'+AttId);
        List<CDT_Deletion_Log__c> logList = new List<CDT_Deletion_Log__c>();
        String reasonForDeletion;
        ID controlDocumentID;
        Set<ID> controlDocumentIDset = new Set<ID>();
        for(ContentDocument c : contentDocs){
            if(AttId.contains(c.Id)){
                controlDocumentID = CDMap.get(c.ID);
                reasonForDeletion = cdIdMap.get(controlDocumentID);
                controlDocumentIDset.add(controlDocumentID);
                if(String.isBlank(reasonForDeletion))
                   c.addError('You cannot delete this attachment. Please Enter the reason for deletion.',FALSE);
                else {
                       CDT_Deletion_Log__c log = new CDT_Deletion_Log__c();
                    	log.Contolled_Document__c = controlDocumentID;
                    	log.File_Name__c= c.Title;
                    	log.DeletionDate__c = Date.Today();
                    	log.Reason__c = reasonForDeletion;
                    	log.User_Name__c = UserInfo.getName();
                    	logList.add(log);
                    	
                }
            	
            }
            
    	}
        Insert(logList);
		List<Controlled_Document__c> Cdlist = [Select ID,Reason_File_Deletion__c from Controlled_Document__c where id in :controlDocumentIDset];
        for(Controlled_Document__c record : cdlist){
            record.Reason_File_Deletion__c ='';
        }
        Update(Cdlist);
    }
}