src/objects/CIS_Assets__c.object
<CustomObject>
    <description>This object is used to track all assets for CIS (Congressional Inventory System)</description>
    <fields>
        <fullName>CIS_Office__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used by CIS - Lookup to PmoAo Office in which this Asset is located</description>
        <label>CIS Office</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>CIS_Offices__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Senate</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CIS_Offices__c</referenceTo>
        <relationshipLabel>CIS Assets</relationshipLabel>
        <relationshipName>CIS_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Ordered__c</fullName>
        <description>What date was this inventory item ordered?</description>
        <label>Date Ordered</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Received__c</fullName>
        <label>Date Received</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expense_Type__c</fullName>
        <label>Expense Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>D - Furniture</fullName>
                </value>
                <value>
                    <fullName>B - Carpet/Drapes</fullName>
                </value>
                <value>
                    <fullName>A - Expensed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Enter the quantity of items on this record.</description>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>Used by CIS. Cannot be removed as it&apos;s being used by &quot;Update Reporting Region&quot; workflow with Storage/Excess rules. Cannot use reference field within workflow rules so have to refer from here.</description>
        <formula>TEXT(CIS_Office__r.Member_ID__r.Region__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Cost__c</fullName>
        <formula>(Unit_Cost__c * Quantity__c) + (Other_Cost__c * Quantity__c )- Credit__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unit_Cost__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Unit Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>CIS Asset</label>
    <nameField>
        <label>Asset Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CIS Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CIS_Contact__c.object
<CustomObject>
    <description>This object is for CIS names for their Members of Congress - Senators and Congessmen, as well as office staff.</description>
    <fields>
        <fullName>CIS_Office__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CIS Office</label>
        <referenceTo>CIS_Offices__c</referenceTo>
        <relationshipLabel>CIS Contacts</relationshipLabel>
        <relationshipName>CIS_Office_Staff</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Member of Congress</fullName>
                </value>
                <value>
                    <fullName>Office Staff</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CIS Contact</label>
    <nameField>
        <label>CIS Contact Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CIS Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CIS_MemberOfCongress__c.object
<CustomObject>
    <description>Members of Congress</description>
    <fields>
        <fullName>Election_Year__c</fullName>
        <label>Next Election</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Member_of_Congress_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member of Congress Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>CIS_Contact__c.Type__c</field>
                <operation>equals</operation>
                <value>Member of Congress</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CIS_Contact__c</referenceTo>
        <relationshipLabel>Members of Congress</relationshipLabel>
        <relationshipName>Members_of_Congress</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Original_Budget__c</fullName>
        <description>Original Budget</description>
        <inlineHelpText>Original Budget</inlineHelpText>
        <label>Original Asset Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                </value>
                <value>
                    <fullName>02</fullName>
                </value>
                <value>
                    <fullName>03</fullName>
                </value>
                <value>
                    <fullName>04</fullName>
                </value>
                <value>
                    <fullName>05</fullName>
                </value>
                <value>
                    <fullName>06</fullName>
                </value>
                <value>
                    <fullName>07</fullName>
                </value>
                <value>
                    <fullName>08</fullName>
                </value>
                <value>
                    <fullName>09</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Spent_Asset_Budget__c</fullName>
        <label>Spent Asset Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>State_of_Office__c</fullName>
        <description>State of Office</description>
        <inlineHelpText>State of Office</inlineHelpText>
        <label>State of Office</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
                <value>
                    <fullName>NJ</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Member of Congress</label>
    <nameField>
        <displayFormat>MOC-{0000}</displayFormat>
        <label>Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members of Congress</pluralLabel>
    <recordTypes>
        <fullName>Senate</fullName>
        <active>true</active>
        <description>Senate</description>
        <label>Senate</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CIS_Offices__c.object
<CustomObject>
    <description>This is the CIS object used for the Member of Congress&apos; Offices.</description>
    <fields>
        <fullName>City__c</fullName>
        <description>The City that the office is located in.</description>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Member_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Member ID</description>
        <inlineHelpText>Member ID</inlineHelpText>
        <label>Member ID</label>
        <referenceTo>CIS_MemberOfCongress__c</referenceTo>
        <relationshipName>PmoAo_Offices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PMO_AO_Number__c</fullName>
        <label>PMO/AO Number</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>TEXT( Member_ID__r.Region__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Space_Assigned__c</fullName>
        <description>Space Assigned</description>
        <inlineHelpText>Space Assigned</inlineHelpText>
        <label>Space Assigned</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>GSA</fullName>
                </value>
                <value>
                    <fullName>Post Office</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Leased</fullName>
                </value>
                <value>
                    <fullName>Commercial</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CIS Office</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>CIS Office ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CIS Offices</pluralLabel>
    <recordTypes>
        <fullName>Senate</fullName>
        <active>true</active>
        <description>Senate</description>
        <label>Senate</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CIS_TestSpendBudgetHandler.cls
/*
  CIS_TestSpendBudgetHandler.
  Class for testing sm1e__smEquipment__c object
  -------------------------------------------------------------------------------
  Author                 Date        Version  Description
  -------------------------------------------------------------------------------
  Murugaboopathi         06/27/2012  1.0      Creation
  
  NOTE: Modifed 11/20/2013 - To make it hard code system Assert statements. Need to be removed.
*/ 


@isTest(SeeAllData=true)
public class CIS_TestSpendBudgetHandler{
    static testMethod void handleAssetsInsert() {
        CIS_Contact__c contactOne = new CIS_Contact__c();
        contactOne.Name = 'TESTLASTNAME';
        contactOne.First_Name__c = 'TESTFIRSTNAME';
        contactOne.Type__c = 'Member of Congress';
        insert contactOne;
    
        CIS_MemberOfCongress__c memOfCongress = new CIS_MemberOfCongress__c();
        Schema.DescribeSObjectResult memOfCongressSchema = Schema.SObjectType.CIS_MemberOfCongress__c;
        Map<String,Schema.RecordTypeInfo> memOfCongressRecordTypeInfo = memOfCongressSchema.getRecordTypeInfosByName(); 
        memOfCongress.recordTypeId = memOfCongressRecordTypeInfo.get('Senate').getRecordTypeId();
        memOfCongress.State_of_Office__c = 'AL';
        memOfCongress.Region__c = '01';
        memOfCongress.Original_Budget__c = 10000.00;
        memOfCongress.Election_Year__c = '2010';
        memOfCongress.Member_of_Congress_Name__c = contactOne.Id;        
        insert memOfCongress;
        
        Schema.DescribeSObjectResult pmoOfficeSchema = Schema.SObjectType.CIS_Offices__c;
        Map<String,Schema.RecordTypeInfo> pmoOfficeRecordTypeInfo = pmoOfficeSchema.getRecordTypeInfosByName();      
        CIS_Offices__c pmoOffice = new CIS_Offices__c();
        pmoOffice.recordTypeId = pmoOfficeRecordTypeInfo.get('Senate').getRecordTypeId();
        pmoOffice.PMO_AO_Number__c = 'TE12';
        pmoOffice.Space_Assigned__c = 'GSA';
        pmoOffice.Member_ID__c = memOfCongress.Id;
        insert  pmoOffice;
        
      
        pmoOffice = [SELECT Id,Name, PMO_AO_Number__c,Member_ID__c FROM CIS_Offices__c WHERE PMO_AO_Number__c = 'TE12' and Member_ID__c = :memOfCongress.Id][0];

        CIS_Assets__c asset = new CIS_Assets__c();
        asset.Name = 'TE01';
        asset.CIS_Office__c = pmoOffice.Id;
        asset.Unit_Cost__c = 100;
        asset.Quantity__c = 2;
        asset.Expense_Type__c = 'B - Carpet/Drapes';
        insert asset;
        
        //After insert
        memOfCongress = [SELECT Id, Spent_Asset_Budget__c FROM CIS_MemberOfCongress__c WHERE Id = :memOfCongress.Id][0];
        asset = [SELECT Id, Total_Cost__c FROM CIS_Assets__c WHERE Id = :asset.Id ][0];
        System.assertEquals(memOfCongress.Spent_Asset_Budget__c,asset.Total_Cost__c);
    }


    static testMethod void handleAssetsUpdate() {
    Test.startTest();
        /*    
        // To test error condition
        CIS_Offices__c errorOffice = new CIS_Offices__c();  
        Schema.DescribeSObjectResult errorOfficeSchema = Schema.SObjectType.CIS_Offices__c;
        Map<String,Schema.RecordTypeInfo> errorOfficeRecordTypeInfo= errorOfficeSchema.getRecordTypeInfosByName();      
        errorOffice.recordTypeId = errorOfficeRecordTypeInfo.get('Senate').getRecordTypeId();
        errorOffice.PMO_AO_Number__c = 'ERRR';
        errorOffice.Space_Assigned__c = 'GSA';
        insert  errorOffice;

        CIS_Assets__c errorAsset = new CIS_Assets__c();
        errorAsset.Name = 'ERROR_TABLE';
        errorAsset.CIS_Office__c = errorOffice.Id;
        errorAsset.Unit_Cost__c = 100;
        errorAsset.Quantity__c = 2;
        Date errorOrdered = Date.newInstance(2010,12,2);
        errorAsset.Date_Ordered__c = errorOrdered ;
        Date errorReceived = Date.newInstance(2011,12,2);
        errorAsset.Date_Received__c = errorReceived;
        insert errorAsset;
        */

        CIS_Contact__c contactOne = new CIS_Contact__c();
        contactOne.Name = 'TESTLASTNAME';
        contactOne.First_Name__c = 'TESTFIRSTNAME';
        contactOne.Type__c = 'Member of Congress';
        insert contactOne;
        contactOne =[select Id,Name,First_Name__c from CIS_Contact__c where Name = 'TESTLASTNAME' and First_Name__c = 'TESTFIRSTNAME'][0];
        
        CIS_MemberOfCongress__c memOfCongress = new CIS_MemberOfCongress__c();
        Schema.DescribeSObjectResult memOfCongressSchema = Schema.SObjectType.CIS_MemberOfCongress__c;
        Map<String,Schema.RecordTypeInfo> memOfCongressRecordTypeInfo = memOfCongressSchema.getRecordTypeInfosByName(); 
        memOfCongress.recordTypeId = memOfCongressRecordTypeInfo.get('Senate').getRecordTypeId();
        memOfCongress.State_of_Office__c = 'AL';
        memOfCongress.Region__c = '01';
        memOfCongress.Original_Budget__c = 10000.00;
        memOfCongress.Election_Year__c = '2010';
        memOfCongress.Member_of_Congress_Name__c = contactOne.Id;
        insert memOfCongress;
        
        Schema.DescribeSObjectResult pmoOfficeSchema = Schema.SObjectType.CIS_Offices__c;
        Map<String,Schema.RecordTypeInfo> pmoOfficeRecordTypeInfo = pmoOfficeSchema.getRecordTypeInfosByName();      
        CIS_Offices__c pmoOffice = new CIS_Offices__c();
        pmoOffice.recordTypeId = pmoOfficeRecordTypeInfo.get('Senate').getRecordTypeId();
        pmoOffice.PMO_AO_Number__c = 'TE12';
        pmoOffice.Space_Assigned__c = 'GSA';
        pmoOffice.City__c = 'TEST LOCATION';        
        pmoOffice.Member_ID__c = memOfCongress.Id;
        insert  pmoOffice;

        // Changing assets from one senator to another senetor
        
        CIS_Contact__c contact22 = new CIS_Contact__c();
        contact22.Name = 'TESTLASTNAME22';
        contact22.First_Name__c = 'TESTFIRSTNAME22';
        contact22.Type__c = 'Member of Congress';        
        insert contact22;
                
        CIS_MemberOfCongress__c memOfCongress22 = new CIS_MemberOfCongress__c();
        Schema.DescribeSObjectResult memOfCongressOneSchema = Schema.SObjectType.CIS_MemberOfCongress__c;
        Map<String,Schema.RecordTypeInfo> memOfCongressOneRecordTypeInfo = memOfCongressOneSchema.getRecordTypeInfosByName(); 
        memOfCongress22.recordTypeId = memOfCongressOneRecordTypeInfo.get('Senate').getRecordTypeId();
        memOfCongress22.State_of_Office__c = 'AL';
        memOfCongress22.Region__c = '01';
        memOfCongress22.Original_Budget__c = 20000.00;
        memOfCongress22.Election_Year__c = '2010';
        memOfCongress22.Member_of_Congress_Name__c = contact22.Id;         
        insert memOfCongress22;
        
        CIS_Offices__c pmoOfficeOne = new CIS_Offices__c();  
        Schema.DescribeSObjectResult pmoOfficeOneSchema = Schema.SObjectType.CIS_Offices__c;
        Map<String,Schema.RecordTypeInfo> pmoOfficeOneRecordTypeInfo= pmoOfficeOneSchema.getRecordTypeInfosByName();      
        pmoOfficeOne.recordTypeId = pmoOfficeOneRecordTypeInfo.get('Senate').getRecordTypeId();
        pmoOfficeOne.PMO_AO_Number__c = 'MM13';
        pmoOfficeOne.Space_Assigned__c = 'GSA';
        pmoOfficeOne.City__c = 'TEST LOCATION';
        pmoOfficeOne.Member_ID__c = memOfCongress22.Id;
        insert  pmoOfficeOne;

        pmoOffice = [SELECT Id,Name, PMO_AO_Number__c,Member_ID__c FROM CIS_Offices__c WHERE PMO_AO_Number__c = 'TE12'][0];
        CIS_Assets__c asset = new CIS_Assets__c();
        asset.Name = 'TestTABLE';
        asset.CIS_Office__c = pmoOffice.Id;
        asset.Expense_Type__c = 'D - Furniture';
        asset.Unit_Cost__c = 100;
        asset.Quantity__c = 2;
        Date ordered = Date.newInstance(2010,12,2);
        asset.Date_Ordered__c = ordered;
        Date received = Date.newInstance(2011,12,2);
        asset.Date_Received__c = received;
        insert asset;
        
        //After insert
        memOfCongress = [select Id,Spent_Asset_Budget__c from CIS_MemberOfCongress__c where Id = :memOfCongress.Id][0];
        asset = [SELECT Id,CIS_Office__c,Unit_Cost__c,Total_Cost__c FROM CIS_Assets__c WHERE Id = :asset.Id and Name = 'TestTABLE'][0];
        System.assertEquals(memOfCongress.Spent_Asset_Budget__c,asset.Total_Cost__c);
        
        
        pmoOfficeOne = [SELECT Id,Name, PMO_AO_Number__c,Member_ID__c FROM CIS_Offices__c WHERE PMO_AO_Number__c = 'MM13' and Member_ID__c = :memOfCongress22.Id][0];
        asset = [SELECT Id,CIS_Office__c,Date_Ordered__c,Date_Received__c,Unit_Cost__c,Total_Cost__c FROM CIS_Assets__c WHERE Id = :asset.Id and Name = 'TestTABLE'][0];        
        asset.CIS_Office__c = pmoOfficeOne.Id;
        asset.Unit_Cost__c = 150;
        asset.Expense_Type__c = 'D - Furniture';
        update asset;
        
        asset = [SELECT Id, Total_Cost__c FROM CIS_Assets__c WHERE Id = :asset.Id and Name = 'TestTABLE'][0];
        memOfCongress22 = [select Id,Spent_Asset_Budget__c from CIS_MemberOfCongress__c where Id = :memOfCongress22.Id and Member_of_Congress_Name__c = :contact22.Id][0];        
        //System.assertEquals(memOfCongress22.Spent_Asset_Budget__c,asset.Total_Cost__c);
        

        //After insert - TESTING THE VALUE.
        asset = [SELECT Id, Total_Cost__c FROM CIS_Assets__c WHERE Id = :asset.Id ][0];
        memOfCongress = [select Id,Spent_Asset_Budget__c from CIS_MemberOfCongress__c where Id = :memOfCongress.Id][0];        
        //System.assertEquals(memOfCongress.Spent_Asset_Budget__c,asset.Total_Cost__c);



        //Creating storage OFFICE
        CIS_Offices__c storagePmoOffice = new CIS_Offices__c();  
        //Moving from Office to storage.
        //storagePmoOffice = [SELECT Id,Name, PMO_AO_Number__c,Member_ID__c FROM CIS_Offices__c WHERE PMO_AO_Number__c = '77ZA'];        
        if([SELECT Id,Name, PMO_AO_Number__c,Member_ID__c FROM CIS_Offices__c WHERE PMO_AO_Number__c = '77ZA'].size() > 0)
        {
            storagePmoOffice = [SELECT Id,Name, PMO_AO_Number__c,Member_ID__c FROM CIS_Offices__c WHERE PMO_AO_Number__c = '77ZA'][0];
        }
        else
        {
            storagePmoOffice.recordTypeId = pmoOfficeRecordTypeInfo.get('Senate').getRecordTypeId();
        	storagePmoOffice.PMO_AO_Number__c = '77ZA';
        	storagePmoOffice.City__c = 'TEST LOCATION';
        	storagePmoOffice.Space_Assigned__c = 'GSA';
        	insert  storagePmoOffice;
        }
        
        asset.CIS_Office__c = storagePmoOffice.Id;
        asset.Expense_Type__c = 'D - Furniture';
        update asset;
        
        //Moving from storage to Office.        
        asset.CIS_Office__c = pmoOfficeOne.Id;
        asset.Expense_Type__c = 'D - Furniture';
        update asset;
        


        //Creating storage OFFICE
        CIS_Offices__c execPmoOffice = new CIS_Offices__c();  
        if([SELECT Id,Name, PMO_AO_Number__c,Member_ID__c FROM CIS_Offices__c WHERE PMO_AO_Number__c = 'EXCS'].size() > 0)
        {
            execPmoOffice = [SELECT Id,Name, PMO_AO_Number__c,Member_ID__c FROM CIS_Offices__c WHERE PMO_AO_Number__c = 'EXCS'][0];
        }
        else
        {
            execPmoOffice.recordTypeId = pmoOfficeRecordTypeInfo.get('Senate').getRecordTypeId();
        	execPmoOffice.PMO_AO_Number__c = 'EXCS';
        	execPmoOffice.Space_Assigned__c = 'GSA';
        	insert  execPmoOffice;
        }
        /*
        execPmoOffice.recordTypeId = pmoOfficeRecordTypeInfo.get('Senate').getRecordTypeId();
        execPmoOffice.PMO_AO_Number__c = 'EXCS';
        execPmoOffice.Space_Assigned__c = 'GSA';
        insert  execPmoOffice;
        */
        Date ordered2 = Date.newInstance(1999,11,2);
        asset.Date_Ordered__c = ordered2;
        Date received2 = Date.newInstance(1999,12,2);
        asset.Date_Received__c = received2;
        asset.CIS_Office__c = execPmoOffice.Id;
        asset.Expense_Type__c = 'D - Furniture';
        update asset;
        
        /* NOT A VALID CONDITION
        //Moving excess to storage
        asset.CIS_Office__c = storagePmoOffice.Id;
        asset.Expense_Type__c = 'D - Furniture';
        update asset;
        */
        
        //Moving Storage to office
        asset.CIS_Office__c = pmoOfficeOne.Id;
        asset.Expense_Type__c = 'D - Furniture';
        update asset;
        
        
        //Moving office to exec
        asset.CIS_Office__c = execPmoOffice.Id;
        asset.Expense_Type__c = 'D - Furniture';
        update asset;
        
        //Moving office to exec
        asset.CIS_Office__c = pmoOffice.Id;
        asset.Expense_Type__c = 'D - Furniture';
        update asset;
        
        
        
        Test.stopTest();
 }
 
    static testMethod void handleAssetsDelete() {
        
        CIS_Contact__c contactOne = new CIS_Contact__c();
        contactOne.Name = 'TESTLASTNAME';
        contactOne.First_Name__c = 'TESTFIRSTNAME';
        contactOne.Type__c = 'Member of Congress';
        insert contactOne;
                
        CIS_MemberOfCongress__c memOfCongress = new CIS_MemberOfCongress__c();
        Schema.DescribeSObjectResult memOfCongressSchema = Schema.SObjectType.CIS_MemberOfCongress__c;
        Map<String,Schema.RecordTypeInfo> memOfCongressRecordTypeInfo = memOfCongressSchema.getRecordTypeInfosByName(); 
        memOfCongress.recordTypeId = memOfCongressRecordTypeInfo.get('Senate').getRecordTypeId();
        memOfCongress.State_of_Office__c = 'AL';
        memOfCongress.Region__c = '01';
        memOfCongress.Original_Budget__c = 10000.00;
        memOfCongress.Election_Year__c = '2010';
        memOfCongress.Member_of_Congress_Name__c = contactOne.Id;            
        insert memOfCongress;
        
        Schema.DescribeSObjectResult pmoOfficeSchema = Schema.SObjectType.CIS_Offices__c;
        Map<String,Schema.RecordTypeInfo> pmoOfficeRecordTypeInfo = pmoOfficeSchema.getRecordTypeInfosByName();      
        CIS_Offices__c pmoOffice = new CIS_Offices__c();
        pmoOffice.recordTypeId = pmoOfficeRecordTypeInfo.get('Senate').getRecordTypeId();
        pmoOffice.PMO_AO_Number__c = 'TE12';
        pmoOffice.Space_Assigned__c = 'GSA';
        pmoOffice.Member_ID__c = memOfCongress.Id;
        insert  pmoOffice;
        
      
        pmoOffice = [SELECT Id,Name, PMO_AO_Number__c,Member_ID__c FROM CIS_Offices__c WHERE PMO_AO_Number__c = 'TE12' and Member_ID__c = :memOfCongress.Id][0];

        CIS_Assets__c asset = new CIS_Assets__c();
        
//        Schema.DescribeSObjectResult assetSchema = Schema.SObjectType.sm1e__smEquipment__c;
//        Map<String,Schema.RecordTypeInfo> assetRecordTypeInfo = assetSchema.getRecordTypeInfosByName(); 
//        asset.recordTypeId = assetRecordTypeInfo.get('Furniture').getRecordTypeId();
        asset.Name = 'TE01';
        asset.CIS_Office__c = pmoOffice.Id;
        asset.Unit_Cost__c = 100;
        asset.Quantity__c = 2;
        asset.Expense_Type__c = 'D - Furniture';
        insert asset;
        //After insert
        memOfCongress = [SELECT Id, Spent_Asset_Budget__c FROM CIS_MemberOfCongress__c WHERE Id = :memOfCongress.Id][0];
        asset = [SELECT Id, Total_Cost__c FROM CIS_Assets__c WHERE Id = :asset.Id ][0];
        System.assertEquals(memOfCongress.Spent_Asset_Budget__c,asset.Total_Cost__c);
                
        Decimal oldSpendBudgetValue = memOfCongress.Spent_Asset_Budget__c;
        //After deletion of the ASSET
        delete asset;
        //After insert
        memOfCongress = [SELECT Id, Spent_Asset_Budget__c FROM CIS_MemberOfCongress__c WHERE Id = :memOfCongress.Id][0];
         
        System.assertEquals(memOfCongress.Spent_Asset_Budget__c,(oldSpendBudgetValue - 200));      
    }
 
}