src/objects/Communications__c.object
<CustomObject>
    <description>This object is created to serve the business need of Internal Management Tool (IMT) Communications events/records.</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Region_SSO__c</fullName>
        <label>Region / SSO</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>OCR</fullName>
                </value>
                <value>
                    <fullName>CFO</fullName>
                </value>
                <value>
                    <fullName>CPO</fullName>
                </value>
                <value>
                    <fullName>OERR</fullName>
                </value>
                <value>
                    <fullName>OSBU</fullName>
                </value>
                <value>
                    <fullName>OAS</fullName>
                </value>
                <value>
                    <fullName>CIO</fullName>
                </value>
                <value>
                    <fullName>OGC</fullName>
                </value>
                <value>
                    <fullName>OGP</fullName>
                </value>
                <value>
                    <fullName>PBS</fullName>
                </value>
                <value>
                    <fullName>FAS</fullName>
                </value>
                <value>
                    <fullName>OCIA</fullName>
                </value>
                <value>
                    <fullName>OCSIT</fullName>
                </value>
                <value>
                    <fullName>OCM</fullName>
                </value>
                <value>
                    <fullName>Region 1</fullName>
                </value>
                <value>
                    <fullName>Region 2</fullName>
                </value>
                <value>
                    <fullName>Region 3</fullName>
                </value>
                <value>
                    <fullName>Region 4</fullName>
                </value>
                <value>
                    <fullName>Region 5</fullName>
                </value>
                <value>
                    <fullName>Region 6</fullName>
                </value>
                <value>
                    <fullName>Region 7</fullName>
                </value>
                <value>
                    <fullName>Region 8</fullName>
                </value>
                <value>
                    <fullName>Region 9</fullName>
                </value>
                <value>
                    <fullName>Region 10</fullName>
                </value>
                <value>
                    <fullName>NCR</fullName>
                </value>
                <value>
                    <fullName>Administrative Office</fullName>
                </value>
                <value>
                    <fullName>Central Office</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Show_in_Shared_Calendar__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Show in IMT Calendar</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Communications</label>
    <nameField>
        <label>Activity</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Communications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/IMTCommunicationsHelper.cls
/*-------------------------------------------------------------------------------------------------*
  Apex class 
  Creates an event on IMT Calendar for Comms record
 *-------------------------------------------------------------------------------------------------*
  Author           | Date        | Version | Description
 *-------------------------------------------------------------------------------------------------*
  Rajakumar          08/16/2013    1.0       Initial version.
 *-------------------------------------------------------------------------------------------------* 
 
 *-------------------------------------------------------------------------------------------------*/
public class IMTCommunicationsHelper {
    
    public static void onAfterInsert(List<Communications__c> triggerNew) {
         List<EventUtil.EventFieldDefinition> eventFields = new list<EventUtil.EventFieldDefinition> {
         new EventUtil.EventFieldDefinition('start_date__c', 'End_Date__c', 'Communications')
         };
         List<Communications__c> records = new List<Communications__c>();                  
         for(Communications__c c: triggerNew) {
             if(c.Show_in_Shared_Calendar__c == true) {
                 records.add(c);
             }     
         }
         //System.debug('TOTAL INSERT RECORDS size: ' +records.size());
         if(!records.isEmpty())
            EventUtil.onAfterInsert(records, eventFields, 'IMTCalendar', 'Region_SSO__c');
    }
    
    public static void onAfterUpdate(List<Communications__c> triggerNew, Map<Id, Communications__c> triggerOldMap, Map<Id, Communications__c> triggerNewMap) {
         List<EventUtil.EventFieldDefinition> eventFields = new list<EventUtil.EventFieldDefinition> {
         new EventUtil.EventFieldDefinition('start_date__c', 'end_date__c', 'Communications')
         };
         List<Communications__c> updatedRecs = new List<Communications__c>();
         Set<Id> delshrRecordIds = new Set<Id>();
         Set<Id> updatedRecordIds = new Set<Id>();
         for(Communications__c req: triggerNew) {
             // list of the communication records which are not available in shared calendar
             if((req.Start_Date__c!=triggerOldMap.get(req.Id).Start_Date__c || 
                 req.End_Date__c!=triggerOldMap.get(req.Id).End_Date__c ||
                 req.Region_SSO__c!=triggerOldMap.get(req.Id).Region_SSO__c ||
                 req.Show_in_Shared_Calendar__c != triggerOldMap.get(req.Id).Show_in_Shared_Calendar__c) && req.Show_in_Shared_Calendar__c == true) {
                 updatedRecordIds.add(req.Id);
             }
             // list of the communication records which are already available in shared calendar
             if((req.Start_Date__c!=triggerOldMap.get(req.Id).Start_Date__c || 
                 req.End_Date__c!=triggerOldMap.get(req.Id).End_Date__c ||
                 req.Region_SSO__c!=triggerOldMap.get(req.Id).Region_SSO__c ||
                 req.Show_in_Shared_Calendar__c == triggerOldMap.get(req.Id).Show_in_Shared_Calendar__c) && req.Show_in_Shared_Calendar__c == true) {
                 updatedRecordIds.add(req.Id);
             }
             // list of the communication records which are already available in shared calendar but no longer required to show
             if((req.Start_Date__c!=triggerOldMap.get(req.Id).Start_Date__c || req.End_Date__c!=triggerOldMap.get(req.Id).End_Date__c ||
                 req.Show_in_Shared_Calendar__c != triggerOldMap.get(req.Id).Show_in_Shared_Calendar__c) && req.Show_in_Shared_Calendar__c == false) {
                 delshrRecordIds.add(req.Id);
             }
            
        }        
        if(!updatedRecordIds.isEmpty() || !delshrRecordIds.isEmpty())
            EventUtil.onAfterUpdate(triggerNew, updatedRecordids, triggerNewMap, delshrRecordIds, eventFields, 'IMTCalendar', 'Region_SSO__c');
    }
}