src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>GSA</fullName>
        <active>true</active>
        <description>This contact record is used to track information for GSA employees.</description>
        <label>GSA</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Request_Tracker__c.object
<CustomObject>
    <description>The Request Tracker a custom object is created to track multiple type of request some with approval process and other with simple workflow.
This object also has an affiliated object called &quot;Survey&quot; which is used with one of Record Type called &quot;Communication Job Log &quot;</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Android</fullName>
                </value>
                <value>
                    <fullName>Blackberry</fullName>
                </value>
                <value>
                    <fullName>iPad</fullName>
                </value>
                <value>
                    <fullName>iPhone</fullName>
                </value>
                <value>
                    <fullName>EEO</fullName>
                </value>
                <value>
                    <fullName>Personnel</fullName>
                </value>
                <value>
                    <fullName>Contracting</fullName>
                </value>
                <value>
                    <fullName>Inspector General</fullName>
                </value>
                <value>
                    <fullName>508 Accessibility Software</fullName>
                </value>
                <value>
                    <fullName>Access Control and Audit Control</fullName>
                </value>
                <value>
                    <fullName>API Management</fullName>
                </value>
                <value>
                    <fullName>Application Servers</fullName>
                </value>
                <value>
                    <fullName>Asset Management</fullName>
                </value>
                <value>
                    <fullName>Browser Extension</fullName>
                </value>
                <value>
                    <fullName>Building Automation</fullName>
                </value>
                <value>
                    <fullName>Building Information Modeling</fullName>
                </value>
                <value>
                    <fullName>Building Management</fullName>
                </value>
                <value>
                    <fullName>Business Process Management System</fullName>
                </value>
                <value>
                    <fullName>CAD-Computer-Aided Design</fullName>
                </value>
                <value>
                    <fullName>CCA-Component Collaboration Architecture</fullName>
                </value>
                <value>
                    <fullName>Certificates / Digital Signature</fullName>
                </value>
                <value>
                    <fullName>Cloud Based Dev Platform</fullName>
                </value>
                <value>
                    <fullName>Collaboration Software</fullName>
                </value>
                <value>
                    <fullName>Content Accessibility Evaluation</fullName>
                </value>
                <value>
                    <fullName>Content Rendering</fullName>
                </value>
                <value>
                    <fullName>Continuous Delivery (CD)</fullName>
                </value>
                <value>
                    <fullName>Continuous Integration</fullName>
                </value>
                <value>
                    <fullName>Cost Estimation</fullName>
                </value>
                <value>
                    <fullName>Customer Relationship Management</fullName>
                </value>
                <value>
                    <fullName>Data Backup</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FOIA__c</fullName>
        <label>FOIA #</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_of_Flash_Drive_s__c</fullName>
        <label>Number of Flash Drive(s)</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OCIO_Blog_InternalOrExternal__c</fullName>
        <inlineHelpText>GSA Employees Only (InSite) or Public</inlineHelpText>
        <label>Internal or External</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Internal GSA-Only</fullName>
                </value>
                <value>
                    <fullName>External Facing Public</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OCIO_CSWR_JobType__c</fullName>
        <inlineHelpText>Please select the work needed to be done, you are planning to request.</inlineHelpText>
        <label>Primary Job Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Photography</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Video</fullName>
                </value>
                <value>
                    <fullName>Graphics</fullName>
                </value>
                <value>
                    <fullName>Printing</fullName>
                </value>
                <value>
                    <fullName>FOIA Requests</fullName>
                </value>
                <value>
                    <fullName>OIG Requests</fullName>
                </value>
                <value>
                    <fullName>Litigation Hold</fullName>
                </value>
                <value>
                    <fullName>Congressional Inquiries</fullName>
                </value>
                <value>
                    <fullName>Legal Requests</fullName>
                </value>
                <value>
                    <fullName>Special HR Request</fullName>
                </value>
                <value>
                    <fullName>Supervisor Special Request</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Normal</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Critical</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Requestor_ID__c</fullName>
        <label>Requestor ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requestor_Original_Date__c</fullName>
        <label>Requestor Original Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Requestor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requestor</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Request Tracker (Requestor)</relationshipLabel>
        <relationshipName>Request_Tracker1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>At Printer</fullName>
                </value>
                <value>
                    <fullName>At Contractor</fullName>
                </value>
                <value>
                    <fullName>Waiting on Client</fullName>
                </value>
                <value>
                    <fullName>Waiting on Vendor</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Closed - Duplicate</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
                <value>
                    <fullName>Pending Supervisor Review</fullName>
                </value>
                <value>
                    <fullName>Approved by Supervisor</fullName>
                </value>
                <value>
                    <fullName>Rejected by Supervisor</fullName>
                </value>
                <value>
                    <fullName>Pending Final Review</fullName>
                </value>
                <value>
                    <fullName>Approved by Final Team</fullName>
                </value>
                <value>
                    <fullName>Rejected by Final Team</fullName>
                </value>
                <value>
                    <fullName>Assigned For Work Completion</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Alternative product found</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Closed: Resolved</fullName>
                </value>
                <value>
                    <fullName>Closed: Unresolved</fullName>
                </value>
                <value>
                    <fullName>Closed: Duplicate</fullName>
                </value>
                <value>
                    <fullName>Closed: Litigation</fullName>
                </value>
                <value>
                    <fullName>Forwarded to OIG For Review</fullName>
                </value>
                <value>
                    <fullName>Tasked to Personnel Office For Review</fullName>
                </value>
                <value>
                    <fullName>Tasked To a Region/Office For Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Request Tracker</label>
    <nameField>
        <displayFormat>{YYYY}-{0000}</displayFormat>
        <label>Request Tracker Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request Tracker</pluralLabel>
    <recordTypes>
        <fullName>EvidencePreservationRequests</fullName>
        <active>true</active>
        <description>To create Evidence Preservation Requests</description>
        <label>Evidence Preservation Requests</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestRequestTrackerTrigger.cls
/*
  TestRequestTrackerTrigger.cls
  Class for testing Request Tracker trigger on Request_Tracker__c object
  -------------------------------------------------------------------------------
  Author                 Date        Version  Description
  -------------------------------------------------------------------------------
  Rajakumar              05/01/2012  1.0      Creation
  Rajakumar              05/17/2012  1.1      Inclued the logic to share the blog 
                                              request record with the supervisor and change the owner to blog queue
  Rajakumar              01/23/2015  1.2      Revised the class for communication job log and blog request
    */
@isTest
private class TestRequestTrackerTrigger 
{
    //For validating the before insert trigger
    @isTest
    static void testBeforeInsert() {
        //List<Request_Tracker__c> compreqs = new List<Request_Tracker__c>();
        Request_Tracker__c request = new Request_Tracker__c();
        Id compRecTypeId = [SELECT Id,DeveloperName FROM RecordType WHERE Name = 'Complaint Tracker' 
                                        AND SObjectType = 'Request_Tracker__c' LIMIT 1].Id;
        Group pubgrpId = [Select Id from Group Where DeveloperName = 'Request_Tracker_Complaint_Tracker_User' LIMIT 1]; 
        User usr = [SELECT Id, Name FROM User WHERE IsActive = true AND Id =:UserInfo.getUserId()];
        request.Category__c = 'EEO';
        request.Status__c = 'Active';
        request.OCIO_Blog_InternalOrExternal__c = 'Internal GSA-Only';
        request.Priority__c = 'Low';
        request.recordTypeId = compRecTypeId; 
        try {
            insert request;
        }
        catch(DMLException e) {
            System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION', e.getDmlStatusCode(0));
        }    
    }
    
    //For validating the before update trigger
    @isTest(SeeAllData=true)
    static void testBeforeUpdate() {
        List<Request_Tracker__c> eprreqs = new List<Request_Tracker__c>();
        Set<Id> groupIds = new Set<Id>();
        Request_Tracker__c eprRequest = new Request_Tracker__c();
        
        Id EPRrecTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'EvidencePreservationRequests' 
                         AND SObjectType = 'Request_Tracker__c'].Id;
        Id EPRpublicGroupId = [Select Id from Group Where DeveloperName = 'Request_Tracker_EPR_ServerServices'].Id;
        List<GroupMember> grpuserlist = [Select GroupId, UserorGroupId from GroupMember Where GroupId = :EPRpublicGroupId LIMIT 2];
        List<Contact> contacts = [SELECT Id, Name FROM Contact LIMIT 2];
        User thisUser = [SELECT Id, Name from User WHERE Id =:UserInfo.getUserId()];
        //List<User> users = [SELECT Id FROM User WHERE IsActive = true AND Id = :grpuserlist[0].UserorGroupId LIMIT 1];
        eprRequest.recordTypeId = EPRrecTypeId;
        eprRequest.Requestor_ID__c = 'TTEST1234KL23';
        eprRequest.Requestor__c = contacts[0].Id;
        eprRequest.Requestor_Original_Date__c = Date.today();
        eprRequest.Status__c = 'Active';
        eprRequest.OCIO_CSWR_JobType__c = 'FOIA Requests';
        eprRequest.FOIA__c = '12345678';
        groupIds.add(EPRpublicGroupId);
        insert eprRequest;
        System.runAs(thisUser) {
            Test.startTest();
            RequestTrackerHelper.createGroupMembers(groupIds);
            Test.stopTest();
            try {
                //Commented below lines to improve the code Coverage - Ramesh 4/7/17
                //eprRequest.FOIA__c = '23456789';
                //eprRequest.Requestor_ID__c = 'TTEST1234KL123';
                //eprRequest.Requestor_Original_Date__c = Date.today();
                eprRequest.Number_of_Flash_Drive_s__c  = 5;
                update eprRequest;
                //Test.stopTest();
            }
            catch(DMLException e) {
                System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION', e.getDmlStatusCode(0));
            }
        }
    } 
}