src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>GSA</fullName>
        <active>true</active>
        <description>This contact record is used to track information for GSA employees.</description>
        <label>GSA</label>
    </recordTypes>
    <recordTypes>
        <fullName>Individual</fullName>
        <active>true</active>
        <description>This contact record is used to track Individuals.</description>
        <label>Individual</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GPM_Project__c.object
<CustomObject>
    <description>This is the primary object in the Project Central app; it is used to capture information about GSA projects.  The current build primarily supports app development as well as the needs of the PMO office.</description>
    <fields>
        <fullName>ConvertedFromRequest__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Determines whether or not this project was converted from a request.</inlineHelpText>
        <label>Converted From Request</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Use this field to select the person responsible for management of the project.</inlineHelpText>
        <label>Project Manager</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Projects (Project Manager)</relationshipLabel>
        <relationshipName>Projects1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/P360_ProjectPulseEmailReminderTest.cls
@isTest
private class P360_ProjectPulseEmailReminderTest {

	public  static String CRON_EXP = '0 0 0 15 3 ? 2022';

	@testSetup public static void dataPrep() {

	  Id projRecordTypeId = Schema.SObjectType.GPM_Project__c.getRecordTypeInfosByName().get('Corporate IT Services').getRecordTypeId();
	  Id contactRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual').getRecordTypeId();
      Contact con = new Contact();
      con.LastName = 'TestLAst';
      con.Email = 'test.name@gsa.gov';
      con.RecordTypeId = contactRecordTypeId;
      insert con;

      GPM_Project__c testproj = new GPM_Project__c();
      testproj.Name = 'Project 1';
      testproj.RecordTypeId = projRecordTypeId;
      testproj.ConvertedFromRequest__c = True;
      testproj.Project_Manager__c = con.Id;
      Insert testproj;
      System.assert(testproj.Name=='Project 1','1 new project created');
   }


	
	@isTest 
	Public static void schedulerTest() {
		System.Test.startTest();

      // Schedule the test job
      String jobId = System.schedule('ScheduleApexClassTest',
                        CRON_EXP,
                        new P360_ProjectPulseEmailReminder());

      // Get the information from the CronTrigger API object
      CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered,
         NextFireTime
         FROM CronTrigger WHERE id = :jobId];

      // Verify the expressions are the same
      System.assertEquals(CRON_EXP,
         ct.CronExpression);

      // Verify the job has not run
      System.assertEquals(0, ct.TimesTriggered);

      // Verify the next time the job will run
      System.assertEquals('2022-03-15 00:00:00',
         String.valueOf(ct.NextFireTime));

      System.Test.stopTest();
	}
	
}