src/objects/Controlled_Document__c.object
<CustomObject>
    <label>Controlled Document</label>
    <nameField>
        <displayFormat>CC{000000}</displayFormat>
        <label>Document ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Controlled Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Controlled_Document_Feed__c.object
<CustomObject>
    <description>This Object is being used by the Controlled Document Tracker application.</description>
    <fields>
        <fullName>Controlled_Document__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Controlled Document</label>
        <referenceTo>Controlled_Document__c</referenceTo>
        <relationshipName>Controlled_Document_Feed</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Grant Update Access Request</label>
    <nameField>
        <displayFormat>GUA-{0000000}</displayFormat>
        <label>Grant Update Access Requests</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grant Update Access Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestBatchQualityAssuranceController.cls
@isTest 
private class TestBatchQualityAssuranceController {
	
	@isTest static void testController(){
		Test.startTest();

		// start Grant Update Access batch
		GrantAccessToChatterFileBatch b = new GrantAccessToChatterFileBatch();
		ID batchprocessid = Database.executeBatch(b, 1);

		// create a controlled document
		//ControlledDocumentTestUtility.createRequiredChatterGroups();
		List<User> exsitingStandardUsers = ControlledDocumentTestUtility.getStandardUsers(1);
		User testUser1 = exsitingStandardUsers.get(0);
		System.runAs(testUser1) {
			Controlled_Document__c controlDoc = ControlledDocumentTestUtility.createTestControlDoc();
			insert controlDoc;
		}

		// query CD
		List<Controlled_Document__c> cdList = [SELECT Id FROM Controlled_Document__c LIMIT 1];

		// create a Grant Update Access Request
		Controlled_Document_Feed__c cdf = new Controlled_Document_Feed__c();
		cdf.Controlled_Document__c = cdList.get(0).Id;
		cdf.Status__c = 'Pending';
		insert cdf;

		// instantiate the controller
		BatchQualityAssuranceController batchQualityAssuranceController = new BatchQualityAssuranceController();
		//BatchQualityAssuranceController.BatchWrapper bw = new BatchQualityAssuranceController.BatchWrapper('', 0, System.now());
		//BatchQualityAssuranceController.BadControlledDocuments bcd = new BatchQualityAssuranceController.BadControlledDocuments('', '', '', '', System.now());

		// the assert
		System.assertNotEquals(b, null);

		Test.stopTest();
	}

}