src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>GSA</fullName>
        <active>true</active>
        <description>This contact record is used to track information for GSA employees.</description>
        <label>GSA</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Survey__c.object
<CustomObject>
    <description>Collects results for the Survey type.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Surveys</relationshipLabel>
        <relationshipName>Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <displayFormat>SUR-{0000}</displayFormat>
        <label>Survey ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <recordTypes>
        <fullName>Employee_Email_Survey</fullName>
        <active>true</active>
        <label>Employee Email Survey</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestSurveyController.cls
@isTest(SeeAllData=true)
public class TestSurveyController {
    static testMethod void changeOwner(){
        Profile p = [SELECT Id FROM Profile WHERE Name = 'GSA Standard Salesforce User' LIMIT 1];
        User u = [SELECT Id, Email FROM User WHERE isActive = true AND ProfileId =: p.Id LIMIT 1];
        Contact c = [SELECT Id, Email FROM Contact WHERE Email =: u.Email LIMIT 1];
       // Contact c = [SELECT Id, Email FROM Contact WHERE Email = 'anne.egan@gsa.gov' LIMIT 1];
        RecordType rt = [SELECT Id, DeveloperName FROM RecordType WHERE DeveloperName = 'Employee_Email_Survey' LIMIT 1];
        Survey__c s = new Survey__c();
        s.Contact__c = c.Id;
        s.RecordTypeId = rt.Id;
        insert s;
        System.assertEquals(true,true);
        
    }
}