src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>GSA</fullName>
        <active>true</active>
        <description>This contact record is used to track information for GSA employees.</description>
        <label>GSA</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GPM_Project__c.object
<CustomObject>
    <description>This is the primary object in the Project Central app; it is used to capture information about GSA projects.  The current build primarily supports app development as well as the needs of the PMO office.</description>
    <fields>
        <fullName>ConvertedFromRequest__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Determines whether or not this project was converted from a request.</inlineHelpText>
        <label>Converted From Request</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Use this field to select the person responsible for management of the project.</inlineHelpText>
        <label>Project Manager</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Projects (Project Manager)</relationshipLabel>
        <relationshipName>Projects1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Use this field to identify the current phase of the project. The project phase should be updated as the project progresses through the project life cycle.</inlineHelpText>
        <label>Project Phase</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Concept Approval</fullName>
                </value>
                <value>
                    <fullName>Initiating</fullName>
                </value>
                <value>
                    <fullName>Planning</fullName>
                </value>
                <value>
                    <fullName>Executing</fullName>
                </value>
                <value>
                    <fullName>Design</fullName>
                </value>
                <value>
                    <fullName>Development</fullName>
                </value>
                <value>
                    <fullName>Testing</fullName>
                </value>
                <value>
                    <fullName>Deployment</fullName>
                </value>
                <value>
                    <fullName>Construction Procurement</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Close-Out</fullName>
                </value>
                <value>
                    <fullName>Close-Out/Closed</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>P360_CorporateITServices</fullName>
        <active>true</active>
        <description>P360 - Use this record type for creating projects that support &apos;Corporate IT Services&apos;</description>
        <label>Corporate IT Services</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/P360_ProjectPulseEmailReminder.cls
/*-------------------------------------------------------------------------------------------------*
Scheduler class for Sending email notifications to Project Managers (custom field - lookup Contact)
*--------------------------------------------------------------------------------------------------*
Author           | Date        | Version | Description
*--------------------------------------------------------------------------------------------------*
Mayank Singla      01/18/2017    1.0       Scheduler class created

*--------------------------------------------------------------------------------------------------*

*--------------------------------------------------------------------------------------------------*/

global class P360_ProjectPulseEmailReminder implements Schedulable {

    global void execute(SchedulableContext SC) {

        sendmail();

    }

    public void sendmail()
    {
        List<GPM_Project__c> projectList = [
                SELECT Id, Name, OwnerId, Project_Manager__c
                FROM GPM_Project__c
                WHERE Id != NULL 
                    AND Project_Manager__c != NULL 
                    AND ConvertedFromRequest__c = TRUE 
                    AND RecordTypeId IN (select Id 
                                     FROM RecordType 
                                     WHERE SobjectType = 'GPM_Project__c'
                                            AND DeveloperName = 'P360_CorporateITServices') 
                    AND (Status__c != 'Close-Out' AND Status__c != 'Close-Out/Closed' AND Status__c != 'Closed')
                ];

        Set<Id> projMngrId = new Set<Id>();

        for(GPM_Project__c proj : projectList){
            projMngrId.add(proj.Project_Manager__c);
        }

        Map<String, String> mapContactEmail = new Map<String, String>();
        List<Contact> contactList = [
                SELECT Id, Email FROM Contact WHERE Id IN :projMngrId
        ];

        for(Contact c : contactList){
            mapContactEmail.put(c.Id, c.Email);
        }

        Messaging.SingleEmailMessage m = new Messaging.SingleEmailMessage();
        List<Messaging.SingleEmailMessage> allMails = new List<Messaging.SingleEmailMessage>();

        for(GPM_Project__c  proj : projectList){
            m = new Messaging.SingleEmailMessage();
            String name = proj.Name;
            Id projId = proj.Id;
            String fullRecordURL = URL.getSalesforceBaseUrl().toExternalForm() +'/'+ proj.Id;

            OrgWideEmailAddress[] owea = [
                    SELECT Id
                    FROM OrgWideEmailAddress
                    WHERE DisplayName like '%Corporate IT%'
            ];

            if ( owea.size() > 0 ) {
                m.setOrgWideEmailAddressId(owea.get(0).Id);
            }

            m.setSubject('Bi-Weekly Status Update');
            String body ='<html lang="en"><body>'+
                '<br><br>'+
                'Hello,'+
                '<br><br>'+
                'As a friendly reminder, please provide your bi-weekly status for the following Project: '+
                '<a href=' + '"' + fullRecordURL + '"' + '>' + name + '</a>' + '. ' +
                'All Corporate IT Services projects are reviewed every 2 weeks and require an updated Pulse. '+
                'If you have any questions/concerns, please contact: '+
                '<a href='+'"'+'mailto:corporateitservicesrequestsupport@gsa.gov'+'"'+'>'+'Corporate IT Services Request Team.'+'<a>'+
                '<br><br>'+
                'When creating your Pulse, please make sure you enter each item on a new line without numbers or dashes.' + '' +
                ' For example:'+
                '<br><br>'+
                '<b>'+'Accomplishments:'+'</b>'+
                '<br>'+
                'This is Accomplishment 1'+
                '<br>'+
                'This is Accomplishment 2'+
                '<br><br>'+
                'Thank you,'+'<br>'+
                'Corporate IT Services Request Team'+ '<br>'+
                'Email: '+'<a href=mailto:corporateitservicesrequestsupport@gsa.gov>'+'CorporateITServicesRequestSupport@gsa.gov'+ '<a>'+
                '</body></html>';
            m.setHTMLBody(body);
            m.setToAddresses(new String[]{string.valueof(mapContactEmail.get(proj.Project_Manager__c))});
            allMails.add(m);
        }
        Messaging.sendEmail(allMails);
    }
}