src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>OCR_Contact_Via__c</fullName>
        <label>Contact Via</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>E-Mail</fullName>
                </value>
                <value>
                    <fullName>Mail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OCR_Reporting_State__c</fullName>
        <formula>TEXT( Account.OCR_Reporting_State__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Reporting State</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>GSA</fullName>
        <active>true</active>
        <description>This contact record is used to track information for GSA employees.</description>
        <label>GSA</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OCIO_Title_VI_Submission__c.object
<CustomObject>
    <description>This object is for the Office of Civil Rights - Title VI application and used to track Title VI Compliance Submissions submitted by the donees.</description>
    <fields>
        <fullName>OCR_Administrative_Grievance_Procedure_D__c</fullName>
        <label>Description</label>
        <length>2500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>OCR_Administrative_Grievance_Procedure__c</fullName>
        <label>Administrative Grievance Procedure</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OCR_Complaint_Received__c</fullName>
        <label>Complaint Received</label>
        <length>2500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>OCR_Complaints_Filed__c</fullName>
        <label>Complaints Filed</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OCR_Donee_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Donee Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Title VI Submissions</relationshipLabel>
        <relationshipName>Title_VI_Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OCR_Donee_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Donee Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Title VI Submissions</relationshipLabel>
        <relationshipName>Title_VI_Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OCR_Hearing_Visual_Impaired_Assistance__c</fullName>
        <label>Hearing/Visual Impaired Assistance</label>
        <length>2500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>OCR_How_Did_You_Learn__c</fullName>
        <label>How Did You Learn</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Word of Mouth</fullName>
                </value>
                <value>
                    <fullName>Information Briefing/Presentation</fullName>
                </value>
                <value>
                    <fullName>Television or radio</fullName>
                </value>
                <value>
                    <fullName>Newspaper</fullName>
                </value>
                <value>
                    <fullName>Mailing</fullName>
                </value>
                <value>
                    <fullName>Internet</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OCR_Information_Unavailable__c</fullName>
        <label>Information Unavailable</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OCR_LEP_Actual_Cost__c</fullName>
        <label>LEP Actual Cost</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OCR_LEP_Additional_Cost__c</fullName>
        <label>LEP Additional Cost</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OCR_LEP_Notification_Method_Other__c</fullName>
        <inlineHelpText>If other, please explain:</inlineHelpText>
        <label>LEP Notification Method - Other</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>OCR_LEP_Notification_Method__c</fullName>
        <label>LEP Notification Method</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Post Written Notice in Non-English Lang</fullName>
                </value>
                <value>
                    <fullName>Brochure</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OCR_Languages_Most_Encountered__c</fullName>
        <label>Languages Most Encountered</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Spanish</fullName>
                </value>
                <value>
                    <fullName>Chinese</fullName>
                </value>
                <value>
                    <fullName>Vietnamese</fullName>
                </value>
                <value>
                    <fullName>Korean</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OCR_Lanuage_Other__c</fullName>
        <inlineHelpText>If other language, please explain:</inlineHelpText>
        <label>Language Other</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>OCR_Limited_English_Proficiency__c</fullName>
        <label>Limited English Proficiency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OCR_Market_Advertise__c</fullName>
        <label>Market/Advertise</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OCR_Organizational_Background__c</fullName>
        <inlineHelpText>Please describe the nature and purpose of your agency/organization, to include programs and activities conducted by your agency/organization.</inlineHelpText>
        <label>Organizational Background</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>OCR_Organizational_Type_Other__c</fullName>
        <inlineHelpText>If other, please explain:</inlineHelpText>
        <label>Organizational Type - Other</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>OCR_Organizational_Type__c</fullName>
        <inlineHelpText>Please mark one or more of the following categories that best describes the “organizational type” for your agency/organization:</inlineHelpText>
        <label>Organizational Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>State Government Agency</fullName>
                </value>
                <value>
                    <fullName>County or City Government Agency</fullName>
                </value>
                <value>
                    <fullName>Non-profit Organization</fullName>
                </value>
                <value>
                    <fullName>Healthcare-related Provider</fullName>
                </value>
                <value>
                    <fullName>Educational Provider</fullName>
                </value>
                <value>
                    <fullName>Provider to the Homeless or Impoverished</fullName>
                </value>
                <value>
                    <fullName>Minority-focused</fullName>
                </value>
                <value>
                    <fullName>Women-focused</fullName>
                </value>
                <value>
                    <fullName>Program for Older Individuals</fullName>
                </value>
                <value>
                    <fullName>Individuals with Disabilities-focused</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OCR_Preparation_Date__c</fullName>
        <label>Preparation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OCR_Problems_Experienced__c</fullName>
        <label>Problems Experienced</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OCR_Property_Availability__c</fullName>
        <label>Property Availability</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OCR_Property_Quality__c</fullName>
        <label>Property Quality</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Excellent</fullName>
                </value>
                <value>
                    <fullName>Good</fullName>
                </value>
                <value>
                    <fullName>Fair</fullName>
                </value>
                <value>
                    <fullName>Poor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OCR_Rollout__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rollout</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Title VI Submissions</relationshipLabel>
        <relationshipName>Title_VI_Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OCR_Submission_Status__c</fullName>
        <label>Submission Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No Activity</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Reviewed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OCR_Training_Educational_Programs_Desc__c</fullName>
        <label>Training/Educational Program Description</label>
        <length>2500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>OCR_Training_Educational_Programs__c</fullName>
        <label>Training/Educational Programs</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OCR_Trans_Interpretation_Assis_Other__c</fullName>
        <inlineHelpText>If other, please explain:</inlineHelpText>
        <label>Trans/Interpretation Assis - Other</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>OCR_Translation_or_Interpretation_Assist__c</fullName>
        <label>Translation or Interpretation Assistance</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bilingual Staff</fullName>
                </value>
                <value>
                    <fullName>Contract Interpreter/Translator</fullName>
                </value>
                <value>
                    <fullName>Translated Written Materials</fullName>
                </value>
                <value>
                    <fullName>Volunteers</fullName>
                </value>
                <value>
                    <fullName>Local Community-based Organization</fullName>
                </value>
                <value>
                    <fullName>Local College/University Language Dept</fullName>
                </value>
                <value>
                    <fullName>State Agency That Provides This Service</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OCR_Unavailable_Data__c</fullName>
        <label>Unavailable Data</label>
        <length>2500</length>
        <type>LongTextArea</type>
    </fields>
    <label>Title VI Submission</label>
    <nameField>
        <displayFormat>TVIS-{0000000}</displayFormat>
        <label>Title VI Submission ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Title VI Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TitleVISubmissionControllerTest.cls
@isTest(seeAlldata = false)
private class TitleVISubmissionControllerTest {
    
    @testSetup
    static void createtestdata(){
        PublicUserGroupHandler.disableGroupMemberRecalculation = true;
        User thisUser = [SELECT Id,userroleid FROM User WHERE Id = :UserInfo.getUserId()];
        thisuser.userroleid='00E30000001ZtBrEAK';
        update thisuser;
        
        system.runAs(thisUser){       
            //--------------------------------
            OCIO_Title_VI_Submission__c titleVISubmissionRec2 = new OCIO_Title_VI_Submission__c();
            titleVISubmissionRec2.OCR_Preparation_Date__c = System.today();
            
            //Assign record to user/contact
            //Campaign
            Campaign camp = new Campaign(Name='test campaign');
            insert camp;
            titleVISubmissionRec2.OCR_Rollout__c =camp.id;
            //Account
            ID acctRecordTypeId = [select Id from RecordType where name = 'Title VI Account' limit 1].id;
            Account acct = new Account(Name='test account', Type='Donee', OCR_Reporting_State__c='VA', OCR_Title_VI_Status__c='Active',
                                                                    BillingStreet='123 Main St', BillingCity='Springs', BillingState='VA', BillingPostalCode='22153', BillingCountry='USA',
                                                                    recordTypeId=acctRecordTypeId);
            insert acct;
            titleVISubmissionRec2.OCR_Donee_Account__c = acct.id;
            //Contact - User
            
            ID contactRecordTypeId = [select Id from RecordType where name = 'Title VI Contact' limit 1].id;
            Contact contact = new Contact(lastName='Newtest',firstName='NewTest123',title='Test',
                                                            email='emailtest@test.com',OCR_Contact_Via__c='email',accountId=acct.Id, recordTypeId=contactRecordTypeId);
            insert contact;
          
            /*Profile p = [select Id, Name from Profile where name like '%Portal User%' limit 1];
            User portalUser = new User(alias = 'portalu', email='test@test.com',
                                            emailencodingkey='UTF-8', firstName='Testing', lastName='Testing', languagelocalekey='en_US',
                                            localesidkey='en_US', contactid = contact.id, profileid = p.Id, timezonesidkey='America/Los_Angeles', username='test@test.com');
            
            insert portalUser;*/
            User portalUser = new User();
            Profile p = [select Id, Name from Profile where name like '%GSA OCR Title VI OHVCP User%' limit 1];
            portalUser = new User(alias = 'portalu', email='test@test.com',
                                            emailencodingkey='UTF-8', firstName='Testing', lastName='Testing', languagelocalekey='en_US',
                                            localesidkey='en_US', contactid = contact.id,portalRole= 'worker', profileid = p.Id, timezonesidkey='America/Los_Angeles', username='test@test.com');
            
            insert portalUser;
            
           // Profile p = [select Id, Name from Profile where name like '%GSA OCR Title VI OHVCP User%' limit 1];
           // User portalUser = [select id from User where profileid =: p.id and isActive = true limit 1];
            
            titleVISubmissionRec2.OCR_Donee_Contact__c = contact.id;
            titleVISubmissionRec2.OCR_Submission_Status__c = 'Draft';
            insert titleVISubmissionRec2;
        }
    }
    static testmethod void testTitleVIController() {
        OCIO_Title_VI_Submission__c rec = [select id,OCR_Rollout__c,OCR_Submission_Status__c,OCR_Donee_Contact__c,OCR_Donee_Account__c,OCR_Preparation_Date__c
                                           from OCIO_Title_VI_Submission__c limit 1];
        User portalUser = [select id from User where email = 'test@test.com' limit 1];
        test.starttest();  
        System.runAs(portalUser) {
            ApexPages.currentPage().getParameters().put('id', rec.id);
            ApexPages.Standardcontroller stdc = new ApexPages.Standardcontroller(new OCIO_Title_VI_Submission__c());
            TitleVISubmissionController controller2 = new TitleVISubmissionController(stdc);
            List<OCIO_Title_VI_Submission__c> recList = controller2.getEditableRecords();
            System.assertNotEquals(0, recList.size());
            recList = controller2.getNonEditableRecords();
            System.assertEquals(true,controller2.getIsPortalUser());
            
            controller2.edit();
            
            controller2.submit();
            String fieldname = controller2.fieldLabel.get('OCR_Organizational_Background__c');
            //System.assert(ApexPages.getMessages().get(1).getDetail().contains(fieldname));
            
            controller2.titleVISubmission.OCR_Organizational_Background__c = 'startup';
            controller2.saveDraft();
            controller2.submit();
            fieldname = controller2.fieldLabel.get('OCR_Organizational_Type__c');
            //System.assert(ApexPages.getMessages().get(2).getDetail().contains(fieldname));
            
            controller2.titleVISubmission.OCR_Organizational_Type__c = 'Minority-focused';
            controller2.titleVISubmission.OCR_Organizational_Type_Other__c = 'test';
            controller2.saveDraft();
            controller2.submit();
            
            controller2.titleVISubmission.OCR_Organizational_Type__c = 'Other';
            controller2.saveDraft();
            controller2.submit();
            
            controller2.titleVISubmission.OCR_Organizational_Type_Other__c = 'test';
            controller2.saveDraft();
            controller2.submit();
            
            controller2.titleVISubmission.OCR_Limited_English_Proficiency__c = 'Yes';
            controller2.saveDraft();
            controller2.submit();
            
            controller2.titleVISubmission.OCR_Languages_Most_Encountered__c = 'Chinese';
            controller2.titleVISubmission.OCR_Lanuage_Other__c = 'Other';
            controller2.saveDraft();
            controller2.submit();
            
            controller2.titleVISubmission.OCR_Languages_Most_Encountered__c = 'Other';
            controller2.saveDraft();
            controller2.submit();
            
            controller2.titleVISubmission.OCR_Lanuage_Other__c = 'Other';
            controller2.saveDraft();
            controller2.submit();
            
            controller2.titleVISubmission.OCR_Translation_or_Interpretation_Assist__c = 'Volunteers';
            controller2.titleVISubmission.OCR_Trans_Interpretation_Assis_Other__c = 'Other';
            controller2.saveDraft();
            controller2.submit();
            
            controller2.titleVISubmission.OCR_Translation_or_Interpretation_Assist__c = 'Other';
            controller2.saveDraft();
            controller2.submit();
            
            controller2.titleVISubmission.OCR_Trans_Interpretation_Assis_Other__c = 'Other';
            controller2.saveDraft();
            controller2.submit();
            
            controller2.titleVISubmission.OCR_LEP_Notification_Method__c = 'Brochure';
            controller2.titleVISubmission.OCR_LEP_Notification_Method_Other__c = 'Other';
            controller2.saveDraft();
            controller2.submit();
            
            controller2.titleVISubmission.OCR_LEP_Notification_Method__c = 'Other';
            controller2.saveDraft();
            controller2.submit();
            
            controller2.titleVISubmission.OCR_LEP_Notification_Method_Other__c = 'Other';
            controller2.saveDraft();
            controller2.submit();
            
            controller2.titleVISubmission.OCR_LEP_Additional_Cost__c = 'Yes';
            controller2.saveDraft();
            controller2.submit();
            
            controller2.titleVISubmission.OCR_LEP_Actual_Cost__c = 45;
            controller2.saveDraft();
            controller2.submit();
            
            controller2.titleVISubmission.OCR_Hearing_Visual_Impaired_Assistance__c = 'Yes';
            controller2.saveDraft();
            controller2.submit();
            
            controller2.titleVISubmission.OCR_Training_Educational_Programs__c = 'Yes';
            controller2.saveDraft();
            controller2.submit();
            
            controller2.titleVISubmission.OCR_Training_Educational_Programs_Desc__c = 'Desc';
            controller2.saveDraft();
            controller2.submit();
            
            controller2.titleVISubmission.OCR_Administrative_Grievance_Procedure__c = 'Yes';
            controller2.saveDraft();
            controller2.submit();
            
            controller2.titleVISubmission.OCR_Administrative_Grievance_Procedure_D__c = 'Desc';
            controller2.saveDraft();
            controller2.submit();
            
            controller2.titleVISubmission.OCR_Market_Advertise__c = 'Yes';
            controller2.saveDraft();
            controller2.submit();
            
            controller2.titleVISubmission.OCR_Complaints_Filed__c = 'Yes';
            controller2.saveDraft();
            controller2.submit();
            
            controller2.titleVISubmission.OCR_Complaint_Received__c = 'Yes';
            controller2.saveDraft();
            controller2.submit();
            
            controller2.titleVISubmission.OCR_How_Did_You_Learn__c = 'Yes';
            controller2.saveDraft();
            controller2.submit();
            
            controller2.titleVISubmission.OCR_Property_Availability__c = 'Yes';
            controller2.saveDraft();
            controller2.submit();
            
            controller2.titleVISubmission.OCR_Problems_Experienced__c = 'Yes';
            controller2.saveDraft();
            controller2.submit();
            
            controller2.titleVISubmission.OCR_Property_Quality__c = 'Yes';
            controller2.saveDraft();
            controller2.submit();
            
            controller2.titleVISubmission.OCR_Information_Unavailable__c = 'Yes';
            controller2.saveDraft();
            controller2.submit();
            
            controller2.titleVISubmission.OCR_Unavailable_Data__c = 'Yes';
            controller2.saveDraft();
            controller2.submit();
            
            
            controller2.editReview();
            controller2.saveReview();
            controller2.cancelAction();
            
            controller2.cancelEdit();
            
            recList = controller2.getNonEditableRecords();
            System.assertNotEquals(0, recList.size());
            
            //Test Exception block
            controller2.titleVISubmission=null;
            controller2.submit();     
        }
        test.stoptest();
        //Test record creation and saving
        OCIO_Title_VI_Submission__c titleVISubmissionRec = new OCIO_Title_VI_Submission__c();
        titleVISubmissionRec.OCR_Administrative_Grievance_Procedure__c = 'No';
        titleVISubmissionRec.OCR_Preparation_Date__c = System.today();
        insert titleVISubmissionRec;
        
        ApexPages.currentPage().getParameters().put('id', titleVISubmissionRec.id);
        TitleVISubmissionController controller = new TitleVISubmissionController(new ApexPages.Standardcontroller(titleVISubmissionRec));
        controller.saveDraft();
        
        System.assertEquals('Draft',controller.titleVISubmission.OCR_Submission_Status__c);
        controller.submit();
        //Still draft status - no validation
        System.assertEquals('Draft',controller.titleVISubmission.OCR_Submission_Status__c);
        
        System.assert(controller.getIsEditable());
        
        //Test Exception blocks
        ApexPages.currentPage().getParameters().put('id', null);
        ApexPages.Standardcontroller stdc = new ApexPages.Standardcontroller(new OCIO_Title_VI_Submission__c());
        TitleVISubmissionController controller2 = new TitleVISubmissionController(stdc);
        controller2.titleVISubmission=null;
        controller2.saveDraft();
        controller2.submit();
        
        //Test portal user
        System.assertEquals(false,controller.getIsPortalUser());
    }
    
}