src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>NewHireEmailTextStatuses__c</fullName>
        <description>Track Survey Email Status Processes by text values. Should be hidden, possibly read only.
Expected values are: 
NH_30 Day Sent;
NH_30 Day Responded;
NH_90 Day Sent;
NH_90 Day Responded;
NH_180 Day Sent;
NH_180 Day Responded;
NH_1 Year Sent;
NH_1 Year Responded;
NH_1.5 Years Sent;
NH_1.5 Years Responded;</description>
        <label>New Hire Email Text Statuses</label>
        <length>350</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Supervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to the supervisor of this Contact.</description>
        <label>Supervisor</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supervisory_Status__c</fullName>
        <description>Populated based on same field on corresponding User record by Federation Identifier.</description>
        <label>Supervisory Status</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/EmailTracker__c.object
<CustomObject>
    <description>Object to store the email reminders for the Contact Manager VOE OHRM Surveys i.e. Hiring manager, Supervisor, etc</description>
    <fields>
        <fullName>Hired_Employee_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Hired Employee ID</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Email Trackers (Hired Employee ID)</relationshipLabel>
        <relationshipName>Email_Trackers2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hired_Employee__c</fullName>
        <description>This field is used to populate who was hired that caused the hiring survey to fire.</description>
        <label>Hired Employee</label>
        <length>96</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SendDate__c</fullName>
        <description>Date the email was or will be sent.</description>
        <label>Send Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the email, Pending or Responded.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Queued</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Responded</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SurveyURL__c</fullName>
        <label>Survey URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>ToContact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Contact Recipient</description>
        <label>To Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Email Trackers</relationshipLabel>
        <relationshipName>Email_Trackers</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Options are 1-1 with Survey Master Record Names</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>VOE - Hiring Manager Survey</fullName>
                </value>
                <value>
                    <fullName>VOE - New Supervisor Survey</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Email Tracker</label>
    <nameField>
        <displayFormat>ET-{00000000}</displayFormat>
        <label>Email Tracking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Trackers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ContactHelper.cls
/*-------------------------------------------------------------------------------------------------*
  Apex class
  Helper class for ContactTriggers apex trigger - Contact Manager VOE Surveys
 *-------------------------------------------------------------------------------------------------*
  Author           | Date        | Version | Description
 *-------------------------------------------------------------------------------------------------*
  Rajakumar          08/17/2015    1.0       Initial version.
  Rajakumar          09/30/2015    1.1       case# 21022 - avoid multiple triggers of hiring manager surveys
  GaneshKumar Mandava    08/24/2017           Removed code that uses SurveyURL__c field on Email Tracker Object
 *-------------------------------------------------------------------------------------------------*
 *-------------------------------------------------------------------------------------------------*/
 public class ContactHelper {
     // after updating the contact record
     /*
     This is to create the EmailTracker__c record for respective Supervisor__c (send the email for hiring manager feedback)
     when the contact NewHireEmailTextStatuses__c is changed to 'NH_30 Day Sent'
     */
     public static void onAfterUpdate(List<Contact> triggerNew, Map<Id, Contact> triggerOldMap) {
         // declarations
         Set<Id> contactIds = new Set<Id>();
         Map<Id, Id> contactToSupervisorMap = new Map<Id,Id>();
         List<EmailTracker__c> newets = new List<EmailTracker__c>();
         String surveyBaseURLof30DayNH = null;
         // processing the contacts which are come under the survey i.e.NH 30 Day Sent
         for(Contact c: triggerNew) {
             String newhireStatusText = (c.NewHireEmailTextStatuses__c != null) ? c.NewHireEmailTextStatuses__c: null;
             // added validation for case# 21022 - BEGIN
             Boolean old30DaySentFlag = false;
             if(triggerOldMap.get(c.Id).NewHireEmailTextStatuses__c != null &&
                 triggerOldMap.get(c.Id).NewHireEmailTextStatuses__c.contains('NH_30 Day Sent') )
                 old30DaySentFlag = true;
             // added validation for case# 21022 - END
             if(c.NewHireEmailTextStatuses__c != null &&
                 newhireStatusText.containsIgnoreCase('NH_30 Day Sent') && c.Supervisor__c != null &&
                 (c.NewHireEmailTextStatuses__c != triggerOldMap.get(c.Id).NewHireEmailTextStatuses__c) &&
                 // added below line oldmapflag validation for case# 21022
                 old30DaySentFlag == false) {

                 System.debug('statustext: '+c.NewHireEmailTextStatuses__c);
                 contactIds.add(c.Id);
                
                 system.debug('hired employee name: ' + c.Name);
                 system.debug('hired first name: ' + c.FirstName);
                 system.debug('hired last name name: ' + c.LastName);
                 newets.add(new EmailTracker__c(Status__c='Sent',
                                             Type__c= 'VOE - Hiring Manager Survey',
                                             ToContact__c= c.Supervisor__c,
                                             Hired_Employee__c = c.FirstName + ' ' + c.LastName,
                                             Hired_Employee_ID__c = c.id,
                                             SendDate__c= Date.today()));
             }
         }

         // insert the new emailtracker records
         if(!contactIds.isEmpty()) {
             try {
                 insert newets;
             }
             catch(DMLException e) {
                 System.debug(LoggingLevel.INFO,'Error while inserting the OHRM VOE Hiring Manager Survey EmailTracker records :' +e.getMessage());
             }
         }
     }

    /**
     * Begin Acumen Solutions APEX development
     *
     * Trigger logic supporting the New Supervisor Survey functionality.
     *  Manage Email Tracker records to Queue and Send Email Alerts
     *  via Time-Based Workflow.
     *
     * @author Justin Lyon
     * @created 09.24.2015
     */

    private static final String EMTRACKER_QUEUED = 'Queued';
    private static final String NEW_SUPERVISOR_SURVEY = 'VOE - New Supervisor Survey';

    // After Update/Insert, When Contact.SupervisorStatus changes/is to 2, initiate the New Supervisor Survey process
    public static void catchNewSupervisors(List<Contact> newContacts, Map<Id, Contact> oldContactMap) {
        List<EmailTracker__c> emTrackers = new List<EmailTracker__c>();

        if(oldContactMap != null) { // After Update
            for(Contact c : newContacts) {
                Contact oldContact = oldContactMap.get(c.Id);
                if(isNewSupervisor(c) && c.Supervisory_Status__c != oldContact.Supervisory_Status__c) {
                    emTrackers.add(buildEmailTracker(c,EMTRACKER_QUEUED,NEW_SUPERVISOR_SURVEY));
                }
            }

        } else { // After Insert
            for(Contact c : newContacts) {
                if(isNewSupervisor(c)) {
                    emTrackers.add(buildEmailTracker(c,EMTRACKER_QUEUED,NEW_SUPERVISOR_SURVEY));
                }
            }
        }

        try {
            insert emTrackers;
        }
        catch(DMLException e) {
            System.debug(
                LoggingLevel.INFO,
                'Error while inserting the OHRM VOE New Supervisory Survey EmailTracker records :'
                + e.getMessage());
        }
    }

    private static Boolean isNewSupervisor(Contact newC) {
        return newC.Supervisory_Status__c == 2
            && newC.Email != null;
    }

    private static EmailTracker__c buildEmailTracker(Contact c, String status, String type) {
        return new EmailTracker__c(
            Status__c = status,
            Type__c = type,
            ToContact__c = c.Id,
            SendDate__c = Date.today().addDays(30));
    }
 }