src/objects/Controlled_Document__c.object
<CustomObject>
    <fields>
        <fullName>Current_Location_Start_Date_New__c</fullName>
        <label>Current Location Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Current_Location__c</fullName>
        <description>User selects what office/region/sub-office currently has the document</description>
        <label>Current Location</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>A - Office of the Administrator</fullName>
                </value>
                <value>
                    <fullName>B - Office of the Chief Financial Officer</fullName>
                </value>
                <value>
                    <fullName>C - Office of Human Resource Management</fullName>
                </value>
                <value>
                    <fullName>D - Office of Mission Assurance</fullName>
                </value>
                <value>
                    <fullName>E - Office of Small Business Utilization</fullName>
                </value>
                <value>
                    <fullName>G - Civilian Board of Contract Appeals</fullName>
                </value>
                <value>
                    <fullName>H - Office of Administrative Services</fullName>
                </value>
                <value>
                    <fullName>I - Office of the GSA IT</fullName>
                </value>
                <value>
                    <fullName>J - Office of the Inspector General</fullName>
                </value>
                <value>
                    <fullName>L - Office of the General Counsel</fullName>
                </value>
                <value>
                    <fullName>M - Office of Governmentwide Policy</fullName>
                </value>
                <value>
                    <fullName>O - Office of Customer Experience</fullName>
                </value>
                <value>
                    <fullName>P - Public Buildings Service</fullName>
                </value>
                <value>
                    <fullName>Q - Federal Acquisition Service</fullName>
                </value>
                <value>
                    <fullName>S - Office of Congressional and Intergovernmental Affairs</fullName>
                </value>
                <value>
                    <fullName>T - Technology Transformation Service</fullName>
                </value>
                <value>
                    <fullName>Y - Federal Permitting Improvement Steering Council</fullName>
                </value>
                <value>
                    <fullName>Z - Office of Strategic Communication</fullName>
                </value>
                <value>
                    <fullName>Region 1A</fullName>
                </value>
                <value>
                    <fullName>Region 1P</fullName>
                </value>
                <value>
                    <fullName>Region 1Q</fullName>
                </value>
                <value>
                    <fullName>Region 2A</fullName>
                </value>
                <value>
                    <fullName>Region 2P</fullName>
                </value>
                <value>
                    <fullName>Region 2Q</fullName>
                </value>
                <value>
                    <fullName>Region 3A</fullName>
                </value>
                <value>
                    <fullName>Region 3P</fullName>
                </value>
                <value>
                    <fullName>Region 3Q</fullName>
                </value>
                <value>
                    <fullName>Region 4A</fullName>
                </value>
                <value>
                    <fullName>Region 4P</fullName>
                </value>
                <value>
                    <fullName>Region 4Q</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Current_Stage_Start_Date_New__c</fullName>
        <label>Current Stage Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Days_In_Current_Location_New__c</fullName>
        <label>Days In Current Location</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Days_On_Current_Stage_New__c</fullName>
        <label>Days On Current Stage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Originating_Office__c</fullName>
        <inlineHelpText>The division originating or overseeing the Controlled Document. Once a value is selected, users from that Originating Service/Staff Office will be able to access and edit this Controlled Document unless further restrictions are implemented.</inlineHelpText>
        <label>Originating Service/Staff Office</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AK - Office of Civil Rights</fullName>
                </value>
                <value>
                    <fullName>A - Office of the Administrator</fullName>
                </value>
                <value>
                    <fullName>B - Office of the Chief Financial Officer</fullName>
                </value>
                <value>
                    <fullName>C - Office of Human Resource Management</fullName>
                </value>
                <value>
                    <fullName>D - Office of Mission Assurance</fullName>
                </value>
                <value>
                    <fullName>E - Office of Small Business Utilization</fullName>
                </value>
                <value>
                    <fullName>G - Civilian Board of Contract Appeals</fullName>
                </value>
                <value>
                    <fullName>H - Office of Administrative Services</fullName>
                </value>
                <value>
                    <fullName>I - Office of the GSA IT</fullName>
                </value>
                <value>
                    <fullName>J - Office of the Inspector General</fullName>
                </value>
                <value>
                    <fullName>L - Office of the General Counsel</fullName>
                </value>
                <value>
                    <fullName>M - Office of Governmentwide Policy</fullName>
                </value>
                <value>
                    <fullName>O - Office of Customer Experience</fullName>
                </value>
                <value>
                    <fullName>P - Public Buildings Service</fullName>
                </value>
                <value>
                    <fullName>PTT - Presidential Transition Team</fullName>
                </value>
                <value>
                    <fullName>Q - Federal Acquisition Service</fullName>
                </value>
                <value>
                    <fullName>S - Office of Congressional and Intergovernmental Affairs</fullName>
                </value>
                <value>
                    <fullName>T - Technology Transformation Service</fullName>
                </value>
                <value>
                    <fullName>Y - Federal Permitting Improvement Steering Council</fullName>
                </value>
                <value>
                    <fullName>Z - Office of Strategic Communication</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <inlineHelpText>An indication of where in the life-cycle of a Controlled Document this record resides. This field is manually updated by users with edit access to the Controlled Document record.</inlineHelpText>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Awaiting Closure</fullName>
                </value>
                <value>
                    <fullName>Awaiting Signature</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Concurrence</fullName>
                </value>
                <value>
                    <fullName>Directives Clearance</fullName>
                </value>
                <value>
                    <fullName>Directives Coordination</fullName>
                </value>
                <value>
                    <fullName>Drafting</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>External Review</fullName>
                </value>
                <value>
                    <fullName>Hold</fullName>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>Revise</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Division__c</fullName>
        <inlineHelpText>The sub-division of the Originating Service/Staff Office selected.</inlineHelpText>
        <label>Office / Portfolio</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Originating_Office__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>AC - Office of the GSA Chief of Staff</fullName>
                </value>
                <value>
                    <fullName>AD - Office of the Deputy Administrator</fullName>
                </value>
                <value>
                    <fullName>AKE – OCR External Programs Division</fullName>
                </value>
                <value>
                    <fullName>AKN – OCR EEO Program Division</fullName>
                </value>
                <value>
                    <fullName>AKR – OCR Regional Operations Division</fullName>
                </value>
                <value>
                    <fullName>BB - Office of Budget</fullName>
                </value>
                <value>
                    <fullName>BE - Office of Strategic Planning and Performance Management</fullName>
                </value>
                <value>
                    <fullName>BG - Office of Financial Management</fullName>
                </value>
                <value>
                    <fullName>BI - Office of Business and Financial Analytics</fullName>
                </value>
                <value>
                    <fullName>BR - Office of Regional Financial Services</fullName>
                </value>
                <value>
                    <fullName>B1 - Childcare Subsidy Administration Program</fullName>
                </value>
                <value>
                    <fullName>CA - OHRM Office of Account Management</fullName>
                </value>
                <value>
                    <fullName>CM - OHRM Office of Management &amp; Performance Improvement</fullName>
                </value>
                <value>
                    <fullName>CS - OHRM Office of HR Strategy &amp; Services</fullName>
                </value>
                <value>
                    <fullName>DA - OMA Northeast Regions Division</fullName>
                </value>
                <value>
                    <fullName>DB - OMA Southeast Regions Division</fullName>
                </value>
                <value>
                    <fullName>DC - OMA Midwest Regions Division</fullName>
                </value>
                <value>
                    <fullName>DD - OMA Policy &amp; Plans Division</fullName>
                </value>
                <value>
                    <fullName>DE - OMA Western Regions Division</fullName>
                </value>
                <value>
                    <fullName>DP - OMA Operations Division</fullName>
                </value>
                <value>
                    <fullName>DS - OMA GSA Security Division</fullName>
                </value>
                <value>
                    <fullName>GA - CBCA Staff Support Division</fullName>
                </value>
                <value>
                    <fullName>GJ - CBCA Judicial Division</fullName>
                </value>
                <value>
                    <fullName>H1A - Office of Internal Acquisition Division</fullName>
                </value>
                <value>
                    <fullName>H1B - Office of Workplace Management and Services Division</fullName>
                </value>
                <value>
                    <fullName>H1C - Charge Card Division</fullName>
                </value>
                <value>
                    <fullName>H1E - Executive Secretariat Division</fullName>
                </value>
                <value>
                    <fullName>H1F - FOIA &amp; Records Management Division</fullName>
                </value>
                <value>
                    <fullName>H1G - GAO/IG Audit Response Division</fullName>
                </value>
                <value>
                    <fullName>IA - OCIO Office of Governmentwide and Enterprise Solutions</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Controlled Document</label>
    <nameField>
        <displayFormat>CC{000000}</displayFormat>
        <label>Document ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Controlled Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Location_and_Stage_History__c.object
<CustomObject>
    <fields>
        <fullName>Controlled_Document__c</fullName>
        <label>Controlled Document</label>
        <referenceTo>Controlled_Document__c</referenceTo>
        <relationshipName>Office_Durations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Location and Stage History</label>
    <nameField>
        <label>Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Location and Stage Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/LocationAndStageHistoryHelper.cls
public class LocationAndStageHistoryHelper{

	// prevents adding a second location and stage history when the stage is changed to closed
	public static Map<Id, boolean> controlledDocumentIdRecursionTracker = new Map<Id, boolean>();
	public static BusinessHours cdtBusinessHours = [SELECT Id 
												FROM BusinessHours 
												WHERE Name = 'CDT Business Hours'];			

	// BEFORE INSERT ONLY
	// inserts start dates and also sets the Current Location
	public static void insertStartDatesAndSetCurrentLocation(List<Controlled_Document__c> newCDocs){
		Date currentLocalDate = System.now().date();
		
		for(Controlled_Document__c newControlledDocument : newCDocs){
			newControlledDocument.Current_Stage_Start_Date_New__c = currentLocalDate;
			newControlledDocument.Days_On_Current_Stage_New__c = 0;
			newControlledDocument.Current_Location_Start_Date_New__c = currentLocalDate;
			newControlledDocument.Days_In_Current_Location_New__c = 0;

			// if the current location IS empty and the originating office is NOT empty
			// check subdivision - if sub division is populated then use THAT
			// if not use the originating office
			if(newControlledDocument.Current_Location__c == null && newControlledDocument.Originating_Office__c != null){
				if(newControlledDocument.Sub_Division__c == null){
					newControlledDocument.Current_Location__c = newControlledDocument.Originating_Office__c;
				} else {
					newControlledDocument.Current_Location__c = newControlledDocument.Sub_Division__c;
				}
			} else if (newControlledDocument.Current_Location__c != null && newControlledDocument.Originating_Office__c == null){
				// do nothing
				// current location was set soooooo good to go!
			} else if (newControlledDocument.Current_Location__c != null && newControlledDocument.Originating_Office__c != null){
				// do nothing 
				// current location was set soooooo good to go!
			} else{
				newControlledDocument.Current_Location__c = 'Location Unspecified';
			}
		}
	}

	// AFTER INSERT ONLY
	public static void insertLocationHistoryForNewCDocs(List<Controlled_Document__c> newCDocs){
		Datetime current = System.now();
		Date currDate = current.date();
		Time currTime = current.time();
		Datetime currentLocal = Datetime.newInstance(currDate, currTime);

		List<Location_and_Stage_History__c> historiesToAdd = new List<Location_and_Stage_History__c>();
		for(Controlled_Document__c controlledDocument : newCDocs){
			if(controlledDocument.Current_Location__c == null) continue;
			// if a CD is inserted as closed then this happens
			if(controlledDocument.Stage__c == 'Closed') continue;
			Location_and_Stage_History__c newHistoryLocation = new Location_and_Stage_History__c();
			newHistoryLocation.Name = controlledDocument.Current_Location__c;
            // Case# 30668 - BEGIN
            String locationName = (controlledDocument.current_Region__c != null) ? mergeString(controlledDocument.current_Region__c, 
                                                                                             controlledDocument.Current_Location__c) : null;
            newHistoryLocation.Name = (locationName != null) ? locationName : controlledDocument.Current_Location__c;
            // Case# 30668 - END
			newHistoryLocation.Stage__c = controlledDocument.Stage__c;
			newHistoryLocation.Active__c = TRUE;
			newHistoryLocation.Start_Date__c = currentLocal;
			newHistoryLocation.of_Days_New__c = 0.0;
			newHistoryLocation.Controlled_Document__c = controlledDocument.Id;
			historiesToAdd.add(newHistoryLocation);
		}
		insert historiesToAdd;
	}

	// BEFORE UPDATE ONLY
	public static void checkAndUpdateHistory(Map<Id, Controlled_Document__c> newCDocs, Map<Id, Controlled_Document__c> oldCDocs){
		Datetime current = System.now();
		Date currDate = current.date();
		Time currTime = current.time();
		Time midnightTime = Time.newInstance(0, 0, 0, 0);
		Datetime currentLocal = Datetime.newInstance(currDate, currTime);
		Datetime currentLocalMidnight = Datetime.newInstance(currDate, midnightTime);
		Date currentLocalDate = currDate;

		System.debug('111');

		List<Controlled_Document__c> cDocsNeedingHistoryChanges = new List<Controlled_Document__c>();
		for(Controlled_Document__c newControlledDocument : newCDocs.values()){
			// prevents closed controlled documents from running twice
			if(controlledDocumentIdRecursionTracker.get(newControlledDocument.Id) == true) {
				// allows another attempt after an initial 'closed' status in case a document is ever updated to 'closed' then to a new status in the same transcation
				// this should never happen -_-
				controlledDocumentIdRecursionTracker.put(newControlledDocument.Id, false);
				continue;
			}

			System.debug('222');

			if(newControlledDocument.Stage__c == 'Closed'){
				newControlledDocument.Current_Location_Start_Date_New__c = null;
				newControlledDocument.Current_Stage_Start_Date_New__c = null;
				newControlledDocument.Days_In_Current_Location_New__c = null;
				newControlledDocument.Days_On_Current_Stage_New__c = null;
				cDocsNeedingHistoryChanges.add(newControlledDocument);
				continue;	
			}

			// this will help preventing nulls on existing controlled documents
			if(newControlledDocument.Current_Location_Start_Date_New__c == null) newControlledDocument.Current_Location_Start_Date_New__c = currentLocalDate;
			if(newControlledDocument.Current_Stage_Start_Date_New__c == null) newControlledDocument.Current_Stage_Start_Date_New__c = currentLocalDate;

			// used to prevent adding the same object to our list
			boolean added = false;
			if(newControlledDocument.Current_Location__c != oldCDocs.get(newControlledDocument.Id).Current_Location__c ||
              newControlledDocument.Current_Region__c != oldCDocs.get(newControlledDocument.Id).Current_Region__c){

				System.debug('333');

				cDocsNeedingHistoryChanges.add(newControlledDocument);
				newControlledDocument.Current_Location_Start_Date_New__c = currentLocalDate;
				newControlledDocument.Days_In_Current_Location_New__c = 0;
				added = true;
			}
			// adds a new record even if the location doesn't change
			if(newControlledDocument.Stage__c != oldCDocs.get(newControlledDocument.Id).Stage__c){

				System.debug('444');

				newControlledDocument.Current_Stage_Start_Date_New__c = currentLocalDate;
				newControlledDocument.Days_On_Current_Stage_New__c = 0;
				if(!added){
					cDocsNeedingHistoryChanges.add(newControlledDocument);
					added = true;
					if(newControlledDocument.Stage__c == 'Closed'){
						controlledDocumentIdRecursionTracker.put(newControlledDocument.Id, true);
					}
				}
			}

			// if these dates change then either an admin is doing something or we are testing
			boolean stageStartDateChanged = false;
			if(newControlledDocument.Current_Stage_Start_Date_New__c != oldCDocs.get(newControlledDocument.Id).Current_Stage_Start_Date_New__c){
				stageStartDateChanged = true;
			}

			// if these dates change then either an admin is doing something or we are testing
			boolean locationStartDateChanged = false;
			if(newControlledDocument.Current_Location_Start_Date_New__c != oldCDocs.get(newControlledDocument.Id).Current_Stage_Start_Date_New__c){
				locationStartDateChanged = true;
			}

			// changes controlled documents whenever the batch is run and not any other time
			if(UpdateDaysOpenOnApprovalStepsBatch.isBatchOn || stageStartDateChanged || locationStartDateChanged){
				newControlledDocument.Days_On_Current_Stage_New__c = getBsnsHoursDifferenceLong(cdtBusinessHours, newControlledDocument.Current_Stage_Start_Date_New__c, currentLocalDate);
				newControlledDocument.Days_In_Current_Location_New__c = getBsnsHoursDifferenceLong(cdtBusinessHours, newControlledDocument.Current_Location_Start_Date_New__c, currentLocalDate);
			}
		}

		List<Id> controlledDocumentIds = new List<Id>();
		List<Location_and_Stage_History__c> historiesToAdd = new List<Location_and_Stage_History__c>();
		for(Controlled_Document__c controlledDocument : cDocsNeedingHistoryChanges){

			System.debug('666');

			controlledDocumentIds.add(controlledDocument.Id);

			// if closed we are not adding a new Location and Stage History but updating the most recent one to inactive and setting the end date
			if(controlledDocument.Stage__c == 'Closed') continue;

			Location_and_Stage_History__c newHistoryLocation = new Location_and_Stage_History__c();
            newHistoryLocation.Name = controlledDocument.Current_Location__c;			
            // Case# 30668 - BEGIN
            String locationName = (controlledDocument.current_Region__c != null) ? mergeString(controlledDocument.current_Region__c, 
                                                                                             controlledDocument.Current_Location__c) : null;
            newHistoryLocation.Name = (locationName != null) ? locationName : controlledDocument.Current_Location__c;
            // Case# 30668 - END
			newHistoryLocation.Stage__c = controlledDocument.Stage__c;
			newHistoryLocation.Active__c = TRUE;
			newHistoryLocation.Start_Date__c = currentLocal;
			newHistoryLocation.Controlled_Document__c = controlledDocument.Id;
			newHistoryLocation.Of_Days_New__c = 0.0;
			historiesToAdd.add(newHistoryLocation);
		}

		List<Location_and_Stage_History__c> oldHistoryList = [SELECT Id, Active__c, Start_Date__c, End_Date__c, of_Days_New__c
													FROM Location_and_Stage_History__c
													WHERE Active__c = true AND
														Controlled_Document__c IN :controlledDocumentIds];							

		for(Location_and_Stage_History__c oldHistory : oldHistoryList){

			System.debug('777');

			oldHistory.Active__c = FALSE;
			oldHistory.End_Date__c = currentLocal;
			if(oldHistory.Start_Date__c != null) {

				System.debug('888');
				Double d = getBsnsHoursDifferenceDouble(cdtBusinessHours, oldHistory.Start_Date__c, oldHistory.End_Date__c);
				oldHistory.of_Days_New__c = d;
			}
		}

		update oldHistoryList;
		System.debug('oldHistoryList' + oldHistoryList);
		insert historiesToAdd;
		System.debug('historiesToAdd' + historiesToAdd);
	}

	private static Long getBsnsHoursDifferenceLong(BusinessHours bsnsHours, Datetime startTime, Datetime endTime){
		Long l = BusinessHours.diff(bsnsHours.Id, startTime, endTime);
		return l/1000/3600/8;
	}

	private static Double getBsnsHoursDifferenceDouble(BusinessHours bsnsHours, Datetime startTime, Datetime endTime){
		Double d = BusinessHours.diff(bsnsHours.Id, startTime, endTime);
		return d/1000/3600/8;
	}
	// Case# 30668 - BEGIN 
    private static String mergeString(String currentRegion, String currentLocation) {
        String merged = null;
        if(currentregion != null) {
            merged = currentRegion + ': ' + currentLocation;
            if(merged.length() > 80) {
                merged = merged.substring(0, 80);
            }
        }
        return merged;
    } // Case# 30668 - END
}