src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Affiliation_Copy__c</fullName>
        <description>Because Affiliation is a Long Text Area field, it cannot be used in the Batch Apex class.</description>
        <label>Affiliation Copy</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MAJOR_ORG__c</fullName>
        <label>Master ORG</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Person_Start_Date__c</fullName>
        <label>Person Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date_Email_Initiation__c</fullName>
        <description>This field is to store the person start date.</description>
        <label>Start Date Email Initiation</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>GSA</fullName>
        <active>true</active>
        <description>This contact record is used to track information for GSA employees.</description>
        <label>GSA</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OHRM__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Email_Sending_Day__c</fullName>
        <label>Email Sending Day</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Email_Template_Name__c</fullName>
        <label>Email Template Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>OHRM</label>
</CustomObject>

src/classes/OHRMEmailScheduler.cls
global with sharing class OHRMEmailScheduler implements Schedulable {
    global void execute(SchedulableContext SC) {
        map<decimal, string> mapCustEmailTemplate = new map<decimal, string>();
        for(OHRM__c ohrmCst : OHRM__c.getall().values()){
            mapCustEmailTemplate.put(Integer.valueOf(ohrmCst.Email_Sending_Day__c), ohrmCst.Email_Template_Name__c);
            system.debug('custom setting map'+mapCustEmailTemplate);
        }
        if(mapCustEmailTemplate != null && mapCustEmailTemplate.size() > 0){
            
            map<string, EmailTemplate> mapEmailTemplate = new map<string, EmailTemplate>();
            set<string> setEmailSubject = new set<string>{'Welcome Email Sent','Transit Subsidy Email Sent'};
            system.debug('mapcustomvalues'+mapCustEmailTemplate.values());
            
            for(EmailTemplate template : [Select Id, Subject, Name From EmailTemplate 
                Where Name IN: mapCustEmailTemplate.values()]){
                mapEmailTemplate.put(template.Name, template);
                setEmailSubject.add('Email: '+template.Subject);
                setEmailSubject.add(template.Subject);     
            }

            //List<string> taskSubs = new List<string>{'Welcome Email Sent','Transit Subsidy Email Sent'};
            //setEmailSubject.add{'Welcome Email Sent','Transit Subsidy Email Sent'};
            System.debug('setEmailSubject'+setEmailSubject);
            system.debug('email map'+mapEmailTemplate);
            Id devRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('GSA').getRecordTypeId();

            Date today = system.Today();
            /*string Query = 'Select Id, Email, isActive__c, Person_Start_Date__c, Start_Date_Email_Initiation__c, '+
                            ' (Select Subject From Tasks Where Subject IN : setEmailSubject) '+
                            ' From Contact Where isActive__c = true AND Email != null AND OHRM_Last_Email_Sent__c = false '+
                            ' AND MAJOR_ORG__c NOT IN (\'G\',\'J\') AND Person_Start_Date__c != null '+ 
                            ' AND RecordTypeId= \''+devRecordTypeId+'\' AND Affiliation_Copy__c=\'Government\' ' +
                            ' AND Start_Date_Email_Initiation__c != null AND Start_Date_Email_Initiation__c <= today  ';*/

           string Query = 'Select Id, Email, isActive__c, Person_Start_Date__c, Start_Date_Email_Initiation__c, '+
                            ' (Select Subject From Tasks Where Subject IN : setEmailSubject) '+
                            ' From Contact Where isActive__c = true AND Email != null  '+
                            ' AND MAJOR_ORG__c NOT IN (\'G\',\'J\') AND Person_Start_Date__c != null '+
                            ' AND RecordTypeId= \''+devRecordTypeId+'\' AND Affiliation_Copy__c!=\'Contractor\' ' +
                            ' AND Start_Date_Email_Initiation__c != null AND Start_Date_Email_Initiation__c <= today  ';
            OHRMEmailBatch objSched = new OHRMEmailBatch(Query,mapCustEmailTemplate,mapEmailTemplate,setEmailSubject);
            database.executebatch(objSched,200);
        }
    }
}