src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Supervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to the supervisor of this Contact.</description>
        <label>Supervisor</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>GSA</fullName>
        <active>true</active>
        <description>This contact record is used to track information for GSA employees.</description>
        <label>GSA</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TSS_Result_Action_Plan__c.object
<CustomObject>
    <description>This is created for TSS Application - Consolidated object for Building, Survey Results, Action Plan</description>
    <fields>
        <fullName>Building_Address__c</fullName>
        <label>Building Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Building_Name__c</fullName>
        <label>Building Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Office__c</fullName>
        <label>Field Office</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fiscal_Year__c</fullName>
        <label>Fiscal Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>FY14</fullName>
                </value>
                <value>
                    <fullName>FY15</fullName>
                </value>
                <value>
                    <fullName>FY16</fullName>
                </value>
                <value>
                    <fullName>FY17</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Location_Code_Plus__c</fullName>
        <label>Location Code Plus</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Occupancy__c</fullName>
        <label>Occupancy</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Property_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TSS_Result_Action_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property_Status__c</fullName>
        <label>Property Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Leased</fullName>
                </value>
                <value>
                    <fullName>Owned</fullName>
                </value>
                <value>
                    <fullName>Postal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Center__c</fullName>
        <label>Service Center</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supervisor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TSS_Result_Action_Plans1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TSS Result and Action Plan</label>
    <nameField>
        <label>TSS Result and Action Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TSS Results and Action Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TSS_Survey__c.object
<CustomObject>
    <description>This is created for TSS Application - Survey</description>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>TSS Surveys</relationshipLabel>
        <relationshipName>TSS_Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FY__c</fullName>
        <label>FY</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>FY14</fullName>
                </value>
                <value>
                    <fullName>FY15</fullName>
                </value>
                <value>
                    <fullName>FY16</fullName>
                </value>
                <value>
                    <fullName>FY17</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Location_Code_Plus__c</fullName>
        <formula>TSS_Result_Action_Plan__r.Location_Code_Plus__c</formula>
        <label>Location Code Plus</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ResponseId__c</fullName>
        <externalId>true</externalId>
        <label>ResponseId</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TSS_Result_Action_Plan__c</fullName>
        <label>TSS Result Action Plan</label>
        <referenceTo>TSS_Result_Action_Plan__c</referenceTo>
        <relationshipLabel>TSS Surveys</relationshipLabel>
        <relationshipName>TSS_Surveys</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>TSS Survey</label>
    <nameField>
        <label>TSS Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TSS Surveys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestTSSSurveyController.cls
/*-------------------------------------------------------------------------------------------------*
  Test class for TSSSurveyController - survey functionality
  TSS Action Planning application
 *-------------------------------------------------------------------------------------------------*
  Author           | Date        | Version | Description
 *-------------------------------------------------------------------------------------------------*
  Rajakumar          05/19/2015    1.1       Survey form - created.

 *-------------------------------------------------------------------------------------------------*

 *-------------------------------------------------------------------------------------------------*/
@isTest()
public class TestTSSSurveyController {
    // setup method for creating the respective records for the testing
    @testSetup public static void dataPrep() {
        RecordType rt = [SELECT Id,Name, DeveloperName
                         FROM RecordType
                         WHERE SobjectType='Account' AND DeveloperName='Account' LIMIT 1];
        RecordType contRT = [SELECT Id, Name, DeveloperName, SObjectType
                             FROM RecordType
                             WHERE SObjectType='Contact' AND DeveloperName ='GSA' LIMIT 1];
        Account acct = new Account();
        acct.Name='GSA';
        acct.RecordTypeId = rt.Id;
        // insert account
        insert acct;
        Contact cont = new Contact();
        cont.LastName = 'Kumar';
        cont.FirstName = 'Raj';
        cont.Email='rajakumar.pallepati@gsa.gov';
        cont.RecordTypeId = contRT.Id;
        // insert contact
        insert cont;
        List<TSS_Result_Action_Plan__c> acplist = new List<TSS_Result_Action_Plan__c>();

        List<User> admusers = [SELECT Id FROM User WHERE IsActive = true AND ProfileId IN
                            (SELECT Id FROM Profile WHERE Name = 'GSA System Administrator') LIMIT 2];
        Set<Id> recIds = new Set<Id>();
        for(Integer i=0;i<1;i++) {
            String acpname = 'ACPTRGI' + String.valueOf(i);
            acplist.add(new TSS_Result_Action_Plan__c(Name=acpname,
                        Building_Address__c='ABC',
                        Building_Name__c='ABC',
                        City__c='FAIRFAX',
                        Field_Office__c='CO',
                        Fiscal_Year__c='FY16',
                        Location_Code_Plus__c=acpname,
                        Occupancy__c=2000,
                        Property_Manager__c=admusers[0].Id,
                        Property_Status__c='Leased',
                        Region__c='CO',
                        Service_Center__c='CO',
                        State__c='VA',
                        Supervisor__c=admusers[0].Id));
            acplist.add(new TSS_Result_Action_Plan__c(Name=acpname+'1',
                        Building_Address__c='VIRTUAL 16',
                        Building_Name__c='VIRTUAL 16',
                        City__c='WASHINGTON',
                        Field_Office__c='CO',
                        Fiscal_Year__c='FY16',
                        Location_Code_Plus__c='VIRTUAL16',
                        Occupancy__c=2000,
                        Property_Manager__c=admusers[0].Id,
                        Property_Status__c='Leased',
                        Region__c='CO',
                        Service_Center__c='CO',
                        State__c='DC',
                        Supervisor__c=admusers[0].Id));
            //added new data to accomodate building not Listed 
            acplist.add(new TSS_Result_Action_Plan__c(Name=acpname+'1',
                        Building_Address__c='Not Listed',
                        Building_Name__c='Not Listed',
                        City__c='WASHINGTON',
                        Field_Office__c='CO',
                        Fiscal_Year__c='FY16',
                        Location_Code_Plus__c='BuildingNotListed16',
                        Occupancy__c=2000,
                        Property_Manager__c=admusers[0].Id,
                        Property_Status__c='Leased',
                        Region__c='CO',
                        Service_Center__c='CO',
                        State__c='DC',
                        Supervisor__c=admusers[0].Id));
        }
        // insert buildings
        insert acplist;
        List<TSS_Survey__c> surveylist = new List<TSS_Survey__c>();
        for(Integer i=0; i<1; i++) {
            String sname = 'Survey' + String.valueOf(i);
            surveylist.add(new TSS_Survey__c(Name=sname,
                     TSS_Result_Action_Plan__c=acplist[0].Id,FY__c='FY16',
                     Contact__c=cont.Id,
                     ResponseId__c=sname));
        }
        // insert surveys
        insert surveylist;

        System.assertEquals(true,true);
    }

    // method to validate the page behaviour when there is no parent record id passed to the page
    @isTest public static void testNegative() {
        PageReference pageRef = Page.TSSSurveyWizard1;
        Test.setCurrentPage(pageRef);
        // Add parameters to page URL
        ApexPages.currentPage().getParameters().put('id', null);
        TSSSurveyController controller = new TSSSurveyController();
        System.assertEquals(false, controller.contactfound);
    }

    // method to validate the page behavior when there is a valid parent record id (existing with comments) passed to the page
    
    @isTest public static void testPostive() {
        PageReference pageRef = Page.TSSSurveyWizard1;
        Test.setCurrentPage(pageRef);
        List<TSS_Result_Action_Plan__c> ext = [SELECT Id, Name FROM TSS_Result_Action_Plan__c
                                               WHERE Location_Code_Plus__c != 'VIRTUAL16' LIMIT 1];
        List<Contact> contact = [SELECT Id, Email FROM Contact];
        // Add parameters to page URL
        ApexPages.currentPage().getParameters().put('id', contact[0].Id);
        ApexPages.currentPage().getHeaders().put('User-Agent','Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36');
        TSSSurveyController controller = new TSSSurveyController();

        List<SelectOption> agencies = controller.getAgencies();
        for(SelectOption s: agencies){
            controller.agency = s.getValue();
            List<SelectOption> bureaus2 = controller.getBureaus();
        }
        List<SelectOption> bureaus = controller.getBureaus();
        List<SelectOption> states = controller.getStates();
        controller.agency = 'DEPARTMENT OF EDUCATION';
        controller.bureau = 'DEPARTMENT OF EDUCATION';
        controller.state = 'VA';
        List<SelectOption> cities = controller.cities;
        controller.city = 'FAIRFAX';
        List<SelectOption> buildings = controller.buildings;
        controller.building = ext[0].Id;
        controller.contact = contact[0].Id;
        controller.telework = 'No';
        String nextbutton = controller.next().getURL();
        System.assertEquals('/apex/tsssurveywizard2',nextbutton);
        String prevbutton = controller.previous().getURL();
        System.assertEquals('/apex/tsssurveywizard1',prevbutton);
        controller.cleancat1 = '1';
        controller.cleancat2 = '2';
        controller.cleancat3 = '3';
        controller.cleancat4 = '4';
        controller.workcat1 = '1';
        controller.workcat2 = '2';
        controller.workcat3 = '3';
        controller.workcat4 = '4';
        controller.condcat1 = '1';
        controller.condcat2 = '2';
        controller.condcat3 = '3';
        controller.condcat4 = '4';
        controller.elevator = '1';
        controller.comments = 'COMMENT ADDED';
        controller.meetspace = '2';
        controller.overallsat = '4';
        controller.bldgmgmt1 = '1';
        controller.bldgmgmt2 = '1';
        controller.security = '1';
        controller.securityPersonnel ='1';
        controller.wkspacetype = 'Other';
        String nextpage = controller.save().getUrl();
        System.assertEquals('/apex/tsssurveythankyou', nextPage);
        String bldgId = ext[0].Id;
        String contId = contact[0].Id;
        List<TSS_Survey__c> surveys = [SELECT Id, Name, Contact__c, TSS_Result_Action_Plan__c
                                FROM TSS_Survey__c
                                WHERE TSS_Result_Action_Plan__c = :bldgId
                                AND Contact__c = :contId];
        System.assertEquals(2, surveys.size());//modified the assert statement
    }

    // method to validate the page behavior when there is a valid parent record id passed to the page (virtual=yes)
    @isTest public static void testVirtualPostive() {
        PageReference pageRef = Page.TSSSurveyWizard1;
        Test.setCurrentPage(pageRef);
        List<TSS_Result_Action_Plan__c> extvirtbuilding = [SELECT Id, Name FROM TSS_Result_Action_Plan__c
                                               WHERE Location_Code_Plus__c = 'VIRTUAL16' LIMIT 1];
        List<Contact> contact = [SELECT Id, Email FROM Contact];
        // Add parameters to page URL
        ApexPages.currentPage().getParameters().put('id', contact[0].Id);
        TSSSurveyController controller = new TSSSurveyController();
        controller.building = extvirtbuilding[0].Id;
        controller.contact = contact[0].Id;
        controller.telework = 'Yes';
        String nextpage = controller.save().getUrl();
        System.assertEquals('/apex/tsssurveythankyou', nextPage);
        String bldgId = extvirtbuilding[0].Id;
        String contId = contact[0].Id;
        List<TSS_Survey__c> surveys = [SELECT Id, Name, Contact__c, TSS_Result_Action_Plan__c
                                FROM TSS_Survey__c
                                WHERE TSS_Result_Action_Plan__c = :bldgId
                                AND Contact__c = :contId];
        System.assertEquals(1, surveys.size());
    }
}