src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>GSA</fullName>
        <active>true</active>
        <description>This contact record is used to track information for GSA employees.</description>
        <label>GSA</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CTI_Cases__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Case_Record_Type_ID__c</fullName>
        <label>Case Record Type ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DNIS__c</fullName>
        <label>DNIS</label>
        <precision>6</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>CTI_Cases</label>
</CustomObject>

src/objects/Exception__c.object
<CustomObject>
    <description>This object is leveraged to store all the exceptions that are generated in the code and needs to be notified to the support group</description>
    <fields>
        <fullName>Email_Exception__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Email Exception</label>
        <type>Checkbox</type>
    </fields>
    <label>Exception</label>
    <nameField>
        <label>Exception Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/KBSyncSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>API_Key__c</fullName>
        <label>API Key</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Create_Exception_Record__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Create Exception Record</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_Delta__c</fullName>
        <label>Date Shift</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Email_Exception__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Email Exception</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Page_Size__c</fullName>
        <label>Page Size</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>KBSyncSettings</label>
</CustomObject>

src/objects/TriggerControls__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>On__c</fullName>
        <defaultValue>true</defaultValue>
        <label>On</label>
        <type>Checkbox</type>
    </fields>
    <label>TriggerControls</label>
</CustomObject>

src/classes/GSA_FCIC_CTI_Case_Creation_Test.cls
@isTest
public class GSA_FCIC_CTI_Case_Creation_Test{

       static testMethod void GSAFCICCTICaseCreationTest(){
       
        integer dnis =null;
        TriggerControls__c triCon2 = new TriggerControls__c(Name = 'Case', On__c = true); insert triCon2;
        TriggerControls__c triCon3 = new TriggerControls__c(Name = 'Contact', On__c = true); insert triCon3;
         KBSyncSettings__c kbSync = new KBSyncSettings__c(Name='SyncSettings', API_Key__c= '1234',Create_Exception_Record__c= true,  Date_Delta__c = 3,Email_Exception__c = true,Page_Size__c=3); insert kbSync ;
        Exception__c exc = new Exception__c(Name = 'CTI Exception'); insert exc;
        Id recTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('GSA.gov').getRecordTypeId();
        CTI_Cases__c cti = new CTI_Cases__c(Name = '14698',DNIS__c =14698, Case_Record_Type_ID__c = recTypeId ); insert cti;
        ApexPages.currentPage().getParameters().put('dnis','');
        GSA_FCIC_CTI_Case_Creation ctiCaseCreation = new GSA_FCIC_CTI_Case_Creation();
        ctiCaseCreation.displayCase(); 
        System.AssertEquals(null,dnis); 
         
        
      }
      
      
       static testMethod void CTICaseCreationTest1(){
       
        integer dnis = 14698;
        TriggerControls__c triCon2 = new TriggerControls__c(Name = 'Case', On__c = true); insert triCon2;
        TriggerControls__c triCon3 = new TriggerControls__c(Name = 'Contact', On__c = true); insert triCon3;
         KBSyncSettings__c kbSync = new KBSyncSettings__c(Name='SyncSettings', API_Key__c= '1234',Create_Exception_Record__c= true,  Date_Delta__c = 3,Email_Exception__c = true,Page_Size__c=3); insert kbSync ;
        Exception__c exc = new Exception__c(Name = 'CTI Exception'); insert exc;
        Id recTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('GSA.gov').getRecordTypeId();
        CTI_Cases__c cti = new CTI_Cases__c(Name = '14698',DNIS__c =14698, Case_Record_Type_ID__c = recTypeId ); insert cti;
        ApexPages.currentPage().getParameters().put('dnis','14698'); 
        GSA_FCIC_CTI_Case_Creation ctiCaseCreation = new GSA_FCIC_CTI_Case_Creation();
        ctiCaseCreation.displayCase();
         System.Assert(14698==dnis); 
         
        
      }
}