src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Affiliation__c</fullName>
        <label>Affiliation</label>
        <length>350</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CHRIS_ID__c</fullName>
        <label>CHRIS ID</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Federated_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Federated ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Contact_ID__c</fullName>
        <description>Contact ID from Oracle</description>
        <externalId>true</externalId>
        <label>Contact ID</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>GOVTPOC_COTAR__c</fullName>
        <label>COTR for Contractors</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MAJOR_ORG_DESCRIPTION__c</fullName>
        <label>Master ORG Description</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MAJOR_ORG__c</fullName>
        <label>Master ORG</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nickname__c</fullName>
        <label>Nickname</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supervisory_Status__c</fullName>
        <description>Populated based on same field on corresponding User record by Federation Identifier.</description>
        <label>Supervisory Status</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UPN__c</fullName>
        <label>UPN</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WORK_BUILDING_PRIMARY__c</fullName>
        <label>Work Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>GSA</fullName>
        <active>true</active>
        <description>This contact record is used to track information for GSA employees.</description>
        <label>GSA</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Survey2__c.object
<CustomObject>
    <label>Survey Master</label>
    <nameField>
        <label>Survey Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Masters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/SurveyFeedback__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Survey Feedbacks</relationshipLabel>
        <relationshipName>Survey_Feedbacks</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Survey2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Survey Master</label>
        <referenceTo>Survey2__c</referenceTo>
        <relationshipLabel>Survey Feedbacks</relationshipLabel>
        <relationshipName>Survey_Feedbacks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Survey Feedback</label>
    <nameField>
        <displayFormat>SF-{000000}</displayFormat>
        <label>Survey Feedback Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Feedbacks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/SurveyIndividualAnswer__c.object
<CustomObject>
    <fields>
        <fullName>Question_Number__c</fullName>
        <label>Question Number</label>
        <length>4</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey2__c</fullName>
        <formula>Survey_Feedback__r.Survey2__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Survey Master</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SurveyIndividualQuestion__c</fullName>
        <label>Survey Individual Question</label>
        <referenceTo>SurveyIndividualQuestion__c</referenceTo>
        <relationshipLabel>Survey Individual Answers</relationshipLabel>
        <relationshipName>Survey_Individual_Answers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Survey_Feedback__c</fullName>
        <label>Survey Feedback</label>
        <referenceTo>SurveyFeedback__c</referenceTo>
        <relationshipLabel>Survey Individual Answers</relationshipLabel>
        <relationshipName>Survey_Individual_Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Survey Individual Answer</label>
    <nameField>
        <displayFormat>SIA-{0000}</displayFormat>
        <label>Survey Individual Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Individual Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SurveyIndividualQuestion__c.object
<CustomObject>
    <fields>
        <fullName>Survey2__c</fullName>
        <label>Survey Master</label>
        <referenceTo>Survey2__c</referenceTo>
        <relationshipLabel>Survey Individual Questions</relationshipLabel>
        <relationshipName>Survey_Individual_Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Survey Individual Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Individual Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestUtil.cls
/**
 * TestUtil.cls
 * @author Justin Lyon
 * @date 6/29/2015
 *
 * Standardize record creation for Test Data.
 */
public with sharing class TestUtil {

	public static Account buildAccount(String name, Id rtId) {
		return new Account(
			Name = name,
			RecordTypeId = rtId);
	}

	public static User buildUser(Integer i, Id profileId, String email) {
		String fName = 'fN' + i;
		String lName = 'lN' + i;
		return new User(
			FirstName = fName,
			LastName = lName,
			Email = email,
			ProfileId = profileId,
			UserName = email.subStringBefore('@') + '@gsa.testUser',
			Alias = fName + 'al',
			CommunityNickname = email.subStringBefore('@'),
			FederationIdentifier = 'testFedID' + i,
			Affiliation__c = String.valueOf(i),
			EmailEncodingKey = 'UTF-8',
			LanguageLocaleKey = 'en_US',
			LocaleSidKey = 'en_US',
			TimeZoneSidKey = 'America/New_York',
			CHRIS_ID__c = '1' + i,
			Contact_ID__c = i,
			GOVTPOC_COTAR__c = String.valueOf(i),
			MAJOR_ORG__c = String.valueOf(i),
			MAJOR_ORG_DESCRIPTION__c = String.valueOf(i),
			Middle_Name__c = String.valueOf(i),
			Nickname__c = String.valueOf(i),
			User_Organization_Name__c = String.valueOf(i),
			User_Region__c = String.valueOf(i),
			UPN__c = String.valueOf(i),
			WORK_BUILDING_PRIMARY__c = String.valueOf(i),
			Supervisory_Status__c = i,
			Supervisory_Status_Description__c = String.valueOf(i)
		);
	}

	public static Contact buildContactByUser(User u, Id rtId, Id accId) {
		return new Contact(
			FirstName = u.FirstName,
			LastName = u.LastName,
			Email = u.Email,
			Contact_Federated_ID__c = u.FederationIdentifier,
			RecordTypeId = rtId,
			AccountId = accId);
	}

	public static Survey2__c buildSurveyMaster(String name) {
		return new Survey2__c(
			Name = name);
	}

	public static SurveyFeedback__c buildSurveyFeedback(Id contactId, Id surveyId) {
		return new SurveyFeedback__c(
			Contact__c = contactId,
			Survey2__c = surveyId);
	}

	public static SurveyIndividualAnswer__c buildSurveyAnswer(Id feedbackId, String questionName) {
		return new SurveyIndividualAnswer__c(
			Survey_Feedback__c = feedbackId,
			Question_Number__c = questionName);
	}

	public static SurveyIndividualQuestion__c buildSurveyQuestion(String name, Id surveyId) {
		return new SurveyIndividualQuestion__c(
			Name = name,
			Survey2__c = surveyId);
	}
}