src/objects/Controlled_Document__c.object
<CustomObject>
    <label>Controlled Document</label>
    <nameField>
        <displayFormat>CC{000000}</displayFormat>
        <label>Document ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Controlled Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Controlled_Document_Feed__c.object
<CustomObject>
    <description>This Object is being used by the Controlled Document Tracker application.</description>
    <fields>
        <fullName>Controlled_Document__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Controlled Document</label>
        <referenceTo>Controlled_Document__c</referenceTo>
        <relationshipName>Controlled_Document_Feed</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.UserType</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Controlled_Document_Feed</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Grant Update Access Request</label>
    <nameField>
        <displayFormat>GUA-{0000000}</displayFormat>
        <label>Grant Update Access Requests</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grant Update Access Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GrantAccessToChatterFiles.cls
global without sharing class GrantAccessToChatterFiles {
	
	webservice static void grantAccessToCDChatterFiles(Id cdid){
		system.debug('===========>>>>>>> cdid ::: '+cdid);
		
		List<Controlled_Document_Feed__c> cdocList = [SELECT Id, Controlled_Document__c, User__c, Status__c
												FROM Controlled_Document_Feed__c 
												WHERE Controlled_Document__c = :cdid
												  AND User__c = :UserInfo.getUserId() 
												  AND Status__c = :'Pending' LIMIT 1];
		
		if(cdocList.isEmpty())	{
			Controlled_Document_Feed__c cdf = new Controlled_Document_Feed__c();
			cdf.Status__c = 'Pending';
			cdf.Controlled_Document__c = cdid;
			cdf.User__c = UserInfo.getUserId();
			insert cdf;
		}	
	}	
	
}