src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Federated_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Federated ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>NewHireEmailTextStatuses__c</fullName>
        <description>Track Survey Email Status Processes by text values. Should be hidden, possibly read only.
Expected values are: 
NH_30 Day Sent;
NH_30 Day Responded;
NH_90 Day Sent;
NH_90 Day Responded;
NH_180 Day Sent;
NH_180 Day Responded;
NH_1 Year Sent;
NH_1 Year Responded;
NH_1.5 Years Sent;
NH_1.5 Years Responded;</description>
        <label>New Hire Email Text Statuses</label>
        <length>350</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Person_Start_Date__c</fullName>
        <label>Person Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Supervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to the supervisor of this Contact.</description>
        <label>Supervisor</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supervisory_Status__c</fullName>
        <description>Populated based on same field on corresponding User record by Federation Identifier.</description>
        <label>Supervisory Status</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>GSA</fullName>
        <active>true</active>
        <description>This contact record is used to track information for GSA employees.</description>
        <label>GSA</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/EmailTracker__c.object
<CustomObject>
    <description>Object to store the email reminders for the Contact Manager VOE OHRM Surveys i.e. Hiring manager, Supervisor, etc</description>
    <fields>
        <fullName>Purpose__c</fullName>
        <label>Purpose</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Initial Send</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Reminder</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SurveyURL__c</fullName>
        <label>Survey URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>ToContact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Contact Recipient</description>
        <label>To Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Email Trackers</relationshipLabel>
        <relationshipName>Email_Trackers</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Email Tracker</label>
    <nameField>
        <displayFormat>ET-{00000000}</displayFormat>
        <label>Email Tracking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Trackers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestContactHelper.cls
/*-------------------------------------------------------------------------------------------------*
  Test class for ContactHelper - VOE OHRM surveys functionality
  Contact Manager - VOE OHRM Surveys
 *-------------------------------------------------------------------------------------------------*
  Author           | Date        | Version | Description
 *-------------------------------------------------------------------------------------------------*
  Rajakumar          08/17/2015    1.1     created.
  GaneshKumar Mandava    08/24/2017        Modified the test class as per best practices
 *-------------------------------------------------------------------------------------------------* 
 *-------------------------------------------------------------------------------------------------*/
@isTest(seealldata=false)
private class TestContactHelper {
    // setup method for creating the respective records for the testing
    @testSetup 
    static void testdata() {
    
        Id accRecTypId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Account').getRecordTypeId();
        Id conRecTypId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('GSA').getRecordTypeId();
        Id profId = [SELECT Id FROM Profile WHERE Name = 'GSA System Administrator'].Id;
        PublicUserGroupHandler.disableGroupMemberRecalculation = true;
        List<User> collUsers = new List<User>();
        collUsers.add(testutil.buildUser(1,profId,'testuser1@test.com'));
        collUsers.add(testutil.buildUser(2,profId,'testuser2@test.com'));
        insert collUsers;
        
        User employee = [SELECT Id, firstname,lastname,Email, FederationIdentifier FROM User 
                            WHERE email ='testuser1@test.com' LIMIT 1];
        User supervisor = [SELECT Id,firstname,lastname, Email, FederationIdentifier FROM User 
                            WHERE email = 'testuser2@test.com' LIMIT 1];
                            
        Account acct = TestUtil.buildAccount('GSA', accRecTypId);
        insert acct;
        system.assertnotEquals(null, acct.id);

        // insert contact for supervisor
        Contact cont2 = new Contact();
        cont2.LastName = 'KumarSupervisor1';
        cont2.FirstName = 'Raj1';
        cont2.Email='testsupervisor1@gsa.gov';
        cont2.RecordTypeId = conRecTypId;
        cont2.Person_Start_Date__c = Date.today()-1;
        cont2.Contact_Federated_ID__c = supervisor.FederationIdentifier;
        cont2.AccountId = acct.id;
        insert cont2;
        
        // insert contact for employee
        Contact cont = new Contact();
        cont.LastName = 'Kumar2';
        cont.FirstName = 'Raj2';
        cont.Email='testemployee1@gsa.gov';
        cont.RecordTypeId = conRecTypId;
        cont.Person_Start_Date__c = Date.today();
        cont.Contact_Federated_ID__c = employee.FederationIdentifier;
        cont.Supervisor__c=cont2.Id;  
        cont.AccountId = acct.Id; 
        cont.Supervisory_Status__c = 2;
        insert cont; 
        
        List<Contact> contacts = new List<Contact>();
        // for bulk testing
        List<User> sfdcUsers = [SELECT Id, Email, FederationIdentifier FROM User 
                            WHERE Id != :UserInfo.getUserId() 
                            AND ProfileId IN (SELECT Id FROM Profile WHERE Name='GSA Standard Salesforce User') 
                            AND IsActive = true LIMIT 200];
        for(Integer i=0;i<200;i++) {
            contacts.add(new Contact(LastName='TestRKP'+i, FirstName='TestKP'+i, RecordTypeId=conRecTypId, 
                            Contact_Federated_ID__c = sfdcUsers[i].FederationIdentifier, Supervisor__c=cont2.Id,
                            Email='rajkpOHRMbulktest'+i+'@gsa.gov', AccountId= acct.Id)); 
        }
        insert contacts;
        
    }
    
  
    // method to validate the trigger email tracker entries for non-30 Day NH Survey - text status value
    static testmethod void testContactSurveyStatusNoChange() {
        List<Contact> contacts = new List<Contact>();
        contacts = [SELECT Id, NewHireEmailTextStatuses__c FROM Contact WHERE Email ='testemployee1@gsa.gov']; 
        test.startTest();
        for(Contact c: contacts) {
            c.NewHireEmailTextStatuses__c = 'NH_30 Day Sent';
            c.Supervisory_Status__c = 2;
        }
        update contacts;
        for(Contact c: contacts) {
            c.NewHireEmailTextStatuses__c = 'NH_30 Day Sent;NH_60 Day Sent';
        }
        update contacts;
        List<Contact> supercontacts = new List<Contact>();
        supercontacts = [SELECT Id FROM Contact WHERE Email='testsupervisor1@gsa.gov'];
        // asserting
        List<EmailTracker__c> etExtract = new List<EmailTracker__c>();
        etExtract = [SELECT Id FROM EmailTracker__c WHERE Purpose__c='Initial Send' 
                        /*AND SurveyURL__c!= null */ AND ToContact__c=:supercontacts[0].Id];
        test.stoptest();
        System.assertEquals(1, etExtract.size());
    }
    
   // method to validate the bulk records for 30 Day NH Survey
    static testmethod void testBulkContactSurveyStatusChange() {
        List<Contact> contacts = new List<Contact>();
        contacts = [SELECT Id, NewHireEmailTextStatuses__c FROM Contact WHERE Email LIKE 'rajkpOHRMbulktest%']; 
        test.startTest();
        for(Contact c: contacts) {
            c.NewHireEmailTextStatuses__c = 'NH_30 Day Sent';
        }
        update contacts;
        List<Contact> supercontacts = new List<Contact>();
        supercontacts = [SELECT Id FROM Contact WHERE Email='testsupervisor1@gsa.gov'];
        // asserting
        List<EmailTracker__c> etExtract = new List<EmailTracker__c>();
        etExtract = [SELECT Id FROM EmailTracker__c WHERE Purpose__c='Initial Send' 
                       /* AND SurveyURL__c!= null */  AND ToContact__c=:supercontacts[0].Id];
        test.stopTest();
        System.assertEquals(200, etExtract.size());
    } 
}