src/objects/Critical_Issues__c.object
<CustomObject>
    <description>This is the object for Critical Items application to track the weekly critical items for the administrative office.</description>
    <fields>
        <fullName>Action_Required_by_Administrator__c</fullName>
        <description>In this section, the region/staff office/service needs determine what if any action is need by the Administrator.</description>
        <inlineHelpText>In this section, the region/staff office/service needs determine what if any action is need by the Administrator.</inlineHelpText>
        <label>Action Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ready For Signature/Approval</fullName>
                </value>
                <value>
                    <fullName>Action/Decision Required</fullName>
                </value>
                <value>
                    <fullName>Feedback Required</fullName>
                </value>
                <value>
                    <fullName>Info Only/May Require Action</fullName>
                </value>
                <value>
                    <fullName>Info Only/No Action Needed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Action_Type_Detail__c</fullName>
        <label>Action Type Detail</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>18F/PIF/X.Gov</fullName>
                </value>
                <value>
                    <fullName>Budget</fullName>
                </value>
                <value>
                    <fullName>Congressional</fullName>
                </value>
                <value>
                    <fullName>Consolidation/Realignment</fullName>
                </value>
                <value>
                    <fullName>Contracts/Acquisition</fullName>
                </value>
                <value>
                    <fullName>Events</fullName>
                </value>
                <value>
                    <fullName>External Correspondence/Report</fullName>
                </value>
                <value>
                    <fullName>FOIA</fullName>
                </value>
                <value>
                    <fullName>GAO/IG Audit</fullName>
                </value>
                <value>
                    <fullName>Hearing</fullName>
                </value>
                <value>
                    <fullName>Integrated Customer Service</fullName>
                </value>
                <value>
                    <fullName>Internal Correspondence/Report</fullName>
                </value>
                <value>
                    <fullName>Key Properties</fullName>
                </value>
                <value>
                    <fullName>News Story/Press Inquiry</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Personnel/HR</fullName>
                </value>
                <value>
                    <fullName>PMA</fullName>
                </value>
                <value>
                    <fullName>Prospectus/Capital Project</fullName>
                </value>
                <value>
                    <fullName>Protests</fullName>
                </value>
                <value>
                    <fullName>Savings Opportunity</fullName>
                </value>
                <value>
                    <fullName>Shared Service</fullName>
                </value>
                <value>
                    <fullName>System/Technology</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Additional_Comments2__c</fullName>
        <label>Background/History</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Critical_Item_Status__c</fullName>
        <description>In this section, identify if this is a new item for this week, a recurring item that continues to require the Acting Administrator&apos;s attention, or a recurring item that has updates for the Acting Administrator.</description>
        <inlineHelpText>Current status of the critical issue.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Updated</fullName>
                </value>
                <value>
                    <fullName>Follow-up</fullName>
                </value>
                <value>
                    <fullName>Monitor</fullName>
                </value>
                <value>
                    <fullName>Delegate Reviewed</fullName>
                </value>
                <value>
                    <fullName>RC Reviewed</fullName>
                </value>
                <value>
                    <fullName>Business Line Reviewed</fullName>
                </value>
                <value>
                    <fullName>RA Reviewed</fullName>
                </value>
                <value>
                    <fullName>Commissioner Reviewed</fullName>
                </value>
                <value>
                    <fullName>Commissioner Approved</fullName>
                </value>
                <value>
                    <fullName>Staff Office Reviewed</fullName>
                </value>
                <value>
                    <fullName>Front Office Reviewed</fullName>
                </value>
                <value>
                    <fullName>Chief of Staff Reviewed</fullName>
                </value>
                <value>
                    <fullName>Deputy Administrator Reviewed</fullName>
                </value>
                <value>
                    <fullName>Administrator Reviewed</fullName>
                </value>
                <value>
                    <fullName>Administrator Approved</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date_Updated__c</fullName>
        <label>Date Updated</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deadline__c</fullName>
        <description>If this section, please provide a deadline (MM/DD/YYYY) for when you would like a response from the Administrator (if any).</description>
        <inlineHelpText>If this section, please provide a deadline (MM/DD/YYYY) for when you would like a response from the Administrator (if any).</inlineHelpText>
        <label>Action Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IQ_Number__c</fullName>
        <description>Required if &quot;Signature Required&quot; is selected in Action Type field</description>
        <label>IQ Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <description>Name of the Organization or Region submitting this request</description>
        <inlineHelpText>Name of the Organization or Region submitting this request</inlineHelpText>
        <label>Submitting Org</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Administrative Office</fullName>
                </value>
                <value>
                    <fullName>Audit Group</fullName>
                </value>
                <value>
                    <fullName>CFO</fullName>
                </value>
                <value>
                    <fullName>CIO</fullName>
                </value>
                <value>
                    <fullName>Exec Sec</fullName>
                </value>
                <value>
                    <fullName>FAS</fullName>
                </value>
                <value>
                    <fullName>OAS</fullName>
                </value>
                <value>
                    <fullName>OCIA</fullName>
                </value>
                <value>
                    <fullName>OCM</fullName>
                </value>
                <value>
                    <fullName>OCR</fullName>
                </value>
                <value>
                    <fullName>OCSIT</fullName>
                </value>
                <value>
                    <fullName>OGC</fullName>
                </value>
                <value>
                    <fullName>OGP</fullName>
                </value>
                <value>
                    <fullName>OHRM</fullName>
                </value>
                <value>
                    <fullName>OMA</fullName>
                </value>
                <value>
                    <fullName>OSBU</fullName>
                </value>
                <value>
                    <fullName>PBS</fullName>
                </value>
                <value>
                    <fullName>TTS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Recommended_Action__c</fullName>
        <description>When an action is required by the Administrator, provide proposed next steps and timeline. Otherwise, provide your next steps (if any) to address this item.</description>
        <inlineHelpText>When an action is required by the Administrator, provide proposed next steps and timeline. Otherwise, provide your next steps (if any) to address this item.</inlineHelpText>
        <label>Recommended Action</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Related_Organization__c</fullName>
        <label>Other Affected Org(s)/Region(s)</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Organization__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Administrative Office</fullName>
                </value>
                <value>
                    <fullName>Audit Group</fullName>
                </value>
                <value>
                    <fullName>CFO</fullName>
                </value>
                <value>
                    <fullName>CIO</fullName>
                </value>
                <value>
                    <fullName>Exec Sec</fullName>
                </value>
                <value>
                    <fullName>FAS</fullName>
                </value>
                <value>
                    <fullName>OAS</fullName>
                </value>
                <value>
                    <fullName>OCIA</fullName>
                </value>
                <value>
                    <fullName>OCM</fullName>
                </value>
                <value>
                    <fullName>OCR</fullName>
                </value>
                <value>
                    <fullName>OCSIT</fullName>
                </value>
                <value>
                    <fullName>OGC</fullName>
                </value>
                <value>
                    <fullName>OGP</fullName>
                </value>
                <value>
                    <fullName>OHRM</fullName>
                </value>
                <value>
                    <fullName>OMA</fullName>
                </value>
                <value>
                    <fullName>OSBU</fullName>
                </value>
                <value>
                    <fullName>PBS</fullName>
                </value>
                <value>
                    <fullName>Region 1</fullName>
                </value>
                <value>
                    <fullName>Region 2</fullName>
                </value>
                <value>
                    <fullName>Region 3</fullName>
                </value>
                <value>
                    <fullName>Region 4</fullName>
                </value>
                <value>
                    <fullName>Region 5</fullName>
                </value>
                <value>
                    <fullName>Region 6</fullName>
                </value>
                <value>
                    <fullName>Region 7</fullName>
                </value>
                <value>
                    <fullName>Region 8</fullName>
                </value>
                <value>
                    <fullName>Region 9</fullName>
                </value>
                <value>
                    <fullName>Region 10</fullName>
                </value>
                <value>
                    <fullName>NCR</fullName>
                </value>
                <value>
                    <fullName>Central Office</fullName>
                </value>
                <value>
                    <fullName>TTS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status_Update__c</fullName>
        <inlineHelpText>Updated details on current status.</inlineHelpText>
        <label>Status Update</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Please select the Point of Contact for this critical item.</inlineHelpText>
        <label>Critical Item POC</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Critical_Issues</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Critical Item</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Critical Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestCriticalItemTrigger.cls
/*-------------------------------------------------------------------------------
  TestCriticalItemTrigger.cls
  Class for testing Critical Item trigger on Critical_Issues__c object
  -------------------------------------------------------------------------------
  Author                 |Date       | Version | Description
  -------------------------------------------------------------------------------
  Rajakumar               03/25/2014   1.0       Creation
  -------------------------------------------------------------------------------
  ------------------------------------------------------------------------------- */
//@isTest(seeAllData=true)
@isTest
private class TestCriticalItemTrigger {
 
    // test the record sharing - Insert
    @isTest
    static void testInsertSharing() {
 
        Set<ID> recids = new Set<ID>();
        Set<ID> ciupdateids = new Set<ID>();
                
        List<Critical_Issues__c> citemslist = new List<Critical_Issues__c>();
        List<User> users = [SELECT Id FROM User WHERE IsActive = true AND ProfileId IN (SELECT Id FROM Profile WHERE Name = 'GSA Standard Platform User') LIMIT 3];
        
        ID ciUser1Id = users[0].Id;
        ID ciUser2Id = users[1].Id;
        ID ciUser3Id = users[2].Id;
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        
        System.runAs(thisUser) {
        // for critical items - created
        for (Integer i=0;i<200;i++) {
            citemslist.add(new Critical_Issues__c(Organization__c = 'OCIO', 
                                        Related_Organization__c='Region 1', 
                                        Critical_Item_Status__c='New', User__c=ciUser1Id,
                                        Action_Required_by_Administrator__c='Ready For Signature/Approval',
                                        Date_Updated__c=Date.today(),
                                        Additional_Comments2__c='Test1',
                                        Action_Type_Detail__c='Budget',
                                        Deadline__c=Date.today()+1,
                                        Recommended_Action__c='need to discuss',
                                        IQ_Number__c='123',
                                        Status_Update__c='Test1', Name='Test'+i));
        }
        insert citemslist;
 
        // insert the records with POC  
        for (Critical_Issues__c ci : citemslist) {
            recids.add(ci.Id);
        }
      
        // assert that 50 POC shares were created for critical items
        List<Critical_Issues__Share> pocshares = [SELECT Id FROM Critical_Issues__Share WHERE 
                                                    ParentId IN :recids AND UserOrGroupId = :ciUser1Id AND AccessLevel = 'Read' 
                                                    AND RowCause = 'POC__c'];
        System.assertEquals(200,pocshares.size());
    
        }
        
    }
    
    // test the record sharing - Update
    @isTest
    static void testUpdateSharing() {
 
        Set<ID> recids = new Set<ID>();
        Set<ID> ciupdateids = new Set<ID>();
        List<Critical_Issues__c> citemslist = new List<Critical_Issues__c>();
        List<User> users = [SELECT Id FROM User WHERE IsActive = true AND ProfileId IN (SELECT Id FROM Profile WHERE Name = 'GSA Standard Platform User') LIMIT 3];
        
        ID ciUser1Id = users[0].Id;
        ID ciUser2Id = users[1].Id;
        ID ciUser3Id = users[2].Id;
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        System.runAs(thisUser) {
        //citemslist = [Select Id, User__c from Critical_Issues__c LIMIT 5];
        
        // for critical items - created
        for (Integer i=0;i<200;i++) {
            citemslist.add(new Critical_Issues__c(Organization__c = 'OCIO', 
                                        Related_Organization__c='Region 1', 
                                        Critical_Item_Status__c='New', User__c=ciUser1Id,
                                        Action_Required_by_Administrator__c='Ready For Signature/Approval',
                                        Date_Updated__c=Date.today(),
                                        Additional_Comments2__c='Test1',
                                        Action_Type_Detail__c='Budget',
                                        Deadline__c=Date.today()+1,
                                        Recommended_Action__c='need to discuss',
                                        IQ_Number__c='123',
                                        Status_Update__c='Test1', Name='Test'+i));
        }
        insert citemslist;
        
        // update the existing records to assign them to different POCs 
        Test.startTest();
        for (Critical_Issues__c ci : citemslist) {
            ci.User__c = ciUser2Id;
            ciupdateids.add(ci.Id);
        }
        update citemslist;
        
        // assert that 5 POC shares were updated for critical items
        List<Critical_Issues__Share> pocupdshares = [SELECT Id FROM Critical_Issues__Share WHERE 
                                                        ParentId IN :ciupdateids AND UserOrGroupId = :ciUser2Id 
                                                        AND RowCause = 'POC__c'];
        System.assertEquals(200, pocupdshares.size());
        
        // assert that 5 old POC shares were deleted i.e. 0 old POC shares exist
        List<Critical_Issues__Share> pocdelshares = [SELECT Id FROM Critical_Issues__Share WHERE 
                                                        ParentId IN :ciupdateids AND UserOrGroupId = :ciUser1Id 
                                                        AND RowCause = 'POC__c'];
        System.assertEquals(0, pocdelshares.size());
        Test.stopTest();
        }
    }
    /*
    @isTest
    static void testUpdateStatusValidation() {
 
        Set<ID> recids = new Set<ID>();
        Set<ID> ciupdateids = new Set<ID>();
        List<Critical_Issues__c> citemslist = new List<Critical_Issues__c>();
        List<User> users = [SELECT Id FROM User WHERE IsActive = true LIMIT 3];
        
        ID ciUser1Id = users[0].Id;
        ID ciUser2Id = users[1].Id;
        ID ciUser3Id = users[2].Id;
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        System.runAs(thisUser) {
        //citemslist = [Select Id, User__c from Critical_Issues__c LIMIT 5];
        for (Integer i=0;i<13;i++) {
            citemslist.add(new Critical_Issues__c(Organization__c = 'OCIO', 
                                        Related_Organization__c='Region 1', 
                                        Critical_Item_Status__c='New', User__c=ciUser1Id,
                                        Action_Required_by_Administrator__c='Ready For Signature/Approval',
                                        Date_Updated__c=Date.today(),
                                        Additional_Comments2__c='Test1',
                                        Action_Type_Detail__c='Budget',
                                        Deadline__c=Date.today()+1,
                                        Recommended_Action__c='need to discuss',
                                        IQ_Number__c='123',
                                        Status_Update__c='Test1', Name='Test'+i));
        }
        insert citemslist;
        
        // insert the records with POC  
        for (Integer i=0; i<13; i++) {
            recids.add(citemslist[i].Id);
            if (i == 0)
                citemslist[i].Critical_Item_Status__c='Follow-up';
            else if (i == 1)
                citemslist[i].Critical_Item_Status__c='RC Reviewed';
            else if (i == 2)
                citemslist[i].Critical_Item_Status__c='Business Line Reviewed';
            else if (i == 3)
                citemslist[i].Critical_Item_Status__c='RA Reviewed';
            else if (i == 4)
                citemslist[i].Critical_Item_Status__c='Commissioner Reviewed';
            else if (i == 5)
                citemslist[i].Critical_Item_Status__c='Commissioner Approved';
            else if (i == 6)
                citemslist[i].Critical_Item_Status__c='Staff Office Reviewed';
            else if (i == 7)
                citemslist[i].Critical_Item_Status__c='Front Office Reviewed';
            else if (i == 8)
                citemslist[i].Critical_Item_Status__c='Chief of Staff Reviewed';
            else if (i == 9)
                citemslist[i].Critical_Item_Status__c='Deputy Administrator Reviewed';
            else if (i == 10)
                citemslist[i].Critical_Item_Status__c='Administrator Reviewed';
            else if (i == 11)
                citemslist[i].Critical_Item_Status__c='Administrator Approved';
            else
                citemslist[i].Action_Required_by_Administrator__c='Ready For Signature/Approval'; 
        
        
        }
        
        // update the existing records to assign them to different POCs 
        try {
            update citemslist;
        }
        catch (DmlException e) {
            System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION', e.getDmlStatusCode(0));
        }
        }
    }
        
    @isTest
    static void testInsertStatusValidation() {
 
        Set<ID> recids = new Set<ID>();
        Set<ID> ciupdateids = new Set<ID>();
        List<Critical_Issues__c> citemslist = new List<Critical_Issues__c>();
        List<User> users = [SELECT Id FROM User WHERE IsActive = true LIMIT 3];
        
        ID ciUser1Id = users[0].Id;
        ID ciUser2Id = users[1].Id;
        ID ciUser3Id = users[2].Id;
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        System.runAs(thisUser) {
        //citemslist = [Select Id, User__c from Critical_Issues__c LIMIT 5];
        for (Integer i=0;i<13;i++) {
            citemslist.add(new Critical_Issues__c(Organization__c = 'OCIO', 
                                        Related_Organization__c='Region 1', 
                                        Critical_Item_Status__c='New', User__c=ciUser1Id,
                                        Action_Required_by_Administrator__c='Ready For Signature/Approval',
                                        Date_Updated__c=Date.today(),
                                        Additional_Comments2__c='Test1',
                                        Action_Type_Detail__c='Budget',
                                        Deadline__c=Date.today()+1,
                                        Recommended_Action__c='need to discuss',
                                        IQ_Number__c='123',
                                        Status_Update__c='Test1', Name='Test'+i));
        }
        //insert citemslist;
        
        // insert the records with POC  
        for (Integer i=0; i<13; i++) {
            //recids.add(citemslist[i].Id);
            if (i == 0)
                citemslist[i].Critical_Item_Status__c='Follow-up';
            else if (i == 1)
                citemslist[i].Critical_Item_Status__c='RC Reviewed';
            else if (i == 2)
                citemslist[i].Critical_Item_Status__c='Business Line Reviewed';
            else if (i == 3)
                citemslist[i].Critical_Item_Status__c='RA Reviewed';
            else if (i == 4)
                citemslist[i].Critical_Item_Status__c='Commissioner Reviewed';
            else if (i == 5)
                citemslist[i].Critical_Item_Status__c='Commissioner Approved';
            else if (i == 6)
                citemslist[i].Critical_Item_Status__c='Staff Office Reviewed';
            else if (i == 7)
                citemslist[i].Critical_Item_Status__c='Front Office Reviewed';
            else if (i == 8)
                citemslist[i].Critical_Item_Status__c='Chief of Staff Reviewed';
            else if (i == 9)
                citemslist[i].Critical_Item_Status__c='Deputy Administrator Reviewed';
            else if (i == 10)
                citemslist[i].Critical_Item_Status__c='Administrator Reviewed';
            else if (i == 11)
                citemslist[i].Critical_Item_Status__c='Administrator Approved';
            else
                citemslist[i].Action_Required_by_Administrator__c='Ready For Signature/Approval';  
        
        
        }
        
        // update the existing records to assign them to different POCs 
        try {
            insert citemslist;
        }
        catch (DmlException e) {
            System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION', e.getDmlStatusCode(0));
        }
        }
    }
    */
    //adding users
    @isTest
    static void testUpdateStatusAddUsers() {
 
        Set<ID> recids = new Set<ID>();
        Set<ID> ciupdateids = new Set<ID>();
        List<Critical_Issues__c> citemslist = new List<Critical_Issues__c>();
        List<User> users = [SELECT Id FROM User WHERE IsActive = true LIMIT 3];
        
        ID ciUser1Id = users[0].Id;
        ID ciUser2Id = users[1].Id;
        ID ciUser3Id = users[2].Id;
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        List<Group> grpList = [SELECT Id FROM Group WHERE DeveloperName 
            IN ('Critical_Items_Delegate_Users',
                'Critical_Items_RA_Users',
                'Critical_Items_RC_Users',
                'Critical_Items_ExecSec_Users',
                'Critical_Items_HSO_Users',
                'Critical_Items_Front_Office_Users',
                'Critical_Items_Commissioner_Users',
                'Critical_Items_Administrator_Users',
                'Critical_Items_ChiefofStaff_Users',
                'Critical_Items_DeputyAdmin_Users',               
                'Critical_Items_BusLineExec_Users')];
        for(Group grp : grpList) {
            GroupMember gm = new GroupMember(GroupId=grp.Id, UserOrGroupId=thisUser.Id);
            //GroupMemberAssign.addUserstoGroup(gm);
            insert gm;
        }    
        System.runAs(thisUser) {
        //citemslist = [Select Id, User__c from Critical_Issues__c LIMIT 5];
        for (Integer i=0;i<13;i++) {
            citemslist.add(new Critical_Issues__c(Organization__c = 'OCIO', 
                                        Related_Organization__c='Region 1', 
                                        Critical_Item_Status__c='New', User__c=ciUser1Id,
                                        Action_Required_by_Administrator__c='Ready For Signature/Approval',
                                        Date_Updated__c=Date.today(),
                                        Additional_Comments2__c='Test1',
                                        Action_Type_Detail__c='Budget',
                                        Deadline__c=Date.today()+1,
                                        Recommended_Action__c='need to discuss',
                                        IQ_Number__c='123',
                                        Status_Update__c='Test1', Name='Test'+i));
        }
        insert citemslist;
        
        // insert the records with POC  
        for (Integer i=0; i<13; i++) {
            recids.add(citemslist[i].Id);
            if (i == 0)
                citemslist[i].Critical_Item_Status__c='Follow-up';
            else if (i == 1)
                citemslist[i].Critical_Item_Status__c='RC Reviewed';
            else if (i == 2)
                citemslist[i].Critical_Item_Status__c='Business Line Reviewed';
            else if (i == 3)
                citemslist[i].Critical_Item_Status__c='RA Reviewed';
            else if (i == 4)
                citemslist[i].Critical_Item_Status__c='Commissioner Reviewed';
            else if (i == 5)
                citemslist[i].Critical_Item_Status__c='Commissioner Approved';
            else if (i == 6)
                citemslist[i].Critical_Item_Status__c='Staff Office Reviewed';
            else if (i == 7)
                citemslist[i].Critical_Item_Status__c='Front Office Reviewed';
            else if (i == 8)
                citemslist[i].Critical_Item_Status__c='Chief of Staff Reviewed';
            else if (i == 9)
                citemslist[i].Critical_Item_Status__c='Deputy Administrator Reviewed';
            else if (i == 10)
                citemslist[i].Critical_Item_Status__c='Administrator Reviewed';
            else if (i == 11)
                citemslist[i].Critical_Item_Status__c='Administrator Approved';
            else
                citemslist[i].Action_Required_by_Administrator__c='Ready For Signature/Approval'; 
        
        
        }
        
        // update the existing records to assign them to different POCs 
        try {
            update citemslist;
        }
        catch (DmlException e) {
            System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION', e.getDmlStatusCode(0));
        }
        }
    }
    
    // adding users
    @isTest
    static void testInsertStatusAddUsers() {
 
        Set<ID> recids = new Set<ID>();
        Set<ID> ciupdateids = new Set<ID>();
        List<Critical_Issues__c> citemslist = new List<Critical_Issues__c>();
        List<User> users = [SELECT Id FROM User WHERE IsActive = true LIMIT 3];
        
        ID ciUser1Id = users[0].Id;
        ID ciUser2Id = users[1].Id;
        ID ciUser3Id = users[2].Id;
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        List<Group> grpList = [SELECT Id FROM Group WHERE DeveloperName 
            IN ('Critical_Items_Delegate_Users',
                'Critical_Items_RA_Users',
                'Critical_Items_RC_Users',
                'Critical_Items_ExecSec_Users',
                'Critical_Items_HSO_Users',
                'Critical_Items_Front_Office_Users',
                'Critical_Items_Commissioner_Users',
                'Critical_Items_Administrator_Users',
                'Critical_Items_ChiefofStaff_Users',
                'Critical_Items_DeputyAdmin_Users',               
                'Critical_Items_BusLineExec_Users')];
        for(Group grp : grpList) {
            GroupMember gm = new GroupMember(GroupId=grp.Id, UserOrGroupId=thisUser.Id);
            //GroupMemberAssign.addUserstoGroup(gm);
            insert gm;
        }    
        System.runAs(thisUser) {
        //citemslist = [Select Id, User__c from Critical_Issues__c LIMIT 5];
        for (Integer i=0;i<13;i++) {
            citemslist.add(new Critical_Issues__c(Organization__c = 'OCIO', 
                                        Related_Organization__c='Region 1', 
                                        Critical_Item_Status__c='New', User__c=ciUser1Id,
                                        Action_Required_by_Administrator__c='Ready For Signature/Approval',
                                        Date_Updated__c=Date.today(),
                                        Additional_Comments2__c='Test1',
                                        Action_Type_Detail__c='Budget',
                                        Deadline__c=Date.today()+1,
                                        Recommended_Action__c='need to discuss',
                                        IQ_Number__c='123',
                                        Status_Update__c='Test1', Name='Test'+i));
        }
        //insert citemslist;
        
        // insert the records with POC  
        for (Integer i=0; i<13; i++) {
            //recids.add(citemslist[i].Id);
            if (i == 0)
                citemslist[i].Critical_Item_Status__c='Follow-up';
            else if (i == 1)
                citemslist[i].Critical_Item_Status__c='RC Reviewed';
            else if (i == 2)
                citemslist[i].Critical_Item_Status__c='Business Line Reviewed';
            else if (i == 3)
                citemslist[i].Critical_Item_Status__c='RA Reviewed';
            else if (i == 4)
                citemslist[i].Critical_Item_Status__c='Commissioner Reviewed';
            else if (i == 5)
                citemslist[i].Critical_Item_Status__c='Commissioner Approved';
            else if (i == 6)
                citemslist[i].Critical_Item_Status__c='Staff Office Reviewed';
            else if (i == 7)
                citemslist[i].Critical_Item_Status__c='Front Office Reviewed';
            else if (i == 8)
                citemslist[i].Critical_Item_Status__c='Chief of Staff Reviewed';
            else if (i == 9)
                citemslist[i].Critical_Item_Status__c='Deputy Administrator Reviewed';
            else if (i == 10)
                citemslist[i].Critical_Item_Status__c='Administrator Reviewed';
            else if (i == 11)
                citemslist[i].Critical_Item_Status__c='Administrator Approved';
            else
                citemslist[i].Action_Required_by_Administrator__c='Ready For Signature/Approval';  
        }
        
        // update the existing records to assign them to different POCs 
        try {
            insert citemslist;
        }
        catch (DmlException e) {
            System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION', e.getDmlStatusCode(0));
        }
        }
    }


    @isTest
    static void testInsertValidationUnassigned() {
 
        Set<ID> recids = new Set<ID>();
        Set<ID> ciupdateids = new Set<ID>();
        List<Critical_Issues__c> citemslist = new List<Critical_Issues__c>();
        List<User> users = [SELECT Id FROM User WHERE IsActive = true LIMIT 3];
        
        ID ciUser1Id = users[0].Id;
        ID ciUser2Id = users[1].Id;
        ID ciUser3Id = users[2].Id;
        User thisUser = [SELECT Id FROM User WHERE IsActive = true AND Id != :UserInfo.getUserId() 
                    AND ProfileId IN (SELECT Id FROM Profile WHERE Name = 'GSA System Administrator') LIMIT 1];
        System.runAs(thisUser) {
        //citemslist = [Select Id, User__c from Critical_Issues__c LIMIT 5];
        for (Integer i=0;i<13;i++) {
            citemslist.add(new Critical_Issues__c(Organization__c = 'OCIO', 
                                        Related_Organization__c='Region 1', 
                                        Critical_Item_Status__c='New', User__c=ciUser1Id,
                                        Action_Required_by_Administrator__c='Info Only/No Action Needed',
                                        Date_Updated__c=Date.today(),
                                        Additional_Comments2__c='Test1',
                                        Action_Type_Detail__c='Budget',
                                        Deadline__c=Date.today()+1,
                                        Recommended_Action__c='need to discuss',
                                        IQ_Number__c='123',
                                        Status_Update__c='Test1', Name='Test'+i));
        }
        //insert citemslist;
        
        // insert the records with POC  
        for (Integer i=0; i<13; i++) {
            //recids.add(citemslist[i].Id);
            if (i == 0)
                citemslist[i].Critical_Item_Status__c='Follow-up';
            else if (i == 1)
                citemslist[i].Critical_Item_Status__c='RC Reviewed';
            else if (i == 2)
                citemslist[i].Critical_Item_Status__c='Business Line Reviewed';
            else if (i == 3)
                citemslist[i].Critical_Item_Status__c='RA Reviewed';
            else if (i == 4)
                citemslist[i].Critical_Item_Status__c='Commissioner Reviewed';
            else if (i == 5)
                citemslist[i].Critical_Item_Status__c='Commissioner Approved';
            else if (i == 6)
                citemslist[i].Critical_Item_Status__c='Staff Office Reviewed';
            else if (i == 7)
                citemslist[i].Critical_Item_Status__c='Front Office Reviewed';
            else if (i == 8)
                citemslist[i].Critical_Item_Status__c='Chief of Staff Reviewed';
            else if (i == 9)
                citemslist[i].Critical_Item_Status__c='Deputy Administrator Reviewed';
            else if (i == 10)
                citemslist[i].Critical_Item_Status__c='Administrator Reviewed';
            else if (i == 11)
                citemslist[i].Critical_Item_Status__c='Administrator Approved';
            else
                citemslist[i].Action_Required_by_Administrator__c='Ready For Signature/Approval';  
        
        
        }
        
        // update the existing records to assign them to different POCs 
        try {
            insert citemslist;
        }
        catch (DmlException e) {
            System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION', e.getDmlStatusCode(0));
        }
        }
    }
    
    @isTest
    static void testUpdateValidationUnassigned() {
 
        Set<ID> recids = new Set<ID>();
        Set<ID> ciupdateids = new Set<ID>();
        List<Critical_Issues__c> citemslist = new List<Critical_Issues__c>();
        List<User> users = [SELECT Id FROM User WHERE IsActive = true LIMIT 3];
        
        ID ciUser1Id = users[0].Id;
        ID ciUser2Id = users[1].Id;
        ID ciUser3Id = users[2].Id;
        User thisUser = [SELECT Id FROM User WHERE IsActive = true AND Id != :UserInfo.getUserId() 
                    AND ProfileId IN (SELECT Id FROM Profile WHERE Name = 'GSA System Administrator') LIMIT 1];
        System.runAs(thisUser) {
        //citemslist = [Select Id, User__c from Critical_Issues__c LIMIT 5];
        for (Integer i=0;i<13;i++) {
            citemslist.add(new Critical_Issues__c(Organization__c = 'OCIO', 
                                        Related_Organization__c='Region 1', 
                                        Critical_Item_Status__c='New', User__c=ciUser1Id,
                                        Action_Required_by_Administrator__c='Info Only/No Action Needed',
                                        Date_Updated__c=Date.today(),
                                        Additional_Comments2__c='Test1',
                                        Action_Type_Detail__c='Budget',
                                        Deadline__c=Date.today()+1,
                                        Recommended_Action__c='need to discuss',
                                        IQ_Number__c='123',
                                        Status_Update__c='Test1', Name='Test'+i));
        }
        insert citemslist;
        
        // insert the records with POC  
        for (Integer i=0; i<13; i++) {
            recids.add(citemslist[i].Id);
            if (i == 0)
                citemslist[i].Critical_Item_Status__c='Follow-up';
            else if (i == 1)
                citemslist[i].Critical_Item_Status__c='RC Reviewed';
            else if (i == 2)
                citemslist[i].Critical_Item_Status__c='Business Line Reviewed';
            else if (i == 3)
                citemslist[i].Critical_Item_Status__c='RA Reviewed';
            else if (i == 4)
                citemslist[i].Critical_Item_Status__c='Commissioner Reviewed';
            else if (i == 5)
                citemslist[i].Critical_Item_Status__c='Commissioner Approved';
            else if (i == 6)
                citemslist[i].Critical_Item_Status__c='Staff Office Reviewed';
            else if (i == 7)
                citemslist[i].Critical_Item_Status__c='Front Office Reviewed';
            else if (i == 8)
                citemslist[i].Critical_Item_Status__c='Chief of Staff Reviewed';
            else if (i == 9)
                citemslist[i].Critical_Item_Status__c='Deputy Administrator Reviewed';
            else if (i == 10)
                citemslist[i].Critical_Item_Status__c='Administrator Reviewed';
            else if (i == 11)
                citemslist[i].Critical_Item_Status__c='Administrator Approved';
            else
                citemslist[i].Action_Required_by_Administrator__c='Info Only/May Require Action'; 
        }
        
        // update the existing records to assign them to different POCs 
        try {
            update citemslist;
        }
        catch (DmlException e) {
            System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION', e.getDmlStatusCode(0));
        }
        }
    }
    
}