src/objects/Developmental_Objective__c.object
<CustomObject>
    <fields>
        <fullName>IDP__c</fullName>
        <inlineHelpText>IDP - This field indicates the IDP that the Objective is related to.</inlineHelpText>
        <label>IDP</label>
        <referenceTo>IDP__c</referenceTo>
        <relationshipLabel>Developmental Objectives</relationshipLabel>
        <relationshipName>Developmental_Objectives</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Developmental Objective</label>
    <nameField>
        <displayFormat>OBJ-{0000000}</displayFormat>
        <label>Developmental Objective Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Developmental Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Form_SF_182__c.object
<CustomObject>
    <fields>
        <fullName>IDP__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Related IDP - Please select the approved IDP that is related to this SF 182</inlineHelpText>
        <label>Related IDP</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>IDP__c.IDP_Status__c</field>
                <operation>equals</operation>
                <value>Approved, Archived</value>
            </filterItems>
            <filterItems>
                <field>IDP__c.OwnerId</field>
                <operation>equals</operation>
                <valueField>$Source.OwnerId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>IDP__c</referenceTo>
        <relationshipLabel>SF 182</relationshipLabel>
        <relationshipName>Form_SF_182</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>SF 182</label>
    <nameField>
        <displayFormat>SF182 {0000}</displayFormat>
        <label>SF 182 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SF 182</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IDP__c.object
<CustomObject>
    <description>This is a custom object to capture IDPs</description>
    <fields>
        <fullName>Create_Date__c</fullName>
        <formula>CreatedDate</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Created Date - This field pre-populates with the date the IDP was created</inlineHelpText>
        <label>Create Date</label>
        <type>Date</type>
    </fields>
    <label>Shared IDPs</label>
    <nameField>
        <displayFormat>IDP-{0000000}</displayFormat>
        <label>IDP Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shared IDPs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IDP_Developmental_Line_Item__c.object
<CustomObject>
    <description>Child object to Developmental Objectives. Used to capture developmental activity line items.</description>
    <fields>
        <fullName>Activity_Type__c</fullName>
        <formula>$RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Activity Type - Select the option that most closely fits your activity</inlineHelpText>
        <label>Activity Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assignment_Title__c</fullName>
        <description>This is a generic title for all developmental activities that can fall under IDP.</description>
        <inlineHelpText>Activity Name - Enter a brief description of the Activity</inlineHelpText>
        <label>Activity Name</label>
        <length>140</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Create_Date__c</fullName>
        <formula>CreatedDate</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Created Date - This field will automatically show the date the activity was created.</inlineHelpText>
        <label>Create Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Developmental_Objective__c</fullName>
        <description>Lookup to Objective from Activity

One Objective of an IDP can have mutiple Activity</description>
        <inlineHelpText>Developmental Objective - Select the Objective that your new Activity will be associated with</inlineHelpText>
        <label>Developmental Objective</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2 AND 3) OR 4</booleanFilter>
            <filterItems>
                <field>Developmental_Objective__c.IDP__r.IDP_Status__c</field>
                <operation>equals</operation>
                <value>New, Needs Revision, Resubmit, Approved</value>
            </filterItems>
            <filterItems>
                <field>$User.Id</field>
                <operation>equals</operation>
                <valueField>Developmental_Objective__c.IDP__r.OwnerId</valueField>
            </filterItems>
            <filterItems>
                <field>Developmental_Objective__c.IDP__r.Id</field>
                <operation>equals</operation>
                <valueField>Developmental_Objective__c.IDP__c</valueField>
            </filterItems>
            <filterItems>
                <field>$User.Id</field>
                <operation>equals</operation>
                <valueField>Developmental_Objective__c.IDP__r.Supervisor__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Developmental_Objective__c</referenceTo>
        <relationshipLabel>Developmental Activities</relationshipLabel>
        <relationshipName>Developmental_Activities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Planned_End_Date__c</fullName>
        <description>Planned End Date for IDP Developmental Activities.</description>
        <inlineHelpText>Planned End Date - Enter the date in which your Activity will end. Example Format: MM/DD/YYYY.</inlineHelpText>
        <label>Planned End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Planned_Start_Date__c</fullName>
        <description>Planned Start Date for IDP Developmental Activities</description>
        <inlineHelpText>Planned Start Date - Enter the date in which your Activity will begin. Example Format: MM/DD/YYYY.</inlineHelpText>
        <label>Planned Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Cost__c</fullName>
        <formula>Books_Material_Costs__c+Tuition_Fees__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Total Estimated Cost - This field calculates the total dollar value from the Estimated Tuition &amp; Fees and Estimated Books &amp; Material Costs fields.</inlineHelpText>
        <label>Total Estimated Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Developmental Activity</label>
    <nameField>
        <displayFormat>DA-{000000}</displayFormat>
        <label>Developmental Activity</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Developmental Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/IDP_SF182RequestEditControllerHelper.cls
/*
	This class only exists because the IDP_SF182RequestEditController cannot be labelled
	'without sharing' because it is associated with a Visualforce page. Usually this 
	could be defended but GSA uses a security scanner that will complain about VF pages
	labelled as 'without sharing'. Getting an exception from security for this is next to 
	impossible.
*/
public without sharing class IDP_SF182RequestEditControllerHelper {

	public static Form_SF_182__c getSF182(Id id){
		return [SELECT Id, Idp__c FROM Form_SF_182__c WHERE Id = :id];
	}

	public static Form_SF_182__c getSF182(String name){
		return [SELECT Id, Idp__c FROM Form_SF_182__c WHERE Name = :name];
	}
	
	public static List<IDP_Developmental_Line_Item__c> getActivities(Id idpId){
		return [
			SELECT Id, Name, Developmental_Objective__r.IDP__c, Total_Cost__c, Assignment_Title__c, 
				Create_Date__c, Planned_Start_Date__c, Planned_End_Date__c, Activity_Type__c
			FROM IDP_Developmental_Line_Item__c 
			WHERE Developmental_Objective__r.IDP__c = :idpId
			ORDER BY Name ASC];
	}

	public static String getActivityName(Id activityId){
		return [SELECT Id, Name FROM IDP_Developmental_Line_Item__c WHERE Id = :activityId].Name;
	}

}