src/objects/Developmental_Objective__c.object
<CustomObject>
    <fields>
        <fullName>IDP__c</fullName>
        <inlineHelpText>IDP - This field indicates the IDP that the Objective is related to.</inlineHelpText>
        <label>IDP</label>
        <referenceTo>IDP__c</referenceTo>
        <relationshipLabel>Developmental Objectives</relationshipLabel>
        <relationshipName>Developmental_Objectives</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Developmental Objective</label>
    <nameField>
        <displayFormat>OBJ-{0000000}</displayFormat>
        <label>Developmental Objective Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Developmental Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Form_SF_182__c.object
<CustomObject>
    <fields>
        <fullName>IDP__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Related IDP - Please select the approved IDP that is related to this SF 182</inlineHelpText>
        <label>Related IDP</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>IDP__c.IDP_Status__c</field>
                <operation>equals</operation>
                <value>Approved, Archived</value>
            </filterItems>
            <filterItems>
                <field>IDP__c.OwnerId</field>
                <operation>equals</operation>
                <valueField>$Source.OwnerId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>IDP__c</referenceTo>
        <relationshipLabel>SF 182</relationshipLabel>
        <relationshipName>Form_SF_182</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>SF 182</label>
    <nameField>
        <displayFormat>SF182 {0000}</displayFormat>
        <label>SF 182 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SF 182</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IDP__c.object
<CustomObject>
    <description>This is a custom object to capture IDPs</description>
    <fields>
        <fullName>IDP_Status__c</fullName>
        <description>IDP Status</description>
        <inlineHelpText>IDP Status - This field indicates where your IDP stands (i.e. New, Supervisor Review, Needs Revision, Approved, Resubmit, Archived)</inlineHelpText>
        <label>IDP Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Supervisor Review</fullName>
                </value>
                <value>
                    <fullName>Needs Revision</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Resubmit</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup for the approving supervisor</description>
        <inlineHelpText>Supervisor - Choose your Supervisor using the lookup function.  This field will indicate who your IDP should be sent to for approval.</inlineHelpText>
        <label>Supervisor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>IDP</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Shared IDPs</label>
    <nameField>
        <displayFormat>IDP-{0000000}</displayFormat>
        <label>IDP Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shared IDPs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IDP_Developmental_Line_Item__c.object
<CustomObject>
    <description>Child object to Developmental Objectives. Used to capture developmental activity line items.</description>
    <fields>
        <fullName>Developmental_Objective__c</fullName>
        <description>Lookup to Objective from Activity

One Objective of an IDP can have mutiple Activity</description>
        <inlineHelpText>Developmental Objective - Select the Objective that your new Activity will be associated with</inlineHelpText>
        <label>Developmental Objective</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2 AND 3) OR 4</booleanFilter>
            <filterItems>
                <field>Developmental_Objective__c.IDP__r.IDP_Status__c</field>
                <operation>equals</operation>
                <value>New, Needs Revision, Resubmit, Approved</value>
            </filterItems>
            <filterItems>
                <field>$User.Id</field>
                <operation>equals</operation>
                <valueField>Developmental_Objective__c.IDP__r.OwnerId</valueField>
            </filterItems>
            <filterItems>
                <field>Developmental_Objective__c.IDP__r.Id</field>
                <operation>equals</operation>
                <valueField>Developmental_Objective__c.IDP__c</valueField>
            </filterItems>
            <filterItems>
                <field>$User.Id</field>
                <operation>equals</operation>
                <valueField>Developmental_Objective__c.IDP__r.Supervisor__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Developmental_Objective__c</referenceTo>
        <relationshipLabel>Developmental Activities</relationshipLabel>
        <relationshipName>Developmental_Activities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Developmental Activity</label>
    <nameField>
        <displayFormat>DA-{000000}</displayFormat>
        <label>Developmental Activity</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Developmental Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SF_182_Training__c.object
<CustomObject>
    <fields>
        <fullName>Activity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Activity - Please select the Developmental Activity (from your IDP) that is relevant to this training</inlineHelpText>
        <label>Activity</label>
        <referenceTo>IDP_Developmental_Line_Item__c</referenceTo>
        <relationshipLabel>SF 182 Request</relationshipLabel>
        <relationshipName>SF_182_Trainings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <inlineHelpText>Approver Status - This field indicates what step within the approval process the request is in (i.e. which of the selected supervisors/approvers is currently reviewing or approving the request)</inlineHelpText>
        <label>Approver Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Pending Supervisor Review</fullName>
                </value>
                <value>
                    <fullName>Reviewed by Supervisor</fullName>
                </value>
                <value>
                    <fullName>Pending Approver 1 Review</fullName>
                </value>
                <value>
                    <fullName>Reviewed by Approver 1</fullName>
                </value>
                <value>
                    <fullName>Pending Approver 2 Review</fullName>
                </value>
                <value>
                    <fullName>Reviewed by Approver 2</fullName>
                </value>
                <value>
                    <fullName>Pending Approver 3 Review</fullName>
                </value>
                <value>
                    <fullName>Reviewed by Approver 3</fullName>
                </value>
                <value>
                    <fullName>Pending Approver 4 Review</fullName>
                </value>
                <value>
                    <fullName>Reviewed by Approver 4</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Final Approval</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request_Status__c</fullName>
        <inlineHelpText>Request Status - Please refer to Instructions for status definitions</inlineHelpText>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approval Process in Progress</fullName>
                </value>
                <value>
                    <fullName>Final Approval</fullName>
                </value>
                <value>
                    <fullName>Initiating</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Cancelled Obligated</fullName>
                </value>
                <value>
                    <fullName>Cancelled Not Obligated</fullName>
                </value>
                <value>
                    <fullName>Correction</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Supervisor - Please refer to your organizational structure to determine your Supervisor</inlineHelpText>
        <label>Supervisor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SF_182_Trainings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SF 182 Request</label>
    <nameField>
        <displayFormat>SF-Training-{000000}</displayFormat>
        <label>SF 182 Training Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SF 182 Request</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestSF182TrainingTrigger.cls
@isTest
private class TestSF182TrainingTrigger {
    public static testmethod void testSF182Training(){
        
        User u = [SELECT Id from User WHERE isActive = true AND Id != :userInfo.getUserId() LIMIT 1];
        //system.debug('This is User Id ' + u.id + ' Logged In User ' + userInfo.getUserId());
        
        List<IDP__c> idp = IDP_TestDataFactory.createTestIDPRecords(1,'FY 2017','New','Test',
                                                    'Test','IDP Standard','GSA System Administrator');
        List<Developmental_Objective__c> dobj = IDP_TestDataFactory.createObjective(idp,1);
        List<IDP_Developmental_Line_Item__c> idpli = IDP_TestDataFactory.createActivity(dobj,1,date.today(),date.today()+1);
      
        idp[0].IDP_Status__c = 'Approved';
        update idp[0];

        List<Form_SF_182__c> sf182 = IDP_TestDataFactory.createsfoneeightytwo(idp,1);
                  
        List<SF_182_Training__c> sf182req = IDP_TestDataFactory.createsfoneeightytworeq(sf182,1,'GSA System Administrator');

        sf182req[0].Supervisor__c=null;
        update sf182req[0];

        system.debug('#####' +sf182req[0]);
        
        sf182req[0].Activity__c = idpli[0].Id;
        update sf182req[0];
        
        sf182req[0].Approval_Status__c = 'Pending Supervisor Review';  
        update sf182req[0];
        
        sf182req[0].Approval_Status__c = 'Reviewed by Supervisor';
        update sf182req[0];
        
        sf182req[0].Approval_Status__c = 'Reviewed by Approver 1';
        update sf182req[0];
        
        sf182req[0].Approval_Status__c = 'Reviewed by Approver 2';
        update sf182req[0];
        
        sf182req[0].Approval_Status__c = 'Reviewed by Approver 3';
        update sf182req[0];

        sf182req[0].Approval_Status__c = 'Final Approval';
        update sf182req[0];
        
        sf182req[0].Approval_Status__c = 'New';
        update sf182req[0];
        
        sf182req[0].Request_Status__c = 'Rejected';
        update sf182req[0];

        sf182req[0].Request_Status__c = 'Initiating';  
        sf182req[0].Supervisor__c = u.Id;  
        update sf182req[0];  
 
        system.assertEquals(true,true);
        
    }

}