src/objects/Developmental_Competency__c.object
<CustomObject>
    <label>Developmental Competency</label>
    <nameField>
        <displayFormat>DC-{000000}</displayFormat>
        <label>Developmental Competency Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Developmental Competencies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Developmental_Objective__c.object
<CustomObject>
    <fields>
        <fullName>IDP__c</fullName>
        <inlineHelpText>IDP - This field indicates the IDP that the Objective is related to.</inlineHelpText>
        <label>IDP</label>
        <referenceTo>IDP__c</referenceTo>
        <relationshipLabel>Developmental Objectives</relationshipLabel>
        <relationshipName>Developmental_Objectives</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Developmental Objective</label>
    <nameField>
        <displayFormat>OBJ-{0000000}</displayFormat>
        <label>Developmental Objective Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Developmental Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IDP__c.object
<CustomObject>
    <description>This is a custom object to capture IDPs</description>
    <fields>
        <fullName>Fiscal_Year_pick__c</fullName>
        <inlineHelpText>Fiscal Year - Select the fiscal year for the IDP</inlineHelpText>
        <label>Fiscal Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>FY 2011</fullName>
                </value>
                <value>
                    <fullName>FY 2012</fullName>
                </value>
                <value>
                    <fullName>FY 2013</fullName>
                </value>
                <value>
                    <fullName>FY 2014</fullName>
                </value>
                <value>
                    <fullName>FY 2015</fullName>
                </value>
                <value>
                    <fullName>FY 2016</fullName>
                </value>
                <value>
                    <fullName>FY 2017</fullName>
                </value>
                <value>
                    <fullName>FY 2018</fullName>
                </value>
                <value>
                    <fullName>FY 2019</fullName>
                </value>
                <value>
                    <fullName>FY 2020</fullName>
                </value>
                <value>
                    <fullName>FY 2021</fullName>
                </value>
                <value>
                    <fullName>FY 2022</fullName>
                </value>
                <value>
                    <fullName>FY 2023</fullName>
                </value>
                <value>
                    <fullName>FY 2024</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Shared IDPs</label>
    <nameField>
        <displayFormat>IDP-{0000000}</displayFormat>
        <label>IDP Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shared IDPs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IDP_Developmental_Line_Item__c.object
<CustomObject>
    <description>Child object to Developmental Objectives. Used to capture developmental activity line items.</description>
    <fields>
        <fullName>Developmental_Objective__c</fullName>
        <description>Lookup to Objective from Activity

One Objective of an IDP can have mutiple Activity</description>
        <inlineHelpText>Developmental Objective - Select the Objective that your new Activity will be associated with</inlineHelpText>
        <label>Developmental Objective</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2 AND 3) OR 4</booleanFilter>
            <filterItems>
                <field>Developmental_Objective__c.IDP__r.IDP_Status__c</field>
                <operation>equals</operation>
                <value>New, Needs Revision, Resubmit, Approved</value>
            </filterItems>
            <filterItems>
                <field>$User.Id</field>
                <operation>equals</operation>
                <valueField>Developmental_Objective__c.IDP__r.OwnerId</valueField>
            </filterItems>
            <filterItems>
                <field>Developmental_Objective__c.IDP__r.Id</field>
                <operation>equals</operation>
                <valueField>Developmental_Objective__c.IDP__c</valueField>
            </filterItems>
            <filterItems>
                <field>$User.Id</field>
                <operation>equals</operation>
                <valueField>Developmental_Objective__c.IDP__r.Supervisor__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Developmental_Objective__c</referenceTo>
        <relationshipLabel>Developmental Activities</relationshipLabel>
        <relationshipName>Developmental_Activities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Developmental Activity</label>
    <nameField>
        <displayFormat>DA-{000000}</displayFormat>
        <label>Developmental Activity</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Developmental Activities</pluralLabel>
    <recordTypes>
        <fullName>Activity</fullName>
        <active>true</active>
        <description>Record Type for all the Activities</description>
        <label>Activity</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestCloneController.cls
@isTest(SeeAllData=true)
public class TestCloneController {

  static testMethod void myTestCloneController() {
        
      List<IDP__c> idp = IDP_TestDataFactory.createTestIDPRecords(1,'FY 2050','New','Test','Test','IDP Standard','GSA System Administrator'); 
      List<Developmental_Objective__c> objective = IDP_TestDataFactory.createObjective(idp,1);
	  List<IDP_Developmental_Line_Item__c> activity = IDP_TestDataFactory.createActivity(objective,1,date.today(),date.today()+1);
	  List<Developmental_Competency__c> comp = IDP_TestDataFactory.createCompetency(activity, 1);
      
      ApexPages.StandardController sc = new ApexPages.standardController(idp[0]);
      IDP_ClonePlusController   cs = new IDP_ClonePlusController (sc);       
      cs.initialiseObjectsForCloning(idp[0].Fiscal_Year_pick__c);  
      system.assertEquals(true,true);
      
      
      IDP_Details idpd = new IDP_Details();
      idpd.idpID=idp[0].id;
      idpd.submitIDP();
      idpd.reviewIDP();
      idpd.continueEditingIDP();
      idpd.deleteIDP();
      idpd.gotoIDPDetailPage();
      idpd.getCurrentIDPS();
      idpd.getPreviousIDPS();
      idpd.getApprovalIDPS();
      idpd.editIDP();
      idpd.createIDP();
      idpd.updateIDPStatus();
  }
}