src/objects/Developmental_Objective__c.object
<CustomObject>
    <fields>
        <fullName>IDP__c</fullName>
        <inlineHelpText>IDP - This field indicates the IDP that the Objective is related to.</inlineHelpText>
        <label>IDP</label>
        <referenceTo>IDP__c</referenceTo>
        <relationshipLabel>Developmental Objectives</relationshipLabel>
        <relationshipName>Developmental_Objectives</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Developmental Objective</label>
    <nameField>
        <displayFormat>OBJ-{0000000}</displayFormat>
        <label>Developmental Objective Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Developmental Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IDP__c.object
<CustomObject>
    <description>This is a custom object to capture IDPs</description>
    <label>Shared IDPs</label>
    <nameField>
        <displayFormat>IDP-{0000000}</displayFormat>
        <label>IDP Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shared IDPs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IDP_Developmental_Line_Item__c.object
<CustomObject>
    <description>Child object to Developmental Objectives. Used to capture developmental activity line items.</description>
    <fields>
        <fullName>Developmental_Objective__c</fullName>
        <description>Lookup to Objective from Activity

One Objective of an IDP can have mutiple Activity</description>
        <inlineHelpText>Developmental Objective - Select the Objective that your new Activity will be associated with</inlineHelpText>
        <label>Developmental Objective</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2 AND 3) OR 4</booleanFilter>
            <filterItems>
                <field>Developmental_Objective__c.IDP__r.IDP_Status__c</field>
                <operation>equals</operation>
                <value>New, Needs Revision, Resubmit, Approved</value>
            </filterItems>
            <filterItems>
                <field>$User.Id</field>
                <operation>equals</operation>
                <valueField>Developmental_Objective__c.IDP__r.OwnerId</valueField>
            </filterItems>
            <filterItems>
                <field>Developmental_Objective__c.IDP__r.Id</field>
                <operation>equals</operation>
                <valueField>Developmental_Objective__c.IDP__c</valueField>
            </filterItems>
            <filterItems>
                <field>$User.Id</field>
                <operation>equals</operation>
                <valueField>Developmental_Objective__c.IDP__r.Supervisor__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Developmental_Objective__c</referenceTo>
        <relationshipLabel>Developmental Activities</relationshipLabel>
        <relationshipName>Developmental_Activities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Developmental Activity</label>
    <nameField>
        <displayFormat>DA-{000000}</displayFormat>
        <label>Developmental Activity</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Developmental Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestActivitySecOnIDPStdPage.cls
/*Modified by Ramesh Dugar to improve the test class 11/22/16*/
@isTest
private class TestActivitySecOnIDPStdPage {

    static testMethod void myUnitTest() {
    
        //creating data using IDP Test Data Factory
        List<IDP__c> idp = IDP_TestDataFactory.createTestIDPRecords(1,'FY 2050','Approved','Test','Test','IDP Standard','GSA System Administrator'); 
        List<Developmental_Objective__c> dobj = IDP_TestDataFactory.createObjective(idp,1);
        List<IDP_Developmental_Line_Item__c> idpli = IDP_TestDataFactory.createActivity(dobj,1,date.today(),date.today()+1); 
        
        system.debug('**'+idp);
        PageReference p = Page.IDP_activitySecOnIDPStdPage;
        p.getParameters().put('id', idp[0].Id);   
        Test.setCurrentPage(p); 
        ApexPages.StandardController sc = new ApexPages.StandardController(idp[0]); 
        IDP_activitySecOnIDPStdPage obj = new IDP_activitySecOnIDPStdPage(sc); 
        obj.getActivityWrapperList();
     
        system.assert(idp != null);                         
    }
}