src/objects/Developmental_Objective__c.object
<CustomObject>
    <fields>
        <fullName>IDP__c</fullName>
        <inlineHelpText>IDP - This field indicates the IDP that the Objective is related to.</inlineHelpText>
        <label>IDP</label>
        <referenceTo>IDP__c</referenceTo>
        <relationshipLabel>Developmental Objectives</relationshipLabel>
        <relationshipName>Developmental_Objectives</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Developmental Objective</label>
    <nameField>
        <displayFormat>OBJ-{0000000}</displayFormat>
        <label>Developmental Objective Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Developmental Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IDP__c.object
<CustomObject>
    <description>This is a custom object to capture IDPs</description>
    <fields>
        <fullName>Create_Date__c</fullName>
        <formula>CreatedDate</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Created Date - This field pre-populates with the date the IDP was created</inlineHelpText>
        <label>Create Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDP_Status__c</fullName>
        <description>IDP Status</description>
        <inlineHelpText>IDP Status - This field indicates where your IDP stands (i.e. New, Supervisor Review, Needs Revision, Approved, Resubmit, Archived)</inlineHelpText>
        <label>IDP Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Supervisor Review</fullName>
                </value>
                <value>
                    <fullName>Needs Revision</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Resubmit</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Series__c</fullName>
        <inlineHelpText>Series - Select the position classification four digit series that is applicable to you (e.g., 0201)</inlineHelpText>
        <label>Series</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0018 - Safety and Occupational Health Management Series</fullName>
                </value>
                <value>
                    <fullName>0020 - Community Planning Series</fullName>
                </value>
                <value>
                    <fullName>0028 - Environmental Protection Specialist Series</fullName>
                </value>
                <value>
                    <fullName>0080 - Security Administration Series</fullName>
                </value>
                <value>
                    <fullName>0086 - Security Clerical and Assistant Series</fullName>
                </value>
                <value>
                    <fullName>0089 - Emergency Management Series</fullName>
                </value>
                <value>
                    <fullName>0099 - General Student Trainee Series</fullName>
                </value>
                <value>
                    <fullName>0110 - Economist Series</fullName>
                </value>
                <value>
                    <fullName>0132 - Intelligence Series</fullName>
                </value>
                <value>
                    <fullName>0201 - HR Specialist Series</fullName>
                </value>
                <value>
                    <fullName>0203 - Human Resources Assistant Series</fullName>
                </value>
                <value>
                    <fullName>0260 - Equal Employment Opportunity Series</fullName>
                </value>
                <value>
                    <fullName>0299 - Human Resources Management Student Trainee</fullName>
                </value>
                <value>
                    <fullName>0301 - Miscellaneous Administration and Program Series</fullName>
                </value>
                <value>
                    <fullName>0303 - Miscellaneous Clerk and Assistant Series</fullName>
                </value>
                <value>
                    <fullName>0305 - Mail and File Series</fullName>
                </value>
                <value>
                    <fullName>0306 - Government Information Series</fullName>
                </value>
                <value>
                    <fullName>0308 - Records and Information Management Specialist</fullName>
                </value>
                <value>
                    <fullName>0318 - Secretary Series</fullName>
                </value>
                <value>
                    <fullName>0326 - Office Automation Clerical and Assistance Series</fullName>
                </value>
                <value>
                    <fullName>0335 - Computer Clerk and Assistant Series</fullName>
                </value>
                <value>
                    <fullName>0340 - Program Management Series</fullName>
                </value>
                <value>
                    <fullName>0341 - Administrative Officer Series</fullName>
                </value>
                <value>
                    <fullName>0342 - Support Services Administration Series</fullName>
                </value>
                <value>
                    <fullName>0343 - Management and Program Analysis Series</fullName>
                </value>
                <value>
                    <fullName>0344 - Management and Program Clerical and Assistance Series</fullName>
                </value>
                <value>
                    <fullName>0350 - Equipment Operator Series</fullName>
                </value>
                <value>
                    <fullName>0360 - Equal Opportunity Compliance Series</fullName>
                </value>
                <value>
                    <fullName>0391 - Telecommunication Series</fullName>
                </value>
                <value>
                    <fullName>0392 - General Telecommunication Series</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Shared IDPs</label>
    <nameField>
        <displayFormat>IDP-{0000000}</displayFormat>
        <label>IDP Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shared IDPs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IDP_Developmental_Line_Item__c.object
<CustomObject>
    <description>Child object to Developmental Objectives. Used to capture developmental activity line items.</description>
    <fields>
        <fullName>Activity_Type__c</fullName>
        <formula>$RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Activity Type - Select the option that most closely fits your activity</inlineHelpText>
        <label>Activity Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assignment_Title__c</fullName>
        <description>This is a generic title for all developmental activities that can fall under IDP.</description>
        <inlineHelpText>Activity Name - Enter a brief description of the Activity</inlineHelpText>
        <label>Activity Name</label>
        <length>140</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Books_Material_Costs__c</fullName>
        <inlineHelpText>Estimated Books &amp; Material Cost - Insert the materials cost for training that was paid for
by the Federal Government. (Refer to the Guide for Human Resources Reporting at
http://www.opm.gov/feddata/guidance.asp for more information) Example Format: 250.</inlineHelpText>
        <label>Estimated Books &amp; Material Costs</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <inlineHelpText>Comments - Enter any comments/notes related to your IDP</inlineHelpText>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Cost_Travel__c</fullName>
        <description>Travel Fees</description>
        <inlineHelpText>Estimated Travel Cost - This field represents the estimated travel cost that the Activity is expected to cost. Example Format: 500.</inlineHelpText>
        <label>Estimated Travel Costs</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Create_Date__c</fullName>
        <formula>CreatedDate</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Created Date - This field will automatically show the date the activity was created.</inlineHelpText>
        <label>Create Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Developmental_Objective__c</fullName>
        <description>Lookup to Objective from Activity

One Objective of an IDP can have mutiple Activity</description>
        <inlineHelpText>Developmental Objective - Select the Objective that your new Activity will be associated with</inlineHelpText>
        <label>Developmental Objective</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2 AND 3) OR 4</booleanFilter>
            <filterItems>
                <field>Developmental_Objective__c.IDP__r.IDP_Status__c</field>
                <operation>equals</operation>
                <value>New, Needs Revision, Resubmit, Approved</value>
            </filterItems>
            <filterItems>
                <field>$User.Id</field>
                <operation>equals</operation>
                <valueField>Developmental_Objective__c.IDP__r.OwnerId</valueField>
            </filterItems>
            <filterItems>
                <field>Developmental_Objective__c.IDP__r.Id</field>
                <operation>equals</operation>
                <valueField>Developmental_Objective__c.IDP__c</valueField>
            </filterItems>
            <filterItems>
                <field>$User.Id</field>
                <operation>equals</operation>
                <valueField>Developmental_Objective__c.IDP__r.Supervisor__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Developmental_Objective__c</referenceTo>
        <relationshipLabel>Developmental Activities</relationshipLabel>
        <relationshipName>Developmental_Activities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Per_Diem__c</fullName>
        <inlineHelpText>Estimated Per Diem - If traveling to fulfill an activity, provide the estimated per diem. Example Format: 1000.</inlineHelpText>
        <label>Estimated Per Diem</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Planned_End_Date__c</fullName>
        <description>Planned End Date for IDP Developmental Activities.</description>
        <inlineHelpText>Planned End Date - Enter the date in which your Activity will end. Example Format: MM/DD/YYYY.</inlineHelpText>
        <label>Planned End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Planned_Start_Date__c</fullName>
        <description>Planned Start Date for IDP Developmental Activities</description>
        <inlineHelpText>Planned Start Date - Enter the date in which your Activity will begin. Example Format: MM/DD/YYYY.</inlineHelpText>
        <label>Planned Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <description>Priority for Training</description>
        <inlineHelpText>Priority - This shows the level of priority for this activity</inlineHelpText>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Required_Date__c</fullName>
        <inlineHelpText>Required Date - The required date is mandatory if the activity is required. Example Format: MM/DD/YYYY.</inlineHelpText>
        <label>Required Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Series__c</fullName>
        <inlineHelpText>Series - The position classification four digit series. (e.g., 0201)</inlineHelpText>
        <label>Series</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Cost__c</fullName>
        <formula>Books_Material_Costs__c+Tuition_Fees__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Total Estimated Cost - This field calculates the total dollar value from the Estimated Tuition &amp; Fees and Estimated Books &amp; Material Costs fields.</inlineHelpText>
        <label>Total Estimated Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Training_Need__c</fullName>
        <description>Required or recommended training</description>
        <inlineHelpText>Is this Activity Required? - Select whether this training is required or recommended</inlineHelpText>
        <label>Is this Activity Required?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Required</fullName>
                </value>
                <value>
                    <fullName>Recommended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tuition_Fees__c</fullName>
        <description>Direct Cost - Tuition &amp; Fees</description>
        <inlineHelpText>Estimated Tuition and Fees - This field represents the estimated tuition and fees that the Activity is expected to cost. Example Format: 2000.</inlineHelpText>
        <label>Estimated Tuition &amp; Fees</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Developmental Activity</label>
    <nameField>
        <displayFormat>DA-{000000}</displayFormat>
        <label>Developmental Activity</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Developmental Activities</pluralLabel>
    <recordTypes>
        <fullName>Activity</fullName>
        <active>true</active>
        <description>Record Type for all the Activities</description>
        <label>Activity</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/IDP_activitySecOnIDPStdPage.cls
public with sharing class IDP_activitySecOnIDPStdPage {

    public String newIDP { get; set; }

    /*public IDP_activitySecOnIDPStdPage() {
        system.debug('-------------------------------------------------------------------------------------------------- Inside Constructor ');
        activityIDPQuerry();
    }*/

    
    public IDP__c currntIDP { get; set; }
    public List<ActivityWrapper> activityWrapperList{ get; set; }
    
    public List<IDP_Developmental_Line_Item__c> activityList = new List<IDP_Developmental_Line_Item__c>();
    
    
    public IDP_activitySecOnIDPStdPage(ApexPages.StandardController controller) {
         system.debug('-------------------------------------------------------------------------------------------------- Inside Constructor ');
         activityIDPQuerry();
    }
    
    public void activityIDPQuerry(){
        // Retrive IDP 
        Id currenIDPId = ApexPages.currentPage().getParameters().get('id');
        system.debug('------------------------------------------------------------------------------- Current IDP Id: ' +currenIDPId );
        String empEmail = UserInfo.getUserEmail();
        currntIDP = new IDP__c();
        currntIDP = [SELECT id, Name, IDP_Status__c 
                     FROM IDP__c
                     WHERE Id = :currenIDPId
                     //WHERE IDP_Status__c = 'New'
                     ORDER By Name DESC
                     LIMIT 1];
        
        //Retrive Activities related to IDP
        activityList = [SELECT id,Name,Priority__c,Total_Cost__c,Assignment_Title__c,Create_Date__c,Planned_Start_Date__c,
                                Training_Need__c,Planned_End_Date__c,Activity_Type__c,Required_Date__c,Series__c,Books_Material_Costs__c,
                                Tuition_Fees__c, Cost_Travel__c, Per_Diem__c, Comments__c, Developmental_Objective__r.Name,  Developmental_Objective__r.Objective__c, 
                                Vendor__c, Location__c, Organization_City__c, RecordTypeId, Related_IDP__c, IDP_ID__c
                        FROM IDP_Developmental_Line_Item__c 
                        WHERE Related_IDP__c = :currntIDP.Name
                        ORDER BY Name ASC];
        system.debug('-------------------------------------------------------------------------------------------------- Activity List Size: ' +activityList.size());                
        prepareActivityWrapperList();
    }
    
    public void prepareActivityWrapperList(){
      List<ActivityWrapper> activityWrapperList = new List<ActivityWrapper>();
      Integer index = 0;
      for(IDP_Developmental_Line_Item__c activity : activityList){
        ActivityWrapper wrapper = new ActivityWrapper(activity,index++);
        activityWrapperList.add(wrapper);
      }
      this.activityWrapperList  = activityWrapperList;
    }
    
    public List<ActivityWrapper> getActivityWrapperList(){
      return activityWrapperList;
    }
    
    public class ActivityWrapper{
      public IDP_Developmental_Line_Item__c activity{get;set;}
      public Integer index{get;set;}
      public Boolean checked{get;set;}
      
      public ActivityWrapper(IDP_Developmental_Line_Item__c activity,Integer index){
        this.activity = activity;
        this.index = index;
        this.checked = false;    
      }
    }
}