src/objects/Exception__c.object
<CustomObject>
    <description>This object is leveraged to store all the exceptions that are generated in the code and needs to be notified to the support group</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Email_Exception__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Email Exception</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Exception_Type__c</fullName>
        <label>Exception Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Exception</label>
    <nameField>
        <label>Exception Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/KBSyncSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>API_Key__c</fullName>
        <label>API Key</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Create_Exception_Record__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Create Exception Record</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_Delta__c</fullName>
        <label>Date Shift</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Email_Exception__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Email Exception</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Page_Size__c</fullName>
        <label>Page Size</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>KBSyncSettings</label>
</CustomObject>

src/classes/GSA_FCIC_ExceptionTest.cls
@isTest
private class GSA_FCIC_ExceptionTest {
	
	static testMethod void createGeneralException() {
		try{
			throw new GSA_FCIC_Exception('Test exception has been thrown');
		} catch(GSA_FCIC_Exception e) {
			e.createExceptionRecord();
		}

		List<Exception__c> exceptions = [Select Id, Description__c, Exception_Type__c from Exception__c];

		system.assertEquals(exceptions.size(),1);
		Exception__c ex = exceptions[0];

		system.assertEquals(ex.Description__c,'Test exception has been thrown');
		system.assertEquals(ex.Exception_Type__c,'GSA_FCIC_Exception');

	}
	
	static testMethod void logGeneralException() {
		try{
			throw new GSA_FCIC_Exception('Test exception has been thrown');
		} catch(GSA_FCIC_Exception e) {
			e.createExceptionRecord(true, false);
		}

		List<Exception__c> exceptions = [Select Id, Description__c, Exception_Type__c from Exception__c];

		system.assertEquals(exceptions.size(),0);
	}

	static testMethod void createKBArticleException() {
		KBSyncSettings__c kbSync = new KBSyncSettings__c(Name='SyncSettings', API_Key__c= '1234',Create_Exception_Record__c= true,  Date_Delta__c = 3,Email_Exception__c = true,Page_Size__c=3);
        insert kbSync ;

		try{
			throw new GSA_FCIC_KBArticles_Exception('Test exception has been thrown');
		} catch(GSA_FCIC_KBArticles_Exception e) {
			e.createExceptionRecord();
		}

		List<Exception__c> exceptions = [Select Id, Description__c, Exception_Type__c from Exception__c];

		system.assertEquals(exceptions.size(),1);
		Exception__c ex = exceptions[0];

		system.assertEquals(ex.Description__c,'Test exception has been thrown');
		system.assertEquals(ex.Exception_Type__c,'GSA_FCIC_KBArticles_Exception');

	}
	
	static testMethod void logKBArticleException() {
		KBSyncSettings__c kbSync = new KBSyncSettings__c(Name='SyncSettings', API_Key__c= '1234',Create_Exception_Record__c= true,  Date_Delta__c = 3,Email_Exception__c = true,Page_Size__c=3);
        insert kbSync ;
		
		try{
			throw new GSA_FCIC_KBArticles_Exception('Test exception has been thrown');
		} catch(GSA_FCIC_KBArticles_Exception e) {
			e.createExceptionRecord(true, false);
		}

		List<Exception__c> exceptions = [Select Id, Description__c, Exception_Type__c from Exception__c];

		system.assertEquals(exceptions.size(),0);
	}


	
}