src/objects/Exception__c.object
<CustomObject>
    <description>This object is leveraged to store all the exceptions that are generated in the code and needs to be notified to the support group</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Email_Exception__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Email Exception</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Exception_Type__c</fullName>
        <label>Exception Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Line_Number__c</fullName>
        <label>Line Number</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Stack_Trace__c</fullName>
        <label>Stack Trace</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Exception</label>
    <nameField>
        <label>Exception Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GSA_FCIC_Exception.cls
public virtual class GSA_FCIC_Exception extends Exception {
	public enum ExceptionType {
		GENERAL,
		KBSYNC,
		CTI
	}	

	public ExceptionType exType;
	private string errorMessage;
    private Exception exeption;

    public virtual void createExceptionRecord(){createExceptionRecord(false, false);}

	public virtual void createExceptionRecord(Boolean logOnly, Boolean emailExceptions) {
		exType = ExceptionType.GENERAL;
		Exception__c exceptionRecord = new Exception__c();
		setExceptionFields(exceptionRecord, emailExceptions);
		if(!logOnly) {
            List<Exception__c> excepRecord = new List<Exception__c>();
            excepRecord.add(exceptionRecord);
			insertExceptionRecord(excepRecord);
		} else {
			outputErrorToLog(exceptionRecord);
		}


	}
	
	protected virtual void setExceptionFields(Exception__c exceptionRecord, Boolean emailExceptions) {
        exceptionRecord.Description__c = this.getMessage();
        exceptionRecord.Stack_Trace__c = this.getStackTraceString();
        exceptionRecord.Line_Number__c = this.getLineNumber();
        exceptionRecord.RecordTypeID = getExceptionRecordTypeId();
        exceptionRecord.Exception_Type__c = this.getTypeName();
        exceptionRecord.Email_Exception__c = emailExceptions;
        exceptionRecord.Name = 'General Exception '+Datetime.now().format();      
    }

    protected void outputErrorToLog(Exception__c exceptionRecord) {
    	System.debug('*******Exception Thrown********');
    	system.debug('Description: '+exceptionRecord.Description__c);
    	system.debug('Stack Trade: '+exceptionRecord.Stack_Trace__c);
    	system.debug('Line Number: '+exceptionRecord.Line_Number__c);
    	system.debug('ExceptionType: '+exceptionRecord.Exception_Type__c);
    	system.debug('Exception Name: '+exceptionRecord.Name);
    	System.debug('*******************************');
    }

    protected void insertExceptionRecord(List<Exception__c> exceptionRecord) {
    	
        try {
            insert exceptionRecord;
        } catch(DmlException e) {
            system.debug('Exception: ' + e.getMessage());
        }
    }

    protected Id getExceptionRecordTypeId() {
    	Schema.RecordTypeInfo rti = Schema.SObjectType.Exception__c.getRecordTypeInfosByName().get(getRecordTypeName());
    	if(rti != null) {
          return rti.getRecordTypeId();
    	} else {
    		return null;
    	}
    }

    protected String getRecordTypeName() {
    	if(exType == ExceptionType.KBSYNC) {
    		return 'KB Sync Failure';
    	} else {
    		return 'General Exception';
    	}
    }
}