src/objects/FedRAMP_Estimated_Days__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>FedRAMP Estimated days for Package Stages</description>
    <fields>
        <fullName>Estimated_Days__c</fullName>
        <label>Estimated Days</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>FedRAMP Estimated Days</label>
</CustomObject>

src/objects/FedRAMP_Package__c.object
<CustomObject>
    <description>Package object for FedRAMP application to track Packages</description>
    <fields>
        <fullName>PATO_Approved_Date__c</fullName>
        <inlineHelpText>Date JAB approves P-ATO</inlineHelpText>
        <label>P-ATO Approved Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Package_Progress__c</fullName>
        <label>Package Progress</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In queue</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Readiness</fullName>
                </value>
                <value>
                    <fullName>SSP</fullName>
                </value>
                <value>
                    <fullName>SAP</fullName>
                </value>
                <value>
                    <fullName>SAR</fullName>
                </value>
                <value>
                    <fullName>ConMon</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>System_Previously_Authorized__c</fullName>
        <description>System Previously Authorized</description>
        <inlineHelpText>Did the CSP have an Agency ATO before coming to FedRAMP?</inlineHelpText>
        <label>System Previously Authorized</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Package</label>
    <nameField>
        <displayFormat>F{YY}{MM}{DD}{0000}</displayFormat>
        <label>Package ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FedRAMP_Package_Stage__c.object
<CustomObject>
    <description>Package Stage object for FedRAMP application to track Stages</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Estimated_Total_Days__c</fullName>
        <label>Estimated Total Days</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Package__c</fullName>
        <label>Package</label>
        <referenceTo>FedRAMP_Package__c</referenceTo>
        <relationshipLabel>Package Stages</relationshipLabel>
        <relationshipName>Package_Stages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Stages__c</fullName>
        <label>Stages</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Readiness</fullName>
                </value>
                <value>
                    <fullName>Kick Off Meeting</fullName>
                </value>
                <value>
                    <fullName>SSP</fullName>
                </value>
                <value>
                    <fullName>SAP</fullName>
                </value>
                <value>
                    <fullName>SAR</fullName>
                </value>
                <value>
                    <fullName>3PAO Testing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>In Process</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Package Stage</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Package Stage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Package Stages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FedRAMP_Stage_Activity__c.object
<CustomObject>
    <description>Stage Activity object for FedRAMP application to track Activities and Events on Package Stages</description>
    <fields>
        <fullName>Actors__c</fullName>
        <label>Actors</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PMO</fullName>
                </value>
                <value>
                    <fullName>ISSO</fullName>
                </value>
                <value>
                    <fullName>JAB</fullName>
                </value>
                <value>
                    <fullName>CSP</fullName>
                </value>
                <value>
                    <fullName>3PAO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Package_Stage__c</fullName>
        <label>Package Stage</label>
        <referenceTo>FedRAMP_Package_Stage__c</referenceTo>
        <relationshipLabel>Stage Activities</relationshipLabel>
        <relationshipName>Stage_Activities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Process</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Stage Activity</label>
    <nameField>
        <displayFormat>SA-{0000}</displayFormat>
        <label>Stage Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stage Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestPackageUtil.cls
/*
    TestPackageUtil.cls
    Tests the PackageUtil.cls
    -------------------------------------------------------------------------------
    Author                 Date        Version  Description
    -------------------------------------------------------------------------------
    Raja Nangunoori       11/18/2013  1.0.00   Re-Design of FedRAMP changes  
*/
//@isTest(seeAllData=true)
@isTest
private class TestPackageUtil {

    static testMethod void PATODate() {
        
        FedRAMP_Estimated_Days__c fedRampEstimatedCustomSettings = new FedRAMP_Estimated_Days__c();
        fedRampEstimatedCustomSettings.Name = '3PAO Testing';
        fedRampEstimatedCustomSettings.Estimated_Days__c = 30;
        insert fedRampEstimatedCustomSettings;
        
        fedRampEstimatedCustomSettings = new FedRAMP_Estimated_Days__c();
        fedRampEstimatedCustomSettings.Name = 'SAR';
        fedRampEstimatedCustomSettings.Estimated_Days__c = 30;
        insert fedRampEstimatedCustomSettings;
        
        fedRampEstimatedCustomSettings = new FedRAMP_Estimated_Days__c();
        fedRampEstimatedCustomSettings.Name = 'SAP';
        fedRampEstimatedCustomSettings.Estimated_Days__c = 15;
        insert fedRampEstimatedCustomSettings;
            
        FedRAMP_Package__c fedPack2 = new FedRAMP_Package__c();
        fedPack2.Package_Progress__c = 'In queue';
        insert fedPack2;
        
        FedRAMP_Package_Stage__c ps = new FedRAMP_Package_Stage__c();
        ps.Stages__c = 'SAR';
        ps.Start_Date__c = date.today();
        ps.End_Date__c = date.today();
        ps.Status__c ='Approved';
        ps.Package__c = fedPack2.Id;
        insert ps;
        
        fedPack2.System_Previously_Authorized__c = 'No';
        fedPack2.PATO_Approved_Date__c = Date.today();
        update fedPack2;
        
        system.assertEquals(true, true);
        
    }
    static testMethod void testPackage(){
        FedRAMP_Package__c fedPack = new FedRAMP_Package__c();
        fedPack.Package_Progress__c = 'In queue';
        insert fedPack;
        
        FedRAMP_Package__c fedPack1 = new FedRAMP_Package__c();
        fedPack1.Package_Progress__c = 'In queue';
        insert fedPack1;
        
        try {
           update fedPack1;   
       }
       catch (DmlException e) {
          System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION', e.getDmlStatusCode(0));
       }
        
        FedRAMP_Package_Stage__c ps = new FedRAMP_Package_Stage__c();
        ps.Stages__c = 'Readiness';
        ps.Start_Date__c = date.today();
        ps.Status__c = 'In Process';
        ps.Package__c = fedPack.Id;
        ps.Estimated_Total_Days__c = 10;
        insert ps;
        
        FedRAMP_Package_Stage__c ps1 = new FedRAMP_Package_Stage__c();
        ps1.Stages__c = 'Readiness';
        ps1.Start_Date__c = date.today();
        ps1.Start_Date__c = date.today();
        ps1.Status__c = 'Approved';
        ps1.Package__c = fedPack.Id;
        ps1.Estimated_Total_Days__c = 20;
        
        FedRAMP_Package_Stage__c ps2 = new FedRAMP_Package_Stage__c();
        ps2.Stages__c = 'Kick Off Meeting';
        ps2.Start_Date__c = date.today();
        ps2.Start_Date__c = date.today();
        ps2.Status__c = 'Approved';
        ps2.Package__c = fedPack.Id;
        ps2.Estimated_Total_Days__c = 20;
        
        try {
           insert ps1;   
           insert ps2;
           update fedPack1;
       }
       catch (DmlException e) {
          System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION', e.getDmlStatusCode(0));
       }

        FedRAMP_Stage_Activity__c sa = new FedRAMP_Stage_Activity__c();
        sa.Actors__c = 'PMO';
        sa.Start_Date__c = date.today();
        sa.Status__c = 'In Process';
        sa.Package_Stage__c = ps.Id;
        insert sa;
        
        FedRAMP_Stage_Activity__c sa1 = new FedRAMP_Stage_Activity__c();
        sa1.Actors__c = 'PMO';
        sa1.Start_Date__c = date.today();
        sa1.Status__c = 'In Process';
        sa1.Package_Stage__c = ps.Id;
        sa1.End_Date__c = date.today();     
        
        try {
           insert sa1;   
       }
       catch (DmlException e) {
          System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION', e.getDmlStatusCode(0));
       }
        update sa;
        update ps;
        system.assertEquals(true, true);
        
        
    }
    static testMethod void testSARStage(){
        FedRAMP_Package__c fedPack = new FedRAMP_Package__c();
        fedPack.Package_Progress__c = 'In queue';
        insert fedPack;
        
        FedRAMP_Package_Stage__c ps = new FedRAMP_Package_Stage__c();
        ps.Stages__c = 'SAR';
        ps.Start_Date__c = date.today();
        ps.Status__c = 'In Process';
        ps.Package__c = fedPack.Id;
        ps.Estimated_Total_Days__c = 10;
        insert ps;
        update fedPack;
        system.assertEquals(true, true);
    }
    static testMethod void testSSPStage(){
        FedRAMP_Package__c fedPack = new FedRAMP_Package__c();
        fedPack.Package_Progress__c = 'In queue';
        insert fedPack;
        
        FedRAMP_Package_Stage__c ps = new FedRAMP_Package_Stage__c();
        ps.Stages__c = 'SSP';
        ps.Start_Date__c = date.today();
        ps.Status__c = 'In Process';
        ps.Package__c = fedPack.Id;
        ps.Estimated_Total_Days__c = 10;
        insert ps;
        
        update fedPack;
        system.assertEquals(true, true);
    }
    static testMethod void testSAPStage(){
        FedRAMP_Package__c fedPack = new FedRAMP_Package__c();
        fedPack.Package_Progress__c = 'In queue';
        insert fedPack;
        
        FedRAMP_Package_Stage__c ps = new FedRAMP_Package_Stage__c();
        ps.Stages__c = 'SAP';
        ps.Start_Date__c = date.today();
        ps.Status__c = 'In Process';
        ps.Package__c = fedPack.Id;
        ps.Estimated_Total_Days__c = 10;
        insert ps;
        
        update fedPack;
        system.assertEquals(true, true);
    }
    static testMethod void testSSPAndSAPStage(){
        FedRAMP_Package__c fedPack = new FedRAMP_Package__c();
        fedPack.Package_Progress__c = 'In queue';
        insert fedPack;
        
        FedRAMP_Package_Stage__c ps = new FedRAMP_Package_Stage__c();
        ps.Stages__c = 'SSP';
        ps.Start_Date__c = date.today();
        ps.Status__c = 'In Process';
        ps.Package__c = fedPack.Id;
        ps.Estimated_Total_Days__c = 10;
        insert ps;
        
        FedRAMP_Package_Stage__c ps1 = new FedRAMP_Package_Stage__c();
        ps1.Stages__c = 'SAP';
        ps1.Start_Date__c = date.today();
        ps1.Status__c = 'In Process';
        ps1.Package__c = fedPack.Id;
        ps1.Estimated_Total_Days__c = 10;
        insert ps1;
        
        update fedPack;
        system.assertEquals(true, true);
    }
    static testMethod void testSSPAndSAPStage1(){
        FedRAMP_Package__c fedPack = new FedRAMP_Package__c();
        fedPack.Package_Progress__c = 'In queue';
        insert fedPack;
        
        FedRAMP_Package_Stage__c ps = new FedRAMP_Package_Stage__c();
        ps.Stages__c = 'SSP';
        ps.Start_Date__c = date.today();
        ps.End_Date__c = date.today();
        ps.Status__c = 'Approved';
        ps.Package__c = fedPack.Id;
        ps.Estimated_Total_Days__c = 10;
        insert ps;
        
        FedRAMP_Package_Stage__c ps1 = new FedRAMP_Package_Stage__c();
        ps1.Stages__c = 'SAP';
        ps1.Start_Date__c = date.today();
        ps1.Status__c = 'In Process';
        ps1.Package__c = fedPack.Id;
        ps1.Estimated_Total_Days__c = 10;
        insert ps1;
        
        update fedPack;
        system.assertEquals(true, true);
    }
    static testMethod void testSSPAndSAPStage2(){
        FedRAMP_Package__c fedPack = new FedRAMP_Package__c();
        fedPack.Package_Progress__c = 'In queue';
        insert fedPack;
        
        FedRAMP_Package_Stage__c ps = new FedRAMP_Package_Stage__c();
        ps.Stages__c = 'SSP';
        ps.Start_Date__c = date.today();
        ps.End_Date__c = date.today();
        ps.Status__c = 'Approved';
        ps.Package__c = fedPack.Id;
        ps.Estimated_Total_Days__c = 10;
        insert ps;
        
        FedRAMP_Package_Stage__c ps1 = new FedRAMP_Package_Stage__c();
        ps1.Stages__c = 'SAP';
        ps1.Start_Date__c = date.today();
        ps1.Status__c = 'Approved';
        ps1.End_Date__c = date.today();
        ps1.Package__c = fedPack.Id;
        ps1.Estimated_Total_Days__c = 10;
        insert ps1;
        
        update fedPack;
        system.assertEquals(true, true);
    }
}