src/objects/Form_SF_182__c.object
<CustomObject>
    <fields>
        <fullName>IDP__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Related IDP - Please select the approved IDP that is related to this SF 182</inlineHelpText>
        <label>Related IDP</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>IDP__c.IDP_Status__c</field>
                <operation>equals</operation>
                <value>Approved, Archived</value>
            </filterItems>
            <filterItems>
                <field>IDP__c.OwnerId</field>
                <operation>equals</operation>
                <valueField>$Source.OwnerId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>IDP__c</referenceTo>
        <relationshipLabel>SF 182</relationshipLabel>
        <relationshipName>Form_SF_182</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>SF 182</label>
    <nameField>
        <displayFormat>SF182 {0000}</displayFormat>
        <label>SF 182 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SF 182</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IDP__c.object
<CustomObject>
    <description>This is a custom object to capture IDPs</description>
    <label>Shared IDPs</label>
    <nameField>
        <displayFormat>IDP-{0000000}</displayFormat>
        <label>IDP Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shared IDPs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IDP_Developmental_Line_Item__c.object
<CustomObject>
    <description>Child object to Developmental Objectives. Used to capture developmental activity line items.</description>
    <label>Developmental Activity</label>
    <nameField>
        <displayFormat>DA-{000000}</displayFormat>
        <label>Developmental Activity</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Developmental Activities</pluralLabel>
    <recordTypes>
        <fullName>Activity</fullName>
        <active>true</active>
        <description>Record Type for all the Activities</description>
        <label>Activity</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SF_182_Training__c.object
<CustomObject>
    <fields>
        <fullName>About_Approvals_Concurrence__c</fullName>
        <defaultValue>&quot;The Approval Process for each SSO/Regions differs.  If you are unaware of the approval chain please leave this section blank and your Supervisor/Approver(s) will add the necessary users for your request. If you are unaware of the &apos;Purchase Card Holder&apos; please leave this field blank, final approver of this request will be required to enter this information.&quot;</defaultValue>
        <label>About Approvals/Concurrence</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>About_the_GSA_Continuing_Srvc_Agreement__c</fullName>
        <defaultValue>&quot;You are required to select the ‘GSA Continuing Service Agreement’ button and accept the terms and conditions when the request&apos;s costs meet or exceed $3,000, or the amount of training hours meet or exceed 80 hours (includes training duty hours and training non duty hours).&quot;</defaultValue>
        <label>About the GSA Continuing Srvc Agreement</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Activity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Activity - Please select the Developmental Activity (from your IDP) that is relevant to this training</inlineHelpText>
        <label>Activity</label>
        <referenceTo>IDP_Developmental_Line_Item__c</referenceTo>
        <relationshipLabel>SF 182 Request</relationshipLabel>
        <relationshipName>SF_182_Trainings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>How_to_Approve_and_Select_Next_Approver__c</fullName>
        <defaultValue>&quot;If you are the ‘Supervisor’ then you should add the next approver in the ‘Approver 1’ field, if you are ‘Approver 1’ then you should add the next approver in the ‘Approver 2’ field, and etc. After reviewing the request  select the ‘Approve/Reject’ link next to your name in the ‘Approval History’ section at the bottom of the page. This will redirect you to the Approval page. Within the Approval page, enter any ‘Comments’ and then select the ‘Approve’ button.&quot;</defaultValue>
        <label>How to Approve and Select Next Approver</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>How_to_Approve_as_a_Final_Approver__c</fullName>
        <defaultValue>&quot;If you are the final approver select ‘Edit’ and add the ‘Purchase Card Holder’ (i.e. the person who will ultimately contact the training vendor for payment and registration) within the &apos;Approvals/Concurrence&apos; section and then select the ‘Final Approver’ checkbox. Select the ‘Approve/Reject’ link next to your name in the ‘Approval History’ section  at the bottom of the page. This will redirect you to the Approval page. Within the Approval page, enter any ‘Comments’ and then select the ‘Approve’ button.&quot;</defaultValue>
        <label>How to Approve as a Final Approver</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>How_to_Cancel_a_Request_Supv_Only__c</fullName>
        <defaultValue>&quot;As a Supervisor, if the requesting user contacts you to cancel their training, follow these steps. The requesting user must recall their request if it is pending another approver&apos;s review (aside from you the Supervisor). After the user recalls the request, select the ‘Cancel Training’ checkbox and Save.&quot;</defaultValue>
        <label>How to Cancel a Request (Supv Only)</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>How_to_Reject_a_Request__c</fullName>
        <defaultValue>&quot;Select the ‘Approve/Reject’ link next to your name in the ‘Approval History’ section  at the bottom of the page. This will redirect you to the Approval/Reject page where you can enter any ‘Comments’ and then select the ‘Reject’ button. The requesting user will be notified about the rejected request. The request can then be changed and re-submitted for the approval process.&quot;</defaultValue>
        <label>How to Reject a Request</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Purchase_Training_Coord_Instructions__c</fullName>
        <defaultValue>&quot;Please review all the details of the requesting user’s training request and contact the training vendor for payment and registration. The ‘Vendor Information’ section includes the contact details for the training vendor. The &apos;Costs and Billing Information - Purchase Card Holder&apos; section is only intended for the Purchase Card Holder to complete. The ‘Training Course Data’ section includes the information regarding the type of training and the ‘Cost and Billing Information - Training Requester’ section details the costs of the requested training.&quot;</defaultValue>
        <label>Purchase Card Holder Instructions</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Requester_Instructions_Activity_Info__c</fullName>
        <defaultValue>&quot;Please select the ‘Activity’ in which you are creating the request for.&quot;</defaultValue>
        <label>Requester Instructions - Activity Info</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Requester_Instructions_Costs_Billing__c</fullName>
        <defaultValue>&quot;Please add the information specific to the costs of your activity / training and enter any specific instructions for the Purchase Card Holder within the ‘Billing Instructions’ field. If cancelled or rejected, the &apos;Grand Total Training Costs&apos; and &apos;Appropriation Fund (Direct Cost)&apos; fields will not be accounted for within the sum of the SF 182&apos;s &apos;Estimated Cumulative Amount&apos;.&quot;</defaultValue>
        <label>Requester Instructions - Costs &amp; Billing</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Requester_Instructions_General_Info__c</fullName>
        <defaultValue>&quot;Complete Activity, Vendor, Training Course Information, Training Codes and Costs sections. The ‘Request Status’ will automatically update based on the ‘Approvals/Concurrence’ section throughout the Approval process. Once training is completed, you should select the &apos;Training Completed&apos; check-box to close out the activity/training request.&quot;</defaultValue>
        <label>Requester Instructions - General Info</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Requester_Instructions_Training_Course__c</fullName>
        <defaultValue>&quot;Please add information specific to your training course by completing the &apos;Training Course Data&apos; and &apos;Training Codes&apos; section.&quot;</defaultValue>
        <label>Requester Instructions - Training Course</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Requester_Instructions_Vendor_Info__c</fullName>
        <defaultValue>&quot;Enter the name of the Vendor providing the training. if you cannot find the vendor using the search, use the &apos;New Vendor&apos; button to create the vendor. Additional reference material on how to create a new Vendor can be found on the IDP Resources section of the IDP Launch page.&quot;</defaultValue>
        <label>Requester Instructions - Vendor Info</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SF_182__c</fullName>
        <inlineHelpText>SF 182 - Auto generated name of the corresponding SF 182 page; select this field&apos;s link to go back to the SF 182 page where general information about the employee is stored</inlineHelpText>
        <label>SF 182</label>
        <referenceTo>Form_SF_182__c</referenceTo>
        <relationshipLabel>SF 182 Request</relationshipLabel>
        <relationshipName>SF_182_Trainings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Supervisor_Approver_Instructions__c</fullName>
        <defaultValue>&quot;Please review all the training request details listed below. It is important to note that the ‘Training Course Data’ and the  ‘Cost and Billing Information - Training Requester’ sections are properly completed before you approve this request.&quot;</defaultValue>
        <label>Supervisor/Approver Instructions</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Training_Vendor_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Training Vendor Name - Please select the name of the vendor that will be providing the training (i.e. Strayer University); if they are not listed within the system please add them using the &apos;Contact Mgr&apos; application: https://gsa.my.salesforce.com/001/o</inlineHelpText>
        <label>Training Vendor Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>contains</operation>
                <value>Vendor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>SF 182 Request</relationshipLabel>
        <relationshipName>SF_182_Trainings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SF 182 Request</label>
    <nameField>
        <displayFormat>SF-Training-{000000}</displayFormat>
        <label>SF 182 Training Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SF 182 Request</pluralLabel>
    <recordTypes>
        <fullName>Purchasing_Training_Coordinator</fullName>
        <active>true</active>
        <description>This is Record Type useful for the Purchasing and Training coordinator to enter the details</description>
        <label>SF 182 Purchase Card Holder</label>
    </recordTypes>
    <recordTypes>
        <fullName>SF_182_Training_Completed</fullName>
        <active>true</active>
        <label>SF 182 Training Completed</label>
    </recordTypes>
    <recordTypes>
        <fullName>SF_182_Training_RecordType</fullName>
        <active>true</active>
        <label>SF 182 Training Request</label>
    </recordTypes>
    <recordTypes>
        <fullName>Sf_182_Approver_RecordType</fullName>
        <active>true</active>
        <label>SF 182 Approval Process</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/IDP_SF182RequestEditController.cls
public with sharing class IDP_SF182RequestEditController {

	/*
		:::Record Type API Name:::					:::Record Type Label Name:::				:::Page Layout Assigned:::
		Sf_182_Approver_RecordType					SF 182 Approval Process						SF 182 Approver Layout
		Purchasing_Training_Coordinator				SF 182 Purchase Card Holder					Purchasing Training Coordinator
		SF_182_Training_Completed					SF 182 Training Completed 					SF 182 Training Completed
		SF_182_Training_RecordType					SF 182 Training Request 					SF 182 Training Layout

		Master Layout == SF 182 Training Layout
	*/
	public final String DEFAULT_RECORD_TYPE = 'SF 182 Training Request';
	//private final String NO_ACTIVITY_ERROR_MESSAGE = 'Please select a valid activity before saving.';
	private final String NO_ACTIVITY_ERROR_MESSAGE = 'The activity you selected is not on the IDP you identified for this SF182. Please update your SF182 to correct the IDP or the activity.';
	private final String NO_ACTIVITY_SELECTED = 'Please select an Activity';
	public boolean isApprover {get; set;}
	public String recordTypeName {get; set;}
	public String currentUserName {get; set;}
	public String selectedActivityName {get; set;}
	public String sf182Name {get; set;}
	public boolean displayPopupVendor {get; set;}
	public boolean displayPopupActivity {get; set;}
	public Id activityId {get; set;}
	public SF_182_Training__c newSF182Request {get; set;}
	public Account newVendor {get; set;}
	public List<IDP_Developmental_Line_Item__c> activityListForSelection {get; set;}
	public String todaysDate {get; set;}
	public String instrRequestor {get; set;}
	public String instrContinuingSvc {get; set;}
	public String instrPurchaseTrainingCoord {get; set;}
	public String instrSupervisorApprover {get; set;}
	public String instrActivityInfo {get; set;}
	public String instrVendorInfo {get; set;}
	public String instrTrainingCourse {get; set;}
	public String instrCostBilling {get; set;}
	public String instrApproveSelectApprover {get; set;}
	public String instrApproveFinalApprover {get; set;}
	public String instrAboutApprovalsConcurrence {get; set;}
	public String instrRejectRequest {get; set;}
	public String instrCancelRequestSupv {get; set;}
	public String pageId {get; set;}

	public IDP_SF182RequestEditController(ApexPages.StandardController stdController){
		setInstructions();
		
		// grab the record FIRST
		newSF182Request = (SF_182_Training__c) stdController.getRecord();
		checkIfEditable();
		
		// at this point we should be good to assign a layout / rendering solution
		pageId = ApexPages.currentPage().getParameters().get('RecordType');
		assignRecordTypeInformation();

		// this populates the string field associated with the Activity popup
		getActivityName();

		newVendor = new Account();

		currentUserName = UserInfo.getName(); 
		
		Datetime myDate = Datetime.now();
		todaysDate = myDate.format('MM/dd/yyyy');
		 
		System.debug('newSF182Request is ' + newSF182Request);
	}

	private void checkIfEditable(){
		List<ProcessInstance> piList = [SELECT Id, (SELECT Id, ActorId, StepStatus FROM StepsAndWorkItems WHERE ActorId =: UserInfo.getUserId()) 
			FROM ProcessInstance 
			WHERE TargetObjectId =: newSF182Request.Id 
				AND Status = 'Pending'];
		if(piList.isEmpty()) {
			isApprover = true;
			return;
		} else {
			for(ProcessInstance pi : piList){
				for(ProcessInstanceHistory history : pi.StepsAndWorkItems){
					if(history.ActorId == UserInfo.getUserId() && history.StepStatus == 'Pending') {
						isApprover = true;
						return;
					}
				}
			}
			isApprover = false;
		}
	}
	
	private void setInstructions(){
		Schema.DescribeFieldResult dfr1 = SF_182_Training__c.Requester_Instructions_General_Info__c.getDescribe();
		instrRequestor = String.valueOf(dfr1.getDefaultValueFormula());
		instrRequestor = instrRequestor.substring(1, instrRequestor.length() - 1);

		Integer i = 0;
		i++;
		i++;
		
		Schema.DescribeFieldResult dfr2 = SF_182_Training__c.About_the_GSA_Continuing_Srvc_Agreement__c.getDescribe();
		instrContinuingSvc = String.valueOf(dfr2.getDefaultValueFormula());
		instrContinuingSvc = instrContinuingSvc.substring(1, instrContinuingSvc.length() - 1);		

		Schema.DescribeFieldResult dfr3 = SF_182_Training__c.Purchase_Training_Coord_Instructions__c.getDescribe();
		instrPurchaseTrainingCoord = String.valueOf(dfr3.getDefaultValueFormula());
		instrPurchaseTrainingCoord = instrPurchaseTrainingCoord.substring(1, instrPurchaseTrainingCoord.length() - 1);

		i++;
		i++;

		Schema.DescribeFieldResult dfr4 = SF_182_Training__c.Supervisor_Approver_Instructions__c.getDescribe();
		instrSupervisorApprover = String.valueOf(dfr4.getDefaultValueFormula());
		instrSupervisorApprover = instrSupervisorApprover.substring(1, instrSupervisorApprover.length() - 1);

		Schema.DescribeFieldResult dfr5 = SF_182_Training__c.Requester_Instructions_Activity_Info__c.getDescribe();
		instrActivityInfo = String.valueOf(dfr5.getDefaultValueFormula());
		instrActivityInfo = instrActivityInfo.substring(1, instrActivityInfo.length() - 1);

		i++;
		i++;

		Schema.DescribeFieldResult dfr6 = SF_182_Training__c.Requester_Instructions_Vendor_Info__c.getDescribe();
		instrVendorInfo = String.valueOf(dfr6.getDefaultValueFormula());
		instrVendorInfo = instrVendorInfo.substring(1, instrVendorInfo.length() - 1);

		Schema.DescribeFieldResult dfr7 = SF_182_Training__c.Requester_Instructions_Training_Course__c.getDescribe();
		instrTrainingCourse = String.valueOf(dfr7.getDefaultValueFormula());
		instrTrainingCourse = instrTrainingCourse.substring(1, instrTrainingCourse.length() - 1);

		i++;
		i++;

		Schema.DescribeFieldResult dfr8 = SF_182_Training__c.Requester_Instructions_Costs_Billing__c.getDescribe();
		instrCostBilling = String.valueOf(dfr8.getDefaultValueFormula());
		instrCostBilling = instrCostBilling.substring(1, instrCostBilling.length() - 1);

		Schema.DescribeFieldResult dfr9 = SF_182_Training__c.How_to_Approve_and_Select_Next_Approver__c.getDescribe();
		instrApproveSelectApprover = String.valueOf(dfr9.getDefaultValueFormula());
		instrApproveSelectApprover = instrApproveSelectApprover.substring(1, instrApproveSelectApprover.length() - 1);

		i++;
		i++;
				
		Schema.DescribeFieldResult dfr10 = SF_182_Training__c.How_to_Approve_as_a_Final_Approver__c.getDescribe();
		instrApproveFinalApprover = String.valueOf(dfr10.getDefaultValueFormula());
		instrApproveFinalApprover = instrApproveFinalApprover.substring(1, instrApproveFinalApprover.length() - 1);
				
		Schema.DescribeFieldResult dfr11 = SF_182_Training__c.How_to_Reject_a_Request__c.getDescribe();
		instrRejectRequest = String.valueOf(dfr11.getDefaultValueFormula());
		instrRejectRequest = instrRejectRequest.substring(1, instrRejectRequest.length() - 1);		

		i++;
		i++;
				
		Schema.DescribeFieldResult dfr12 = SF_182_Training__c.How_to_Cancel_a_Request_Supv_Only__c.getDescribe();
		instrCancelRequestSupv = String.valueOf(dfr12.getDefaultValueFormula());
		instrCancelRequestSupv = instrCancelRequestSupv.substring(1, instrCancelRequestSupv.length() - 1);			
		
		Schema.DescribeFieldResult dfr13 = SF_182_Training__c.About_Approvals_Concurrence__c.getDescribe();
		instrAboutApprovalsConcurrence = String.valueOf(dfr13.getDefaultValueFormula());
		instrAboutApprovalsConcurrence = instrAboutApprovalsConcurrence.substring(1, instrAboutApprovalsConcurrence.length() - 1);		

		i++;
		i++;	
		System.debug(i);	
	
	}

	public void assignRecordTypeInformation(){
		if(newSF182Request.RecordTypeId == null && pageId == null) {
			RecordType recordTypeObj = [SELECT Id, Name FROM RecordType WHERE SobjectType = 'SF_182_Training__c' AND Name =: DEFAULT_RECORD_TYPE];
			newSF182Request.RecordTypeId = recordTypeObj.Id;
			recordTypeName = DEFAULT_RECORD_TYPE;

		} else if (newSF182Request.RecordTypeId != null) {
			RecordType recordTypeObj = [SELECT Id, Name FROM RecordType WHERE SobjectType = 'SF_182_Training__c' AND Id =: newSF182Request.RecordTypeId];
			recordTypeName = recordTypeObj.Name;

		} else if (pageId != null){
			RecordType recordTypeObj = [SELECT Id, Name FROM RecordType WHERE SobjectType = 'SF_182_Training__c' AND Id =: pageId];
			newSF182Request.RecordTypeId = recordTypeObj.Id;
			recordTypeName = recordTypeObj.Name;

		}

	}

	public PageReference save(){
		if(!checkIfActivityIsValid()) return null;
		try {
			upsert newSF182Request;
			PageReference redirectPage = new PageReference('/apex/IDP_SF182RequestDetail?id=' + newSF182Request.Id);
			redirectPage.setRedirect(true);
			return redirectPage;
		} catch (DmlException e){
			String errorMessage = e.getDmlMessage(0);
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, errorMessage));
			return null;
		}
	}

	public PageReference saveAndNew(){
		if(!checkIfActivityIsValid()) return null;
		try {
			upsert newSF182Request;
			PageReference redirectPage = new PageReference('/apex/IDP_SF182RequestEdit');
			redirectPage.setRedirect(true);
			return redirectPage;
		} catch (DmlException e){
			String errorMessage = e.getDmlMessage(0);
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, errorMessage));
			return null;
		}
	}

	public void showPopupVendor() {
		displayPopupVendor = true;
		newVendor = new Account();
	}

	public void closePopupVendor() {
		displayPopupVendor = false;
	}

	public void showPopupActivity(){
		// CLCNEW START
		if(sf182Name != null) {
			getRelatedActivities();
			displayPopupActivity = true;
		} else {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Please select an SF 182 before choosing an activty.'));
		}
		// CLCNEW END
	}

	public void closePopupActivity(){
		displayPopupActivity = false;
	}

	public void createNewVendor(){
		if(newVendor.Name == null) {
			closePopupVendor();
			return;
		}
		closePopupVendor();
		newVendor.RecordTypeId = getVendorRecordId();
		// CLCNEW START
		try {
			insert newVendor;
			newSF182Request.Training_Vendor_Name__c = newVendor.Id;
		} catch (DmlException e) {
			String errorMessage = e.getDmlMessage(0);
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, errorMessage));
		}
		// CLCNEW END
	}

	private Id getVendorRecordId(){
		return [SELECT Id FROM RecordType WHERE SobjectType = 'Account' AND  Name = 'Vendor'].Id;
	}

	private boolean checkIfActivityIsValid(){
		Form_SF_182__c tempSF182 = IDP_SF182RequestEditControllerHelper.getSF182(newSF182Request.SF_182__c);			

		List<IDP_Developmental_Line_Item__c> validActivities = IDP_SF182RequestEditControllerHelper.getActivities(tempSF182.Idp__c);
			
		if(validActivities.size() == 0) {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, NO_ACTIVITY_ERROR_MESSAGE));
			return false;
		}
				

		for(IDP_Developmental_Line_Item__c activity : validActivities){
			if(activity.Name == selectedActivityName) return true;
		}
		system.debug('No Activity === ' + selectedActivityName);
		if(selectedActivityName == ''){
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'NO_ACTIVITY_SELECTED'));
			return false;
		} else {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, NO_ACTIVITY_ERROR_MESSAGE));
			return false;
		}
		return false;
	}
	
	private void getRelatedActivities(){
		Form_SF_182__c tempSF182 = IDP_SF182RequestEditControllerHelper.getSF182(sf182Name);
		activityListForSelection = IDP_SF182RequestEditControllerHelper.getActivities(tempSF182.Idp__c);
	}

	public void selectActivityFiltered(){
		displayPopupActivity = false;
		newSF182Request.Activity__c = activityId;
	}

	public void getActivityName(){
		SF_182_Training__c tempSF182Request;
		if(newSF182Request.Id != null) {
			tempSF182Request = [SELECT Id, Activity__c FROM SF_182_Training__c WHERE Id =: newSF182Request.Id];
			if(tempSF182Request.Activity__c != null){
				//IDP_Developmental_Line_Item__c activity = [SELECT Id, Name FROM IDP_Developmental_Line_Item__c WHERE Id =: tempSF182Request.Activity__c];
				//selectedActivityName = activity.Name;
				selectedActivityName = IDP_SF182RequestEditControllerHelper.getActivityName(tempSF182Request.Activity__c);
			}
		}
	}

}