src/objects/Form_SF_182__c.object
<CustomObject>
    <fields>
        <fullName>IDP__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Related IDP - Please select the approved IDP that is related to this SF 182</inlineHelpText>
        <label>Related IDP</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>IDP__c.IDP_Status__c</field>
                <operation>equals</operation>
                <value>Approved, Archived</value>
            </filterItems>
            <filterItems>
                <field>IDP__c.OwnerId</field>
                <operation>equals</operation>
                <valueField>$Source.OwnerId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>IDP__c</referenceTo>
        <relationshipLabel>SF 182</relationshipLabel>
        <relationshipName>Form_SF_182</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>SF 182</label>
    <nameField>
        <displayFormat>SF182 {0000}</displayFormat>
        <label>SF 182 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SF 182</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IDP__c.object
<CustomObject>
    <description>This is a custom object to capture IDPs</description>
    <fields>
        <fullName>IDP_Status__c</fullName>
        <description>IDP Status</description>
        <inlineHelpText>IDP Status - This field indicates where your IDP stands (i.e. New, Supervisor Review, Needs Revision, Approved, Resubmit, Archived)</inlineHelpText>
        <label>IDP Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Supervisor Review</fullName>
                </value>
                <value>
                    <fullName>Needs Revision</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Resubmit</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Shared IDPs</label>
    <nameField>
        <displayFormat>IDP-{0000000}</displayFormat>
        <label>IDP Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shared IDPs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestIdpTrigger.cls
@isTest
private class TestIdpTrigger {

    static testMethod void myUnitTest() {
 
        
        List<IDP__c> idp = IDP_TestDataFactory.createTestIDPRecords(2,'FY 2050','New','Team Lead',
                                                    'Manager','IDP Standard','GSA Standard Salesforce User');
        idp[0].IDP_Status__c='Approved';
        update idp[0];
        idp[1].IDP_Status__c='Approved';
        update idp[1];
       List<IDP__c> idp1 = IDP_TestDataFactory.createTestIDPRecords(1,'FY 2050','New','Team Lead',
                                                    'Manager','IDP Standard','GSA Standard Salesforce User'); 
        idp1[0].IDP_Status__c='Supervisor Review';
        update idp1[0];

        
       List<Form_SF_182__c> sf182 = IDP_TestDataFactory.createsfoneeightytwo(idp,1);
        
        system.assert(idp != null);
                               

    }
    
    static testMethod void supervisorApproval() {
        
        List<IDP__c> idp2 = IDP_TestDataFactory.createTestIDPRecords(1,'FY 2050','New','Team Lead',
                                                    'Manager','IDP Standard','GSA Standard Salesforce User');

     
        
        system.assert(idp2 != null);
                               

    }
}