src/objects/Form_SF_182__c.object
<CustomObject>
    <fields>
        <fullName>SF_182_Instructions__c</fullName>
        <defaultValue>&quot;Please complete the fields below; the help text will guide you on what information is needed within each of the fields. Once you have completed the information, select &apos;Save&apos;. After saving, select the &apos;New SF 182 Request&apos; button which will redirect you to where you can complete your request and then submit it for training, approval, registration and payment. IMPORTANT :  You should ONLY create one &apos;SF 182&apos; per IDP, but you should create a new &apos;SF 182 Request&apos; for each activity / training.&quot;</defaultValue>
        <label>Requesting User - SF 182 Instructions</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Supervisor_SF_182_Instructions__c</fullName>
        <defaultValue>&quot;The ‘SF 182 Request’ section (located at the bottom of this page) lists all the users requests for the chosen FY.                                Please note that &apos;Estimated Cumulative Amount&apos; field contains the sum of the  &apos;Grand Total Training Costs&apos; from each Training Request(s) and the &apos;Actual Cumulative Amount&apos; field contains the sum of the &apos;Appropriation Fund (Direct Cost)&apos; from each Training Request(s). Costs for training that is rejected, cancelled and no money was obligated or if money was obligated but is refundable will not be included in the totals. You can use the‘Supervisor Comments’ field to provide feedback for the requesting user.&quot;</defaultValue>
        <label>Supervisor - SF 182 Instructions</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>SF 182</label>
    <nameField>
        <displayFormat>SF182 {0000}</displayFormat>
        <label>SF 182 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SF 182</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/IDP_SF182EditController.cls
public with sharing class IDP_SF182EditController {

	public String instr {get; set;}
	public String instrSupervisor {get; set;}
	
	public IDP_SF182EditController(ApexPages.StandardController stdController){
		Schema.DescribeFieldResult dfr = Form_SF_182__c.SF_182_Instructions__c.getDescribe();
		instr = String.valueOf(dfr.getDefaultValueFormula());
		instr = instr.substring(1, instr.length() - 1);

		Schema.DescribeFieldResult dfr_sprv = Form_SF_182__c.Supervisor_SF_182_Instructions__c.getDescribe();
		instrSupervisor = String.valueOf(dfr_sprv.getDefaultValueFormula());
		instrSupervisor = instrSupervisor.substring(1, instrSupervisor.length() - 1);

	}

}