src/objects/GalaxyReconciliationBatch__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>The Reconciliation jobs are run in a sequence. The finish method of the first job will schedule the next job. Since the job will still remain active in the system, we will see the error message about scheduling a job that is already existing. We will use this  field to delete the job as soon as we’re done executing that step in the process.</description>
    <fields>
        <fullName>Apex_Jobs_Run_Date__c</fullName>
        <description>The Date when all APEX jobs finished executing ...</description>
        <label>Apex Jobs Run Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CustomRunDate__c</fullName>
        <defaultValue>Null</defaultValue>
        <label>Custom Run Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Schedule6_ID__c</fullName>
        <defaultValue>&apos;0&apos;</defaultValue>
        <label>Schedule6 ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>GalaxyReconciliationBatch</label>
</CustomObject>

src/objects/Glxy_Lease__c.object
<CustomObject>
    <customHelpPage>GLXY_HelpPage</customHelpPage>
    <description>This table contains lease information at the beginning of the fiscal year.  This information is updated at the beginning of each fiscal year.</description>
    <fields>
        <fullName>BaseAnnualRent__c</fullName>
        <inlineHelpText>Be sure to click save to adjust monthly impact.</inlineHelpText>
        <label>Base Annual Rent</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BaseLeaseEffectiveDate__c</fullName>
        <label>Lease Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ExpirationDateofLease__c</fullName>
        <description>Expiration Date</description>
        <label>Lease Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>REXUSStatusCode__c</fullName>
        <label>Rexus Status Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RegionCD__c</fullName>
        <description>Region Code</description>
        <label>Region Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StatusCode__c</fullName>
        <description>Status Code</description>
        <inlineHelpText>Current status of during G2 Base Sertting period. Options are Active, Terminated, Pending.
DL	Deleted
PD	Pending
TM	Terminated
AC	Active</inlineHelpText>
        <label>Status Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_IA_Sq_feet__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total IA Sq ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_NOA_Sq_feet__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total NOA Sq ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Lease</label>
    <nameField>
        <label>Lease Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Glxy_LeaseLocation__c.object
<CustomObject>
    <description>This table contains the Building information for each lease.  One lease can have multiple buildings assocated with it.</description>
    <fields>
        <fullName>BuildingNumber__c</fullName>
        <label>Building Number</label>
        <referenceTo>PBS_Building__c</referenceTo>
        <relationshipLabel>LeaseLocations</relationshipLabel>
        <relationshipName>LeaseLocations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LeaseNumber__c</fullName>
        <label>Lease Number</label>
        <referenceTo>Glxy_Lease__c</referenceTo>
        <relationshipName>LeaseLocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Location_Code__c</fullName>
        <formula>BuildingNumber__r.Location_Code_Plus__c</formula>
        <label>Location Code</label>
        <type>Text</type>
    </fields>
    <label>Lease Location</label>
    <nameField>
        <displayFormat>LOC-{00000000}</displayFormat>
        <label>Lease Location ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lease Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Glxy_Reconciliation__c.object
<CustomObject>
    <description>This table contains snap shot of Lease data by month</description>
    <fields>
        <fullName>BuildingNumber__c</fullName>
        <label>Building Number</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LeaseNumberMonth__c</fullName>
        <externalId>true</externalId>
        <label>Lease Number Month</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LeaseNumber__c</fullName>
        <label>Lease Number</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RegionCD__c</fullName>
        <label>Region Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StatusCode__c</fullName>
        <description>Status Code</description>
        <inlineHelpText>DL Deleted
PD Pending
TM Terminated
AC Active</inlineHelpText>
        <label>Status Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Galaxy Reconciliation</label>
    <nameField>
        <displayFormat>RE-{0000000000}</displayFormat>
        <label>Galaxy Reconciliation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Galaxy Reconciliation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PBS_Building__c.object
<CustomObject>
    <description>PBS Common Building Object</description>
    <fields>
        <fullName>Building_ID__c</fullName>
        <externalId>true</externalId>
        <label>Building ID</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Location_Code_Plus__c</fullName>
        <externalId>true</externalId>
        <label>Location Code Plus</label>
        <length>8</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>PBS Building</label>
    <nameField>
        <displayFormat>PBS-BLDG-{000000000}</displayFormat>
        <label>PBS Building Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PBS Buildings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GLXY_ReconciliationLocationsUpdate.cls
global with sharing class GLXY_ReconciliationLocationsUpdate implements Database.Batchable<sObject>,Database.stateful{
	
	global List<Glxy_Reconciliation__c> objReconciliationUpdatedRecords = New List<Glxy_Reconciliation__c>();
	global Date dtProcessRunDate = Datetime.Now().Date().addMonths(-1);
	global string strCurrentMonth = String.valueOf(dtProcessRunDate.Month());
		
	global Database.QueryLocator start(Database.BatchableContext BC){
		//Galaxy 2.2 - Provide capability to run the process for previous months
   		GalaxyReconciliationBatch__c objCustomSettings1 = GalaxyReconciliationBatch__c.getOrgDefaults();
   		if (objCustomSettings1.CustomRunDate__c != null){
   			dtProcessRunDate = objCustomSettings1.CustomRunDate__c.addMonths(-1);
   			strCurrentMonth = String.valueOf(dtProcessRunDate.Month());
   		}
   		//Galaxy 2.2 - Provide capability to run the process for previous months
		string QueryAllLocations =  'SELECT LeaseNumber__r.Name, Location_Code__c ' +
	 	 						 	'FROM   Glxy_LeaseLocation__c  ' + 
	 	 						 	'Where  LeaseNumber__r.REXUSStatusCode__c  = \'Active\' ' + 
	 	 						 	'ORDER BY LeaseNumber__r.Name ';
	 	//System.Debug('MyDebug = ' + QueryAllLocations); 						 
	 	Return Database.getQueryLocator(QueryAllLocations);
	}
	
	global void execute(Database.BatchableContext BC, List<sObject> scope){
		objReconciliationUpdatedRecords.Clear();
		string strLoopCurrentLease;
		string strLoopPreviousLease = '-';
		string strBuildingIDs = '';
		boolean blnHasData = false;
		
		Glxy_LeaseLocation__c objLeaseLocation = null;
		for(sObject obj: scope) {
			blnHasData = true;
			objLeaseLocation = (Glxy_LeaseLocation__c) obj;
			strLoopCurrentLease = objLeaseLocation.LeaseNumber__r.Name;
			if ((strLoopCurrentLease <> strLoopPreviousLease) && (strLoopPreviousLease <> '-')){
				if (strBuildingIDs.LastIndexOf(',') > 0)
					strBuildingIDs = strBuildingIDs.Left(strBuildingIDs.LastIndexOf(','));
				objReconciliationUpdatedRecords.Add(new Glxy_Reconciliation__c(
            		LeaseNumberMonth__c = strCurrentMonth + strLoopPreviousLease,
                	BuildingNumber__c = strBuildingIDs
            	));
            	strBuildingIDs = '';	
			}
			strBuildingIDs = strBuildingIDs + objLeaseLocation.Location_Code__c + ',';
			strLoopPreviousLease = strLoopCurrentLease;
        } 
		
		if (blnHasData = true){
			if (strBuildingIDs.LastIndexOf(',') > 0)
				strBuildingIDs = strBuildingIDs.Left(strBuildingIDs.LastIndexOf(','));
			objReconciliationUpdatedRecords.Add(new Glxy_Reconciliation__c(
        		LeaseNumberMonth__c = strCurrentMonth + strLoopPreviousLease,
            	BuildingNumber__c = strBuildingIDs
        	));
		}
		
		try{	
        	Database.UpsertResult[] results = Database.Upsert(objReconciliationUpdatedRecords, Schema.Glxy_Reconciliation__c.LeaseNumberMonth__c, false);
	 	}catch (DmlException e){
        	System.debug('GLXY_ReconciliationLocationsUpdate Upsert error - ' + e.getMessage());
    	}
	}
	
	global void finish(Database.BatchableContext BC){
		//Delete this job from Scheduled Jobs ...
		GalaxyReconciliationBatch__c objCustomSettings = GalaxyReconciliationBatch__c.getOrgDefaults();
		try{	
        	System.abortJob(objCustomSettings.Schedule6_ID__c);
	 	}catch (Exception e){
        	System.debug('GLXY_ReconciliationLocationsUpdate Job Delete error - ' + e.getMessage());
    	}
		// Update the Process Completion Date ...
		GalaxyReconciliationBatch__c objCustomSettings2 = GalaxyReconciliationBatch__c.getOrgDefaults();
   		objCustomSettings2.Apex_Jobs_Run_Date__c = datetime.now();
   		objCustomSettings2.CustomRunDate__c = Null;//G2 Release 2.2 - If it was scheduled for a particular month, clear the month off; 
   		try{	
        	Update objCustomSettings2;
	 	}catch (Exception e){
        	System.debug('GLXY_ReconciliationLocationsUpdate Job Create error - ' + e.getMessage());
    	}
	}
  	
  	 static testMethod void testClass(){
  	 	
  	 	Glxy_Lease__c objleaseEntry = new Glxy_Lease__c(
 	  	 	StatusCode__c='Active',
 	  	 	REXUSStatusCode__c='Active',
	   		BaseLeaseEffectiveDate__c=Datetime.Now().Date(),
	 		ExpirationDateofLease__c=Datetime.Now().Date(),
	 		RegionCD__c='11',
	 		Total_NOA_Sq_feet__c=4444,
	 		Total_IA_Sq_feet__c=3333333,
	  		name='testte',
	 		BaseAnnualRent__c =2222);
 		insert objleaseEntry;
		System.Assert(objleaseEntry!=NULL);
		
		Glxy_Lease__c objleaseEntry2 = new Glxy_Lease__c(
 	  	 	StatusCode__c='Active',
 	  	 	REXUSStatusCode__c='Active',
	   		BaseLeaseEffectiveDate__c=Datetime.Now().Date(),
	 		ExpirationDateofLease__c=Datetime.Now().Date(),
	 		RegionCD__c='11',
	 		Total_NOA_Sq_feet__c=4444,
	 		Total_IA_Sq_feet__c=3333333,
	  		name='testte2',
	 		BaseAnnualRent__c =2222);
 		insert objleaseEntry2;
		System.Assert(objleaseEntry2!=NULL);
		
		PBS_Building__c objBuildingEntry = new PBS_Building__c(
 	  	 	Location_Code_Plus__c = 'DC0021ZZ',
 	  	 	Building_ID__c = 123);
 		insert objBuildingEntry;
 		System.Assert(objBuildingEntry!=NULL);
 		
 		PBS_Building__c objBuildingEntry2 = new PBS_Building__c(
 	  	 	Location_Code_Plus__c = 'DC0022ZZ',
 	  	 	Building_ID__c = 12334);
 		insert objBuildingEntry2;
 		System.Assert(objBuildingEntry2!=NULL);
 		
  	 	Glxy_Lease__c objLease = [Select id from Glxy_Lease__c Limit 1];
  	 	PBS_Building__c objBuilding = [Select id from PBS_Building__c Limit 1];
  	 	
  	 	Glxy_LeaseLocation__c objLeaseLocation = new Glxy_LeaseLocation__c (
            LeaseNumber__c = objLease.id,
            BuildingNumber__c = objBuilding.id
        );
        insert objLeaseLocation;
 		
 		Glxy_LeaseLocation__c objLeaseLocation2 = new Glxy_LeaseLocation__c (
            LeaseNumber__c = objleaseEntry2.id,
            BuildingNumber__c = objBuildingEntry2.id
        );
        insert objLeaseLocation2;

    	Test.startTest();     
    	GLXY_ReconciliationLocationsUpdate objTest = new GLXY_ReconciliationLocationsUpdate();
    	Database.executeBatch(objTest);      
    	Test.stopTest();     
    }  
}