src/objects/Galaxy_Snapshot__c.object
<CustomObject>
    <fields>
        <fullName>Snapshot_Date__c</fullName>
        <defaultValue>DATEVALUE(Now())</defaultValue>
        <inlineHelpText>The system will make a data snapshot on the data specified</inlineHelpText>
        <label>Snapshot Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&quot;Scheduled&quot;</defaultValue>
        <label>Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Galaxy Snapshot</label>
    <nameField>
        <label>Galaxy Snapshot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Galaxy Snapshot</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Glxy_AssociatedLeases__c.object
<CustomObject>
    <fields>
        <fullName>DoubleRentIA__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Double Rent IA</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>DoubleRentNOA__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Double Rent NOA</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Double_Rent__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Double Rent</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LeaseExpiration_lkp__c</fullName>
        <formula>Lease__r.ExpirationDateofLease__c</formula>
        <inlineHelpText>The expiration date of the lease in REXUS</inlineHelpText>
        <label>Lease Expiration</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Effective_Date__c</fullName>
        <formula>Project__r.EffectiveDate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project Number</label>
        <referenceTo>Glxy_LeaseProjects__c</referenceTo>
        <relationshipLabel>Associated Leases/Projects</relationshipLabel>
        <relationshipName>Associated_Leases</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Associated Leases/Projects</label>
    <nameField>
        <displayFormat>LP-{00000}</displayFormat>
        <label>Associated Leases</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Leases/Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Glxy_DoubleRent__c.object
<CustomObject>
    <fields>
        <fullName>Associated_Leases_Projects_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Associated Leases/Projects</label>
        <referenceTo>Glxy_AssociatedLeases__c</referenceTo>
        <relationshipLabel>Double Rents</relationshipLabel>
        <relationshipName>Double_Rents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FY_Obligation_IA__c</fullName>
        <formula>Apr_IA__c + May_IA__c + Jun_IA__c + Jul_IA__c + Aug_IA__c + Sep_IA__c + Oct_IA__c + Nov_IA__c + Dec_IA__c + JAN_IA__c + Feb_IA__c + Mar_IA__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>FY Obligation IA</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FY_Obligation_NOA__c</fullName>
        <formula>Apr_NOA__c + May_NOA__c + Jun_NOA__c + Jul_NOA__c + Aug_NOA__c + Sep_NOA__c + Oct_NOA__c + Nov_NOA__c + Dec_NOA__c + JAN_NOA__c + Feb_NOA__c + Mar_NOA__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>FY Obligation NOA</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FY_Obligation__c</fullName>
        <formula>FY_Obligation_IA__c + FY_Obligation_NOA__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>FY Obligation</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Fiscal_Year__c</fullName>
        <label>Fiscal Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Double Rent</label>
    <nameField>
        <displayFormat>DR-{000000}</displayFormat>
        <label>Double Rent Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Double Rents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/GLXY_LeaseProjectforSnapshot__c.object
<CustomObject>
    <fields>
        <fullName>Acceptance620Date__c</fullName>
        <label>Date 620</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BDGFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Include in Budget Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EffectiveDate__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IASquareFeet__c</fullName>
        <label>New IA Sq Ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NOASquareFeet__c</fullName>
        <label>New NOA Sq Ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProcessedDate__c</fullName>
        <label>Process Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProjectID__c</fullName>
        <label>Project ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectStatus__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Record_Type__c</fullName>
        <label>Record Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SnapshotName__c</fullName>
        <label>Snapshot Name</label>
        <referenceTo>Galaxy_Snapshot__c</referenceTo>
        <relationshipLabel>Lease Projects for Snapshot</relationshipLabel>
        <relationshipName>GLXY_LeaseProjectforSnapshot</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Source_Record__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Source Record</label>
        <referenceTo>Glxy_LeaseProjects__c</referenceTo>
        <relationshipLabel>GLXY_LeaseProjectforSnapshot</relationshipLabel>
        <relationshipName>GLXY_LeaseProjectforSnapshot</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Lease Project for Snapshot</label>
    <nameField>
        <displayFormat>LPH-{0000}</displayFormat>
        <label>Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lease Projects for Snapshot</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/GLXY_LeaseProjectPaymentsForSnapshot__c.object
<CustomObject>
    <fields>
        <fullName>Acceptance620Date__c</fullName>
        <label>620 to R7 Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AnnualAmount__c</fullName>
        <label>Annual Amount</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BudgetExclusionReason__c</fullName>
        <label>Budget Exclusion Reason</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>EffectiveDate__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ExpirationDate__c</fullName>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FYObligationIA__c</fullName>
        <label>FY Obligation IA</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FYObligationNOA__c</fullName>
        <label>FY Obligation NOA</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FYObligation__c</fullName>
        <label>FY Obligation</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>IASqFt__c</fullName>
        <label>IA Sq Ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IncludeinBudgetFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Include in Budget Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NOASqFt__c</fullName>
        <label>NOA Sq Ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ParentRecord__c</fullName>
        <label>Parent Record</label>
        <referenceTo>GLXY_LeaseProjectforSnapshot__c</referenceTo>
        <relationshipLabel>Lease Project Payments for Snapshot</relationshipLabel>
        <relationshipName>Lease_Project_Payments_for_Snapshot</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PaymentID__c</fullName>
        <label>Payment ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PaymentType__c</fullName>
        <label>Payment Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Category__c</fullName>
        <label>Payment Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Lease Proj. Lump Sum</fullName>
                </value>
                <value>
                    <fullName>Lease Proj. Step Rent</fullName>
                </value>
                <value>
                    <fullName>Double Rent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProcessDate__c</fullName>
        <label>Process Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Record_Type__c</fullName>
        <label>Record Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_Record__c</fullName>
        <label>Source Record</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status_Code__c</fullName>
        <label>Status Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Actual</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Estimate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Lease Project Payments for Snapshot</label>
    <nameField>
        <displayFormat>LPPH-{0000}</displayFormat>
        <label>Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lease Project Payments for Snapshot</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Glxy_LeaseProjects__c.object
<CustomObject>
    <customHelpPage>GLXY_HelpPage</customHelpPage>
    <description>This table contains information on all the New, Renewal, Extension, Succeeding, Superseding, Terminating, Chg in SF, and New/Replacing leases associated with a Project.  The Project is the starting point for new leases or changes to existing leases.</description>
    <fields>
        <fullName>Acceptance620Date__c</fullName>
        <inlineHelpText>Date contracting officer approves lease action</inlineHelpText>
        <label>Date 620</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BDGFlag__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Include In Budget Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EffectiveDate__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IASquareFeet__c</fullName>
        <defaultValue>0</defaultValue>
        <label>New IA Sq Ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NOASquareFeet__c</fullName>
        <defaultValue>0</defaultValue>
        <label>New NOA Sq Ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProcessedDate__c</fullName>
        <inlineHelpText>Date project goes from estimated to actual status</inlineHelpText>
        <label>Process Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProjectID__c</fullName>
        <externalId>true</externalId>
        <label>Project ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ProjectStatus__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Lease Project</label>
    <nameField>
        <label>Project Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lease Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/GLXY_SS_LoadProjectDoubleRent.cls
global with sharing class GLXY_SS_LoadProjectDoubleRent implements Database.Batchable<sObject>,Database.stateful{
 
    global List<GLXY_LeaseProjectPaymentsForSnapshot__c> objSnapShotRecords = New List<GLXY_LeaseProjectPaymentsForSnapshot__c>();
	public string strSnapShotID;
	public string strSnapShotName;
	public boolean blnProcessErrors = false;
	Public Map<string, String> mapProjectRecords = new Map<string, String>();
	
	global Database.QueryLocator start(Database.BatchableContext BC){
    	
    	// Snapshot processing ...
    	List<Galaxy_Snapshot__c> lstPreviouslyScheduledSnapshots = 
						[SELECT Id, Name 
						 FROM 	Galaxy_Snapshot__c 
						 Where 	Status__c = 'Started'
						 And 	Snapshot_Date__c = :Datetime.Now().Date() 
						 Limit 1];
		if(lstPreviouslyScheduledSnapshots.size() != 0){
			strSnapShotID = lstPreviouslyScheduledSnapshots[0].Id;
			strSnapShotName = lstPreviouslyScheduledSnapshots[0].Name;
		}
		
		// Load Lease Project Record Id's
		List<GLXY_LeaseProjectforSnapshot__c> listProjects = [Select ID, ProjectID__c From GLXY_LeaseProjectforSnapshot__c Where SnapshotName__c = :strSnapShotID];
		for(GLXY_LeaseProjectforSnapshot__c objItem : listProjects)
			mapProjectRecords.put(objItem.ProjectID__c, objItem.ID);
			
		//Query Payment Lines	
		Integer intCurrentFY = Datetime.Now().Date().Month() > 9? Datetime.Now().Date().Year() + 1 : Datetime.Now().Date().Year();
		String  strCurrentFY = String.ValueOf(intCurrentFY);
		//string  QuerySOQL =  'Select 	ID, RecordType.DeveloperName, Project__r.Acceptance620Date__c, Double_Rent__c, Project_Effective_Date__c, ' +
        //                     '			DoubleRentIA__c, DoubleRentNOA__c, Project__r.IASquareFeet__c, LeaseExpiration_lkp__c, ' +
		//			    	   '			Project__r.BDGFlag__c, Project__r.Name, Project__r.NOASquareFeet__c, ' +
		//			    	   '			Project__r.ProcessedDate__c, Project__r.ID ' +
		//			    	   'From 		Glxy_AssociatedLeases__c ' +
		//			    	   'Where (Project__r.ProjectStatus__c != \'Completed\' OR (Project__r.ProjectStatus__c = \'Completed\' And FISCAL_YEAR(Project__r.ProcessedDate__c) = :intCurrentFY)) ' +
        //                     'ORDER BY 	Name ';	 
        string  QuerySOQL = 'Select 	Associated_Leases_Projects_ID__r.ID, Associated_Leases_Projects_ID__r.RecordType.DeveloperName, Associated_Leases_Projects_ID__r.Project__r.Acceptance620Date__c, Associated_Leases_Projects_ID__r.Double_Rent__c, Associated_Leases_Projects_ID__r.Project_Effective_Date__c, ' +
                             '			FY_Obligation__c, FY_Obligation_IA__c, FY_Obligation_NOA__c, Associated_Leases_Projects_ID__r.Project__r.IASquareFeet__c, Associated_Leases_Projects_ID__r.LeaseExpiration_lkp__c, ' +
					    	 '			Associated_Leases_Projects_ID__r.Project__r.BDGFlag__c, Associated_Leases_Projects_ID__r.Project__r.Name, Associated_Leases_Projects_ID__r.Project__r.NOASquareFeet__c, ' +
					    	 '			Associated_Leases_Projects_ID__r.Project__r.ProcessedDate__c, Associated_Leases_Projects_ID__r.Project__r.ID ' +
					    	 'From 		Glxy_DoubleRent__c ' +
					    	 'Where (Associated_Leases_Projects_ID__r.Project__r.ProjectStatus__c != \'Completed\' OR (Associated_Leases_Projects_ID__r.Project__r.ProjectStatus__c = \'Completed\' And FISCAL_YEAR(Associated_Leases_Projects_ID__r.Project__r.ProcessedDate__c) = :intCurrentFY)) ' +
					    	 'And    Associated_Leases_Projects_ID__r.Project__r.ProjectStatus__c <> \'Cancelled\' ' +
					    	 'And   Fiscal_Year__c = :strCurrentFY ' +
                             'ORDER BY 	Name ';
        Return Database.getQueryLocator(QuerySOQL);
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope){

        try{
        	objSnapShotRecords.clear();
	        Glxy_DoubleRent__c objDR = null;
	        
	        for(sObject obj: scope) {
	        	objDR = (Glxy_DoubleRent__c) obj;
		      	objSnapShotRecords.Add(new GLXY_LeaseProjectPaymentsForSnapshot__c(
		        	Acceptance620Date__c = objDR.Associated_Leases_Projects_ID__r.Project__r.Acceptance620Date__c,
		        	AnnualAmount__c = objDR.Associated_Leases_Projects_ID__r.Double_Rent__c,
		        	BudgetExclusionReason__c = '',
		        	EffectiveDate__c = objDR.Associated_Leases_Projects_ID__r.Project_Effective_Date__c,
		        	ExpirationDate__c = objDR.Associated_Leases_Projects_ID__r.LeaseExpiration_lkp__c,
		        	FYObligation__c = objDR.FY_Obligation__c,
		        	FYObligationIA__c = objDR.FY_Obligation_IA__c,
		        	FYObligationNOA__c = objDR.FY_Obligation_NOA__c,
		        	IASqFt__c = objDR.Associated_Leases_Projects_ID__r.Project__r.IASquareFeet__c,
		        	IncludeinBudgetFlag__c = objDR.Associated_Leases_Projects_ID__r.Project__r.BDGFlag__c,
		        	NOASqFt__c = objDR.Associated_Leases_Projects_ID__r.Project__r.NOASquareFeet__c,
		        	ParentRecord__c =  mapProjectRecords.get(objDR.Associated_Leases_Projects_ID__r.Project__r.Name),
		        	Payment_Category__c = 'Double Rent',
		        	PaymentID__c = '',
		        	PaymentType__c = '',
		        	ProcessDate__c = objDR.Associated_Leases_Projects_ID__r.Project__r.ProcessedDate__c,
		        	Record_Type__c = objDR.Associated_Leases_Projects_ID__r.RecordType.DeveloperName,
		        	Source_Record__c = objDR.Associated_Leases_Projects_ID__r.ID,
		        	Status_Code__c = ''
		        ));
        	}	
        	Database.SaveResult[] result = Database.Insert(objSnapShotRecords);
	 	
	 	} catch (Exception e){
	 		blnProcessErrors = true;
        	Galaxy_Snapshot__c objSnapshotStatus = New Galaxy_Snapshot__c(ID = strSnapShotID, Status__c = 'Failed', StatusMessage__c = 'Snapshot process error (Loading Lease Project Double Rent data) - ' + e.getMessage());
			Update objSnapshotStatus;
    	}

    }
    
    global void finish(Database.BatchableContext BC){
    	If (!blnProcessErrors){
    		Galaxy_Snapshot__c objSnapshotStatus = New Galaxy_Snapshot__c(
				ID = strSnapShotID,
				StatusMessage__c = 'Completed Lease Project Double Rent data; Loading Lease Project Step Rent data ...'
			);
			Update objSnapshotStatus;
			
			database.executeBatch(new GLXY_SS_LoadProjectStepRent());	
    	}
    }
	
}