src/objects/GalaxyReconciliationBatch__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>The Reconciliation jobs are run in a sequence. The finish method of the first job will schedule the next job. Since the job will still remain active in the system, we will see the error message about scheduling a job that is already existing. We will use this  field to delete the job as soon as we’re done executing that step in the process.</description>
    <fields>
        <fullName>Schedule2_ID__c</fullName>
        <defaultValue>&apos;0&apos;</defaultValue>
        <label>Schedule2 ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>GalaxyReconciliationBatch</label>
</CustomObject>

src/objects/Glxy_ConsumerPriceIndex__c.object
<CustomObject>
    <description>This table contains information about each lease, along with increases and decreases in operating costs associated with the lease and the CPI to adjust rent on leases.</description>
    <fields>
        <fullName>Acceptance620Date__c</fullName>
        <inlineHelpText>Date 620 approved/forwarded to R7</inlineHelpText>
        <label>620 to R7 Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AnnualAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Annual Amount</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BDGFlag__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Checkmark indicates item is included in budget projection</inlineHelpText>
        <label>Include in Budget Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EffectiveDateFY__c</fullName>
        <formula>Text(YEAR( EffectiveDate__c + 92 ))</formula>
        <label>Effective Date FY</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EffectiveDate__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FY_Obligation_IA__c</fullName>
        <label>FY Obligation IA</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FY_Obligation_NOA__c</fullName>
        <label>FY Obligation NOA</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LeaseNumber__c</fullName>
        <label>Lease Number</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>Region Specified for Lease falls outside your region</errorMessage>
            <filterItems>
                <field>$User.Glxy_Region_Code__c</field>
                <operation>equals</operation>
                <valueField>Glxy_Lease__c.RegionCD__c</valueField>
            </filterItems>
            <filterItems>
                <field>$User.Glxy_Region_Code__c</field>
                <operation>equals</operation>
                <value>CO</value>
            </filterItems>
            <infoMessage>Leases in this list as limited to your region</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Glxy_Lease__c</referenceTo>
        <relationshipLabel>Consumer Price Index</relationshipLabel>
        <relationshipName>CPIs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProcessedDateFY__c</fullName>
        <formula>Text(YEAR(ProcessedDate__c + 92 ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Process Date FY</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProcessedDate__c</fullName>
        <inlineHelpText>Date completed</inlineHelpText>
        <label>Process Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RegionCd__c</fullName>
        <formula>TEXT(LeaseNumber__r.RegionCD__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StatusCD__c</fullName>
        <inlineHelpText>&quot;Actual&quot; or &quot;Estimate&quot;</inlineHelpText>
        <label>Status Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Actual</fullName>
                </value>
                <value>
                    <fullName>Estimate</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Consumer Price Index</label>
    <nameField>
        <displayFormat>CPI-{000000}</displayFormat>
        <label>CPI ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consumer Price Index</pluralLabel>
    <recordTypes>
        <fullName>Rexus</fullName>
        <active>true</active>
        <description>Record imported from Rexus</description>
        <label>Rexus</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Glxy_Lease__c.object
<CustomObject>
    <customHelpPage>GLXY_HelpPage</customHelpPage>
    <description>This table contains lease information at the beginning of the fiscal year.  This information is updated at the beginning of each fiscal year.</description>
    <fields>
        <fullName>BaseAnnualRent__c</fullName>
        <inlineHelpText>Be sure to click save to adjust monthly impact.</inlineHelpText>
        <label>Base Annual Rent</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BaseLeaseEffectiveDate__c</fullName>
        <label>Lease Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DelegatedLease__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Indicator Box populated with a check if designated as a Delegated Lease in REXUS.</inlineHelpText>
        <label>Delegated Lease</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ExpirationDateofLease__c</fullName>
        <description>Expiration Date</description>
        <label>Lease Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IAConverstionDate__c</fullName>
        <inlineHelpText>The date upon which the fund type converts from IA Base to NOA Base</inlineHelpText>
        <label>IA/NOA Conversion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RegionCD__c</fullName>
        <description>Region Code</description>
        <label>Region Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StatusCode__c</fullName>
        <description>Status Code</description>
        <inlineHelpText>Current status of during G2 Base Sertting period. Options are Active, Terminated, Pending.
DL	Deleted
PD	Pending
TM	Terminated
AC	Active</inlineHelpText>
        <label>Status Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_IA_Sq_feet__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total IA Sq ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_NOA_Sq_feet__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total NOA Sq ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Lease</label>
    <nameField>
        <label>Lease Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Glxy_UpdateProcessDateEOYCPI.cls
global with sharing class Glxy_UpdateProcessDateEOYCPI implements Database.Batchable<sObject>,Database.stateful{
	
	global List<Glxy_ConsumerPriceIndex__c> objUpdatedRecords = New List<Glxy_ConsumerPriceIndex__c>();
	global String strCurrentFY;
	global Date dtAdvanceDate;
		
	global Database.QueryLocator start(Database.BatchableContext BC){
		//Advance all the Process Dates to the Current FYs. This only applies to those records in ESTIMATE status, so we can better project the #s
        //This process will be scheduled via a job. 

        //#1) Calculate current Fiscal Year (GSA FY), and Advance Date
        Integer intCurrentFY = date.today().Year();  
        Integer intCurrentYearMonth = date.today().Month();
        if (intCurrentYearMonth <= 9 && !Test.isRunningTest()){ // in Real time
            intCurrentFY -=1;
        }
        
        if (intCurrentYearMonth >= 9 && Test.isRunningTest()){ // for test methods to get coverage
        	intCurrentFY +=1;
        }
        
        strCurrentFY = String.ValueOf(intCurrentFY); 
        dtAdvanceDate = Date.Newinstance (Integer.ValueOf(strCurrentFY), 10, 01);
        
        //#2) Advance Glxy_ConsumerPriceIndex__c ...
        string RexusRecordTypeID = Schema.SObjectType.Glxy_ConsumerPriceIndex__c.getRecordTypeInfosByName().get('Rexus').getRecordTypeId();
		string QueryData = 'Select   ID, ProcessedDate__c ' +
	 	 					'From    Glxy_ConsumerPriceIndex__c ' + 
	 	 					'Where   StatusCd__c = \'Estimate\' ' + 
	 	 					'And 	 ProcessedDateFY__c != Null ' + 
	 	 					'And     ProcessedDateFY__c <= :strCurrentFY ' +
	 	 					'And 	 EffectiveDateFY__c != Null ' + 
	 	 					'And     EffectiveDateFY__c <= :strCurrentFY ' +
	 	 					'ORDER BY ID ';						 
	 	Return Database.getQueryLocator(QueryData);
	}
	
	global void execute(Database.BatchableContext BC, List<sObject> scope){
		objUpdatedRecords.Clear();
		Glxy_ConsumerPriceIndex__c objCPI;
		
		for(sObject obj: scope) {
			objCPI = (Glxy_ConsumerPriceIndex__c) obj;
			objUpdatedRecords.Add(new Glxy_ConsumerPriceIndex__c(
                ID = objCPI.ID,
                ProcessedDate__c = dtAdvanceDate
            ));
		}
		
		try{	
        	Database.update(objUpdatedRecords, false);
	 	}catch (DmlException e){
        	System.debug('Glxy_UpdateProcessDateEOYCPI Update error - ' + e.getMessage());
    	}
		 
	}
	
	global void finish(Database.BatchableContext BC){
		//Invoke the next job ... 
   		GalaxyReconciliationBatch__c objCustomSettings = GalaxyReconciliationBatch__c.getOrgDefaults(); // Reuse the Reconciliation Batch Variables, since they never run together
   		DateTime n = datetime.now().addMinutes(1);
   		String cron = '';
   		cron += n.second();
   		cron += ' ' + n.minute();
   		cron += ' ' + n.hour();
   		cron += ' ' + n.day();
   		cron += ' ' + n.month();
   		cron += ' ' + '?';
   		cron += ' ' + n.year();
   		objCustomSettings.Schedule2_ID__c = System.Schedule('Glxy_JobScheduleProcessDateUpdateEOYSR', cron, new Glxy_JobScheduleProcessDateUpdateEOYSR());
   		try{	
        	Update objCustomSettings;
	 	}catch (Exception e){
        	System.debug('Glxy_UpdateProcessDateEOYCPI - Job Create error - ' + e.getMessage());
    	}
	}
  	
  	 static testMethod void testClass(){
		
		Glxy_Lease__c ObjLease = new Glxy_Lease__c();
        ObjLease.StatusCode__c = 'Active';
        ObjLease.BaseLeaseEffectiveDate__c = date.newinstance(date.today().Year(), 1, 1);
        ObjLease.ExpirationDateofLease__c = date.newinstance(date.today().Year() + 5, 1, 1);
        ObjLease.RegionCD__c = '1';
        ObjLease.Total_NOA_Sq_feet__c = 10;
        ObjLease.Total_IA_Sq_feet__c = 20;
        objLease.DelegatedLease__c = false;
        objLease.BaseAnnualRent__c = 1000;
        objLease.IAConverstionDate__c = date.newinstance(date.today().Year(), 1, 1);
        insert ObjLease;
        System.Assert(ObjLease!=NULL);
        
        string RexusRecordTypeID = Schema.SObjectType.Glxy_ConsumerPriceIndex__c.getRecordTypeInfosByName().get('Rexus').getRecordTypeId();
        Glxy_ConsumerPriceIndex__c objCPI2 = new Glxy_ConsumerPriceIndex__c (
            LeaseNumber__c = objLease.id,
            RecordTypeID = RexusRecordTypeID,
            AnnualAmount__c = 200,
            FY_Obligation_NOA__c = 50,
            FY_Obligation_IA__c = 50,
            BDGFlag__c = true,
            ProcessedDate__c = Datetime.Now().Date().addYears(0),
            EffectiveDate__c = Datetime.Now().Date().addYears(0),
            Acceptance620Date__c = Datetime.Now().Date().addYears(0),
            StatusCD__c = 'Estimate'
        );
        insert objCPI2;
        
    	Test.startTest();     
    	Glxy_UpdateProcessDateEOYCPI objTest = new Glxy_UpdateProcessDateEOYCPI();
    	Database.executeBatch(objTest);      
    	Test.stopTest();     
    }  
}