src/objects/GalaxyBudgetCall__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>The Budget Call jobs are run in a sequence. The finish method of the first job will schedule the next job. Since the job will still remain active in the system, we will see the error message about scheduling a job that is already existing. We will use this field to delete the job as soon as we’re done executing that step in the process.</description>
    <fields>
        <fullName>AdjustFiscalYear__c</fullName>
        <defaultValue>1</defaultValue>
        <description>The Fiscal Year () function always return FY value one less than the current FY. If this changes in the future, this value should be set to &apos;0&apos;.</description>
        <label>AdjustFiscalYear</label>
        <precision>12</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DataToStoreforXFYs__c</fullName>
        <defaultValue>3</defaultValue>
        <description>Budget Call Data - Calculate and save data for +- &quot;X&quot; years.</description>
        <label>DataToStoreforXFYs</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Schedule2_ID__c</fullName>
        <defaultValue>&apos;0&apos;</defaultValue>
        <label>Schedule2 ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>GalaxyBudgetCall</label>
</CustomObject>

src/objects/Glxy_BudgetCallLineItem__c.object
<CustomObject>
    <fields>
        <fullName>BudgetCategory__c</fullName>
        <label>Budget Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Base Rent</fullName>
                </value>
                <value>
                    <fullName>Cancellation</fullName>
                </value>
                <value>
                    <fullName>Double Rent</fullName>
                </value>
                <value>
                    <fullName>Expansion</fullName>
                </value>
                <value>
                    <fullName>IBAA</fullName>
                </value>
                <value>
                    <fullName>Lump Sums</fullName>
                </value>
                <value>
                    <fullName>Operating Cost Escalation (CPI)</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Project Step Rent</fullName>
                </value>
                <value>
                    <fullName>Rent Increase</fullName>
                </value>
                <value>
                    <fullName>RWA</fullName>
                </value>
                <value>
                    <fullName>Step Rent</fullName>
                </value>
                <value>
                    <fullName>Total</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Taxes</fullName>
                </value>
                <value>
                    <fullName>Project Lump Sums</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LeaseNumber__c</fullName>
        <label>Lease Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Budget Call Line Item</label>
    <nameField>
        <displayFormat>LI-{0000}</displayFormat>
        <label>Budget Call Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Call Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Glxy_Lease__c.object
<CustomObject>
    <customHelpPage>GLXY_HelpPage</customHelpPage>
    <description>This table contains lease information at the beginning of the fiscal year.  This information is updated at the beginning of each fiscal year.</description>
    <fields>
        <fullName>BaseLeaseEffectiveDate__c</fullName>
        <label>Lease Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ExpirationDateofLease__c</fullName>
        <description>Expiration Date</description>
        <label>Lease Expiration Date</label>
        <type>Date</type>
    </fields>
    <label>Lease</label>
    <nameField>
        <label>Lease Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Glxy_BC_CleanUpBudgetCallLineItems.cls
global with sharing class Glxy_BC_CleanUpBudgetCallLineItems implements Database.Batchable<sObject> {
   public String Query;

	global Glxy_BC_CleanUpBudgetCallLineItems(){
	}
	
   	global Database.QueryLocator start(Database.BatchableContext BC){
   		Date dtProcessRunDate = Datetime.Now().Date();
		string Query = 'Select Name from Glxy_BudgetCallLineItem__c';
   		Return Database.getQueryLocator(Query);
   	}

   	global void execute(Database.BatchableContext BC, List<sObject> scope){
		Delete scope;
      	DataBase.emptyRecycleBin(scope);
   	}

   	global void finish(Database.BatchableContext BC){
   		/*
   		//Invoke the next job ... 
   		GalaxyBudgetCall__c objCustomSettings = GalaxyBudgetCall__c.getOrgDefaults();
   		DateTime n = datetime.now().addMinutes(1);
   		String cron = '';
   		cron += n.second();
   		cron += ' ' + n.minute();
   		cron += ' ' + n.hour();
   		cron += ' ' + n.day();
   		cron += ' ' + n.month();
   		cron += ' ' + '?';
   		cron += ' ' + n.year();
   		objCustomSettings.Schedule2_ID__c = System.Schedule('Glxy_BC_LoadLease', cron, new GLXY_BC_JobSchedule2());
   		try{	
        	Update objCustomSettings;
	 	}catch (Exception e){
        	System.debug('Glxy_BC_CleanUpBudgetCallLineItems - Job Create error - ' + e.getMessage());
    	}*/
    	
    	//Invoke the next batch
    	database.executeBatch(new GLXY_BC_LoadLease());
    	
   	}
   	
   @isTest static void testClass(){
   		
   		Test.startTest();    
   		
   		Glxy_Lease__c objLease = new Glxy_Lease__c();
		objLease.Name = 'LAK05855';
		objLease.BaseLeaseEffectiveDate__c = Datetime.Now().Date();
		objLease.ExpirationDateofLease__c =Datetime.Now().Date();
		insert objLease;
		
   		Glxy_BudgetCallLineItem__c objBudgetCall = new Glxy_BudgetCallLineItem__c(
            LeaseNumber__c = 'LAK05855',
            BudgetCategory__c = 'Base Rent'
            );
        insert objBudgetCall;
        
        Insert new GalaxyBudgetCall__c(Name='TEST', AdjustFiscalYear__c = 1, DataToStoreforXFYs__c = 3);
                
        Glxy_BC_CleanUpBudgetCallLineItems objTest = new Glxy_BC_CleanUpBudgetCallLineItems();
        Database.executeBatch(objTest);
        System.Assert(objTest!=NULL);     
        Test.stopTest();     
    }   
}