src/objects/Galaxy_Snapshot__c.object
<CustomObject>
    <fields>
        <fullName>Snapshot_Date__c</fullName>
        <defaultValue>DATEVALUE(Now())</defaultValue>
        <inlineHelpText>The system will make a data snapshot on the data specified</inlineHelpText>
        <label>Snapshot Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&quot;Scheduled&quot;</defaultValue>
        <label>Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Galaxy Snapshot</label>
    <nameField>
        <label>Galaxy Snapshot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Galaxy Snapshot</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Glxy_Lease__c.object
<CustomObject>
    <customHelpPage>GLXY_HelpPage</customHelpPage>
    <description>This table contains lease information at the beginning of the fiscal year.  This information is updated at the beginning of each fiscal year.</description>
    <fields>
        <fullName>Antennas__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Antennas</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BaseAnnualRent__c</fullName>
        <inlineHelpText>Be sure to click save to adjust monthly impact.</inlineHelpText>
        <label>Base Annual Rent</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BaseLeaseEffectiveDate__c</fullName>
        <label>Lease Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BaseSquareFeet__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Base Sq Ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BaseStructuredParkingSpaces__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Parking spaces available in a parking structure/garage.</description>
        <label>Base Structured Parking Spaces</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BaseSurfaceParkingSpaces__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Parking spaces available in a parking lot.</description>
        <label>Base Surface Parking Spaces</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DelegatedLease__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Indicator Box populated with a check if designated as a Delegated Lease in REXUS.</inlineHelpText>
        <label>Delegated Lease</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ExpirationDateofLease__c</fullName>
        <description>Expiration Date</description>
        <label>Lease Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>HoldoverExpirationDate__c</fullName>
        <description>Holdover Expiration Date</description>
        <label>Holdover Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>HoldoverStatusInd__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Status, Yes or No  - The Government’s right to remain in the lease space after the expiration date of the current term without a contract in the event a mutual agreement to extend the lease term cannot be made and continued occupancy is required.</inlineHelpText>
        <label>Holdover Status Indicator</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IAConverstionDate__c</fullName>
        <inlineHelpText>The date upon which the fund type converts from IA Base to NOA Base</inlineHelpText>
        <label>IA/NOA Conversion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IAPercentage__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Percent of RSF/AR that is Indefinite Authority.</inlineHelpText>
        <label>IA Percentage</label>
        <precision>8</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>LandOnly__c</fullName>
        <formula>If(
    (
       BaseStructuredParkingSpaces__c == 0 &amp;&amp;
       BaseSurfaceParkingSpaces__c == 0 &amp;&amp;   
       BaseSquareFeet__c == 0 &amp;&amp;
       Antennas__c == 0
    ),
True,
False
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Land Only</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NOAPercentage__c</fullName>
        <formula>1 - IAPercentage__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Percent of RSF/AR that is New Obligational Authority.</inlineHelpText>
        <label>NOA Percentage</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Next_FY_Leases__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Flag to identify the leases that are not included in base.</inlineHelpText>
        <label>Next FY Leases</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ParkingOnly__c</fullName>
        <formula>IF(AND( BaseSquareFeet__c = 0, BaseStructuredParkingSpaces__c + BaseSurfaceParkingSpaces__c &lt;&gt; 0),&quot;Yes&quot;,&quot;No&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Parking-Only</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RealtySpecialist__c</fullName>
        <label>Realty Specialist Email</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RegionCD__c</fullName>
        <description>Region Code</description>
        <label>Region Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StatusCode__c</fullName>
        <description>Status Code</description>
        <inlineHelpText>Current status of during G2 Base Sertting period. Options are Active, Terminated, Pending.
DL	Deleted
PD	Pending
TM	Terminated
AC	Active</inlineHelpText>
        <label>Status Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TeamCode__c</fullName>
        <label>Team Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TerminationDateofLease__c</fullName>
        <description>Termination  Date</description>
        <label>Lease Termination Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_IA_Sq_feet__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total IA Sq ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_NOA_Sq_feet__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total NOA Sq ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Lease</label>
    <nameField>
        <label>Lease Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Glxy_LeaseSnapshot__c.object
<CustomObject>
    <fields>
        <fullName>Antennas__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Antennas</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BaseAnnualRent__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Base Annual Rent</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BaseSquareFeet__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Base Sq Ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BaseStructuredParkingSpaces__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Base Structured Parking Spaces</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BaseSurfaceParkingSpaces__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Base Surface Parking Spaces</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DelegatedLease__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Delegated Lease</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HoldoverExpirationDate__c</fullName>
        <label>Holdover Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>HoldoverStatusInd__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Holdover Status Indicator</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IAConverstionDate__c</fullName>
        <label>IA/NOA Conversion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IAPercentage__c</fullName>
        <defaultValue>0</defaultValue>
        <label>IA Percentage</label>
        <precision>8</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>LandOnly__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Land Only</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LeaseEffectiveDate__c</fullName>
        <label>Lease Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LeaseExpirationDate__c</fullName>
        <label>Lease Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LeaseNumber__c</fullName>
        <label>Lease Number</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LeaseTerminationDate__c</fullName>
        <label>Lease Termination Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NOAPercentage__c</fullName>
        <defaultValue>0</defaultValue>
        <label>NOA Percentage</label>
        <precision>8</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>NextFYLeases__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Next FY Leases</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ParkingOnly__c</fullName>
        <formula>IF(AND(BaseSquareFeet__c = 0, BaseStructuredParkingSpaces__c + BaseSurfaceParkingSpaces__c &lt;&gt; 0),&quot;Yes&quot;,&quot;No&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Parking Only</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RealtySpecialistEmail__c</fullName>
        <label>Realty Specialist Email</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RegionCode__c</fullName>
        <label>Region Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StatusCode__c</fullName>
        <label>Status Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Lease for Snapshot</label>
    <nameField>
        <displayFormat>LH-{0000}</displayFormat>
        <label>Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leases for Snapshot</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/GLXY_SS_LoadLease.cls
global with sharing class GLXY_SS_LoadLease implements Database.Batchable<sObject>,Database.stateful{
    
    global List<Glxy_LeaseSnapshot__c> objSnapShotRecords = New List<Glxy_LeaseSnapshot__c>();
	public string 	strSnapShotID;
	public string 	strSnapShotName;
	public boolean 	blnProcessErrors = false;
	public string	strLimitClause = '';
	 
    global Database.QueryLocator start(Database.BatchableContext BC){
    	
    	List<Galaxy_Snapshot__c> lstPreviouslyScheduledSnapshots = 
						[SELECT Id, Name 
						 FROM 	Galaxy_Snapshot__c 
						 Where 	Status__c = 'Scheduled'
						 And 	Snapshot_Date__c = :Datetime.Now().Date() 
						 Limit 1];
		if(lstPreviouslyScheduledSnapshots.size() != 0){
			strSnapShotID = lstPreviouslyScheduledSnapshots[0].Id;
			strSnapShotName = lstPreviouslyScheduledSnapshots[0].Name;
					
			//Update the status to Started
			Galaxy_Snapshot__c objProcessing = lstPreviouslyScheduledSnapshots[0];
			objProcessing.Status__c = 'Started';
			Update objProcessing;
		} else {
			//Salesforce does not provide mechanism to exit start method
			strLimitClause = 'Limit 0';
		}
	 
        string QueryAllLeases = 'Select ID, Name, Antennas__c, BaseAnnualRent__c, BaseSquareFeet__c, BaseStructuredParkingSpaces__c, ' +
		                                 'BaseSurfaceParkingSpaces__c, DelegatedLease__c, IAConverstionDate__c, IAPercentage__c, ' +
								    	 'LandOnly__c, BaseLeaseEffectiveDate__c, ExpirationDateofLease__c, TerminationDateofLease__c, ' +
								    	 'Next_FY_Leases__c, NOAPercentage__c, ParkingOnly__c, RealtySpecialist__c, HoldoverExpirationDate__c, HoldoverStatusInd__c, ' +
								    	 'RegionCD__c, StatusCode__c, TeamCode__c, Total_IA_Sq_feet__c, Total_NOA_Sq_feet__c ' +  
						    	 'From  GLXY_Lease__c ' +
						    	 //'Where StatusCode__c = \'Active\' ' + 
                                 //'And   Next_FY_Leases__c = False ' +
                                 'ORDER BY Name ' + strLimitClause;
        Return Database.getQueryLocator(QueryAllLeases);
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope){

        try{
        	objSnapShotRecords.clear();
	        Glxy_Lease__c objLease = null;
	        
	        for(sObject obj: scope) {
	        	objLease = (Glxy_Lease__c) obj;
		      	objSnapShotRecords.Add(new Glxy_LeaseSnapshot__c(
		        	Antennas__c = objLease.Antennas__c,
		        	BaseAnnualRent__c = objLease.BaseAnnualRent__c,
		        	BaseSquareFeet__c = objLease.BaseSquareFeet__c,
		        	BaseStructuredParkingSpaces__c = objLease.BaseStructuredParkingSpaces__c,
		        	BaseSurfaceParkingSpaces__c = objLease.BaseStructuredParkingSpaces__c,
		        	DelegatedLease__c = objLease.DelegatedLease__c,
		        	HoldoverExpirationDate__c = objLease.HoldoverExpirationDate__c,
		        	HoldoverStatusInd__c = objLease.HoldoverStatusInd__c,
		        	IAConverstionDate__c = objLease.IAConverstionDate__c,
		        	IAPercentage__c = objLease.IAPercentage__c,
		        	LandOnly__c = objLease.LandOnly__c,
		        	LeaseEffectiveDate__c = objLease.BaseLeaseEffectiveDate__c,
		        	LeaseExpirationDate__c = objLease.ExpirationDateofLease__c,
		        	LeaseNumber__c = objLease.Name,
		        	LeaseTerminationDate__c = objLease.TerminationDateofLease__c,
		        	NextFYLeases__c = objLease.Next_FY_Leases__c,
		        	NOAPercentage__c = objLease.NOAPercentage__c,
		        	RealtySpecialistEmail__c = objLease.RealtySpecialist__c,
		        	RegionCode__c = objLease.RegionCD__c,
		        	SnapshotName__c = strSnapShotID,
		        	SourceRecord__c = objLease.ID,
		        	StatusCode__c = objLease.StatusCode__c,
		        	Team_Code__c = objLease.TeamCode__c,
		        	TotalIASqft__c = objLease.Total_IA_Sq_feet__c,
		        	TotalNOASqft__c = objLease.Total_NOA_Sq_feet__c,
		        	UniqueID__c = strSnapShotID + '||' + objLease.ID
		        ));
        	}	
        	Database.SaveResult[] result = Database.Insert(objSnapShotRecords);
	 	
	 	}catch (Exception e){
	 		blnProcessErrors = true;
        	Galaxy_Snapshot__c objSnapshotStatus = New Galaxy_Snapshot__c(
				ID = strSnapShotID, Status__c = 'Failed', StatusMessage__c = 'Snapshot process error (Loading Lease data) - ' + e.getMessage());
			Update objSnapshotStatus;
    	}

    }
    
    global void finish(Database.BatchableContext BC){
    	If (!blnProcessErrors && (strLimitClause != 'Limit 0')){
    		Galaxy_Snapshot__c objSnapshotStatus = New Galaxy_Snapshot__c(
				ID = strSnapShotID,
				StatusMessage__c = 'Completed Lease snap shot; Loading CPI data ...'
			);
			Update objSnapshotStatus;
			
			database.executeBatch(new GLXY_SS_LoadCPI());
    	}
    }

}