src/objects/Galaxy_Snapshot__c.object
<CustomObject>
    <fields>
        <fullName>Snapshot_Date__c</fullName>
        <defaultValue>DATEVALUE(Now())</defaultValue>
        <inlineHelpText>The system will make a data snapshot on the data specified</inlineHelpText>
        <label>Snapshot Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&quot;Scheduled&quot;</defaultValue>
        <label>Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Galaxy Snapshot</label>
    <nameField>
        <label>Galaxy Snapshot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Galaxy Snapshot</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/GLXY_LeaseProjectforSnapshot__c.object
<CustomObject>
    <fields>
        <fullName>Acceptance620Date__c</fullName>
        <label>Date 620</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BDGFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Include in Budget Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Budget_Exclusion_Reason__c</fullName>
        <label>Budget Exclusion Reason</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>EffectiveDate__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProcessedDate__c</fullName>
        <label>Process Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProjectID__c</fullName>
        <label>Project ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectStatus__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SnapshotName__c</fullName>
        <label>Snapshot Name</label>
        <referenceTo>Galaxy_Snapshot__c</referenceTo>
        <relationshipLabel>Lease Projects for Snapshot</relationshipLabel>
        <relationshipName>GLXY_LeaseProjectforSnapshot</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Lease Project for Snapshot</label>
    <nameField>
        <displayFormat>LPH-{0000}</displayFormat>
        <label>Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lease Projects for Snapshot</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/GLXY_LeaseProjectPaymentsForSnapshot__c.object
<CustomObject>
    <fields>
        <fullName>Acceptance620Date__c</fullName>
        <label>620 to R7 Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EffectiveDate__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ExpirationDate__c</fullName>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PaymentID__c</fullName>
        <label>Payment ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectNumber__c</fullName>
        <formula>ParentRecord__r.ProjectID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Number</label>
        <type>Text</type>
    </fields>
    <label>Lease Project Payments for Snapshot</label>
    <nameField>
        <displayFormat>LPPH-{0000}</displayFormat>
        <label>Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lease Project Payments for Snapshot</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Glxy_LeaseProjects__c.object
<CustomObject>
    <customHelpPage>GLXY_HelpPage</customHelpPage>
    <description>This table contains information on all the New, Renewal, Extension, Succeeding, Superseding, Terminating, Chg in SF, and New/Replacing leases associated with a Project.  The Project is the starting point for new leases or changes to existing leases.</description>
    <fields>
        <fullName>Acceptance620Date__c</fullName>
        <inlineHelpText>Date contracting officer approves lease action</inlineHelpText>
        <label>Date 620</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BDGFlag__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Include In Budget Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Budget_Exclusion_Reason__c</fullName>
        <label>Budget Exclusion Reason</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>EffectiveDate__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProcessedDate__c</fullName>
        <inlineHelpText>Date project goes from estimated to actual status</inlineHelpText>
        <label>Process Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProjectID__c</fullName>
        <externalId>true</externalId>
        <label>Project ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ProjectStatus__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Lease Project</label>
    <nameField>
        <label>Project Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lease Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Glxy_LPLumpSum__c.object
<CustomObject>
    <description>This table contains the lump sum changes to lease project payments for a single or successive months that are not changes to the annual rental rate.  These are one-time non-recurring payments such as annual tax adjustments, claims, or project buy-outs.</description>
    <fields>
        <fullName>Acceptance620Date__c</fullName>
        <formula>ProjectNumber__r.Acceptance620Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Date 620 approved - sent to FW</inlineHelpText>
        <label>620 to R7 Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Annual Amount</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BDGFlag__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Checkmark indicates item is included in budget projection</inlineHelpText>
        <label>Include in Budget Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Budget_Exclusion_Reason__c</fullName>
        <label>Budget Exclusion Reason</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>EffectiveDate__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ExpirationDate__c</fullName>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FY_Obligation_IA__c</fullName>
        <label>FY Obligation IA</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FY_Obligation_NOA__c</fullName>
        <label>FY Obligation NOA</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FY_Obligation__c</fullName>
        <defaultValue>0</defaultValue>
        <label>FY Obligation</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>IA_Sq_Ft__c</fullName>
        <defaultValue>0</defaultValue>
        <label>IA Sq Ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LumSumType__c</fullName>
        <inlineHelpText>In the drop down menu, choose the category that best describes the type of lump sum you&apos;re entering, such as rent free period, buyout, claim, etc</inlineHelpText>
        <label>Lump Sum Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bid Tax</fullName>
                </value>
                <value>
                    <fullName>Broker Commission Credit</fullName>
                </value>
                <value>
                    <fullName>Buyout</fullName>
                </value>
                <value>
                    <fullName>Catch Up Payment</fullName>
                </value>
                <value>
                    <fullName>Claim</fullName>
                </value>
                <value>
                    <fullName>Debits &amp; Credits</fullName>
                </value>
                <value>
                    <fullName>Escalation</fullName>
                </value>
                <value>
                    <fullName>Interest</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Paragraph 15</fullName>
                </value>
                <value>
                    <fullName>Recovery Act</fullName>
                </value>
                <value>
                    <fullName>Rent</fullName>
                </value>
                <value>
                    <fullName>Rent Free Period</fullName>
                </value>
                <value>
                    <fullName>Tax Escalation</fullName>
                </value>
                <value>
                    <fullName>Termination</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NOA_Sq_Ft__c</fullName>
        <defaultValue>0</defaultValue>
        <label>NOA Sq Ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PaymentID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Unique identifier from Rexus. This helps in finding the record in Rexus.</inlineHelpText>
        <label>Payment ID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ProcessedDate__c</fullName>
        <inlineHelpText>Date completed</inlineHelpText>
        <label>Process Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProjectNumber__c</fullName>
        <label>Project Number</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>Region value specified is outside your region</errorMessage>
            <filterItems>
                <field>$User.Glxy_Region_Code__c</field>
                <operation>equals</operation>
                <valueField>Glxy_LeaseProjects__c.RegionCd__c</valueField>
            </filterItems>
            <filterItems>
                <field>$User.Glxy_Region_Code__c</field>
                <operation>equals</operation>
                <value>CO</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Glxy_LeaseProjects__c</referenceTo>
        <relationshipLabel>Lease Proj Lump Sums</relationshipLabel>
        <relationshipName>LP_Lump_Sums</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>StatusCd__c</fullName>
        <label>Status Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Actual</fullName>
                </value>
                <value>
                    <fullName>Estimate</fullName>
                </value>
                <value>
                    <fullName>Voided</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Lease Proj Lump Sum</label>
    <nameField>
        <displayFormat>LPLS-{000000}</displayFormat>
        <label>LP Lump Sum ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lease Proj Lump Sums</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Glxy_LPLumpSumObligations__c.object
<CustomObject>
    <fields>
        <fullName>FY_Obligation_IA__c</fullName>
        <formula>Apr_IA__c + May_IA__c + Jun_IA__c + Jul_IA__c + Aug_IA__c + Sep_IA__c + Oct_IA__c + Nov_IA__c + Dec_IA__c + JAN_IA__c + Feb_IA__c + Mar_IA__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>FY Obligation IA</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FY_Obligation_NOA__c</fullName>
        <formula>Apr_NOA__c + May_NOA__c + Jun_NOA__c + Jul_NOA__c + Aug_NOA__c + Sep_NOA__c + Oct_NOA__c + Nov_NOA__c + Dec_NOA__c + JAN_NOA__c + Feb_NOA__c + Mar_NOA__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>FY Obligation NOA</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FY_Obligation__c</fullName>
        <formula>FY_Obligation_IA__c + FY_Obligation_NOA__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>FY Obligation</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LPLumpSum__c</fullName>
        <label>LP Lump Sum</label>
        <referenceTo>Glxy_LPLumpSum__c</referenceTo>
        <relationshipName>LP_Lump_Sum_Obligations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Lease Proj Lump Sum Obligations</label>
    <nameField>
        <displayFormat>LPLSO-{000000}</displayFormat>
        <label>LP Lump Sum Obligation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lease Proj Lump Sum Obligations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/GLXY_SS_LoadProjectLumpSum.cls
global with sharing class GLXY_SS_LoadProjectLumpSum implements Database.Batchable<sObject>,Database.stateful{
 
    global List<GLXY_LeaseProjectPaymentsForSnapshot__c> objSnapShotRecords = New List<GLXY_LeaseProjectPaymentsForSnapshot__c>();
	public string strSnapShotID;
	public string strSnapShotName;
	public boolean blnProcessErrors = false;
	Public Map<string, String> mapProjectRecords = new Map<string, String>();
	
	global Database.QueryLocator start(Database.BatchableContext BC){
    	
    	// Snapshot processing ...
    	List<Galaxy_Snapshot__c> lstPreviouslyScheduledSnapshots = 
						[SELECT Id, Name 
						 FROM 	Galaxy_Snapshot__c 
						 Where 	Status__c = 'Started'
						 And 	Snapshot_Date__c = :Datetime.Now().Date() 
						 Limit 1];
		if(lstPreviouslyScheduledSnapshots.size() != 0){
			strSnapShotID = lstPreviouslyScheduledSnapshots[0].Id;
			strSnapShotName = lstPreviouslyScheduledSnapshots[0].Name;
		}
		
		// Load Lease Project Record Id's
		List<GLXY_LeaseProjectforSnapshot__c> listProjects = [Select ID, ProjectID__c From GLXY_LeaseProjectforSnapshot__c Where SnapshotName__c = :strSnapShotID];
		for(GLXY_LeaseProjectforSnapshot__c objItem : listProjects)
			mapProjectRecords.put(objItem.ProjectID__c, objItem.ID);
			
		//Query Payment Lines	
		Integer intCurrentFY = Datetime.Now().Date().Month() > 9? Datetime.Now().Date().Year() + 1 : Datetime.Now().Date().Year();
		String  strCurrentFY = String.ValueOf(intCurrentFY);	 
        //string  QuerySOQL = 'Select 	ID, RecordType.DeveloperName, Acceptance620Date__c, Amount__c, Budget_Exclusion_Reason__c, EffectiveDate__c, ExpirationDate__c, ' +
        //                     '			FY_Obligation__c, FY_Obligation_IA__c, FY_Obligation_NOA__c, IA_Sq_Ft__c, ' +
		//			    	   '			BDGFlag__c, ProjectNumber__r.Name, LumSumType__c, NOA_Sq_Ft__c, ' +
		//			    	   '			ProcessedDate__c, PaymentID__c, StatusCd__c, ProjectNumber__r.ID ' +
		//			    	   'From 		Glxy_LPLumpSum__c ' +
		//			    	   'Where (ProjectNumber__r.ProjectStatus__c != \'Completed\' OR (ProjectNumber__r.ProjectStatus__c = \'Completed\' And FISCAL_YEAR(ProjectNumber__r.ProcessedDate__c) = :intCurrentFY)) ' +
        //                     'ORDER BY 	Name ';
		string  QuerySOQL = 'Select 	LPLumpSum__r.ID, LPLumpSum__r.RecordType.DeveloperName, LPLumpSum__r.Acceptance620Date__c, LPLumpSum__r.Amount__c, LPLumpSum__r.Budget_Exclusion_Reason__c, LPLumpSum__r.EffectiveDate__c, LPLumpSum__r.ExpirationDate__c, ' +
                             '			FY_Obligation__c, FY_Obligation_IA__c, FY_Obligation_NOA__c, LPLumpSum__r.IA_Sq_Ft__c, ' +
					    	 '			LPLumpSum__r.BDGFlag__c, LPLumpSum__r.ProjectNumber__r.Name, LPLumpSum__r.LumSumType__c, LPLumpSum__r.NOA_Sq_Ft__c, ' +
					    	 '			LPLumpSum__r.ProcessedDate__c, LPLumpSum__r.PaymentID__c, LPLumpSum__r.StatusCd__c, LPLumpSum__r.ProjectNumber__r.ID ' +
					    	 'From 		Glxy_LPLumpSumObligations__c ' +
					    	 'Where (LPLumpSum__r.ProjectNumber__r.ProjectStatus__c != \'Completed\' OR (LPLumpSum__r.ProjectNumber__r.ProjectStatus__c = \'Completed\' And FISCAL_YEAR(LPLumpSum__r.ProjectNumber__r.ProcessedDate__c) = :intCurrentFY)) ' +
					    	 'And   FiscalYear__c = :strCurrentFY ' +
                             'ORDER BY 	Name ';                             
        Return Database.getQueryLocator(QuerySOQL);
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope){

        try{
        	objSnapShotRecords.clear();
	        Glxy_LPLumpSumObligations__c objLS = null;
	        
	        for(sObject obj: scope) {
	        	objLS = (Glxy_LPLumpSumObligations__c) obj;
		      	objSnapShotRecords.Add(new GLXY_LeaseProjectPaymentsForSnapshot__c(
		        	Acceptance620Date__c = objLS.LPLumpSum__r.Acceptance620Date__c,
		        	AnnualAmount__c = objLS.LPLumpSum__r.Amount__c,
		        	BudgetExclusionReason__c = objLS.LPLumpSum__r.Budget_Exclusion_Reason__c,
		        	EffectiveDate__c = objLS.LPLumpSum__r.EffectiveDate__c,
		        	ExpirationDate__c = objLS.LPLumpSum__r.ExpirationDate__c,
		        	FYObligation__c = objLS.FY_Obligation__c,
		        	FYObligationIA__c = objLS.FY_Obligation_IA__c,
		        	FYObligationNOA__c = objLS.FY_Obligation_NOA__c,
		        	IASqFt__c = objLS.LPLumpSum__r.IA_Sq_Ft__c,
		        	IncludeinBudgetFlag__c = objLS.LPLumpSum__r.BDGFlag__c,
		        	NOASqFt__c = objLS.LPLumpSum__r.NOA_Sq_Ft__c,
		        	ParentRecord__c =  mapProjectRecords.get(objLS.LPLumpSum__r.ProjectNumber__r.Name),
		        	Payment_Category__c = 'Lease Proj. Lump Sum',
		        	PaymentID__c = string.valueOf(objLS.LPLumpSum__r.PaymentID__c),
		        	PaymentType__c = objLS.LPLumpSum__r.LumSumType__c,
		        	ProcessDate__c = objLS.LPLumpSum__r.ProcessedDate__c,
		        	Record_Type__c = objLS.LPLumpSum__r.RecordType.DeveloperName,
		        	Source_Record__c = objLS.LPLumpSum__r.ID,
		        	Status_Code__c = objLS.LPLumpSum__r.StatusCd__c
		        ));
        	}	
        	Database.SaveResult[] result = Database.Insert(objSnapShotRecords);
	 	
	 	} catch (Exception e){
	 		blnProcessErrors = true;
        	Galaxy_Snapshot__c objSnapshotStatus = New Galaxy_Snapshot__c(ID = strSnapShotID, Status__c = 'Failed', StatusMessage__c = 'Snapshot process error (Loading Lease Project Lump Sum data) - ' + e.getMessage());
			Update objSnapshotStatus;
    	}

    }
    
    global void finish(Database.BatchableContext BC){
    	If (!blnProcessErrors){
    		Galaxy_Snapshot__c objSnapshotStatus = New Galaxy_Snapshot__c(
				ID = strSnapShotID,
				StatusMessage__c = 'Completed Lease Project Lump Sum data; Loading Lease Project Double Rent data ...'
			);
			Update objSnapshotStatus;
			
			database.executeBatch(new GLXY_SS_LoadProjectDoubleRent());	
    	}
    }
	
}