src/objects/GalaxyBudgetCall__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>The Budget Call jobs are run in a sequence. The finish method of the first job will schedule the next job. Since the job will still remain active in the system, we will see the error message about scheduling a job that is already existing. We will use this field to delete the job as soon as we’re done executing that step in the process.</description>
    <fields>
        <fullName>AdjustFiscalYear__c</fullName>
        <defaultValue>1</defaultValue>
        <description>The Fiscal Year () function always return FY value one less than the current FY. If this changes in the future, this value should be set to &apos;0&apos;.</description>
        <label>AdjustFiscalYear</label>
        <precision>12</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DataToStoreforXFYs__c</fullName>
        <defaultValue>3</defaultValue>
        <description>Budget Call Data - Calculate and save data for +- &quot;X&quot; years.</description>
        <label>DataToStoreforXFYs</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>GalaxyBudgetCall</label>
</CustomObject>

src/objects/Glxy_BudgetCallLineItem__c.object
<CustomObject>
    <fields>
        <fullName>Apr__c</fullName>
        <label>Apr</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Aug__c</fullName>
        <label>Aug</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BudgetCategory__c</fullName>
        <label>Budget Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Base Rent</fullName>
                </value>
                <value>
                    <fullName>Cancellation</fullName>
                </value>
                <value>
                    <fullName>Double Rent</fullName>
                </value>
                <value>
                    <fullName>Expansion</fullName>
                </value>
                <value>
                    <fullName>IBAA</fullName>
                </value>
                <value>
                    <fullName>Lump Sums</fullName>
                </value>
                <value>
                    <fullName>Operating Cost Escalation (CPI)</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Project Step Rent</fullName>
                </value>
                <value>
                    <fullName>Rent Increase</fullName>
                </value>
                <value>
                    <fullName>RWA</fullName>
                </value>
                <value>
                    <fullName>Step Rent</fullName>
                </value>
                <value>
                    <fullName>Total</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Taxes</fullName>
                </value>
                <value>
                    <fullName>Project Lump Sums</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DataGroup__c</fullName>
        <label>Data Group</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dec__c</fullName>
        <label>Dec</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Feb__c</fullName>
        <label>Feb</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FiscalYear__c</fullName>
        <label>Fiscal Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IAConversionFY__c</fullName>
        <label>IAConversionFY</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Jan__c</fullName>
        <label>Jan</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Jul__c</fullName>
        <label>Jul</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Jun__c</fullName>
        <label>Jun</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LeaseNumber__c</fullName>
        <label>Lease Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LeaseStatus__c</fullName>
        <label>Lease Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lease_Expiration_Date__c</fullName>
        <label>Lease Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Mar__c</fullName>
        <label>Mar</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>May__c</fullName>
        <label>May</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Nov__c</fullName>
        <label>Nov</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Oct__c</fullName>
        <label>Oct</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Sep__c</fullName>
        <label>Sep</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SquareFeet__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Square Feet</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Actual</fullName>
                </value>
                <value>
                    <fullName>Estimate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TeamCode__c</fullName>
        <label>Team Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Budget Call Line Item</label>
    <nameField>
        <displayFormat>LI-{0000}</displayFormat>
        <label>Budget Call Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Call Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Glxy_Lease__c.object
<CustomObject>
    <customHelpPage>GLXY_HelpPage</customHelpPage>
    <description>This table contains lease information at the beginning of the fiscal year.  This information is updated at the beginning of each fiscal year.</description>
    <fields>
        <fullName>Apr_IA__c</fullName>
        <description>Updated in R2.4; earlier formula - (CostPerSqFt__c * Total_IA_Sq_feet__c ) / 12</description>
        <formula>(BaseAnnualRent__c *  IAPercentage__c)/12</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>APR IA</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Apr_NOA__c</fullName>
        <description>Updated in R2.4; earlier formula -
( CostPerSqFt__c * IF(ParkingOnly__c = &quot;No&quot;, Total_NOA_Sq_feet__c, BaseStructuredParkingSpaces__c + BaseSurfaceParkingSpaces__c ) )/12</description>
        <formula>(BaseAnnualRent__c *  NOAPercentage__c)/12</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>APR NOA</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BaseAnnualRent__c</fullName>
        <inlineHelpText>Be sure to click save to adjust monthly impact.</inlineHelpText>
        <label>Base Annual Rent</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BaseLeaseEffectiveDate__c</fullName>
        <label>Lease Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BaseSquareFeet__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Base Sq Ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BaseStructuredParkingSpaces__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Parking spaces available in a parking structure/garage.</description>
        <label>Base Structured Parking Spaces</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BaseSurfaceParkingSpaces__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Parking spaces available in a parking lot.</description>
        <label>Base Surface Parking Spaces</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CostPerSqFt__c</fullName>
        <formula>BaseAnnualRent__c / IF(BaseSquareFeet__c &lt;&gt; 0, BaseSquareFeet__c ,if( ParkingOnly__c = &quot;Yes&quot; ,BaseStructuredParkingSpaces__c + BaseSurfaceParkingSpaces__c ,1 ) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cost Per Sq Foot</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ExpirationDateofLease__c</fullName>
        <description>Expiration Date</description>
        <label>Lease Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IAConverstionDate__c</fullName>
        <inlineHelpText>The date upon which the fund type converts from IA Base to NOA Base</inlineHelpText>
        <label>IA/NOA Conversion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IAConverstionFY__c</fullName>
        <formula>IF( 
ISBLANK(IAConverstionDate__c), 
&quot;2099&quot;, 
Text(YEAR(IAConverstionDate__c + 92))
)</formula>
        <label>IAConverstionFY</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Next_FY_Leases__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Flag to identify the leases that are not included in base.</inlineHelpText>
        <label>Next FY Leases</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ParkingOnly__c</fullName>
        <formula>IF(AND( BaseSquareFeet__c = 0, BaseStructuredParkingSpaces__c + BaseSurfaceParkingSpaces__c &lt;&gt; 0),&quot;Yes&quot;,&quot;No&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Parking-Only</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RegionCD__c</fullName>
        <description>Region Code</description>
        <label>Region Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StatusCode__c</fullName>
        <description>Status Code</description>
        <inlineHelpText>Current status of during G2 Base Sertting period. Options are Active, Terminated, Pending.
DL	Deleted
PD	Pending
TM	Terminated
AC	Active</inlineHelpText>
        <label>Status Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TeamCode__c</fullName>
        <label>Team Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_IA_Annual_Rent__c</fullName>
        <description>Updated in R2.4; previous formula was - (CostPerSqFt__c * Total_IA_Sq_feet__c)</description>
        <formula>(BaseAnnualRent__c * IAPercentage__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total IA Annual Rent</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_IA_Sq_feet__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total IA Sq ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_NOA_Annual_Rent__c</fullName>
        <description>Updated in R2.4; Previous formula - 
if( ParkingOnly__c = &quot;Yes&quot; , BaseAnnualRent__c, (CostPerSqFt__c * Total_NOA_Sq_feet__c) )</description>
        <formula>(BaseAnnualRent__c * NOAPercentage__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total NOA Annual Rent</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_NOA_Sq_feet__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total NOA Sq ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Lease</label>
    <nameField>
        <label>Lease Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/GLXY_BC_LoadLease.cls
global with sharing class GLXY_BC_LoadLease implements Database.Batchable<sObject>,Database.stateful{
    
    global List<Glxy_BudgetCallLineItem__c> objBudgetCallRecords = New List<Glxy_BudgetCallLineItem__c>();
    global Integer intLeaseEffectiveFY;
    global Integer intLeaseExpirationFY;
    global Integer intCurrentFY;
    global Integer intIAConversionFY;
    
    global decimal dbMonthlyIA = 0.0;
    global decimal dbMonthlyNOA = 0.0;
    global decimal dbMonthlyTotal = 0.0;
    global decimal dbSqFtIA = 0.0;
    global decimal dbSqFtNOA = 0.0;
    global decimal dbSqFtTotal = 0.0;
    global decimal dblAnnualRentIA = 0.0;
    global decimal dblAnnualRentNOA = 0.0;
    
    GalaxyBudgetCall__c objCustomSettingsYears = GalaxyBudgetCall__c.getOrgDefaults();
	//Integer intYearLimit = Integer.ValueOf(objCustomSettingsYears.DataToStoreforXFYs__c);
	//Integer intAdjustFY = Integer.ValueOf(objCustomSettingsYears.AdjustFiscalYear__c);
	
    global Database.QueryLocator start(Database.BatchableContext BC){
        string QueryAllLeases =  'SELECT Id, Name, StatusCode__c, IAConverstionFY__c, Total_IA_Annual_Rent__c, Total_NOA_Annual_Rent__c, BaseAnnualRent__c, CostPerSqFt__c, BaseSquareFeet__c, ParkingOnly__c, Apr_IA__c, Apr_NOA__c, ' +
                                 'Total_NOA_Sq_feet__c, Total_IA_Sq_feet__c, RegionCD__c, TeamCode__c, BaseStructuredParkingSpaces__c,  BaseSurfaceParkingSpaces__c, ' +
                                 'ExpirationDateofLease__c, IAConverstionDate__c, BaseLeaseEffectiveDate__c ' +
                                 'FROM  Glxy_Lease__c  ' + 
                                 //'Where StatusCode__c = \'Active\' ' + 
                                 //'And   Next_FY_Leases__c = False ' +  
                                 'ORDER BY Name ';
        Return Database.getQueryLocator(QueryAllLeases);
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope){
        
        objBudgetCallRecords.clear();
        Glxy_Lease__c objLease = null;
        intCurrentFY = Datetime.Now().Date().Month() > 9? Datetime.Now().Date().Year() + 1 : Datetime.Now().Date().Year();
        
        for(sObject obj: scope) {
        	objLease = (Glxy_Lease__c) obj;
        	
        	dbMonthlyIA = 0.0;
	        dbMonthlyNOA = 0.0;
	        dbMonthlyTotal = 0.0;
	        dbSqFtIA = 0.0;
	        dbSqFtNOA = 0.0;
	        dbSqFtTotal = 0.0;
			dblAnnualRentIA = 0.0;
    		dblAnnualRentNOA = 0.0;
	    		
        	If (objLease.StatusCode__c == 'Active') { 
        		dbMonthlyIA = objLease.Apr_IA__c;
		        dbMonthlyNOA = objLease.Apr_NOA__c; 		// April NOA Formula accounts for parking Only Leases ...
		        dbMonthlyTotal = dbMonthlyNOA + dbMonthlyIA;
		        dbSqFtIA = objLease.Total_IA_Sq_feet__c;
		        dbSqFtNOA = objLease.Total_NOA_Sq_feet__c;
		        dbSqFtTotal = dbSqFtNOA + dbSqFtIA;
				dblAnnualRentIA = objLease.Total_IA_Annual_Rent__c;
	    		dblAnnualRentNOA = objLease.Total_NOA_Annual_Rent__c;
        	}
    
	        //Insert Base Rent IA
	        objBudgetCallRecords.Add(new Glxy_BudgetCallLineItem__c(
	            FiscalYear__c = String.valueOf(intCurrentFY),
	            LeaseNumber__c = objLease.Name,
	            BudgetCategory__c = 'Base Rent', 
	            DataGroup__c = 'IA',
	            Status__c = 'Actual',
	            LeaseStatus__c = objLease.StatusCode__c, 
	            Lease_Expiration_Date__c = objLease.ExpirationDateofLease__c,
	            IAConversionFY__c = objLease.IAConverstionFY__c,
	            Jan__c = dbMonthlyIA, Feb__c = dbMonthlyIA, Mar__c = dbMonthlyIA, Apr__c = dbMonthlyIA, May__c = dbMonthlyIA, Jun__c = dbMonthlyIA,
	            Jul__c = dbMonthlyIA, Aug__c = dbMonthlyIA, Sep__c = dbMonthlyIA, Oct__c = dbMonthlyIA, Nov__c = dbMonthlyIA, Dec__c = dbMonthlyIA,
	            SquareFeet__c = dbSqFtIA,
	            AnnualAmount__c = dblAnnualRentIA,
	            RegionCode__c = objLease.RegionCD__c,
	            TeamCode__c = objLease.TeamCode__c
	        ));
	        //Insert Base Rent NOA
	        objBudgetCallRecords.Add(new Glxy_BudgetCallLineItem__c(
	            FiscalYear__c = String.valueOf(intCurrentFY),
	            LeaseNumber__c = objLease.Name,
	            BudgetCategory__c = 'Base Rent', 
	            DataGroup__c = 'NOA',
	            Status__c = 'Actual',
	            LeaseStatus__c = objLease.StatusCode__c,
	            Lease_Expiration_Date__c = objLease.ExpirationDateofLease__c, 
	            IAConversionFY__c = objLease.IAConverstionFY__c,
	            Jan__c = dbMonthlyNOA, Feb__c = dbMonthlyNOA, Mar__c = dbMonthlyNOA, Apr__c = dbMonthlyNOA, May__c = dbMonthlyNOA, Jun__c = dbMonthlyNOA,
	            Jul__c = dbMonthlyNOA, Aug__c = dbMonthlyNOA, Sep__c = dbMonthlyNOA, Oct__c = dbMonthlyNOA, Nov__c = dbMonthlyNOA, Dec__c = dbMonthlyNOA,
	            SquareFeet__c = dbSqFtNOA,
	            AnnualAmount__c = dblAnnualRentNOA,
	            RegionCode__c = objLease.RegionCD__c,
	            TeamCode__c = objLease.TeamCode__c
	        ));
        }
        Database.SaveResult[] result = Database.Insert(objBudgetCallRecords);
    }
    
    global void finish(Database.BatchableContext BC){
    	//Invoke the next batch
    	database.executeBatch(new GLXY_BC_LoadCPI());
    }
    
}