src/objects/GalaxyReconciliationBatch__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>The Reconciliation jobs are run in a sequence. The finish method of the first job will schedule the next job. Since the job will still remain active in the system, we will see the error message about scheduling a job that is already existing. We will use this  field to delete the job as soon as we’re done executing that step in the process.</description>
    <fields>
        <fullName>CustomRunDate__c</fullName>
        <defaultValue>Null</defaultValue>
        <label>Custom Run Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Schedule2_ID__c</fullName>
        <defaultValue>&apos;0&apos;</defaultValue>
        <label>Schedule2 ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>GalaxyReconciliationBatch</label>
</CustomObject>

src/objects/Glxy_Reconciliation__c.object
<CustomObject>
    <description>This table contains snap shot of Lease data by month</description>
    <fields>
        <fullName>AnnualRent__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Base Annual Rent</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CPIAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>CPI Monthly Amount</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CancelAnnualRentIA__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Cancel Annual Rent IA</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CancelAnnualRentNOA__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Cancel Annual Rent NOA</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ChangeInSFRent__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Change in SF Rent</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CurrentMonthGalaxy__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Current Month Galaxy</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LeaseNumberMonth__c</fullName>
        <externalId>true</externalId>
        <label>Lease Number Month</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LeaseNumber__c</fullName>
        <label>Lease Number</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LumpSumTotal__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Total Lump Sum = Lump Sum Amount + Rent Increase LS + CPI LS</description>
        <inlineHelpText>Total Lump Sum = Lump Sum Amount + Rent Increase LS + CPI LS</inlineHelpText>
        <label>Lump Sum Total</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RentDifference__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Escalation Monthly Rent</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tax__c</fullName>
        <defaultValue>0</defaultValue>
        <label>LS-Tax Escalation</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Galaxy Reconciliation</label>
    <nameField>
        <displayFormat>RE-{0000000000}</displayFormat>
        <label>Galaxy Reconciliation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Galaxy Reconciliation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GLXY_ReconciliationCleanUp.cls
global with sharing class GLXY_ReconciliationCleanUp implements Database.Batchable<sObject> {
   public String Query;

	global GLXY_ReconciliationCleanUp(){
	}
	
   	global Database.QueryLocator start(Database.BatchableContext BC){
   		Date dtProcessRunDate = Datetime.Now().Date().addMonths(-1);
   		//Galaxy 2.2 - Provide capability to run the process for previous months
   		GalaxyReconciliationBatch__c objCustomSettings = GalaxyReconciliationBatch__c.getOrgDefaults();
   		if (objCustomSettings.CustomRunDate__c != null){
   			dtProcessRunDate = objCustomSettings.CustomRunDate__c.addMonths(-1);
   		}
   		//Galaxy 2.2 - Provide capability to run the process for previous months
		string strCurrentMonth = String.valueOf(dtProcessRunDate.Month());
   		string Query = 'Select Name from Glxy_Reconciliation__c where Month__c = \'' + strCurrentMonth + '\'';
   		//Galaxy 2.2 - October, clean up all the data
   		If (strCurrentMonth == '10'){
   			Query = 'Select Name from Glxy_Reconciliation__c';
   		}
   		//Galaxy 2.2 - October, clean up all the data
   		Return Database.getQueryLocator(Query);
   	}

   	global void execute(Database.BatchableContext BC, List<sObject> scope){
		Delete scope;
      	DataBase.emptyRecycleBin(scope);
   	}

   	global void finish(Database.BatchableContext BC){
   		//Invoke the next job ... 
   		GalaxyReconciliationBatch__c objCustomSettings = GalaxyReconciliationBatch__c.getOrgDefaults();
   		DateTime n = datetime.now().addMinutes(1);
   		String cron = '';
   		cron += n.second();
   		cron += ' ' + n.minute();
   		cron += ' ' + n.hour();
   		cron += ' ' + n.day();
   		cron += ' ' + n.month();
   		cron += ' ' + '?';
   		cron += ' ' + n.year();
   		objCustomSettings.Schedule2_ID__c = System.Schedule('GLXY_Reconciliation', cron, new GLXY_ReconciliationJobSchedule2());
   		try{	
        	Update objCustomSettings;
	 	}catch (Exception e){
        	System.debug('GLXY_ReconciliationCleanUp Job Create error - ' + e.getMessage());
    	}
   	}
   	
   static testMethod void testClass(){
   		
   		Test.startTest();    
   		
   		Date dtProcessRunDate = Datetime.Now().Date();                
        String strCurrentMonth = String.valueOf(dtProcessRunDate.Month() - 1);
        
   		Glxy_Reconciliation__c objReconciliation = new Glxy_Reconciliation__c(
            LeaseNumberMonth__c = strCurrentMonth + 'LDE0034',
            LeaseNumber__c = 'LDE0034',
            Month__c = strCurrentMonth,
            CurrentMonthGalaxy__c = 0.0,
            AnnualRent__c = 0.0,
            RentDifference__c = 0.0,
            CPIAmount__c = 0.0,
            CancelAnnualRentIA__c = 0.0,
            CancelAnnualRentNOA__c = 0.0,
            ChangeInSFRent__c = 0.0,
            LumpSumTotal__c = 0.0,
            Tax__c = 0.0
            );
        insert objReconciliation;
                 
        GLXY_ReconciliationCleanUp objTest = new GLXY_ReconciliationCleanUp();
        Database.executeBatch(objTest);
        System.Assert(objTest!=NULL);     
        Test.stopTest();     
    }   
}