src/objects/GalaxyReconciliationBatch__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>The Reconciliation jobs are run in a sequence. The finish method of the first job will schedule the next job. Since the job will still remain active in the system, we will see the error message about scheduling a job that is already existing. We will use this  field to delete the job as soon as we’re done executing that step in the process.</description>
    <fields>
        <fullName>CustomRunDate__c</fullName>
        <defaultValue>Null</defaultValue>
        <label>Custom Run Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Schedule3_ID__c</fullName>
        <defaultValue>&apos;0&apos;</defaultValue>
        <label>Schedule3 ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Schedule4_ID__c</fullName>
        <defaultValue>&apos;0&apos;</defaultValue>
        <label>Schedule4 ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>GalaxyReconciliationBatch</label>
</CustomObject>

src/objects/Glxy_ConsumerPriceIndex__c.object
<CustomObject>
    <description>This table contains information about each lease, along with increases and decreases in operating costs associated with the lease and the CPI to adjust rent on leases.</description>
    <fields>
        <fullName>Acceptance620Date__c</fullName>
        <inlineHelpText>Date 620 approved/forwarded to R7</inlineHelpText>
        <label>620 to R7 Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AnnualAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Annual Amount</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BDGFlag__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Checkmark indicates item is included in budget projection</inlineHelpText>
        <label>Include in Budget Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EffectiveDateFY__c</fullName>
        <formula>Text(YEAR( EffectiveDate__c + 92 ))</formula>
        <label>Effective Date FY</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EffectiveDate__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FY_Obligation__c</fullName>
        <defaultValue>0</defaultValue>
        <label>FY Obligation</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LeaseNumber__c</fullName>
        <label>Lease Number</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>Region Specified for Lease falls outside your region</errorMessage>
            <filterItems>
                <field>$User.Glxy_Region_Code__c</field>
                <operation>equals</operation>
                <valueField>Glxy_Lease__c.RegionCD__c</valueField>
            </filterItems>
            <filterItems>
                <field>$User.Glxy_Region_Code__c</field>
                <operation>equals</operation>
                <value>CO</value>
            </filterItems>
            <infoMessage>Leases in this list as limited to your region</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Glxy_Lease__c</referenceTo>
        <relationshipLabel>Consumer Price Index</relationshipLabel>
        <relationshipName>CPIs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RegionCd__c</fullName>
        <formula>TEXT(LeaseNumber__r.RegionCD__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StatusCD__c</fullName>
        <inlineHelpText>&quot;Actual&quot; or &quot;Estimate&quot;</inlineHelpText>
        <label>Status Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Actual</fullName>
                </value>
                <value>
                    <fullName>Estimate</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Consumer Price Index</label>
    <nameField>
        <displayFormat>CPI-{000000}</displayFormat>
        <label>CPI ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consumer Price Index</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Glxy_Lease__c.object
<CustomObject>
    <customHelpPage>GLXY_HelpPage</customHelpPage>
    <description>This table contains lease information at the beginning of the fiscal year.  This information is updated at the beginning of each fiscal year.</description>
    <fields>
        <fullName>BaseAnnualRent__c</fullName>
        <inlineHelpText>Be sure to click save to adjust monthly impact.</inlineHelpText>
        <label>Base Annual Rent</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BaseLeaseEffectiveDate__c</fullName>
        <label>Lease Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DelegatedLease__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Indicator Box populated with a check if designated as a Delegated Lease in REXUS.</inlineHelpText>
        <label>Delegated Lease</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ExpirationDateofLease__c</fullName>
        <description>Expiration Date</description>
        <label>Lease Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FY_Obligation__c</fullName>
        <formula>BaseAnnualRent__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>FY Obligation</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>IAConverstionDate__c</fullName>
        <inlineHelpText>The date upon which the fund type converts from IA Base to NOA Base</inlineHelpText>
        <label>IA/NOA Conversion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>REXUSStatusCode__c</fullName>
        <label>Rexus Status Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RegionCD__c</fullName>
        <description>Region Code</description>
        <label>Region Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StatusCode__c</fullName>
        <description>Status Code</description>
        <inlineHelpText>Current status of during G2 Base Sertting period. Options are Active, Terminated, Pending.
DL	Deleted
PD	Pending
TM	Terminated
AC	Active</inlineHelpText>
        <label>Status Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_IA_Sq_feet__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total IA Sq ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_NOA_Sq_feet__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total NOA Sq ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Lease</label>
    <nameField>
        <label>Lease Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Glxy_Reconciliation__c.object
<CustomObject>
    <description>This table contains snap shot of Lease data by month</description>
    <fields>
        <fullName>CPIAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>CPI Monthly Amount</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CPILumpSum__c</fullName>
        <defaultValue>0</defaultValue>
        <label>CPI Lump Sum</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LeaseNumberMonth__c</fullName>
        <externalId>true</externalId>
        <label>Lease Number Month</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LeaseNumber__c</fullName>
        <label>Lease Number</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RegionCD__c</fullName>
        <label>Region Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StatusCode__c</fullName>
        <description>Status Code</description>
        <inlineHelpText>DL Deleted
PD Pending
TM Terminated
AC Active</inlineHelpText>
        <label>Status Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Galaxy Reconciliation</label>
    <nameField>
        <displayFormat>RE-{0000000000}</displayFormat>
        <label>Galaxy Reconciliation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Galaxy Reconciliation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GLXY_ReconciliationSummaryTotals3.cls
public with sharing class GLXY_ReconciliationSummaryTotals3 {
    
    public void CalculateTotals(){
        
        List<Glxy_Reconciliation__c> objReconciliationUpdatedRecords = New List<Glxy_Reconciliation__c>();
        AggregateResult[] AgR;
        
        Date dtProcessRunDate = Datetime.Now().Date();
        string strCurrentMonth = String.valueOf(dtProcessRunDate.addMonths(-1).Month());
        Date dtCurrentDay = Datetime.Now().Date();
        //Galaxy 2.2 - Provide capability to run the process for previous months
        GalaxyReconciliationBatch__c objCustomSettings1 = GalaxyReconciliationBatch__c.getOrgDefaults();
        if (objCustomSettings1.CustomRunDate__c != null){
            dtProcessRunDate = objCustomSettings1.CustomRunDate__c;
            strCurrentMonth = String.valueOf(dtProcessRunDate.addMonths(-1).Month());
            dtCurrentDay = objCustomSettings1.CustomRunDate__c;
        }
        
        Integer PreviousMonthYear = dtProcessRunDate.Year();
        if (dtProcessRunDate.Month() == 1 ) {
            PreviousMonthYear -= 1;
        }
        
        Integer DaysinThisMonth = date.daysInMonth(dtProcessRunDate.Year(), dtProcessRunDate.Month());
        Date StartMonth  = Date.newInstance(dtProcessRunDate.Year(), dtProcessRunDate.month(), 01);
        Date EndMonth  = Date.newInstance(dtProcessRunDate.Year(), dtProcessRunDate.month(), DaysinThisMonth);
        Integer DaysinPreviousMonth = date.daysInMonth(PreviousMonthYear, dtProcessRunDate.addMonths(-1).Month());
        Date StartPreviousMonth =  Date.newInstance(PreviousMonthYear, dtProcessRunDate.addMonths(-1).Month(), 01);
        Date EndPreviousMonth =  Date.newInstance(PreviousMonthYear, dtProcessRunDate.addMonths(-1).Month(), DaysinPreviousMonth);
        //Galaxy 2.2 - Provide capability to run the process for previous months
        
        Integer dtCurrentFY = dtProcessRunDate.Year();
        if ((dtProcessRunDate.addMonths(-1).Month() == 10 || dtProcessRunDate.addMonths(-1).Month() == 11)) {// Runs for Oct Nov Dec data, add FY +=1
            dtCurrentFY +=1;
        }
        
        //Loop to sum data by Lease Number
        string strLoopCurrentLease;
        string strLoopPreviousLease;
        Boolean blnHasData;
      
       	//CPI related fields ...
        Decimal dblCPIAmount = 0.0;
        Decimal dblCPILumpSum = 0.0;
        
        // Make a list of all Leases that will be used as sub-queries as move through the other Objects ...
        Set<String> LeaseNames = New Set<String>();
        Set<String> LeaseIds = New Set<String>();
        List<Glxy_Lease__c> objGetLeasesList = [Select ID, Name From  Glxy_Lease__c WHERE REXUSStatusCode__c  = 'Active']; 
        for (Glxy_Lease__c objtemp : objGetLeasesList) {
            LeaseNames.add(objtemp.Name);
            LeaseIds.add(objtemp.ID);
        }

         // CPI Related Field updates ......
        strLoopPreviousLease = '-';
        blnHasData = false;
        List<Glxy_ConsumerPriceIndex__c> objCPIData = [ 
            Select  LeaseNumber__r.Name, AnnualAmount__c, EffectiveDate__c, EffectiveDateFY__c, Acceptance620Date__c
            From    Glxy_ConsumerPriceIndex__c
            Where   LeaseNumber__c in :LeaseIds
            And     StatusCd__c = 'Actual' 
            And 	BDGFlag__c = true 
            And     Acceptance620Date__c <= :EndPreviousMonth //G2 R2.2
            AND     Acceptance620Date__c = THIS_FISCAL_YEAR   //G2 R2.2
            And     EffectiveDate__c <= :EndPreviousMonth     //G2 R2.2
            Order by LeaseNumber__r.Name
            ];

        for (Glxy_ConsumerPriceIndex__c RowData : objCPIData) { 
            strLoopCurrentLease = RowData.LeaseNumber__r.Name;
            blnHasData = true;
            if ((strLoopCurrentLease <> strLoopPreviousLease) && (strLoopPreviousLease <> '-')){
                objReconciliationUpdatedRecords.Add(new Glxy_Reconciliation__c(
                    LeaseNumberMonth__c = strCurrentMonth + strLoopPreviousLease,
                    CPIAmount__c = dblCPIAmount,
                    CPILumpSum__c = dblCPILumpSum
                ));
                dblCPIAmount = 0.0;
                dblCPILumpSum = 0.0;
            }
            If (dtProcessRunDate.addMonths(-1).Month() == RowData.Acceptance620Date__c.Month()){ //Accrual - Run only When Reconciliation Run Month = Acceptance Month
                 dblCPILumpSum += fnReturnCPILumpSum(RowData.EffectiveDate__c, RowData.Acceptance620Date__c, (RowData.AnnualAmount__c/12));
            }
            dblCPIAmount += RowData.AnnualAmount__c/12;    
            strLoopPreviousLease = strLoopCurrentLease; 
        }
        
        if (blnHasData){ // Run one last time, for the last record ...
            objReconciliationUpdatedRecords.Add(new Glxy_Reconciliation__c(
                LeaseNumberMonth__c = strCurrentMonth + strLoopPreviousLease,
                CPIAmount__c = dblCPIAmount,
                CPILumpSum__c = dblCPILumpSum
            ));
        }
        
        try{    
            Database.UpsertResult[] results = Database.Upsert(objReconciliationUpdatedRecords, Schema.Glxy_Reconciliation__c.LeaseNumberMonth__c, false);
        }catch (DmlException e){
            System.debug('GLXY_ReconciliationSummaryTotals - CPI Data Update error - ' + e.getMessage());
        }
        objReconciliationUpdatedRecords.clear();
  
        //Delete this job from Scheduled Jobs ...
        try{    
            GalaxyReconciliationBatch__c objCustomSettings = GalaxyReconciliationBatch__c.getOrgDefaults();
            System.abortJob(objCustomSettings.Schedule3_ID__c);
        }catch (Exception e){
            System.debug('GLXY_ReconciliationSummaryTotals3 - Delete Job error - ' + e.getMessage());
        }
       //Invoke the NEXT job ...
        GalaxyReconciliationBatch__c objCustomSettings2 = GalaxyReconciliationBatch__c.getOrgDefaults();
        DateTime n = datetime.now().addMinutes(1);
        String cron = '';
        cron += n.second();
        cron += ' ' + n.minute();
        cron += ' ' + n.hour();
        cron += ' ' + n.day();
        cron += ' ' + n.month();
        cron += ' ' + '?';
        cron += ' ' + n.year();
        objCustomSettings2.Schedule4_ID__c = System.Schedule('GLXY_ReconciliationTotalLumpSums', cron, new GLXY_ReconciliationJobSchedule4());
        try{    
            Update objCustomSettings2;
        }catch (Exception e){
            System.debug('GLXY_ReconciliationSummaryTotals2 - Create Job error - ' + e.getMessage());
        }
        
    }
    
    Private Decimal fnReturnCPILumpSum(Date EffectiveDate, Date AcceptanceDate, Decimal MonthlyAmount){
        Decimal dblCPILumpSum = 0.0;
        Integer DaysinThisMonth = date.daysInMonth(EffectiveDate.Year(), EffectiveDate.Month());
        Integer DaysDiff = EffectiveDate.daysBetween(date.newInstance(EffectiveDate.Year(), EffectiveDate.Month(), DaysinThisMonth)) + 1;
        dblCPILumpSum = (EffectiveDate.MonthsBetween(AcceptanceDate.AddMonths(-1)) * MonthlyAmount);
        dblCPILumpSum += (DaysDiff * MonthlyAmount)/DaysinThisMonth; //Effective Month proration 
        Return dblCPILumpSum;
    }
    
    // **** RUN all the TEST methods for code coverage ... ****//    
    private static testmethod void testReconciliationSummaryTotalsController() {
        
        GalaxyReconciliationBatch__c objCustomSettings = New GalaxyReconciliationBatch__c(
            CustomRunDate__c = Datetime.Now().Date()
        );
        insert objCustomSettings;
        
        List<Glxy_Lease__c> objLeaseLeaseRecords = New List<Glxy_Lease__c>();
        
        Glxy_Lease__c ObjLease = new Glxy_Lease__c();
        ObjLease.Name = 'LDE00374';
        ObjLease.StatusCode__c = 'Active';
        ObjLease.REXUSStatusCode__c = 'Active';
        ObjLease.BaseAnnualRent__c = 1200;
        ObjLease.BaseLeaseEffectiveDate__c = date.newinstance(date.today().Year(), 1, 1);
        ObjLease.ExpirationDateofLease__c = date.newinstance(date.today().Year() + 5, 1, 1);
        ObjLease.RegionCD__c = '1';
        ObjLease.Total_NOA_Sq_feet__c = 10;
        ObjLease.Total_IA_Sq_feet__c = 20;
        objLease.DelegatedLease__c = false;
        objLease.IAConverstionDate__c = date.newinstance(date.today().Year(), 1, 1);
        //insert ObjLease;
        objLeaseLeaseRecords.Add(ObjLease);
        
        Glxy_Lease__c ObjLease2 = new Glxy_Lease__c();
        ObjLease2.Name = 'LDE00370';
        ObjLease2.StatusCode__c = 'Active';
        ObjLease2.REXUSStatusCode__c = 'Active';
        ObjLease2.BaseAnnualRent__c = 1200;
        ObjLease2.BaseLeaseEffectiveDate__c = date.newinstance(date.today().Year(), 1, 1);
        ObjLease2.ExpirationDateofLease__c = date.newinstance(date.today().Year() + 5, 1, 1);
        ObjLease2.RegionCD__c = '1';
        ObjLease2.Total_NOA_Sq_feet__c = 10;
        ObjLease2.Total_IA_Sq_feet__c = 20;
        objLease2.DelegatedLease__c = false;
        objLease2.IAConverstionDate__c = date.newinstance(date.today().Year() + 2, 1, 1);
        //insert ObjLease2;
        objLeaseLeaseRecords.Add(ObjLease2);
        
        Insert objLeaseLeaseRecords;
        
        List<Glxy_ConsumerPriceIndex__c> objCPIRecords = New List<Glxy_ConsumerPriceIndex__c>();
        Glxy_ConsumerPriceIndex__c objTest1 = new Glxy_ConsumerPriceIndex__c (
            LeaseNumber__c = objLease.id,
            EffectiveDate__c = Datetime.Now().Date().adddays(-31),
            FY_Obligation__c = 0,
            StatusCd__c = 'Actual',
            Acceptance620Date__c = Datetime.Now().Date().adddays(-31)
        );
        objCPIRecords.Add(objTest1);
        Glxy_ConsumerPriceIndex__c objTest12 = new Glxy_ConsumerPriceIndex__c (
            LeaseNumber__c = objLease2.id,
            EffectiveDate__c = Datetime.Now().Date().adddays(-31),
            FY_Obligation__c = 0,
            StatusCd__c = 'Actual',
            Acceptance620Date__c = Datetime.Now().Date().adddays(-31)
        );
        objCPIRecords.Add(objTest12);
        insert objCPIRecords;

       	GLXY_ReconciliationSummaryTotals3 objTest3 = new GLXY_ReconciliationSummaryTotals3();
        objTest3.CalculateTotals();
        System.Assert(objTest3!=NULL);
        Decimal outputD =  objTest3.fnReturnCPILumpSum(Datetime.Now().Date().adddays(-31), Datetime.Now().Date().adddays(-10), 100);

       
    } 
}