src/objects/Glxy_BudgetCallLineItem__c.object
<CustomObject>
    <fields>
        <fullName>AnnualAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Annual Amount</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BudgetCategory__c</fullName>
        <label>Budget Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Base Rent</fullName>
                </value>
                <value>
                    <fullName>Cancellation</fullName>
                </value>
                <value>
                    <fullName>Double Rent</fullName>
                </value>
                <value>
                    <fullName>Expansion</fullName>
                </value>
                <value>
                    <fullName>IBAA</fullName>
                </value>
                <value>
                    <fullName>Lump Sums</fullName>
                </value>
                <value>
                    <fullName>Operating Cost Escalation (CPI)</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Project Step Rent</fullName>
                </value>
                <value>
                    <fullName>Rent Increase</fullName>
                </value>
                <value>
                    <fullName>RWA</fullName>
                </value>
                <value>
                    <fullName>Step Rent</fullName>
                </value>
                <value>
                    <fullName>Total</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Taxes</fullName>
                </value>
                <value>
                    <fullName>Project Lump Sums</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CancellationSqFt__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Cancellation Sq Ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DataGroup__c</fullName>
        <label>Data Group</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DelegatedLease__c</fullName>
        <label>Delegated Lease</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExpansionSqFt__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Expansion Sq Ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FiscalYear__c</fullName>
        <label>Fiscal Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IAConversionFY__c</fullName>
        <label>IAConversionFY</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LeaseNumber__c</fullName>
        <label>Lease Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LeaseStatus__c</fullName>
        <label>Lease Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lease_Expiration_Date__c</fullName>
        <label>Lease Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RegionCode__c</fullName>
        <label>Region Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SquareFeet__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Square Feet</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TeamCode__c</fullName>
        <label>Team Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Budget Call Line Item</label>
    <nameField>
        <displayFormat>LI-{0000}</displayFormat>
        <label>Budget Call Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Call Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GLXY_BC_QueryLocatorAggregatorFY2.cls
global with sharing class GLXY_BC_QueryLocatorAggregatorFY2 implements Iterator<AggregateResult> {
	
	AggregateResult [] DataPage {get;set;} 
	Integer pageindex {get; set;}  
	Integer intCurrentFY;
	String 	strCurrentFY;
	String 	strNextFiscalYear;
	String 	strNextFiscalYear2;
			
	global GLXY_BC_QueryLocatorAggregatorFY2() { 
		intCurrentFY = Datetime.Now().Date().Month() > 9? Datetime.Now().Date().Year() + 1 : Datetime.Now().Date().Year();
	 	strCurrentFY = String.ValueOf(intCurrentFY);      
		strNextFiscalYear = String.ValueOf(intCurrentFY + 1);
		strNextFiscalYear2 = String.ValueOf(intCurrentFY + 2);
		
		pageindex = 0;
		string Query =  'SELECT   LeaseNumber__c, Sum(AnnualAmount__c) AnnualAmount, ' + 
				'		  Sum(SquareFeet__c) SquareFeet, Sum(CancellationSqFt__c) CancelSquareFeet, Sum(ExpansionSqFt__c) ExpanSquareFeet, ' +  
				'		  Max(IAConversionFY__c) IAConversionFY, Max(DelegatedLease__c) DelegatedLease, ' + 
				'		  Max(RegionCode__c) RegionCode, Max(Lease_Expiration_Date__c) LeaseExpirationDate, Max(TeamCode__c) TeamCode, Max(LeaseStatus__c) LeaseStatus ' + 
		        'FROM  	  Glxy_BudgetCallLineItem__c ' +
		        'Where   ((BudgetCategory__c  = \'Base Rent\' And FiscalYear__c = :strCurrentFY) ' +  
		        'OR    	 (BudgetCategory__c  in (\'Step Rent\', \'Project Step Rent\', \'Operating Cost Escalation (CPI)\') And FiscalYear__c <= :strNextFiscalYear) ' +  
		        'OR    	 (BudgetCategory__c Like \'Project - %\' And FiscalYear__c <= :strNextFiscalYear)) ' +
	        	'And      RegionCode__c in (\'1\',\'2\',\'3\',\'4\',\'5\',\'6\') ' +
		        'And      LeaseNumber__c != null ' +
		        'And      (DataGroup__c = \'NOA\' Or (DataGroup__c = \'IA\' And IAConversionFY__c != Null And IAConversionFY__c <= :strNextFiscalYear2)) ' +
		        'Group by LeaseNumber__c ' + 
		        'ORDER BY LeaseNumber__c ';   
		DataPage = Database.query(Query);                         
	}
	
	global boolean hasNext(){  
		return DataPage != null && !DataPage.isEmpty() && pageindex < DataPage.size();  
	}
	
	global AggregateResult next(){
		return DataPage[pageindex++];
	}
	
}