src/objects/Glxy_BudgetCallLineItem__c.object
<CustomObject>
    <fields>
        <fullName>AnnualAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Annual Amount</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Apr__c</fullName>
        <label>Apr</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Aug__c</fullName>
        <label>Aug</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BudgetCategory__c</fullName>
        <label>Budget Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Base Rent</fullName>
                </value>
                <value>
                    <fullName>Cancellation</fullName>
                </value>
                <value>
                    <fullName>Double Rent</fullName>
                </value>
                <value>
                    <fullName>Expansion</fullName>
                </value>
                <value>
                    <fullName>IBAA</fullName>
                </value>
                <value>
                    <fullName>Lump Sums</fullName>
                </value>
                <value>
                    <fullName>Operating Cost Escalation (CPI)</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Project Step Rent</fullName>
                </value>
                <value>
                    <fullName>Rent Increase</fullName>
                </value>
                <value>
                    <fullName>RWA</fullName>
                </value>
                <value>
                    <fullName>Step Rent</fullName>
                </value>
                <value>
                    <fullName>Total</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Taxes</fullName>
                </value>
                <value>
                    <fullName>Project Lump Sums</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CancellationAnnualRent__c</fullName>
        <label>Cancellation Annual Rent</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CancellationPartYearCost__c</fullName>
        <label>Cancellation Part Year Cost</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CancellationSqFt__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Cancellation Sq Ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DataGroup__c</fullName>
        <label>Data Group</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dec__c</fullName>
        <label>Dec</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>DelegatedLease__c</fullName>
        <label>Delegated Lease</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EscalationAnnualRent__c</fullName>
        <label>Escalation Annual Rent</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>EscalationPartYearCost__c</fullName>
        <label>Escalation Part Year Cost</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>EscalationSqFt__c</fullName>
        <label>Escalation Sq Ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ExpansionAnnualRent__c</fullName>
        <label>Expansion Annual Rent</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ExpansionPartYearCost__c</fullName>
        <label>Expansion Part Year Cost</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ExpansionSqFt__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Expansion Sq Ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Feb__c</fullName>
        <label>Feb</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FiscalYear__c</fullName>
        <label>Fiscal Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IAConversionFY__c</fullName>
        <label>IAConversionFY</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Jan__c</fullName>
        <label>Jan</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Jul__c</fullName>
        <label>Jul</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Jun__c</fullName>
        <label>Jun</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LeaseNumber__c</fullName>
        <label>Lease Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LeaseStatus__c</fullName>
        <label>Lease Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lease_Expiration_Date__c</fullName>
        <label>Lease Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Mar__c</fullName>
        <label>Mar</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>May__c</fullName>
        <label>May</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Nov__c</fullName>
        <label>Nov</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Oct__c</fullName>
        <label>Oct</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>RegionCode__c</fullName>
        <label>Region Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sep__c</fullName>
        <label>Sep</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SquareFeet__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Square Feet</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TeamCode__c</fullName>
        <label>Team Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Budget Call Line Item</label>
    <nameField>
        <displayFormat>LI-{0000}</displayFormat>
        <label>Budget Call Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Call Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GLXY_BC_QueryLocatorAggregatorTotals.cls
global with sharing class GLXY_BC_QueryLocatorAggregatorTotals implements Iterator<AggregateResult> {
	
	AggregateResult [] DataPage {get;set;} 
	Integer pageindex {get; set;}  
	//Integer intCurrentFY = 0;
	//String 	strCurrentFY, strCurrentFY2;
			
	global GLXY_BC_QueryLocatorAggregatorTotals(string strFiscalYear) { 
		//intCurrentFY += Datetime.Now().Date().Month() > 9? Datetime.Now().Date().Year() + 1 : Datetime.Now().Date().Year();
	 	//strCurrentFY = String.ValueOf(intCurrentFY);
		//strCurrentFY2 = String.ValueOf(intCurrentFY + 2);
		
		pageindex = 0; 
		string Query =  'SELECT  LeaseNumber__c, FiscalYear__c, RegionCode__c RegionCode, DataGroup__c, ' +  
        				'		 Max(IAConversionFY__c) IAConversionFY, Max(DelegatedLease__c) DelegatedLease, ' + 
        				'		 Max(TeamCode__c) TeamCode, Max(Lease_Expiration_Date__c) LeaseExpirationDate, Max(LeaseStatus__c) LeaseStatus, ' + 
        				' 		 Sum(AnnualAmount__c) AnnualAmount, Sum(SquareFeet__c) SquareFeet, ' + 
        				'		 Sum(Apr__c) April, Sum(Aug__c) August, Sum(CancellationAnnualRent__c) CancellationAnnualRent, ' +  
        				'		 Sum(CancellationPartYearCost__c) CancellationPartYearCost,  Sum(CancellationSqFt__c) CancellationSqFt, ' +  
        				'		 Sum(Dec__c) December, Sum(EscalationAnnualRent__c) EscalationAnnualRent, ' +  
        				'		 Sum(EscalationPartYearCost__c) EscalationPartYearCost, Sum(EscalationSqFt__c) EscalationSqFt, ' +  
        				'		 Sum(ExpansionAnnualRent__c) ExpansionAnnualRent, Sum(ExpansionPartYearCost__c) ExpansionPartYearCost, ' +  
        				'		 Sum(ExpansionSqFt__c) ExpansionSqFt, Sum(Feb__c) February, ' +  
        				'		 Sum(Jan__c) January, ' +  
    				    '		 Sum(Jul__c) July, Sum(Jun__c) June, Sum(Mar__c) March, ' +  
        				'		 Sum(May__c) May, Sum(Nov__c) November, Sum(Oct__c) October, Sum(Sep__c) September ' + 
                        'FROM  	 Glxy_BudgetCallLineItem__c ' +
                        'Where 	 FiscalYear__c = :strFiscalYear ' +
                        'And  	 ( BudgetCategory__c Like \'Base Rent%\' OR BudgetCategory__c Like \'Project - %\' ) ' +
                        'Group by FiscalYear__c, RegionCode__c, LeaseNumber__c, DataGroup__c ' + 
                        'ORDER BY FiscalYear__c, RegionCode__c, LeaseNumber__c, DataGroup__c';
		DataPage = Database.query(Query);             
	}
	
	global boolean hasNext(){  
		return DataPage != null && !DataPage.isEmpty() && pageindex < DataPage.size();  
	}
	
	global AggregateResult next(){
		return DataPage[pageindex++];
	}
	
}