src/objects/Glxy_Lease__c.object
<CustomObject>
    <customHelpPage>GLXY_HelpPage</customHelpPage>
    <description>This table contains lease information at the beginning of the fiscal year.  This information is updated at the beginning of each fiscal year.</description>
    <fields>
        <fullName>BaseLeaseEffectiveDate__c</fullName>
        <label>Lease Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BaseSquareFeet__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Base Sq Ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BaseStructuredParkingSpaces__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Parking spaces available in a parking structure/garage.</description>
        <label>Base Structured Parking Spaces</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BaseSurfaceParkingSpaces__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Parking spaces available in a parking lot.</description>
        <label>Base Surface Parking Spaces</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ExpirationDateofLease__c</fullName>
        <description>Expiration Date</description>
        <label>Lease Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LeaseID__c</fullName>
        <externalId>true</externalId>
        <label>Lease ID</label>
        <length>8</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>RegionCD__c</fullName>
        <description>Region Code</description>
        <label>Region Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StatusCode__c</fullName>
        <description>Status Code</description>
        <inlineHelpText>Current status of during G2 Base Sertting period. Options are Active, Terminated, Pending.
DL	Deleted
PD	Pending
TM	Terminated
AC	Active</inlineHelpText>
        <label>Status Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_IA_Sq_feet__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total IA Sq ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_NOA_Sq_feet__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total NOA Sq ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Lease</label>
    <nameField>
        <label>Lease Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Glxy_LeaseAgencies__c.object
<CustomObject>
    <description>This table contains the Agency Space Assignments (ASA) data for Leases.</description>
    <fields>
        <fullName>ABCode__c</fullName>
        <formula>PBSABCode__r.AB_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AB Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASAIAAnnualRent__c</fullName>
        <formula>LeaseNumber__r.IA_Cost_Per_Sq_Ft__c *  ASA_IASqFt__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ASA IA Annual Rent</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ASAID__c</fullName>
        <externalId>true</externalId>
        <label>ASAID</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ASANOAAnnualRent__c</fullName>
        <formula>(LeaseNumber__r.NOA_Rate_Per_Sq_Ft__c) *  (ASA_NOASqFt__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ASA NOA Annual Rent</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ASA_IASqFt__c</fullName>
        <formula>IF((LeaseNumber__r.Total_IA_Sq_feet__c + LeaseNumber__r.Total_NOA_Sq_feet__c)=0,0,(LeaseNumber__r.Total_IA_Sq_feet__c / ( LeaseNumber__r.Total_IA_Sq_feet__c + LeaseNumber__r.Total_NOA_Sq_feet__c )) *  SquareFeet__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ASA IA Sq Ft</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASA_NOASqFt__c</fullName>
        <formula>IF(( LeaseNumber__r.Total_IA_Sq_feet__c + LeaseNumber__r.Total_NOA_Sq_feet__c )=0,0,(LeaseNumber__r.Total_NOA_Sq_feet__c / ( LeaseNumber__r.Total_IA_Sq_feet__c + LeaseNumber__r.Total_NOA_Sq_feet__c )) *  SquareFeet__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ASA NOA Sq Ft</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASA__c</fullName>
        <label>ASA</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Agency_Bureau_Name__c</fullName>
        <formula>PBSABCode__r.Agency_Bureau_Short_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Agency Bureau Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BaseStructuredParkingSpaces__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Base Structured Parking Spaces</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BaseSurfaceParkingSpaces__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Base Surface Parking Spaces</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LeaseNumber__c</fullName>
        <label>Lease Number</label>
        <referenceTo>Glxy_Lease__c</referenceTo>
        <relationshipName>Lease_Agencies</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>REXUSABCode__c</fullName>
        <formula>REXUSPBSABCode__r.AB_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>REXUS AB Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>REXUSASAIAAnnualRent__c</fullName>
        <formula>LeaseNumber__r.IA_Cost_Per_Sq_Ft__c * REXUSASA_IASqFt__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>REXUS ASA IA Annual Rent</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>REXUSASANOAAnnualRent__c</fullName>
        <formula>LeaseNumber__r.NOA_Rate_Per_Sq_Ft__c * REXUSASA_NOASqFt__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>REXUS ASA NOA Annual Rent</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>REXUSASA_IASqFt__c</fullName>
        <formula>IF((LeaseNumber__r.Total_IA_Sq_feet__c + LeaseNumber__r.Total_NOA_Sq_feet__c)=0,0,(LeaseNumber__r.Total_IA_Sq_feet__c / ( LeaseNumber__r.Total_IA_Sq_feet__c + LeaseNumber__r.Total_NOA_Sq_feet__c )) * REXUSSquareFeet__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>REXUS ASA IA Sq Ft</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>REXUSASA_NOASqFt__c</fullName>
        <formula>IF(( LeaseNumber__r.Total_IA_Sq_feet__c + LeaseNumber__r.Total_NOA_Sq_feet__c )=0,0,(LeaseNumber__r.Total_NOA_Sq_feet__c / ( LeaseNumber__r.Total_IA_Sq_feet__c + LeaseNumber__r.Total_NOA_Sq_feet__c )) * REXUSSquareFeet__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>REXUS ASA NOA Sq Ft</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>REXUSASA__c</fullName>
        <label>REXUS ASA</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>REXUSAgencyBureauName__c</fullName>
        <formula>REXUSPBSABCode__r.Agency_Bureau_Short_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>REXUS Agency Bureau Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>REXUSBaseStructuredParkingSpaces__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Parking spaces available in a parking structure/garage. (REXUS current Value)</description>
        <label>REXUS Base Structured Parking Spaces</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>REXUSBaseSurfaceParkingSpaces__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Parking spaces available in a parking lot. (REXUS current Value)</description>
        <label>REXUS Base Surface Parking Spaces</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>REXUSSquareFeet__c</fullName>
        <defaultValue>0</defaultValue>
        <description>SQ Ft assigned at ASA Level (REXUS current Value)</description>
        <label>REXUS SquareFeet</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SquareFeet__c</fullName>
        <label>Square Feet</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Lease Agency</label>
    <nameField>
        <displayFormat>ADA-{00000000}</displayFormat>
        <label>Lease Agency ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lease Agencies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Glxy_LeaseAgencyRelatedList.cls
public with sharing class Glxy_LeaseAgencyRelatedList {
	
	Private final Glxy_Lease__c ObjLease;
	Public List<Glxy_LeaseAgencies__c> LeaseAgencies{get;set;}
	
	public Glxy_LeaseAgencyRelatedList(ApexPages.StandardController controller) {
		ObjLease = (Glxy_Lease__c)controller.getRecord();
	}
	
    public Glxy_LeaseAgencies__c[] GetLeaseAgencyRelatedListBase() {
       Glxy_Lease__c ObjLease = [select LeaseID__c from Glxy_Lease__c where id =:ObjLease.id];
	   LeaseAgencies = [select id, Name, ABCode__c, Agency_Bureau_Name__c, ASA__c, ASAIAAnnualRent__c, ASA_IASqFt__c, ASAID__c, ASANOAAnnualRent__c, ASA_NOASqFt__c, BaseStructuredParkingSpaces__c, BaseSurfaceParkingSpaces__c, SquareFeet__c from Glxy_LeaseAgencies__c Where LeaseNumber__c = :ObjLease.ID and ASA__c != null] ;
	   Return LeaseAgencies;
    }
    
    public Glxy_LeaseAgencies__c[] GetLeaseAgencyRelatedListREXUS() {
       Glxy_Lease__c ObjLease = [select LeaseID__c from Glxy_Lease__c where id =:ObjLease.id];
	   LeaseAgencies = [select id, Name, REXUSABCode__c, REXUSAgencyBureauName__c, REXUSASA__c, REXUSASAIAAnnualRent__c, REXUSASA_IASqFt__c, ASAID__c, REXUSASANOAAnnualRent__c, REXUSASA_NOASqFt__c, REXUSBaseStructuredParkingSpaces__c, REXUSBaseSurfaceParkingSpaces__c, REXUSSquareFeet__c from Glxy_LeaseAgencies__c Where LeaseNumber__c = :ObjLease.ID And REXUSASA__c != null] ;
	   Return LeaseAgencies;
    }
    
	@isTest static void Test_Glxy_LeaseAgencyRelatedList(){
		Glxy_Lease__c lease= new Glxy_Lease__c();
	   	lease.StatusCode__c = 'Active';
	   	Date myDate = date.newinstance(2012, 2, 17);
	   	Date myDate1 = date.newinstance(2013, 2, 17);
	   	lease.BaseLeaseEffectiveDate__c = myDate ;
	   	lease.ExpirationDateofLease__c = myDate1 ;
	   	lease.RegionCD__c = '3';
	   	lease.Total_NOA_Sq_feet__c = 1000;
	   	lease.Total_IA_Sq_feet__c = 1000;
	   	lease.BaseSquareFeet__c = 2000;
   		insert lease;
   		system.assertNotEquals(NULL,lease);
   		
	   	Glxy_LeaseAgencies__c pi = new Glxy_LeaseAgencies__c();
	   	pi.LeaseNumber__c=lease.id;
	   	pi.ASA__c = 'AB11';
	   	pi.SquareFeet__c = 100;
	   	insert pi;
	   	
	   	Glxy_LeaseAgencies__c pi2 = new Glxy_LeaseAgencies__c();
	   	pi2.LeaseNumber__c=lease.id;
	   	pi2.ASA__c = 'AB11';
	   	pi2.SquareFeet__c = 0;
	   	pi2.REXUSASA__c = 'ASA2';
	   	insert pi2;
   		
   		ApexPages.StandardController con = new ApexPages.StandardController(lease);
   		Glxy_LeaseAgencyRelatedList rl =  new Glxy_LeaseAgencyRelatedList(con);
   		List <Glxy_LeaseAgencies__c> reportResults1 = rl.GetLeaseAgencyRelatedListREXUS();
   		List <Glxy_LeaseAgencies__c> reportResults2 = rl.GetLeaseAgencyRelatedListBase();
   		
	}
    
    
}