src/objects/Glxy_AssociatedLeases__c.object
<CustomObject>
    <fields>
        <fullName>Lease__c</fullName>
        <label>Lease</label>
        <referenceTo>Glxy_Lease__c</referenceTo>
        <relationshipName>Associated_Leases</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project Number</label>
        <referenceTo>Glxy_LeaseProjects__c</referenceTo>
        <relationshipLabel>Associated Leases/Projects</relationshipLabel>
        <relationshipName>Associated_Leases</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Associated Leases/Projects</label>
    <nameField>
        <displayFormat>LP-{00000}</displayFormat>
        <label>Associated Leases</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Leases/Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Glxy_DoubleRent__c.object
<CustomObject>
    <fields>
        <fullName>Apr_IA__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Apr IA</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Apr_NOA__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Apr NOA</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Associated_Leases_Projects_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Associated Leases/Projects</label>
        <referenceTo>Glxy_AssociatedLeases__c</referenceTo>
        <relationshipLabel>Double Rents</relationshipLabel>
        <relationshipName>Double_Rents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Aug_IA__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Aug IA</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Aug_NOA__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Aug NOA</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Dec_IA__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Dec IA</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Dec_NOA__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Dec NOA</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FY_Obligation_IA__c</fullName>
        <formula>Apr_IA__c + May_IA__c + Jun_IA__c + Jul_IA__c + Aug_IA__c + Sep_IA__c + Oct_IA__c + Nov_IA__c + Dec_IA__c + JAN_IA__c + Feb_IA__c + Mar_IA__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>FY Obligation IA</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FY_Obligation_NOA__c</fullName>
        <formula>Apr_NOA__c + May_NOA__c + Jun_NOA__c + Jul_NOA__c + Aug_NOA__c + Sep_NOA__c + Oct_NOA__c + Nov_NOA__c + Dec_NOA__c + JAN_NOA__c + Feb_NOA__c + Mar_NOA__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>FY Obligation NOA</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FY_Obligation__c</fullName>
        <formula>FY_Obligation_IA__c + FY_Obligation_NOA__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>FY Obligation</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Feb_IA__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Feb IA</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Feb_NOA__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Feb NOA</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Fiscal_Year__c</fullName>
        <label>Fiscal Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>JAN_IA__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Jan IA</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>JAN_NOA__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Jan NOA</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Jul_IA__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Jul IA</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Jul_NOA__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Jul NOA</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Jun_IA__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Jun IA</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Jun_NOA__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Jun NOA</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Mar_IA__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Mar IA</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Mar_NOA__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Mar NOA</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>May_IA__c</fullName>
        <defaultValue>0</defaultValue>
        <label>May IA</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>May_NOA__c</fullName>
        <defaultValue>0</defaultValue>
        <label>May NOA</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Nov_IA__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Nov IA</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Nov_NOA__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Nov NOA</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Oct_IA__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Oct IA</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Oct_NOA__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Oct NOA</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Sep_IA__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Sep IA</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Sep_NOA__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Sep NOA</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Double Rent</label>
    <nameField>
        <displayFormat>DR-{000000}</displayFormat>
        <label>Double Rent Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Double Rents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Glxy_Lease__c.object
<CustomObject>
    <customHelpPage>GLXY_HelpPage</customHelpPage>
    <description>This table contains lease information at the beginning of the fiscal year.  This information is updated at the beginning of each fiscal year.</description>
    <label>Lease</label>
    <nameField>
        <label>Lease Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Glxy_LeaseProjects__c.object
<CustomObject>
    <customHelpPage>GLXY_HelpPage</customHelpPage>
    <description>This table contains information on all the New, Renewal, Extension, Succeeding, Superseding, Terminating, Chg in SF, and New/Replacing leases associated with a Project.  The Project is the starting point for new leases or changes to existing leases.</description>
    <label>Lease Project</label>
    <nameField>
        <label>Project Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lease Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/GLXY_BC_QueryLocatorDoubleRent.cls
global with sharing class GLXY_BC_QueryLocatorDoubleRent implements Iterator<AggregateResult> {
	
	AggregateResult [] DataPage {get;set;} 
	Integer pageindex {get; set;}  
			
	global GLXY_BC_QueryLocatorDoubleRent() { 
		pageindex = 0;
		Integer IntCurrentFY = Datetime.Now().Date().Month() > 9? Datetime.Now().Date().Year() + 1 : Datetime.Now().Date().Year();
		string strCurrentFY = String.ValueOf(IntCurrentFY);
		string strCurrentFY2 = String.ValueOf(intCurrentFY + 2);
		 
		string query =   'Select Associated_Leases_Projects_ID__r.Lease__r.ID LeaseID, Max(Associated_Leases_Projects_ID__r.Lease__r.Name) LeaseNumber, ' +
						 '		 Max(Associated_Leases_Projects_ID__r.Lease__r.RegionCD__c) Region, Max(Associated_Leases_Projects_ID__r.Lease__r.ExpirationDateofLease__c) LeaseExpirationDate, Max(Associated_Leases_Projects_ID__r.Lease__r.TeamCode__c) TeamCode, ' +
						 ' 		 Fiscal_Year__c FiscalYear, Associated_Leases_Projects_ID__r.Project__r.eEorA__c StatusCode, Sum(FY_Obligation__c) AnnualAmount, Sum(FY_Obligation_IA__c) AnnualAmountIA, Sum(FY_Obligation_NOA__c) AnnualAmountNOA, ' +
						 '       Sum(JAN_IA__c) JANIA, Sum(FEB_IA__c) FEBIA, Sum(MAR_IA__c) MARIA, Sum(APR_IA__c) APRIA, Sum(MAY_IA__c) MAYIA, Sum(JUN_IA__c) JUNIA, Sum(JUL_IA__c) JULIA, Sum(AUG_IA__c) AUGIA, Sum(SEP_IA__c) SEPIA, Sum(OCT_IA__c) OCTIA, Sum(NOV_IA__c) NOVIA, Sum(DEC_IA__c) DECIA, ' +
                		 '       Sum(JAN_NOA__c) JANNOA, Sum(FEB_NOA__c) FEBNOA, Sum(MAR_NOA__c) MARNOA, Sum(APR_NOA__c) APRNOA, Sum(MAY_NOA__c) MAYNOA, Sum(JUN_NOA__c) JUNNOA, Sum(JUL_NOA__c) JULNOA, Sum(AUG_NOA__c) AUGNOA, Sum(SEP_NOA__c) SEPNOA, Sum(OCT_NOA__c) OCTNOA, Sum(NOV_NOA__c) NOVNOA, Sum(DEC_NOA__c) DECNOA ' + 
               			 'From   Glxy_DoubleRent__c ' +
               			 'Where  Associated_Leases_Projects_ID__r.Project__r.BDGFlag__c = true ' +
               			 'And    Associated_Leases_Projects_ID__c <> \'\' ' +
               			 'And  	 Associated_Leases_Projects_ID__r.Project__r.ProjectStatus__c <> \'Cancelled\' ' +
               			 'AND    Fiscal_Year__c >= :strCurrentFY ' +
                         'AND    Fiscal_Year__c <= :strCurrentFY2 ' +
	       				 'Group by  Associated_Leases_Projects_ID__r.Lease__r.ID, Fiscal_Year__c, Associated_Leases_Projects_ID__r.Project__r.eEorA__c ' +
 	 					 'ORDER BY  Associated_Leases_Projects_ID__r.Lease__r.ID, Fiscal_Year__c, Associated_Leases_Projects_ID__r.Project__r.eEorA__c ';
		System.debug('MyDebug = ' + query);
		DataPage = Database.query(query);             
	}
	
	global boolean hasNext(){  
		return DataPage != null && !DataPage.isEmpty() && pageindex < DataPage.size();  
	}
	
	global AggregateResult next(){
		return DataPage[pageindex++];
	}
	
}