src/objects/Glxy_BudgetSubmission__c.object
<CustomObject>
    <fields>
        <fullName>ReportingFiscalYear__c</fullName>
        <label>Reporting Fiscal Year</label>
        <length>4</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubmissionType__c</fullName>
        <label>Submission Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Budget Call</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>OMB</fullName>
                </value>
                <value>
                    <fullName>Congressional Justification</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Budget Submission</label>
    <nameField>
        <displayFormat>BudgetID-{0000}</displayFormat>
        <label>Budget Submission ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Submission</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Glxy_BudgetSubmissionData__c.object
<CustomObject>
    <fields>
        <fullName>AnnualCancellationsAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Lease Cancellations Obligations</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AnnualCancellationsSqFt__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Lease Cancellations  Sq Ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AnnualExpansionIAAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Lease Expansion - IA Obligations</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AnnualExpansionIASqFt__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Lease Expansion - IA Sq Ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AnnualExpansionNOAAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Lease Expansion - NOA Obligations</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AnnualExpansionNOASqFt__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Lease Expansion - NOA Sq Ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AnnualLumpSumAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Lump Sum - Taxes; Lease Buyouts</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AnnualRentIncreaseAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Rental Increases Obligations</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AnnualRentIncreaseSqFt__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Rental Increases Sq Ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AnticipatedRecoveries__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Anticipated Recoveries</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BaseCostAmount__c</fullName>
        <formula>PriorYearCostAmount__c + AnnualRentIncreaseAmount__c + AnnualLumpSumAmount__c  +   AnnualCancellationsAmount__c + AnnualExpansionNOAAmount__c + IAToNOAAmount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BASE COST Obligations</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BaseCostSqFt__c</fullName>
        <formula>PriorYearCostSqFt__c +  IAToNOASqFt__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BASE COST  Sq Ft</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BudgetSubmissionID__c</fullName>
        <label>Budget Submission ID</label>
        <referenceTo>Glxy_BudgetSubmission__c</referenceTo>
        <relationshipLabel>Budget Submission Data</relationshipLabel>
        <relationshipName>Budget_Submission_Data</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CancellationsIAAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Lease Cancellations IA Obligations</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CancellationsIASqFt__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Lease Cancellations IA Sq Ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CancellationsNOAAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Lease Cancellations NOA Obligations</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CancellationsNOASqFt__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Lease Cancellations NOA Sq Ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CurrentYearCostAmount__c</fullName>
        <formula>BaseCostAmount__c + RentIncreaseNOAAmount__c + RentIncreaseIAAmount__c +  LumpSumNOAAmount__c + LumpSumIAAmount__c +  CancellationsNOAAmount__c + CancellationsIAAmount__c +  ExpansionNOAAmount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CURRENT YEAR COST  Obligations</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CurrentYearCostSqFt__c</fullName>
        <formula>BaseCostSqFt__c + CancellationsNOASqFt__c + CancellationsIASqFt__c +   ExpansionNOASqFt__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CURRENT YEAR COST Sq Ft</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ExpansionIAAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Lease Expansion - IA Obligations</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ExpansionIASqFt__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Lease Expansion - IA Sq Ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ExpansionNOAAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Lease Expansion - NOA Obligations</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ExpansionNOASqFt__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Lease Expansion - NOA Sq Ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FiscalYear__c</fullName>
        <label>Fiscal Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IAObligationsMinus__c</fullName>
        <defaultValue>0</defaultValue>
        <label>IA Obligations (-)</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>IAObligations__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Indefinite Authority (IA) Obligations</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>IASqFt__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Indefinite Authority (IA)  Sq Ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IAToNOAAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Lease Expansion IA to NOA Obligations</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>IAToNOASqFt__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Lease Expansion IA to NOA Sq Ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LumpSumIAAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Lump Sum - Taxes; Lease Buyouts - IA</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LumpSumNOAAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Lump Sum - Taxes; Lease Buyouts - NOA</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NOAObligationsMinus__c</fullName>
        <formula>CurrentYearCostAmount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>NOA Obligations (-)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NOAObligations__c</fullName>
        <defaultValue>0</defaultValue>
        <label>New Obligational Authority (NOA) Obligat</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NOASqFt__c</fullName>
        <formula>CurrentYearCostSqFt__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>New Obligational Authority (NOA)  Sq Ft</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PriorYearBalances__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Prior Year Balances</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PriorYearCostAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>PRIOR YEAR COST Obligations</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PriorYearCostSqFt__c</fullName>
        <defaultValue>0</defaultValue>
        <label>PRIOR YEAR COST  Sq Ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RecessionMinus__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Recission (-)</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>Text(BudgetSubmissionID__r.RegionCD__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RentIncreaseIAAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Rental Increases - IA Obligations</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>RentIncreaseIASqFt__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Rental Increases - IA Sq Ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RentIncreaseNOAAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Rental Increases - NOA Obligations</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>RentIncreaseNOASqFt__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Rental Increases - NOA Sq Ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ReportingFiscalYear__c</fullName>
        <formula>BudgetSubmissionID__r.ReportingFiscalYear__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Reporting Fiscal Year</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reprogrammings__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Reprogrammings (-)</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SubmissionType__c</fullName>
        <formula>Text(BudgetSubmissionID__r.SubmissionType__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Submission Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TotalCurrentYearObligations__c</fullName>
        <formula>NOAObligationsMinus__c +  IAObligationsMinus__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Current Year Obligations</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TotalObligations__c</fullName>
        <formula>NOAObligations__c +  IAObligations__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Current Year Authority Obligations</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TotalSqFt__c</fullName>
        <formula>NOASqFt__c +  IASqFt__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Current Year Authority Sq Ft</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UnobligatedBalances__c</fullName>
        <formula>NOAObligations__c +  PriorYearBalances__c +  AnticipatedRecoveries__c -  NOAObligationsMinus__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unobligated Balances</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Budget Submission Data</label>
    <nameField>
        <displayFormat>ID-{0000}</displayFormat>
        <label>Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Submission Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Glxy_BC_3ColumnChart.cls
public with sharing class Glxy_BC_3ColumnChart {
 	
 	public String strReportingYear 	{get; set;}
    public String strSubmissionType {get; set;}
    public String strRegion        	{get; set;}
    public String strDataFormat  	{get; set;}
    
    public String FiscalYear1 {get; set;}
    public Decimal AnticipatedRecoveries1 {get; set;}
	public Decimal BaseCostAmount1 {get; set;}
	public Decimal BaseCostSqFt1 {get; set;}
	public Decimal CurrentYearCostAmount1 {get; set;}
	public Decimal CurrentYearCostSqFt1 {get; set;}
	public Decimal IAObligationsMinus1 {get; set;}
	public Decimal IAObligations1 {get; set;}
	public Decimal IASqFt1 {get; set;}
	public Decimal CancellationsIAAmount1 {get; set;}
	public Decimal CancellationsIASqFt1 {get; set;}
	public Decimal CancellationsNOAAmount1 {get; set;}
	public Decimal CancellationsNOASqFt1 {get; set;}
	public Decimal AnnualCancellationsAmount1 {get; set;}
	public Decimal AnnualCancellationsSqFt1 {get; set;}
	public Decimal AnnualExpansionIAAmount1 {get; set;}
	public Decimal ExpansionIAAmount1 {get; set;}
	public Decimal AnnualExpansionIASqFt1 {get; set;}
	public Decimal ExpansionIASqFt1 {get; set;}
	public Decimal IAToNOAAmount1 {get; set;}
	public Decimal IAToNOASqFt1 {get; set;}
	public Decimal AnnualExpansionNOAAmount1 {get; set;}
	public Decimal ExpansionNOAAmount1 {get; set;}
	public Decimal AnnualExpansionNOASqFt1 {get; set;}
	public Decimal ExpansionNOASqFt1 {get; set;}
	public Decimal AnnualLumpSumAmount1 {get; set;}
	public Decimal LumpSumIAAmount1 {get; set;}
	public Decimal LumpSumNOAAmount1 {get; set;}
	public Decimal NOAObligations1 {get; set;}
	public Decimal NOASqFt1 {get; set;}
	public Decimal NOAObligationsMinus1 {get; set;}
	public Decimal PriorYearBalances1 {get; set;}
	public Decimal PriorYearCostAmount1 {get; set;}
	public Decimal PriorYearCostSqFt1 {get; set;}
	public Decimal RecessionMinus1 {get; set;}
	public Decimal RentIncreaseIAAmount1 {get; set;}
	public Decimal RentIncreaseIASqFt1 {get; set;}
	public Decimal RentIncreaseNOAAmount1 {get; set;}
	public Decimal RentIncreaseNOASqFt1 {get; set;}
	public Decimal AnnualRentIncreaseAmount1 {get; set;}
	public Decimal AnnualRentIncreaseSqFt1 {get; set;}
	public Decimal Reprogrammings1 {get; set;}
	public Decimal TotalObligations1 {get; set;}
	public Decimal TotalSqFt1 {get; set;}
	public Decimal TotalCurrentYearObligations1 {get; set;}
	public Decimal UnobligatedBalances1 {get; set;}

	public String FiscalYear2 {get; set;}
	public Decimal AnticipatedRecoveries2 {get; set;}
	public Decimal BaseCostAmount2 {get; set;}
	public Decimal BaseCostSqFt2 {get; set;}
	public Decimal CurrentYearCostAmount2 {get; set;}
	public Decimal CurrentYearCostSqFt2 {get; set;}
	public Decimal IAObligationsMinus2 {get; set;}
	public Decimal IAObligations2 {get; set;}
	public Decimal IASqFt2 {get; set;}
	public Decimal CancellationsIAAmount2 {get; set;}
	public Decimal CancellationsIASqFt2 {get; set;}
	public Decimal CancellationsNOAAmount2 {get; set;}
	public Decimal CancellationsNOASqFt2 {get; set;}
	public Decimal AnnualCancellationsAmount2 {get; set;}
	public Decimal AnnualCancellationsSqFt2 {get; set;}
	public Decimal AnnualExpansionIAAmount2 {get; set;}
	public Decimal ExpansionIAAmount2 {get; set;}
	public Decimal AnnualExpansionIASqFt2 {get; set;}
	public Decimal ExpansionIASqFt2 {get; set;}
	public Decimal IAToNOAAmount2 {get; set;}
	public Decimal IAToNOASqFt2 {get; set;}
	public Decimal AnnualExpansionNOAAmount2 {get; set;}
	public Decimal ExpansionNOAAmount2 {get; set;}
	public Decimal AnnualExpansionNOASqFt2 {get; set;}
	public Decimal ExpansionNOASqFt2 {get; set;}
	public Decimal AnnualLumpSumAmount2 {get; set;}
	public Decimal LumpSumIAAmount2 {get; set;}
	public Decimal LumpSumNOAAmount2 {get; set;}
	public Decimal NOAObligations2 {get; set;}
	public Decimal NOASqFt2 {get; set;}
	public Decimal NOAObligationsMinus2 {get; set;}
	public Decimal PriorYearBalances2 {get; set;}
	public Decimal PriorYearCostAmount2 {get; set;}
	public Decimal PriorYearCostSqFt2 {get; set;}
	public Decimal RecessionMinus2 {get; set;}
	public Decimal RentIncreaseIAAmount2 {get; set;}
	public Decimal RentIncreaseIASqFt2 {get; set;}
	public Decimal RentIncreaseNOAAmount2 {get; set;}
	public Decimal RentIncreaseNOASqFt2 {get; set;}
	public Decimal AnnualRentIncreaseAmount2 {get; set;}
	public Decimal AnnualRentIncreaseSqFt2 {get; set;}
	public Decimal Reprogrammings2 {get; set;}
	public Decimal TotalObligations2 {get; set;}
	public Decimal TotalSqFt2 {get; set;}
	public Decimal TotalCurrentYearObligations2 {get; set;}
	public Decimal UnobligatedBalances2 {get; set;}
	
	public String FiscalYear3 {get; set;}
	public Decimal AnticipatedRecoveries3 {get; set;}
	public Decimal BaseCostAmount3 {get; set;}
	public Decimal BaseCostSqFt3 {get; set;}
	public Decimal CurrentYearCostAmount3 {get; set;}
	public Decimal CurrentYearCostSqFt3 {get; set;}
	public Decimal IAObligationsMinus3 {get; set;}
	public Decimal IAObligations3 {get; set;}
	public Decimal IASqFt3 {get; set;}
	public Decimal CancellationsIAAmount3 {get; set;}
	public Decimal CancellationsIASqFt3 {get; set;}
	public Decimal CancellationsNOAAmount3 {get; set;}
	public Decimal CancellationsNOASqFt3 {get; set;}
	public Decimal AnnualCancellationsAmount3 {get; set;}
	public Decimal AnnualCancellationsSqFt3 {get; set;}
	public Decimal AnnualExpansionIAAmount3 {get; set;}
	public Decimal ExpansionIAAmount3 {get; set;}
	public Decimal AnnualExpansionIASqFt3 {get; set;}
	public Decimal ExpansionIASqFt3 {get; set;}
	public Decimal IAToNOAAmount3 {get; set;}
	public Decimal IAToNOASqFt3 {get; set;}
	public Decimal AnnualExpansionNOAAmount3 {get; set;}
	public Decimal ExpansionNOAAmount3 {get; set;}
	public Decimal AnnualExpansionNOASqFt3 {get; set;}
	public Decimal ExpansionNOASqFt3 {get; set;}
	public Decimal AnnualLumpSumAmount3 {get; set;}
	public Decimal LumpSumIAAmount3 {get; set;}
	public Decimal LumpSumNOAAmount3 {get; set;}
	public Decimal NOAObligations3 {get; set;}
	public Decimal NOASqFt3 {get; set;}
	public Decimal NOAObligationsMinus3 {get; set;}
	public Decimal PriorYearBalances3 {get; set;}
	public Decimal PriorYearCostAmount3 {get; set;}
	public Decimal PriorYearCostSqFt3 {get; set;}
	public Decimal RecessionMinus3 {get; set;}
	public Decimal RentIncreaseIAAmount3 {get; set;}
	public Decimal RentIncreaseIASqFt3 {get; set;}
	public Decimal RentIncreaseNOAAmount3 {get; set;}
	public Decimal RentIncreaseNOASqFt3 {get; set;}
	public Decimal AnnualRentIncreaseAmount3 {get; set;}
	public Decimal AnnualRentIncreaseSqFt3 {get; set;}
	public Decimal Reprogrammings3 {get; set;}
	public Decimal TotalObligations3 {get; set;}
	public Decimal TotalSqFt3 {get; set;}
	public Decimal TotalCurrentYearObligations3 {get; set;}
	public Decimal UnobligatedBalances3 {get; set;}
     	
    public Glxy_BC_3ColumnChart() {
    	
    	String strSOQL;
    	
		strReportingYear = '2014';
     	strSubmissionType = 'OMB';
     	strRegion = '1';
     	strDataFormat = '\'TEST\'';
     	
     	If (System.currentPageReference().getParameters().get('Region')!=null){
     		strReportingYear = System.currentPageReference().getParameters().get('ReportingYear');
     		strSubmissionType = System.currentPageReference().getParameters().get('SubmissionType');
     		strRegion = System.currentPageReference().getParameters().get('Region');
     		strDataFormat = System.currentPageReference().getParameters().get('DataFormat');
     	}
     	
     	strSOQL =   'Select Sum(AnticipatedRecoveries__c) AnticipatedRecoveries, Sum(BaseCostAmount__c) BaseCostAmount, Sum(BaseCostSqFt__c) BaseCostSqFt, ' + 
		            'Max(BudgetSubmissionID__c) BudgetSubmissionID, Sum(CurrentYearCostAmount__c) CurrentYearCostAmount, Sum(CurrentYearCostSqFt__c) CurrentYearCostSqFt, ' + 
            		'FiscalYear__c FiscalYear, Sum(IAObligationsMinus__c) IAObligationsMinus, Sum(IAObligations__c) IAObligations, Sum(IASqFt__c) IASqFt, Sum(CancellationsIAAmount__c) CancellationsIAAmount, ' +  
            		'Sum(CancellationsIASqFt__c) CancellationsIASqFt, Sum(CancellationsNOASqFt__c) CancellationsNOASqFt, Sum(CancellationsNOAAmount__c) CancellationsNOAAmount, Sum(AnnualCancellationsAmount__c) AnnualCancellationsAmount,  ' + 
            		'Sum(AnnualCancellationsSqFt__c) AnnualCancellationsSqFt, Sum(AnnualExpansionIAAmount__c) AnnualExpansionIAAmount, Sum(AnnualExpansionIASqFt__c) AnnualExpansionIASqFt,  ' + 
            		'Sum(ExpansionIAAmount__c) ExpansionIAAmount, Sum(ExpansionIASqFt__c) ExpansionIASqFt , Sum(IAToNOAAmount__c) IAToNOAAmount, Sum(IAToNOASqFt__c) IAToNOASqFt, ' + 
            		'Sum(AnnualExpansionNOAAmount__c) AnnualExpansionNOAAmount, Sum(ExpansionNOAAmount__c) ExpansionNOAAmount, Sum(TotalCurrentYearObligations__c) TotalCYObligations, ' + 
            		'Sum(AnnualExpansionNOASqFt__c) AnnualExpansionNOASqFt, Sum(ExpansionNOASqFt__c) ExpansionNOASqFt, Sum(AnnualLumpSumAmount__c) AnnualLumpSumAmount, Sum(LumpSumIAAmount__c) LumpSumIAAmount, ' + 
            		'Sum(LumpSumNOAAmount__c) LumpSumNOAAmount, Sum(NOAObligations__c) NOAObligations, Sum(NOASqFt__c) NOASqFt, Sum(NOAObligationsMinus__c) NOAObligationsMinus, Sum(PriorYearBalances__c) PriorYearBalances, ' + 
            		'Sum(PriorYearCostAmount__c) PriorYearCostAmount, Sum(PriorYearCostSqFt__c) PriorYearCostSqFt, Sum(RecessionMinus__c) RecessionMinus, ' + 
            		'Sum(RentIncreaseIAAmount__c) RentIncreaseIAAmount, Sum(RentIncreaseIASqFt__c) RentIncreaseIASqFt, Sum(RentIncreaseNOAAmount__c) RentIncreaseNOAAmount, Sum(RentIncreaseNOASqFt__c) RentIncreaseNOASqFt, ' + 
            		'Sum(AnnualRentIncreaseAmount__c) AnnualRentIncreaseAmount, Sum(AnnualRentIncreaseSqFt__c) AnnualRentIncreaseSqFt, Sum(Reprogrammings__c) Reprogrammings, ' + 
            		'Sum(TotalObligations__c) TotalObligations, Sum(TotalSqFt__c) TotalSqFt, Sum(UnobligatedBalances__c) UnobligatedBalances ' + 
            'From    Glxy_BudgetSubmissionData__c ' + ' ' +   
            'Where   ReportingFiscalYear__c = :strReportingYear ' +  
            'And 	 SubmissionType__c = ' + String.escapeSingleQuotes(strSubmissionType)  + ' ' +   
            'And 	 Region__c = ' + String.escapeSingleQuotes(strRegion)  + ' ' +  
            'And     DataFormat__c In (' + String.escapeSingleQuotes(strDataFormat) + ') ' + 
            'Group BY FiscalYear__c ' + 
            'Order by FiscalYear__c ';
        strSOQL = strSOQL.Replace('\\','');     
       	System.debug('MyDebug = ' + strSOQL);
       
      	AggregateResult[] AgR = Database.Query(strSOQL);
      	Integer intRowCounter = 1;
      	
		for (AggregateResult RowData : AgR) { 
			//Column 1
			If (intRowCounter == 1){
				FiscalYear1 = (String) RowData.get('FiscalYear');
				AnticipatedRecoveries1 = (Decimal) RowData.get('AnticipatedRecoveries');
				BaseCostAmount1 = (Decimal) RowData.get('BaseCostAmount');
				BaseCostSqFt1 = (Decimal) RowData.get('BaseCostSqFt');
				CurrentYearCostAmount1 = (Decimal) RowData.get('CurrentYearCostAmount');
				CurrentYearCostSqFt1 = (Decimal) RowData.get('CurrentYearCostSqFt');
				IAObligationsMinus1 = (Decimal) RowData.get('IAObligationsMinus');
				IAObligations1 = (Decimal) RowData.get('IAObligations');
				IASqFt1 = (Decimal) RowData.get('IASqFt');
				CancellationsIAAmount1 = (Decimal) RowData.get('CancellationsIAAmount');
				CancellationsIASqFt1 = (Decimal) RowData.get('CancellationsIASqFt');
				CancellationsNOAAmount1 = (Decimal) RowData.get('CancellationsNOAAmount');
				CancellationsNOASqFt1 = (Decimal) RowData.get('CancellationsNOASqFt');
				AnnualCancellationsAmount1 = (Decimal) RowData.get('AnnualCancellationsAmount');
				AnnualCancellationsSqFt1 = (Decimal) RowData.get('AnnualCancellationsSqFt');
				AnnualCancellationsSqFt1 = (Decimal) RowData.get('AnnualCancellationsSqFt');
				ExpansionIAAmount1 = (Decimal) RowData.get('ExpansionIAAmount');
				AnnualExpansionIASqFt1 = (Decimal) RowData.get('AnnualExpansionIASqFt');
				AnnualExpansionIAAmount1 = (Decimal) RowData.get('AnnualExpansionIAAmount');
				ExpansionIASqFt1 = (Decimal) RowData.get('ExpansionIASqFt');
				IAToNOAAmount1 = (Decimal) RowData.get('IAToNOAAmount');
				IAToNOASqFt1 = (Decimal) RowData.get('IAToNOASqFt');
				AnnualExpansionNOAAmount1 = (Decimal) RowData.get('AnnualExpansionNOAAmount');
				ExpansionNOAAmount1 = (Decimal) RowData.get('ExpansionNOAAmount');
				AnnualExpansionNOASqFt1 = (Decimal) RowData.get('AnnualExpansionNOASqFt');
				ExpansionNOASqFt1 = (Decimal) RowData.get('ExpansionNOASqFt');
				AnnualLumpSumAmount1 = (Decimal) RowData.get('AnnualLumpSumAmount');
				LumpSumIAAmount1 = (Decimal) RowData.get('LumpSumIAAmount');
				LumpSumNOAAmount1 = (Decimal) RowData.get('LumpSumNOAAmount');
				NOAObligations1 = (Decimal) RowData.get('NOAObligations');
				NOASqFt1 = (Decimal) RowData.get('NOASqFt');
				NOAObligationsMinus1 = (Decimal) RowData.get('NOAObligationsMinus');
				PriorYearBalances1 = (Decimal) RowData.get('PriorYearBalances');
				PriorYearCostAmount1 = (Decimal) RowData.get('PriorYearCostAmount');
				PriorYearCostSqFt1 = (Decimal) RowData.get('PriorYearCostSqFt');
				RecessionMinus1 = (Decimal) RowData.get('RecessionMinus');
				RentIncreaseIAAmount1 = (Decimal) RowData.get('RentIncreaseIAAmount');
				RentIncreaseIASqFt1 = (Decimal) RowData.get('RentIncreaseIASqFt');
				RentIncreaseNOAAmount1 = (Decimal) RowData.get('RentIncreaseNOAAmount');
				RentIncreaseNOASqFt1 = (Decimal) RowData.get('RentIncreaseNOASqFt');
				AnnualRentIncreaseAmount1 = (Decimal) RowData.get('AnnualRentIncreaseAmount');
				AnnualRentIncreaseSqFt1 = (Decimal) RowData.get('AnnualRentIncreaseSqFt');
				Reprogrammings1 = (Decimal) RowData.get('Reprogrammings');
				TotalObligations1 = (Decimal) RowData.get('TotalObligations');
				TotalSqFt1 = (Decimal) RowData.get('TotalSqFt');
				TotalCurrentYearObligations1 = (Decimal) RowData.get('TotalCYObligations');
				UnobligatedBalances1 = (Decimal) RowData.get('UnobligatedBalances');
			}
			
			//Column 2
			If (intRowCounter == 2){
				FiscalYear2 = (String) RowData.get('FiscalYear');
				AnticipatedRecoveries2 = (Decimal) RowData.get('AnticipatedRecoveries');
				BaseCostAmount2 = (Decimal) RowData.get('BaseCostAmount');
				BaseCostSqFt2 = (Decimal) RowData.get('BaseCostSqFt');
				CurrentYearCostAmount2 = (Decimal) RowData.get('CurrentYearCostAmount');
				CurrentYearCostSqFt2 = (Decimal) RowData.get('CurrentYearCostSqFt');
				IAObligationsMinus2 = (Decimal) RowData.get('IAObligationsMinus');
				IAObligations2 = (Decimal) RowData.get('IAObligations');
				IASqFt2 = (Decimal) RowData.get('IASqFt');
				CancellationsIAAmount2 = (Decimal) RowData.get('CancellationsIAAmount');
				CancellationsIASqFt2 = (Decimal) RowData.get('CancellationsIASqFt');
				CancellationsNOAAmount2 = (Decimal) RowData.get('CancellationsNOAAmount');
				CancellationsNOASqFt2 = (Decimal) RowData.get('CancellationsNOASqFt');
				AnnualCancellationsAmount2 = (Decimal) RowData.get('AnnualCancellationsAmount');
				AnnualCancellationsSqFt2 = (Decimal) RowData.get('AnnualCancellationsSqFt');
				AnnualCancellationsSqFt2 = (Decimal) RowData.get('AnnualCancellationsSqFt');
				ExpansionIAAmount2 = (Decimal) RowData.get('ExpansionIAAmount');
				AnnualExpansionIASqFt2 = (Decimal) RowData.get('AnnualExpansionIASqFt');
				AnnualExpansionIAAmount2 = (Decimal) RowData.get('AnnualExpansionIAAmount');
				ExpansionIASqFt2 = (Decimal) RowData.get('ExpansionIASqFt');
				IAToNOAAmount2 = (Decimal) RowData.get('IAToNOAAmount');
				IAToNOASqFt2 = (Decimal) RowData.get('IAToNOASqFt');
				AnnualExpansionNOAAmount2 = (Decimal) RowData.get('AnnualExpansionNOAAmount');
				ExpansionNOAAmount2 = (Decimal) RowData.get('ExpansionNOAAmount');
				AnnualExpansionNOASqFt2 = (Decimal) RowData.get('AnnualExpansionNOASqFt');
				ExpansionNOASqFt2 = (Decimal) RowData.get('ExpansionNOASqFt');
				AnnualLumpSumAmount2 = (Decimal) RowData.get('AnnualLumpSumAmount');
				LumpSumIAAmount2 = (Decimal) RowData.get('LumpSumIAAmount');
				LumpSumNOAAmount2 = (Decimal) RowData.get('LumpSumNOAAmount');
				NOAObligations2 = (Decimal) RowData.get('NOAObligations');
				NOASqFt2 = (Decimal) RowData.get('NOASqFt');
				NOAObligationsMinus2 = (Decimal) RowData.get('NOAObligationsMinus');
				PriorYearBalances2 = (Decimal) RowData.get('PriorYearBalances');
				PriorYearCostAmount2 = (Decimal) RowData.get('PriorYearCostAmount');
				PriorYearCostSqFt2 = (Decimal) RowData.get('PriorYearCostSqFt');
				RecessionMinus2 = (Decimal) RowData.get('RecessionMinus');
				RentIncreaseIAAmount2 = (Decimal) RowData.get('RentIncreaseIAAmount');
				RentIncreaseIASqFt2 = (Decimal) RowData.get('RentIncreaseIASqFt');
				RentIncreaseNOAAmount2 = (Decimal) RowData.get('RentIncreaseNOAAmount');
				RentIncreaseNOASqFt2 = (Decimal) RowData.get('RentIncreaseNOASqFt');
				AnnualRentIncreaseAmount2 = (Decimal) RowData.get('AnnualRentIncreaseAmount');
				AnnualRentIncreaseSqFt2 = (Decimal) RowData.get('AnnualRentIncreaseSqFt');
				Reprogrammings2 = (Decimal) RowData.get('Reprogrammings');
				TotalObligations2 = (Decimal) RowData.get('TotalObligations');
				TotalSqFt2 = (Decimal) RowData.get('TotalSqFt');
				TotalCurrentYearObligations2 = (Decimal) RowData.get('TotalCYObligations');
				UnobligatedBalances2 = (Decimal) RowData.get('UnobligatedBalances');
			}
			
			//Column 3
			If (intRowCounter == 3){
				FiscalYear3 = (String) RowData.get('FiscalYear');
				AnticipatedRecoveries3 = (Decimal) RowData.get('AnticipatedRecoveries');
				BaseCostAmount3 = (Decimal) RowData.get('BaseCostAmount');
				BaseCostSqFt3 = (Decimal) RowData.get('BaseCostSqFt');
				CurrentYearCostAmount3 = (Decimal) RowData.get('CurrentYearCostAmount');
				CurrentYearCostSqFt3 = (Decimal) RowData.get('CurrentYearCostSqFt');
				IAObligationsMinus3 = (Decimal) RowData.get('IAObligationsMinus');
				IAObligations3 = (Decimal) RowData.get('IAObligations');
				IASqFt3 = (Decimal) RowData.get('IASqFt');
				CancellationsIAAmount3 = (Decimal) RowData.get('CancellationsIAAmount');
				CancellationsIASqFt3 = (Decimal) RowData.get('CancellationsIASqFt');
				CancellationsNOAAmount3 = (Decimal) RowData.get('CancellationsNOAAmount');
				CancellationsNOASqFt3 = (Decimal) RowData.get('CancellationsNOASqFt');
				AnnualCancellationsAmount3 = (Decimal) RowData.get('AnnualCancellationsAmount');
				AnnualCancellationsSqFt3 = (Decimal) RowData.get('AnnualCancellationsSqFt');
				AnnualCancellationsSqFt3 = (Decimal) RowData.get('AnnualCancellationsSqFt');
				ExpansionIAAmount3 = (Decimal) RowData.get('ExpansionIAAmount');
				AnnualExpansionIASqFt3 = (Decimal) RowData.get('AnnualExpansionIASqFt');
				AnnualExpansionIAAmount3 = (Decimal) RowData.get('AnnualExpansionIAAmount');
				ExpansionIASqFt3 = (Decimal) RowData.get('ExpansionIASqFt');
				IAToNOAAmount3 = (Decimal) RowData.get('IAToNOAAmount');
				IAToNOASqFt3 = (Decimal) RowData.get('IAToNOASqFt');
				AnnualExpansionNOAAmount3 = (Decimal) RowData.get('AnnualExpansionNOAAmount');
				ExpansionNOAAmount3 = (Decimal) RowData.get('ExpansionNOAAmount');
				AnnualExpansionNOASqFt3 = (Decimal) RowData.get('AnnualExpansionNOASqFt');
				ExpansionNOASqFt3 = (Decimal) RowData.get('ExpansionNOASqFt');
				AnnualLumpSumAmount3 = (Decimal) RowData.get('AnnualLumpSumAmount');
				LumpSumIAAmount3 = (Decimal) RowData.get('LumpSumIAAmount');
				LumpSumNOAAmount3 = (Decimal) RowData.get('LumpSumNOAAmount');
				NOAObligations3 = (Decimal) RowData.get('NOAObligations');
				NOASqFt3 = (Decimal) RowData.get('NOASqFt');
				NOAObligationsMinus3 = (Decimal) RowData.get('NOAObligationsMinus');
				PriorYearBalances3 = (Decimal) RowData.get('PriorYearBalances');
				PriorYearCostAmount3 = (Decimal) RowData.get('PriorYearCostAmount');
				PriorYearCostSqFt3 = (Decimal) RowData.get('PriorYearCostSqFt');
				RecessionMinus3 = (Decimal) RowData.get('RecessionMinus');
				RentIncreaseIAAmount3 = (Decimal) RowData.get('RentIncreaseIAAmount');
				RentIncreaseIASqFt3 = (Decimal) RowData.get('RentIncreaseIASqFt');
				RentIncreaseNOAAmount3 = (Decimal) RowData.get('RentIncreaseNOAAmount');
				RentIncreaseNOASqFt3 = (Decimal) RowData.get('RentIncreaseNOASqFt');
				AnnualRentIncreaseAmount3 = (Decimal) RowData.get('AnnualRentIncreaseAmount');
				AnnualRentIncreaseSqFt3 = (Decimal) RowData.get('AnnualRentIncreaseSqFt');
				Reprogrammings3 = (Decimal) RowData.get('Reprogrammings');
				TotalObligations3 = (Decimal) RowData.get('TotalObligations');
				TotalSqFt3 = (Decimal) RowData.get('TotalSqFt');
				TotalCurrentYearObligations3 = (Decimal) RowData.get('TotalCYObligations');
				UnobligatedBalances3 = (Decimal) RowData.get('UnobligatedBalances');
			}
	    	
	    	intRowCounter ++;
		}        
         
    }
    
    // **** RUN all the TEST methods for code coverage ... ****//    
    @isTest(SeeAllData=true) Static void  test3ColumChartReportData() {
       	
   		PageReference pageRef = Page.GLXY_rpt3ColumnChart;
	    Test.setCurrentPage(pageRef);
	    ApexPages.currentPage().getParameters().put('ReportingYear', '2014');
	    ApexPages.currentPage().getParameters().put('SubmissionType', '\'OMB\'');
	    ApexPages.currentPage().getParameters().put('Region', '\'CO\'');
	    ApexPages.currentPage().getParameters().put('DataFormat', '\'TEST\'');
		    
       	/*Map<String,ID> profiles = new Map<String,ID>();  
       	List<Profile> ps = [select id, name from Profile where name = 'GSA System Administrator' or name = 'System Administrator'];
       	Group GalaxyCOGroup = [select id, name from Group  where name = 'Galaxy-CO-Users'];  
        for(Profile p : ps){  
            profiles.put(p.name, p.id);  
		} 
		  
       	User admin = [SELECT Id FROM user WHERE IsActive = True And User_Region__c = 'CO' And profileid = :profiles.get('GSA System Administrator') Limit 1];  
       	List<GroupMember> GMlist = new List<GroupMember>();
       	GroupMember GM = new GroupMember();
       	GM.GroupId = GalaxyCOGroup.ID;
       	GM.UserOrGroupId = admin.Id;
       	GMList.add(GM);
       	insert GMList;*/
       	
       	//system.runas(admin){
        	Glxy_BudgetSubmission__c objMaster = New Glxy_BudgetSubmission__c(
	 	  	 	RegionCD__c = 'CO',
		   		ReportingFiscalYear__c = '2014',
		 		SubmissionType__c = 'OMB');
	       	insert objMaster;
	       	
	       	Glxy_BudgetSubmissionData__c objDetail4 = New Glxy_BudgetSubmissionData__c(
	 	  	 	BudgetSubmissionID__c = objMaster.ID,
	 	  	 	FiscalYear__c  = '2014',
		   		DataFormat__c = 'TEST',
		 		ReportColumnIdentifier__c = 1);
	       	insert objDetail4;
	       
	       	Glxy_BudgetSubmissionData__c objDetail5 = New Glxy_BudgetSubmissionData__c(
	 	  	 	BudgetSubmissionID__c = objMaster.ID,
	 	  	 	FiscalYear__c  = '2015',
		   		DataFormat__c = 'TEST',
		 		ReportColumnIdentifier__c = 2);
	       	insert objDetail5;
	       
	       	Glxy_BudgetSubmissionData__c objDetail6 = New Glxy_BudgetSubmissionData__c(
	 	  	 	BudgetSubmissionID__c = objMaster.ID,
	 	  	 	FiscalYear__c  = '2016',
		   		DataFormat__c = 'TEST',
		 		ReportColumnIdentifier__c = 3);
	       	insert objDetail6;

		    Glxy_BC_3ColumnChart objTest = new Glxy_BC_3ColumnChart();
		    System.Assert(objTest!=NULL); 
      // }
       
    }
    
}