src/objects/Glxy_Lease__c.object
<CustomObject>
    <customHelpPage>GLXY_HelpPage</customHelpPage>
    <description>This table contains lease information at the beginning of the fiscal year.  This information is updated at the beginning of each fiscal year.</description>
    <fields>
        <fullName>DigestID__c</fullName>
        <label>Digest ID</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RegionCD__c</fullName>
        <description>Region Code</description>
        <label>Region Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TeamCode__c</fullName>
        <label>Team Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Lease</label>
    <nameField>
        <label>Lease Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Glxy_LeaseDigest__c.object
<CustomObject>
    <description>Lease Digest object, child of Transaction object for galaxy</description>
    <fields>
        <fullName>DigestID__c</fullName>
        <externalId>true</externalId>
        <label>Digest ID</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>LeaseNumber__c</fullName>
        <label>Lease Number</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectNumber__c</fullName>
        <label>Project Number</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <label>Transaction</label>
        <referenceTo>Glxy_Transaction__c</referenceTo>
        <relationshipLabel>Lease Digests</relationshipLabel>
        <relationshipName>Lease_Digests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Lease Digest</label>
    <nameField>
        <label>Lease Digest ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lease Digests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Glxy_LeaseProjects__c.object
<CustomObject>
    <customHelpPage>GLXY_HelpPage</customHelpPage>
    <description>This table contains information on all the New, Renewal, Extension, Succeeding, Superseding, Terminating, Chg in SF, and New/Replacing leases associated with a Project.  The Project is the starting point for new leases or changes to existing leases.</description>
    <fields>
        <fullName>EffectiveDate__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NewLease__c</fullName>
        <inlineHelpText>New lease numbers to be assigned by REXUS for Succeeding, Superseding, and New/Replacing actions.  For Extensions, Renewal, Expansion, Reduction, and Other actions, this field will reflect existing lease number (Old Lease Number).</inlineHelpText>
        <label>New Lease Number</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProcessedDate__c</fullName>
        <inlineHelpText>Date project goes from estimated to actual status</inlineHelpText>
        <label>Process Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProjectStatus__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RegionCd__c</fullName>
        <label>Region Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RexusNewIASqFt__c</fullName>
        <label>Rexus New IA Sq Ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RexusNewNOASqFt__c</fullName>
        <label>Rexus New NOA Sq Ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TeamCode__c</fullName>
        <label>Team Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Lease Project</label>
    <nameField>
        <label>Project Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lease Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Glxy_LPStepRent__c.object
<CustomObject>
    <description>This table contains the step rent information about lease projects. This is one kind of lease project payment but can have different characteristics.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Amount</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>EffectiveDate__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ExpirationDate__c</fullName>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProcessedDate__c</fullName>
        <inlineHelpText>Date transaction completed and processed</inlineHelpText>
        <label>Process Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProjectNumber__c</fullName>
        <label>Project Number</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>Region value specified is outside your region</errorMessage>
            <filterItems>
                <field>$User.Glxy_Region_Code__c</field>
                <operation>equals</operation>
                <valueField>Glxy_LeaseProjects__c.RegionCd__c</valueField>
            </filterItems>
            <filterItems>
                <field>$User.Glxy_Region_Code__c</field>
                <operation>equals</operation>
                <value>CO</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Glxy_LeaseProjects__c</referenceTo>
        <relationshipLabel>Lease Proj Step Rents</relationshipLabel>
        <relationshipName>LP_Step_Rents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RegionCD__c</fullName>
        <formula>TEXT(ProjectNumber__r.RegionCd__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TeamCode__c</fullName>
        <formula>ProjectNumber__r.TeamCode__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Team Code</label>
        <type>Text</type>
    </fields>
    <label>Lease Proj Step Rent</label>
    <nameField>
        <displayFormat>LPSTP{0000000}</displayFormat>
        <label>LP Step Rent #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lease Proj Step Rents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Glxy_Transaction__c.object
<CustomObject>
    <customHelpPage>GLXY_HelpPage</customHelpPage>
    <description>This table contains monthly Galaxy summarized Data. This data will be loaded on monthly basis using SalesForce APEX code. Purpose of this data is to produce monthly reconciliation reports.</description>
    <fields>
        <fullName>BA53_User__c</fullName>
        <inlineHelpText>BA53 Analyst that the associated Lease is assigned to in REXUS</inlineHelpText>
        <label>BA53 User</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LeaseNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Lease object</description>
        <label>Lease Number</label>
        <referenceTo>Glxy_Lease__c</referenceTo>
        <relationshipLabel>Galaxy Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>New_Lease_Number__c</fullName>
        <description>New Lease Number</description>
        <inlineHelpText>LXXNNNNN - L &apos;State Code&apos; 00000. This is an eight character identifier for a specific lease. With the first character being &quot;L&quot;, the second two characters being the state code, and the final five characters being a unique set of numeric values.</inlineHelpText>
        <label>New Lease Number</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Number</label>
        <referenceTo>Glxy_LeaseProjects__c</referenceTo>
        <relationshipLabel>Galaxy Transactions</relationshipLabel>
        <relationshipName>Galaxy_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Galaxy Transaction</label>
    <nameField>
        <label>Transaction ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Galaxy Transactions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Glxy_extProjectStepRents.cls
public with sharing class Glxy_extProjectStepRents {
	
	private final Glxy_LeaseDigest__c objRecord;
	public List<Glxy_LPStepRent__c> objProjectStepRents {get;set;}
	
	public Glxy_extProjectStepRents(ApexPages.StandardController controller) {
       objRecord = (Glxy_LeaseDigest__c) controller.getRecord();
       Glxy_LeaseDigest__c objRecordDetail = [select LeaseNumber__c From Glxy_LeaseDigest__c Where id =:objRecord.id];
       objProjectStepRents = [Select ID, Name, ProjectNumber__c, RegionCD__c, EffectiveDate__c, ExpirationDate__c, ProcessedDate__c, Amount__c, TeamCode__c 
       						 From 	Glxy_LPStepRent__c 
       						 Where 	ProjectNumber__r.NewLease__c = :objRecordDetail.LeaseNumber__c];
    }
	
	@isTest static void Glxy_extProjectStepRentsTest(){
	 	
	 	Date myDate =  date.newinstance(2012, 2, 17);
		Date myDate1 = date.newinstance(2013, 2, 17);
		
		Glxy_Lease__c objLease = new Glxy_Lease__c();
		objLease.Name = 'LDE00374';
		insert objLease;
		
  		Glxy_LeaseProjects__c project= new Glxy_LeaseProjects__c();
		project.ProjectStatus__c = 'Active';
		project.EffectiveDate__c = myDate ;
		project.RegionCd__c = '3';
		project.RexusNewNOASqFt__c = 1000;
		project.RexusNewIASqFt__c = 1000;
		Project.NewLease__c = 'LDE00374';
		insert project;
		system.assertNotEquals(NULL,project);
			   
	  	Glxy_LPStepRent__c SR = new Glxy_LPStepRent__c();
	   	SR.ProjectNumber__c = project.id;
	   	insert SR;
		system.assertNotEquals(NULL,SR);
		
		Glxy_Transaction__c objTransaction = new Glxy_Transaction__c (
            LeaseNumber__c = objLease.id,  
            Project_Number__c = project.id ,
            RecordTypeId = Schema.SObjectType.Glxy_Transaction__c.getRecordTypeInfosByName().get('Project Final Certification').getRecordTypeId(), 
            BA53_User__c = 'test',
            New_Lease_Number__c = 'LDE00374',
            Region__c = 'test'
    	);
        insert objTransaction;
        system.assertNotEquals(NULL,objTransaction);
        
        Glxy_LeaseDigest__c objDigest = new Glxy_LeaseDigest__c (
            Transaction__c = objTransaction.id,  
            LeaseNumber__c = 'LDE00374',
            DigestID__c = 1234567
    	);
        insert objDigest;
        system.assertNotEquals(NULL,objDigest);
	   	
	   	ApexPages.StandardController con = new ApexPages.StandardController(objDigest);
	  	Glxy_extProjectStepRents objPaymentLines = new Glxy_extProjectStepRents(con);
  }
  
}