src/objects/Glxy_LeaseProjects__c.object
<CustomObject>
    <customHelpPage>GLXY_HelpPage</customHelpPage>
    <description>This table contains information on all the New, Renewal, Extension, Succeeding, Superseding, Terminating, Chg in SF, and New/Replacing leases associated with a Project.  The Project is the starting point for new leases or changes to existing leases.</description>
    <fields>
        <fullName>AnnualRent__c</fullName>
        <defaultValue>0</defaultValue>
        <label>New Annual Rent</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>EffectiveDate__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IASquareFeet__c</fullName>
        <defaultValue>0</defaultValue>
        <label>New IA Sq Ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NOASquareFeet__c</fullName>
        <defaultValue>0</defaultValue>
        <label>New NOA Sq Ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Old_Annual_Rent__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Old Annual Rent</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProjectStatus__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_Type__c</fullName>
        <inlineHelpText>Project Type</inlineHelpText>
        <label>Project Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Change in Services</fullName>
                </value>
                <value>
                    <fullName>Change in SF</fullName>
                </value>
                <value>
                    <fullName>Change To External Contacts</fullName>
                </value>
                <value>
                    <fullName>Escalation</fullName>
                </value>
                <value>
                    <fullName>Expansion</fullName>
                </value>
                <value>
                    <fullName>Extension</fullName>
                </value>
                <value>
                    <fullName>Holdover</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>New/Replacing</fullName>
                </value>
                <value>
                    <fullName>Operating Cost Escalation</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Real Estate Tax Escalation</fullName>
                </value>
                <value>
                    <fullName>Reduction</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Step Rent Decrease</fullName>
                </value>
                <value>
                    <fullName>Step Rent Increase</fullName>
                </value>
                <value>
                    <fullName>Succeeding</fullName>
                </value>
                <value>
                    <fullName>Superseding</fullName>
                </value>
                <value>
                    <fullName>Termination</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RegionCd__c</fullName>
        <label>Region Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SquareFeet__c</fullName>
        <defaultValue>0</defaultValue>
        <label>New Sq Ft</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>eEorA__c</fullName>
        <inlineHelpText>Estimated or Actual</inlineHelpText>
        <label>Effective Date Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Actual</fullName>
                </value>
                <value>
                    <fullName>Estimate</fullName>
                </value>
                <value>
                    <fullName>Voided</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Lease Project</label>
    <nameField>
        <label>Project Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lease Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Glxy_ProjectAgency__c.object
<CustomObject>
    <description>This table contains the Agency Space Assignments (ASA) data for Projects.</description>
    <fields>
        <fullName>BaseStructuredParkingSpaces__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Base Structured Parking Spaces</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BaseSurfaceParkingSpace__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Base Surface Parking Spaces</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OldASA__c</fullName>
        <label>Old ASA</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PBSABCode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PBS AB Code</label>
        <referenceTo>PBS_AB_Code__c</referenceTo>
        <relationshipLabel>Project Agencies</relationshipLabel>
        <relationshipName>Project_Agencies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectNumber__c</fullName>
        <label>Project Number</label>
        <referenceTo>Glxy_LeaseProjects__c</referenceTo>
        <relationshipName>Project_Agencies</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Agency</label>
    <nameField>
        <displayFormat>PA-{000000}</displayFormat>
        <label>Project Agency ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Agencies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Glxy_ProjectRequestASA__c.object
<CustomObject>
    <fields>
        <fullName>OldASA__c</fullName>
        <inlineHelpText>Current ASA number for specific space for an agency.</inlineHelpText>
        <label>Old ASA</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectAgencyID__c</fullName>
        <label>Project Agency</label>
        <referenceTo>Glxy_ProjectAgency__c</referenceTo>
        <relationshipName>Project_Agency_ASA</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RequestASAID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Unique identifier from Rexus. This helps in finding the record in Rexus.</inlineHelpText>
        <label>RequestASAID</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Project Request ASA</label>
    <nameField>
        <displayFormat>ID-{000000}</displayFormat>
        <label>Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Request ASA</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PBS_AB_Code__c.object
<CustomObject>
    <description>PBS A/B Codes Object</description>
    <fields>
        <fullName>AB_Code__c</fullName>
        <description>This field is the 4-digit code that uniquely identifies the agency bureau for which the exception, exemption, administrative, or agency (including trust fund agency) adjustment was created.</description>
        <externalId>true</externalId>
        <label>AB Code</label>
        <length>4</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Agency_Bureau_Name__c</fullName>
        <description>The full name of the agency or bureau.</description>
        <label>Agency Bureau Name</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Agency_Bureau_Short_Name__c</fullName>
        <description>The 20-character agency bureau short name.</description>
        <label>Agency Bureau Short Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Agency_Code__c</fullName>
        <description>The first 2-digits of the A/B Code identifies the client agency.</description>
        <label>Agency Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bureau_Code__c</fullName>
        <description>The first 3 and fourth digits of the A/B Code identifies the client agency.</description>
        <label>Bureau Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>PBS AB Code</label>
    <nameField>
        <displayFormat>PBSABCode-{0000000000}</displayFormat>
        <label>PBS AB Code Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PBS AB Codes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/GLXY_DeriveOldASA.cls
public with sharing class GLXY_DeriveOldASA {
    
    public static Set<string> glbMasterIDsToUpdate;
    
    public static void fnUpdateASA(Set<string> MasterIDsToUpdate) {
        System.Debug('MyDebug Inside fnUpdateASA');
        List<Glxy_ProjectRequestASA__c> objListASA = [Select ProjectAgencyID__c, OldASA__c from Glxy_ProjectRequestASA__c 
                                                      Where ProjectAgencyID__c in :MasterIDsToUpdate
                                                      Order By ProjectAgencyID__c];
        
        System.Debug('MyDebug objListASA.Size = ' + objListASA.size());
        List<Glxy_ProjectAgency__c> objAgenciesToUpdate = New List<Glxy_ProjectAgency__c>();    
        string strLoopCurrentAgency;
        string strLoopPreviousAgency = '-';
        string strASAList = '';
        boolean blnHasData = false;                                       
        //Loop through to find the Request ASA's associated with an Agency  
        for (Glxy_ProjectRequestASA__c objASA : objListASA) {
            blnHasData = true;
            strLoopCurrentAgency = objASA.ProjectAgencyID__c;
            System.Debug('MyDebug strLoopPreviousAgency - ' + strLoopPreviousAgency);
            System.Debug('MyDebug strLoopCurrentAgency - ' + strLoopCurrentAgency);
                if ((strLoopCurrentAgency <> strLoopPreviousAgency) && (strLoopPreviousAgency <> '-')){
                    if (strASAList.LastIndexOf(',') > 0)
                        strASAList = strASAList.Left(strASAList.LastIndexOf(', '));
                    objAgenciesToUpdate.Add(new Glxy_ProjectAgency__c(
                        ID = strLoopPreviousAgency,
                        OldASA__c = strASAList
                    ));
                    System.Debug('MyDebug InsertAgency - ' + strLoopPreviousAgency);
                    strASAList = '';    
                }
                strASAList = strASAList + objASA.OldASA__c + ', ';
                strLoopPreviousAgency = strLoopCurrentAgency;
        }   
        
        if (blnHasData = true){
            if (strASAList.LastIndexOf(', ') > 0)
                strASAList = strASAList.Left(strASAList.LastIndexOf(', '));
            objAgenciesToUpdate.Add(new Glxy_ProjectAgency__c(
                ID = (ID) strLoopCurrentAgency,
                OldASA__c = strASAList
            ));
            System.Debug('MyDebug InsertAgency - ' + strLoopCurrentAgency);
        }
        
        try{    
            Database.Update(objAgenciesToUpdate);
        }catch (DmlException e){
            System.debug('GLXY_DeriveOldASA Update error - ' + e.getMessage());
        }
    }
    
    @isTest(SeeAllData=false) Static void  TestTriggerGLXY_DeriveOldASA () {
            Glxy_LeaseProjects__c project = new Glxy_LeaseProjects__c (Name = '6AK0141', NOASquareFeet__c = 1935.45, IASquareFeet__c = 0, 
                Project_Type__c = 'Succeeding', EffectiveDate__c = date.newInstance(2011,2,14), RegionCd__c = '10',
                AnnualRent__c = 0, ProjectStatus__c = 'Active', Old_Annual_Rent__c = 0, SquareFeet__c = 1935.45, eEorA__c = 'Actual');
            insert project;
            System.Assert(project!=NULL);   
            
            PBS_AB_Code__c obAB1 = New PBS_AB_Code__c();
            obAB1.AB_Code__c = '9999';
            obAB1.Agency_Bureau_Name__c = 'test';
            obAB1.Agency_Bureau_Short_Name__c = 'test';
            obAB1.Agency_Code__c = '19';
            obAB1.Bureau_Code__c = '01';
            insert obAB1;
            
            PBS_AB_Code__c obAB2 = New PBS_AB_Code__c();
            obAB2.AB_Code__c = '8888';
            obAB2.Agency_Bureau_Name__c = 'test2';
            obAB2.Agency_Bureau_Short_Name__c = 'test2';
            obAB2.Agency_Code__c = '10';
            obAB2.Bureau_Code__c = '11';
            insert obAB2;
            
            Glxy_ProjectAgency__c objTest1 = new Glxy_ProjectAgency__c();
            objTest1.ProjectNumber__c = project.id;
            objTest1.PBSABCode__c = obAB1.id;
            objtest1.BaseStructuredParkingSpaces__c  = 10;
            objtest1.BaseSurfaceParkingSpace__c = 10;
            insert objTest1;
            
            Glxy_ProjectAgency__c objTest2 = new Glxy_ProjectAgency__c();
            objTest2.ProjectNumber__c = project.id;
            objTest2.PBSABCode__c = obAB2.id;
            objtest2.BaseStructuredParkingSpaces__c  = 10;
            objtest2.BaseSurfaceParkingSpace__c = 10;
            insert objTest2;
            
            Glxy_ProjectRequestASA__c objTest1a =  new Glxy_ProjectRequestASA__c();
            objTest1a.ProjectAgencyID__c = objTest1.id;
            objTest1a.OldASA__c = 'AAAS';
            objTest1a.RequestASAID__c = 1112;
            
            Glxy_ProjectRequestASA__c objTest1b =  new Glxy_ProjectRequestASA__c();
            objTest1b.ProjectAgencyID__c = objTest1.id;
            objTest1b.OldASA__c = 'AAAB';
            objTest1b.RequestASAID__c = 1113;
            
            Glxy_ProjectRequestASA__c objTest2a =  new Glxy_ProjectRequestASA__c();
            objTest2a.ProjectAgencyID__c = objTest2.id;
            objTest2a.OldASA__c = 'AAAD';
            objTest2a.RequestASAID__c = 1114;
            
            List<Glxy_ProjectRequestASA__c> RequestASAs = new List<Glxy_ProjectRequestASA__c> {objTest1a, objTest1b, objTest2a};
            Insert RequestASAs;
            
            Delete objTest1a;

        }
         
    
}