src/objects/Glxy_Lease__c.object
<CustomObject>
    <customHelpPage>GLXY_HelpPage</customHelpPage>
    <description>This table contains lease information at the beginning of the fiscal year.  This information is updated at the beginning of each fiscal year.</description>
    <fields>
        <fullName>BaseAnnualRent__c</fullName>
        <inlineHelpText>Be sure to click save to adjust monthly impact.</inlineHelpText>
        <label>Base Annual Rent</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BaseLeaseEffectiveDate__c</fullName>
        <label>Lease Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DelegatedLease__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Indicator Box populated with a check if designated as a Delegated Lease in REXUS.</inlineHelpText>
        <label>Delegated Lease</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Delegated_Lease_Rep_lkp__c</fullName>
        <formula>IF(DelegatedLease__c = true, &apos;True&apos;, &apos;False&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Delegated Lease</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExpirationDateofLease__c</fullName>
        <description>Expiration Date</description>
        <label>Lease Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IAConverstionDate__c</fullName>
        <inlineHelpText>The date upon which the fund type converts from IA Base to NOA Base</inlineHelpText>
        <label>IA/NOA Conversion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RegionCD__c</fullName>
        <description>Region Code</description>
        <label>Region Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StatusCode__c</fullName>
        <description>Status Code</description>
        <inlineHelpText>Current status of during G2 Base Sertting period. Options are Active, Terminated, Pending.
DL	Deleted
PD	Pending
TM	Terminated
AC	Active</inlineHelpText>
        <label>Status Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_IA_Sq_feet__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total IA Sq ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_NOA_Sq_feet__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total NOA Sq ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Lease</label>
    <nameField>
        <label>Lease Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Glxy_LeaseProjects__c.object
<CustomObject>
    <customHelpPage>GLXY_HelpPage</customHelpPage>
    <description>This table contains information on all the New, Renewal, Extension, Succeeding, Superseding, Terminating, Chg in SF, and New/Replacing leases associated with a Project.  The Project is the starting point for new leases or changes to existing leases.</description>
    <fields>
        <fullName>AnnualRent__c</fullName>
        <defaultValue>0</defaultValue>
        <label>New Annual Rent</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BDGFlag__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Include In Budget Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CancelARentIA__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Cancellation Annual Rent IA</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CancelARentNOA__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Cancellation Annual Rent NOA</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>DelegatedProject__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This designation is determined as &apos;yes&apos;  if authority has been delegated to a client agency.</inlineHelpText>
        <label>Delegated Project</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Delegated_Project_Rep_lkp__c</fullName>
        <formula>IF( DelegatedProject__c =true, &apos;True&apos;, &apos;False&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Delegated Project</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EffectiveDate__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EscalARentIA__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Escalation Annual Rent IA</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>EscalARentNOA__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Escalation Annual Rent NOA</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ExpanARentIA__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Expansion Annual Rent IA</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ExpanARentNOA__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Expansion Annual Rent NOA</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Old_Annual_Rent__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Old Annual Rent</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProcessedDateFY__c</fullName>
        <formula>Text(YEAR(ProcessedDate__c + 92 ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Process Date FY</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectStatus__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RegionCd__c</fullName>
        <label>Region Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>eEorA__c</fullName>
        <inlineHelpText>Estimated or Actual</inlineHelpText>
        <label>Effective Date Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Actual</fullName>
                </value>
                <value>
                    <fullName>Estimate</fullName>
                </value>
                <value>
                    <fullName>Voided</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Lease Project</label>
    <nameField>
        <label>Project Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lease Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Glxy_LumpSum__c.object
<CustomObject>
    <description>This table contains the lump sum changes to lease payments for a single or successive months that are not changes to the annual rental rate.  These are one-time non-recurring payments such as annual tax adjustments, claims, or lease buy-outs.</description>
    <fields>
        <fullName>BDGFlag__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Checkmark indicates item is included in budget projection</inlineHelpText>
        <label>Include in Budget Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EffectiveDate__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ExpirationDate__c</fullName>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FY_Obligation_IA__c</fullName>
        <label>FY Obligation IA</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FY_Obligation_NOA__c</fullName>
        <label>FY Obligation NOA</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LeaseNumber__c</fullName>
        <label>Lease Number</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>Value entered falls outside your users region</errorMessage>
            <filterItems>
                <field>$User.Glxy_Region_Code__c</field>
                <operation>equals</operation>
                <valueField>Glxy_Lease__c.RegionCD__c</valueField>
            </filterItems>
            <filterItems>
                <field>$User.Glxy_Region_Code__c</field>
                <operation>equals</operation>
                <value>CO</value>
            </filterItems>
            <infoMessage>Lease in this list are limited to your region</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Glxy_Lease__c</referenceTo>
        <relationshipLabel>Lump Sums</relationshipLabel>
        <relationshipName>Lump_Sums</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProcessedDateFY__c</fullName>
        <formula>Text(YEAR(ProcessedDate__c + 92 ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Process Date FY</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RegionCD__c</fullName>
        <formula>Text(LeaseNumber__r.RegionCD__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <label>Lump Sum</label>
    <nameField>
        <displayFormat>LS-{000000}</displayFormat>
        <label>Lump Sum ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lump Sums</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Glxy_LumpSumObligations__c.object
<CustomObject>
    <fields>
        <fullName>FY_Obligation_IA__c</fullName>
        <formula>Apr_IA__c + May_IA__c + Jun_IA__c + Jul_IA__c + Aug_IA__c + Sep_IA__c + Oct_IA__c + Nov_IA__c + Dec_IA__c + JAN_IA__c + Feb_IA__c + Mar_IA__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>FY Obligation IA</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FY_Obligation_NOA__c</fullName>
        <formula>Apr_NOA__c + May_NOA__c + Jun_NOA__c + Jul_NOA__c + Aug_NOA__c + Sep_NOA__c + Oct_NOA__c + Nov_NOA__c + Dec_NOA__c + JAN_NOA__c + Feb_NOA__c + Mar_NOA__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>FY Obligation NOA</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FiscalYear__c</fullName>
        <label>Fiscal Year</label>
        <length>4</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LumpSum__c</fullName>
        <label>Lump Sum</label>
        <referenceTo>Glxy_LumpSum__c</referenceTo>
        <relationshipLabel>Lump Sum Obligations</relationshipLabel>
        <relationshipName>Lump_Sum_Obligations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Lump Sum Obligations</label>
    <nameField>
        <displayFormat>LSO-{000000}</displayFormat>
        <label>Lump Sum Obligation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lump Sum Obligations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Glxy_BC_TrendAnalysis.cls
public with sharing class Glxy_BC_TrendAnalysis {
	
	public String 	strRegion               {get; set;}
    Public Boolean 	blnIncludeinBudgetFlag  {get; set;}
    Public String 	strDelegatedFlag        {get; set;}
	Public String 	strCurrrentFY        	{get; set;}
    
	public String  strFiscalYear1	{get; set;}
	public Decimal EscalationNOA1	{get; set;}
	public Decimal CancellationNOA1	{get; set;}
	public Decimal LumpSumNOA1		{get; set;}
	public Decimal ExpansionNOA1	{get; set;}
	public Decimal EscalationIA1	{get; set;}
	public Decimal CancellationIA1	{get; set;}
	public Decimal ExpansionIA1		{get; set;}
	public Decimal LumpSumIA1		{get; set;}
	
	public String  strFiscalYear2	{get; set;}
	public Decimal EscalationNOA2	{get; set;}
	public Decimal CancellationNOA2	{get; set;}
	public Decimal LumpSumNOA2		{get; set;}
	public Decimal ExpansionNOA2	{get; set;}
	public Decimal EscalationIA2	{get; set;}
	public Decimal CancellationIA2	{get; set;}
	public Decimal ExpansionIA2		{get; set;}
	public Decimal LumpSumIA2		{get; set;}
	
	public String  strFiscalYear3	{get; set;}
	public Decimal EscalationNOA3	{get; set;}
	public Decimal CancellationNOA3	{get; set;}
	public Decimal LumpSumNOA3		{get; set;}
	public Decimal ExpansionNOA3	{get; set;}
	public Decimal EscalationIA3	{get; set;}
	public Decimal CancellationIA3	{get; set;}
	public Decimal ExpansionIA3		{get; set;}
	public Decimal LumpSumIA3		{get; set;}
	
	public String  strFiscalYear4	{get; set;}
	public Decimal EscalationNOA4	{get; set;}
	public Decimal CancellationNOA4	{get; set;}
	public Decimal LumpSumNOA4		{get; set;}
	public Decimal ExpansionNOA4	{get; set;}
	public Decimal EscalationIA4	{get; set;}
	public Decimal CancellationIA4	{get; set;}
	public Decimal ExpansionIA4		{get; set;}
	public Decimal LumpSumIA4		{get; set;}
	
	public String  strFiscalYear5	{get; set;}
	public Decimal EscalationNOA5	{get; set;}
	public Decimal CancellationNOA5	{get; set;}
	public Decimal LumpSumNOA5		{get; set;}
	public Decimal ExpansionNOA5	{get; set;}
	public Decimal EscalationIA5	{get; set;}
	public Decimal CancellationIA5	{get; set;}
	public Decimal ExpansionIA5		{get; set;}
	public Decimal LumpSumIA5		{get; set;}
	
	Private String strSOQL;
	Private String strFiscalYear;
	AggregateResult[] AgR;
	 
	Public Decimal fnCheckNull(Decimal DataInput) {
        if (DataInput == null){
            return 0;
        } else {
            return DataInput;
        }   
    }
    
    public Glxy_BC_TrendAnalysis(){
     	
     	if (System.currentPageReference().getParameters().get('Region')!=null){
            strRegion = System.currentPageReference().getParameters().get('Region');
            strDelegatedFlag = '\'False\'';
            blnIncludeinBudgetFlag = True;
        }else{
            strRegion = '\'4\'';
            strDelegatedFlag = '\'False\'';
            blnIncludeinBudgetFlag = True;
        }
        
        Integer intCurrentFy = date.today().Year(); //Current Fiscal Year, add +1 after September 
        Integer intCurrentYearMonth = date.today().Month();
        if (intCurrentYearMonth > 9){
            intCurrentFy +=1;
        }
        strCurrrentFY = String.ValueOf(intCurrentFy);
               
        //Column 1: (Fiscal Year - 2)
        strFiscalYear1 = String.ValueOf(intCurrentFy - 2);
        subBuildSQL (strFiscalYear1, False);
        AgR = Database.Query(strSOQL);
        for (AggregateResult RowData : AgR) { 
        	EscalationNOA1   = (Decimal) RowData.get('EscalationNOA');
        	CancellationNOA1 = (Decimal) RowData.get('CancellationNOA');
        	ExpansionNOA1    = (Decimal) RowData.get('ExpansionNOA');
        	EscalationIA1    = (Decimal) RowData.get('EscalationIA');
        	CancellationIA1  = (Decimal) RowData.get('CancellationIA');
        	ExpansionIA1     = (Decimal) RowData.get('ExpansionIA');
        }
        
        //Column 2: (Fiscal Year - 1)
        strFiscalYear2 = String.ValueOf(intCurrentFy - 1);
        subBuildSQL (strFiscalYear2, False);
        AgR = Database.Query(strSOQL);
        for (AggregateResult RowData : AgR) { 
        	EscalationNOA2   = (Decimal) RowData.get('EscalationNOA');
        	CancellationNOA2 = (Decimal) RowData.get('CancellationNOA');
        	ExpansionNOA2    = (Decimal) RowData.get('ExpansionNOA');
        	EscalationIA2    = (Decimal) RowData.get('EscalationIA');
        	CancellationIA2  = (Decimal) RowData.get('CancellationIA');
        	ExpansionIA2     = (Decimal) RowData.get('ExpansionIA');
        }
        
        //Column 3: (Fiscal Year)
        strFiscalYear3 = String.ValueOf(intCurrentFy);
       	subBuildSQL (strFiscalYear3, False);
        AgR = Database.Query(strSOQL);
        for (AggregateResult RowData : AgR) { 
        	EscalationNOA3   = (Decimal) RowData.get('EscalationNOA');
        	CancellationNOA3 = (Decimal) RowData.get('CancellationNOA');
        	ExpansionNOA3    = (Decimal) RowData.get('ExpansionNOA');
        	EscalationIA3    = (Decimal) RowData.get('EscalationIA');
        	CancellationIA3  = (Decimal) RowData.get('CancellationIA');
        	ExpansionIA3     = (Decimal) RowData.get('ExpansionIA');
        }
        
        //Column 4: (Fiscal Year + 1)
        strFiscalYear4 = String.ValueOf(intCurrentFy + 1);
       	subBuildSQL (strFiscalYear4, True);
        AgR = Database.Query(strSOQL);
        for (AggregateResult RowData : AgR) { 
        	EscalationNOA4   = (Decimal) RowData.get('EscalationNOA');
        	CancellationNOA4 = (Decimal) RowData.get('CancellationNOA');
        	ExpansionNOA4    = (Decimal) RowData.get('ExpansionNOA');
        	EscalationIA4    = (Decimal) RowData.get('EscalationIA');
        	CancellationIA4  = (Decimal) RowData.get('CancellationIA');
        	ExpansionIA4     = (Decimal) RowData.get('ExpansionIA');
        }
        
        //Column 5: (Fiscal Year + 2)
        strFiscalYear5 = String.ValueOf(intCurrentFy + 2);
       	subBuildSQL (strFiscalYear5, True);
        AgR = Database.Query(strSOQL);
        for (AggregateResult RowData : AgR) { 
        	EscalationNOA5   = (Decimal) RowData.get('EscalationNOA');
        	CancellationNOA5 = (Decimal) RowData.get('CancellationNOA');
        	ExpansionNOA5    = (Decimal) RowData.get('ExpansionNOA');
        	EscalationIA5    = (Decimal) RowData.get('EscalationIA');
        	CancellationIA5  = (Decimal) RowData.get('CancellationIA');
        	ExpansionIA5     = (Decimal) RowData.get('ExpansionIA');
        }
        
        subLoadLumpSumData(intCurrentFy);
	}
	
	Private void subBuildSQL(String strFiscalYear, Boolean blnFutureFiscalYear){
		
		If (blnFutureFiscalYear){
			strSOQL =  'Select Sum(EscalARentNOA__c) EscalationNOA, Sum(CancelARentNOA__c) CancellationNOA, Sum(ExpanARentNOA__c) ExpansionNOA, ' +
						'		Sum(EscalARentIA__c) EscalationIA, Sum(CancelARentIA__c) CancellationIA, Sum(ExpanARentIA__c) ExpansionIA ' +
	                    'From   Glxy_LeaseProjects__c ' +
	                    'Where 	ProcessedDateFY__c >= \'' + String.escapeSingleQuotes(strCurrrentFY) + '\' ' +
                    	'And 	ProcessedDateFY__c <= \'' + String.escapeSingleQuotes(strFiscalYear) + '\' ' +
	                    'And    RegionCD__c In (' + String.escapeSingleQuotes(strRegion) + ') ' +
	                    'And    Delegated_Project_Rep_lkp__c In (' + String.escapeSingleQuotes(strDelegatedFlag) + ') ' + 
	                    'And    BDGFlag__c = :blnIncludeinBudgetFlag ' +
	                    'And 	ProjectStatus__c <> \'Cancelled\' ';
		} else {
			strSOQL =  'Select  Sum(EscalARentNOA__c) EscalationNOA, Sum(CancelARentNOA__c) CancellationNOA, Sum(ExpanARentNOA__c) ExpansionNOA, ' +
						'		Sum(EscalARentIA__c) EscalationIA, Sum(CancelARentIA__c) CancellationIA, Sum(ExpanARentIA__c) ExpansionIA ' +
	                    'From   Glxy_LeaseProjects__c ' +
	                    'Where 	ProcessedDateFY__c = \'' + String.escapeSingleQuotes(strFiscalYear) + '\' ' +
	                    'And    RegionCD__c In (' + String.escapeSingleQuotes(strRegion) + ') ' +
	                    'And    Delegated_Project_Rep_lkp__c In (' + String.escapeSingleQuotes(strDelegatedFlag) + ') ' + 
	                    'And    BDGFlag__c = :blnIncludeinBudgetFlag ' +
	                    'And 	ProjectStatus__c <> \'Cancelled\' ';
		}       
        strSOQL = strSOQL.Replace('\\',''); 
        System.debug('MyDebug SQL = ' + strSOQL);
	}
	
	Private void subLoadLumpSumData(Integer intCurrentFYParameter){
		
		strSOQL =  'Select  FiscalYear__c, Sum(FY_Obligation_IA__c) LumpSumIAAmount, Sum(FY_Obligation_NOA__c) LumpSumNOAAmount ' +
                    'From   Glxy_LumpSumObligations__c ' +
                    'Where 	FiscalYear__c >= \'' + String.Valueof(intCurrentFYParameter - 2) + '\' ' +
                    'And 	FiscalYear__c <= \'' + String.Valueof(intCurrentFYParameter + 2) + '\' ' +
                    'And    LumpSum__r.LeaseNumber__r.RegionCD__c In (' + String.escapeSingleQuotes(strRegion) + ') ' +
                    'And    LumpSum__r.LeaseNumber__r.Delegated_Lease_Rep_lkp__c In (' + String.escapeSingleQuotes(strDelegatedFlag) + ') ' +
                    'And    LumpSum__r.BDGFlag__c = :blnIncludeinBudgetFlag ' + 
                    'Group by FiscalYear__c ' + 
                    'Order by FiscalYear__c ';
		
		strSOQL = strSOQL.Replace('\\',''); 
        System.debug('MyDebug LS-SQL = ' + strSOQL);
        
        AgR = Database.Query(strSOQL);
        
        for (AggregateResult RowData : AgR) { 
        	If (String.ValueOf(RowData.get('FiscalYear__c')) == String.ValueOf(intCurrentFYParameter - 2)){
        		LumpSumIA1 = (Decimal) RowData.get('LumpSumIAAmount');
        		LumpSumNOA1 = (Decimal) RowData.get('LumpSumNOAAmount');
        	} else If (String.ValueOf(RowData.get('FiscalYear__c')) == String.ValueOf(intCurrentFYParameter - 1)){
        		LumpSumIA2 = (Decimal) RowData.get('LumpSumIAAmount');
        		LumpSumNOA2 = (Decimal) RowData.get('LumpSumNOAAmount');
        	} else If  (String.ValueOf(RowData.get('FiscalYear__c')) == String.ValueOf(intCurrentFYParameter)){
        		LumpSumIA3 = (Decimal) RowData.get('LumpSumIAAmount');
        		LumpSumNOA3 = (Decimal) RowData.get('LumpSumNOAAmount');
        	} else If  (String.ValueOf(RowData.get('FiscalYear__c')) == String.ValueOf(intCurrentFYParameter + 1)){
        		LumpSumIA4 = (Decimal) RowData.get('LumpSumIAAmount');
        		LumpSumNOA4 = (Decimal) RowData.get('LumpSumNOAAmount');
        	} else If  (String.ValueOf(RowData.get('FiscalYear__c')) == String.ValueOf(intCurrentFYParameter + 2)){
        		LumpSumIA5 = (Decimal) RowData.get('LumpSumIAAmount');
        		LumpSumNOA5 = (Decimal) RowData.get('LumpSumNOAAmount');	
        	}
        }
       
	} 
	
	
	// **** RUN all the TEST methods for code coverage ... ****//    
   	private static testmethod void testGlxy_BC_TrendAnalysis() {
        PageReference pageRef = Page.Glxy_rptBudgetTrends;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('Region', '\'1\'');
        
        Glxy_LeaseProjects__c objPro = new Glxy_LeaseProjects__c();
        objPro.Name='123456789';
        Date myDate = date.newinstance(Datetime.Now().Date().Year(), 10, 10);  
        objPro.EffectiveDate__c = myDate;
        objPro.AnnualRent__c = 1000.0;
        objPro.RegionCd__c = '1';
        objPro.DelegatedProject__c = true;
        objPro.ProjectStatus__c = 'Active';
        objPro.eEorA__c = 'ACTUAL';
        objPro.Old_Annual_Rent__c = 1000.0;
        insert objPro;
         
        Glxy_LeaseProjects__c objPro1 = new Glxy_LeaseProjects__c();
        objPro1.Name='123456799';
        Date myDate1 = date.newinstance(Datetime.Now().Date().Year(), 10, 10);  
        objPro1.EffectiveDate__c = myDate1;
        objPro1.AnnualRent__c = 1000.0;
        objPro1.RegionCd__c = '1';
        objPro.DelegatedProject__c = true;
        objPro1.ProjectStatus__c = 'Active';
        objPro1.eEorA__c = 'ESTIMATE';
        objPro1.Old_Annual_Rent__c = 1000.0;
        insert objPro1;
        
       	Date myDate2 = date.newinstance(Datetime.Now().Date().Year(), 10, 10);  
              	 
	    Glxy_Lease__c objleaseEntry = new Glxy_Lease__c(
            StatusCode__c = 'Active',
            BaseLeaseEffectiveDate__c = Datetime.Now().Date(),
            ExpirationDateofLease__c = Datetime.Now().Date().addYears(10),
            IAConverstionDate__c = Datetime.Now().Date().addYears(5),
            RegionCD__c = '1',
            DelegatedLease__c = false,
            Total_NOA_Sq_feet__c = 0,
            Total_IA_Sq_feet__c = 0,
            name='LNV00374',
            BaseAnnualRent__c = 2222);
        insert objleaseEntry;
        System.Assert(objleaseEntry!=NULL);
        
	    Glxy_LumpSum__c objTestLS = new Glxy_LumpSum__c();
	    objTestLS.LeaseNumber__c = objleaseEntry.id;
	    objTestLS.EffectiveDate__c = myDate2.addyears(-5);
	    objTestLS.ExpirationDate__c = myDate2.addyears(+5);
	    objTestLS.BDGFlag__c = true;
	    objTestLS.amount__c = 200;
	    insert objTestLS;
	    System.Assert(objTestLS!=NULL);
        
        Glxy_BC_TrendAnalysis objTest = new Glxy_BC_TrendAnalysis();
        
        objTest.strRegion = '1';
    	objTest.blnIncludeinBudgetFlag = true;
    	objTest.strCurrrentFY = string.valueof(myDate2.Year());
    
		objTest.strFiscalYear1	 = '0';
		objTest.EscalationNOA1	 = 0;
		objTest.CancellationNOA1 = 0;
		objTest.LumpSumNOA1		 = 0;
		objTest.ExpansionNOA1	 = 0;
		objTest.EscalationIA1	 = 0;
		objTest.CancellationIA1	 = 0;
		objTest.ExpansionIA1	 = 0;
		objTest.LumpSumIA1		 = 0;
		
		objTest.strFiscalYear2	 = '0';
		objTest.EscalationNOA2	 = 0;
		objTest.CancellationNOA2 = 0;
		objTest.LumpSumNOA2		 = 0;
		objTest.ExpansionNOA2	 = 0;
		objTest.EscalationIA2	 = 0;
		objTest.CancellationIA2	 = 0;
		objTest.ExpansionIA2	 = 0;
		objTest.LumpSumIA2		 = 0;
		
		objTest.strFiscalYear3	 = '0';
		objTest.EscalationNOA3	 = 0;
		objTest.CancellationNOA3 = 0;
		objTest.LumpSumNOA3		 = 0;
		objTest.ExpansionNOA3	 = 0;
		objTest.EscalationIA3	 = 0;
		objTest.CancellationIA3	 = 0;
		objTest.ExpansionIA3	 = 0;
		objTest.LumpSumIA3		 = 0;
		
		objTest.strFiscalYear4	 = '0';
		objTest.EscalationNOA4	 = 0;
		objTest.CancellationNOA4 = 0;
		objTest.LumpSumNOA4		 = 0;
		objTest.ExpansionNOA4	 = 0;
		objTest.EscalationIA4	 = 0;
		objTest.CancellationIA4	 = 0;
		objTest.ExpansionIA4	 = 0;
		objTest.LumpSumIA4		 = 0;
		
		objTest.strFiscalYear5	 = '0';
		objTest.EscalationNOA5	 = 0;
		objTest.CancellationNOA5 = 0;
		objTest.LumpSumNOA5		 = 0;
		objTest.ExpansionNOA5	 = 0;
		objTest.EscalationIA5	 = 0;
		objTest.CancellationIA5	 = 0;
		objTest.ExpansionIA5	 = 0;
		objTest.LumpSumIA5		 = 0;
	
        Decimal inputDD = 0.0;
        Decimal outputD =  objTest.fnCheckNull(inputDD);
        Decimal outputD2 =  objTest.fnCheckNull(null);
        System.Assert(objTest!=NULL);
        
    }
	
}