src/objects/Glxy_LeaseProjects__c.object
<CustomObject>
    <customHelpPage>GLXY_HelpPage</customHelpPage>
    <description>This table contains information on all the New, Renewal, Extension, Succeeding, Superseding, Terminating, Chg in SF, and New/Replacing leases associated with a Project.  The Project is the starting point for new leases or changes to existing leases.</description>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EffectiveDate__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RegionCd__c</fullName>
        <label>Region Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RexusNewIASqFt__c</fullName>
        <label>Rexus New IA Sq Ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RexusNewNOASqFt__c</fullName>
        <label>Rexus New NOA Sq Ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>GU</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NC</fullName>
                </value>
                <value>
                    <fullName>ND</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Lease Project</label>
    <nameField>
        <label>Project Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lease Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Glxy_LPLumpSum__c.object
<CustomObject>
    <description>This table contains the lump sum changes to lease project payments for a single or successive months that are not changes to the annual rental rate.  These are one-time non-recurring payments such as annual tax adjustments, claims, or project buy-outs.</description>
    <fields>
        <fullName>EffectiveDate__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProjectNumber__c</fullName>
        <label>Project Number</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>Region value specified is outside your region</errorMessage>
            <filterItems>
                <field>$User.Glxy_Region_Code__c</field>
                <operation>equals</operation>
                <valueField>Glxy_LeaseProjects__c.RegionCd__c</valueField>
            </filterItems>
            <filterItems>
                <field>$User.Glxy_Region_Code__c</field>
                <operation>equals</operation>
                <value>CO</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Glxy_LeaseProjects__c</referenceTo>
        <relationshipLabel>Lease Proj Lump Sums</relationshipLabel>
        <relationshipName>LP_Lump_Sums</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RegionCD__c</fullName>
        <formula>TEXT(ProjectNumber__r.RegionCd__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <label>Lease Proj Lump Sum</label>
    <nameField>
        <displayFormat>LPLS-{000000}</displayFormat>
        <label>LP Lump Sum ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lease Proj Lump Sums</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Glxy_ProjectLocation__c.object
<CustomObject>
    <description>This table contains the Building information for each project.  One project can have multiple buildings assocated with it.</description>
    <fields>
        <fullName>Address__c</fullName>
        <formula>BuildingNumber__r.Street_Address__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BuildingName__c</fullName>
        <formula>BuildingNumber__r.Building_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Building Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BuildingNumber__c</fullName>
        <label>Building Number</label>
        <referenceTo>PBS_Building__c</referenceTo>
        <relationshipLabel>Project Locations</relationshipLabel>
        <relationshipName>Project_Locations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <formula>BuildingNumber__r.City__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LocationCode__c</fullName>
        <formula>BuildingNumber__r.Location_Code_Plus__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Location Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectNumber__c</fullName>
        <label>Project Number</label>
        <referenceTo>Glxy_LeaseProjects__c</referenceTo>
        <relationshipName>Project_Locations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <formula>BuildingNumber__r.State_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>State</label>
        <type>Text</type>
    </fields>
    <label>Project Location</label>
    <nameField>
        <displayFormat>PL-{00000}</displayFormat>
        <label>Project Location ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PBS_Building__c.object
<CustomObject>
    <description>PBS Common Building Object</description>
    <fields>
        <fullName>Building_ID__c</fullName>
        <externalId>true</externalId>
        <label>Building ID</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location_Code_Plus__c</fullName>
        <externalId>true</externalId>
        <label>Location Code Plus</label>
        <length>8</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>PBS Building</label>
    <nameField>
        <displayFormat>PBS-BLDG-{000000000}</displayFormat>
        <label>PBS Building Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PBS Buildings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GLXY_LPLSBuildingRelatedList.cls
public with sharing class GLXY_LPLSBuildingRelatedList {
	
	private final Glxy_LPLumpSum__c LSObj;
 
	 public List<Glxy_ProjectLocation__c> projectLocations{get;set;}
	
	    public GLXY_LPLSBuildingRelatedList(ApexPages.StandardController controller) {
	
	       LSObj=(Glxy_LPLumpSum__c)controller.getRecord();
	       Glxy_LPLumpSum__c objLS=[select ProjectNumber__c from Glxy_LPLumpSum__c where id =:LSObj.id];
	       projectLocations=[select id, Name,BuildingNumber__c, BuildingNumber__r.Name, BuildingName__c,Address__c, City__c, State__c, LocationCode__c from Glxy_ProjectLocation__c where ProjectNumber__c=:objLS.ProjectNumber__c];
	
	    }
	    
	      @isTest
		static void Test_GLXY_LPLSBuildingRelatedList (){
	  
		Glxy_LeaseProjects__c project= new Glxy_LeaseProjects__c();
	   	//project.StatusCode__c='Active';
	   	Date myDate = date.newinstance(2012, 2, 17);
	    Date myDate1 = date.newinstance(2013, 2, 17);
	   	project.EffectiveDate__c=myDate ;
	   	//project.ExpirationDateofLease__c=myDate1 ;
	   	project.RegionCD__c='3';
	   	project.RexusNewNOASqFt__c=1000;
	   	project.RexusNewIASqFt__c=1000;
	   	//project.BaseSquareFeet__c=2000;
	   
	   	insert project;
	   
	   	Glxy_LPLumpSum__c pi = new Glxy_LPLumpSum__c();
	   	pi.ProjectNumber__c=project.id;
	   	insert pi;
		   
	   	PBS_Building__c build= new PBS_Building__c();
	   	build.Location_Code_Plus__c='test';
	   	build.Building_ID__c=123;
	   	insert build;
	   
	   	Glxy_ProjectLocation__c  ll= new Glxy_ProjectLocation__c ();
	   	ll.ProjectNumber__c=project.id;
	   	ll.BuildingNumber__c=build.id;
	   
	   	insert ll;
	   	system.assertNotEquals(NULL,ll);
	   	
	    ApexPages.StandardController con = new ApexPages.StandardController(pi);
	   
	   	GLXY_LPLSBuildingRelatedList rl= new GLXY_LPLSBuildingRelatedList(con);
	  }
	

}