src/objects/Glxy_LeaseProjects__c.object
<CustomObject>
    <customHelpPage>GLXY_HelpPage</customHelpPage>
    <description>This table contains information on all the New, Renewal, Extension, Succeeding, Superseding, Terminating, Chg in SF, and New/Replacing leases associated with a Project.  The Project is the starting point for new leases or changes to existing leases.</description>
    <fields>
        <fullName>AnnualRent__c</fullName>
        <defaultValue>0</defaultValue>
        <label>New Annual Rent</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AssociatedLeases_lkup__c</fullName>
        <description>Since SF cannot handle multiple child objects, this field is designed to aggregate all the Associated Leases that are tied to this project. This field is updated via a trigger on the Associated Lease object. This field is used across all the Reports.</description>
        <label>Associated Leases (Expiration Date)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BDGFlag__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Include In Budget Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Budget_Exclusion_Reason__c</fullName>
        <label>Budget Exclusion Reason</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ChangeinIASQFt__c</fullName>
        <formula>IASquareFeet__c - OldIASqFt__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Change in IA Sq Ft</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ChangeinNOASQFt__c</fullName>
        <formula>NOASquareFeet__c - OldNOASqFt__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Change in NOA Sq Ft</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EffectiveDate__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IASquareFeet__c</fullName>
        <defaultValue>0</defaultValue>
        <label>New IA Sq Ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NOASquareFeet__c</fullName>
        <defaultValue>0</defaultValue>
        <label>New NOA Sq Ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NewLease__c</fullName>
        <inlineHelpText>New lease numbers to be assigned by REXUS for Succeeding, Superseding, and New/Replacing actions.  For Extensions, Renewal, Expansion, Reduction, and Other actions, this field will reflect existing lease number (Old Lease Number).</inlineHelpText>
        <label>New Lease Number</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OldIASqFt__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Old IA Sq Ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OldNOASqFt__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Old NOA Sq Ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProjectStatus__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_Type__c</fullName>
        <inlineHelpText>Project Type</inlineHelpText>
        <label>Project Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Change in Services</fullName>
                </value>
                <value>
                    <fullName>Change in SF</fullName>
                </value>
                <value>
                    <fullName>Change To External Contacts</fullName>
                </value>
                <value>
                    <fullName>Escalation</fullName>
                </value>
                <value>
                    <fullName>Expansion</fullName>
                </value>
                <value>
                    <fullName>Extension</fullName>
                </value>
                <value>
                    <fullName>Holdover</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>New/Replacing</fullName>
                </value>
                <value>
                    <fullName>Operating Cost Escalation</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Real Estate Tax Escalation</fullName>
                </value>
                <value>
                    <fullName>Reduction</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Step Rent Decrease</fullName>
                </value>
                <value>
                    <fullName>Step Rent Increase</fullName>
                </value>
                <value>
                    <fullName>Succeeding</fullName>
                </value>
                <value>
                    <fullName>Superseding</fullName>
                </value>
                <value>
                    <fullName>Termination</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RegionCd__c</fullName>
        <label>Region Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Remarks__c</fullName>
        <label>Remarks</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TeamCode__c</fullName>
        <label>Team Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>eEorA__c</fullName>
        <inlineHelpText>Estimated or Actual</inlineHelpText>
        <label>Effective Date Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Actual</fullName>
                </value>
                <value>
                    <fullName>Estimate</fullName>
                </value>
                <value>
                    <fullName>Voided</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Lease Project</label>
    <nameField>
        <label>Project Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lease Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/GLXY_clsNewReplacingReductionReport.cls
public with sharing class GLXY_clsNewReplacingReductionReport {
public map<string,Glxy_LeaseProjects__c> leaseProjectMap{get;set;}
public decimal iaImpactSum          {get;set;}
public decimal noaImpactSum         {get;set;}
public String iaImpactSumFormatted  {get;set;}
public string noaImpactSumformatted {get;set;}

public String strRegion  {get; set;}

public list<Glxy_LeaseProjects__c> leaseProjectlist{get;set;}

    public GLXY_clsNewReplacingReductionReport () { 
        
        if (System.currentPageReference().getParameters().get('Region')!=null){
            strRegion = System.currentPageReference().getParameters().get('Region');
        }else{
            strRegion = '\'3\'';
        }
                
        iaImpactSum = 0;
        noaImpactSum =0;
        String strSOQL;
        
        leaseProjectMap = new map<string,Glxy_LeaseProjects__c>(); 
        leaseProjectList = new list<Glxy_LeaseProjects__c>();
        
        strSOQL = 'Select id, RegionCd__c, BDGFlag__c, Project_Type__c, EffectiveDate__c,TeamCode__c, NewLease__c,Budget_Exclusion_Reason__c,AnnualRent__c,NOASquareFeet__c, IASquareFeet__c,eEorA__c,  AssociatedLeases_lkup__c,ProjectStatus__c, Remarks__c, ChangeinIASQFt__c, ChangeinNOASQFt__c, name ' + 
                    'From Glxy_LeaseProjects__c ' +
                    'Where Project_Type__c = \'Reduction\' ' +
                    'And    RegionCD__c In (' + String.escapeSingleQuotes(strRegion) + ') ' +
                    'And    ProjectStatus__c <> \'Cancelled\' ' +
                    'Order by RegionCD__c ' ;
                    
        strSOQL = strSOQL.Replace('\\','');             
                           
        list<Glxy_LeaseProjects__c> leaseproj = Database.query(strSOQL);
        for(Glxy_LeaseProjects__c proj :leaseproj){
            if(proj.Remarks__c != null && proj.Remarks__c.contains('created by the system')) {
                //leaseProjectMap.put(proj.Remarks__c.substringBetween('New/Replacing Project ', ' for Prior Lease'),proj);
                if(leaseProjectMap.containsKey(proj.Remarks__c.substringBetween('New/Replacing Project ', ' for Prior Lease'))) {
                
                    string key = proj.Remarks__c.substringBetween('New/Replacing Project ', ' for Prior Lease')+'_d';
                    leaseProjectMap.put(key ,proj);
                
                }
                else if(proj.Remarks__c != null){
                    leaseProjectMap.put(proj.Remarks__c.substringBetween('New/Replacing Project ', ' for Prior Lease'),proj);
                }
            
            }
        }
        //SET<string> keys = leaseProjectMap.keyset();
        list<string> keys = new List<String>(leaseProjectMap.keyset());
        strSOQL = 'select id,RegionCd__c,BDGFlag__c, Project_Type__c, EffectiveDate__c,TeamCode__c, NewLease__c, Budget_Exclusion_Reason__c,AnnualRent__c,NOASquareFeet__c, IASquareFeet__c, eEorA__c,AssociatedLeases_lkup__c,ProjectStatus__c, OldIASqFt__c, OldNOASqFt__c, ChangeinIASQFt__c, ChangeinNOASQFt__c,name ' + 
                   'from Glxy_LeaseProjects__c ' +
                  'where Project_Type__c = \'New/Replacing\' ' +
                    'And RegionCD__c In (' + String.escapeSingleQuotes(strRegion) + ') '  +
                    'and name In :keys ' +
                    'Order by RegionCD__c ' ;
                    
                                            
        strSOQL = strSOQL.Replace('\\',''); 
        
        list<Glxy_LeaseProjects__c> leaseproj1 = Database.query(strSOQL);
        for(Glxy_LeaseProjects__c proj :leaseproj1){
            if(leaseProjectMap.get(proj.name) != null) {
                //if(leaseProjectMap.get(proj.name).EffectiveDate__c == proj.EffectiveDate__c) {
                    leaseProjectList.add(leaseProjectMap.get(proj.name));
                    leaseProjectList.add(proj);   
                //}
                    if(leaseProjectMap.get(proj.name+'_d') != null) {
                       leaseProjectList.add(leaseProjectMap.get(proj.name+'_d'));
                       leaseProjectList.add(proj); 
                    }
            
            }
        
        }
        for(Glxy_LeaseProjects__c  proj1 : leaseProjectList) {
        if(proj1.Project_Type__c =='New/Replacing') {
        iaImpactSum  = iaImpactSum +proj1.OldIASqFt__c;
        noaImpactSum = noaImpactSum +proj1.OldNOASqFt__c;
        }
        else
        {
        iaImpactSum  = iaImpactSum +proj1.ChangeinIASQFt__c;
        noaImpactSum = noaImpactSum +proj1.ChangeinNOASQFt__c;
        }
            
        }
        iaImpactSumFormatted  = iaImpactSum.format();
        noaImpactSumFormatted  = noaImpactSum.format();
    }

}