src/objects/Glxy_BudgetSubmission__c.object
<CustomObject>
    <fields>
        <fullName>RegionCD__c</fullName>
        <label>Region Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ReportingFiscalYear__c</fullName>
        <label>Reporting Fiscal Year</label>
        <length>4</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubmissionType__c</fullName>
        <label>Submission Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Budget Call</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>OMB</fullName>
                </value>
                <value>
                    <fullName>Congressional Justification</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Budget Submission</label>
    <nameField>
        <displayFormat>BudgetID-{0000}</displayFormat>
        <label>Budget Submission ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Submission</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Glxy_BudgetSubmissionData__c.object
<CustomObject>
    <fields>
        <fullName>BudgetSubmissionID__c</fullName>
        <label>Budget Submission ID</label>
        <referenceTo>Glxy_BudgetSubmission__c</referenceTo>
        <relationshipLabel>Budget Submission Data</relationshipLabel>
        <relationshipName>Budget_Submission_Data</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DataFormat__c</fullName>
        <label>Data Format</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>RAW</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Adjustment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FiscalYear__c</fullName>
        <label>Fiscal Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReportColumnIdentifier__c</fullName>
        <label>Report Column Identifier</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ReportingFiscalYear__c</fullName>
        <formula>BudgetSubmissionID__r.ReportingFiscalYear__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Reporting Fiscal Year</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubmissionType__c</fullName>
        <formula>Text(BudgetSubmissionID__r.SubmissionType__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Submission Type</label>
        <type>Text</type>
    </fields>
    <label>Budget Submission Data</label>
    <nameField>
        <displayFormat>ID-{0000}</displayFormat>
        <label>Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Submission Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/GLXY_FutureMethods.cls
public with sharing class GLXY_FutureMethods {
	
    @future public static void AddRegionalBudgetSubmissions(String strReportingFiscalYear, String strSubmissionType){
    	
    	List<Glxy_BudgetSubmission__c> objBudgetSubmissionRecords = New List<Glxy_BudgetSubmission__c>();
    	List<Glxy_BudgetSubmissionData__c> objBudgetSubmissionDataRecords = New List<Glxy_BudgetSubmissionData__c>();
    	Integer intFiscalYearStart;
    	Integer intReportColumnIdentifier;
    	
    	//Before we perform this update we want to set the isFutureUpdate boolean in our Glxy_RecursiveBlocker class to true */
        Glxy_RecursiveBlocker.isFutureUpdate = true;
        
        //Create Budget Submission records ...
        For (Integer intRegion = 1; intRegion <= 11; intRegion ++){
        	objBudgetSubmissionRecords.Add(new Glxy_BudgetSubmission__c(
		        ReportingFiscalYear__c = strReportingFiscalYear,
		       	SubmissionType__c = strSubmissionType,
		       	RegionCD__c = String.ValueOf(intRegion)
	   		));
        }
        Insert objBudgetSubmissionRecords;
        
        //Create Budget Submission DATA records - Template ...
        for (Glxy_BudgetSubmission__c ObjMaster : [SELECT ID, ReportingFiscalYear__c 
        											 From   Glxy_BudgetSubmission__c
                  									 Where  ReportingFiscalYear__c = :strReportingFiscalYear
                  									 And 	SubmissionType__c = :strSubmissionType]){
			 
			 intFiscalYearStart = Integer.ValueOf(ObjMaster.ReportingFiscalYear__c);
			 intReportColumnIdentifier = 1;
			 
			 For (Integer intFY = intFiscalYearStart; intFY <= intFiscalYearStart + 2; intFY ++){    		     
    		     objBudgetSubmissionDataRecords.Add(new Glxy_BudgetSubmissionData__c(
    		     			BudgetSubmissionID__c = ObjMaster.ID,
					        FiscalYear__c = String.ValueOf(intFY),
					       	DataFormat__c = 'RAW',
					       	ReportColumnIdentifier__c = intReportColumnIdentifier
				 ));
				 objBudgetSubmissionDataRecords.Add(new Glxy_BudgetSubmissionData__c(
    		     			BudgetSubmissionID__c = ObjMaster.ID,
					        FiscalYear__c = String.ValueOf(intFY),
					       	DataFormat__c = 'Adjustment',
					       	ReportColumnIdentifier__c = intReportColumnIdentifier
				 ));
				 intReportColumnIdentifier ++;
			 }		 
			 
		}
   		Insert objBudgetSubmissionDataRecords;
   		
   		//Calculate the RAW data  ...
   		GLXY_BC_RefreshBudgetData objRefreshBudgetData = new GLXY_BC_RefreshBudgetData();
   		objRefreshBudgetData.CalculateNumbers(strReportingFiscalYear, strSubmissionType, '1');
   		objRefreshBudgetData.CalculateNumbers(strReportingFiscalYear, strSubmissionType, '2');
   		objRefreshBudgetData.CalculateNumbers(strReportingFiscalYear, strSubmissionType, '3');
   		objRefreshBudgetData.CalculateNumbers(strReportingFiscalYear, strSubmissionType, '4');
   		objRefreshBudgetData.CalculateNumbers(strReportingFiscalYear, strSubmissionType, '5');
   		objRefreshBudgetData.CalculateNumbers(strReportingFiscalYear, strSubmissionType, '6');
   		objRefreshBudgetData.CalculateNumbers(strReportingFiscalYear, strSubmissionType, '7');
   		objRefreshBudgetData.CalculateNumbers(strReportingFiscalYear, strSubmissionType, '8');
   		objRefreshBudgetData.CalculateNumbers(strReportingFiscalYear, strSubmissionType, '9');
   		objRefreshBudgetData.CalculateNumbers(strReportingFiscalYear, strSubmissionType, '10');
   		objRefreshBudgetData.CalculateNumbers(strReportingFiscalYear, strSubmissionType, '11');
   		objRefreshBudgetData.CalculateNumbers(strReportingFiscalYear, strSubmissionType, 'CO');
   		
    }
}