src/objects/Glxy_BudgetCallLineItem__c.object
<CustomObject>
    <fields>
        <fullName>AnnualAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Annual Amount</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Apr__c</fullName>
        <label>Apr</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Aug__c</fullName>
        <label>Aug</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BudgetCategory__c</fullName>
        <label>Budget Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Base Rent</fullName>
                </value>
                <value>
                    <fullName>Cancellation</fullName>
                </value>
                <value>
                    <fullName>Double Rent</fullName>
                </value>
                <value>
                    <fullName>Expansion</fullName>
                </value>
                <value>
                    <fullName>IBAA</fullName>
                </value>
                <value>
                    <fullName>Lump Sums</fullName>
                </value>
                <value>
                    <fullName>Operating Cost Escalation (CPI)</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Project Step Rent</fullName>
                </value>
                <value>
                    <fullName>Rent Increase</fullName>
                </value>
                <value>
                    <fullName>RWA</fullName>
                </value>
                <value>
                    <fullName>Step Rent</fullName>
                </value>
                <value>
                    <fullName>Total</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Taxes</fullName>
                </value>
                <value>
                    <fullName>Project Lump Sums</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DataGroup__c</fullName>
        <label>Data Group</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dec__c</fullName>
        <label>Dec</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>DelegatedLease__c</fullName>
        <label>Delegated Lease</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Feb__c</fullName>
        <label>Feb</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FiscalYear__c</fullName>
        <label>Fiscal Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Jan__c</fullName>
        <label>Jan</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Jul__c</fullName>
        <label>Jul</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Jun__c</fullName>
        <label>Jun</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LeaseNumber__c</fullName>
        <label>Lease Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LeaseStatus__c</fullName>
        <label>Lease Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lease_Expiration_Date__c</fullName>
        <label>Lease Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Mar__c</fullName>
        <label>Mar</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>May__c</fullName>
        <label>May</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Nov__c</fullName>
        <label>Nov</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Oct__c</fullName>
        <label>Oct</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>RegionCode__c</fullName>
        <label>Region Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sep__c</fullName>
        <label>Sep</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SquareFeet__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Square Feet</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Actual</fullName>
                </value>
                <value>
                    <fullName>Estimate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TeamCode__c</fullName>
        <label>Team Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Budget Call Line Item</label>
    <nameField>
        <displayFormat>LI-{0000}</displayFormat>
        <label>Budget Call Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Call Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Glxy_BC_GenerateFY2bProjectionIA.cls
global with sharing class Glxy_BC_GenerateFY2bProjectionIA implements Database.Batchable<AggregateResult>,Database.stateful{
	
	global List<Glxy_BudgetCallLineItem__c> objInsertRecords = New List<Glxy_BudgetCallLineItem__c>();
	AggregateResult objLeaseBudgetCallLineItem;
	Integer intCurrentFY;
	String 	strCurrentFY;
	
	global Iterable<AggregateResult> start(Database.batchableContext info){
	 	return new GLXY_BC_AggregateResultIterableFY2bIA(); 
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope){
    	
    	objInsertRecords.Clear();
    	Decimal dblMonthlyAmount;
    	Decimal dblAnnualAmount;
    	Decimal dblSquareFeet;
    	
    	intCurrentFY = Datetime.Now().Date().Month() > 9? Datetime.Now().Date().Year() + 1 : Datetime.Now().Date().Year();
    	string strDataGroup;
    	
    	for(sObject obj: scope) {
    		objLeaseBudgetCallLineItem = (AggregateResult) obj;
    		
    		dblAnnualAmount = (Decimal) objLeaseBudgetCallLineItem.get('AnnualAmount');
	    	dblMonthlyAmount = (Decimal) objLeaseBudgetCallLineItem.get('AnnualAmount')/12;
	    	dblSquareFeet = (Decimal) objLeaseBudgetCallLineItem.get('SquareFeet') + (Decimal) objLeaseBudgetCallLineItem.get('CancelSquareFeet') + (Decimal) objLeaseBudgetCallLineItem.get('ExpanSquareFeet');
    		
    		//strDataGroup = String.valueOf(objLeaseBudgetCallLineItem.get('DataGroup__c'));
    		//If (strDataGroup == 'IA' && String.valueOf(intCurrentFY + 1) > String.valueOf(objLeaseBudgetCallLineItem.get('IAConversionFY'))){
    		//	strDataGroup = 'NOA';
    		//}
    		
    		objInsertRecords.Add(new Glxy_BudgetCallLineItem__c(
    			FiscalYear__c = String.valueOf(intCurrentFY + 2),
    			LeaseNumber__c = String.valueOf(objLeaseBudgetCallLineItem.get('LeaseNumber__c')),
                BudgetCategory__c = 'Base Rent',
                DataGroup__c = 'IA',
                Status__c = 'Estimate',
                Lease_Expiration_Date__c = Date.valueOf(objLeaseBudgetCallLineItem.get('LeaseExpirationDate')),
                DelegatedLease__c = String.valueOf(objLeaseBudgetCallLineItem.get('DelegatedLease')),
                RegionCode__c = String.valueOf(objLeaseBudgetCallLineItem.get('RegionCode')),
                LeaseStatus__c = String.valueOf(objLeaseBudgetCallLineItem.get('LeaseStatus')),
                TeamCode__c = String.valueOf(objLeaseBudgetCallLineItem.get('TeamCode')),
                AnnualAmount__c = dblAnnualAmount,
                SquareFeet__c = dblSquareFeet,
                Jan__c = dblMonthlyAmount, Feb__c = dblMonthlyAmount, Mar__c = dblMonthlyAmount, Apr__c = dblMonthlyAmount, May__c = dblMonthlyAmount, Jun__c = dblMonthlyAmount,
                Jul__c = dblMonthlyAmount, Aug__c = dblMonthlyAmount, Sep__c = dblMonthlyAmount, Oct__c = dblMonthlyAmount, Nov__c = dblMonthlyAmount, Dec__c = dblMonthlyAmount
            )); 	
    	}
    	
        try{    
            Database.Insert(objInsertRecords, false);
        }catch (DmlException e){
            System.debug('Glxy_BC_GenerateFY2bProjectionIA Insert error - ' + e.getMessage());
        }
    }
    
    global void finish(Database.BatchableContext BC){
    	//Invoke the next batch
    	database.executeBatch(new Glxy_BC_GenerateFYTotals3());
    }
    
}