src/objects/Glxy_BudgetCallLineItem__c.object
<CustomObject>
    <fields>
        <fullName>DelegatedLease__c</fullName>
        <label>Delegated Lease</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LeaseNumber__c</fullName>
        <label>Lease Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LeaseStatus__c</fullName>
        <label>Lease Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lease_Expiration_Date__c</fullName>
        <label>Lease Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Budget Call Line Item</label>
    <nameField>
        <displayFormat>LI-{0000}</displayFormat>
        <label>Budget Call Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Call Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Glxy_Lease__c.object
<CustomObject>
    <customHelpPage>GLXY_HelpPage</customHelpPage>
    <description>This table contains lease information at the beginning of the fiscal year.  This information is updated at the beginning of each fiscal year.</description>
    <fields>
        <fullName>BaseAnnualRent__c</fullName>
        <inlineHelpText>Be sure to click save to adjust monthly impact.</inlineHelpText>
        <label>Base Annual Rent</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BaseLeaseEffectiveDate__c</fullName>
        <label>Lease Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DelegatedLease__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Indicator Box populated with a check if designated as a Delegated Lease in REXUS.</inlineHelpText>
        <label>Delegated Lease</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Delegated_Lease_Rep_lkp__c</fullName>
        <formula>IF(DelegatedLease__c = true, &apos;True&apos;, &apos;False&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Delegated Lease</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExpirationDateofLease__c</fullName>
        <description>Expiration Date</description>
        <label>Lease Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IAConverstionDate__c</fullName>
        <inlineHelpText>The date upon which the fund type converts from IA Base to NOA Base</inlineHelpText>
        <label>IA/NOA Conversion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LeaseID__c</fullName>
        <externalId>true</externalId>
        <label>Lease ID</label>
        <length>8</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Next_FY_Leases__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Flag to identify the leases that are not included in base.</inlineHelpText>
        <label>Next FY Leases</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RegionCD__c</fullName>
        <description>Region Code</description>
        <label>Region Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StatusCode__c</fullName>
        <description>Status Code</description>
        <inlineHelpText>Current status of during G2 Base Sertting period. Options are Active, Terminated, Pending.
DL	Deleted
PD	Pending
TM	Terminated
AC	Active</inlineHelpText>
        <label>Status Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_IA_Sq_feet__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total IA Sq ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_NOA_Sq_feet__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total NOA Sq ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Lease</label>
    <nameField>
        <label>Lease Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Glxy_BC_UpdateDelegatedFlag.cls
global with sharing class Glxy_BC_UpdateDelegatedFlag implements Database.Batchable<sObject>,Database.stateful{
    
    global List<Glxy_BudgetCallLineItem__c> objUpdatedRecords = New List<Glxy_BudgetCallLineItem__c>();
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        string Query =  'SELECT  ID, Name, LeaseID__c, Delegated_Lease_Rep_lkp__c, StatusCode__c, ExpirationDateofLease__c ' + 
                        'FROM  Glxy_Lease__c  ' + 
                        //'Where StatusCode__c = \'Active\' ' + 
                        //'AND   Next_FY_Leases__c = False ' +  
                        'ORDER BY Name ';
        Return Database.getQueryLocator(Query);
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope){
        objUpdatedRecords.Clear();
        Set<String> objSetLeases = New Set<String>(); 
        objSetLeases.Clear();
        Map<String, Glxy_Lease__c> objMapLeases = new Map<String, Glxy_Lease__c>();
        objMapLeases.Clear();
        
        Glxy_Lease__c objLease = null;
        for(sObject obj: scope) {
        	objLease = (Glxy_Lease__c) obj;
        	System.Debug('Lease = ' + objLease.Name);
            objSetLeases.add(objLease.Name);
            objMapLeases.put(objLease.Name, objLease);
        }
        
        List<Glxy_BudgetCallLineItem__c> objBudgetCallLineItems = [    
            Select  ID, LeaseNumber__c
            From    Glxy_BudgetCallLineItem__c  
            Where   LeaseNumber__c in :objSetLeases
            Order by LeaseNumber__c];
                
        for (Glxy_BudgetCallLineItem__c RowData : objBudgetCallLineItems) { 
        	System.Debug('LeaseLoop = ' + objLease.LeaseID__c);
        	System.Debug('LeaseLoopFlag = ' + objMapLeases.get(RowData.LeaseNumber__c));
            objUpdatedRecords.Add(new Glxy_BudgetCallLineItem__c(
                ID = RowData.ID,
                State__c = String.valueOf(RowData.LeaseNumber__c).substring(1,3),
                DelegatedLease__c = objMapLeases.get(RowData.LeaseNumber__c).Delegated_Lease_Rep_lkp__c,
                LeaseStatus__c = objMapLeases.get(RowData.LeaseNumber__c).StatusCode__c
                //Lease_Expiration_Date__c = objMapLeases.get(RowData.LeaseNumber__c).ExpirationDateofLease__c
            ));
        }  
     
        try{    
            Database.update(objUpdatedRecords, false);
        }catch (DmlException e){
            System.debug('Glxy_UpdateDelegatedFlag Update error - ' + e.getMessage());
        }
    }
    
    global void finish(Database.BatchableContext BC){
 		
    	//Invoke the next batch
    	database.executeBatch(new Glxy_BC_GenerateFYTotals());
    	
    }
    
    @isTest (SeeAllData=false) static void testClass(){
        
        Glxy_Lease__c objleaseEntry = new Glxy_Lease__c(
            StatusCode__c='Active',
            BaseLeaseEffectiveDate__c = Datetime.Now().Date().addYears(-5),
            ExpirationDateofLease__c = Datetime.Now().Date().addYears(+5),
            IAConverstionDate__c = Datetime.Now().Date().addYears(+2),
            RegionCD__c = '11',
            Total_NOA_Sq_feet__c = 0,
            Total_IA_Sq_feet__c = 0,
            name='LDE00374',
            BaseAnnualRent__c = 2222);
        insert objleaseEntry;
        System.Assert(objleaseEntry!=NULL);
        
        Glxy_BudgetCallLineItem__c objBCEntry = new Glxy_BudgetCallLineItem__c(
            LeaseNumber__c = 'LDE00374');
        insert objBCEntry;
        
        //Test.startTest();     
        Glxy_BC_UpdateDelegatedFlag objTest = new Glxy_BC_UpdateDelegatedFlag();
        Database.executeBatch(objTest);      
        //Test.stopTest();     
    } 
}