src/objects/Glxy_Lease__c.object
<CustomObject>
    <customHelpPage>GLXY_HelpPage</customHelpPage>
    <description>This table contains lease information at the beginning of the fiscal year.  This information is updated at the beginning of each fiscal year.</description>
    <fields>
        <fullName>BaseLeaseEffectiveDate__c</fullName>
        <label>Lease Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BaseSquareFeet__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Base Sq Ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ExpirationDateofLease__c</fullName>
        <description>Expiration Date</description>
        <label>Lease Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RegionCD__c</fullName>
        <description>Region Code</description>
        <label>Region Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StatusCode__c</fullName>
        <description>Status Code</description>
        <inlineHelpText>Current status of during G2 Base Sertting period. Options are Active, Terminated, Pending.
DL	Deleted
PD	Pending
TM	Terminated
AC	Active</inlineHelpText>
        <label>Status Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_IA_Sq_feet__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total IA Sq ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_NOA_Sq_feet__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total NOA Sq ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Lease</label>
    <nameField>
        <label>Lease Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Glxy_LeaseLocation__c.object
<CustomObject>
    <description>This table contains the Building information for each lease.  One lease can have multiple buildings assocated with it.</description>
    <fields>
        <fullName>Address_lkp__c</fullName>
        <formula>BuildingNumber__r.Street_Address__c</formula>
        <label>Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BuildingNumber__c</fullName>
        <label>Building Number</label>
        <referenceTo>PBS_Building__c</referenceTo>
        <relationshipLabel>LeaseLocations</relationshipLabel>
        <relationshipName>LeaseLocations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Building_Name_lkp__c</fullName>
        <formula>BuildingNumber__r.Building_Name__c</formula>
        <label>Building Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Building_Number_lkp__c</fullName>
        <formula>BuildingNumber__r.Bld_Building_Uk1__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Building Number lkp</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City_lkp__c</fullName>
        <formula>BuildingNumber__r.City__c</formula>
        <label>City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LeaseNumber__c</fullName>
        <label>Lease Number</label>
        <referenceTo>Glxy_Lease__c</referenceTo>
        <relationshipName>LeaseLocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Location_Code__c</fullName>
        <formula>BuildingNumber__r.Location_Code_Plus__c</formula>
        <label>Location Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State_lkp__c</fullName>
        <formula>BuildingNumber__r.State_Code__c</formula>
        <label>State</label>
        <type>Text</type>
    </fields>
    <label>Lease Location</label>
    <nameField>
        <displayFormat>LOC-{00000000}</displayFormat>
        <label>Lease Location ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lease Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Glxy_StepRent__c.object
<CustomObject>
    <description>This table contains the step rent information about leases. This is one kind of lease payment but can have different characteristics.</description>
    <fields>
        <fullName>LeaseNumber__c</fullName>
        <label>Lease Number</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>Region value specified is outside your region</errorMessage>
            <filterItems>
                <field>$User.Glxy_Region_Code__c</field>
                <operation>equals</operation>
                <valueField>Glxy_Lease__c.RegionCD__c</valueField>
            </filterItems>
            <filterItems>
                <field>$User.Glxy_Region_Code__c</field>
                <operation>equals</operation>
                <value>CO</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Glxy_Lease__c</referenceTo>
        <relationshipLabel>Step Rents</relationshipLabel>
        <relationshipName>Step_Rents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RegionCD__c</fullName>
        <formula>TEXT(LeaseNumber__r.RegionCD__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StatusCode__c</fullName>
        <label>Status Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Estimate</fullName>
                </value>
                <value>
                    <fullName>Actual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Step Rent</label>
    <nameField>
        <displayFormat>STP{0000000}</displayFormat>
        <label>Step Rent #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Step Rents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PBS_Building__c.object
<CustomObject>
    <description>PBS Common Building Object</description>
    <fields>
        <fullName>Building_ID__c</fullName>
        <externalId>true</externalId>
        <label>Building ID</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Location_Code_Plus__c</fullName>
        <externalId>true</externalId>
        <label>Location Code Plus</label>
        <length>8</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>PBS Building</label>
    <nameField>
        <displayFormat>PBS-BLDG-{000000000}</displayFormat>
        <label>PBS Building Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PBS Buildings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GLXY_SRBuildingRelatedList.cls
public with sharing class GLXY_SRBuildingRelatedList {

 private final Glxy_StepRent__c SRObj;
 
 public List<Glxy_LeaseLocation__c> leaseLocations{get;set;}

    public GLXY_SRBuildingRelatedList(ApexPages.StandardController controller) {

       SRObj=(Glxy_StepRent__c)controller.getRecord();
       
       Glxy_StepRent__c objSR=[select LeaseNumber__c from Glxy_StepRent__c where id =:SRObj.id];
       leaseLocations=[select id, Name,BuildingNumber__c, BuildingNumber__r.Name, Building_Name_lkp__c, Building_Number_lkp__c, Address_lkp__c, City_lkp__c, State_lkp__c, Location_Code__c from Glxy_LeaseLocation__c where LeaseNumber__c=:objSR.LeaseNumber__c];



    }
    
    
@isTest static void Test_GLXY_SRBuildingRelatedList(){
  
			   Glxy_Lease__c lease= new Glxy_Lease__c();
			   lease.StatusCode__c='Active';
			   Date myDate = 
					date.newinstance(2012, 2, 17);
					 Date myDate1 = 
					date.newinstance(2013, 2, 17);
			   lease.BaseLeaseEffectiveDate__c=myDate ;
			   lease.ExpirationDateofLease__c=myDate1 ;
			   lease.RegionCD__c='3';
				lease.Total_NOA_Sq_feet__c=1000;
			   lease.Total_IA_Sq_feet__c=1000;
			   lease.BaseSquareFeet__c=2000;
			   
			   insert lease;
			   
			  Glxy_StepRent__c pi = new Glxy_StepRent__c();
			   pi.LeaseNumber__c=lease.id;
			   insert pi;
			   
			   PBS_Building__c build= new PBS_Building__c();
			   build.Location_Code_Plus__c='test';
			   build.Building_ID__c=123;
			   insert build;
			   
			   Glxy_LeaseLocation__c  ll= new Glxy_LeaseLocation__c ();
			   ll.LeaseNumber__c=lease.id;
			   ll.BuildingNumber__c=build.id;
			   
			   insert ll;
			   system.assertNotEquals(NULL,ll);
				ApexPages.StandardController con = new ApexPages.StandardController(pi);
			   
			   GLXY_SRBuildingRelatedList rl= new GLXY_SRBuildingRelatedList(con );
  }
}