src/objects/Glxy_FMISVATObligation__c.object
<CustomObject>
    <description>FMIS VAT OBLIGATION</description>
    <fields>
        <fullName>ACTG_PERIOD__c</fullName>
        <label>ACTG PERIOD</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AMT__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BUDGET_ACTVTY_CD__c</fullName>
        <label>BUDGET ACTVTY CODE</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DESCRIPTION__c</fullName>
        <label>DESCRIPTION</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>DTYP__c</fullName>
        <label>DTYP</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FUNC_CD__c</fullName>
        <label>Function CODE</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FUND_CD__c</fullName>
        <label>FUND Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Function_Name__c</fullName>
        <label>Function Name</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LEASE_NO__c</fullName>
        <label>LEASE NUMBER</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PEG_DOC_NUM__c</fullName>
        <label>PDN</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>REGION_CD__c</fullName>
        <label>REGION CODE</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SEQ_NO__c</fullName>
        <label>SEQUENCE NO</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TITLE__c</fullName>
        <label>TITLE</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TT__c</fullName>
        <label>TT</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>FMIS VAT Obligation</label>
    <nameField>
        <label>FMISVATObligation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FMIS VAT OBLIGATION</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Glxy_Lease__c.object
<CustomObject>
    <customHelpPage>GLXY_HelpPage</customHelpPage>
    <description>This table contains lease information at the beginning of the fiscal year.  This information is updated at the beginning of each fiscal year.</description>
    <fields>
        <fullName>BaseAnnualRent__c</fullName>
        <inlineHelpText>Be sure to click save to adjust monthly impact.</inlineHelpText>
        <label>Base Annual Rent</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BaseLeaseEffectiveDate__c</fullName>
        <label>Lease Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ExpirationDateofLease__c</fullName>
        <description>Expiration Date</description>
        <label>Lease Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RegionCD__c</fullName>
        <description>Region Code</description>
        <label>Region Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StatusCode__c</fullName>
        <description>Status Code</description>
        <inlineHelpText>Current status of during G2 Base Sertting period. Options are Active, Terminated, Pending.
DL	Deleted
PD	Pending
TM	Terminated
AC	Active</inlineHelpText>
        <label>Status Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_IA_Sq_feet__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total IA Sq ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_NOA_Sq_feet__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total NOA Sq ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Lease</label>
    <nameField>
        <label>Lease Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Glxy_LeaseAccrual__c.object
<CustomObject>
    <description>This table contains the Lease Accrual information. This information will be provided by BA53 users during the Lease Digest approval process for sending over to the REXUS application.</description>
    <fields>
        <fullName>Accrual_Amount__c</fullName>
        <inlineHelpText>Amount obligated for expected cost.</inlineHelpText>
        <label>Accrual Amount</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Accrual_Type__c</fullName>
        <inlineHelpText>Identifies accrual cost category (CPI, Real Estate Taxes, BID Taxes, Facilities Rental/Other, Settlement)</inlineHelpText>
        <label>Accrual Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Full</fullName>
                </value>
                <value>
                    <fullName>Partial</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LeaseDigest__c</fullName>
        <label>Lease Digest</label>
        <referenceTo>Glxy_LeaseDigest__c</referenceTo>
        <relationshipLabel>Lease Accruals</relationshipLabel>
        <relationshipName>Lease_Accruals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PDN__c</fullName>
        <inlineHelpText>Pegasys Document Number</inlineHelpText>
        <label>PDN</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Lease Accrual</label>
    <nameField>
        <displayFormat>LA-{0000000}</displayFormat>
        <label>Lease Accrual ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lease Accruals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Glxy_LeaseDigest__c.object
<CustomObject>
    <description>Lease Digest object, child of Transaction object for galaxy</description>
    <fields>
        <fullName>Include_Accrual__c</fullName>
        <inlineHelpText>Indicator box that is selected when referencing an accrual associated with the digest action.</inlineHelpText>
        <label>Include Accrual</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>YES</fullName>
                </value>
                <value>
                    <fullName>NO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LeaseNumber__c</fullName>
        <label>Lease Number</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <label>Transaction</label>
        <referenceTo>Glxy_Transaction__c</referenceTo>
        <relationshipLabel>Lease Digests</relationshipLabel>
        <relationshipName>Lease_Digests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Lease Digest</label>
    <nameField>
        <label>Lease Digest ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lease Digests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Glxy_Transaction__c.object
<CustomObject>
    <customHelpPage>GLXY_HelpPage</customHelpPage>
    <description>This table contains monthly Galaxy summarized Data. This data will be loaded on monthly basis using SalesForce APEX code. Purpose of this data is to produce monthly reconciliation reports.</description>
    <fields>
        <fullName>BA53_User__c</fullName>
        <inlineHelpText>BA53 Analyst that the associated Lease is assigned to in REXUS</inlineHelpText>
        <label>BA53 User</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LeaseNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Lease object</description>
        <label>Lease Number</label>
        <referenceTo>Glxy_Lease__c</referenceTo>
        <relationshipLabel>Galaxy Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Galaxy Transaction</label>
    <nameField>
        <label>Transaction ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Galaxy Transactions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Glxy_AddAccruals.cls
public with sharing class Glxy_AddAccruals {
    
    Public List<Glxy_FMISVATObligation__c> PDNRecords {get;set;}
    Public List<Glxy_LeaseAccrual__c> UsedPDNRecords {get;set;}
    private final Glxy_LeaseAccrual__c ObjDigest;
    Public String strLeaseNumber {get; set;}
    Public String strRegion {get; set;}
    Public String strFMISLeaseNumber {get; set;}
     
    public Glxy_AddAccruals(ApexPages.StandardController controller) {
        ObjDigest = (Glxy_LeaseAccrual__c)controller.getRecord();
        strLeaseNumber = [Select Transaction__r.LeaseNumber__c From Glxy_LeaseDigest__c where ID = :ObjDigest.LeaseDigest__c Limit 1].Transaction__r.LeaseNumber__c;
        strRegion = [Select RegionCD__c From Glxy_Lease__c where ID = :strLeaseNumber].RegionCD__c;
        strLeaseNumber = [Select Name From Glxy_Lease__c where ID = :strLeaseNumber].Name;
        if (strRegion.length() == 1){strRegion = '0' + strRegion;}
        strFMISLeaseNumber = strRegion + 'B' + strLeaseNumber.Right(5); //Convert to FMIS Lease Number
    }
    
    Public Glxy_FMISVATObligation__c[] GetPDNForlease() {
    	String strType1 = 'LY%';
       	String strType2 = 'LR%';	
       	String strType3 = 'LU%';	
       	PDNRecords = Database.query('select ACTG_PERIOD__c, AMT__c, BUDGET_ACTVTY_CD__c, DESCRIPTION__c, FUNC_CD__c, Function_Name__c, FUND_CD__c, PEG_DOC_NUM__c, REGION_CD__c, SEQ_NO__c, TITLE__c, TT__c, DTYP__c from Glxy_FMISVATObligation__c Where LEASE_NO__c = :strFMISLeaseNumber And (PEG_DOC_NUM__c Like :strType1 OR PEG_DOC_NUM__c Like :strType2 OR PEG_DOC_NUM__c Like :strType3)');
       	Return PDNRecords;
    }
    
    Public Glxy_LeaseAccrual__c[] GetUsedPDNsForlease() {
      UsedPDNRecords = [select LeaseDigest__r.Transaction__r.Name, LeaseDigest__c, PDN__c, Accrual_Type__c, Accrual_Amount__c, CreatedDate, CreatedByID from Glxy_LeaseAccrual__c where LeaseDigest__r.Transaction__r.LeaseNumber__r.Name = :strLeaseNumber order by CreatedDate Desc] ;
      Return UsedPDNRecords;
    }

    @isTest(SeeAllData=false) Static void  TestGlxy_AddAccruals() {
			Glxy_Lease__c ObjLease = new Glxy_Lease__c();
	       	ObjLease.StatusCode__c='Active';
	       	Date myDate = date.newinstance(Datetime.Now().Date().Year(), 2, 17);
	       	Date myDate1 = date.newinstance(Datetime.Now().Date().addyears(+1).Year(), 2, 17);
	       	ObjLease.BaseLeaseEffectiveDate__c=myDate ;
	       	ObjLease.ExpirationDateofLease__c=myDate1 ;
	       	ObjLease.RegionCD__c = '1';
	       	ObjLease.Name = 'LVA0001';
	       	ObjLease.Total_NOA_Sq_feet__c=4444;
	       	ObjLease.Total_IA_Sq_feet__c=3333333;
	       	ObjLease.BaseAnnualRent__c = 1200;
	       	insert ObjLease;
			System.Assert(ObjLease!=NULL);
			
			Glxy_Transaction__c objTest2 = new Glxy_Transaction__c (
	            LeaseNumber__c = ObjLease.id,  
	            RecordTypeId = Schema.SObjectType.Glxy_Transaction__c.getRecordTypeInfosByName().get('Lease Action').getRecordTypeId(), 
	            BA53_User__c = 'test',
	            Region__c = '01'
	        );
	        insert objTest2;
        	System.Assert(objTest2!=NULL);
        	
	        Glxy_LeaseDigest__c objTest3 = new Glxy_LeaseDigest__c (
	        	Transaction__c = objTest2.ID,
	        	Include_Accrual__c = 'YES'
	        );
	        insert objTest3;
        	System.Assert(objTest3!=NULL);
        	
        	Glxy_LeaseDigest__c objTest4 = new Glxy_LeaseDigest__c (
	        	Transaction__c = objTest2.ID,
	        	Include_Accrual__c = 'YES'
	        );
	        insert objTest4;
        	System.Assert(objTest4!=NULL);
        	
         	List<Glxy_LeaseAccrual__c> objLeaseAccrualRecords = New List<Glxy_LeaseAccrual__c>();
        	 
	        Glxy_LeaseAccrual__c objTest31 = New Glxy_LeaseAccrual__c(
	        	LeaseDigest__c = objTest3.id,
	        	PDN__C = 'PDN'
	        );
	        objLeaseAccrualRecords.Add(objTest31);
	        
	         Glxy_LeaseAccrual__c objTest32 = New Glxy_LeaseAccrual__c(
	        	LeaseDigest__c = objTest3.id,
	        	PDN__C = 'PDN2'
	        );
	        objLeaseAccrualRecords.Add(objTest32);

	        Glxy_LeaseAccrual__c objTest41 = New Glxy_LeaseAccrual__c(
	        	LeaseDigest__c = objTest4.id,
	        	PDN__C = 'PDN'
	        );
	        objLeaseAccrualRecords.Add(objTest41);
	        
	        Insert objLeaseAccrualRecords;
	        
	        Glxy_FMISVATObligation__c objVat = New Glxy_FMISVATObligation__c(
	        	TITLE__c = 'LVA0001',
	        	LEASE_NO__c = '01B0001',
	        	PEG_DOC_NUM__c = 'LR1000',
	        	AMT__C = 100
	        );
	        
	        Insert objVat;
	        
	        ApexPages.StandardController con = new ApexPages.StandardController(objTest31);
	        Glxy_AddAccruals objTesta = new Glxy_AddAccruals(con);
	        objTesta.GetPDNForlease();
	        objTesta.GetUsedPDNsForlease();
		}
    
}