src/objects/Glxy_BudgetCallLineItem__c.object
<CustomObject>
    <fields>
        <fullName>AnnualAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Annual Amount</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Apr__c</fullName>
        <label>Apr</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Aug__c</fullName>
        <label>Aug</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BudgetCategory__c</fullName>
        <label>Budget Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Base Rent</fullName>
                </value>
                <value>
                    <fullName>Cancellation</fullName>
                </value>
                <value>
                    <fullName>Double Rent</fullName>
                </value>
                <value>
                    <fullName>Expansion</fullName>
                </value>
                <value>
                    <fullName>IBAA</fullName>
                </value>
                <value>
                    <fullName>Lump Sums</fullName>
                </value>
                <value>
                    <fullName>Operating Cost Escalation (CPI)</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Project Step Rent</fullName>
                </value>
                <value>
                    <fullName>Rent Increase</fullName>
                </value>
                <value>
                    <fullName>RWA</fullName>
                </value>
                <value>
                    <fullName>Step Rent</fullName>
                </value>
                <value>
                    <fullName>Total</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Taxes</fullName>
                </value>
                <value>
                    <fullName>Project Lump Sums</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CancellationAnnualRent__c</fullName>
        <label>Cancellation Annual Rent</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CancellationPartYearCost__c</fullName>
        <label>Cancellation Part Year Cost</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CancellationSqFt__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Cancellation Sq Ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DataGroup__c</fullName>
        <label>Data Group</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dec__c</fullName>
        <label>Dec</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>DelegatedLease__c</fullName>
        <label>Delegated Lease</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EscalationAnnualRent__c</fullName>
        <label>Escalation Annual Rent</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>EscalationPartYearCost__c</fullName>
        <label>Escalation Part Year Cost</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>EscalationSqFt__c</fullName>
        <label>Escalation Sq Ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ExpansionAnnualRent__c</fullName>
        <label>Expansion Annual Rent</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ExpansionPartYearCost__c</fullName>
        <label>Expansion Part Year Cost</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ExpansionSqFt__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Expansion Sq Ft</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Feb__c</fullName>
        <label>Feb</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FiscalYear__c</fullName>
        <label>Fiscal Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Jan__c</fullName>
        <label>Jan</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Jul__c</fullName>
        <label>Jul</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Jun__c</fullName>
        <label>Jun</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LeaseNumber__c</fullName>
        <label>Lease Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LeaseStatus__c</fullName>
        <label>Lease Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lease_Expiration_Date__c</fullName>
        <label>Lease Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Mar__c</fullName>
        <label>Mar</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>May__c</fullName>
        <label>May</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Nov__c</fullName>
        <label>Nov</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Oct__c</fullName>
        <label>Oct</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>RecordIdentifier__c</fullName>
        <description>Applicable to Budget Category of Totals only ...</description>
        <externalId>true</externalId>
        <label>Record Identifier</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RegionCode__c</fullName>
        <label>Region Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sep__c</fullName>
        <label>Sep</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SquareFeet__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Square Feet</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Actual</fullName>
                </value>
                <value>
                    <fullName>Estimate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TeamCode__c</fullName>
        <label>Team Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Budget Call Line Item</label>
    <nameField>
        <displayFormat>LI-{0000}</displayFormat>
        <label>Budget Call Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Call Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Glxy_BC_GenerateFYTotals.cls
global with sharing class Glxy_BC_GenerateFYTotals implements Database.Batchable<AggregateResult>,Database.stateful{	
	global List<Glxy_BudgetCallLineItem__c> objInsertRecords = New List<Glxy_BudgetCallLineItem__c>();
	AggregateResult objLeaseBudgetCallLineItem;
	Integer intCurrentFY;
	String 	strCurrentFY;
	String 	strCurrentFY2;
	
	global Iterable<AggregateResult> start(Database.batchableContext info){
	 	return new GLXY_BC_AggregateResultIterableTotals(); 
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope){
    	
    	objInsertRecords.Clear();
    	String strStatus, strLeaseNumber, strDelegatedLease;
    	Decimal dblBaseSqFt;
    	strCurrentFY = String.valueOf(Datetime.Now().Date().Month() > 9? Datetime.Now().Date().Year() + 1 : Datetime.Now().Date().Year());
    	
    	for(sObject obj: scope) {
    		objLeaseBudgetCallLineItem = (AggregateResult) obj;
    		strStatus = 'Estimate';
    		If (String.valueOf(objLeaseBudgetCallLineItem.get('FiscalYear__c')) == strCurrentFY) strStatus = 'Actual';
    		
    		strLeaseNumber = String.valueOf(objLeaseBudgetCallLineItem.get('LeaseNumber__c')); 
    		If(String.isEmpty(String.valueOf(objLeaseBudgetCallLineItem.get('LeaseNumber__c')))){
        		strLeaseNumber = 'Unassigned'; 
        	}
        	
        	strDelegatedLease = String.valueOf(objLeaseBudgetCallLineItem.get('DelegatedLease')); 
    		If(String.isEmpty(String.valueOf(objLeaseBudgetCallLineItem.get('DelegatedLease')))){
        		strDelegatedLease = 'False'; 
        	}
        	
        	//dblBaseSqFt = (Decimal) objLeaseBudgetCallLineItem.get('SquareFeet');
        	//If (String.valueOf(objLeaseBudgetCallLineItem.get('LeaseStatus')) != 'Active'){
        	//	dblBaseSqFt = 0.00;
        	//}

    		objInsertRecords.Add(new Glxy_BudgetCallLineItem__c(
    			LeaseNumber__c = String.valueOf(objLeaseBudgetCallLineItem.get('LeaseNumber__c')),
    			FiscalYear__c = String.valueOf(objLeaseBudgetCallLineItem.get('FiscalYear__c')),
    			DataGroup__c = String.valueOf(objLeaseBudgetCallLineItem.get('DataGroup__c')),
    			DelegatedLease__c = strDelegatedLease,
                RegionCode__c = String.valueOf(objLeaseBudgetCallLineItem.get('RegionCode')),
                TeamCode__c = String.valueOf(objLeaseBudgetCallLineItem.get('TeamCode')), 
                Lease_Expiration_Date__c = Date.valueOf(objLeaseBudgetCallLineItem.get('LeaseExpirationDate')),
                LeaseStatus__c = String.valueOf(objLeaseBudgetCallLineItem.get('LeaseStatus')), 
                BudgetCategory__c = 'Total',
                Status__c = strStatus,
                State__c = String.valueOf(objLeaseBudgetCallLineItem.get('LeaseNumber__c')).substring(1,3),
                RecordIdentifier__c = (String.valueOf(objLeaseBudgetCallLineItem.get('FiscalYear__c')) + strLeaseNumber + 'Total' + String.valueOf(objLeaseBudgetCallLineItem.get('DataGroup__c'))),
                AnnualAmount__c = (Decimal) objLeaseBudgetCallLineItem.get('AnnualAmount'),
                SquareFeet__c = (Decimal) objLeaseBudgetCallLineItem.get('SquareFeet'),
                Jan__c = 0, 
                Feb__c = 0,
                Mar__c = 0,
                Apr__c = 0,
                May__c = 0,
                Jun__c = 0,
                Jul__c = 0,
                Aug__c = 0,
                Sep__c = 0,
                Oct__c = 0, 
                Nov__c = 0,
                Dec__c = 0,
                CancellationAnnualRent__c = (Decimal) objLeaseBudgetCallLineItem.get('CancellationAnnualRent'),
                CancellationPartYearCost__c = (Decimal) objLeaseBudgetCallLineItem.get('CancellationPartYearCost'),
                CancellationSqFt__c = (Decimal) objLeaseBudgetCallLineItem.get('CancellationSqFt'),
                EscalationAnnualRent__c = (Decimal) objLeaseBudgetCallLineItem.get('EscalationAnnualRent'),
                EscalationPartYearCost__c = (Decimal) objLeaseBudgetCallLineItem.get('EscalationPartYearCost'),
                EscalationSqFt__c = (Decimal) objLeaseBudgetCallLineItem.get('EscalationSqFt'),
                ExpansionAnnualRent__c = (Decimal) objLeaseBudgetCallLineItem.get('ExpansionAnnualRent'),
                ExpansionPartYearCost__c = (Decimal) objLeaseBudgetCallLineItem.get('ExpansionPartYearCost'),
                ExpansionSqFt__c = (Decimal) objLeaseBudgetCallLineItem.get('ExpansionSqFt')
            )); 	
    	}
    	
        try{    
            Database.Insert(objInsertRecords, false);
        }catch (DmlException e){
            System.debug('Glxy_BC_GenerateFYTotals Insert error - ' + e.getMessage());
        }
    }
    
    global void finish(Database.BatchableContext BC){
    	//Invoke the next batch
    	database.executeBatch(new GLXY_BC_ComputeLeaseTotals());
    }
    
}