src/objects/GobiernoUSA_gov__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <fields>
        <fullName>GobiernoUSA_gov_Article_ID__c</fullName>
        <label>GobiernoUSA.gov Article ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>GobiernoUSA.gov</label>
    <pluralLabel>GoviernoUSA.gov</pluralLabel>
</CustomObject>

src/objects/KBSyncSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>API_Key__c</fullName>
        <label>API Key</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Create_Exception_Record__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Create Exception Record</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_Delta__c</fullName>
        <label>Date Shift</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Email_Exception__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Email Exception</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Page_Size__c</fullName>
        <label>Page Size</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>KBSyncSettings</label>
</CustomObject>

src/objects/USA_gov__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <fields>
        <fullName>USA_gov_Article_Id__c</fullName>
        <label>USA.gov Article Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>USA.gov</label>
    <pluralLabel>USA.gov</pluralLabel>
</CustomObject>

src/classes/GSA_FCIC_KDBArticles_ServiceTest.cls
@isTest
private class GSA_FCIC_KDBArticles_ServiceTest {

	static testMethod void testPublishService() {
	  
	  //KBSyncSettings__c settings = KBSyncSettings__c.getValues('SyncSettings');   
		KBSyncSettings__c kbSync = new KBSyncSettings__c(Name='SyncSettings', API_Key__c= '1234',Create_Exception_Record__c= true,  Date_Delta__c = 3,Email_Exception__c = true,Page_Size__c=3);
		insert kbSync ;
		system.assert(kbSync.API_Key__c == '1234');
		test.starttest();
		Test.setMock(HttpCalloutMock.class, new GSA_FCIC_KDBArticles_MockCallout(200,'Sucess',GSA_FCIC_KDBArticles_TestGenerator.getPublishedResponse(100),null));
		DateTime todayDate = DateTime.newInstance(System.Date.today(), System.Time.newInstance(0, 0, 0, 0));
		GSA_FCIC_KDBArticles_WSParser.narrativeResponse resp = GSA_FCIC_KDBArticles_Service.getNarritive(todayDate,1);
		system.debug('testPublishService resp');
		system.debug(resp);
		GSA_FCIC_KDBArticles_Service.processNarratives(resp);

		List<USA_gov__kav> returnedArticles = [SELECT KnowledgeArticleId, Id, Language, USA_gov_Article_Id__c from USA_gov__kav WHERE Language = 'en_US' and isLatestVersion = true and PublishStatus = 'Online' and USA_gov_Article_Id__c = '100'];
		system.assertEquals(returnedArticles.size(), 1);
		test.stoptest();
	}

	static testMethod void testUpdateService() {
	  
	  	//KBSyncSettings__c settings = KBSyncSettings__c.getValues('SyncSettings');   
		KBSyncSettings__c kbSync = new KBSyncSettings__c(Name='SyncSettings', API_Key__c= '1234',Create_Exception_Record__c= true,  Date_Delta__c = 3,Email_Exception__c = true,Page_Size__c=3);
		insert kbSync ;

		USA_gov__kav article = new USA_gov__kav();
		article.USA_gov_Article_Id__c = '100';
		article.urlName = '100';
		article.Title = 'Test Article';
		insert article;

		List<USA_gov__kav> insertedArticle = [SELECT KnowledgeArticleId, Id, Language, USA_gov_Article_Id__c from USA_gov__kav WHERE Id = :article.Id];

		system.assertEquals(insertedArticle.size(), 1);

		KbManagement.PublishingService.publishArticle(insertedArticle[0].KnowledgeArticleId, true);
		system.assert(kbSync.API_Key__c == '1234');
		test.starttest();
		Test.setMock(HttpCalloutMock.class, new GSA_FCIC_KDBArticles_MockCallout(200,'Sucess',GSA_FCIC_KDBArticles_TestGenerator.getPublishedResponse(100),null));
		DateTime todayDate = DateTime.newInstance(System.Date.today(), System.Time.newInstance(0, 0, 0, 0));
		GSA_FCIC_KDBArticles_WSParser.narrativeResponse resp = GSA_FCIC_KDBArticles_Service.getNarritive(todayDate,1);
		system.debug('testUpdateService resp');
		system.debug(resp);
		GSA_FCIC_KDBArticles_Service.processNarratives(resp);

		List<USA_gov__kav> returnedArticles = [SELECT KnowledgeArticleId, Id, Language, USA_gov_Article_Id__c from USA_gov__kav WHERE Language = 'en_US' and isLatestVersion = true and PublishStatus = 'Online' and USA_gov_Article_Id__c = '100'];
		system.assertEquals(returnedArticles.size(), 1);
		test.stoptest();
	}

	static testMethod void testUpdateServiceSPANISH(){

		//KBSyncSettings__c settings = KBSyncSettings__c.getValues('SyncSettings');   
		KBSyncSettings__c kbSync = new KBSyncSettings__c(Name='SyncSettings', API_Key__c= '1234',Create_Exception_Record__c= true,  Date_Delta__c = 3,Email_Exception__c = true,Page_Size__c=3);
		insert kbSync ;

		GobiernoUSA_gov__kav article = new GobiernoUSA_gov__kav();
		article.GobiernoUSA_gov_Article_ID__c = '100';
		article.urlName = '100';
		article.Title = 'Test Article';
		insert article;

		List<GobiernoUSA_gov__kav> insertedArticle = [SELECT KnowledgeArticleId, Id, Language, GobiernoUSA_gov_Article_ID__c from GobiernoUSA_gov__kav WHERE Id = :article.Id];

		system.assertEquals(insertedArticle.size(), 1);

		KbManagement.PublishingService.publishArticle(insertedArticle[0].KnowledgeArticleId, true);
		system.assert(kbSync.API_Key__c == '1234');
		test.starttest();
		Test.setMock(HttpCalloutMock.class, new GSA_FCIC_KDBArticles_MockCallout(200,'Sucess',GSA_FCIC_KDBArticles_TestGenerator.getPublishedResponseSPANISH(100),null));
		DateTime todayDate = DateTime.newInstance(System.Date.today(), System.Time.newInstance(0, 0, 0, 0));
		GSA_FCIC_KDBArticles_WSParser.narrativeResponse resp = GSA_FCIC_KDBArticles_Service.getNarritive(todayDate,1);
		system.debug('testUpdateService resp');
		system.debug(resp);
		GSA_FCIC_KDBArticles_Service.processNarratives(resp);

		List<GobiernoUSA_gov__kav> returnedArticles = [SELECT KnowledgeArticleId, Id, Language, GobiernoUSA_gov_Article_ID__c from GobiernoUSA_gov__kav WHERE Language = 'en_US' and isLatestVersion = true and PublishStatus = 'Online' and GobiernoUSA_gov_Article_ID__c = '100'];
		system.assertEquals(returnedArticles.size(), 1);
		test.stoptest();		
	}

	static testMethod void testArchiveService() {
	  
	  //KBSyncSettings__c settings = KBSyncSettings__c.getValues('SyncSettings');   
		KBSyncSettings__c kbSync = new KBSyncSettings__c(Name='SyncSettings', API_Key__c= '1234',Create_Exception_Record__c= true,  Date_Delta__c = 3,Email_Exception__c = true,Page_Size__c=3);
		insert kbSync ;

		USA_gov__kav article = new USA_gov__kav();
		article.USA_gov_Article_Id__c = '100';
		article.urlName = '100';
		article.Title = 'Test Article';
		insert article;

		List<USA_gov__kav> insertedArticle = [SELECT KnowledgeArticleId, Id, Language, USA_gov_Article_Id__c from USA_gov__kav WHERE Id = :article.Id];

		system.assertEquals(insertedArticle.size(), 1);

		KbManagement.PublishingService.publishArticle(insertedArticle[0].KnowledgeArticleId, true);
		system.assert(kbSync.API_Key__c == '1234');
		test.starttest();
		Test.setMock(HttpCalloutMock.class, new GSA_FCIC_KDBArticles_MockCallout(200,'Sucess',GSA_FCIC_KDBArticles_TestGenerator.getArchivedResponse(100),null));
		DateTime todayDate = DateTime.newInstance(System.Date.today(), System.Time.newInstance(0, 0, 0, 0));
		GSA_FCIC_KDBArticles_WSParser.narrativeResponse resp = GSA_FCIC_KDBArticles_Service.getNarritive(todayDate,1);
		system.debug('testArchiveService resp');
		system.debug(resp);
		GSA_FCIC_KDBArticles_Service.processNarratives(resp);
		List<USA_gov__kav> returnedArticles = [SELECT KnowledgeArticleId, Id, Language, USA_gov_Article_Id__c from USA_gov__kav WHERE Language = 'en_US' and isLatestVersion = true and PublishStatus = 'Online' and USA_gov_Article_Id__c = '100'];
		system.assertEquals(returnedArticles.size(), 0);

		test.stoptest();
	}

}