src/objects/GPM_Project__c.object
<CustomObject>
    <description>This is the primary object in the Project Central app; it is used to capture information about GSA projects.  The current build primarily supports app development as well as the needs of the PMO office.</description>
    <fields>
        <fullName>Actual_End_Date__c</fullName>
        <inlineHelpText>Use this field upon project completion to input the date that the project actually ends.</inlineHelpText>
        <label>Actual End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Key_Project__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Determines whether or not a project is one of the Key Projects</inlineHelpText>
        <label>Key Project</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project_Status__c</fullName>
        <inlineHelpText>Use this field to identify the current status of the project. The project status should be updated as project situations change.</inlineHelpText>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>On-Going</fullName>
                </value>
                <value>
                    <fullName>Delayed</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>On-Hold</fullName>
                </value>
                <value>
                    <fullName>Formative</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Use this field to identify the current phase of the project. The project phase should be updated as the project progresses through the project life cycle.</inlineHelpText>
        <label>Project Phase</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Concept Approval</fullName>
                </value>
                <value>
                    <fullName>Initiating</fullName>
                </value>
                <value>
                    <fullName>Planning</fullName>
                </value>
                <value>
                    <fullName>Executing</fullName>
                </value>
                <value>
                    <fullName>Design</fullName>
                </value>
                <value>
                    <fullName>Development</fullName>
                </value>
                <value>
                    <fullName>Testing</fullName>
                </value>
                <value>
                    <fullName>Deployment</fullName>
                </value>
                <value>
                    <fullName>Construction Procurement</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Close-Out</fullName>
                </value>
                <value>
                    <fullName>Close-Out/Closed</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UpcomingActionItems__c</fullName>
        <description>Upcoming Project Action Items</description>
        <inlineHelpText>The &quot;Latest Project Updates&quot; section read-only
 and only allow users to update those fields from the &quot;New Pulse&quot; quick action button or &apos;New Pulse&quot; from related list.</inlineHelpText>
        <label>Upcoming Action Items</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>P360_CorporateITServices</fullName>
        <active>true</active>
        <description>P360 - Use this record type for creating projects that support &apos;Corporate IT Services&apos;</description>
        <label>Corporate IT Services</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/P360_Request__c.object
<CustomObject>
    <description>Project 360 - This custom object stores all request records for Project 360 application</description>
    <fields>
        <fullName>IsConverted__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Indicates whether or not this request is converted into a project</inlineHelpText>
        <label>Converted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Current status of the request</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New Request</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Scoping</fullName>
                </value>
                <value>
                    <fullName>Analysis</fullName>
                </value>
                <value>
                    <fullName>Solution/LOE Complete</fullName>
                </value>
                <value>
                    <fullName>Awaiting BRG Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UpcomingActionItems__c</fullName>
        <description>Pulse Upcoming Action Items</description>
        <inlineHelpText>Upcoming Action Items from the latest pulse</inlineHelpText>
        <label>Upcoming Action Items</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <label>Request</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/P360_ControllerTest.cls
@isTest
public class P360_ControllerTest {

    static testMethod void testActionMap() {
        P360_Controller con = new P360_Controller();
        Map<String,String> m = P360_Controller.ProjActionMap;
        for (String s : P360_Controller.ProjIDList) {
            System.assert(m.get(s) != null, s + ' was not inserted.');
        }
    }


    static testMethod void testGetActionCount() {
        P360_Controller con = new P360_Controller();
        String TestactionMapJSON = con.actionMapJSON;
        String TestProjIDListJSON = con.ProjIDListJSON;
        String TestRequestactionMapJSON = con.RequestactionMapJSON;
        String TestRequestIDListJSON = con.RequestIDListJSON;
        Integer oneLine = P360_Controller.getActionCount('asdf');
        Integer nullInput = P360_Controller.getActionCount(null);
        Integer threeLines = P360_Controller.getActionCount('asdf<br>asdf<br>asdf');

        System.assert(oneLine == 1, 'Given string with no breaks, did not parse to 1 row.');
        System.assert(nullInput == 0, 'Given null string, did not parse to 0 rows.');
        System.assert(threeLines == 3, 'Given string with two breaks, did not parse to 2 rows.');
    }


    @testSetup
    static void setup() {
         Id strRecordTypeId = [Select Id From RecordType Where SobjectType = 'GPM_Project__c' and DeveloperName = 'P360_CorporateITServices'].Id;

         List<GPM_Project__c> proj = new List<GPM_Project__c>{new GPM_Project__c(Name='I1', Project_Status__c=null, Key_Project__c=True,RecordTypeId=strRecordTypeId,UpcomingActionItems__c='Hello'),
                                                            new GPM_Project__c(Name='I2', Project_Status__c=null,  Key_Project__c=True,RecordTypeId=strRecordTypeId),
                                                            new GPM_Project__c(Name='I3', Project_Status__c=null,  Key_Project__c=True,RecordTypeId=strRecordTypeId),
                                                            new GPM_Project__c(Name='nonKeyProject'),
                                                            new GPM_Project__c(Name='completedProject',Actual_End_Date__c= System.today()+100, Project_Status__c='Completed',RecordTypeId=strRecordTypeId)};
        insert proj;
        System.assert(proj.size()==5,'5 new projects created');
        system.debug('**+id'+proj);
        
         List<P360_Request__c> Request = new List<P360_Request__c>{new P360_Request__c(Name='RequestProj',IsConverted__c= False, Status__c='New Request')};
        insert Request;
        System.assert(Request.size()==1,'1 new projects created');
    }

     

}