src/objects/GPM_Project__c.object
<CustomObject>
    <description>This is the primary object in the Project Central app; it is used to capture information about GSA projects.  The current build primarily supports app development as well as the needs of the PMO office.</description>
    <fields>
        <fullName>Accomplishments__c</fullName>
        <description>Project Accomplishments</description>
        <inlineHelpText>The &quot;Latest Project Updates&quot; section read-only
 and only allow users to update those fields from the &quot;New Pulse&quot; quick action button or &apos;New Pulse&quot; from related list.</inlineHelpText>
        <label>Accomplishments</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Actual_End_Date__c</fullName>
        <inlineHelpText>Use this field upon project completion to input the date that the project actually ends.</inlineHelpText>
        <label>Actual End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Days_Since_Closed__c</fullName>
        <formula>Today()-Actual_End_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Days Since Closed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Issues__c</fullName>
        <description>Project Issues</description>
        <inlineHelpText>The &quot;Latest Project Updates&quot; section read-only
 and only allow users to update those fields from the &quot;New Pulse&quot; quick action button or &apos;New Pulse&quot; from related list.</inlineHelpText>
        <label>Issues</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Key_Project__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Determines whether or not a project is one of the Key Projects</inlineHelpText>
        <label>Key Project</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Planned_End_Date__c</fullName>
        <inlineHelpText>Use this field to indicate the date that you anticipate the project to end.  This date should serve as a baseline and remain unchanged once entered.</inlineHelpText>
        <label>Planned End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Use this field to select the person responsible for management of the project.</inlineHelpText>
        <label>Project Manager</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Projects (Project Manager)</relationshipLabel>
        <relationshipName>Projects1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Status__c</fullName>
        <inlineHelpText>Use this field to identify the current status of the project. The project status should be updated as project situations change.</inlineHelpText>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>On-Going</fullName>
                </value>
                <value>
                    <fullName>Delayed</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>On-Hold</fullName>
                </value>
                <value>
                    <fullName>Formative</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StatusUpdateOrComments__c</fullName>
        <inlineHelpText>The &quot;Latest Project Updates&quot; section read-only
 and only allow users to update those fields from the &quot;New Pulse&quot; quick action button or &apos;New Pulse&quot; from related list.</inlineHelpText>
        <label>Status Update/Comments</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Use this field to identify the current phase of the project. The project phase should be updated as the project progresses through the project life cycle.</inlineHelpText>
        <label>Project Phase</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Concept Approval</fullName>
                </value>
                <value>
                    <fullName>Initiating</fullName>
                </value>
                <value>
                    <fullName>Planning</fullName>
                </value>
                <value>
                    <fullName>Executing</fullName>
                </value>
                <value>
                    <fullName>Design</fullName>
                </value>
                <value>
                    <fullName>Development</fullName>
                </value>
                <value>
                    <fullName>Testing</fullName>
                </value>
                <value>
                    <fullName>Deployment</fullName>
                </value>
                <value>
                    <fullName>Construction Procurement</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Close-Out</fullName>
                </value>
                <value>
                    <fullName>Close-Out/Closed</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UpcomingActionItems__c</fullName>
        <description>Upcoming Project Action Items</description>
        <inlineHelpText>The &quot;Latest Project Updates&quot; section read-only
 and only allow users to update those fields from the &quot;New Pulse&quot; quick action button or &apos;New Pulse&quot; from related list.</inlineHelpText>
        <label>Upcoming Action Items</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>P360_CorporateITServices</fullName>
        <active>true</active>
        <description>P360 - Use this record type for creating projects that support &apos;Corporate IT Services&apos;</description>
        <label>Corporate IT Services</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/P360_Request__c.object
<CustomObject>
    <description>Project 360 - This custom object stores all request records for Project 360 application</description>
    <fields>
        <fullName>Accomplishments__c</fullName>
        <description>Pulse Accomplishments</description>
        <inlineHelpText>Accomplishments from the latest pulse</inlineHelpText>
        <label>Accomplishments</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Costs__c</fullName>
        <description>Provided by the Triage team after evaluation of the request</description>
        <inlineHelpText>Provided by the Triage team after evaluation of the request</inlineHelpText>
        <label>Costs</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>EstimatedCosts__c</fullName>
        <description>Is yes, to the previous question (Current Cost Information), provide the estimated costs.</description>
        <inlineHelpText>Is yes, to the previous question (Current Cost Information), provide the estimated costs.</inlineHelpText>
        <label>Estimated Costs</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>InputChannel__c</fullName>
        <inlineHelpText>Source of this request</inlineHelpText>
        <label>Input Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Web</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Data Load</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IsConverted__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Indicates whether or not this request is converted into a project</inlineHelpText>
        <label>Converted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Issues__c</fullName>
        <description>Pulse Issues</description>
        <inlineHelpText>Issues from the latest pulse</inlineHelpText>
        <label>Issues</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>LevelOfEffort__c</fullName>
        <description>What is the level of effort for this request?</description>
        <inlineHelpText>Please describe the level of effort to complete this request as either High, Medium, or Low</inlineHelpText>
        <label>Level of Effort</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RequestType__c</fullName>
        <description>This field is being used in email template and is hidden from all users from page layouts, profiles, and reports.</description>
        <formula>IF ( CONTAINS(RecordType.Name, &apos;New Application&apos;), &apos;New Application&apos; , 
     (IF ( CONTAINS(RecordType.Name, &apos;Enhancement&apos;), &apos;Enhancement&apos;, &apos;Request&apos;)))</formula>
        <label>Request Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RequestorName__c</fullName>
        <description>Requestor Name</description>
        <inlineHelpText>Requestor Full Name (i.e. Elizabeth Sanders)</inlineHelpText>
        <label>Requestor Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StatusUpdateOrComments__c</fullName>
        <description>Pulse Status Update/Comments</description>
        <inlineHelpText>Status Update/Comments from the latest pulse</inlineHelpText>
        <label>Status Update/Comments</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Current status of the request</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New Request</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Scoping</fullName>
                </value>
                <value>
                    <fullName>Analysis</fullName>
                </value>
                <value>
                    <fullName>Solution/LOE Complete</fullName>
                </value>
                <value>
                    <fullName>Awaiting BRG Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Enhancement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UpcomingActionItems__c</fullName>
        <description>Pulse Upcoming Action Items</description>
        <inlineHelpText>Upcoming Action Items from the latest pulse</inlineHelpText>
        <label>Upcoming Action Items</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <label>Request</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/P360_Controller.cls
public with sharing class  P360_Controller { 
   
    public List<GPM_Project__c> ProjLst{get;set;}
    public List<GPM_Project__c> keyProj{get;set;}
    public List<GPM_Project__c> compltdProj{get;set;}
    public List<P360_Request__c> RqstLst{get;set;}
    public static Map<String, String> ProjActionMap{get; set;}
    public static Map<String, String> RequestActionMap{get; set;}
    public static List<String> ProjIDList{get; set;}
    public static List<String> RequestIDList{get; set;}
    public String actionMapJSON {get{return JSON.serialize(ProjActionMap);}}
    public String ProjIDListJSON {get{return JSON.serialize(ProjIDList);}}
    public String RequestactionMapJSON {get{return JSON.serialize(RequestActionMap);}}
    public String RequestIDListJSON {get{return JSON.serialize(RequestIDList);}}

   
    Id strRecordTypeId = [Select Id From RecordType Where SobjectType = 'GPM_Project__c' and DeveloperName = 'P360_CorporateITServices'].Id;
    public P360_Controller(){
      
        ProjActionMap = new Map<String, String>();
        ProjIDList = new List<String>();
        RequestActionMap = new Map<String, String>();
        RequestIDList = new List<String>();
       

        ProjLst = [
            SELECT
                ID
                ,Name
                ,Status__c 
                ,Project_Status__c  
                ,UpcomingActionItems__c
                ,Issues__c
                ,StatusUpdateOrComments__c
                ,Accomplishments__c
                ,OwnerId
                ,Owner.Name
                ,Actual_End_Date__c
            	,Project_Manager__r.Name
            	,Planned_End_Date__c 
            FROM GPM_Project__c
            WHERE Project_Status__c!='Completed' 
            AND Project_Status__c!='Cancelled'
            AND RecordTypeID=:strRecordTypeId                  
           
        ];  

        compltdProj = [
            SELECT
                ID
                ,Name
                ,Status__c 
                ,Project_Status__c
                ,UpcomingActionItems__c
                ,Issues__c
                ,StatusUpdateOrComments__c             
                ,Accomplishments__c
                ,OwnerId
                ,Owner.Name
                ,Actual_End_Date__c
                ,Project_Manager__r.Name
            	,Planned_End_Date__c 
            FROM GPM_Project__c
            WHERE Project_Status__c='Completed'
            AND Days_Since_Closed__c < 365
            AND RecordTypeID=:strRecordTypeId
            
        ];

        keyProj = [
            SELECT
                ID
                ,Name
                ,Status__c 
                ,Project_Status__c
                ,UpcomingActionItems__c
                ,Issues__c
                ,StatusUpdateOrComments__c                 
                ,Accomplishments__c
                ,Key_Project__c                
                ,OwnerId
                ,Owner.Name
                ,Actual_End_Date__c
				,Project_Manager__r.Name
				,Planned_End_Date__c            
            FROM GPM_Project__c
            Where Key_Project__c = True
            AND RecordTypeID=:strRecordTypeId
            AND Project_Status__c!='Cancelled'
            ORDER BY LastModifiedDate desc
            LIMIT 3
        ];

        RqstLst = [
            SELECT
                ID
                ,Name
                ,Status__c               
                ,OwnerId                
                ,Owner.Name 
                ,IsConverted__c
                ,LevelOfEffort__c
                ,RequestType__c  
                ,InputChannel__c                 
                ,RecordTypeID 
                ,StatusUpdateOrComments__c 
                ,UpcomingActionItems__c            
                ,Accomplishments__c
                ,Type__c               
                ,Costs__c
                ,EstimatedCosts__c
            	,RequestorName__c
            FROM P360_Request__c
            Where IsConverted__c= False
            AND   Status__c != 'Cancelled'                           
            ORDER BY LastModifiedDate desc
        ];

        setActionCountMap(ProjLst);
        setRequestActionCountMap(RqstLst);
    }

    public static void setActionCountMap(List<GPM_Project__c> proj) {
        for (GPM_Project__c i : proj) {
            ProjActionMap.put(i.id, String.valueOf(getActionCount(i.UpcomingActionItems__c)));
            ProjIDList.add(i.id);
        }
    }

    public static void setRequestActionCountMap(List<P360_Request__c> Req) {
        for (P360_Request__c j : Req) {
            RequestActionMap.put(j.id, String.valueOf(getActionCount(j.UpcomingActionItems__c)));
            RequestIDList.add(j.id);
        }
    }

    public static Integer getActionCount(String txt) {
    return (txt == null || txt.length() == 0) ? 0 : (txt.countMatches('<br>') + 1);
    }


}