src/objects/GPM_Milestone__c.object
<CustomObject>
    <description>This object is used to support the Project object; it allows users to capture unique project milestones.</description>
    <fields>
        <fullName>GPM_Project__c</fullName>
        <label>Project</label>
        <referenceTo>GPM_Project__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Milestones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Milestone_Progress__c</fullName>
        <inlineHelpText>Describes the progress status of the Milestone.</inlineHelpText>
        <label>Milestone Progress</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Delayed</fullName>
                </value>
                <value>
                    <fullName>On-Hold</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMO_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PMO Lead</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Milestones (PMO Lead)</relationshipLabel>
        <relationshipName>PMOLead</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Manager</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Milestones (Project Manager)</relationshipLabel>
        <relationshipName>ProjectManager</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Milestone</label>
    <nameField>
        <displayFormat>MIL-{0000000}</displayFormat>
        <label>Milestone</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/GPM_Project__c.object
<CustomObject>
    <description>This is the primary object in the Project Central app; it is used to capture information about GSA projects.  The current build primarily supports app development as well as the needs of the PMO office.</description>
    <fields>
        <fullName>OCIO_Strategic_Initiative__c</fullName>
        <inlineHelpText>Use this field to select any addition key principles or strategic initiatives defined by your Service/Staff Office for this project.</inlineHelpText>
        <label>Key Principles / Initiatives</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Service_Staff_Office__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Anytime, Anywhere, Any Device</fullName>
                </value>
                <value>
                    <fullName>Customer Service</fullName>
                </value>
                <value>
                    <fullName>Below the Line</fullName>
                </value>
                <value>
                    <fullName>Back Office Modernization (BOM)</fullName>
                </value>
                <value>
                    <fullName>Information Management</fullName>
                </value>
                <value>
                    <fullName>Security</fullName>
                </value>
                <value>
                    <fullName>Mandate</fullName>
                </value>
                <value>
                    <fullName>Enterprise Transformation</fullName>
                </value>
                <value>
                    <fullName>Smart Building</fullName>
                </value>
                <value>
                    <fullName>FAS - Commodity Buy</fullName>
                </value>
                <value>
                    <fullName>FAS - FSSI</fullName>
                </value>
                <value>
                    <fullName>FAS - Modernize Acquisition Processes</fullName>
                </value>
                <value>
                    <fullName>FAS - Modernizing Schedules</fullName>
                </value>
                <value>
                    <fullName>FAS - OASIS</fullName>
                </value>
                <value>
                    <fullName>FAS - Supply Chain Modernization</fullName>
                </value>
                <value>
                    <fullName>FAS - Workplace Modernization</fullName>
                </value>
                <value>
                    <fullName>OCPO - 1800 F milestones are met</fullName>
                </value>
                <value>
                    <fullName>OCPO - Govt’s best at performance mgmt</fullName>
                </value>
                <value>
                    <fullName>OCPO - Learning org ready for future</fullName>
                </value>
                <value>
                    <fullName>OCPO - Workers enjoy new OTJ experiences</fullName>
                </value>
                <value>
                    <fullName>OCPO - LR helps deliver new workplace</fullName>
                </value>
                <value>
                    <fullName>OCPO - GSA turns to CPO 1st for HR needs</fullName>
                </value>
                <value>
                    <fullName>OCPO - An engaged workforce</fullName>
                </value>
                <value>
                    <fullName>OCPO - Customer Focused Service</fullName>
                </value>
                <value>
                    <fullName>SSO Shared Service Team Engagement</fullName>
                </value>
                <value>
                    <fullName>Cloud First</fullName>
                </value>
                <value>
                    <fullName>Open Source Software (OSS)</fullName>
                </value>
                <value>
                    <fullName>Enterprise Info &amp; Data Mgt Team (EIDM)</fullName>
                </value>
                <value>
                    <fullName>Digital Services</fullName>
                </value>
                <value>
                    <fullName>Records Management</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMO_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Use this field to select the PMO representative for the project.</inlineHelpText>
        <label>PMO Lead</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Projects (PMO Lead)</relationshipLabel>
        <relationshipName>PMO_Lead_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Description__c</fullName>
        <inlineHelpText>Use this field to provide a description of the purpose of the project.</inlineHelpText>
        <label>Project Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Use this field to select the person responsible for management of the project.</inlineHelpText>
        <label>Project Manager</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Projects (Project Manager)</relationshipLabel>
        <relationshipName>Projects1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Tier__c</fullName>
        <inlineHelpText>Project Tier is used to track projects for the Office of GSA IT.  This option is only available for the GSA IT Service / Staff Office.</inlineHelpText>
        <label>Project Tier</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Service_Staff_Office__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Tier 1</fullName>
                </value>
                <value>
                    <fullName>Tier 2</fullName>
                </value>
                <value>
                    <fullName>Tier 3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SSO_Goals_Themes__c</fullName>
        <inlineHelpText>Use this field to select goals or strategic themes defined by your Service/Staff Office for this project.</inlineHelpText>
        <label>SSO Goals / Themes</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Service_Staff_Office__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>FAS - Acquisition Excellence</fullName>
                </value>
                <value>
                    <fullName>FAS - Customer Focused Offerings</fullName>
                </value>
                <value>
                    <fullName>FAS - Environmental Sustainability</fullName>
                </value>
                <value>
                    <fullName>FAS - Workforce Excellence</fullName>
                </value>
                <value>
                    <fullName>OGP - Innovation</fullName>
                </value>
                <value>
                    <fullName>OGP - Operational Excellence</fullName>
                </value>
                <value>
                    <fullName>OGP - Customer Intimacy</fullName>
                </value>
                <value>
                    <fullName>OCIO - App Portfolio Modernization</fullName>
                </value>
                <value>
                    <fullName>OCIO - Business Capability Consulting</fullName>
                </value>
                <value>
                    <fullName>OCIO - Compliance Driven Bus. Activities</fullName>
                </value>
                <value>
                    <fullName>OCIO - Consolidate and Broaden Services</fullName>
                </value>
                <value>
                    <fullName>OCIO - Effective Bus. Line Partnership</fullName>
                </value>
                <value>
                    <fullName>OCIO - IT Service Delivery Excellence</fullName>
                </value>
                <value>
                    <fullName>OCIO - IT Service Support Excellence</fullName>
                </value>
                <value>
                    <fullName>OCIO - IT Workforce Transformation</fullName>
                </value>
                <value>
                    <fullName>OCIO - Optimized IT Portfolio</fullName>
                </value>
                <value>
                    <fullName>OCIO - Secure Access</fullName>
                </value>
                <value>
                    <fullName>OCIO - Standardized Infrastructure Env</fullName>
                </value>
                <value>
                    <fullName>OCIO - Unified Vendor Management</fullName>
                </value>
                <value>
                    <fullName>OCPO - 1800 F Milestone Met</fullName>
                </value>
                <value>
                    <fullName>OCPO - Positive Performance</fullName>
                </value>
                <value>
                    <fullName>OCPO - Learning Organization Model</fullName>
                </value>
                <value>
                    <fullName>OCPO - Employees Embrace</fullName>
                </value>
                <value>
                    <fullName>OCPO - Labor Relations</fullName>
                </value>
                <value>
                    <fullName>OCPO - CPO First for Their HR Needs</fullName>
                </value>
                <value>
                    <fullName>Viewed as experts in our roles</fullName>
                </value>
                <value>
                    <fullName>Provide superior &amp; timely comms support</fullName>
                </value>
                <value>
                    <fullName>Enhance/Strengthen Technology</fullName>
                </value>
                <value>
                    <fullName>Create streamlined, consistent processes</fullName>
                </value>
                <value>
                    <fullName>Improve internal collaboration &amp; comms</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ProjectHelper.cls
/*-------------------------------------------------------------------------------------------------*
  Apex helper class for GPM_Project__c object trigger
 *-------------------------------------------------------------------------------------------------*
  Author           | Date        | Version | Description
 *-------------------------------------------------------------------------------------------------*
  Rajakumar          02/17/2015    1.0       Initial version.
  Rajakumar          03/18/2015    1.1       Commented code- remove the executive summary section
 *-------------------------------------------------------------------------------------------------*
 
 *-------------------------------------------------------------------------------------------------*/

public class ProjectHelper {
    // on after insert - for updating the PMO Lead and Project Managers in milestone records
    /*
    public static void onAfterInsert(List<GPM_Project__c> triggerNew, Map<Id, GPM_Project__c> triggerNewMap) {
        Set<Id> projIds = new Set<Id>();
        List<GPM_Milestone__c> milestones = new List<GPM_Milestone__c>();
        
        for(GPM_Project__c pr: triggerNew) {
            if(pr.Project_Tier__c == 'Tier 1' && (pr.Project_Manager__c != null || pr.PMO_Lead__c != null)) {
                projIds.add(pr.Id);
            }
        }
        milestones = [SELECT Id, Project_Manager__c, PMO_Lead__c, GPM_Project__c, Milestone_Progress__c FROM GPM_Milestone__c
                                    WHERE GPM_Project__c IN :projIds AND Milestone_Progress__c != 'Completed'];
        for(GPM_Milestone__c gm: milestones) {
            gm.Project_Manager__c = triggerNewMap.get(gm.GPM_Project__c).Project_Manager__c;
            gm.PMO_Lead__c = triggerNewMap.get(gm.GPM_Project__c).PMO_Lead__c;
        }
        try {
            if(!milestones.isEmpty()) {
                 update milestones;
            } 
        }
        catch(DMLException e) {
            System.debug(LoggingLevel.ERROR,'Error while updating the milestone records with Project Manager and PMO Lead :' +e.getMessage());    
        }         
        
    }
    */
    // on after update - for updating the PMO Lead and Project Managers in respective milestone records
    public static void onAfterUpdate(List<GPM_Project__c> triggerNew, Map<Id, GPM_Project__c> triggerOldMap, 
                                        Map<Id, GPM_Project__c> triggerNewMap) {
        Set<Id> projIds = new Set<Id>();
        List<GPM_Milestone__c> milestones = new List<GPM_Milestone__c>();
        
        for(GPM_Project__c pr: triggerNew) {
            if(pr.Project_Tier__c == 'Tier 1' && 
                ((pr.Project_Manager__c != null && pr.Project_Manager__c != triggerOldMap.get(pr.Id).Project_Manager__c) || 
                 (pr.PMO_Lead__c != null && pr.PMO_Lead__c != triggerOldMap.get(pr.Id).PMO_Lead__c)) ) {
                projIds.add(pr.Id);
            }
            if(pr.Project_Tier__c == 'Tier 1' && 
                ((pr.Project_Manager__c == null && pr.Project_Manager__c != triggerOldMap.get(pr.Id).Project_Manager__c) || 
                 (pr.PMO_Lead__c == null && pr.PMO_Lead__c != triggerOldMap.get(pr.Id).PMO_Lead__c)) ) {
                projIds.add(pr.Id);
            }            
        }
        milestones = [SELECT Id, Project_Manager__c, PMO_Lead__c, GPM_Project__c, Milestone_Progress__c FROM GPM_Milestone__c 
                                    WHERE GPM_Project__c IN :projIds AND Milestone_Progress__c != 'Completed'];
        for(GPM_Milestone__c gm: milestones) {
            gm.Project_Manager__c = triggerNewMap.get(gm.GPM_Project__c).Project_Manager__c;
            gm.PMO_Lead__c = triggerNewMap.get(gm.GPM_Project__c).PMO_Lead__c;
        }
        try {
            if(!milestones.isEmpty()) {
                 update milestones;
            } 
        }
        catch(DMLException e) {
            System.debug(LoggingLevel.ERROR,'Error while updating the milestone records with Project Manager and PMO Lead :' +e.getMessage());    
        }
    }  
    /* 1.1 commented - begin
    // before insert - for updating the few multi-select picklist values & objective richtextarea field 
    //                 on the executive section of the project layout 
    public static void onBeforeInsert(List<GPM_Project__c> triggerNew) {
        for(GPM_Project__c pr: triggerNew) {
            if(pr.SSO_Goals_Themes__c != null) {
                pr.SSO_Goals_Themes_formula__c = pr.SSO_Goals_Themes__c;
            }
            if(pr.Project_Description__c != null) {
                pr.Project_Objective_formula__c = pr.Project_Description__c;
            }
            if(pr.OCIO_Strategic_Initiative__c != null) {
                pr.Key_Principles_Initiatives_formula__c = pr.OCIO_Strategic_Initiative__c;
            }
        }
    }
    
    // before update - for updating the few multi-select picklist values & objective richtextarea field 
    //                 on the executive section of the project layout 
    public static void onBeforeUpdate(List<GPM_Project__c> triggerNew, Map<Id, GPM_Project__c> triggerOldMap) {
        for(GPM_Project__c pr: triggerNew) {
            if(pr.SSO_Goals_Themes__c != null && pr.SSO_Goals_Themes__c != triggerOldMap.get(pr.Id).SSO_Goals_Themes__c) {
                pr.SSO_Goals_Themes_formula__c = pr.SSO_Goals_Themes__c;
            }
            if(pr.Project_Description__c != null && pr.Project_Description__c != triggerOldMap.get(pr.Id).Project_Description__c) {
                pr.Project_Objective_formula__c = pr.Project_Description__c;
            }
            if(pr.OCIO_Strategic_Initiative__c != null && pr.OCIO_Strategic_Initiative__c != triggerOldMap.get(pr.Id).OCIO_Strategic_Initiative__c) {
                pr.Key_Principles_Initiatives_formula__c = pr.OCIO_Strategic_Initiative__c;
            }
            if(pr.SSO_Goals_Themes__c == null && triggerOldMap.get(pr.Id).SSO_Goals_Themes__c != null) {
                pr.SSO_Goals_Themes_formula__c = null;
            }
            if(pr.Project_Description__c == null && triggerOldMap.get(pr.Id).Project_Description__c != null) {
                pr.Project_Objective_formula__c = null;
            }
            if(pr.OCIO_Strategic_Initiative__c == null && triggerOldMap.get(pr.Id).OCIO_Strategic_Initiative__c != null) {
                pr.Key_Principles_Initiatives_formula__c = null;
            }    
        }
    } 
    1.1 commented - end */                                 
}