src/objects/GPM_Milestone__c.object
<CustomObject>
    <description>This object is used to support the Project object; it allows users to capture unique project milestones.</description>
    <fields>
        <fullName>GPM_Project__c</fullName>
        <label>Project</label>
        <referenceTo>GPM_Project__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Milestones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Manager</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Milestones (Project Manager)</relationshipLabel>
        <relationshipName>ProjectManager</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Milestone</label>
    <nameField>
        <displayFormat>MIL-{0000000}</displayFormat>
        <label>Milestone</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/GPM_Project__c.object
<CustomObject>
    <description>This is the primary object in the Project Central app; it is used to capture information about GSA projects.  The current build primarily supports app development as well as the needs of the PMO office.</description>
    <fields>
        <fullName>OCIO_Strategic_Initiative__c</fullName>
        <inlineHelpText>Use this field to select any addition key principles or strategic initiatives defined by your Service/Staff Office for this project.</inlineHelpText>
        <label>Key Principles / Initiatives</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Service_Staff_Office__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Anytime, Anywhere, Any Device</fullName>
                </value>
                <value>
                    <fullName>Customer Service</fullName>
                </value>
                <value>
                    <fullName>Below the Line</fullName>
                </value>
                <value>
                    <fullName>Back Office Modernization (BOM)</fullName>
                </value>
                <value>
                    <fullName>Information Management</fullName>
                </value>
                <value>
                    <fullName>Security</fullName>
                </value>
                <value>
                    <fullName>Mandate</fullName>
                </value>
                <value>
                    <fullName>Enterprise Transformation</fullName>
                </value>
                <value>
                    <fullName>Smart Building</fullName>
                </value>
                <value>
                    <fullName>FAS - Commodity Buy</fullName>
                </value>
                <value>
                    <fullName>FAS - FSSI</fullName>
                </value>
                <value>
                    <fullName>FAS - Modernize Acquisition Processes</fullName>
                </value>
                <value>
                    <fullName>FAS - Modernizing Schedules</fullName>
                </value>
                <value>
                    <fullName>FAS - OASIS</fullName>
                </value>
                <value>
                    <fullName>FAS - Supply Chain Modernization</fullName>
                </value>
                <value>
                    <fullName>FAS - Workplace Modernization</fullName>
                </value>
                <value>
                    <fullName>OCPO - 1800 F milestones are met</fullName>
                </value>
                <value>
                    <fullName>OCPO - Govt’s best at performance mgmt</fullName>
                </value>
                <value>
                    <fullName>OCPO - Learning org ready for future</fullName>
                </value>
                <value>
                    <fullName>OCPO - Workers enjoy new OTJ experiences</fullName>
                </value>
                <value>
                    <fullName>OCPO - LR helps deliver new workplace</fullName>
                </value>
                <value>
                    <fullName>OCPO - GSA turns to CPO 1st for HR needs</fullName>
                </value>
                <value>
                    <fullName>OCPO - An engaged workforce</fullName>
                </value>
                <value>
                    <fullName>OCPO - Customer Focused Service</fullName>
                </value>
                <value>
                    <fullName>SSO Shared Service Team Engagement</fullName>
                </value>
                <value>
                    <fullName>Cloud First</fullName>
                </value>
                <value>
                    <fullName>Open Source Software (OSS)</fullName>
                </value>
                <value>
                    <fullName>Enterprise Info &amp; Data Mgt Team (EIDM)</fullName>
                </value>
                <value>
                    <fullName>Digital Services</fullName>
                </value>
                <value>
                    <fullName>Records Management</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_Description__c</fullName>
        <inlineHelpText>Use this field to provide a description of the purpose of the project.</inlineHelpText>
        <label>Project Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Project_Tier__c</fullName>
        <inlineHelpText>Project Tier is used to track projects for the Office of GSA IT.  This option is only available for the GSA IT Service / Staff Office.</inlineHelpText>
        <label>Project Tier</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Service_Staff_Office__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Tier 1</fullName>
                </value>
                <value>
                    <fullName>Tier 2</fullName>
                </value>
                <value>
                    <fullName>Tier 3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SSO_Goals_Themes__c</fullName>
        <inlineHelpText>Use this field to select goals or strategic themes defined by your Service/Staff Office for this project.</inlineHelpText>
        <label>SSO Goals / Themes</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Service_Staff_Office__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>FAS - Acquisition Excellence</fullName>
                </value>
                <value>
                    <fullName>FAS - Customer Focused Offerings</fullName>
                </value>
                <value>
                    <fullName>FAS - Environmental Sustainability</fullName>
                </value>
                <value>
                    <fullName>FAS - Workforce Excellence</fullName>
                </value>
                <value>
                    <fullName>OGP - Innovation</fullName>
                </value>
                <value>
                    <fullName>OGP - Operational Excellence</fullName>
                </value>
                <value>
                    <fullName>OGP - Customer Intimacy</fullName>
                </value>
                <value>
                    <fullName>OCIO - App Portfolio Modernization</fullName>
                </value>
                <value>
                    <fullName>OCIO - Business Capability Consulting</fullName>
                </value>
                <value>
                    <fullName>OCIO - Compliance Driven Bus. Activities</fullName>
                </value>
                <value>
                    <fullName>OCIO - Consolidate and Broaden Services</fullName>
                </value>
                <value>
                    <fullName>OCIO - Effective Bus. Line Partnership</fullName>
                </value>
                <value>
                    <fullName>OCIO - IT Service Delivery Excellence</fullName>
                </value>
                <value>
                    <fullName>OCIO - IT Service Support Excellence</fullName>
                </value>
                <value>
                    <fullName>OCIO - IT Workforce Transformation</fullName>
                </value>
                <value>
                    <fullName>OCIO - Optimized IT Portfolio</fullName>
                </value>
                <value>
                    <fullName>OCIO - Secure Access</fullName>
                </value>
                <value>
                    <fullName>OCIO - Standardized Infrastructure Env</fullName>
                </value>
                <value>
                    <fullName>OCIO - Unified Vendor Management</fullName>
                </value>
                <value>
                    <fullName>OCPO - 1800 F Milestone Met</fullName>
                </value>
                <value>
                    <fullName>OCPO - Positive Performance</fullName>
                </value>
                <value>
                    <fullName>OCPO - Learning Organization Model</fullName>
                </value>
                <value>
                    <fullName>OCPO - Employees Embrace</fullName>
                </value>
                <value>
                    <fullName>OCPO - Labor Relations</fullName>
                </value>
                <value>
                    <fullName>OCPO - CPO First for Their HR Needs</fullName>
                </value>
                <value>
                    <fullName>Viewed as experts in our roles</fullName>
                </value>
                <value>
                    <fullName>Provide superior &amp; timely comms support</fullName>
                </value>
                <value>
                    <fullName>Enhance/Strengthen Technology</fullName>
                </value>
                <value>
                    <fullName>Create streamlined, consistent processes</fullName>
                </value>
                <value>
                    <fullName>Improve internal collaboration &amp; comms</fullName>
                </value>
                <value>
                    <fullName>Deliver Business Value</fullName>
                </value>
                <value>
                    <fullName>Lead IT Innovation Across the Fed Govt</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Staff_Office__c</fullName>
        <inlineHelpText>Use this field to select the Service/Staff Office that is managing the project.</inlineHelpText>
        <label>Service/Staff Office</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AK - Office of Civil Rights</fullName>
                </value>
                <value>
                    <fullName>A - Office of the Administrator</fullName>
                </value>
                <value>
                    <fullName>B - Office of the Chief Financial Officer</fullName>
                </value>
                <value>
                    <fullName>C - Office of Human Resource Management</fullName>
                </value>
                <value>
                    <fullName>D - Office of Mission Assurance</fullName>
                </value>
                <value>
                    <fullName>E - Office of Small Business Utilization</fullName>
                </value>
                <value>
                    <fullName>G - Civilian Board of Contract Appeals</fullName>
                </value>
                <value>
                    <fullName>H - Office of Administrative Services</fullName>
                </value>
                <value>
                    <fullName>I - Office of the GSA IT</fullName>
                </value>
                <value>
                    <fullName>J - Office of the Inspector General</fullName>
                </value>
                <value>
                    <fullName>L - Office of the General Counsel</fullName>
                </value>
                <value>
                    <fullName>M - Office of Governmentwide Policy</fullName>
                </value>
                <value>
                    <fullName>P - Public Buildings Service</fullName>
                </value>
                <value>
                    <fullName>Q - Federal Acquisition Service</fullName>
                </value>
                <value>
                    <fullName>S - Office of Congressional &amp; Intergovernmental Affairs</fullName>
                </value>
                <value>
                    <fullName>T - Technology Transformation Service</fullName>
                </value>
                <value>
                    <fullName>USDA – Office of the Chief Financial Officer</fullName>
                </value>
                <value>
                    <fullName>Z - Office of Communications and Marketing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Use this field to identify the current phase of the project. The project phase should be updated as the project progresses through the project life cycle.</inlineHelpText>
        <label>Project Phase</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Concept Approval</fullName>
                </value>
                <value>
                    <fullName>Initiating</fullName>
                </value>
                <value>
                    <fullName>Planning</fullName>
                </value>
                <value>
                    <fullName>Executing</fullName>
                </value>
                <value>
                    <fullName>Design</fullName>
                </value>
                <value>
                    <fullName>Development</fullName>
                </value>
                <value>
                    <fullName>Testing</fullName>
                </value>
                <value>
                    <fullName>Deployment</fullName>
                </value>
                <value>
                    <fullName>Construction Procurement</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Close-Out</fullName>
                </value>
                <value>
                    <fullName>Close-Out/Closed</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>Project_Central</fullName>
        <active>true</active>
        <description>Full project record type with many fields to support project management.</description>
        <label>Standard Project</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestProjectTrigger.cls
/*-------------------------------------------------------------------------------------
  TestProjectTrigger.cls
  Class for testing the apex trigger on GPM_Project__c custom object
  -------------------------------------------------------------------------------------
   Author        |Date       |Version  |Description
  -------------------------------------------------------------------------------------
   Rajakumar      02/17/2015  1.0       Created.
   Rajakumar      03/18/2015  1.1       Commented code- remove the executive summary section
  -------------------------------------------------------------------------------------
  
  -------------------------------------------------------------------------------------
*/  
@isTest
private class TestProjectTrigger {
    @testSetup static void dataPrep() {
        List<GPM_Project__c> prjlist = new List<GPM_Project__c>();
        Id recTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Project_Central' AND SObjectType = 'GPM_Project__c'].Id;
        Id accountTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Account' AND SObjectType = 'Account'].Id;
        Id contTypeId = [SELECT Id FROM RecordType WHERE DeveloperName='GSA' AND SObjectType='Contact'].Id;
        Account acct = new Account(Name='GSATEST$TRIG', RecordTypeId=accountTypeId);
        insert acct;
        
        List<Contact> contacts = new List<Contact>();
        for(Integer j=0; j<2; j++) {
            Contact cont = new Contact(RecordTypeId=contTypeId, LastName='PrkPTEST'+j, Email='rp'+j+'trigtestgsa@gsa.gov');
            contacts.add(cont);
        }        
        insert contacts;
        
        for(Integer i = 0; i< 200; i++) {
            GPM_Project__c pr = new GPM_Project__c();
            pr.RecordTypeId = recTypeId;
            pr.Name = 'SmplTrig$123ABC';
            pr.Status__c = 'Concept Approval';
            pr.Project_Description__c = 'SampleDescription';
            pr.SSO_Goals_Themes__c = 'Lead IT Innovation Across the Fed Govt';
            pr.Service_Staff_Office__c = 'I - Office of the GSA IT';
            pr.OCIO_Strategic_Initiative__c = 'None';
            pr.Project_Tier__c = 'Tier 1';
            pr.Project_Manager__c = contacts[0].Id;
            pr.PMO_Lead__c = contacts[1].Id;
            prjlist.add(pr);
        }
        insert prjlist; 
        
        List<GPM_Milestone__c> milestones = new List<GPM_Milestone__c>();
        GPM_Milestone__c ms = new GPM_Milestone__c(GPM_Project__c=prjlist[0].Id, Milestone_Progress__c='Planned', Name__c ='SMStone1',
                                    Milestone_Status__c='Yellow',Planned_End_Date__c=Date.today()+15);
        milestones.add(ms);
        insert milestones;  
        System.assertEquals(true,true);   
    }
    /* 1.1 commented - begin
    @isTest static void doCountInsert() {
        List<GPM_Project__c> gpr = [SELECT Id, Project_Objective_formula__c, 
                                        SSO_Goals_Themes_formula__c, 
                                        Key_Principles_Initiatives_formula__c FROM GPM_Project__c];
        System.assertEquals(200, gpr.size());           
    }
    
    @isTest static void doValidateInsertObjective() {
        List<GPM_Project__c> gpr = [SELECT Id, Project_Description__c, Project_Objective_formula__c, 
                                        SSO_Goals_Themes__c, SSO_Goals_Themes_formula__c, 
                                        OCIO_Strategic_Initiative__c, Key_Principles_Initiatives_formula__c 
                                     FROM GPM_Project__c LIMIT 1];
        System.assertEquals(gpr[0].Project_Description__c, gpr[0].Project_Objective_formula__c);        
    }
    
    @isTest static void doValidateInsertSSOGoals() {
        List<GPM_Project__c> gpr = [SELECT Id, Project_Description__c, Project_Objective_formula__c, 
                                        SSO_Goals_Themes__c, SSO_Goals_Themes_formula__c, 
                                        OCIO_Strategic_Initiative__c, Key_Principles_Initiatives_formula__c 
                                     FROM GPM_Project__c LIMIT 1];
        System.assertEquals(gpr[0].SSO_Goals_Themes__c, gpr[0].SSO_Goals_Themes_formula__c);      
    }
    
    @isTest static void doValidateInsertKeyPrinciples() {
        List<GPM_Project__c> gpr = [SELECT Id, Project_Description__c, Project_Objective_formula__c, 
                                        SSO_Goals_Themes__c, SSO_Goals_Themes_formula__c, 
                                        OCIO_Strategic_Initiative__c, Key_Principles_Initiatives_formula__c 
                                     FROM GPM_Project__c LIMIT 1];
        System.assertEquals(gpr[0].OCIO_Strategic_Initiative__c, gpr[0].Key_Principles_Initiatives_formula__c);      
    }
    
    @isTest static void doCountUpdate() {
        List<GPM_Project__c> gprList = [SELECT Id, Project_Description__c, Project_Objective_formula__c, 
                                        SSO_Goals_Themes__c, SSO_Goals_Themes_formula__c, 
                                        OCIO_Strategic_Initiative__c, Key_Principles_Initiatives_formula__c 
                                     FROM GPM_Project__c];
        for(GPM_Project__c pr : gprList) {
            pr.SSO_Goals_Themes__c = 'Deliver Business Value';
            pr.Project_Description__c = 'SAMPLEUpdatedRecord';
            pr.OCIO_Strategic_Initiative__c = 'Open Source Software (OSS)';
        }
        update gprList;
        List<GPM_Project__c> extract = [SELECT Id, Project_Description__c, Project_Objective_formula__c, 
                                        SSO_Goals_Themes__c, SSO_Goals_Themes_formula__c, 
                                        OCIO_Strategic_Initiative__c, Key_Principles_Initiatives_formula__c 
                                     FROM GPM_Project__c];
        System.assertEquals(200, extract.size());      
    }
    
    @isTest static void doValidateUpdateObjective() {
        List<GPM_Project__c> gprList = [SELECT Id, Project_Description__c, Project_Objective_formula__c, 
                                        SSO_Goals_Themes__c, SSO_Goals_Themes_formula__c, 
                                        OCIO_Strategic_Initiative__c, Key_Principles_Initiatives_formula__c 
                                     FROM GPM_Project__c];
        for(GPM_Project__c pr : gprList) {
            pr.SSO_Goals_Themes__c = null;
            pr.Project_Description__c = 'SAMPLEUpdatedRecord';
            pr.OCIO_Strategic_Initiative__c = 'Open Source Software (OSS)';
        }
        update gprList;
        List<GPM_Project__c> gpr = [SELECT Id, Project_Description__c, Project_Objective_formula__c, 
                                        SSO_Goals_Themes__c, SSO_Goals_Themes_formula__c, 
                                        OCIO_Strategic_Initiative__c, Key_Principles_Initiatives_formula__c 
                                     FROM GPM_Project__c];
        System.assertEquals(gpr[0].Project_Description__c, gpr[0].Project_Objective_formula__c);       
    }
    
    @isTest static void doValidateUpdateSSOGoals() {
        List<GPM_Project__c> gprList = [SELECT Id, Project_Description__c, Project_Objective_formula__c, 
                                        SSO_Goals_Themes__c, SSO_Goals_Themes_formula__c, 
                                        OCIO_Strategic_Initiative__c, Key_Principles_Initiatives_formula__c 
                                     FROM GPM_Project__c];
        for(GPM_Project__c pr : gprList) {
            pr.SSO_Goals_Themes__c = 'Deliver Business Value';
            pr.Project_Description__c = 'SAMPLEUpdatedRecord';
            pr.OCIO_Strategic_Initiative__c = null;
        }
        update gprList;
        List<GPM_Project__c> gpr = [SELECT Id, Project_Description__c, Project_Objective_formula__c, 
                                        SSO_Goals_Themes__c, SSO_Goals_Themes_formula__c, 
                                        OCIO_Strategic_Initiative__c, Key_Principles_Initiatives_formula__c 
                                     FROM GPM_Project__c];
        System.assertEquals(gpr[0].SSO_Goals_Themes__c, gpr[0].SSO_Goals_Themes_formula__c);       
    }
    
    @isTest static void doValidateUpdateKeyPrinciples() {
        List<GPM_Project__c> gprList = [SELECT Id, Project_Description__c, Project_Objective_formula__c, 
                                        SSO_Goals_Themes__c, SSO_Goals_Themes_formula__c, 
                                        OCIO_Strategic_Initiative__c, Key_Principles_Initiatives_formula__c 
                                     FROM GPM_Project__c];
        for(GPM_Project__c pr : gprList) {
            pr.SSO_Goals_Themes__c = 'Deliver Business Value';
            pr.Project_Description__c = null;
            pr.OCIO_Strategic_Initiative__c = 'Open Source Software (OSS)';
        }
        update gprList;
        List<GPM_Project__c> gpr = [SELECT Id, Project_Description__c, Project_Objective_formula__c, 
                                        SSO_Goals_Themes__c, SSO_Goals_Themes_formula__c, 
                                        OCIO_Strategic_Initiative__c, Key_Principles_Initiatives_formula__c 
                                     FROM GPM_Project__c];
        System.assertEquals(gpr[0].OCIO_Strategic_Initiative__c, gpr[0].Key_Principles_Initiatives_formula__c);       
    }
    1.1 commented - end */
    @isTest static void doValidateUpdatePM() {
        List<GPM_Project__c> gprList = [SELECT Id, Project_Description__c 
                                     FROM GPM_Project__c];
        List<Contact> contList = [SELECT Id FROM Contact ORDER By CreatedDate];
        for(GPM_Project__c pr : gprList) {
            pr.Project_Manager__c = contList[1].Id;
            pr.PMO_Lead__c = null;
        }
        update gprList;
        List<GPM_Project__c> gpr = [SELECT Id, Project_Description__c, Project_Manager__c, PMO_Lead__c
                                     FROM GPM_Project__c WHERE Project_Manager__c = :contList[1].Id];
        System.assertEquals(200, gpr.size());       
    }
    
    @isTest static void doValidateUpdatePMOLead() {
        List<GPM_Project__c> gprList = [SELECT Id, Project_Description__c 
                                     FROM GPM_Project__c];
        List<Contact> contList = [SELECT Id FROM Contact ORDER By CreatedDate];
        for(GPM_Project__c pr : gprList) {
            pr.Project_Manager__c = null;
            pr.PMO_Lead__c = contList[0].Id;
        }
        update gprList;
        List<GPM_Project__c> gpr = [SELECT Id, Project_Description__c, Project_Manager__c, PMO_Lead__c
                                     FROM GPM_Project__c WHERE PMO_Lead__c = :contList[0].Id];
        System.assertEquals(200, gpr.size());       
    }
}