src/objects/IDP__c.object
<CustomObject>
    <description>This is a custom object to capture IDPs</description>
    <fields>
        <fullName>Career_Goals_Long_Run__c</fullName>
        <description>Employee&apos;s long term career goals</description>
        <inlineHelpText>Long Term Career Goals (3+ Years) - Insert your Long-Term Career Goals here (3+ Years). Avoid using the following special characters: &gt;  &lt;  &amp;  &quot;  &apos; in the text boxes.</inlineHelpText>
        <label>Long-Term Career Goals (3+ Years)</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Career_Goals_Short_Run__c</fullName>
        <description>Employee&apos;s Short term career goals</description>
        <inlineHelpText>Short Term Career Goals (1-3 Years) - Insert your Short-Term Career Goals here (1-3 Years). Avoid using the following special characters: &gt;  &lt;  &amp;  &quot;  &apos; in the text boxes.</inlineHelpText>
        <label>Short Term Career Goals (1-3 Years)</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Director__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field that manually shares the record with the employees Director</description>
        <inlineHelpText>Other Viewer - Select another individual who should be able to view your IDP</inlineHelpText>
        <label>Other Viewer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>IDP1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fiscal_Year_pick__c</fullName>
        <inlineHelpText>Fiscal Year - Select the fiscal year for the IDP</inlineHelpText>
        <label>Fiscal Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>FY 2011</fullName>
                </value>
                <value>
                    <fullName>FY 2012</fullName>
                </value>
                <value>
                    <fullName>FY 2013</fullName>
                </value>
                <value>
                    <fullName>FY 2014</fullName>
                </value>
                <value>
                    <fullName>FY 2015</fullName>
                </value>
                <value>
                    <fullName>FY 2016</fullName>
                </value>
                <value>
                    <fullName>FY 2017</fullName>
                </value>
                <value>
                    <fullName>FY 2018</fullName>
                </value>
                <value>
                    <fullName>FY 2019</fullName>
                </value>
                <value>
                    <fullName>FY 2020</fullName>
                </value>
                <value>
                    <fullName>FY 2021</fullName>
                </value>
                <value>
                    <fullName>FY 2022</fullName>
                </value>
                <value>
                    <fullName>FY 2023</fullName>
                </value>
                <value>
                    <fullName>FY 2024</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IDP_Status__c</fullName>
        <description>IDP Status</description>
        <inlineHelpText>IDP Status - This field indicates where your IDP stands (i.e. New, Supervisor Review, Needs Revision, Approved, Resubmit, Archived)</inlineHelpText>
        <label>IDP Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Supervisor Review</fullName>
                </value>
                <value>
                    <fullName>Needs Revision</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Resubmit</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup for the approving supervisor</description>
        <inlineHelpText>Supervisor - Choose your Supervisor using the lookup function.  This field will indicate who your IDP should be sent to for approval.</inlineHelpText>
        <label>Supervisor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>IDP</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Shared IDPs</label>
    <nameField>
        <displayFormat>IDP-{0000000}</displayFormat>
        <label>IDP Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shared IDPs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestRecordSharingUtil.cls
/*
    TestRecordSharingUtil.cls
    Test class for RecordSharingUtil.cls
    -------------------------------------------------------------------------------
    Author                 Date        Version      Description
    -------------------------------------------------------------------------------
    Raja Nangunoori       03/25/2014    1.0.00      Test Class for RecordSharingUtil
*/
@isTest(SeeAllData=true)
public class TestRecordSharingUtil {
    static testMethod void getSharingObj() {
            Account acc = new Account();
            acc.Name = 'Test Account';
            insert acc;
            String accId = acc.Id;
            RecordSharingUtil.getSharingObj(accId);
            system.assertEquals(true, true);
            
        }
        
    static testMethod void shareRecord() {
            String apiName;
            String recordId;
            String userId;
            String accessLevel;
            String rowCause; 
            Boolean isGroup;
            List<IDP__c> lstIDP = [SELECT Id FROM IDP__c LIMIT 1];
            List<User> lstUser = [SELECT Id FROM User WHERE IsActive = True LIMIT 1];
            String idpId = lstIDP[0].Id;
            apiName = RecordSharingUtil.getSharingObj(idpId);
            recordId = lstIDP[0].Id;
            userId = lstUser[0].Id;
            accessLevel = 'Read';
            rowCause = 'Manual';
            isGroup = false;
            List<recordSharingUtil.RecordSharingDefiniation> rs = new List<recordSharingUtil.RecordSharingDefiniation>{
                    new recordSharingUtil.RecordSharingDefiniation(recordId, userId, accessLevel, rowCause)
                };
            RecordSharingUtil.share(rs);
            system.assertEquals(true, true);
            
        }
        
        static testMethod void unshareRecord() {
            String apiName;
            String recordId;
            String userId;
            String accessLevel;
            String rowCause; 
            Boolean isGroup;
            String groupId;
            List<IDP__c> lstIDP = [SELECT Id FROM IDP__c LIMIT 1];
            List<User> lstUser = [SELECT Id FROM User WHERE IsActive = True LIMIT 1];
            List<Group> lstG = [SELECT Id FROM Group LIMIT 1];
            String idpId = lstIDP[0].Id;
            apiName = RecordSharingUtil.getSharingObj(idpId);
            recordId = lstIDP[0].Id;
            groupId = lstG[0].Id;
            accessLevel = 'Read';
            rowCause = 'Manual';            
            isGroup = true; 
            List<recordSharingUtil.RecordSharingDefiniation> rs = new List<recordSharingUtil.RecordSharingDefiniation>{
                    new recordSharingUtil.RecordSharingDefiniation(recordId, groupId, accessLevel, rowCause, isGroup)
                };
            RecordSharingUtil.share(rs);
            RecordSharingUtil.unshare(rs);
            system.assertEquals(true, true);
            
        }
        
        static testMethod void getAllRecords() {
            List<IDP__c> lstIDP = [SELECT Id FROM IDP__c LIMIT 1];
            RecordSharingUtil.getAllUsers(lstIDP[0].Id);
            system.assertEquals(true, true);
        }       
                
        static testMethod void getUsersByRowCause() {           
            IDP__c idp1 = new IDP__c();
        idp1.Fiscal_Year_pick__c = 'FY 2014';
        idp1.IDP_Status__c = 'New';
        idp1.Supervisor__c = UserInfo.getUserId();
        idp1.Director__c = UserInfo.getUserId();
        idp1.Career_Goals_Long_Run__c = 'T';
        idp1.Career_Goals_Short_Run__c = 'T';
        insert idp1;            
        RecordSharingUtil.getUsersByRowCause(idp1.Id, 'Supervisor_Access__c');
        system.assertEquals(true, true);
        }
}