src/objects/Integrations__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>GUID__c</fullName>
        <label>GUID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Integrations</label>
</CustomObject>

src/classes/GSA_FCIC_Datalink_Redirect_Test.cls
@isTest
public class GSA_FCIC_Datalink_Redirect_Test{

    static testMethod void validateConstructor(){
        Test.startTest();

        Integrations__c datalinkIntegration = new Integrations__c();
        datalinkIntegration.Name = 'Datalink';
        datalinkIntegration.GUID__C = '123';
        datalinkIntegration.Password__c = 'password';
        insert datalinkIntegration;

        GSA_FCIC_Datalink_Redirect button = new GSA_FCIC_Datalink_Redirect();

        System.assertNotEquals(null, button);

        Test.stopTest();
    }

}