src/objects/Items__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <inlineHelpText>No entry is required. The status is system generated depending on the review process.</inlineHelpText>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Submitted</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Under PBS Review</fullName>
                </value>
                <value>
                    <fullName>Under FAS Review</fullName>
                </value>
                <value>
                    <fullName>Under OCFO Review</fullName>
                </value>
                <value>
                    <fullName>Under SRB Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Re_Submit_Denied_Items_for_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If you are trying to Re-Submit the Denied Item, address the needed corrective action before checking the &quot;Re-Submit Denied Item for Approval&quot; checkbox.</inlineHelpText>
        <label>Re-Submit Denied Item for Approval</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Spend_Request_Number__c</fullName>
        <label>Spend Request Number</label>
        <referenceTo>Spend_Request__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Total_Cost__c</fullName>
        <description>Populated by workflow to calculate the Total of the O&amp;M and DM&amp;E fields if the request is IT Spend and Calculates the Unit Cost X Quantity if the Request is a Professional Services Request.</description>
        <label>Total Cost</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Item</label>
    <nameField>
        <displayFormat>Item-{0000}</displayFormat>
        <label>Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <recordTypes>
        <fullName>Professional_Services_Item</fullName>
        <active>true</active>
        <description>An activity providing management or advisory support</description>
        <label>Professional Services Item</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Spend_Request__c.object
<CustomObject>
    <fields>
        <fullName>Lock_Spend_Request__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Edits aren&apos;t allowed when locked. If you would like to unlock this request, please post a comment to the GSA Spend Chatter Group or Submit a new request.</inlineHelpText>
        <label>Locked Parent Spend Request</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Staff_Office__c</fullName>
        <label>Service/Staff Office</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AA - Office of the Administrator</fullName>
                </value>
                <value>
                    <fullName>AC - Office of the Chief of Staff</fullName>
                </value>
                <value>
                    <fullName>AD - Office of the Deputy Administrator</fullName>
                </value>
                <value>
                    <fullName>AE - Office of the Senior Counselor to the Administrator</fullName>
                </value>
                <value>
                    <fullName>AF - Office of the Assistant Administrator</fullName>
                </value>
                <value>
                    <fullName>AG - Office of the Associate Administrator</fullName>
                </value>
                <value>
                    <fullName>AK - Office of Civil Rights</fullName>
                </value>
                <value>
                    <fullName>B - Office of the Chief Financial Officer</fullName>
                </value>
                <value>
                    <fullName>C - Office of the Chief People Officer</fullName>
                </value>
                <value>
                    <fullName>D - Office of Emergency Response &amp; Recovery</fullName>
                </value>
                <value>
                    <fullName>E - Office of Small Business Utilization</fullName>
                </value>
                <value>
                    <fullName>G - Civilan Board of Contract Appeals</fullName>
                </value>
                <value>
                    <fullName>H - Office of Administrative Services</fullName>
                </value>
                <value>
                    <fullName>I - GSA IT</fullName>
                </value>
                <value>
                    <fullName>J - Office of the Inspector General</fullName>
                </value>
                <value>
                    <fullName>L - Office of General Counsel</fullName>
                </value>
                <value>
                    <fullName>M - Office of Governmentwide Policy</fullName>
                </value>
                <value>
                    <fullName>MV-Office of the Chief Acquisition Office</fullName>
                </value>
                <value>
                    <fullName>P - Public Buildings Service</fullName>
                </value>
                <value>
                    <fullName>Q - Federal Acquisition Service</fullName>
                </value>
                <value>
                    <fullName>R - Office of Performance Improvement</fullName>
                </value>
                <value>
                    <fullName>S - Office of Congressional &amp; Intergovernmental Affairs</fullName>
                </value>
                <value>
                    <fullName>WA - Office of the Regional Administrator</fullName>
                </value>
                <value>
                    <fullName>X - Office of Citizen Services &amp; Innovative Technologies</fullName>
                </value>
                <value>
                    <fullName>Z - Office of Communications and Marketing</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submit_for_Approval_Date__c</fullName>
        <description>When &quot;Submit for Approval&quot; button is clicked, &quot;Submit for Approval Date&quot; field will be filled with Today&apos;s date &amp; used in &quot;GSA Spend Daily Status Report&quot;.</description>
        <label>Submit for Approval Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Planned_Cost__c</fullName>
        <description>Used in the IT Acquisition Planning app - for use on the IT Planned Acquisitions object. To calculate the total cost of items related to the plan.</description>
        <inlineHelpText>System generated based on costs entered in line items.</inlineHelpText>
        <label>Total Planned Cost</label>
        <summarizedField>Items__c.Total_Cost__c</summarizedField>
        <summaryForeignKey>Items__c.Spend_Request_Number__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Spend Request</label>
    <nameField>
        <displayFormat>SR-{0000000000}</displayFormat>
        <label>Spend Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Spend Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SpendTrackerHelper.cls
global class SpendTrackerHelper{
  public static Id Professional_Services_Item_RecordType = [SELECT Id FROM RecordType WHERE DeveloperName = 'Professional_Services_Item' AND SObjectType = 'Items__c'].Id;
  public static List<Id> workItemIds = new List<Id>();
    
    webservice static Integer getEligibleItemsCountForApproval(Id localId){
      List<Approval.ProcessSubmitRequest> requests =  getEligibleItemsForApproval(localId, false);
      system.debug('getEligibleItemsCount : ' + requests.size());
      return requests.size();
  }
   

    webservice static void submitAllEligibleItems(Id localId)
    { 
 
         List<Spend_Request__c> parentObj = [SELECT Id,Lock_Spend_Request__c,Submit_for_Approval_Date__c,Total_Planned_Cost__c FROM Spend_Request__c WHERE Id = :localId];
 
         List<Approval.ProcessSubmitRequest> requests =  getEligibleItemsForApproval(localId, true);
                      
             system.debug('Number of items to submit: ' + requests.size());   
                List<Approval.ProcessResult> requestResult = Approval.process(requests);
            if(!requestResult.isEmpty()) {
                workItemIds = requestResult.get(0).getNewWorkitemIds();
            }
                if (!requests.isEmpty()){
                    //To bypass locked checkbox validation rule
                    parentObj[0].Lock_Spend_Request__c = false;
                    parentObj[0].Submit_for_Approval_Date__c = date.Today();
                    //Bypassing locked checkbox validation rule
                    update parentObj[0];
                    
                    //Lock the record back 
                    parentObj[0].Lock_Spend_Request__c = true;
                    update parentObj[0];
                }
    }
    
    //
    // Passing updateStatus = false will bypass programmatically updating the Item Status.
    //
    public static List<Approval.ProcessSubmitRequest> getEligibleItemsForApproval(Id localId, boolean updateStatus) {
         List<Spend_Request__c> parentList = [SELECT Id,Lock_Spend_Request__c,Submit_for_Approval_Date__c,Total_Planned_Cost__c,Service_Staff_Office__c FROM Spend_Request__c WHERE Id = :localId];
        Spend_Request__c parent = new Spend_Request__c();
        if(!parentList.isEmpty()) {
            parent = parentList.get(0);
        }
        List<Items__c> childObj = [SELECT Id,Approval_Status__c,Re_Submit_Denied_Items_for_Approval__c,Spend_Request_Number__r.Lock_Spend_Request__c,Spend_Request_Number__r.Submit_for_Approval_Date__c,Total_Cost__c,RecordTypeId FROM Items__c WHERE Spend_Request_Number__c= :localId];
        System.debug('This is child Object values' + childObj);
        List<Approval.ProcessSubmitRequest> requests = new List<Approval.ProcessSubmitRequest> ();
        List<Items__c> eligibleItems = new List<Items__c>();
        System.debug('Total_Planned_Cost__c : ' + parent.Total_Planned_Cost__c );
        for(Items__c co : childObj){
           if((co.Approval_Status__c=='Not Submitted')|| (co.Approval_Status__c=='Denied'&& co.Re_Submit_Denied_Items_for_Approval__c ==True)){
               if(updateStatus && co.RecordTypeId == SpendTrackerHelper.Professional_Services_Item_RecordType
                    && parent.Total_Planned_Cost__c >= 150000 
                    ) {
                    co.Approval_Status__c = getApprovalStatus(parent, co);
               }
               eligibleItems.add(co);
           }
        
            if(updateStatus && co.RecordTypeId == SpendTrackerHelper.Professional_Services_Item_RecordType
                    && parent.Total_Planned_Cost__c >= 150000) {
                upsert(eligibleItems);
            }
        }
        
        for(Items__c co : eligibleItems){
                Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
                req1.setComments('Submitted for Approval');
                //req1.setObjectId(childObj[i].Id);
                req1.setObjectId(co.Id);
                requests.add(req1);
                
                    system.debug('Elegible IDs: ' + req1 );
          }
          return  requests;
    }
    
    public static String getApprovalStatus(Spend_Request__c parent, Items__c item){
        String status = '';
        System.debug('SSO : ' + parent.Service_Staff_Office__c);
        System.debug('Total_Cost__c : ' + item.Total_Cost__c);
        if(parent.Total_Planned_Cost__c >= 150000 
            && item.Total_Cost__c < 150000 
           && item.RecordTypeId == SpendTrackerHelper.Professional_Services_Item_RecordType) {
               status = 'Under SRB Review';
        }
        else if(item.Total_Cost__c >= 150000) {
            if(parent.Service_Staff_Office__c == 'P - Public Buildings Service') {
                status = 'Under PBS Review';
            }
            else if(parent.Service_Staff_Office__c == 'Q - Federal Acquisition Service') {
                status = 'Under FAS Review';
                
            } 
            else if(parent.Service_Staff_Office__c == 'B - Office of the Chief Financial Officer') {
                status = 'Under OCFO Review';
            }
            else {
                status = 'Under SRB Review';
            }
        }
        
        return status;
        
    }
    webservice static Integer getEligibleItemsCountForRecall(Id localId){
      List<Approval.ProcessWorkitemRequest> requests =  getEligibleItemsForRecall(localId, false);
      system.debug('getEligibleItemsCount : ' + requests.size());
      return requests.size();
  }

    
    webservice static void recallAllEligibleItems(Id localId)
    { 
        System.debug('==> ' + localId);
 
         List<Approval.ProcessWorkitemRequest > requests =  getEligibleItemsForRecall(localId, true);
             System.debug('==> requests ==> ' + requests);         
        if(!requests.isEmpty()) {
                List<Approval.ProcessResult> requestResult = Approval.process(requests);
        }
            resetAllItems(localId);
                
    }
    
    public static void resetAllItems(Id localId) {
        List<Items__c> cObj = New List<Items__c>();
        List<Items__c> childObj = [SELECT Id,Approval_Status__c,Re_Submit_Denied_Items_for_Approval__c,Spend_Request_Number__r.Lock_Spend_Request__c,Spend_Request_Number__r.Submit_for_Approval_Date__c,Total_Cost__c,RecordTypeId FROM Items__c WHERE Spend_Request_Number__c= :localId];
        for(Items__c co : childObj){
            co.Approval_Status__c = 'Not Submitted';
            cObj.add(co);
        }
        update cObj;
        List<Spend_Request__c> parentObj = [SELECT Id,Lock_Spend_Request__c,Submit_for_Approval_Date__c,Total_Planned_Cost__c FROM Spend_Request__c WHERE Id = :localId LIMIT 1];
        for (Spend_Request__c spendRequest : parentObj ){
            spendRequest.Lock_Spend_Request__c = false;
        }
        
           Update parentObj;
    }
    
    //
    // Passing updateStatus = false will bypass programmatically updating the Item Status.
    //
    public static List<Approval.ProcessWorkitemRequest> getEligibleItemsForRecall(Id localId, boolean updateStatus) {
         List<Spend_Request__c> parentList = [SELECT Id,Lock_Spend_Request__c,Submit_for_Approval_Date__c,Total_Planned_Cost__c, Service_Staff_Office__c FROM Spend_Request__c WHERE Id = :localId];
        Spend_Request__c parent = new Spend_Request__c();
        if(!parentList.isEmpty()) {
            parent = parentList.get(0);
        }
        List<Items__c> childObj = [SELECT Id,Approval_Status__c,Re_Submit_Denied_Items_for_Approval__c,Spend_Request_Number__r.Lock_Spend_Request__c,Spend_Request_Number__r.Submit_for_Approval_Date__c,Total_Cost__c,RecordTypeId FROM Items__c WHERE Spend_Request_Number__c= :localId];
        System.debug('This is child Object values' + childObj);
        List<Approval.ProcessWorkitemRequest> requests = new List<Approval.ProcessWorkitemRequest> ();
        List<Items__c> eligibleItemsForRecall = new List<Items__c>();
        for(Items__c co : childObj){
           if((co.Approval_Status__c=='Under SRB Review')|| (co.Approval_Status__c=='Under OCFO Review')||(co.Approval_Status__c=='Under FAS Review')||(co.Approval_Status__c=='Under PBS Review')){
               
               eligibleItemsForRecall.add(co);
           }
        
            }
        
        for(Items__c co : eligibleItemsForRecall){
        List<ProcessInstanceWorkitem> piwi = [SELECT Id, ProcessInstanceId, ProcessInstance.TargetObjectId FROM ProcessInstanceWorkitem WHERE ProcessInstance.TargetObjectId =: co.Id];
            Approval.ProcessWorkitemRequest req1 = new Approval.ProcessWorkitemRequest();   
            //Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
            if(updateStatus){
            req1.setComments('Recall Approval');
            req1.setAction('Removed');        
            req1.setWorkitemId(piwi.get(0).Id);
   
            
                
             }  
                requests.add(req1);
                
                    system.debug('Elegible IDs: ' + req1 );
          }
          return  requests;
    }
    
  }