src/objects/KBSyncSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>API_Key__c</fullName>
        <label>API Key</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Create_Exception_Record__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Create Exception Record</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_Delta__c</fullName>
        <label>Date Shift</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Email_Exception__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Email Exception</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Page_Size__c</fullName>
        <label>Page Size</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>KBSyncSettings</label>
</CustomObject>

src/classes/GSA_FCIC_KDBArticles_Callout_Test.cls
@isTest
private class GSA_FCIC_KDBArticles_Callout_Test {
    
    static testMethod void testServiceFail() {
        //KBSyncSettings__c settings = KBSyncSettings__c.getValues('SyncSettings');   
        KBSyncSettings__c kbSync = new KBSyncSettings__c(Name='SyncSettings', API_Key__c= '1234',Create_Exception_Record__c= true,  Date_Delta__c = 3,Email_Exception__c = false,Page_Size__c=3);
        insert kbSync ;
        system.assert(kbSync.API_Key__c == '1234');

        Test.starttest();

        Test.setMock(HttpCalloutMock.class, new GSA_FCIC_KDBArticles_MockCallout(201,'Failure',GSA_FCIC_KDBArticles_TestGenerator.getPublishedResponse(100),null));
        DateTime todayDate = DateTime.newInstance(System.Date.today(), System.Time.newInstance(0, 0, 0, 0));
        GSA_FCIC_KDBArticles_Callout.getArticleDetails_WS(todayDate, null, new Map<String, String>{'Key1' => 'Value1'}, new List<String>{'Field1', 'Field2'}, (Integer)kbSync.Page_Size__c,0, null, false);
        GSA_FCIC_KDBArticles_Callout.getArticleDetails_WS(todayDate, null, null, null, (Integer)kbSync.Page_Size__c,0, null, false);

        Test.stoptest();

        System.assertEquals(1,1); // Fake assert TODO: come back
    }
    
}