src/objects/OCIO_Title_VI_Review__c.object
<CustomObject>
    <description>This object is for the Office of Civil Rights - Title VI application and used to track Title VI Compliance data reviews.</description>
    <fields>
        <fullName>OCR_Title_VI_Submission__c</fullName>
        <label>Title VI Submission</label>
        <referenceTo>OCIO_Title_VI_Submission__c</referenceTo>
        <relationshipLabel>Title VI Reviews</relationshipLabel>
        <relationshipName>Title_VI_Reviews</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Title VI Review</label>
    <nameField>
        <displayFormat>TVIR-{0000000}</displayFormat>
        <label>Title VI Review ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Title VI Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TitleVIReviewChildController.cls
/*
	TitleVIReviewChildController
	In between page that checks to see if there are associated children, if not then creates one
	and then redirects.
	-------------------------------------------------------------------
	Author                 Date        Version  Description
	-------------------------------------------------------------------
	Damien Phillippi       11/22/2011  1.00     Creation
	Damien Phillippi       12/20/2011  1.01     Moving DML from an action method in order to prevent XSRF issues.
*/
public with sharing class TitleVIReviewChildController
{
	private Id parentId;
	public TitleVIReviewChildController()
	{
		parentId = ApexPages.currentPage().getParameters().get('id');
	}
	
	public PageReference redirect()
	{
		createReview();
		return new PageReference('/apex/TitleVIReview?id=' + parentId);
	}
	
	private void createReview()
	{
		if ([SELECT Id FROM OCIO_Title_VI_Review__c WHERE OCR_Title_VI_Submission__c =: parentId].size() == 0)
		{
			//Any additional fields that need populated would go here.
			OCIO_Title_VI_Review__c newReview = new OCIO_Title_VI_Review__c();
			newReview.OCR_Title_VI_Submission__c = parentId;
			insert newReview;
		}
	}	
}