src/objects/OCIO_Title_VI_Review__c.object
<CustomObject>
    <description>This object is for the Office of Civil Rights - Title VI application and used to track Title VI Compliance data reviews.</description>
    <fields>
        <fullName>OCR_Title_VI_Submission__c</fullName>
        <label>Title VI Submission</label>
        <referenceTo>OCIO_Title_VI_Submission__c</referenceTo>
        <relationshipLabel>Title VI Reviews</relationshipLabel>
        <relationshipName>Title_VI_Reviews</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Title VI Review</label>
    <nameField>
        <displayFormat>TVIR-{0000000}</displayFormat>
        <label>Title VI Review ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Title VI Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OCIO_Title_VI_Submission__c.object
<CustomObject>
    <description>This object is for the Office of Civil Rights - Title VI application and used to track Title VI Compliance Submissions submitted by the donees.</description>
    <label>Title VI Submission</label>
    <nameField>
        <displayFormat>TVIS-{0000000}</displayFormat>
        <label>Title VI Submission ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Title VI Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TitleVIReviewChildControllerTest.cls
@isTest(seeAlldata=false)
private class TitleVIReviewChildControllerTest {
    @testSetUp
    static void createtestdata(){
        OCIO_Title_VI_Submission__c submission = new OCIO_Title_VI_Submission__c();
        insert submission;
        system.assertNotEquals(null, submission.id);
        
    }
    static testMethod void testController()
    {
        OCIO_Title_VI_Submission__c rec = [select id from OCIO_Title_VI_Submission__c limit 1];
        ApexPages.currentPage().getParameters().put('id', rec.Id);
        test.startTest();
        TitleVIReviewChildController controller = new TitleVIReviewChildController();
        controller.redirect();      
        System.assert([SELECT Id FROM OCIO_Title_VI_Review__c WHERE OCR_Title_VI_Submission__c =: rec.Id].size() != 0);
        test.stopTest();
    }

}