src/objects/OCIO_Ethics_450_Form_Review__c.object
<CustomObject>
    <description>This object is used by the Office of General Counsel (OGC) to track the review of employee&apos;s 450 forms.</description>
    <fields>
        <fullName>Candidate_New_Employee_Name__c</fullName>
        <label>Candidate/ New Employee Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>The subject line and the body of the email from a Ethics 450 form submission will be populated here.</inlineHelpText>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Ethics450_Candidate_NewEmployee_s_Email__c</fullName>
        <label>Candidate/ New Employee Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Ethics450_Region__c</fullName>
        <description>This field captures the Region of the employee.</description>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>NCR</fullName>
                </value>
                <value>
                    <fullName>Central Office -FAS</fullName>
                </value>
                <value>
                    <fullName>Central Office -PBS</fullName>
                </value>
                <value>
                    <fullName>Central Office -Staff Offices</fullName>
                </value>
                <value>
                    <fullName>Civilian Board of Contract Appeals (G)</fullName>
                </value>
                <value>
                    <fullName>Office of Inspector General (IG)</fullName>
                </value>
                <value>
                    <fullName>LG</fullName>
                </value>
                <value>
                    <fullName>LP</fullName>
                </value>
                <value>
                    <fullName>LR</fullName>
                </value>
                <value>
                    <fullName>Regional Attorney (L)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ethics450_Run_Workflow__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is set to true via code to kick off workflow rules only after attachment is associated to the Ethics 450 record</description>
        <label>Run Workflow</label>
        <type>Checkbox</type>
    </fields>
    <label>Ethics 450 Form Review</label>
    <nameField>
        <displayFormat>Review-{00000}</displayFormat>
        <label>Ethics 450 Form Review  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ethics 450 Form Reviews</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/EmailToEthics450.cls
/*
    EmailToEthics450.cls
    Inbound email handler class that will accept an email and create an associated ethics 450 form
    -------------------------------------------------------------------
    Author                 Date        Version  Description
    -------------------------------------------------------------------
    Sathish Durairaj       12/20/2011  1.0.0    Creation
    Damien Phillippi       12/22/2011  1.1.0    Creating Ethics object from Email
*/
global class EmailToEthics450 implements Messaging.InboundEmailHandler
{
    global Messaging.InboundEmailResult handleInboundEmail(Messaging.InboundEmail email, Messaging.InboundEnvelope envelope)
    {
        Messaging.InboundEmailResult result = new Messaging.InboundEmailresult();
        
        OCIO_Ethics_450_Form_Review__c ethicsFormReview = new OCIO_Ethics_450_Form_Review__c();
        
        ethicsFormReview.Candidate_New_Employee_Name__c = email.fromName;
        ethicsFormReview.Ethics450_Candidate_NewEmployee_s_Email__c = email.fromAddress;
        
        Schema.DescribeFieldResult fieldResult = OCIO_Ethics_450_Form_Review__c.Ethics450_Region__c.getDescribe();
        Set<String> regionValues = new Set<String>();
        for(Schema.PicklistEntry f: fieldResult.getPicklistValues())
        {
            regionValues.add(f.getLabel());
            regionValues.add(f.getValue());
        }
        
        if (regionValues.contains(email.subject)){
            ethicsFormReview.Ethics450_Region__c = email.subject;
        }
        ethicsFormReview.description__c = email.subject + '\n' + email.plainTextBody;
        
        insert ethicsFormReview;
        
        if (email.binaryAttachments != null && email.binaryAttachments.size() > 0)
        {
            for (integer i = 0 ; i < email.binaryAttachments.size() ; i++)
            {
                Attachment attachment = new Attachment();
                // attach to the newly created contact record
                attachment.ParentId = ethicsFormReview.Id;
                attachment.Name = email.binaryAttachments[i].filename;
                attachment.Body = email.binaryAttachments[i].body;
                insert attachment;
            }
        }
        
        ethicsFormReview.Ethics450_Run_Workflow__c = true;
        update ethicsFormReview;
        
        return result;
    }
}