src/objects/OrgUsersLicense__c.object
<CustomObject>
    <fields>
        <fullName>ActiveUser__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active User?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FederationID__c</fullName>
        <label>Federation ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrgFedIDKey__c</fullName>
        <externalId>true</externalId>
        <label>OrgFedIDKey</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>OrgID__c</fullName>
        <label>Org ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrgName__c</fullName>
        <label>Org. Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserID__c</fullName>
        <label>User ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserLicense__c</fullName>
        <label>User License</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Org. User  License</label>
    <nameField>
        <displayFormat>ID-{0000}</displayFormat>
        <label>Org. User License Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Org. Users License</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OrgUserLicenseTriggerServerTest.cls
@isTest
public with sharing class OrgUserLicenseTriggerServerTest {
    
    @isTest(SeeAllData=false) 
    Static void TestTriggerOrgUserLicenseTriggerServer() {
        
        OrgUsersLicense__c objOrgUser = New OrgUsersLicense__c();
        objOrgUser.ActiveUser__c = true;
        objOrgUser.FederationID__c = 'FedID';
        objOrgUser.OrgFedIDKey__c = 'OrgIDFedID';
        objOrgUser.OrgID__c = 'OrgID';
        objOrgUser.OrgName__c = 'OrgName';
        objOrgUser.UserID__c = 'UserID@test.com.EEO';
        objOrgUser.UserLicense__c = 'Salesforce';
        Insert objOrgUser;
        
        //Check if the Object record was created sucessfully
        System.Assert(objOrgUser.ID != NULL);
    }
         
}