src/objects/OrgUsersLicense__c.object
<CustomObject>
    <fields>
        <fullName>ActiveUser__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active User?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FederationID__c</fullName>
        <label>Federation ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OfficeStaffOffice__c</fullName>
        <label>Office/Staff Office</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrgFedIDKey__c</fullName>
        <externalId>true</externalId>
        <label>OrgFedIDKey</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>OrgID__c</fullName>
        <label>Org ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrgName__c</fullName>
        <label>Org. Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserID__c</fullName>
        <label>User ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserLicense__c</fullName>
        <label>User License</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Org. User  License</label>
    <nameField>
        <displayFormat>ID-{0000}</displayFormat>
        <label>Org. User License Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Org. Users License</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UpdateUserLicenseUtil.cls
public with sharing class UpdateUserLicenseUtil {
	
    @future
    public static void UpdateUserLicense (Set<Id> userIds) {
    	
    	List<OrgUsersLicense__c> UpdateLicenseObj = new List<OrgUsersLicense__c>();
    	string strFederaditionID;
    	
   		for (User objUser: [SELECT 	ID, IsActive, SAML_Federation_ID_Custom__c, Username, Profile.UserLicense.Name, MAJOR_ORG_DESCRIPTION__c 
   							FROM 	User 
   							WHERE 	ID IN :userIds]){
   			
   			OrgUsersLicense__c objUserUpdated = New OrgUsersLicense__c();
	    	objUserUpdated.ActiveUser__c = objUser.IsActive;
	    	objUserUpdated.FederationID__c = objUser.SAML_Federation_ID_Custom__c;
	    	objUserUpdated.UserID__c = objUser.Username;
	    	objUserUpdated.UserLicense__c = objUser.Profile.UserLicense.Name;
	    	objUserUpdated.OrgID__c = UserInfo.getOrganizationId();
	    	objUserUpdated.OrgName__c = UserInfo.getOrganizationName();
	    	objUserUpdated.OrgFedIDKey__c = (UserInfo.getOrganizationId() + objUser.SAML_Federation_ID_Custom__c);
	    	objUserUpdated.OfficeStaffOffice__c = objUser.MAJOR_ORG_DESCRIPTION__c;
	    	If (objUser.SAML_Federation_ID_Custom__c != Null && (objUser.Profile.UserLicense.Name == 'Salesforce' ||  objUser.Profile.UserLicense.Name == 'Salesforce Platform' ||  objUser.Profile.UserLicense.Name == 'Chatter Free')){
	    		UpdateLicenseObj.Add(objUserUpdated);
	    	}
        }
     	
     	Database.UpsertResult[] upsertResults = Database.upsert(UpdateLicenseObj, OrgUsersLicense__c.OrgFedIDKey__c, false);
    }	
    
}