src/objects/PublicCalendarList__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>need to access the public calendar via API</description>
    <fields>
        <fullName>CalendarID__c</fullName>
        <label>CalendarID</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>PublicCalendarList</label>
</CustomObject>

src/classes/IMTCalendarController.cls
/*-------------------------------------------------------------------------------
  IMTCalendarController.cls
  Class for displaying the IMT Calendar in visualforce page
  -------------------------------------------------------------------------------
  Author                |Date       |Version  |Description
  -------------------------------------------------------------------------------
  Rajakumar              08/13/2013  1.0       Initial version
  -------------------------------------------------------------------------------
*/  
public with sharing class IMTCalendarController {
    public String calendarId {get; set; }
    
    public IMTCalendarController () {
        calendarId = PublicCalendarList__c.getValues('IMTCalendar').CalendarID__c;    
    }
}