src/objects/RAP_Survey__c.object
<CustomObject>
    <description>Assign Survey to Users, and capture their responses from them.</description>
    <fields>
        <fullName>CAV_Date__c</fullName>
        <label>CAV Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Experience_for_Job_Performance__c</fullName>
        <inlineHelpText>This experience will help me perform my job responsibilities better</inlineHelpText>
        <label>4. Experience for Job Performance</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Strongly Disagree</fullName>
                </value>
                <value>
                    <fullName>Disagree</fullName>
                </value>
                <value>
                    <fullName>Neutral</fullName>
                </value>
                <value>
                    <fullName>Strongly Agree</fullName>
                </value>
                <value>
                    <fullName>Agree</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Future_RAP_Opportunities__c</fullName>
        <inlineHelpText>Would you participate in future Ride Along Opportunities?</inlineHelpText>
        <label>5. Future RAP Opportunities</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IOA_Information_Seeking__c</fullName>
        <inlineHelpText>What information would you like the IOA to seek during the visit you feel would be valuable to your business decisions?</inlineHelpText>
        <label>7. IOA Information Seeking</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IOA_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>IOA Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RAP_Surveys1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IOA_Role__c</fullName>
        <inlineHelpText>I better understand the role of IOA as a result of the Ride Along</inlineHelpText>
        <label>3. IOA Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Strongly Disagree</fullName>
                </value>
                <value>
                    <fullName>Disagree</fullName>
                </value>
                <value>
                    <fullName>Neutral</fullName>
                </value>
                <value>
                    <fullName>Strongly Agree</fullName>
                </value>
                <value>
                    <fullName>Agree</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Interest_in_other_Opportunity__c</fullName>
        <inlineHelpText>Would you be interested in other opportunities to meet with IOAs and ACOs?</inlineHelpText>
        <label>8. Interest in other Opportunity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Locations_and_Logistics__c</fullName>
        <inlineHelpText>Locations and other logistical details were worked out prior to the visit</inlineHelpText>
        <label>2. Locations and Logistics</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Strongly Disagree</fullName>
                </value>
                <value>
                    <fullName>Disagree</fullName>
                </value>
                <value>
                    <fullName>Neutral</fullName>
                </value>
                <value>
                    <fullName>Strongly Agree</fullName>
                </value>
                <value>
                    <fullName>Agree</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PCO_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PCO Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RAP_Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pre_trip_meeting__c</fullName>
        <inlineHelpText>I found the Pre Trip business meeting helpful and informative</inlineHelpText>
        <label>1. Pre trip meeting</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Strongly Disagree</fullName>
                </value>
                <value>
                    <fullName>Disagree</fullName>
                </value>
                <value>
                    <fullName>Neutral</fullName>
                </value>
                <value>
                    <fullName>Strongly Agree</fullName>
                </value>
                <value>
                    <fullName>Agree</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Recommend_RAP__c</fullName>
        <inlineHelpText>Would you recommend a Ride Along to your colleagues</inlineHelpText>
        <label>6. Recommend RAP</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SIOA_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SIOA Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RAP_Surveys2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Why__c</fullName>
        <label>Why?</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Why_do_you__c</fullName>
        <label>Why..?</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>RAP Survey</label>
    <nameField>
        <displayFormat>RAP - {00000}</displayFormat>
        <label>RAP ID Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RAP Surveys</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestRAPSurveyTrigger.cls
@isTest
public class TestRAPSurveyTrigger{
    private static testMethod void unitTest(){
        List<user> usList = [select id from user where profileId =: '00e30000001zjtP' limit 3];
        
        RAP_Survey__c rs = new RAP_Survey__c();
        rs.PCO_Name__c = usList[0].id;
        rs.SIOA_Name__c = usList[1].id; 
        rs.IOA_Name__c = usList[2].id;
        rs.CAV_Date__c = system.toDay()-1;
        insert rs;
        
        SubmitRecord.processDetails(rs.id);
        
        rs.Pre_trip_meeting__c = 'Test';
        rs.Locations_and_Logistics__c = 'Test1';
        rs.IOA_Role__c = 'Test2';
        rs.Experience_for_Job_Performance__c = 'Test3';
        rs.Future_RAP_Opportunities__c = 'Test4';
        rs.Recommend_RAP__c = 'Test5';
        rs.IOA_Information_Seeking__c = 'Test6';
        rs.Interest_in_other_Opportunity__c = 'Test7';
        rs.Why__c = 'Test8';
        rs.Why_do_you__c = 'Test9';
        update rs;
 
        SubmitRecord.processDetails(rs.id);
        
        
        System.assertEquals(true,true);
        }
}