src/objects/RAP_Survey__c.object
<CustomObject>
    <description>Assign Survey to Users, and capture their responses from them.</description>
    <fields>
        <fullName>Experience_for_Job_Performance__c</fullName>
        <inlineHelpText>This experience will help me perform my job responsibilities better</inlineHelpText>
        <label>4. Experience for Job Performance</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Strongly Disagree</fullName>
                </value>
                <value>
                    <fullName>Disagree</fullName>
                </value>
                <value>
                    <fullName>Neutral</fullName>
                </value>
                <value>
                    <fullName>Strongly Agree</fullName>
                </value>
                <value>
                    <fullName>Agree</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Future_RAP_Opportunities__c</fullName>
        <inlineHelpText>Would you participate in future Ride Along Opportunities?</inlineHelpText>
        <label>5. Future RAP Opportunities</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IOA_Information_Seeking__c</fullName>
        <inlineHelpText>What information would you like the IOA to seek during the visit you feel would be valuable to your business decisions?</inlineHelpText>
        <label>7. IOA Information Seeking</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IOA_Role__c</fullName>
        <inlineHelpText>I better understand the role of IOA as a result of the Ride Along</inlineHelpText>
        <label>3. IOA Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Strongly Disagree</fullName>
                </value>
                <value>
                    <fullName>Disagree</fullName>
                </value>
                <value>
                    <fullName>Neutral</fullName>
                </value>
                <value>
                    <fullName>Strongly Agree</fullName>
                </value>
                <value>
                    <fullName>Agree</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Interest_in_other_Opportunity__c</fullName>
        <inlineHelpText>Would you be interested in other opportunities to meet with IOAs and ACOs?</inlineHelpText>
        <label>8. Interest in other Opportunity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Locations_and_Logistics__c</fullName>
        <inlineHelpText>Locations and other logistical details were worked out prior to the visit</inlineHelpText>
        <label>2. Locations and Logistics</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Strongly Disagree</fullName>
                </value>
                <value>
                    <fullName>Disagree</fullName>
                </value>
                <value>
                    <fullName>Neutral</fullName>
                </value>
                <value>
                    <fullName>Strongly Agree</fullName>
                </value>
                <value>
                    <fullName>Agree</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PCO_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PCO Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RAP_Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pre_trip_meeting__c</fullName>
        <inlineHelpText>I found the Pre Trip business meeting helpful and informative</inlineHelpText>
        <label>1. Pre trip meeting</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Strongly Disagree</fullName>
                </value>
                <value>
                    <fullName>Disagree</fullName>
                </value>
                <value>
                    <fullName>Neutral</fullName>
                </value>
                <value>
                    <fullName>Strongly Agree</fullName>
                </value>
                <value>
                    <fullName>Agree</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Recommend_RAP__c</fullName>
        <inlineHelpText>Would you recommend a Ride Along to your colleagues</inlineHelpText>
        <label>6. Recommend RAP</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Survey_Completed_Date__c</fullName>
        <label>Survey Completed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Survey_Status__c</fullName>
        <label>Survey Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Why__c</fullName>
        <label>Why?</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Why_do_you__c</fullName>
        <label>Why..?</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>RAP Survey</label>
    <nameField>
        <displayFormat>RAP - {00000}</displayFormat>
        <label>RAP ID Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RAP Surveys</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SubmitRecord.cls
global class SubmitRecord{
    webservice static String processDetails(string Id){
       
        RAP_Survey__c  ops = [Select Id,Survey_Status__c,Pre_trip_meeting__c,Interest_in_other_Opportunity__c,Why__c,Why_do_you__c,
                              IOA_Information_Seeking__c,Recommend_RAP__c,Experience_for_Job_Performance__c,Future_RAP_Opportunities__c,
                              Locations_and_Logistics__c,IOA_Role__c,Survey_Completed_Date__c,RecordTypeId, PCO_Name__c from RAP_Survey__c
                              where Id =:Id ];
        ops.Survey_Status__c = 'Completed';
        ops.Survey_Completed_Date__c = system.today();
        try{
            if(ops.Pre_trip_meeting__c != null && ops.Locations_and_Logistics__c != null && ops.IOA_Role__c != null && ops.Experience_for_Job_Performance__c != null 
               && ops.Future_RAP_Opportunities__c != null && ops.Recommend_RAP__c != null && ops.IOA_Information_Seeking__c != null && ops.Interest_in_other_Opportunity__c != null
               && ops.Why__c != null && ops.Why_do_you__c != null){
                update ops;
                            
                RAP_Survey__Share PCOShr = new RAP_Survey__Share();
                PCOShr.ParentID = ops.Id;
                PCOShr.UserOrGroupId = ops.PCO_Name__c;
                PCOShr.AccessLevel= 'Read';
                PCOShr.RowCause = Schema.RAP_Survey__Share.RowCause.PCO_Name__c;
                Database.SaveResult sr = Database.insert(PCOShr, false); 
            }else{
                return 'Please fill all the answers and submit';  
            }} catch(Exception e){ return e.getMessage();} 
        return 'yes';
    } 
}