src/objects/Request_Tracker__c.object
<CustomObject>
    <description>The Request Tracker a custom object is created to track multiple type of request some with approval process and other with simple workflow.
This object also has an affiliated object called &quot;Survey&quot; which is used with one of Record Type called &quot;Communication Job Log &quot;</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>At Printer</fullName>
                </value>
                <value>
                    <fullName>At Contractor</fullName>
                </value>
                <value>
                    <fullName>Waiting on Client</fullName>
                </value>
                <value>
                    <fullName>Waiting on Vendor</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Closed - Duplicate</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
                <value>
                    <fullName>Pending Supervisor Review</fullName>
                </value>
                <value>
                    <fullName>Approved by Supervisor</fullName>
                </value>
                <value>
                    <fullName>Rejected by Supervisor</fullName>
                </value>
                <value>
                    <fullName>Pending Final Review</fullName>
                </value>
                <value>
                    <fullName>Approved by Final Team</fullName>
                </value>
                <value>
                    <fullName>Rejected by Final Team</fullName>
                </value>
                <value>
                    <fullName>Assigned For Work Completion</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Alternative product found</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Closed: Resolved</fullName>
                </value>
                <value>
                    <fullName>Closed: Unresolved</fullName>
                </value>
                <value>
                    <fullName>Closed: Duplicate</fullName>
                </value>
                <value>
                    <fullName>Closed: Litigation</fullName>
                </value>
                <value>
                    <fullName>Forwarded to OIG For Review</fullName>
                </value>
                <value>
                    <fullName>Tasked to Personnel Office For Review</fullName>
                </value>
                <value>
                    <fullName>Tasked To a Region/Office For Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Request Tracker</label>
    <nameField>
        <displayFormat>{YYYY}-{0000}</displayFormat>
        <label>Request Tracker Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request Tracker</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/RT_CancelRequestQuickActionController.cls
public class RT_CancelRequestQuickActionController {
	@AuraEnabled
	Public static Boolean UpdateRequestTrackerStatusField(String Id){
        Boolean buttonEnableDisable=False ;
        String UserId=UserInfo.getUserId();
        Request_Tracker__c requestRecord=[Select id,OwnerId,Request_Tracker__c.Name from Request_Tracker__c where id=:Id];
        system.debug('The Request Tracker value is------------------>'+ requestRecord);   
        User u = [select id,Name,FirstName,LastName from User where Id=:requestRecord.OwnerId];
        string OwnerName=u.Name;
        system.debug('**'+OwnerName);
        if(UserId==requestRecord.OwnerId){
            requestRecord.Status__c='Cancelled';
            Update requestRecord;
        }
        else {
            buttonEnableDisable= True;
        }
    	return buttonEnableDisable;
	}
    
    @AuraEnabled
    Public static string ReturnOwnerName(String Id){
        Request_Tracker__c requestRecord=[Select id,OwnerId,Owner.Name from Request_Tracker__c where id=:Id];
        return requestRecord.Owner.Name;
    }
}