src/objects/Request_Tracker__c.object
<CustomObject>
    <description>The Request Tracker a custom object is created to track multiple type of request some with approval process and other with simple workflow.
This object also has an affiliated object called &quot;Survey&quot; which is used with one of Record Type called &quot;Communication Job Log &quot;</description>
    <fields>
        <fullName>ITS_Alternative_Available__c</fullName>
        <description>If there is an existing product in the GSA IT Standards profile that can be used instead of the proposed software, select Yes.   Otherwise, select No to request a new standard.</description>
        <inlineHelpText>If there is an existing product in the GSA IT Standards profile that can be used instead of the proposed software, select Yes.   Otherwise, select No to request a new standard.</inlineHelpText>
        <label>Alternative Available</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ITS_Product_Name__c</fullName>
        <description>Name of the requested product/standard.</description>
        <label>Product Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ITS_Product_Version__c</fullName>
        <description>Requested product/software version number.</description>
        <label>Product Version</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ITS_ServiceNow_Ticket__c</fullName>
        <description>ServiceNow ticket number that initiated this request.  (Service Catalog Request Number.)</description>
        <inlineHelpText>Please enter the Service Catalog Request Number from ServiceNow.</inlineHelpText>
        <label>ServiceNow Ticket #</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OCIO_Requester__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>For an internal GSA requester, use the &quot;User&quot; value in the drop-down (most common).  For an external customer requester, use &quot;Customer Portal User&quot;.</inlineHelpText>
        <label>Requester</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Request_Tracker1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Request Tracker</label>
    <nameField>
        <displayFormat>{YYYY}-{0000}</displayFormat>
        <label>Request Tracker Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request Tracker</pluralLabel>
    <recordTypes>
        <fullName>IT_Standard_Request</fullName>
        <active>true</active>
        <description>To create a request for a change to the IT Standards Profile.</description>
        <label>IT Standard Request</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/RT_CancelRequestQAControllerTest.cls
@isTest 
public class RT_CancelRequestQAControllerTest {
    static testMethod void testcase1(){
        Request_Tracker__c ITSreq = new Request_Tracker__c();
        Id recTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'IT_Standard_Request' 
                         AND SObjectType = 'Request_Tracker__c'].Id;
        User usr = [SELECT Id, Name FROM User WHERE IsActive = true AND Id =:UserInfo.getUserId()];
        ITSreq.RecordTypeId = recTypeId;
        ITSreq.ITS_Product_Name__c = 'Multifunction Digital Copier/Printer';
        ITSreq.ITS_Product_Version__c = 'MPC3002G';
        ITSreq.OCIO_Requester__c = usr.Id;
        ITSreq.ITS_ServiceNow_Ticket__c	= 'RITM0011111';
        ITSreq.ITS_Alternative_Available__c	= 'No';
        try {insert ITSreq;}
        catch(DMLException e) {
            System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION', e.getDmlStatusCode(0));
        }  
        RT_CancelRequestQuickActionController.UpdateRequestTrackerStatusField(ITSreq.Id);  
        RT_CancelRequestQuickActionController.ReturnOwnerName(ITSreq.Id);
    }
}