src/objects/Survey__c.object
<CustomObject>
    <description>Collects results for the Survey type.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Surveys</relationshipLabel>
        <relationshipName>Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <displayFormat>SUR-{0000}</displayFormat>
        <label>Survey ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <recordTypes>
        <fullName>Employee_Email_Survey</fullName>
        <active>true</active>
        <label>Employee Email Survey</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SurveyController.cls
public with sharing class SurveyController{
    public static void updateOwner(List<Survey__c> lstSurvey){
    Set<Id> conId = new Set<Id>();
    String recId;
        for(Survey__c s : lstSurvey){
            conId.add(s.Contact__c);
            recId = s.RecordTypeId;
        }
     RecordType rId = [SELECT Id, DeveloperName, Name FROM RecordType WHERE Id =: recId LIMIT 1];
         if(rId.DeveloperName == 'Employee_Email_Survey'){
                 Contact c = [SELECT Id, Email FROM Contact WHERE Id IN :conId LIMIT 1];     
                 User u = [SELECT Id FROM User WHERE Email =: c.Email LIMIT 1];
        for(Survey__c sur : lstSurvey){
            sur.OwnerId = u.Id;
        }
             }
    }
}