src/objects/Suspension_and_Debarment_Case__c.object
<CustomObject>
    <fields>
        <fullName>Case_Closed__c</fullName>
        <description>Yes or No picklist based on if the record is closed.</description>
        <label>Case Closed</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case_Name__c</fullName>
        <description>Case name of Suspension and Debarment case</description>
        <externalId>true</externalId>
        <inlineHelpText>Case name of Suspension and Debarment case</inlineHelpText>
        <label>Case Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Status__c</fullName>
        <defaultValue>&quot;Pending Initial IO Review&quot;</defaultValue>
        <description>A cases status field that is updated by the approval process.</description>
        <inlineHelpText>A cases status field that is updated by the approval process.</inlineHelpText>
        <label>Case Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comments_for_SDO__c</fullName>
        <description>Comments for SDO</description>
        <inlineHelpText>Comments for SDO</inlineHelpText>
        <label>Comments for SDO</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Debarment_Decision_Date__c</fullName>
        <description>Debarment Date</description>
        <inlineHelpText>Debarment Date</inlineHelpText>
        <label>Debarment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>General_Case_Information__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>General Case Information</label>
        <referenceTo>Suspension_and_Debarment_Case__c</referenceTo>
        <relationshipName>Suspension_and_Debarment_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Integrity_Officer_Name__c</fullName>
        <formula>Integrity_Officer__r.FirstName &amp; &quot; &quot; &amp;  Integrity_Officer__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Integrity Officer Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Proposal_for_Debarment_Date__c</fullName>
        <description>Proposal for Debarment Date</description>
        <inlineHelpText>Proposal for Debarment Date</inlineHelpText>
        <label>Proposal for Debarment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Respondent_Name__c</fullName>
        <description>The primary business or individual respondent for the case.</description>
        <inlineHelpText>The primary business or individual respondent for the case. Please format individual respondent names as Last name, First name, MI.</inlineHelpText>
        <label>Respondent Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Suspension_Date__c</fullName>
        <description>Suspension Date</description>
        <inlineHelpText>Suspension Date</inlineHelpText>
        <label>Suspension Date</label>
        <type>Date</type>
    </fields>
    <label>Suspension and Debarment Record</label>
    <nameField>
        <displayFormat>SD-{00000000}</displayFormat>
        <label>Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suspension and Debarment Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SDRespondentListController.cls
public with sharing class SDRespondentListController {

	public List<Suspension_and_Debarment_Case__c> respondentCases { get; set; }
	public List<RespondentLineItem> respondentLineItems { get; set; }
	public String baseURL { get; set; }

	private final Suspension_and_Debarment_Case__c SDObj;

	public SDRespondentListController(ApexPages.StandardController controller) {
		baseURL = System.URL.getSalesforceBaseUrl().toExternalForm();
		SDObj = (Suspension_and_Debarment_Case__c) controller.getRecord();
		respondentCases = [
				// any queried fields need to be added to wrapper class at the end
				SELECT 	Id
						, Name
						, Respondent_Name__c
						, Case_Closed__c
						, Suspension_Date__c
						, Proposal_for_Debarment_Date__c
						, Debarment_Decision_Date__c
						, Comments_for_SDO__c
						, Case_Status__c
						, Case_Name__c
						, Integrity_Officer_Name__c
						, OwnerId
						, Owner.Name
				FROM Suspension_and_Debarment_Case__c
				WHERE General_Case_Information__c = :SDObj.id
				ORDER BY id
		];
		respondentLineItems = populaterespondentLineItems(respondentCases);
	}

	public List<RespondentLineItem> populaterespondentLineItems(List<Suspension_and_Debarment_Case__c> sdCases){
		List<RespondentLineItem> tempRespondentLineItems = new List<RespondentLineItem>();
		for(Suspension_and_Debarment_Case__c sdCase : sdCases){
			tempRespondentLineItems.add(new RespondentLineItem(sdCase));
		}
		return tempRespondentLineItems;
	}

	public class RespondentLineItem{
		public String id { get; set; }
		public String name { get; set; }
		public String respondentName { get; set; }
		public Boolean closeCase { get; set; }
		public Date suspensionDate { get; set; }
		public Date proposalForDebarmentDate { get; set; }
		public Date debarmentDecisionDate { get; set; }
		public String commentsForSDO { get; set; }
		public String caseStatus { get; set; }
		public String ownerName { get; set; }

		public RespondentLineItem(Suspension_and_Debarment_Case__c sdCase){
			this.id = sdCase.Id;
			this.name = sdCase.Name;
			this.respondentName = sdCase.Respondent_Name__c;
			if(sdCase.Case_Closed__c == 'Yes'){
				this.closeCase = true;
			} else {
				this.closeCase = false;
			}
			this.suspensionDate = sdCase.Suspension_Date__c;
			this.proposalForDebarmentDate = sdCase.Proposal_for_Debarment_Date__c;
			this.debarmentDecisionDate = sdCase.Debarment_Decision_Date__c;
			this.commentsForSDO = sdCase.Comments_for_SDO__c;
			if(sdCase.Owner.Name == null && sdCase.OwnerId != null){
				User u = [SELECT Id, Name FROM User WHERE Id = :sdCase.OwnerId];
				this.caseStatus = addOwnerToStatus(sdCase.Case_Status__c, u.Name);
			} else {
				this.caseStatus = addOwnerToStatus(sdCase.Case_Status__c, sdCase.Owner.Name);
			}
			this.ownerName = sdCase.Owner.Name;
		}

		private String addOwnerToStatus(String oldStatus, String owner){
			if(owner == null) return oldStatus;
			if(oldStatus.contains('IO')){
				return oldStatus.replace('IO', owner);
			} else if (oldStatus.contains('Integrity Officer')){
				return oldStatus.replace('Integrity Officer', owner);
			} else {
				return oldStatus;
			}
		}
	}
}