src/objects/Suspension_and_Debarment_Case__c.object
<CustomObject>
    <fields>
        <fullName>ACA_Decision_Date__c</fullName>
        <description>Administrative Compliance Agreement Date</description>
        <inlineHelpText>Administrative Compliance Agreement Date</inlineHelpText>
        <label>ACA Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Basis__c</fullName>
        <description>Basis</description>
        <inlineHelpText>Basis</inlineHelpText>
        <label>Basis</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Primary Basis Judicial</fullName>
                </value>
                <value>
                    <fullName>Fact-Based</fullName>
                </value>
                <value>
                    <fullName>Voluntary Disclosure</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Business__c</fullName>
        <description>Business or individual, if Business, categorize if it is a small business or not</description>
        <inlineHelpText>Business or individual, if Business, categorize if it is a small business or not</inlineHelpText>
        <label>Business / Individual</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Individual</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Business (Small)</fullName>
                </value>
                <value>
                    <fullName>Business (Not Small)</fullName>
                </value>
                <value>
                    <fullName>Business (Unknown)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case_Name__c</fullName>
        <description>Case name of Suspension and Debarment case</description>
        <externalId>true</externalId>
        <inlineHelpText>Case name of Suspension and Debarment case</inlineHelpText>
        <label>Case Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_Record_Complete__c</fullName>
        <description>Date Record Complete</description>
        <label>Date Record Complete</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_of_Transfer__c</fullName>
        <description>Date case was transferred to Lead Agency</description>
        <inlineHelpText>Date case was transferred to Lead Agency</inlineHelpText>
        <label>Date of Transfer</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Debarment_ACA_Termination_Date__c</fullName>
        <description>Debarment/ACA Termination Date</description>
        <inlineHelpText>Debarment/ACA Termination Date</inlineHelpText>
        <label>Debarment/ACA Termination Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Debarment_Decision_Date__c</fullName>
        <description>Debarment Date</description>
        <inlineHelpText>Debarment Date</inlineHelpText>
        <label>Debarment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Direct_Imputed_Affiliated__c</fullName>
        <description>Direct Imputed Affiliated</description>
        <inlineHelpText>Direct Imputed Affiliated</inlineHelpText>
        <label>Direct / Imputed / Affiliated</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>Imputed</fullName>
                </value>
                <value>
                    <fullName>Affliated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>General_Case_Information__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>General Case Information</label>
        <referenceTo>Suspension_and_Debarment_Case__c</referenceTo>
        <relationshipName>Suspension_and_Debarment_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grounds_for_Debarment_Other__c</fullName>
        <description>Field to capture comments if Other is selected for Grounds for Debarment</description>
        <inlineHelpText>Comma separated Other Ground(s) for Debarment</inlineHelpText>
        <label>Other Ground(s) for Debarment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Grounds_for_Debarment__c</fullName>
        <description>Grounds for Debarment</description>
        <inlineHelpText>Comma separated Other Ground(s) for Debarment.</inlineHelpText>
        <label>Grounds for Debarment</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bribery / Conspiracy to Commit Bribery</fullName>
                    <color>#0B6FCE</color>
                </value>
                <value>
                    <fullName>Conspiracy, General</fullName>
                    <color>#CC0000</color>
                </value>
                <value>
                    <fullName>False Statements</fullName>
                    <color>#006600</color>
                </value>
                <value>
                    <fullName>Falsification or Destruction of Records</fullName>
                    <color>#A845DC</color>
                </value>
                <value>
                    <fullName>Fraud</fullName>
                    <color>#33CCFF</color>
                </value>
                <value>
                    <fullName>Hobbs Act Conspiracy</fullName>
                    <color>#E27001</color>
                </value>
                <value>
                    <fullName>Mail Fraud</fullName>
                    <color>#66FFFF</color>
                </value>
                <value>
                    <fullName>Tax Violations</fullName>
                    <color>#66FF99</color>
                </value>
                <value>
                    <fullName>Theft</fullName>
                    <color>#FF99FF</color>
                </value>
                <value>
                    <fullName>Other</fullName>
                    <color>#FF6666</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Hearing_Date__c</fullName>
        <description>Hearing Date</description>
        <inlineHelpText>Hearing Date</inlineHelpText>
        <label>Hearing Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lead_Agency_Action_Date__c</fullName>
        <description>The Lead Agency action date for each action taken for each respondnet in the case.</description>
        <inlineHelpText>The Lead Agency action date for each action taken for each respondnet in the case.</inlineHelpText>
        <label>Lead Agency Action Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lead_Agency_Action__c</fullName>
        <description>The Lead Agency actions taken for each respondent in the case.</description>
        <inlineHelpText>The Lead Agency actions taken for each respondent in the case.</inlineHelpText>
        <label>Lead Agency Action</label>
        <length>256</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Lead_Agency_Determination_Necessary__c</fullName>
        <description>Lead Agency Determination Necessary</description>
        <inlineHelpText>Is Lead Agency Determination Necessary?</inlineHelpText>
        <label>Lead Agency Determination Necessary</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lead_Agency__c</fullName>
        <description>The Lead Agency for the Case.</description>
        <inlineHelpText>The Lead Agency for the Case.</inlineHelpText>
        <label>Lead Agency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Agency for International Development</fullName>
                </value>
                <value>
                    <fullName>Agriculture</fullName>
                </value>
                <value>
                    <fullName>Commerce</fullName>
                </value>
                <value>
                    <fullName>Defense, Air Force</fullName>
                </value>
                <value>
                    <fullName>Defense, Army</fullName>
                </value>
                <value>
                    <fullName>Defense, Defense Logistics Agency</fullName>
                </value>
                <value>
                    <fullName>Defense, Navy</fullName>
                </value>
                <value>
                    <fullName>Education</fullName>
                </value>
                <value>
                    <fullName>Energy</fullName>
                </value>
                <value>
                    <fullName>Environmental Protection Agency</fullName>
                </value>
                <value>
                    <fullName>General Services Administration</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Health and Human Services</fullName>
                </value>
                <value>
                    <fullName>Homeland Security</fullName>
                </value>
                <value>
                    <fullName>Homeland Security, Immigration and Customs Enforcement</fullName>
                </value>
                <value>
                    <fullName>Housing and Urban Development</fullName>
                </value>
                <value>
                    <fullName>Interior</fullName>
                </value>
                <value>
                    <fullName>Justice</fullName>
                </value>
                <value>
                    <fullName>Labor</fullName>
                </value>
                <value>
                    <fullName>National Aeronautics and Space Administration</fullName>
                </value>
                <value>
                    <fullName>National Science Foundation</fullName>
                </value>
                <value>
                    <fullName>Nuclear Regulatory Commission</fullName>
                </value>
                <value>
                    <fullName>Office of Personnel Management</fullName>
                </value>
                <value>
                    <fullName>Small Business Administration</fullName>
                </value>
                <value>
                    <fullName>Social Security Administration</fullName>
                </value>
                <value>
                    <fullName>State</fullName>
                </value>
                <value>
                    <fullName>Transportation</fullName>
                </value>
                <value>
                    <fullName>Treasury</fullName>
                </value>
                <value>
                    <fullName>Veterans Affairs</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>No_Action_Decision_Date__c</fullName>
        <description>No Action Date</description>
        <inlineHelpText>No Action Date</inlineHelpText>
        <label>No Action Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Other_Hearing_Dates__c</fullName>
        <description>Comma separated Other Hearing Dates in mm/dd/yyyy format.</description>
        <inlineHelpText>Comma separated Other Hearing Dates in mm/dd/yyyy format.</inlineHelpText>
        <label>Other Hearing Dates</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Proposal_for_Debarment_Date__c</fullName>
        <description>Proposal for Debarment Date</description>
        <inlineHelpText>Proposal for Debarment Date</inlineHelpText>
        <label>Proposal for Debarment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Request_for_Information_Date__c</fullName>
        <description>Request for Information Date</description>
        <inlineHelpText>Request for Information Date</inlineHelpText>
        <label>Request for Information Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Respondent_Name__c</fullName>
        <description>The primary business or individual respondent for the case.</description>
        <inlineHelpText>The primary business or individual respondent for the case. Please format individual respondent names as Last name, First name, MI.</inlineHelpText>
        <label>Respondent Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SDO_Received_Date__c</fullName>
        <description>Date recommendation was received by SDO</description>
        <inlineHelpText>Date recommendation was received by SDO</inlineHelpText>
        <label>Date Received by SDO</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Show_Cause_Letter_Date__c</fullName>
        <description>Show Cause Letter Date</description>
        <inlineHelpText>Show Cause Letter Date</inlineHelpText>
        <label>Show Cause Letter Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Suspension_Date__c</fullName>
        <description>Suspension Date</description>
        <inlineHelpText>Suspension Date</inlineHelpText>
        <label>Suspension Date</label>
        <type>Date</type>
    </fields>
    <label>Suspension and Debarment Record</label>
    <nameField>
        <displayFormat>SD-{00000000}</displayFormat>
        <label>Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suspension and Debarment Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SDSuspensionDebarmentTriggerTest.cls
@isTest
public with sharing class SDSuspensionDebarmentTriggerTest {

	public testMethod static void testOwnerChange_AdminChangesOwner_OwnerChangeSuccessful(){
		Schema.DescribeSObjectResult cfrSchema = Schema.SObjectType.Suspension_and_Debarment_Case__c;
		Map<String, Schema.RecordTypeInfo> SDTypeInfo = cfrSchema.getRecordTypeInfosByName();

		Suspension_and_Debarment_Case__c SDC = new Suspension_and_Debarment_Case__c(
				id = null,
				recordtypeid = SDTypeInfo.get('Suspension and Debarment Case').getRecordTypeId()
		);

		Suspension_and_Debarment_Case__c SDC_RL = new Suspension_and_Debarment_Case__c();
		ApexPages.StandardController ctrl = new ApexPages.StandardController(SDC_RL);

		SDC.Case_Name__c = 'New Test Case';

		Date RecDate = date.newinstance(2015, 22, 15);
		Date TransDate = date.newinstance(2016, 1, 11);

		SDC.Date_Record_Complete__c= Date.today();
		SDC.SDO_Received_Date__c = RecDate;
		SDC.Basis__c = 'Primary Basis Judicial';
		SDC.Direct_Imputed_Affiliated__c = 'Direct';
		SDC.Lead_Agency_Determination_Necessary__c = 'Yes' ;
		SDC.Lead_Agency__c = 'Test Agency';
		SDC.Date_of_Transfer__c = TransDate;

		insert SDC;

		Suspension_and_Debarment_Case__c Respins = new Suspension_and_Debarment_Case__c(
				id = null,
				recordtypeid = SDTypeInfo.get('Suspension and Debarment Respondent').getRecordTypeId()
		);

		Respins.General_Case_Information__c = SDC.id;
		Respins.Respondent_Name__c = 'Smith, John';
		Respins.Business__c = 'Individual';

		Date Date1 = date.newinstance(2015, 12, 11);
		Date Date3 = date.newinstance(2016, 2, 24);

		Respins.Lead_Agency_Action__c = 'Create';
		Respins.Lead_Agency_Action_Date__c = Date1;
		Respins.ACA_Decision_Date__c = Date1;
		Respins.Debarment_ACA_Termination_Date__c = Date3;
		Respins.Request_for_Information_Date__c = Date3;
		Respins.Show_Cause_Letter_Date__c = Date3;
		Respins.Suspension_Date__c = Date3;
		Respins.Proposal_for_Debarment_Date__c = Date3;
		Respins.Hearing_Date__c = Date3;
		Respins.Other_Hearing_Dates__c = '1/1/2014,1/1/2016';
		Respins.Debarment_ACA_Termination_Date__c = Date3;
		Respins.Debarment_Decision_Date__c = Date3;
		Respins.No_Action_Decision_Date__c = Date3;
		Respins.ACA_Decision_Date__c = Date3;
		Respins.Grounds_for_Debarment__c = 'Other;Theft';
		Respins.Grounds_for_Debarment_Other__c = 'Something';

		insert Respins;

		Suspension_and_Debarment_Case__c sdCase = [SELECT Id, OwnerId, Owner.Name FROM Suspension_and_Debarment_Case__c WHERE Id = :Respins.Id];

		Id adminProfileId = [SELECT Id FROM Profile WHERE Name = 'GSA System Administrator'].Id;
		User otherAdmin = [SELECT Id FROM User WHERE ProfileId = :adminProfileId AND IsActive = true AND Id != :UserInfo.getUserId() LIMIT 1];

		System.runAs(otherAdmin){
			sdCase.OwnerId = otherAdmin.Id;
			update sdCase;
		}

		System.assertEquals(sdCase.OwnerId, otherAdmin.Id);
	}

}