src/objects/TSS_Action_Item__c.object
<CustomObject>
    <description>This is created for TSS Application - Action Items</description>
    <fields>
        <fullName>Estimated_Completion_Date__c</fullName>
        <label>Estimated Completion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Extent_of_Issue__c</fullName>
        <label>Extent of Issue</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Building</fullName>
                </value>
                <value>
                    <fullName>Tenant(Agency)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Issue_Description__c</fullName>
        <label>Issue Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Location_Code_Plus__c</fullName>
        <formula>TSS_Result_Action_Plan__r.Location_Code_Plus__c</formula>
        <label>Location Code Plus</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Category__c</fullName>
        <label>Service Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Quality of Cleanliness</fullName>
                </value>
                <value>
                    <fullName>Condition of Facility (functional, repairs needed)</fullName>
                </value>
                <value>
                    <fullName>Personal Workspace</fullName>
                </value>
                <value>
                    <fullName>Elevators</fullName>
                </value>
                <value>
                    <fullName>Know who to call on Building issues</fullName>
                </value>
                <value>
                    <fullName>Overall Satisfaction</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TSS_Result_Action_Plan__c</fullName>
        <label>TSS Result and Action Plan</label>
        <referenceTo>TSS_Result_Action_Plan__c</referenceTo>
        <relationshipLabel>TSS Action Items</relationshipLabel>
        <relationshipName>TSS_Action_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>TSS Action Item</label>
    <nameField>
        <label>TSS Action Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TSS Action Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TSS_Result_Action_Plan__c.object
<CustomObject>
    <description>This is created for TSS Application - Consolidated object for Building, Survey Results, Action Plan</description>
    <fields>
        <fullName>Building_Address__c</fullName>
        <label>Building Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Building_Name__c</fullName>
        <label>Building Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Office__c</fullName>
        <label>Field Office</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fiscal_Year__c</fullName>
        <label>Fiscal Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>FY14</fullName>
                </value>
                <value>
                    <fullName>FY15</fullName>
                </value>
                <value>
                    <fullName>FY16</fullName>
                </value>
                <value>
                    <fullName>FY17</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Location_Code_Plus__c</fullName>
        <label>Location Code Plus</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Occupancy__c</fullName>
        <label>Occupancy</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Property_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TSS_Result_Action_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property_Status__c</fullName>
        <label>Property Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Leased</fullName>
                </value>
                <value>
                    <fullName>Owned</fullName>
                </value>
                <value>
                    <fullName>Postal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Center__c</fullName>
        <label>Service Center</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supervisor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TSS_Result_Action_Plans1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TSS Result and Action Plan</label>
    <nameField>
        <label>TSS Result and Action Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TSS Results and Action Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestTSSActionItemTrigger.cls
/*-------------------------------------------------------------------------------------
  TestTSSActionItemTrigger.cls
  Class for testing the apex trigger on TSS_Action_Item__c custom object
  -------------------------------------------------------------------------------------
   Author                |Date       |Version  |Description
  -------------------------------------------------------------------------------------
   Rajakumar              11/05/2014  1.0       Created.
   
  -------------------------------------------------------------------------------------
  
  -------------------------------------------------------------------------------------
*/  
@isTest
private class TestTSSActionItemTrigger {
    
    @isTest
    static void doInsert() {
        List<TSS_Result_Action_Plan__c> acplist = new List<TSS_Result_Action_Plan__c>();
        List<TSS_Action_Item__c> ailist = new List<TSS_Action_Item__c>();
        /*
        List<User> users = [SELECT Id FROM User WHERE IsActive = true AND ProfileId IN 
                            (SELECT Id FROM Profile WHERE Name = 'GSA Standard Platform User') LIMIT 3];
        Id apUser1Id = users[0].Id;
        Id apUser2Id = users[1].Id;
        Id apUser3Id = users[2].Id;
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()]; 
        */
        List<User> admusers = [SELECT Id FROM User WHERE IsActive = true AND ProfileId IN 
                            (SELECT Id FROM Profile WHERE Name = 'GSA System Administrator') 
                            AND Id = :UserInfo.getUserId() LIMIT 1];
        Set<Id> recIds = new Set<Id>();                   
        for(Integer i=0;i<1;i++) {
            String acpname = 'AITRGI' + String.valueOf(i);
            acplist.add(new TSS_Result_Action_Plan__c(Name=acpname,
                        Building_Address__c='ABC',
                        Building_Name__c='ABC',
                        City__c='Washington',
                        Field_Office__c='CO',
                        Fiscal_Year__c='FY14',
                        Location_Code_Plus__c=acpname,
                        Occupancy__c=2000,
                        Property_Manager__c=admusers[0].Id,
                        Property_Status__c='Leased',
                        Region__c='CO',
                        Service_Center__c='CO',
                        State__c='D.C.',
                        Supervisor__c=admusers[0].Id));
        }
        insert acplist;
        ailist.add(new TSS_Action_Item__c(Name='TSAITEM',
                   Status__c='Cancelled',
                   Estimated_Completion_Date__c=Date.today()+5,
                   Extent_of_Issue__c='Building',
                   Service_Category__c='Elevators',
                   TSS_Result_Action_Plan__c=acplist[0].Id,
                   Issue_Description__c='SAMPLETRIG'));
        try {
            insert ailist;
        }
        catch (DmlException e) {
            System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION', e.getDmlStatusCode(0));
        }
    }   
    
    @isTest
    static void doUpdate() {
        List<TSS_Result_Action_Plan__c> acplist = new List<TSS_Result_Action_Plan__c>();
        List<TSS_Action_Item__c> ailist = new List<TSS_Action_Item__c>();
        /*
        List<User> users = [SELECT Id FROM User WHERE IsActive = true AND ProfileId IN 
                            (SELECT Id FROM Profile WHERE Name = 'GSA Standard Platform User') LIMIT 3];
        Id apUser1Id = users[0].Id;
        Id apUser2Id = users[1].Id;
        Id apUser3Id = users[2].Id;
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()]; 
        */
        List<User> admusers = [SELECT Id FROM User WHERE IsActive = true AND ProfileId IN 
                            (SELECT Id FROM Profile WHERE Name = 'GSA System Administrator') 
                            AND Id = :UserInfo.getUserId() LIMIT 1];
        Set<Id> recIds = new Set<Id>();                   
        for(Integer i=0;i<1;i++) {
            String acpname = 'AITRGU' + String.valueOf(i);
            acplist.add(new TSS_Result_Action_Plan__c(Name=acpname,
                        Building_Address__c='ABC',
                        Building_Name__c='ABC',
                        City__c='Washington',
                        Field_Office__c='CO',
                        Fiscal_Year__c='FY14',
                        Location_Code_Plus__c=acpname,
                        Occupancy__c=2000,
                        Property_Manager__c=admusers[0].Id,
                        Property_Status__c='Leased',
                        Region__c='CO',
                        Service_Center__c='CO',
                        State__c='D.C.',
                        Supervisor__c=admusers[0].Id));
        }
        insert acplist;
        ailist.add(new TSS_Action_Item__c(Name='TSAITEM',
                   Status__c='In Progress',
                   Estimated_Completion_Date__c=Date.today()+5,
                   Extent_of_Issue__c='Building',
                   Service_Category__c='Elevators',
                   TSS_Result_Action_Plan__c=acplist[0].Id,
                   Issue_Description__c='SAMPLETRIG'));
        insert ailist;
        ailist[0].Status__c='Cancelled';
        try {
            update ailist;
        }
        catch (DmlException e) {
            System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION', e.getDmlStatusCode(0));
        }
    }
}